import sizes from '@/public/images/protect/sizes.json';
import type { FigureKey, Lang } from './types';

// Localized SVG illustrations, generated by scripts/build-protect-images.mjs
// into public/images/protect/<key>-<lang>.svg (text inside is localized).
export const FIGURES: Record<FigureKey, { alt: Record<Lang, string>; caption: Record<Lang, string> }> = {
  'car-shortfall': {
    alt: {
      en: 'Bar chart, example numbers. What a crash really cost: $48,000 in medical bills, $24,000 in lost paychecks over 6 months, plus pain and lost everyday life, which has no receipt. What was paid: $10,000 from the injured driver\'s own PIP and $0 from the other driver\'s insurance. The gap of $62,000 plus pain is what uninsured motorist coverage on your own policy can help pay, up to your limit.',
      es: 'Gráfico de barras con cifras de ejemplo. Lo que el choque costó de verdad: $48,000 en facturas médicas, $24,000 de sueldo perdido en 6 meses, más el dolor y la vida diaria perdida, que no tienen recibo. Lo que se pagó: $10,000 del PIP del propio conductor lesionado y $0 del seguro del otro conductor. Lo que falta, $62,000 más el dolor, es lo que la cobertura UM de su propia póliza puede ayudar a pagar, hasta su límite.',
      ru: 'Диаграмма с условными цифрами. Во что авария обошлась на деле: $48 000 за лечение, $24 000 потерянной зарплаты за 6 месяцев, плюс боль и потерянная обычная жизнь, на которые нет чека. Что оплачено: $10 000 по PIP самого пострадавшего и $0 от страховки виновника. Дыру в $62 000 плюс боль может закрыть покрытие UM в вашем собственном полисе, в пределах лимита.',
    },
    caption: {
      en: 'Example numbers. In Florida, a driver with only the state minimum has no insurance for the injuries they cause to others.',
      es: 'Cifras de ejemplo. En Florida, un conductor con solo el mínimo del estado no tiene seguro para las lesiones que cause a otros.',
      ru: 'Цифры условные. Во Флориде у водителя с минимальной страховкой нет покрытия травм, которые он причинил другим.',
    },
  },
  'paycheck-timeline': {
    alt: {
      en: 'Timeline, example. Day 1: the crash; you are hurt and your paycheck stops. First weeks: PIP pays 60% of lost pay and 80% of medical bills from one shared $10,000. Month 2 or 3: PIP runs out while rent, the car payment, groceries and the light bill keep coming. Month 6: Social Security disability only if the injury is expected to last a year or more, and after a 5-month wait. What can fill the gap: if the other driver had no or too little insurance, UM can pay lost pay, medical bills and pain and suffering, up to your limit.',
      es: 'Línea de tiempo de ejemplo. Día 1: el choque; usted se lesiona y su sueldo se detiene. Primeras semanas: el PIP paga el 60% del sueldo perdido y el 80% de los gastos médicos, todo de los mismos $10,000. Mes 2 o 3: se acaba el PIP y la renta, el carro, la comida y la luz siguen llegando. Mes 6: el Seguro Social por incapacidad solo si la lesión va a durar un año o más y tras 5 meses de espera. Lo que puede cubrir el hueco: si el otro conductor no tenía seguro o tenía muy poco, el UM puede pagar sueldo perdido, gastos médicos y dolor, hasta su límite.',
      ru: 'Пример на временной шкале. День 1: авария, вы травмированы, зарплата перестаёт приходить. Первые недели: PIP платит 60% потерянного дохода и 80% счетов врачей из одних и тех же $10 000. 2–3 месяц: PIP закончился, а аренда, машина, продукты и свет остались. 6 месяц: пособие Social Security по инвалидности — только если травма продлится год и дольше и после 5 месяцев ожидания. Что может закрыть дыру: если у виновника нет страховки или её мало, UM может оплатить потерянный доход, лечение, боль и страдания в пределах лимита.',
    },
    caption: {
      en: 'Example timeline. PIP numbers come from Florida law; the Social Security rules come from the SSA.',
      es: 'Línea de tiempo de ejemplo. Las cifras del PIP vienen de la ley de Florida; las reglas del Seguro Social, de la SSA.',
      ru: 'Условный пример. Цифры по PIP взяты из закона Флориды, правила Social Security — из публикации SSA.',
    },
  },
  'two-kinds-of-losses': {
    alt: {
      en: 'Two cards. Losses with a receipt: medical bills, lost paychecks, money you would have earned in the future, help at home and rides to therapy. Losses without a receipt: pain that does not go away, bad sleep and fear of driving, not being able to lift your kids, missing sports, church and family trips. UM coverage can help pay for both kinds, up to your limit.',
      es: 'Dos tarjetas. Pérdidas con recibo: facturas médicas, sueldo perdido, lo que usted iba a ganar en el futuro, ayuda en casa y viajes a terapia. Pérdidas sin recibo: dolor que no se va, mal sueño y miedo a manejar, no poder cargar a sus hijos, perderse deportes, la iglesia y los viajes en familia. El UM puede ayudar a pagar los dos tipos, hasta su límite.',
      ru: 'Две карточки. Потери с чеком: счета за лечение, потерянная зарплата, деньги, которые вы заработали бы в будущем, помощь по дому и поездки к врачу. Потери без чека: боль, которая не проходит, плохой сон и страх за рулём, невозможность поднять ребёнка, нет спорта, церкви и семейных поездок. UM может помочь оплатить оба вида потерь в пределах лимита.',
    },
    caption: {
      en: 'The law calls these "economic" and "non-economic" damages. In plain words: losses with and without a receipt.',
      es: 'La ley los llama daños "económicos" y "no económicos". En palabras simples: pérdidas con y sin recibo.',
      ru: 'В законе это называется «экономическим» и «неэкономическим» ущербом. Проще говоря — потери с чеком и без чека.',
    },
  },
  'umbrella-layers': {
    alt: {
      en: 'Diagram. An umbrella policy is an extra layer, for example $1,000,000, sitting on top of car liability (for example $100,000) and home liability (for example $300,000). Step 1: car or home insurance pays first. Step 2: the umbrella pays the rest, up to its limit. It helps protect savings, property and your future.',
      es: 'Diagrama. La póliza umbrella es una capa extra, por ejemplo de $1,000,000, encima de la responsabilidad del auto (por ejemplo $100,000) y de la casa (por ejemplo $300,000). Paso 1: primero paga el seguro de auto o casa. Paso 2: el umbrella paga el resto, hasta su límite. Ayuda a proteger ahorros, propiedades y su futuro.',
      ru: 'Схема. Зонтичный полис (umbrella) — дополнительный слой, например $1 000 000, поверх ответственности по авто (например $100 000) и по дому (например $300 000). Шаг 1: сначала платит страховка авто или дома. Шаг 2: остальное платит umbrella в пределах лимита. Он помогает защитить сбережения, имущество и ваше будущее.',
    },
    caption: {
      en: 'Amounts are examples. Your limits and what is covered depend on your policies.',
      es: 'Los montos son ejemplos. Sus límites y lo que se cubre dependen de sus pólizas.',
      ru: 'Суммы условные. Лимиты и покрытие зависят от ваших полисов.',
    },
  },
  'limit-vs-verdict': {
    alt: {
      en: 'Grid of 85 squares, each worth $100,000. One blue square is the at-fault driver\'s $100,000 insurance limit. The other squares, in red, are the rest of an $8.47 million jury verdict. The judgment was entered against the driver for the full amount. Source: Florida Supreme Court case SC17-85 (2018).',
      es: 'Cuadrícula de 85 cuadros de $100,000 cada uno. Un cuadro azul es el límite de $100,000 del seguro del conductor culpable. Los demás, en rojo, son el resto de un veredicto de $8.47 millones. La sentencia se dictó contra el conductor por el monto total. Fuente: Corte Suprema de Florida, caso SC17-85 (2018).',
      ru: 'Сетка из 85 квадратов по $100 000. Один синий квадрат — лимит страховки виновника, $100 000. Остальные, красные, — оставшаяся часть решения присяжных на $8,47 млн. Решение суда вынесено против водителя на всю сумму. Источник: Верховный суд Флориды, дело SC17-85 (2018).',
    },
    caption: {
      en: 'Real case, public court record. The case later went to the Florida Supreme Court over how the claim was handled.',
      es: 'Caso real, registro público del tribunal. Luego llegó a la Corte Suprema de Florida por la forma en que se manejó el reclamo.',
      ru: 'Реальное дело, открытые судебные документы. Позже оно дошло до Верховного суда Флориды из-за того, как урегулировали претензию.',
    },
  },
  'home-liability': {
    alt: {
      en: 'Four tiles. Pool: a child or guest is hurt in the pool. Dog bite: your dog bites a neighbor or visitor. A guest falls: wet patio, loose step, dark stairs. Florida was number 2 in the U.S. for dog-bite claims in 2025, with an average claim of $62,375. Home liability is often $100,000 to $300,000; if a claim is bigger, the rest can fall on you. An umbrella adds a layer.',
      es: 'Cuatro recuadros. Piscina: un niño o invitado se lesiona. Mordida de perro: su perro muerde a un vecino o visita. Una caída: patio mojado, escalón flojo, poca luz. Florida fue la número 2 en EE. UU. en reclamos por mordidas de perro en 2025, con un promedio de $62,375. La responsabilidad de casa suele ser de $100,000 a $300,000; si el reclamo es mayor, el resto puede caer en usted. El umbrella agrega una capa más.',
      ru: 'Четыре плитки. Бассейн: ребёнок или гость пострадал в бассейне. Укус собаки: ваша собака укусила соседа или гостя. Гость упал: мокрая терраса, шаткая ступенька, темнота. Флорида — 2-е место в США по страховым случаям с укусами собак в 2025 году, в среднем $62 375. Лимит ответственности по дому часто от $100 000 до $300 000; если иск больше, остальное может лечь на вас. Umbrella добавляет ещё один слой.',
    },
    caption: {
      en: 'Dog-bite figures and typical limits: Insurance Information Institute (2025 data).',
      es: 'Cifras de mordidas y límites típicos: Insurance Information Institute (datos de 2025).',
      ru: 'Данные об укусах собак и типичных лимитах: Insurance Information Institute (2025).',
    },
  },
  'family-paycheck': {
    alt: {
      en: 'Diagram. One paycheck pays for the mortgage or rent, groceries and bills, childcare, kids\' education, the car payment and debts, and final expenses. If it stops forever, these bills do not. Life insurance can pay your family a lump sum to keep these going. 47% of U.S. adults say they would struggle to pay bills within 6 months of losing the main earner (LIMRA and Life Happens, 2026).',
      es: 'Diagrama. Un sueldo paga la hipoteca o renta, la comida y las cuentas, el cuidado de los niños, los estudios de los hijos, el pago del carro y las deudas, y los gastos finales. Si el sueldo se detiene para siempre, las cuentas no. El seguro de vida puede pagarle a su familia una suma para que todo siga. El 47% de los adultos en EE. UU. dice que tendría problemas para pagar sus cuentas en 6 meses si faltara quien más gana (LIMRA y Life Happens, 2026).',
      ru: 'Схема. Одна зарплата оплачивает ипотеку или аренду, продукты и счета, няню или садик, учёбу детей, машину и долги, расходы на похороны. Если зарплата пропадёт навсегда, счета останутся. Страхование жизни может выплатить семье сумму, чтобы всё это продолжалось. 47% взрослых в США говорят, что с трудом оплатили бы счета уже через 6 месяцев после потери кормильца (LIMRA и Life Happens, 2026).',
    },
    caption: {
      en: 'The 47% figure is from the 2026 Insurance Barometer by LIMRA and Life Happens.',
      es: 'La cifra del 47% es del Insurance Barometer 2026 de LIMRA y Life Happens.',
      ru: 'Цифра 47% — из исследования Insurance Barometer 2026 (LIMRA и Life Happens).',
    },
  },
  'future-paychecks': {
    alt: {
      en: 'Bar chart, example. Earning $50,000 a year adds up to $250,000 in 5 years, $500,000 in 10, $750,000 in 15, $1 million in 20 and $1.25 million in 25 years: money your family is counting on. Life insurance can replace part or all of it.',
      es: 'Gráfico de barras de ejemplo. Ganar $50,000 al año suma $250,000 en 5 años, $500,000 en 10, $750,000 en 15, $1 millón en 20 y $1.25 millones en 25 años: dinero con el que cuenta su familia. El seguro de vida puede reemplazar una parte o todo.',
      ru: 'Условная диаграмма. Доход $50 000 в год — это $250 000 за 5 лет, $500 000 за 10, $750 000 за 15, $1 млн за 20 и $1,25 млн за 25 лет. На эти деньги рассчитывает семья. Страхование жизни может заменить часть или всё.',
    },
    caption: {
      en: 'Simple math, before raises and taxes. Your numbers will be different.',
      es: 'Cuenta simple, sin aumentos ni impuestos. Sus números serán distintos.',
      ru: 'Простая арифметика, без повышений и налогов. Ваши цифры будут другими.',
    },
  },
};

export function figureSrc(key: FigureKey, lang: Lang) {
  const [w, h] = (sizes as Record<string, Record<string, number[]>>)[key][lang];
  return { src: `/images/protect/${key}-${lang}.svg`, width: w, height: h };
}
