// Business product pages (/[lang]/insurance/general-liability, business-owners-policy,
// commercial-auto, errors-omissions). The product H1 stays fixed; `h` is a
// standalone line under it, so keep it generic to all four products.
import { V, type HeroCopyPool } from './types';

export const commercial: HeroCopyPool = {
  en: [
    V('One claim shouldn’t close your doors.', 'A customer slips, a pipe bursts, a storm knocks out power. We make sure your business policy fits the risks you actually face — and help you when you file.'),
    V('You built the business. We help protect it.', 'Liability, property, business vehicles: a local agent reviews your coverage and shows you exactly where your business is exposed.'),
    V('Your business deserves an agent, not a hotline.', 'Contact us during business hours and an agent calls you back within one hour. When you have a claim, you deal with people who know your business.'),
    V('Is your business ready for hurricane season?', 'Property, business interruption, flood: send us your policy and we’ll check your coverage before the next storm does.'),
    V('Protection that grows with your business.', 'New location, new employees, new equipment? We review your policy as you grow so a gap never catches you off guard.'),
    V('Proof of insurance, without the headache.', 'Certificates, additional insureds, the limits your landlord or clients require: we handle it and explain it in plain English, Spanish or Russian.'),
    V('Small business. Big responsibilities.', 'One lawsuit can threaten everything you’ve worked for. The right liability coverage puts a wall between that risk and your business.'),
    V('Family-owned, like the businesses we protect.', 'We know what it takes to keep the lights on. More than 5,000 Florida clients count on us to explain their coverage and stand with them at claim time.'),
    V('Know what your business policy really covers.', 'Exclusions and limits hide in the fine print. We read it with you, line by line, and flag anything that could leave you paying out of pocket.'),
    V('If you had to close for a month, could you pay your people?', 'Business interruption coverage can help replace lost income while you rebuild. We’ll check whether your policy includes it and how much.'),
    V('Talk to someone who understands small business.', 'Our team of 12 speaks English, Spanish and Russian. Tell us how your business works and we’ll build protection around it.'),
    V('A claim is when you find out who your agent is.', 'We help you document the loss, understand your coverage and keep the claim moving so you can get back to work.'),
    V('Your equipment and inventory, protected.', 'Tools, stock, computers, the walk-in cooler. We make sure the things your business runs on are covered for what it would take to replace them.'),
    V('Send us your policy. We’ll find the gaps.', 'Most business owners haven’t read their policy since they bought it. A licensed local agent will review it and explain what’s missing, in plain words.'),
  ],
  es: [
    V('Un reclamo no debería cerrar su negocio.', 'Un cliente se resbala, revienta una tubería, una tormenta deja el local sin luz. Nos aseguramos de que su póliza se ajuste a los riesgos reales de su negocio y le ayudamos cuando presente un reclamo.'),
    V('Usted construyó su negocio. Nosotros le ayudamos a protegerlo.', 'Responsabilidad civil, propiedad, vehículos del negocio: un agente local revisa su cobertura y le muestra exactamente dónde está expuesto.'),
    V('Su negocio merece un agente, no una línea de espera.', 'Contáctenos en horario de oficina y un agente le devuelve la llamada en menos de una hora. Si tiene un reclamo, lo atiende gente que conoce su negocio.'),
    V('¿Su negocio está listo para la temporada de huracanes?', 'Propiedad, interrupción del negocio, inundación: envíenos su póliza y revisamos su cobertura antes de que llegue la próxima tormenta.'),
    V('Una protección que crece con su negocio.', '¿Nuevo local, nuevos empleados, equipo nuevo? Revisamos su póliza a medida que crece para que ningún hueco lo tome por sorpresa.'),
    V('Prueba de seguro, sin dolores de cabeza.', 'Certificados, asegurados adicionales, los límites que exige su arrendador o sus clientes: nos encargamos y se lo explicamos en español, inglés o ruso.'),
    V('Negocio pequeño, grandes responsabilidades.', 'Una sola demanda puede poner en riesgo todo lo que ha construido. La responsabilidad civil adecuada levanta un muro entre ese riesgo y su negocio.'),
    V('Una agencia familiar, como los negocios que protegemos.', 'Sabemos lo que cuesta mantener las luces encendidas. Más de 5,000 clientes en Florida cuentan con nosotros para entender su cobertura y tener apoyo a la hora del reclamo.'),
    V('Sepa qué cubre de verdad la póliza de su negocio.', 'Las exclusiones y los límites se esconden en la letra pequeña. La leemos con usted, línea por línea, y le señalamos lo que podría salirle de su bolsillo.'),
    V('Si tuviera que cerrar un mes, ¿podría pagarle a su gente?', 'La cobertura de interrupción del negocio puede ayudar a reponer los ingresos perdidos mientras se recupera. Revisamos si su póliza la incluye y por cuánto.'),
    V('Hable con alguien que entiende a los pequeños negocios.', 'Nuestro equipo de 12 personas habla español, inglés y ruso. Cuéntenos cómo funciona su negocio y armamos la protección a su medida.'),
    V('En un reclamo se ve quién es de verdad su agente.', 'Le ayudamos a documentar la pérdida, entender su cobertura y mantener el reclamo en marcha para que vuelva a trabajar cuanto antes.'),
    V('Su equipo y su inventario, protegidos.', 'Herramientas, mercancía, computadoras, el cuarto frío. Nos aseguramos de que lo que mueve su negocio esté cubierto por lo que costaría reponerlo.'),
    V('Envíenos su póliza. Nosotros encontramos los huecos.', 'La mayoría de los dueños de negocio no ha vuelto a leer su póliza desde que la compró. Un agente local licenciado la revisa y le explica con claridad lo que falta.'),
  ],
  ru: [
    V('Один страховой случай не должен закрыть ваш бизнес.', 'Клиент поскользнулся, прорвало трубу, шторм оставил без электричества. Проверим, что полис покрывает реальные риски вашего бизнеса, и поможем, когда придётся подавать заявление.'),
    V('Вы построили бизнес. Мы поможем его защитить.', 'Ответственность, имущество, рабочие машины — местный агент проверит покрытие и покажет, где именно ваш бизнес уязвим.'),
    V('Вашему бизнесу нужен агент, а не горячая линия.', 'Свяжитесь с нами в рабочее время — агент перезвонит в течение часа. А при страховом случае с вами будут работать люди, которые знают ваш бизнес.'),
    V('Готов ли ваш бизнес к сезону ураганов?', 'Имущество, перерыв в деятельности, наводнение — пришлите полис, и мы проверим покрытие до того, как это сделает следующий шторм.'),
    V('Защита, которая растёт вместе с бизнесом.', 'Новая точка, новые сотрудники, новое оборудование? Пересматриваем полис по мере роста, чтобы пробелы не застали вас врасплох.'),
    V('Страховой сертификат — без головной боли.', 'Сертификаты, additional insured, лимиты, которых требует арендодатель или заказчик, — всё оформим и объясним на русском, английском или испанском.'),
    V('Малый бизнес — большая ответственность.', 'Один иск может поставить под угрозу всё, что вы построили. Правильная страховка ответственности встанет стеной между этим риском и вашим бизнесом.'),
    V('Семейное агентство — как и бизнесы, которые мы защищаем.', 'Мы знаем, каково держать своё дело на плаву. Более 5 000 клиентов во Флориде рассчитывают на нас: мы объясняем покрытие и остаёмся рядом при страховом случае.'),
    V('Знайте, что на самом деле покрывает ваш полис.', 'Исключения и лимиты прячутся в мелком шрифте. Прочитаем его вместе, строчка за строчкой, и отметим всё, за что вам пришлось бы платить самим.'),
    V('Если придётся закрыться на месяц, чем платить сотрудникам?', 'Покрытие перерыва в деятельности может компенсировать потерянный доход, пока вы восстанавливаетесь. Проверим, есть ли оно в вашем полисе и на какую сумму.'),
    V('Поговорите с тем, кто понимает малый бизнес.', 'Наша команда из 12 человек говорит на русском, английском и испанском. Расскажите, как устроен ваш бизнес, — и мы выстроим защиту под него.'),
    V('Страховой случай показывает, какой у вас агент.', 'Поможем задокументировать ущерб, разобраться в покрытии и довести дело до конца, чтобы вы быстрее вернулись к работе.'),
    V('Оборудование и товар под защитой.', 'Инструменты, товарные запасы, компьютеры, холодильная камера. Проверим, что всё, на чём держится бизнес, застраховано на сумму, нужную для замены.'),
    V('Пришлите полис — мы найдём пробелы.', 'Большинство владельцев бизнеса не перечитывали полис с момента покупки. Лицензированный местный агент проверит его и простыми словами объяснит, чего не хватает.'),
  ],
};
