// Free Coverage Check landing page (/[lang]/coverage-check): `h` is the whole H1.
// Variant 0 is the page's original copy (lib/coverage-check.ts).
import { V, type HeroCopyPool } from './types';

export const coverage: HeroCopyPool = {
  en: [
    V('Free 5-Minute Coverage Check for Florida Families', 'Most people find out what their policy doesn’t cover after the accident, the storm, or the lawsuit. A licensed agent will review your auto, home, condo, business, or life coverage and show you the gaps before they cost you.'),
    V('Send us your policy. We’ll show you what it doesn’t cover.', 'A licensed local agent reviews your auto, home, condo, business or life policy and points out the gaps in plain language — before a claim does.'),
    V('Find the gaps in your coverage before a storm finds them.', 'Hurricane deductible, flood, water damage, roof limits. In five minutes we’ll tell you where your home policy leaves you exposed.'),
    V('Know what you’re covered for before you need it.', 'Most people read their policy for the first time after the accident. Let us read it with you now, for free, in English, Spanish or Russian.'),
    V('Is your family really protected? Let’s check.', 'We look at your policies together — home, car, life — and show you where one ends and the next gap begins.'),
    V('A second pair of eyes on your insurance, free.', 'No obligation, no pressure. A local agent reviews what you have and explains, line by line, what it would and wouldn’t pay for.'),
    V('Five minutes today can spare you a nightmare later.', 'A denied claim is the worst way to discover a gap. Our free coverage check shows you the weak spots while there’s still time to fix them.'),
    V('Your policy, explained by a person, not a portal.', 'Send us your declarations page and an agent will call you back within one hour during business hours to walk you through it.'),
    V('Does your insurance match the life you have now?', 'New car, new baby, new roof, new business. If your coverage hasn’t changed, it may have gaps. We’ll check it for free.'),
    V('Liability limits, deductibles, exclusions — decoded.', 'The numbers on your policy decide who pays after an accident. We’ll explain yours in plain words and flag anything that looks too thin.'),
    V('Before the next storm, check your coverage.', 'Wind and flood are two different risks, and a standard home policy doesn’t cover flood. Our free check shows you where you stand.'),
    V('Trusted by 5,000+ Florida clients. Your check is free.', 'More than 5,000 clients across Florida trust our family-owned agency. Send us your policy and we’ll show you what we’d fix, free.'),
    V('A team of 12. Three languages. One free coverage check.', 'Our team speaks English, Spanish and Russian, so you’ll understand every gap we find — and every option to close it.'),
    V('Don’t wait for a claim to learn what’s missing.', 'Send us your policy and we’ll check your coverage. It’s free, it takes five minutes, and you’ll know exactly what you have.'),
  ],
  es: [
    V('Revisión gratis de su cobertura en 5 minutos para familias de Florida', 'La mayoría de las personas descubre lo que su póliza no cubre después del accidente, la tormenta o la demanda. Un agente licenciado revisará su seguro de auto, casa, condominio, negocio o vida y le mostrará los huecos antes de que le cuesten caro.'),
    V('Envíenos su póliza. Le mostramos lo que no cubre.', 'Un agente local licenciado revisa su póliza de auto, casa, condominio, negocio o vida y le señala los huecos con palabras sencillas, antes de que lo haga un reclamo.'),
    V('Encuentre los huecos de su cobertura antes que la tormenta.', 'Deducible de huracán, inundación, daños por agua, límites del techo. En cinco minutos le decimos dónde lo deja expuesto su póliza de casa.'),
    V('Sepa qué le cubre su seguro antes de necesitarlo.', 'La mayoría lee su póliza por primera vez después del accidente. Déjenos leerla con usted ahora, gratis, en español, inglés o ruso.'),
    V('¿Su familia está protegida de verdad? Revisémoslo.', 'Revisamos juntos sus pólizas —casa, auto, vida— y le mostramos dónde termina una y dónde empieza el próximo hueco.'),
    V('Una segunda opinión sobre su seguro, gratis.', 'Sin compromiso y sin presión. Un agente local revisa lo que tiene y le explica, línea por línea, qué pagaría y qué no.'),
    V('Cinco minutos hoy pueden evitarle un mal rato mañana.', 'Un reclamo negado es la peor manera de descubrir un hueco. Nuestra revisión gratis le muestra los puntos débiles cuando todavía hay tiempo de corregirlos.'),
    V('Su póliza, explicada por una persona, no por un portal.', 'Envíenos la página de declaraciones y un agente le devuelve la llamada en menos de una hora, en horario de oficina, para explicársela.'),
    V('¿Su seguro corresponde a la vida que tiene hoy?', 'Auto nuevo, bebé, techo nuevo, negocio propio. Si su cobertura no ha cambiado, puede tener huecos. La revisamos gratis.'),
    V('Límites, deducibles, exclusiones: se lo explicamos claro.', 'Los números de su póliza deciden quién paga después de un accidente. Le explicamos los suyos con claridad y le señalamos lo que se ve demasiado corto.'),
    V('Antes de la próxima tormenta, revise su cobertura.', 'El viento y la inundación son riesgos distintos, y una póliza de casa estándar no cubre inundación. Nuestra revisión gratis le dice en qué situación está.'),
    V('Más de 5,000 clientes en Florida confían en nosotros. Su revisión es gratis.', 'Más de 5,000 clientes en toda la Florida confían en nuestra agencia familiar. Envíenos su póliza y le mostramos qué mejoraríamos, sin costo.'),
    V('Un equipo de 12, tres idiomas, una revisión gratis.', 'Nuestro equipo habla español, inglés y ruso, para que entienda cada hueco que encontremos y cada opción para cerrarlo.'),
    V('No espere a un reclamo para saber qué le falta.', 'Envíenos su póliza y revisamos su cobertura. Es gratis, toma cinco minutos y sabrá exactamente lo que tiene.'),
  ],
  ru: [
    V('Бесплатная проверка страховки за 5 минут для семей во Флориде', 'Большинство людей узнаёт, чего не покрывает их полис, уже после аварии, шторма или судебного иска. Лицензированный агент проверит вашу страховку авто, дома, кондо, бизнеса или жизни и покажет пробелы до того, как они обойдутся вам дорого.'),
    V('Пришлите полис — покажем, чего он не покрывает.', 'Лицензированный местный агент проверит вашу страховку авто, дома, кондо, бизнеса или жизни и простыми словами покажет пробелы — раньше, чем это сделает страховой случай.'),
    V('Найдите пробелы в страховке раньше урагана.', 'Ураганная франшиза, наводнение, ущерб от воды, лимиты на крышу. За пять минут скажем, где ваш полис на дом оставляет вас без защиты.'),
    V('Узнайте, что покрывает страховка, пока она не понадобилась.', 'Большинство людей впервые читают свой полис уже после аварии. Давайте прочитаем его вместе сейчас — бесплатно, на русском, английском или испанском.'),
    V('Ваша семья действительно защищена? Давайте проверим.', 'Посмотрим на все ваши полисы вместе — дом, авто, жизнь — и покажем, где заканчивается один и начинается следующий пробел.'),
    V('Свежий взгляд на вашу страховку — бесплатно.', 'Без обязательств и без давления. Местный агент проверит, что у вас есть, и по строчкам объяснит, что будет оплачено, а что нет.'),
    V('Пять минут сегодня избавят от больших проблем завтра.', 'Отказ в выплате — худший способ узнать о пробеле. Бесплатная проверка покажет слабые места, пока их ещё можно исправить.'),
    V('Ваш полис объяснит человек, а не личный кабинет.', 'Пришлите страницу деклараций — агент перезвонит в течение часа в рабочее время и всё разберёт с вами.'),
    V('Соответствует ли страховка вашей жизни сегодня?', 'Новая машина, ребёнок, новая крыша, свой бизнес. Если покрытие не менялось, в нём могут быть пробелы. Проверим бесплатно.'),
    V('Лимиты, франшизы, исключения — переведём на понятный язык.', 'Цифры в полисе решают, кто платит после аварии. Объясним ваши простыми словами и отметим всё, что выглядит слишком скромно.'),
    V('Перед следующим штормом проверьте страховку.', 'Ветер и наводнение — разные риски, и стандартный полис на дом наводнение не покрывает. Бесплатная проверка покажет, на что вы можете рассчитывать.'),
    V('Нам доверяют более 5 000 клиентов во Флориде. Проверка — бесплатно.', 'Более 5 000 клиентов по всей Флориде доверяют нашему семейному агентству. Пришлите полис — бесплатно покажем, что бы мы улучшили.'),
    V('Команда из 12 человек, три языка, одна бесплатная проверка.', 'Мы говорим на русском, английском и испанском — вы поймёте каждый найденный пробел и каждый способ его закрыть.'),
    V('Не ждите страхового случая, чтобы узнать, чего не хватает.', 'Пришлите полис — мы проверим покрытие. Это бесплатно, занимает пять минут, и вы будете точно знать, что у вас есть.'),
  ],
};
