// Home page (/en, /es, /ru): <h1>{lead}<br/><span class="accent">{h}</span></h1>
import { L, type HeroCopyPool } from './types';

export const home: HeroCopyPool = {
  en: [
    L('Your family’s safety', 'is our top priority.', 'We check your coverage for the gaps most policies hide — and when you have a claim, your own local agent is on your side. In English, Spanish or Russian.'),
    L('Insurance is a promise.', 'We make sure it’s kept.', 'When something goes wrong, you won’t be stuck with a hotline. You’ll call your agent, who knows your policy and stays with you until the claim is done.'),
    L('Find the gaps in your coverage', 'before a storm does.', 'Send us your policy and we’ll check your coverage — deductibles, flood, liability — and explain in plain words what’s missing.'),
    L('A real agent who calls back', 'within the hour.', 'Reach out during business hours and an agent calls you back within one hour. No call centers, no runaround — just people who know you.'),
    L('Family-owned. Florida-proud.', 'In your corner at claim time.', 'More than 5,000 clients across Florida trust our family-owned agency to explain their coverage honestly and stand with them when they need it.'),
    L('Protect what you’ve built', 'before you need to.', 'Your home, your car, your business, your kids’ future. We look at the whole picture and show you exactly where you’re exposed.'),
    L('Twelve people. Three languages.', 'One team on your side.', 'Our team of 12 speaks English, Spanish and Russian, so you understand every line of your policy — and every step of a claim.'),
    L('Is your policy ready', 'for hurricane season?', 'Hurricane deductibles, flood exclusions, roof limits: the fine print matters most on the worst day. Send us your policy and we’ll check your coverage.'),
    L('The right coverage starts', 'with the right questions.', 'We don’t start with a number. We ask about your family, your home and your plans, then build protection that actually fits your life.'),
    L('After an accident or a storm,', 'you won’t face it alone.', 'Your local agent helps you report the damage, understand what’s covered and keep the claim moving. That’s the part of insurance that really counts.'),
    L('Coverage that keeps up', 'with your life.', 'New baby, new car, new roof, new business? Life in Florida changes fast. We review your protection so it changes with you.'),
    L('Know exactly what you’re covered for', '— in your language.', 'Clear answers in English, Spanish or Russian from a licensed local agent. No jargon today, no surprises on the day you file a claim.'),
    L('5,000+ Florida clients', 'know their agent by name.', 'At our family-owned agency, you’re a neighbor, not a policy number. Tell us what you want to protect — it takes five minutes.'),
    L('Home, car, business and life —', 'one agent who sees it all.', 'Keep everything with one local agent who knows the whole picture and catches the gaps between your policies before they turn into bills.'),
  ],
  es: [
    L('La seguridad de su familia', 'es nuestra prioridad.', 'Revisamos su cobertura para encontrar los huecos que muchas pólizas esconden, y cuando tenga un reclamo, su propio agente local estará de su lado. En español, inglés o ruso.'),
    L('Un seguro es una promesa.', 'Nosotros hacemos que se cumpla.', 'Cuando algo sale mal, no tendrá que pelear con una línea de atención. Llamará a su agente, que conoce su póliza y lo acompaña hasta que se resuelva el reclamo.'),
    L('Encuentre los huecos de su póliza', 'antes que la tormenta.', 'Envíenos su póliza y revisamos su cobertura —deducibles, inundación, responsabilidad civil— y le explicamos con palabras sencillas lo que le falta.'),
    L('Un agente de verdad', 'que le llama en menos de una hora.', 'Comuníquese en horario de oficina y un agente le devuelve la llamada en menos de una hora. Sin centros de llamadas ni vueltas: gente que lo conoce.'),
    L('Agencia familiar, orgullo de Florida.', 'A su lado a la hora del reclamo.', 'Más de 5,000 clientes en toda la Florida confían en nuestra agencia familiar para que les expliquemos su cobertura con honestidad y los acompañemos cuando la necesitan.'),
    L('Proteja lo que ha construido', 'antes de necesitarlo.', 'Su casa, su auto, su negocio, el futuro de sus hijos. Miramos el panorama completo y le mostramos exactamente dónde está desprotegido.'),
    L('Doce personas. Tres idiomas.', 'Un equipo de su lado.', 'Nuestro equipo de 12 personas habla español, inglés y ruso, para que entienda cada línea de su póliza y cada paso de un reclamo.'),
    L('¿Su póliza está lista', 'para la temporada de huracanes?', 'Deducible de huracán, exclusiones de inundación, límites del techo: la letra pequeña importa más en el peor día. Envíenos su póliza y revisamos su cobertura.'),
    L('La cobertura correcta empieza', 'con las preguntas correctas.', 'No empezamos por un número. Le preguntamos por su familia, su casa y sus planes, y armamos una protección que de verdad se ajuste a su vida.'),
    L('Después de un accidente o una tormenta,', 'no estará solo.', 'Su agente local le ayuda a reportar los daños, entender qué está cubierto y mantener el reclamo en marcha. Esa es la parte del seguro que de verdad cuenta.'),
    L('Una cobertura que avanza', 'al ritmo de su vida.', '¿Bebé en camino, auto nuevo, techo nuevo, negocio propio? La vida en Florida cambia rápido. Revisamos su protección para que cambie con usted.'),
    L('Sepa exactamente qué le cubre su póliza', '— en su idioma.', 'Respuestas claras en español, inglés o ruso de un agente local licenciado. Sin tecnicismos hoy, sin sorpresas el día del reclamo.'),
    L('Más de 5,000 clientes en Florida', 'conocen a su agente por su nombre.', 'En nuestra agencia familiar usted es un vecino, no un número de póliza. Cuéntenos qué quiere proteger: solo toma cinco minutos.'),
    L('Casa, auto, negocio y vida:', 'un solo agente que lo ve todo.', 'Tenga todo con un agente local que conoce el panorama completo y detecta los huecos entre sus pólizas antes de que se conviertan en facturas.'),
  ],
  ru: [
    L('Безопасность вашей семьи —', 'наш главный приоритет.', 'Мы проверим ваш полис на пробелы, которые скрывают многие страховки, а при страховом случае на вашей стороне будет свой местный агент. На русском, английском или испанском.'),
    L('Страховка — это обещание.', 'Мы следим, чтобы его выполнили.', 'Если что-то случится, вам не придётся часами висеть на горячей линии. Вы позвоните своему агенту — он знает ваш полис и ведёт вас до закрытия страхового случая.'),
    L('Найдите пробелы в страховке', 'раньше, чем их найдёт ураган.', 'Пришлите нам свой полис — мы проверим покрытие: франшизы, наводнение, ответственность — и простыми словами объясним, чего не хватает.'),
    L('Живой агент перезвонит', 'в течение часа.', 'Оставьте заявку в рабочее время — агент перезвонит вам в течение часа. Никаких колл-центров и бесконечных переключений: только люди, которые вас знают.'),
    L('Семейное агентство', 'на вашей стороне при страховом случае.', 'Более 5 000 клиентов по всей Флориде доверяют нашему семейному агентству: мы честно объясняем покрытие и остаёмся рядом, когда страховка нужна.'),
    L('Защитите то, что построили,', 'пока это не понадобилось.', 'Дом, машина, бизнес, будущее детей. Мы смотрим на картину целиком и показываем, где именно вы не защищены.'),
    L('Двенадцать человек. Три языка.', 'Одна команда за вас.', 'Наша команда из 12 человек говорит на русском, английском и испанском — вы поймёте каждую строчку полиса и каждый шаг урегулирования.'),
    L('Готов ли ваш полис', 'к сезону ураганов?', 'Ураганная франшиза, исключения по наводнению, лимиты на крышу — мелкий шрифт важнее всего в самый тяжёлый день. Пришлите полис, и мы проверим ваше покрытие.'),
    L('Правильная страховка начинается', 'с правильных вопросов.', 'Мы начинаем не с цифры. Мы спрашиваем о семье, доме и планах — и подбираем защиту, которая действительно подходит вашей жизни.'),
    L('После аварии или урагана', 'вы не останетесь один на один с проблемой.', 'Местный агент поможет зафиксировать ущерб, разобраться, что покрыто, и довести страховой случай до конца. Это и есть самое важное в страховке.'),
    L('Страховка, которая успевает', 'за вашей жизнью.', 'Родился ребёнок, новая машина, новая крыша, свой бизнес? Жизнь во Флориде меняется быстро. Мы пересмотрим защиту, чтобы она менялась вместе с вами.'),
    L('Точно знайте, от чего вы застрахованы', '— на родном языке.', 'Понятные ответы на русском, английском или испанском от лицензированного местного агента. Без жаргона сегодня и без сюрпризов в день страхового случая.'),
    L('Более 5 000 клиентов во Флориде', 'знают своего агента по имени.', 'В нашем семейном агентстве вы сосед, а не номер полиса. Расскажите, что хотите защитить, — это займёт пять минут.'),
    L('Дом, авто, бизнес и жизнь —', 'один агент, который видит всё.', 'Держите всё у одного местного агента: он видит полную картину и замечает пробелы между полисами до того, как они превратятся в счета.'),
  ],
};
