// Life insurance product page (/[lang]/insurance/life-insurance). The product H1
// stays fixed; `h` is a standalone line under it.
import { V, type HeroCopyPool } from './types';

export const life: HeroCopyPool = {
  en: [
    V('Who would pay the bills if you couldn’t?', 'Life insurance can keep your family in their home and your kids’ plans on track. We help you figure out how much protection they really need.'),
    V('Love your family? Put it in writing.', 'A life policy is a promise that outlives you. A local agent helps you choose coverage in plain language, in English, Spanish or Russian.'),
    V('The mortgage doesn’t stop when a paycheck does.', 'The right amount of life insurance can pay off the house, cover everyday costs and help with college. We’ll help you find the number that fits your family.'),
    V('Protect the people who count on you.', 'Your spouse, your kids, your parents. We look at who depends on your income and build coverage around them.'),
    V('Is life insurance through work enough?', 'Coverage from your job often ends when the job does and may be far less than your family needs. We’ll check what you have and where the gap is.'),
    V('A few minutes today. Decades of protection.', 'Answer a few questions and a licensed agent will explain your options, term or permanent, without pressure and without jargon.'),
    V('Your agent will be there for your family, too.', 'When the time comes, your family won’t face the paperwork alone. We help beneficiaries through the claim in the language they’re most comfortable with.'),
    V('Growing family? Grow your protection.', 'A new baby, a new home, a new business — each is a reason to review your life coverage. We’ll show you whether it still fits.'),
    V('Term or permanent? We’ll explain it plainly.', 'Every family is different. We lay out how each type works, what it’s for and what it would mean for yours, then you decide.'),
    V('Leave your kids memories, not debts.', 'Life insurance can cover the mortgage, car loans and final expenses so the people you love can focus on each other.'),
    V('Family-owned agency. Family-first advice.', 'We protect more than 5,000 Florida clients the way we’d protect our own family: honestly, patiently and in your language.'),
    V('It’s not about dying. It’s about their living.', 'Life insurance keeps your family’s plans alive: the house, school, their everyday life. Let’s make sure they’re covered.'),
    V('Stay-at-home parents need coverage too.', 'Childcare, cooking, driving, caring for everyone — replacing that work costs real money. We’ll help you protect both parents.'),
    V('Already have a policy? Let’s make sure it still fits.', 'Send us your policy and we’ll check your coverage against your family today — not the family you had when you bought it.'),
  ],
  es: [
    V('¿Quién pagaría las cuentas si usted no pudiera?', 'El seguro de vida puede mantener a su familia en su casa y los planes de sus hijos en pie. Le ayudamos a calcular cuánta protección necesitan de verdad.'),
    V('¿Ama a su familia? Déjelo por escrito.', 'Una póliza de vida es una promesa que lo sobrevive. Un agente local le ayuda a elegir su cobertura con palabras claras, en español, inglés o ruso.'),
    V('La hipoteca no se detiene cuando falta un sueldo.', 'Un seguro de vida suficiente puede pagar la casa, cubrir los gastos del día a día y ayudar con la universidad. Le ayudamos a encontrar la cifra adecuada para su familia.'),
    V('Proteja a quienes cuentan con usted.', 'Su pareja, sus hijos, sus padres. Vemos quién depende de sus ingresos y armamos la cobertura pensando en ellos.'),
    V('¿Basta con el seguro de vida del trabajo?', 'La cobertura del empleo suele terminar cuando termina el trabajo y puede quedarse muy corta para lo que su familia necesita. Revisamos lo que tiene y dónde está el hueco.'),
    V('Unos minutos hoy. Décadas de tranquilidad.', 'Responda unas preguntas y un agente licenciado le explicará sus opciones, a término o permanente, sin presiones y sin tecnicismos.'),
    V('Su agente también estará ahí para su familia.', 'Cuando llegue el momento, su familia no enfrentará sola el papeleo. Acompañamos a los beneficiarios durante el reclamo, en el idioma en que se sientan más cómodos.'),
    V('¿Crece la familia? Que crezca su protección.', 'Un bebé, una casa nueva, un negocio propio: cada uno es una razón para revisar su seguro de vida. Le mostramos si todavía se ajusta a lo que necesita.'),
    V('¿A término o permanente? Se lo explicamos claro.', 'Cada familia es distinta. Le explicamos cómo funciona cada tipo, para qué sirve y qué significaría para la suya; luego usted decide.'),
    V('Deje a sus hijos recuerdos, no deudas.', 'El seguro de vida puede cubrir la hipoteca, los préstamos del auto y los gastos finales para que sus seres queridos puedan apoyarse entre ellos.'),
    V('Agencia familiar. La familia, primero.', 'Protegemos a más de 5,000 clientes en Florida como protegeríamos a nuestra propia familia: con honestidad, paciencia y en su idioma.'),
    V('No se trata de morir, sino de que ellos sigan adelante.', 'El seguro de vida mantiene vivos los planes de su familia: la casa, la escuela, su día a día. Asegurémonos de que estén protegidos.'),
    V('Quien se queda en casa también necesita un seguro.', 'Cuidar a los niños, cocinar, llevarlos y traerlos, atender a todos: reemplazar ese trabajo cuesta dinero de verdad. Le ayudamos a proteger a los dos padres.'),
    V('¿Ya tiene una póliza? Veamos si todavía le sirve.', 'Envíenos su póliza y revisamos su cobertura pensando en su familia de hoy, no en la que tenía cuando la compró.'),
  ],
  ru: [
    V('Кто будет платить по счетам, если вы не сможете?', 'Страхование жизни поможет семье остаться в своём доме, а детям — не отказываться от планов. Поможем понять, какая защита им действительно нужна.'),
    V('Любите семью? Закрепите это на бумаге.', 'Полис страхования жизни — это обещание, которое переживёт вас. Местный агент поможет выбрать покрытие и всё объяснит простыми словами — на русском, английском или испанском.'),
    V('Ипотека не остановится, если пропадёт зарплата.', 'Достаточная страховка жизни может закрыть ипотеку, покрыть повседневные расходы и помочь с колледжем. Поможем найти сумму, которая подходит вашей семье.'),
    V('Защитите тех, кто на вас рассчитывает.', 'Супруг, дети, родители. Посмотрим, кто зависит от вашего дохода, и выстроим покрытие вокруг них.'),
    V('Хватит ли страховки жизни от работы?', 'Страховка от работодателя обычно заканчивается вместе с работой и может оказаться намного меньше, чем нужно семье. Проверим, что у вас есть и где пробел.'),
    V('Несколько минут сегодня — защита на десятилетия.', 'Ответьте на пару вопросов, и лицензированный агент объяснит варианты — срочное или пожизненное страхование — без давления и без жаргона.'),
    V('Ваш агент будет рядом и с вашей семьёй.', 'Когда придёт время, семье не придётся разбираться с бумагами в одиночку. Мы поможем выгодоприобретателям с выплатой — на том языке, на котором им удобнее.'),
    V('Семья растёт? Пусть растёт и защита.', 'Ребёнок, новый дом, свой бизнес — каждый повод пересмотреть страхование жизни. Покажем, подходит ли вам ещё ваш полис.'),
    V('Срочное или пожизненное? Объясним просто.', 'Каждая семья своя. Расскажем, как работает каждый вариант, для чего он нужен и что он даст именно вам, — а решать будете вы.'),
    V('Оставьте детям воспоминания, а не долги.', 'Страховка жизни может покрыть ипотеку, автокредит и расходы на похороны, чтобы близкие могли поддерживать друг друга, а не искать деньги.'),
    V('Семейное агентство. Семья — на первом месте.', 'Мы защищаем более 5 000 клиентов во Флориде так, как защищали бы собственную семью: честно, терпеливо и на вашем языке.'),
    V('Это не о смерти. Это о том, как будут жить они.', 'Страхование жизни сохраняет планы вашей семьи: дом, учёбу, привычную жизнь. Давайте убедимся, что они защищены.'),
    V('Родителю, который ведёт дом, тоже нужна страховка.', 'Присмотр за детьми, готовка, поездки, забота обо всех — заменить эту работу стоит реальных денег. Поможем защитить обоих родителей.'),
    V('Полис уже есть? Проверим, подходит ли он сейчас.', 'Пришлите полис — мы проверим покрытие с учётом вашей семьи сегодня, а не той, что была, когда вы его покупали.'),
  ],
};
