import type { BlogPost } from '../types';

// Facts checked 2026-10-10 against official sources: FLHSMV Florida Insurance
// Requirements (only PIP and PDL are required to register; PDL pays for damage to
// another person's property); Florida DFS Personal Automobile Insurance Overview and
// Automobile Insurance Toolkit (definitions of comprehensive / other than collision and
// collision, actual cash value, common deductibles, lienholders, collision usually needs
// comprehensive); 2026 F.S. 627.7288 (no deductible on windshield damage under
// comprehensive), 627.744 (pre-insurance inspection for physical damage coverage),
// 319.14 ("flood vehicle" title brand and disclosure). No insurer named.
const S = {
  flhsmv: 'https://www.flhsmv.gov/insurance/',
  dfsOverview: 'https://www.myfloridacfo.com/division/consumers/understanding-insurance/personal-automobile-insurance-overview',
  dfsApply: 'https://myfloridacfo.com/docs-sf/insurance-consumer-advocate-libraries/ica-documents/applying-for-automobile-insurance-what-you-need-to-know.pdf',
  dfsToolkit: 'https://myfloridacfo.com/docs-sf/consumer-services-libraries/consumerservices-documents/understanding-coverage/consumer-guides/english%2D%2D%2Dautomobile-insurance-toolkit.pdf',
  s7288: 'https://www.flsenate.gov/Laws/Statutes/2026/627.7288',
  s744: 'https://www.flsenate.gov/Laws/Statutes/2026/627.744',
  s1914: 'https://www.flsenate.gov/Laws/Statutes/2026/319.14',
};

export const post: BlogPost = {
  slug: 'comprehensive-vs-collision-florida',
  datePublished: '2026-10-10',
  translations: {
    en: {
      title: 'Comprehensive vs. Collision in Florida: Flooded Cars, Hurricanes and Theft',
      metaTitle: 'Comprehensive vs. Collision Car Insurance in Florida | M&K Agency',
      description: 'What comprehensive car insurance covers in Florida (flood, hurricane, theft, glass) versus collision, when a lender requires them, and how deductibles work.',
      ogAlt: 'A car in floodwater next to a car with a dented bumper, with two shields labeled comprehensive and collision',
      excerpt: 'Hurricane flooding, a stolen car and a fender bender are three different claims. Here is which part of a Florida auto policy pays for each.',
      category: 'Car insurance',
      body: [
        { type: 'p', text: 'In South Florida, a car can be ruined without ever hitting anything: storm surge on US-1, a palm frond through the windshield, or a break-in overnight. Whether your own policy pays for that depends on two optional coverages that people often lump together as "full coverage": **comprehensive** and **collision**. This guide explains the difference in plain terms, using the definitions published by the Florida Department of Financial Services (DFS).' },
        { type: 'h2', text: 'What Florida actually requires' },
        { type: 'p', text: 'To register a vehicle with four or more wheels in Florida, you must carry **Personal Injury Protection (PIP)** and **Property Damage Liability (PDL)**, at least $10,000 each ([FLHSMV](' + S.flhsmv + ')). PDL pays for damage you cause to **someone else\'s** property. Neither PIP nor PDL repairs your own car. That is the job of collision and comprehensive, which state law does not require. For the details of the minimum, see our guide to [Florida minimum car insurance requirements](/en/blog/florida-minimum-car-insurance-requirements).' },
        { type: 'h2', text: 'Comprehensive ("other than collision")' },
        { type: 'p', text: 'Comprehensive is often printed on the declarations page as **Other than Collision**. According to DFS, it pays for damage to your insured vehicle from **fire, theft, windstorm, vandalism, flood, falling objects, or hitting an animal** ([DFS overview](' + S.dfsOverview + ')). For Florida drivers, that list covers most hurricane-season losses:' },
        { type: 'ul', items: [
          '**Flooded car:** water from storm surge, heavy rain or a flooded parking lot is a comprehensive loss, not collision.',
          '**Hurricane wind:** a tree, sign or roof debris falling on the car.',
          '**Theft and break-ins:** the stolen vehicle, and damage done while breaking in.',
          '**Windshield:** under Florida law, the comprehensive deductible does not apply to damage to the windshield ([s. 627.7288, F.S.](' + S.s7288 + ')).',
          '**Animals:** hitting a deer or other animal is listed under comprehensive, not collision.',
        ] },
        { type: 'h2', text: 'Collision' },
        { type: 'p', text: 'Collision pays to repair your vehicle if it **collides with another vehicle, flips over, or crashes into an object** (except animals), **regardless of fault**. If the car is a total loss, payment is typically limited to its **actual cash value**, unless you and the insurer agreed on a specific value in advance ([DFS overview](' + S.dfsOverview + ')). Typical collision claims: rear-ending someone in traffic, sliding into a pole on a wet road, or backing into a wall. If another driver caused the crash, their PDL may pay, but collision lets you repair your car through your own policy without waiting for that dispute to end.' },
        { type: 'callout', title: 'Quick test', text: 'Did the car hit something (or roll over)? That is collision. Did something happen to the car (water, wind, fire, theft, a falling object, an animal)? That is comprehensive.' },
        { type: 'h2', text: 'Flooded cars after a hurricane' },
        { type: 'p', text: 'Without comprehensive, a car destroyed by floodwater is generally not covered by your auto policy, and homeowners and flood policies usually exclude motor vehicles. If the insurer declares a water-damaged car a total loss, Florida treats it as a **"flood vehicle"**: the title must carry that brand, and a seller must disclose it in writing before a sale ([s. 319.14, F.S.](' + S.s1914 + ')). That protects you when shopping for a used car after a storm, too. Our article [When is a car totaled in Florida?](/en/blog/when-is-a-car-totaled-florida) explains total loss and actual cash value.' },
        { type: 'p', text: 'Practical tips before a storm: move the car to higher ground or a garage if you can do so safely, photograph it (inside and out, with the odometer), and keep the declarations page on your phone. After the storm, do not try to start a car that sat in water; report the claim and let the adjuster inspect it. If your home was damaged too, follow our [hurricane claim checklist](/en/blog/hurricane-claim-checklist-florida).' },
        { type: 'callout', title: 'Do not wait for the forecast', text: 'Insurers may stop accepting new coverage or changes while a hurricane threatens. Review your comprehensive coverage at the start of the season, not when the cone is already over Miami-Dade.' },
        { type: 'h2', text: 'Deductibles and how they work' },
        { type: 'p', text: 'Each coverage has its own deductible, the amount you pay before the policy pays. DFS lists $250, $500 and $1,000 as common choices ([DFS toolkit](' + S.dfsToolkit + ')). A higher deductible lowers what the policy pays on each claim, so pick an amount you could pay the day after a storm. Remember that the windshield exception above applies only to the windshield under comprehensive.' },
        { type: 'h2', text: 'Equipment, rentals and towing' },
        { type: 'p', text: 'DFS points out that, in general, only equipment **permanently attached** to the vehicle is considered in a collision claim. If you carry trade tools, have a bolted-on toolbox, a wheelchair lift or other custom features added by you or a dealer, ask your agent how they are treated before a loss ([DFS toolkit](' + S.dfsToolkit + ')). Rental car and towing coverage are separate optional coverages, not part of comprehensive or collision ([DFS consumer guide](' + S.dfsApply + ')). After a hurricane, when repair shops are backed up for weeks, it is worth knowing whether your policy includes a rental.' },
        { type: 'h2', text: 'When you need them anyway' },
        { type: 'ul', items: [
          '**Financed or leased car:** DFS notes that most lienholders require both comprehensive and collision. Dropping them can violate your loan or lease.',
          '**Collision usually comes with comprehensive:** insurers normally require comprehensive in order to buy collision, while comprehensive alone is usually available ([DFS toolkit](' + S.dfsToolkit + ')).',
          '**Inspection in Miami-Dade:** for many new policies with physical damage coverage, Florida law requires the insurer to inspect the vehicle first. Exceptions include brand-new cars bought from a dealer, cars 10 years old or older, renewals, and drivers with 2+ years of continuous physical damage coverage ([s. 627.744, F.S.](' + S.s744 + ')).',
        ] },
        { type: 'h2', text: 'Should you keep both on an older car?' },
        { type: 'p', text: 'There is no single answer. Compare the car\'s current value with your deductible, ask yourself whether you could replace the car without a claim check, and remember that in our area flood and theft risk do not go away as a car ages. Some drivers keep comprehensive and drop collision on an older, paid-off car; others keep both. A licensed agent can show you the coverage options side by side for your vehicle.' },
        { type: 'p', text: 'Want to review your coverage? See our [car insurance page for Florida City](/en/car-insurance-florida-city), [request a quote](/en/quote) or call **(305) 859-3953**. Our office at 33550 S Dixie Hwy, Suite 102, Florida City, is open Monday to Friday, 9 to 6, and Saturday by appointment.' },
      ],
      faq: [
        { q: 'Does comprehensive cover a car flooded by a hurricane?', a: 'Yes. DFS lists flood and windstorm among the losses comprehensive (other than collision) pays for, subject to your deductible and policy terms. Collision and liability-only policies do not cover flood damage to your own car.' },
        { q: 'Is comprehensive or collision required in Florida?', a: 'Not by state law. Florida requires PIP and PDL to register a car. A lender or leasing company can require comprehensive and collision as a condition of the loan or lease.' },
        { q: 'Do I pay a deductible to replace my windshield?', a: 'If you have comprehensive coverage, Florida law (s. 627.7288) says the deductible does not apply to damage to the windshield.' },
        { q: 'Is hitting a deer collision or comprehensive?', a: 'According to DFS, damage from hitting an animal falls under comprehensive, and collision excludes animals.' },
      ],
      sources: [
        { label: 'FLHSMV: Florida Insurance Requirements', url: S.flhsmv },
        { label: 'Florida DFS: Personal Automobile Insurance Overview', url: S.dfsOverview },
        { label: 'Florida DFS: Automobile Insurance Toolkit (PDF)', url: S.dfsToolkit },
        { label: 'Florida DFS Insurance Consumer Advocate: Applying for Automobile Insurance (PDF)', url: S.dfsApply },
        { label: 'Florida Statutes s. 627.7288 (2026): comprehensive deductible and windshields', url: S.s7288 },
        { label: 'Florida Statutes s. 627.744 (2026): pre-insurance inspection', url: S.s744 },
        { label: 'Florida Statutes s. 319.14 (2026): flood vehicle title brand and disclosure', url: S.s1914 },
      ],
    },
    es: {
      title: 'Cobertura amplia vs. colisión en Florida: carros inundados, huracanes y robo',
      metaTitle: 'Seguro de auto: cobertura amplia vs. colisión en Florida | M&K Agency',
      description: 'Qué cubre la cobertura amplia (comprehensive) en Florida: inundación, huracán, robo y parabrisas; en qué se diferencia de colisión y cuándo la exige el banco.',
      ogAlt: 'Un carro en agua de inundación junto a un carro con el parachoques abollado y dos escudos: amplia y colisión',
      excerpt: 'Un carro inundado por un huracán, un robo y un choque son tres reclamos distintos. Así sabe qué parte de su póliza de auto paga cada uno.',
      category: 'Seguro de auto',
      body: [
        { type: 'p', text: 'En el sur de Florida, un carro puede quedar inservible sin chocar contra nada: la marejada ciclónica en la US-1, una rama de palma que rompe el parabrisas o un robo durante la noche. Que su propia póliza pague o no depende de dos coberturas opcionales que mucha gente llama "full coverage": la **cobertura amplia** (comprehensive) y la **cobertura de colisión**. Aquí le explicamos la diferencia con las definiciones del Departamento de Servicios Financieros de Florida (DFS).' },
        { type: 'h2', text: 'Lo que exige la ley de Florida' },
        { type: 'p', text: 'Para registrar un vehículo de cuatro ruedas o más en Florida, usted necesita **Protección contra Lesiones Personales (PIP)** y **Responsabilidad por Daños a la Propiedad (PDL)**, de al menos $10,000 cada una ([FLHSMV](' + S.flhsmv + ')). El PDL paga los daños que usted cause a la propiedad **de otra persona**. Ni el PIP ni el PDL reparan su propio carro: para eso existen la colisión y la cobertura amplia, que la ley estatal no exige. Más detalles en nuestra guía del [seguro mínimo de auto en Florida](/es/blog/florida-minimum-car-insurance-requirements).' },
        { type: 'h2', text: 'Cobertura amplia ("other than collision")' },
        { type: 'p', text: 'En la página de declaraciones, la cobertura amplia suele aparecer como **Other than Collision**. Según el DFS, paga los daños a su vehículo asegurado causados por **incendio, robo, vendaval, vandalismo, inundación, objetos que caen o el choque con un animal** ([DFS](' + S.dfsOverview + ')). Para quien maneja en Florida, eso abarca casi todas las pérdidas de la temporada de huracanes:' },
        { type: 'ul', items: [
          '**Carro inundado:** el agua de la marejada, de un aguacero o de un parqueo inundado es un reclamo de cobertura amplia, no de colisión.',
          '**Viento de huracán:** un árbol, un letrero o escombros del techo que caen sobre el carro.',
          '**Robo:** el robo del vehículo y los daños al forzarlo.',
          '**Parabrisas:** por ley de Florida, el deducible de la cobertura amplia no se aplica a los daños al parabrisas ([sección 627.7288](' + S.s7288 + ')).',
          '**Animales:** atropellar un venado u otro animal entra en la cobertura amplia, no en colisión.',
        ] },
        { type: 'h2', text: 'Colisión' },
        { type: 'p', text: 'La colisión paga la reparación de su vehículo si **choca con otro vehículo, se vuelca o choca contra un objeto** (excepto animales), **sin importar quién tuvo la culpa**. Si el carro es pérdida total, el pago normalmente se limita a su **valor real en efectivo** (actual cash value), salvo que usted y la aseguradora hayan acordado antes un valor específico ([DFS](' + S.dfsOverview + ')). Ejemplos típicos: chocar por detrás en el tráfico, patinar contra un poste con la calle mojada o dar marcha atrás contra una pared. Si el otro conductor tuvo la culpa, su PDL puede pagar; con colisión usted repara su carro por su propia póliza sin esperar a que se resuelva esa disputa.' },
        { type: 'callout', title: 'Prueba rápida', text: '¿El carro chocó contra algo o se volcó? Es colisión. ¿Al carro le pasó algo (agua, viento, fuego, robo, un objeto que cayó, un animal)? Es cobertura amplia.' },
        { type: 'h2', text: 'Carros inundados después de un huracán' },
        { type: 'p', text: 'Sin cobertura amplia, un carro destruido por el agua por lo general no está cubierto por su póliza de auto, y las pólizas de casa y de inundación normalmente excluyen los vehículos. Si la aseguradora declara pérdida total un carro dañado por agua, Florida lo considera un **"flood vehicle"**: el título debe llevar esa marca y el vendedor debe informarlo por escrito antes de la venta ([sección 319.14](' + S.s1914 + ')). Eso también lo protege si compra un carro usado después de una tormenta. En [¿Cuándo se considera pérdida total un carro en Florida?](/es/blog/when-is-a-car-totaled-florida) explicamos la pérdida total y el valor real en efectivo.' },
        { type: 'p', text: 'Antes de la tormenta: si puede hacerlo sin riesgo, lleve el carro a un lugar alto o a un garaje, tómele fotos por dentro y por fuera (incluido el odómetro) y guarde la página de declaraciones en su teléfono. Después, no intente prender un carro que estuvo bajo el agua; reporte el reclamo y deje que el ajustador lo inspeccione. Si su casa también sufrió daños, siga nuestra [lista de pasos para reclamar después de un huracán](/es/blog/hurricane-claim-checklist-florida).' },
        { type: 'callout', title: 'No espere al pronóstico', text: 'Las aseguradoras pueden dejar de aceptar coberturas nuevas o cambios mientras un huracán amenaza. Revise su cobertura amplia al comenzar la temporada, no cuando el cono ya está sobre Miami-Dade.' },
        { type: 'h2', text: 'Cómo funcionan los deducibles' },
        { type: 'p', text: 'Cada cobertura tiene su propio deducible, la parte que usted paga antes de que pague la póliza. El DFS menciona $250, $500 y $1,000 como opciones comunes ([guía del DFS](' + S.dfsToolkit + ')). Con un deducible más alto, la póliza paga menos en cada reclamo, así que elija una cantidad que podría pagar al día siguiente de una tormenta. La excepción del parabrisas aplica solo al parabrisas bajo la cobertura amplia.' },
        { type: 'h2', text: 'Equipos, carro de alquiler y grúa' },
        { type: 'p', text: 'El DFS aclara que, en general, en un reclamo de colisión solo se toma en cuenta el equipo **instalado de forma permanente** en el vehículo. Si usted lleva herramientas de trabajo, tiene una caja de herramientas atornillada, un elevador para silla de ruedas u otros accesorios agregados por usted o por el concesionario, pregunte a su agente cómo se cubren antes de que ocurra un siniestro ([guía del DFS](' + S.dfsToolkit + ')). El carro de alquiler y la grúa son coberturas opcionales aparte, no forman parte de la amplia ni de la colisión ([guía del DFS](' + S.dfsApply + ')). Después de un huracán, cuando los talleres tienen semanas de espera, conviene saber si su póliza incluye carro de alquiler.' },
        { type: 'h2', text: 'Cuándo las necesita de todos modos' },
        { type: 'ul', items: [
          '**Carro financiado o en leasing:** el DFS indica que la mayoría de los prestamistas exige cobertura amplia y colisión. Quitarlas puede incumplir su contrato.',
          '**La colisión suele ir con la amplia:** las aseguradoras normalmente exigen la cobertura amplia para vender colisión, mientras que la amplia sola suele estar disponible ([guía del DFS](' + S.dfsToolkit + ')).',
          '**Inspección en Miami-Dade:** en muchas pólizas nuevas con cobertura de daños físicos, la ley exige que la aseguradora inspeccione el vehículo primero. Hay excepciones: carros nuevos comprados en un concesionario, carros de 10 años o más, renovaciones y conductores con 2 años o más de cobertura de daños físicos sin interrupción ([sección 627.744](' + S.s744 + ')).',
        ] },
        { type: 'h2', text: '¿Vale la pena mantener ambas en un carro viejo?' },
        { type: 'p', text: 'No hay una respuesta única. Compare el valor actual del carro con su deducible, piense si podría reemplazarlo sin un reclamo y recuerde que en nuestra zona el riesgo de inundación y de robo no desaparece con los años. Hay quien mantiene la cobertura amplia y quita la colisión en un carro viejo ya pagado; otros mantienen las dos. Un agente con licencia puede mostrarle las opciones para su vehículo una al lado de la otra.' },
        { type: 'p', text: '¿Quiere revisar su cobertura? Visite nuestra página de [seguro de auto en Florida City](/es/car-insurance-florida-city), [pida una cotización](/es/quote) o llame al **(305) 859-3953**. Nuestra oficina en 33550 S Dixie Hwy, Suite 102, Florida City, atiende de lunes a viernes de 9 a 6, y los sábados con cita.' },
      ],
      faq: [
        { q: '¿La cobertura amplia paga si un huracán inunda mi carro?', a: 'Sí. El DFS incluye la inundación y el vendaval entre los daños que paga la cobertura amplia (other than collision), sujeto a su deducible y a los términos de la póliza. La colisión y una póliza solo de responsabilidad no cubren los daños por inundación a su propio carro.' },
        { q: '¿La ley de Florida exige cobertura amplia o colisión?', a: 'No. Florida exige PIP y PDL para registrar un carro. El banco o la compañía de leasing sí puede exigir cobertura amplia y colisión como condición del préstamo o del contrato.' },
        { q: '¿Pago deducible para cambiar el parabrisas?', a: 'Si tiene cobertura amplia, la ley de Florida (sección 627.7288) establece que el deducible no se aplica a los daños al parabrisas.' },
        { q: '¿Atropellar un venado es colisión o cobertura amplia?', a: 'Según el DFS, el choque con un animal entra en la cobertura amplia; la colisión excluye los animales.' },
      ],
      sources: [
        { label: 'FLHSMV: requisitos de seguro en Florida', url: S.flhsmv },
        { label: 'DFS de Florida: resumen del seguro de auto personal (en inglés)', url: S.dfsOverview },
        { label: 'DFS de Florida: guía del seguro de auto, PDF (en inglés)', url: S.dfsToolkit },
        { label: 'DFS de Florida: cómo solicitar un seguro de auto, PDF (en inglés)', url: S.dfsApply },
        { label: 'Estatutos de Florida, sección 627.7288 (2026): deducible y parabrisas (en inglés)', url: S.s7288 },
        { label: 'Estatutos de Florida, sección 627.744 (2026): inspección previa al seguro (en inglés)', url: S.s744 },
        { label: 'Estatutos de Florida, sección 319.14 (2026): título de flood vehicle (en inglés)', url: S.s1914 },
      ],
    },
    ru: {
      title: 'Comprehensive и collision во Флориде: затопленные машины, ураганы и угон',
      metaTitle: 'Comprehensive и collision: автостраховка во Флориде | M&K Agency',
      description: 'Что покрывает comprehensive во Флориде (наводнение, ураган, угон, лобовое стекло), чем она отличается от collision и когда их требует банк или лизинг.',
      ogAlt: 'Машина в воде после наводнения рядом с машиной с помятым бампером и два щита: comprehensive и collision',
      excerpt: 'Машина, затопленная ураганом, угон и мелкая авария — это три разных страховых случая. Разбираем, какая часть полиса платит за каждый.',
      category: 'Автострахование',
      body: [
        { type: 'p', text: 'В Южной Флориде машину можно потерять, ни во что не врезавшись: штормовой нагон на US-1, пальмовая ветка в лобовом стекле или ночной взлом. Заплатит ли ваш собственный полис, зависит от двух необязательных покрытий, которые часто вместе называют «full coverage»: **comprehensive** и **collision**. Объясняем разницу простыми словами по определениям Департамента финансовых услуг Флориды (DFS).' },
        { type: 'h2', text: 'Что на самом деле требует закон Флориды' },
        { type: 'p', text: 'Чтобы зарегистрировать во Флориде машину с четырьмя и более колёсами, нужны **PIP** (Personal Injury Protection) и **PDL** (Property Damage Liability), минимум по $10,000 каждое ([FLHSMV](' + S.flhsmv + ')). PDL оплачивает ущерб, который вы причинили **чужому** имуществу. Ни PIP, ни PDL не ремонтируют вашу собственную машину — для этого существуют collision и comprehensive, а их закон штата не требует. Подробнее — в нашей статье о [минимальной автостраховке во Флориде](/ru/blog/florida-minimum-car-insurance-requirements).' },
        { type: 'h2', text: 'Comprehensive («other than collision»)' },
        { type: 'p', text: 'В декларации полиса comprehensive часто называется **Other than Collision**. По данным DFS, оно оплачивает повреждение застрахованной машины от **пожара, угона, урагана (windstorm), вандализма, наводнения, падающих предметов или столкновения с животным** ([DFS](' + S.dfsOverview + ')). Для Флориды это почти все потери сезона ураганов:' },
        { type: 'ul', items: [
          '**Затопленная машина:** вода от нагона, ливня или затопленной парковки — это случай comprehensive, а не collision.',
          '**Ураганный ветер:** на машину упали дерево, вывеска или обломки крыши.',
          '**Угон и взлом:** сама украденная машина и повреждения при взломе.',
          '**Лобовое стекло:** по закону Флориды франшиза comprehensive не применяется к повреждению лобового стекла ([ст. 627.7288](' + S.s7288 + ')).',
          '**Животные:** наезд на оленя или другое животное относится к comprehensive, а не к collision.',
        ] },
        { type: 'h2', text: 'Collision' },
        { type: 'p', text: 'Collision оплачивает ремонт вашей машины, если она **столкнулась с другой машиной, перевернулась или врезалась в предмет** (кроме животных), **независимо от того, кто виноват**. Если машина признана тоталом, выплата обычно ограничена её **рыночной стоимостью** (actual cash value), если только вы со страховщиком заранее не согласовали конкретную сумму ([DFS](' + S.dfsOverview + ')). Типичные случаи: въехали в задний бампер в пробке, занесло в столб на мокрой дороге, сдали назад в стену. Если виноват другой водитель, может заплатить его PDL, но collision позволяет отремонтировать машину по своему полису, не дожидаясь, пока решится спор.' },
        { type: 'callout', title: 'Быстрая проверка', text: 'Машина во что-то врезалась или перевернулась? Это collision. С машиной что-то случилось (вода, ветер, огонь, угон, упавший предмет, животное)? Это comprehensive.' },
        { type: 'h2', text: 'Затопленные машины после урагана' },
        { type: 'p', text: 'Без comprehensive машина, погибшая в воде, как правило, не покрывается автополисом, а полисы на дом и от наводнения обычно исключают транспортные средства. Если страховщик признал машину, пострадавшую от воды, тоталом, во Флориде она считается **«flood vehicle»**: эта отметка ставится в титул, и продавец обязан письменно сообщить о ней до продажи ([ст. 319.14](' + S.s1914 + ')). Это защищает и вас, если вы покупаете подержанную машину после шторма. Что такое тотал и рыночная стоимость, мы объясняем в статье [«Когда машину признают тоталом во Флориде»](/ru/blog/when-is-a-car-totaled-florida).' },
        { type: 'p', text: 'Перед штормом: если это безопасно, перегоните машину повыше или в гараж, сфотографируйте её снаружи и внутри (включая одометр) и сохраните декларацию полиса в телефоне. После шторма не пытайтесь заводить машину, которая стояла в воде: заявите о случае и дождитесь осмотра аджастера. Если пострадал и дом, воспользуйтесь нашим [чек-листом страхового случая после урагана](/ru/blog/hurricane-claim-checklist-florida).' },
        { type: 'callout', title: 'Не ждите прогноза', text: 'Пока ураган угрожает региону, страховщики могут перестать принимать новые покрытия и изменения. Проверьте comprehensive в начале сезона, а не тогда, когда «конус» уже над Майами-Дейд.' },
        { type: 'h2', text: 'Как работает франшиза' },
        { type: 'p', text: 'У каждого покрытия своя франшиза (deductible) — сумма, которую вы платите сами до выплаты по полису. DFS называет распространённые варианты: $250, $500 и $1,000 ([руководство DFS](' + S.dfsToolkit + ')). Чем выше франшиза, тем меньше выплата по каждому случаю, поэтому выбирайте сумму, которую сможете заплатить на следующий день после шторма. Исключение для лобового стекла касается только стекла и только по comprehensive.' },
        { type: 'h2', text: 'Оборудование, аренда машины и эвакуатор' },
        { type: 'p', text: 'DFS уточняет: как правило, по collision учитывается только оборудование, **постоянно закреплённое** на машине. Если вы возите рабочие инструменты, у вас прикручен ящик для инструментов, установлен подъёмник для инвалидной коляски или другие доработки от вас или дилера, заранее спросите агента, как они покрываются ([руководство DFS](' + S.dfsToolkit + ')). Аренда машины на время ремонта и эвакуатор — это отдельные необязательные покрытия, они не входят ни в comprehensive, ни в collision ([памятка DFS](' + S.dfsApply + ')). После урагана, когда в автосервисах очереди на недели, полезно знать, есть ли в вашем полисе аренда машины.' },
        { type: 'p', text: 'И ещё один практический момент для русскоязычных водителей: в декларации полиса покрытия записаны по-английски. Ищите строки «Comprehensive» или «Other than Collision» и «Collision» — рядом с каждой указана своя франшиза. Если строки нет, этого покрытия у вас нет, даже если при покупке вам сказали «полная страховка».' },
        { type: 'h2', text: 'Когда они нужны в любом случае' },
        { type: 'ul', items: [
          '**Машина в кредите или лизинге:** по данным DFS, большинство кредиторов требует и comprehensive, и collision. Если их убрать, можно нарушить договор.',
          '**Collision обычно идёт вместе с comprehensive:** страховщики, как правило, продают collision только вместе с comprehensive, а comprehensive отдельно обычно доступно ([руководство DFS](' + S.dfsToolkit + ')).',
          '**Осмотр в Майами-Дейд:** для многих новых полисов с покрытием физического ущерба закон требует, чтобы страховщик сначала осмотрел машину. Исключения: новая машина из дилерского центра, машины 10 лет и старше, продления полиса и водители с покрытием физического ущерба 2 года и больше без перерыва ([ст. 627.744](' + S.s744 + ')).',
        ] },
        { type: 'h2', text: 'Стоит ли оставлять оба покрытия на старой машине?' },
        { type: 'p', text: 'Единого ответа нет. Сравните текущую стоимость машины со своей франшизой, подумайте, сможете ли вы заменить её без страховой выплаты, и помните: в нашем районе риск наводнения и угона с возрастом машины никуда не исчезает. Кто-то на старой выплаченной машине оставляет comprehensive и убирает collision, кто-то сохраняет оба. Лицензированный агент покажет варианты покрытия для вашей машины рядом друг с другом.' },
        { type: 'p', text: 'Хотите проверить своё покрытие? Загляните на нашу страницу [автострахования во Флорида-Сити](/ru/car-insurance-florida-city), [оставьте заявку](/ru/quote) или позвоните по номеру **(305) 859-3953**. Наш офис: 33550 S Dixie Hwy, Suite 102, Florida City; понедельник–пятница с 9 до 6, в субботу по записи. Говорим по-русски.' },
      ],
      faq: [
        { q: 'Покрывает ли comprehensive машину, затопленную ураганом?', a: 'Да. DFS относит наводнение и ураганный ветер к случаям, которые оплачивает comprehensive (other than collision), с учётом франшизы и условий полиса. Collision и полис только с ответственностью не покрывают ущерб от воды вашей собственной машине.' },
        { q: 'Обязательны ли во Флориде comprehensive или collision?', a: 'По закону штата — нет. Для регистрации машины нужны PIP и PDL. Но банк или лизинговая компания могут потребовать comprehensive и collision по условиям кредита или лизинга.' },
        { q: 'Нужно ли платить франшизу за замену лобового стекла?', a: 'Если у вас есть comprehensive, по закону Флориды (ст. 627.7288) франшиза к повреждению лобового стекла не применяется.' },
        { q: 'Наезд на оленя — это collision или comprehensive?', a: 'По данным DFS, столкновение с животным относится к comprehensive, а collision животных исключает.' },
      ],
      sources: [
        { label: 'FLHSMV: требования к страхованию во Флориде (на английском)', url: S.flhsmv },
        { label: 'DFS Флориды: обзор личного автострахования (на английском)', url: S.dfsOverview },
        { label: 'DFS Флориды: руководство по автострахованию, PDF (на английском)', url: S.dfsToolkit },
        { label: 'DFS Флориды: памятка о покупке автостраховки, PDF (на английском)', url: S.dfsApply },
        { label: 'Законы Флориды, ст. 627.7288 (2026): франшиза и лобовое стекло (на английском)', url: S.s7288 },
        { label: 'Законы Флориды, ст. 627.744 (2026): осмотр машины перед страхованием (на английском)', url: S.s744 },
        { label: 'Законы Флориды, ст. 319.14 (2026): отметка flood vehicle в титуле (на английском)', url: S.s1914 },
      ],
    },
  },
};
