import type { BlogPost } from '../types';

// Facts checked 2026-10-09 against official sources: 2026 Florida Statutes on
// flsenate.gov: s. 627.70132 (1 year / 18 months notice), s. 627.7142 (Homeowner
// Claims Bill of Rights within 14 days), s. 627.7152(13) (post-loss benefits can't be
// assigned for policies issued on or after Jan 1, 2023), s. 626.854 (48 hours' notice
// before an insurer inspection; public adjuster fee cap 10% / 20%; cancel within 10 days,
// or 30 days after the date of loss in a declared emergency), s. 489.147 (contractor
// solicitation rules); FEMA/NFIP claims checklist and claims manual (proof of loss
// within 60 days); DFS consumer helpline 1-877-693-5236. Deadlines for the insurer are
// in the hurricane-claim-timeline-florida post and are not repeated here. No insurer named.
const S = {
  s70132: 'https://www.flsenate.gov/Laws/Statutes/2026/627.70132',
  s7142: 'https://www.flsenate.gov/Laws/Statutes/2026/627.7142',
  s7152: 'https://www.flsenate.gov/Laws/Statutes/2026/627.7152',
  s854: 'https://www.flsenate.gov/Laws/Statutes/2026/626.854',
  s147: 'https://www.flsenate.gov/Laws/Statutes/2026/489.147',
  nfip: 'https://www.floodsmart.gov/claims-checklist',
  nfipManual: 'https://www.fema.gov/sites/default/files/documents/fema_fim-appendix-e-claims_apr2021.pdf',
  dfs: 'https://www.myfloridacfo.com/division/consumers',
};

export const post: BlogPost = {
  slug: 'hurricane-claim-checklist-florida',
  datePublished: '2026-10-09',
  translations: {
    en: {
      title: 'Hurricane Claim Checklist for Florida Homeowners',
      metaTitle: 'How to File a Hurricane Claim in Florida: Checklist | M&K Agency',
      description: 'Step-by-step checklist for filing a hurricane insurance claim in Florida: photos, temporary repairs, adjuster visits, flood claims, contractors and your rights.',
      ogAlt: 'Clipboard checklist, camera and tarp in front of a Florida house after a storm',
      excerpt: 'What to do in the first hours, days and weeks after a hurricane so your home insurance claim is complete, documented and on time.',
      category: 'Homeowners insurance',
      body: [
        { type: 'p', text: 'When a hurricane passes, it is hard to think clearly. This checklist puts the steps of a Florida home or condo claim in order, from the first walk-around to the final payment. For the deadlines your insurer must meet (7, 30 and 60 days), see our [hurricane claim timeline](/en/blog/hurricane-claim-timeline-florida); this guide focuses on **what you do**.' },
        { type: 'h2', text: 'Before the storm: 15 minutes that help later' },
        { type: 'ul', items: [
          'Save your policy number and your insurer’s claim phone number in your phone, and keep a copy of your declarations page in the cloud.',
          'Walk through the house with your phone and record a video of every room, closets, appliances, the roof (from the ground) and the outside.',
          'Know your **hurricane deductible**. It is often a percentage of the dwelling limit, not a fixed amount; our [wind deductible guide](/en/florida-home-insurance-wind-deductible) explains how it works.',
          'Check whether you have **flood insurance**. Standard home policies do not cover flood; it is a separate policy (see our [flood insurance page](/en/flood-insurance-homestead-fl)).',
        ] },
        { type: 'h2', text: 'First 24–72 hours: safety and evidence' },
        { type: 'ol', items: [
          'Stay out of the house until it is safe. Watch for downed lines, gas smells and standing water.',
          '**Photograph and film all damage before you move or fix anything:** roof, ceilings, walls, floors, windows, fences, cars and damaged belongings. Include close-ups and wide shots.',
          'Prevent further damage with reasonable temporary repairs, for example a tarp on the roof or boards over a broken window. Most policies require this. **Keep every receipt** and photograph the repair.',
          'Do not throw away damaged items before the adjuster sees them unless they are a health hazard; if you must, photograph them first and keep a sample (such as a piece of carpet).',
          'If the home is not livable, keep receipts for hotel, meals and other extra costs. Many policies include additional living expense coverage; check your policy.',
        ] },
        { type: 'h2', text: 'Report the claim' },
        { type: 'p', text: 'Report as soon as it is safe, by phone, app or online. Florida law sets an outer limit of **1 year** after the date of loss for a new claim and **18 months** for a supplemental claim; for a hurricane, the date of loss is the day of landfall ([s. 627.70132](' + S.s70132 + ')). Write down the claim number, the date and the name of everyone you speak with.' },
        { type: 'p', text: 'Within **14 days** after your first contact about the claim, your insurer must send you the **Homeowner Claims Bill of Rights**, a plain-language summary of your rights in the claims process ([s. 627.7142](' + S.s7142 + ')). Read it and keep it with your file.' },
        { type: 'h2', text: 'The adjuster visit' },
        { type: 'ul', items: [
          'An adjuster or other person acting for the insurer must give you at least **48 hours’ notice** before an on-site inspection or meeting ([s. 626.854(14)](' + S.s854 + ')).',
          'Be there if you can. Show every damaged area, including the attic and outbuildings, and hand over a list of damaged belongings.',
          'Ask for the adjuster’s name and license number and for a copy of the estimate.',
          'Compare the estimate with a written estimate from a licensed contractor. If something was missed, you can file a supplemental claim.',
        ] },
        { type: 'h2', text: 'Flood damage is a separate claim' },
        { type: 'p', text: 'If water came in from storm surge or rising water, report it to your **flood** insurer too. Under the National Flood Insurance Program, you generally must send a signed, sworn **proof of loss** with supporting documents **within 60 days** of the loss, unless FEMA extends the deadline for that event ([NFIP checklist](' + S.nfip + ')). Wind and flood damage are adjusted separately, so photos that show the water line are useful.' },
        { type: 'h2', text: 'Contractors, public adjusters and what you sign' },
        { type: 'ul', items: [
          'For residential policies issued on or after January 1, 2023, you **cannot assign** your post-loss benefits to a contractor; such an assignment is void ([s. 627.7152(13)](' + S.s7152 + ')). Read any contract carefully before signing.',
          'A contractor may not offer you a gift, cash or a deductible waiver for letting it inspect your roof or for filing a roof claim ([s. 489.147](' + S.s147 + ')). Waiving a deductible this way can be insurance fraud.',
          'If you hire a **public adjuster**, the fee is capped by law: generally **10%** of claim payments for claims made in the year after a declared state of emergency, and 20% otherwise. You can cancel the contract without penalty within 10 days, or, in a declared emergency, within 30 days after the date of loss if that is longer ([s. 626.854](' + S.s854 + ')).',
          'Check any contractor or adjuster license before you pay or sign.',
        ] },
        { type: 'h2', text: 'Keep a claim log' },
        { type: 'p', text: 'One folder (paper or digital) with your photos, receipts, letters, the estimate, every payment and a dated list of calls and emails. If you disagree with the result, the timeline guide explains state **mediation**, and the Florida Department of Financial Services consumer helpline at **1-877-693-5236** can help with questions ([DFS](' + S.dfs + ')).' },
        { type: 'callout', title: 'Questions about your coverage before the next storm?', text: 'A licensed agent can review your policy, deductibles and flood options in English, Spanish or Russian. See our [homeowners insurance page](/en/homeowners-insurance-florida-city), [request a quote](/en/quote) or call (305) 859-3953. This is general information, not legal advice; coverage depends on your policy.' },
      ],
      faq: [
        { q: 'Should I make repairs before the adjuster comes?', a: 'Make reasonable temporary repairs to stop more damage, such as a roof tarp, after you photograph everything. Keep the receipts. Hold off on permanent repairs until the damage has been documented and inspected, unless your insurer agrees.' },
        { q: 'Do I file one claim for wind and flood?', a: 'Usually not. Wind damage goes to your home insurer and flood damage to your flood insurer. An NFIP flood claim generally needs a proof of loss within 60 days of the loss.' },
        { q: 'Can a roofer handle my insurance claim for me?', a: 'A contractor can repair your home, but for policies issued on or after January 1, 2023, you cannot assign your claim benefits to it, and contractors may not offer gifts or deductible waivers for roof claims.' },
      ],
      sources: [
        { label: 'Florida Statutes s. 627.70132 (2026): notice of property insurance claim', url: S.s70132 },
        { label: 'Florida Statutes s. 627.7142 (2026): Homeowner Claims Bill of Rights', url: S.s7142 },
        { label: 'Florida Statutes s. 627.7152 (2026): assignment agreements', url: S.s7152 },
        { label: 'Florida Statutes s. 626.854 (2026): public adjusters; notice before inspections', url: S.s854 },
        { label: 'Florida Statutes s. 489.147 (2026): prohibited property insurance practices by contractors', url: S.s147 },
        { label: 'FEMA / NFIP: Claims checklist for policyholders', url: S.nfip },
        { label: 'FEMA: NFIP Flood Insurance Manual, Appendix E: Claims (PDF)', url: S.nfipManual },
        { label: 'Florida Department of Financial Services: Consumer Services', url: S.dfs },
      ],
    },
    es: {
      title: 'Lista de pasos para reclamar al seguro después de un huracán en Florida',
      metaTitle: 'Cómo reclamar al seguro por un huracán en Florida | M&K Agency',
      description: 'Guía paso a paso para presentar un reclamo de huracán en Florida: fotos, reparaciones temporales, visita del ajustador, reclamos de inundación y sus derechos.',
      ogAlt: 'Lista de verificación, cámara y lona frente a una casa de Florida después de una tormenta',
      excerpt: 'Qué hacer en las primeras horas, días y semanas después de un huracán para que su reclamo esté completo, documentado y a tiempo.',
      category: 'Seguro de vivienda',
      body: [
        { type: 'p', text: 'Después de un huracán cuesta pensar con calma. Esta lista ordena los pasos de un reclamo de casa o condominio en Florida, desde la primera revisión hasta el pago final. Los plazos que debe cumplir la aseguradora (7, 30 y 60 días) están en nuestra guía de [plazos del reclamo por huracán](/es/blog/hurricane-claim-timeline-florida); aquí nos enfocamos en **lo que usted hace**.' },
        { type: 'h2', text: 'Antes de la tormenta: 15 minutos que ayudan después' },
        { type: 'ul', items: [
          'Guarde en el teléfono su número de póliza y el teléfono de reclamos de su aseguradora, y una copia de la página de declaraciones en la nube.',
          'Recorra la casa grabando un video de cada cuarto, los clósets, los electrodomésticos, el techo (desde el suelo) y el exterior.',
          'Conozca su **deducible de huracán**. Muchas veces es un porcentaje del límite de la vivienda y no una cantidad fija; nuestra [guía del deducible de viento](/es/florida-home-insurance-wind-deductible) lo explica.',
          'Revise si tiene **seguro de inundación**. La póliza de casa normal no cubre inundación; es una póliza aparte (vea nuestra [página de seguro de inundación](/es/flood-insurance-homestead-fl)).',
        ] },
        { type: 'h2', text: 'Primeras 24–72 horas: seguridad y pruebas' },
        { type: 'ol', items: [
          'No entre a la casa hasta que sea seguro. Cuidado con cables caídos, olor a gas y agua estancada.',
          '**Tome fotos y videos de todos los daños antes de mover o arreglar algo:** techo, cielorrasos, paredes, pisos, ventanas, cercas, carros y pertenencias dañadas. Incluya tomas de cerca y de lejos.',
          'Evite más daños con reparaciones temporales razonables, por ejemplo una lona en el techo o tablas en una ventana rota. La mayoría de las pólizas lo exigen. **Guarde todos los recibos** y fotografíe la reparación.',
          'No bote objetos dañados antes de que los vea el ajustador, salvo que sean un riesgo para la salud; si tiene que hacerlo, fotografíelos antes y guarde una muestra (por ejemplo, un pedazo de alfombra).',
          'Si la casa no se puede habitar, guarde los recibos de hotel, comidas y otros gastos extra. Muchas pólizas incluyen cobertura de gastos adicionales de vivienda; revise la suya.',
        ] },
        { type: 'h2', text: 'Presente el reclamo' },
        { type: 'p', text: 'Repórtelo apenas sea seguro, por teléfono, aplicación o internet. La ley de Florida fija un límite máximo de **1 año** desde la fecha de la pérdida para un reclamo nuevo y **18 meses** para un reclamo suplementario; en un huracán, la fecha de la pérdida es el día en que tocó tierra ([art. 627.70132](' + S.s70132 + ')). Anote el número de reclamo, la fecha y el nombre de cada persona con quien hable.' },
        { type: 'p', text: 'Dentro de los **14 días** después de su primer contacto sobre el reclamo, la aseguradora debe enviarle la **Carta de Derechos del Propietario en Reclamos** (Homeowner Claims Bill of Rights), un resumen sencillo de sus derechos ([art. 627.7142](' + S.s7142 + ')). Léala y guárdela con sus papeles.' },
        { type: 'h2', text: 'La visita del ajustador' },
        { type: 'ul', items: [
          'El ajustador u otra persona que actúe por la aseguradora debe avisarle con al menos **48 horas** antes de una inspección o reunión en la propiedad ([art. 626.854(14)](' + S.s854 + ')).',
          'Si puede, esté presente. Muestre todas las áreas dañadas, incluido el ático y las construcciones exteriores, y entregue una lista de las pertenencias dañadas.',
          'Pida el nombre y el número de licencia del ajustador y una copia del estimado.',
          'Compare el estimado con uno por escrito de un contratista con licencia. Si faltó algo, puede presentar un reclamo suplementario.',
        ] },
        { type: 'h2', text: 'El daño por inundación es un reclamo aparte' },
        { type: 'p', text: 'Si el agua entró por marejada ciclónica o crecida, repórtelo también a su aseguradora de **inundación**. En el Programa Nacional de Seguro contra Inundaciones (NFIP), por lo general debe enviar una **prueba de pérdida** (proof of loss) firmada y jurada, con documentos de respaldo, **dentro de los 60 días** posteriores a la pérdida, salvo que FEMA extienda el plazo para ese evento ([lista del NFIP](' + S.nfip + ')). El viento y la inundación se ajustan por separado, así que las fotos que muestran la marca del agua son útiles.' },
        { type: 'h2', text: 'Contratistas, ajustadores públicos y lo que usted firma' },
        { type: 'ul', items: [
          'En pólizas residenciales emitidas a partir del 1 de enero de 2023, usted **no puede ceder** sus beneficios del reclamo a un contratista; esa cesión es nula ([art. 627.7152(13)](' + S.s7152 + ')). Lea bien cualquier contrato antes de firmar.',
          'Un contratista no puede ofrecerle regalos, dinero ni la exención del deducible a cambio de inspeccionar su techo o de presentar un reclamo por el techo ([art. 489.147](' + S.s147 + ')). Exonerar el deducible así puede ser fraude de seguros.',
          'Si contrata a un **ajustador público**, la ley limita sus honorarios: en general **10%** de los pagos en reclamos presentados en el año siguiente a una declaración de emergencia, y 20% en los demás casos. Puede cancelar el contrato sin penalidad dentro de 10 días o, en una emergencia declarada, dentro de los 30 días posteriores a la pérdida si ese plazo es mayor ([art. 626.854](' + S.s854 + ')).',
          'Verifique la licencia de cualquier contratista o ajustador antes de pagar o firmar.',
        ] },
        { type: 'h2', text: 'Lleve un registro del reclamo' },
        { type: 'p', text: 'Una carpeta (en papel o digital) con fotos, recibos, cartas, el estimado, cada pago y una lista con fecha de llamadas y correos. Si no está de acuerdo con el resultado, la guía de plazos explica la **mediación** estatal, y la línea de ayuda al consumidor del Departamento de Servicios Financieros de Florida, **1-877-693-5236**, puede orientarle ([DFS](' + S.dfs + ')).' },
        { type: 'callout', title: '¿Dudas sobre su cobertura antes de la próxima tormenta?', text: 'Un agente con licencia puede revisar su póliza, deducibles y opciones de inundación en español, inglés o ruso. Vea nuestra [página de seguro de vivienda](/es/homeowners-insurance-florida-city), [pida una cotización](/es/quote) o llame al (305) 859-3953. Esta es información general, no asesoría legal; la cobertura depende de su póliza.' },
      ],
      faq: [
        { q: '¿Debo reparar antes de que venga el ajustador?', a: 'Haga reparaciones temporales razonables para evitar más daños, como una lona en el techo, después de fotografiar todo. Guarde los recibos. Espere para las reparaciones permanentes hasta que el daño esté documentado e inspeccionado, salvo que la aseguradora esté de acuerdo.' },
        { q: '¿Presento un solo reclamo por viento e inundación?', a: 'Normalmente no. El daño por viento va a la aseguradora de la casa y el de inundación a la aseguradora de inundación. Un reclamo del NFIP en general requiere una prueba de pérdida dentro de los 60 días.' },
        { q: '¿Un techador puede manejar mi reclamo?', a: 'Un contratista puede reparar su casa, pero en pólizas emitidas desde el 1 de enero de 2023 usted no puede cederle los beneficios del reclamo, y los contratistas no pueden ofrecer regalos ni exonerar el deducible por reclamos de techo.' },
      ],
      sources: [
        { label: 'Estatutos de Florida, art. 627.70132 (2026): aviso de reclamo de seguro de propiedad (en inglés)', url: S.s70132 },
        { label: 'Estatutos de Florida, art. 627.7142 (2026): Homeowner Claims Bill of Rights (en inglés)', url: S.s7142 },
        { label: 'Estatutos de Florida, art. 627.7152 (2026): cesión de beneficios (en inglés)', url: S.s7152 },
        { label: 'Estatutos de Florida, art. 626.854 (2026): ajustadores públicos; aviso antes de inspecciones (en inglés)', url: S.s854 },
        { label: 'Estatutos de Florida, art. 489.147 (2026): prácticas prohibidas de contratistas (en inglés)', url: S.s147 },
        { label: 'FEMA / NFIP: lista de verificación de reclamos (en inglés)', url: S.nfip },
        { label: 'FEMA: Manual del NFIP, Apéndice E: Reclamos (PDF, en inglés)', url: S.nfipManual },
        { label: 'Departamento de Servicios Financieros de Florida: Servicios al Consumidor', url: S.dfs },
      ],
    },
    ru: {
      title: 'Чек-лист страхового случая после урагана для владельцев домов во Флориде',
      metaTitle: 'Как подать страховой случай после урагана во Флориде | M&K Agency',
      description: 'Пошаговый чек-лист: как заявить страховой случай после урагана во Флориде — фото, временный ремонт, визит адджастера, наводнение, подрядчики и ваши права.',
      ogAlt: 'Чек-лист, фотоаппарат и брезент перед домом во Флориде после шторма',
      excerpt: 'Что делать в первые часы, дни и недели после урагана, чтобы заявка по страховке дома была полной, с доказательствами и в срок.',
      category: 'Страхование дома',
      body: [
        { type: 'p', text: 'После урагана трудно думать спокойно. Этот чек-лист раскладывает по порядку шаги по страховому случаю для дома или кондо во Флориде — от первого осмотра до итоговой выплаты. Сроки, которые обязана соблюдать страховая (7, 30 и 60 дней), собраны в нашей статье о [сроках урегулирования после урагана](/ru/blog/hurricane-claim-timeline-florida); здесь речь о том, **что делаете вы**.' },
        { type: 'h2', text: 'До шторма: 15 минут, которые потом пригодятся' },
        { type: 'ul', items: [
          'Сохраните в телефоне номер полиса и телефон отдела претензий вашей страховой, а копию страницы деклараций (declarations page) — в облаке.',
          'Пройдите по дому и снимите на видео каждую комнату, шкафы, технику, крышу (с земли) и двор.',
          'Узнайте свою **ураганную франшизу**. Часто это процент от суммы страхования дома, а не фиксированная сумма; подробнее в нашем [гиде по ветровой франшизе](/ru/florida-home-insurance-wind-deductible).',
          'Проверьте, есть ли у вас **страховка от наводнения**. Обычный полис на дом наводнение не покрывает — это отдельный полис.',
        ] },
        { type: 'h2', text: 'Первые 24–72 часа: безопасность и доказательства' },
        { type: 'ol', items: [
          'Не заходите в дом, пока это небезопасно. Остерегайтесь оборванных проводов, запаха газа и стоячей воды.',
          '**Сфотографируйте и снимите на видео все повреждения до того, как что-то двигать или чинить:** крышу, потолки, стены, полы, окна, забор, машины и испорченные вещи. Нужны и крупные, и общие планы.',
          'Предотвратите дальнейший ущерб разумным временным ремонтом: например, брезент на крышу или щиты на разбитое окно. Большинство полисов этого требуют. **Сохраняйте все чеки** и фотографируйте ремонт.',
          'Не выбрасывайте повреждённые вещи до осмотра адджастером, если они не опасны для здоровья; если выбросить всё же нужно, сначала сфотографируйте и оставьте образец (например, кусок ковра).',
          'Если жить в доме нельзя, сохраняйте чеки за гостиницу, питание и другие дополнительные расходы. Многие полисы покрывают дополнительные расходы на проживание — проверьте свой.',
        ] },
        { type: 'h2', text: 'Заявите о страховом случае' },
        { type: 'p', text: 'Сообщите о нём, как только это безопасно, — по телефону, через приложение или онлайн. Закон Флориды устанавливает предельный срок: **1 год** с даты ущерба для нового заявления и **18 месяцев** для дополнительного; для урагана датой ущерба считается день выхода на сушу ([ст. 627.70132](' + S.s70132 + ')). Запишите номер заявки, дату и имена всех, с кем говорили.' },
        { type: 'p', text: 'В течение **14 дней** после вашего первого обращения страховая обязана прислать **Билль о правах владельца жилья при страховом случае** (Homeowner Claims Bill of Rights) — простое изложение ваших прав ([ст. 627.7142](' + S.s7142 + ')). Прочитайте его и храните вместе с документами.' },
        { type: 'h2', text: 'Визит адджастера' },
        { type: 'ul', items: [
          'Адджастер или другой представитель страховой должен предупредить вас минимум за **48 часов** до осмотра или встречи на объекте ([ст. 626.854(14)](' + S.s854 + ')).',
          'По возможности присутствуйте. Покажите все повреждённые места, включая чердак и хозпостройки, и передайте список испорченных вещей.',
          'Попросите имя и номер лицензии адджастера и копию сметы.',
          'Сравните смету с письменной сметой лицензированного подрядчика. Если что-то упущено, можно подать дополнительное заявление.',
        ] },
        { type: 'h2', text: 'Ущерб от наводнения — отдельное заявление' },
        { type: 'p', text: 'Если вода зашла из-за штормового нагона или подъёма воды, сообщите и страховщику **от наводнения**. По Национальной программе страхования от наводнений (NFIP), как правило, нужно отправить подписанное и заверенное под присягой **подтверждение ущерба** (proof of loss) с документами **в течение 60 дней** после ущерба, если FEMA не продлит срок для этого события ([чек-лист NFIP](' + S.nfip + ')). Ветер и наводнение урегулируются отдельно, поэтому фото с отметкой уровня воды очень полезны.' },
        { type: 'h2', text: 'Подрядчики, публичные адджастеры и что вы подписываете' },
        { type: 'ul', items: [
          'По жилым полисам, выданным 1 января 2023 года или позже, **нельзя переуступить** подрядчику права на страховую выплату; такая переуступка недействительна ([ст. 627.7152(13)](' + S.s7152 + ')). Внимательно читайте любой договор перед подписью.',
          'Подрядчик не вправе предлагать подарки, деньги или отказ от франшизы за осмотр крыши или за подачу заявления по крыше ([ст. 489.147](' + S.s147 + ')). Такое «прощение» франшизы может быть страховым мошенничеством.',
          'Если вы нанимаете **публичного адджастера**, его гонорар ограничен законом: как правило, **10%** выплат по заявлениям, поданным в течение года после объявления чрезвычайного положения, и 20% в остальных случаях. Договор можно расторгнуть без штрафа в течение 10 дней, а при объявленном ЧП — в течение 30 дней после даты ущерба, если этот срок дольше ([ст. 626.854](' + S.s854 + ')).',
          'Проверяйте лицензию любого подрядчика или адджастера до оплаты и подписи.',
        ] },
        { type: 'h2', text: 'Ведите журнал страхового случая' },
        { type: 'p', text: 'Одна папка (бумажная или в телефоне): фото, чеки, письма, смета, каждая выплата и список звонков и писем с датами. Если вы не согласны с решением, в статье о сроках описана государственная **медиация**, а горячая линия для потребителей Департамента финансовых услуг Флориды **1-877-693-5236** поможет с вопросами ([DFS](' + S.dfs + ')).' },
        { type: 'callout', title: 'Есть вопросы о покрытии до следующего шторма?', text: 'Лицензированный агент разберёт ваш полис, франшизы и варианты страховки от наводнения на русском, английском или испанском. Смотрите [страницу о страховании дома](/ru/homeowners-insurance-florida-city), [запросите расчёт](/ru/quote) или звоните (305) 859-3953. Это общая информация, а не юридическая консультация; покрытие зависит от вашего полиса.' },
      ],
      faq: [
        { q: 'Нужно ли ремонтировать до приезда адджастера?', a: 'Сделайте разумный временный ремонт, чтобы остановить ущерб (например, брезент на крышу), но только после того, как всё сфотографируете. Сохраните чеки. С капитальным ремонтом подождите, пока ущерб не задокументирован и не осмотрен, если страховая не согласовала иное.' },
        { q: 'Подавать одно заявление на ветер и наводнение?', a: 'Обычно нет. Ущерб от ветра заявляется страховщику дома, от наводнения — страховщику от наводнения. По NFIP подтверждение ущерба, как правило, нужно подать в течение 60 дней.' },
        { q: 'Может ли кровельщик вести моё страховое дело?', a: 'Подрядчик может отремонтировать дом, но по полисам, выданным с 1 января 2023 года, переуступить ему права на выплату нельзя, а предлагать подарки или отказ от франшизы за заявление по крыше подрядчикам запрещено.' },
      ],
      sources: [
        { label: 'Законы Флориды, ст. 627.70132 (2026): уведомление о страховом случае по имуществу (на английском)', url: S.s70132 },
        { label: 'Законы Флориды, ст. 627.7142 (2026): Homeowner Claims Bill of Rights (на английском)', url: S.s7142 },
        { label: 'Законы Флориды, ст. 627.7152 (2026): переуступка прав на выплату (на английском)', url: S.s7152 },
        { label: 'Законы Флориды, ст. 626.854 (2026): публичные адджастеры; уведомление об осмотре (на английском)', url: S.s854 },
        { label: 'Законы Флориды, ст. 489.147 (2026): запрещённые практики подрядчиков (на английском)', url: S.s147 },
        { label: 'FEMA / NFIP: чек-лист страхового случая (на английском)', url: S.nfip },
        { label: 'FEMA: руководство NFIP, приложение E: страховые случаи (PDF, на английском)', url: S.nfipManual },
        { label: 'Департамент финансовых услуг Флориды: защита потребителей (на английском)', url: S.dfs },
      ],
    },
  },
};
