import type { BusinessPage } from './types';
import { SRC_URL as U, sources } from './sources';

// General-information page. Do not name any market or state specific policy
// terms as universal; DFS guidance is attributed to DFS.
export const BUILDERS_RISK: BusinessPage = {
  path: '/builders-risk-insurance-florida',
  icon: '🏠',
  published: '2026-09-26',
  modified: '2026-09-26',
  team: ['mikhail-kozlov', 'carolina-silva', 'jose-egues-chalela'],
  copy: {
    en: {
      metaTitle: 'Builders Risk Insurance in Florida | M&K Agency',
      metaDesc: 'Builders risk insurance for Florida homes and buildings under construction: who typically needs it, how it works and what to have ready for a quote.',
      breadcrumb: 'Builders risk insurance',
      kicker: 'Builders Risk · Florida',
      h1a: 'Builders risk insurance in Florida,',
      h1b: 'for the building while it goes up.',
      sub: 'Owners building a home, contractors and developers across Florida: we help you look at builders risk coverage for a structure under construction, and at what your lender or construction contract asks for. In English, Spanish or Russian.',
      linkLabel: 'Builders risk',
      serviceType: 'Builders risk insurance',
      intro: [
        { type: 'h2', text: 'What builders risk insurance is' },
        { type: 'p', text: `The National Association of Insurance Commissioners describes builders’ risk as coverage that “insures against loss to buildings in the course of construction,” typically written on a reporting or completed value form ([NAIC glossary](${U.naic})). In plain terms, it’s designed for the period while a structure is being built, before a regular property policy takes over. Policy forms vary, so what a specific policy covers depends on its wording.` },
        { type: 'p', text: 'Florida builds a lot: the U.S. Census Bureau reports **178,297 housing units in 114,415 buildings** authorized by building permits in Florida in 2025.' },
        { type: 'h2', text: 'Who typically needs it' },
        { type: 'ul', items: [
          'Owners building a new home, including owner-builders',
          'General contractors and home builders, when the contract makes them responsible for insuring the work',
          'Investors and developers building or substantially renovating a property',
          'Anyone with a construction loan: lenders often require builders risk, so check your loan documents for the exact requirement',
        ] },
      ],
      covTitle: 'How builders risk fits with other coverage',
      cov: [
        { h: 'Builders risk', p: 'Covers the structure under construction. The covered causes of loss, limits and deductibles depend on the policy you choose.' },
        { h: 'General liability', p: 'A separate policy for injury or damage to others caused by the work. Contractors usually carry their own; owner-builders should ask about it too.' },
        { h: 'Workers’ compensation', p: 'A separate policy for employees hurt on the job. Builders risk does not replace it.' },
        { h: 'Tools & equipment', p: 'Contractors’ own tools and equipment are usually insured separately under an inland marine policy.' },
        { h: 'Property insurance after completion', p: 'When construction ends and the building is occupied, a permanent homeowners or commercial property policy needs to be in place.' },
      ],
      body: [
        { type: 'h2', text: 'Florida points to know' },
        { type: 'h3', text: 'Wind, rain and the stage of construction' },
        { type: 'p', text: `In its [commercial insurance FAQs](${U.dfsBr}), the Florida Department of Financial Services notes that builder’s risk policies are named-peril policies and that rain is not a named peril in the contract, although there could be limited coverage for materials at the job site damaged by rain if included by endorsement. DFS adds that wind damage should be covered, subject to other contractual provisions, and that some policies require construction to reach a certain stage, such as 50% or 75% of completion, before coverage applies for wind. Every policy is different, so we go through these points with you on the actual quote.` },
        { type: 'h3', text: 'Building as an owner-builder?' },
        { type: 'p', text: `Florida’s owner-builder disclosure statement, set out in [§ 489.103](${U.fs489_103}), says the owner-builder is the responsible party of record on the permit. It also warns that an owner-builder may be held liable for injuries to unlicensed workers on the property and that homeowner’s insurance may not cover those injuries. If you’re building this way, talk to us about liability coverage as well as builders risk.` },
        { type: 'h3', text: 'Check your loan and your contract' },
        { type: 'p', text: 'Construction loans and construction contracts often spell out who must buy builders risk, for what amount and who must be named on the policy. Send us those pages with your request so the quote matches them.' },
        { type: 'h2', text: 'What to have ready for a quote' },
        { type: 'ul', items: [
          'Project address and a short description: new home, addition, renovation or commercial building',
          'Construction type (for example concrete block or wood frame), number of stories and square footage',
          'Completed value of the project',
          'Start date and expected completion date',
          'Current stage of construction, if work has already started',
          'Who the owner, general contractor and lender are',
          'Insurance requirements from the loan or construction contract',
          'Site security: fencing, lighting, cameras',
        ] },
        { type: 'p', text: 'When the home is finished, see [new construction home insurance](/en/new-construction-home-insurance-florida). Contractors can also see [contractor insurance](/en/contractor-insurance-florida).' },
      ],
      faqTitle: 'Builders risk insurance: common questions',
      faq: [
        { q: 'Will my homeowners policy cover a house that’s still being built?', a: 'Don’t assume it will. A house under construction is commonly insured under a builders risk policy until it’s finished and a permanent policy takes over. Talk to us before work starts so there’s no gap.' },
        { q: 'Who buys builders risk, the owner or the contractor?', a: 'Either can, depending on the construction contract and the lender. Those documents usually say who is responsible. Send them to us and we’ll help you find that section.' },
        { q: 'Does builders risk cover hurricane damage?', a: 'It depends on the policy. Florida DFS notes that wind damage should be covered subject to the policy’s other provisions, and that some policies require a certain stage of completion before wind coverage applies. We’ll show you how the quoted policy handles wind and which deductible applies.' },
        { q: 'How long does a builders risk policy last?', a: 'Policies are written for a set term that should match your construction schedule. Ask us what your options are if the project runs longer than planned.' },
        { q: 'Do you only work with projects near Florida City?', a: 'No. Our office is in Florida City, but we work with owners and contractors building across Florida by phone, text and email, in English, Spanish and Russian.' },
      ],
      sources: sources('en', ['naic', 'dfsBr', 'fs489_103', 'bps2025']),
    },
    es: {
      metaTitle: 'Seguro Builders Risk en Florida | M&K Agency',
      metaDesc: 'Seguro builders risk para casas y edificios en construcción en Florida: quién lo necesita, cómo funciona y qué tener a mano para cotizar. Atención en español.',
      breadcrumb: 'Seguro builders risk',
      kicker: 'Builders risk · Florida',
      h1a: 'Seguro builders risk en Florida,',
      h1b: 'para la obra mientras se construye.',
      sub: 'Dueños que construyen su casa, contratistas y desarrolladores en toda Florida: le ayudamos a revisar la cobertura builders risk para una estructura en construcción y lo que pide su prestamista o su contrato de construcción. En español, inglés o ruso.',
      linkLabel: 'Builders risk',
      serviceType: 'Seguro builders risk (riesgo de construcción)',
      intro: [
        { type: 'h2', text: 'Qué es el seguro builders risk' },
        { type: 'p', text: `La Asociación Nacional de Comisionados de Seguros (NAIC) describe el builders’ risk como una cobertura que “asegura contra pérdidas a edificios en proceso de construcción”, normalmente emitida en un formulario de reporte o de valor terminado ([glosario de la NAIC](${U.naic})). En palabras sencillas, está pensada para el período en que la estructura se está construyendo, antes de que entre una póliza de propiedad normal. Los formularios varían, así que lo que cubre una póliza concreta depende de su redacción.` },
        { type: 'p', text: 'En Florida se construye mucho: la Oficina del Censo de EE. UU. reporta **178,297 viviendas en 114,415 edificios** autorizadas con permiso de construcción en Florida en 2025.' },
        { type: 'h2', text: 'Quién suele necesitarlo' },
        { type: 'ul', items: [
          'Dueños que construyen una casa nueva, incluidos los que construyen como dueño-constructor (owner-builder)',
          'Contratistas generales y constructores, cuando el contrato los hace responsables de asegurar la obra',
          'Inversionistas y desarrolladores que construyen o renuevan a fondo una propiedad',
          'Cualquiera con un préstamo de construcción: los prestamistas a menudo exigen builders risk, así que revise los documentos de su préstamo para ver el requisito exacto',
        ] },
      ],
      covTitle: 'Cómo encaja el builders risk con otras coberturas',
      cov: [
        { h: 'Builders risk', p: 'Cubre la estructura en construcción. Las causas de pérdida cubiertas, los límites y los deducibles dependen de la póliza que elija.' },
        { h: 'Responsabilidad civil general', p: 'Una póliza aparte para lesiones o daños a terceros causados por la obra. Los contratistas suelen tener la suya; los dueños-constructores también deben preguntar por ella.' },
        { h: 'Compensación laboral', p: 'Una póliza aparte para empleados lesionados en el trabajo. El builders risk no la reemplaza.' },
        { h: 'Herramientas y equipos', p: 'Las herramientas y equipos propios de los contratistas normalmente se aseguran aparte con una póliza inland marine.' },
        { h: 'Seguro de propiedad al terminar', p: 'Cuando termina la construcción y se ocupa el edificio, debe haber una póliza permanente de vivienda o de propiedad comercial.' },
      ],
      body: [
        { type: 'h2', text: 'Lo que debe saber en Florida' },
        { type: 'h3', text: 'Viento, lluvia y etapa de la construcción' },
        { type: 'p', text: `En sus [preguntas frecuentes sobre seguros comerciales](${U.dfsBr}), el Departamento de Servicios Financieros de Florida señala que las pólizas builder’s risk son de riesgos nombrados y que la lluvia no es un riesgo nombrado en el contrato, aunque podría haber cobertura limitada para materiales en la obra dañados por lluvia si se incluye por endoso. El DFS agrega que los daños por viento deberían estar cubiertos, sujeto a otras disposiciones del contrato, y que algunas pólizas exigen que la construcción alcance cierta etapa, como el 50% o el 75% de avance, antes de que aplique la cobertura de viento. Cada póliza es distinta, así que revisamos estos puntos con usted en la cotización real.` },
        { type: 'h3', text: '¿Construye como dueño-constructor?' },
        { type: 'p', text: `La declaración de divulgación para dueños-constructores de Florida, incluida en el [§ 489.103](${U.fs489_103}), dice que el dueño-constructor es la parte responsable que figura en el permiso. También advierte que puede ser responsable por lesiones de trabajadores sin licencia en la propiedad y que el seguro de vivienda puede no cubrir esas lesiones. Si construye así, hable con nosotros sobre responsabilidad civil además del builders risk.` },
        { type: 'h3', text: 'Revise su préstamo y su contrato' },
        { type: 'p', text: 'Los préstamos y contratos de construcción a menudo indican quién debe comprar el builders risk, por qué monto y a quién se debe incluir en la póliza. Envíenos esas páginas con su solicitud para que la cotización corresponda.' },
        { type: 'h2', text: 'Qué tener a mano para cotizar' },
        { type: 'ul', items: [
          'Dirección del proyecto y breve descripción: casa nueva, ampliación, renovación o edificio comercial',
          'Tipo de construcción (por ejemplo, bloque de concreto o estructura de madera), número de pisos y pies cuadrados',
          'Valor terminado del proyecto',
          'Fecha de inicio y fecha estimada de terminación',
          'Etapa actual de la construcción, si la obra ya empezó',
          'Quiénes son el dueño, el contratista general y el prestamista',
          'Requisitos de seguro del préstamo o del contrato de construcción',
          'Seguridad de la obra: cerca, iluminación, cámaras',
        ] },
        { type: 'p', text: 'Cuando la casa esté terminada, vea [seguro para casas de nueva construcción](/es/new-construction-home-insurance-florida). Los contratistas también pueden ver [seguro para contratistas](/es/contractor-insurance-florida).' },
      ],
      faqTitle: 'Seguro builders risk: preguntas frecuentes',
      faq: [
        { q: '¿Mi póliza de vivienda cubre una casa que todavía se está construyendo?', a: 'No lo dé por hecho. Una casa en construcción se asegura comúnmente con una póliza builders risk hasta que se termina y entra una póliza permanente. Hable con nosotros antes de empezar la obra para que no queden huecos.' },
        { q: '¿Quién compra el builders risk, el dueño o el contratista?', a: 'Cualquiera de los dos, según el contrato de construcción y el prestamista. Esos documentos normalmente indican quién es responsable. Envíenoslos y le ayudamos a encontrar esa sección.' },
        { q: '¿El builders risk cubre daños por huracán?', a: 'Depende de la póliza. El DFS de Florida señala que los daños por viento deberían estar cubiertos sujeto a las demás disposiciones de la póliza, y que algunas pólizas exigen cierta etapa de avance antes de que aplique la cobertura de viento. Le mostramos cómo maneja el viento la póliza cotizada y qué deducible aplica.' },
        { q: '¿Cuánto dura una póliza builders risk?', a: 'Las pólizas se emiten por un plazo fijo que debe coincidir con su calendario de construcción. Pregúntenos qué opciones tiene si la obra se alarga más de lo previsto.' },
        { q: '¿Solo trabajan con proyectos cerca de Florida City?', a: 'No. Nuestra oficina está en Florida City, pero atendemos a dueños y contratistas que construyen en toda Florida por teléfono, mensaje de texto y correo, en español, inglés y ruso.' },
      ],
      sources: sources('es', ['naic', 'dfsBr', 'fs489_103', 'bps2025']),
    },
    ru: {
      metaTitle: 'Страховка builders risk во Флориде | M&K Agency',
      metaDesc: 'Страховка builders risk для строящихся домов и зданий во Флориде: кому она нужна, как работает и что подготовить для расчёта. Агент говорит по-русски.',
      breadcrumb: 'Страховка builders risk',
      kicker: 'Builders risk · Флорида',
      h1a: 'Страховка builders risk во Флориде —',
      h1b: 'для здания, пока оно строится.',
      sub: 'Владельцы, которые строят дом, подрядчики и девелоперы по всей Флориде: поможем разобраться со страховкой builders risk для строящегося объекта и с тем, что требует ваш кредитор или договор подряда. По-русски, по-английски или по-испански.',
      linkLabel: 'Builders risk',
      serviceType: 'Страхование строительных рисков (builders risk)',
      intro: [
        { type: 'h2', text: 'Что такое страховка builders risk' },
        { type: 'p', text: `Национальная ассоциация страховых комиссаров США (NAIC) описывает builders’ risk как страховку, которая «страхует от ущерба здания в процессе строительства» и обычно оформляется на форме с отчётностью или по стоимости завершённого объекта ([глоссарий NAIC](${U.naic})). Проще говоря, она рассчитана на период, пока объект строится, до того как вступит в силу обычный полис на имущество. Формы полисов различаются, поэтому покрытие конкретного полиса зависит от его формулировок.` },
        { type: 'p', text: 'Во Флориде много строят: по данным Бюро переписи США, в 2025 году во Флориде выданы разрешения на **178 297 единиц жилья в 114 415 зданиях**.' },
        { type: 'h2', text: 'Кому она обычно нужна' },
        { type: 'ul', items: [
          'Владельцам, которые строят новый дом, в том числе как owner-builder',
          'Генподрядчикам и строителям домов, если договор возлагает на них страхование объекта',
          'Инвесторам и девелоперам, которые строят или капитально реконструируют объект',
          'Всем, у кого строительный кредит: кредиторы часто требуют builders risk, поэтому проверьте точное требование в кредитных документах',
        ] },
      ],
      covTitle: 'Как builders risk сочетается с другими страховками',
      cov: [
        { h: 'Builders risk', p: 'Покрывает строящийся объект. Застрахованные риски, лимиты и франшизы зависят от выбранного полиса.' },
        { h: 'General liability (общая ответственность)', p: 'Отдельный полис на вред третьим лицам, причинённый работами. У подрядчиков обычно есть свой; owner-builder тоже стоит о нём спросить.' },
        { h: 'Workers’ compensation', p: 'Отдельный полис для работников, пострадавших на работе. Builders risk его не заменяет.' },
        { h: 'Инструмент и оборудование', p: 'Собственный инструмент и оборудование подрядчиков обычно страхуются отдельно полисом inland marine.' },
        { h: 'Страховка имущества после завершения', p: 'Когда стройка закончена и в здание заезжают, нужен постоянный полис — на дом или коммерческое имущество.' },
      ],
      body: [
        { type: 'h2', text: 'Что важно знать во Флориде' },
        { type: 'h3', text: 'Ветер, дождь и стадия строительства' },
        { type: 'p', text: `В своих [ответах на вопросы о коммерческом страховании](${U.dfsBr}) Департамент финансовых услуг Флориды отмечает, что полисы builder’s risk покрывают поименованные риски и что дождь не является поименованным риском в договоре, хотя возможно ограниченное покрытие материалов на объекте, повреждённых дождём, если оно включено эндорсментом. DFS добавляет, что ущерб от ветра должен покрываться с учётом других условий договора и что некоторые полисы требуют, чтобы строительство достигло определённой стадии — например, 50% или 75% готовности, — прежде чем начнёт действовать покрытие от ветра. Все полисы разные, поэтому мы разбираем эти пункты с вами на конкретном расчёте.` },
        { type: 'h3', text: 'Строите как owner-builder?' },
        { type: 'p', text: `Заявление owner-builder, текст которого приведён в [§ 489.103](${U.fs489_103}), говорит, что owner-builder — ответственное лицо, указанное в разрешении на строительство. Там же предупреждается, что владелец может отвечать за травмы нелицензированных работников на участке и что страховка дома может эти травмы не покрывать. Если вы строите так, поговорите с нами не только о builders risk, но и о страховке ответственности.` },
        { type: 'h3', text: 'Проверьте кредит и договор' },
        { type: 'p', text: 'В строительных кредитах и договорах подряда часто прописано, кто должен купить builders risk, на какую сумму и кого нужно вписать в полис. Пришлите нам эти страницы вместе с запросом, чтобы расчёт им соответствовал.' },
        { type: 'h2', text: 'Что подготовить для расчёта' },
        { type: 'ul', items: [
          'Адрес объекта и краткое описание: новый дом, пристройка, реконструкция или коммерческое здание',
          'Тип конструкции (например, бетонный блок или деревянный каркас), этажность и площадь',
          'Стоимость завершённого объекта',
          'Дата начала и ожидаемая дата окончания',
          'Текущая стадия строительства, если работы уже идут',
          'Кто владелец, генподрядчик и кредитор',
          'Требования к страховке из кредита или договора подряда',
          'Охрана объекта: забор, освещение, камеры',
        ] },
        { type: 'p', text: 'Когда дом будет готов, смотрите [страховку новостроек](/ru/new-construction-home-insurance-florida). Подрядчикам также пригодится [страховка для подрядчиков](/ru/contractor-insurance-florida).' },
      ],
      faqTitle: 'Страховка builders risk: частые вопросы',
      faq: [
        { q: 'Покроет ли мой полис на дом строящийся дом?', a: 'Не стоит на это рассчитывать. Строящийся дом обычно страхуют полисом builders risk, пока он не будет закончен и не начнёт действовать постоянный полис. Поговорите с нами до начала работ, чтобы не было пробела.' },
        { q: 'Кто покупает builders risk — владелец или подрядчик?', a: 'Любой из них, в зависимости от договора подряда и кредитора. Обычно в этих документах указано, кто отвечает за страховку. Пришлите их нам — поможем найти нужный раздел.' },
        { q: 'Покрывает ли builders risk ущерб от урагана?', a: 'Зависит от полиса. DFS Флориды отмечает, что ущерб от ветра должен покрываться с учётом прочих условий полиса и что некоторые полисы требуют определённой стадии готовности, прежде чем начнёт действовать покрытие от ветра. Мы покажем, как рассчитанный полис решает вопрос ветра и какая франшиза применяется.' },
        { q: 'На какой срок оформляется builders risk?', a: 'Полис оформляется на фиксированный срок, который должен совпадать с графиком строительства. Спросите нас, какие есть варианты, если стройка затянется.' },
        { q: 'Вы работаете только с объектами рядом с Florida City?', a: 'Нет. Наш офис во Florida City, но мы работаем с владельцами и подрядчиками, которые строят по всей Флориде, по телефону, SMS и email — по-русски, по-английски и по-испански.' },
      ],
      sources: sources('ru', ['naic', 'dfsBr', 'fs489_103', 'bps2025']),
    },
  },
};
