import type { BusinessPage } from './types';
import { SRC_URL as U, sources } from './sources';

export const CONTRACTORS: BusinessPage = {
  path: '/contractor-insurance-florida',
  icon: '🏗️',
  published: '2026-09-26',
  modified: '2026-09-26',
  team: ['mikhail-kozlov', 'jose-egues-chalela', 'craig-fernandes'],
  copy: {
    en: {
      metaTitle: 'Contractor Insurance in Florida | M&K Agency',
      metaDesc: 'Insurance for Florida contractors and trades: general liability, workers’ comp, work trucks and tools. Talk to an agent in English, Spanish or Russian.',
      breadcrumb: 'Contractor insurance',
      kicker: 'Contractor Insurance · Florida',
      h1a: 'Contractor insurance in Florida,',
      h1b: 'built around the work you actually do.',
      sub: 'General contractors, roofers, electricians, plumbers, HVAC and specialty trades across Florida: we help you line up general liability, workers’ comp, work-truck and tools coverage, and get certificates to your clients when a job needs them. In English, Spanish or Russian.',
      linkLabel: 'Contractors',
      serviceType: 'Contractor insurance',
      intro: [
        { type: 'h2', text: 'What Florida contractors are up against' },
        { type: 'p', text: 'Florida is one of the busiest construction markets in the country. U.S. Census Bureau permit data shows **178,297 new housing units** authorized by building permits in Florida in 2025. More jobs means more general contractors asking for certificates, more crews on ladders and roofs, and more trucks and trailers moving between job sites.' },
        { type: 'p', text: 'The claims that hurt contractors usually come from the same few places:' },
        { type: 'ul', items: [
          '**Damage to a client’s property:** a ladder through a window, a water line hit during demo, overspray on a neighbor’s car.',
          '**Injuries to people who aren’t on your crew:** a homeowner who trips over materials, a delivery driver hurt on site.',
          '**Injuries to your own workers:** falls, cuts, heat illness, back injuries from lifting.',
          '**Accidents on the road:** the work truck or a loaded trailer on the way to a job.',
          '**Stolen or damaged tools and equipment** from the truck, the job site or the shop.',
          '**Contract requirements:** GCs, property managers and HOAs often require specific limits, additional insured wording or a certificate before you can start.',
        ] },
      ],
      covTitle: 'Coverage that usually fits a contracting business',
      cov: [
        { h: 'General liability', p: 'Responds to claims that your work or your crew caused bodily injury or property damage to others, subject to the policy terms. It’s the policy clients ask for most often on a certificate.' },
        { h: 'Workers’ compensation', p: 'Pays medical bills and lost wages for employees hurt on the job. In Florida’s construction industry the requirement starts with the first employee.' },
        { h: 'Commercial auto', p: 'For pickups, vans and box trucks titled to the business or used mainly for work, plus the trailers you tow to the job.' },
        { h: 'Tools & equipment', p: 'Often called inland marine. Helps repair or replace tools and equipment that are stolen or damaged on the job, in transit or in storage.' },
        { h: 'Business owner’s policy', p: 'For eligible businesses, bundles general liability with coverage for business property such as a shop, office contents or inventory.' },
        { h: 'Umbrella / excess liability', p: 'Adds liability limits on top of your general liability and auto policies when a contract asks for more than your base limits.' },
      ],
      body: [
        { type: 'h2', text: 'Florida rules contractors should know' },
        { type: 'h3', text: 'Workers’ comp starts with one employee in construction' },
        { type: 'p', text: `Under [Florida Statutes § 440.02](${U.fs440_02}), most private employers need workers’ compensation once they have four or more employees, but in the **construction industry the threshold is one employee**. The same section counts sole proprietors and partners engaged in construction, and independent contractors working in construction, as employees for workers’ comp purposes.` },
        { type: 'p', text: `Corporate officers can elect an exemption instead. In construction, no more than three officers of a corporation (or a group of affiliated companies) may be exempt, and each must own at least 10% of the company and be listed as an officer with the Division of Corporations; an LLC member who owns at least 10% counts as an officer ([§ 440.02](${U.fs440_02})). The exemption is filed electronically with the Department of Financial Services, and a certificate is valid for two years ([§ 440.05](${U.fs440_05})).` },
        { type: 'h3', text: 'Your subcontractors are your problem too' },
        { type: 'p', text: `[Section 440.10](${U.fs440_10}) says a contractor shall require a subcontractor to provide evidence of workers’ compensation insurance, or a copy of an officer’s exemption certificate. If a sub has no coverage, the contractor can end up liable for that sub’s employees. Collect certificates before a sub starts and keep them on file.` },
        { type: 'h3', text: 'Licensed contractors attest to insurance' },
        { type: 'p', text: `Contractors certified or registered by the Construction Industry Licensing Board must attest, when the license is issued and at each renewal, that they carry workers’ compensation as required by chapter 440 and public liability and property damage insurance in amounts set by board rule ([§ 489.115](${U.fs489_115})). Electrical contractors are licensed by a separate board ([§ 489.507](${U.fs489_507})). You can look up any license on the [DBPR license search](${U.dbprLookup}).` },
        { type: 'h2', text: 'What to have ready for a quote' },
        { type: 'ul', items: [
          'Your trade(s) and license number, if you have one',
          'Business name, entity type (LLC, corporation, sole proprietor) and years in business',
          'Estimated revenue and payroll for the next 12 months',
          'Number of employees and how much of the work you sub out',
          'Residential vs. commercial work, and any new construction',
          'Vehicles (year, make, model, VIN) and who drives them',
          'Tools and equipment you want covered, with approximate values',
          'Contract or certificate requirements you’ve been given: limits, additional insured, waiver of subrogation',
          'Claims in the last three to five years',
        ] },
        { type: 'callout', title: 'Need a certificate for a job?', text: 'Send us the insurance section of the contract or the GC’s certificate request. We’ll go through the wording with you and tell you what your current policy can and can’t satisfy before you sign.' },
        { type: 'p', text: 'Related: [general liability](/en/insurance/general-liability), [commercial auto](/en/insurance/commercial-auto), [business owner’s policy](/en/insurance/business-owners-policy) and [umbrella insurance](/en/umbrella-insurance-florida-city).' },
      ],
      faqTitle: 'Contractor insurance: common questions',
      faq: [
        { q: 'Do I need workers’ comp if it’s just me?', a: 'It depends on how your business is set up. Florida law counts a sole proprietor or partner working in construction as an employee for workers’ comp purposes. A corporate officer or LLC member who owns at least 10% may be able to file an exemption with the state instead (up to three officers per company in construction). Many general contractors will ask for either a policy or an exemption certificate before you start. Call us and we’ll walk through your setup.' },
        { q: 'Does general liability cover my own tools or truck?', a: 'No. General liability is for injury or damage you cause to other people and their property. Your tools need tools and equipment (inland marine) coverage, and a work truck needs a commercial auto policy.' },
        { q: 'Can a client be listed as additional insured on my certificate?', a: 'Often, yes. Many general liability policies include or can add additional insured endorsements, but the wording varies. Send us the request and we’ll confirm what your policy supports before you promise it to a client.' },
        { q: 'Do you quote newer contracting businesses?', a: 'Yes. Insurance companies will look at your experience in the trade, the type of work you plan to take on and your expected revenue, so have those ready when you call.' },
        { q: 'Do you only work with contractors near Florida City?', a: 'No. Our office is in Florida City, but we work with contractors across Florida by phone, text and email, in English, Spanish and Russian.' },
      ],
      sources: sources('en', ['fs440_02', 'fs440_05', 'fs440_10', 'fs489_115', 'fs489_507', 'dbprLookup', 'bps2025']),
    },
    es: {
      metaTitle: 'Seguro para Contratistas en Florida | M&K Agency',
      metaDesc: 'Seguros para contratistas en Florida: responsabilidad civil, compensación laboral, camionetas de trabajo y herramientas. Atención en español, inglés o ruso.',
      breadcrumb: 'Seguro para contratistas',
      kicker: 'Seguro para contratistas · Florida',
      h1a: 'Seguro para contratistas en Florida,',
      h1b: 'a la medida del trabajo que usted hace.',
      sub: 'Contratistas generales, techadores, electricistas, plomeros, técnicos de aire acondicionado y oficios especializados en toda Florida: le ayudamos a reunir responsabilidad civil general, compensación laboral, seguro de camioneta de trabajo y de herramientas, y a enviar certificados a sus clientes cuando un trabajo los pide. En español, inglés o ruso.',
      linkLabel: 'Contratistas',
      serviceType: 'Seguro para contratistas',
      intro: [
        { type: 'h2', text: 'Los riesgos de un contratista en Florida' },
        { type: 'p', text: 'Florida es uno de los mercados de construcción más activos del país. Según los datos de permisos de la Oficina del Censo de EE. UU., en 2025 se autorizaron **178,297 viviendas nuevas** con permiso de construcción en Florida. Más obras significan más contratistas generales pidiendo certificados, más cuadrillas en escaleras y techos, y más camionetas y remolques entre una obra y otra.' },
        { type: 'p', text: 'Los reclamos que más afectan a los contratistas suelen venir de los mismos lugares:' },
        { type: 'ul', items: [
          '**Daños a la propiedad del cliente:** una escalera que rompe una ventana, una tubería de agua perforada durante la demolición, pintura rociada sobre el carro del vecino.',
          '**Lesiones a personas que no son de su equipo:** un dueño de casa que tropieza con materiales, un repartidor que se lastima en la obra.',
          '**Lesiones de sus propios trabajadores:** caídas, cortaduras, golpes de calor, lesiones de espalda al cargar peso.',
          '**Accidentes en la carretera:** la camioneta de trabajo o un remolque cargado camino a la obra.',
          '**Herramientas y equipos robados o dañados** en la camioneta, en la obra o en el taller.',
          '**Requisitos de contrato:** contratistas generales, administradores de propiedades y asociaciones de propietarios (HOA) a menudo exigen límites específicos, asegurado adicional o un certificado antes de empezar.',
        ] },
      ],
      covTitle: 'Coberturas que suelen necesitar los contratistas',
      cov: [
        { h: 'Responsabilidad civil general', p: 'Responde a reclamos de que su trabajo o su equipo causó lesiones o daños a la propiedad de terceros, según los términos de la póliza. Es la que los clientes piden con más frecuencia en un certificado.' },
        { h: 'Compensación laboral', p: 'Paga gastos médicos y salarios perdidos de empleados lesionados en el trabajo. En la industria de la construcción de Florida, la obligación empieza con el primer empleado.' },
        { h: 'Auto comercial', p: 'Para camionetas pickup, vans y camiones de caja a nombre del negocio o usados principalmente para trabajar, además de los remolques que lleva a la obra.' },
        { h: 'Herramientas y equipos', p: 'También llamado inland marine. Ayuda a reparar o reemplazar herramientas y equipos robados o dañados en la obra, en tránsito o guardados.' },
        { h: 'Póliza de dueño de negocio (BOP)', p: 'Para negocios elegibles, combina la responsabilidad civil general con cobertura para bienes del negocio, como un taller, el contenido de la oficina o el inventario.' },
        { h: 'Umbrella / responsabilidad en exceso', p: 'Agrega límites de responsabilidad por encima de sus pólizas de responsabilidad general y de auto cuando un contrato pide más de lo que tiene.' },
      ],
      body: [
        { type: 'h2', text: 'Reglas de Florida que todo contratista debe conocer' },
        { type: 'h3', text: 'En construcción, la compensación laboral empieza con un empleado' },
        { type: 'p', text: `Según los [Estatutos de Florida § 440.02](${U.fs440_02}), la mayoría de los empleadores privados necesitan compensación laboral a partir de cuatro empleados, pero en la **industria de la construcción basta con un empleado**. La misma sección considera empleados, a efectos de la compensación laboral, a los propietarios únicos y socios que trabajan en construcción y a los contratistas independientes del sector.` },
        { type: 'p', text: `Los oficiales de una corporación pueden elegir una exención. En construcción, no más de tres oficiales de una corporación (o de un grupo de empresas afiliadas) pueden estar exentos; cada uno debe ser dueño de al menos el 10% de la empresa y figurar como oficial en la División de Corporaciones. Un miembro de LLC con al menos el 10% cuenta como oficial ([§ 440.02](${U.fs440_02})). La exención se presenta por vía electrónica ante el Departamento de Servicios Financieros y el certificado es válido por dos años ([§ 440.05](${U.fs440_05})).` },
        { type: 'h3', text: 'Sus subcontratistas también son su responsabilidad' },
        { type: 'p', text: `La [sección 440.10](${U.fs440_10}) establece que el contratista debe exigir a cada subcontratista prueba de seguro de compensación laboral, o una copia del certificado de exención del oficial. Si un subcontratista no tiene cobertura, el contratista puede terminar respondiendo por los empleados de ese subcontratista. Pida los certificados antes de que empiece y guárdelos.` },
        { type: 'h3', text: 'Los contratistas con licencia declaran su seguro' },
        { type: 'p', text: `Los contratistas certificados o registrados ante la Junta de Licencias de la Industria de la Construcción deben declarar, al recibir la licencia y en cada renovación, que tienen compensación laboral según el capítulo 440 y seguro de responsabilidad pública y daños a la propiedad en los montos que fija la junta por reglamento ([§ 489.115](${U.fs489_115})). Los contratistas eléctricos tienen su propia junta de licencias ([§ 489.507](${U.fs489_507})). Puede verificar cualquier licencia en la [búsqueda de licencias del DBPR](${U.dbprLookup}).` },
        { type: 'h2', text: 'Qué tener a mano para cotizar' },
        { type: 'ul', items: [
          'Su oficio y número de licencia, si la tiene',
          'Nombre del negocio, tipo de entidad (LLC, corporación, propietario único) y años de operación',
          'Ingresos y nómina estimados para los próximos 12 meses',
          'Número de empleados y qué parte del trabajo subcontrata',
          'Trabajo residencial o comercial, y si hace construcción nueva',
          'Vehículos (año, marca, modelo, VIN) y quién los maneja',
          'Herramientas y equipos que quiere asegurar, con su valor aproximado',
          'Requisitos de contrato o de certificado: límites, asegurado adicional, renuncia de subrogación',
          'Reclamos de los últimos tres a cinco años',
        ] },
        { type: 'callout', title: '¿Le piden un certificado para una obra?', text: 'Envíenos la sección de seguros del contrato o la solicitud de certificado del contratista general. Revisamos la redacción con usted y le decimos qué puede cumplir su póliza actual y qué no, antes de firmar.' },
        { type: 'p', text: 'Relacionado: [responsabilidad civil general](/es/insurance/general-liability), [auto comercial](/es/insurance/commercial-auto), [póliza de dueño de negocio](/es/insurance/business-owners-policy) y [seguro umbrella](/es/umbrella-insurance-florida-city).' },
      ],
      faqTitle: 'Seguro para contratistas: preguntas frecuentes',
      faq: [
        { q: '¿Necesito compensación laboral si trabajo solo?', a: 'Depende de cómo esté organizado su negocio. La ley de Florida considera empleado, a efectos de la compensación laboral, al propietario único o socio que trabaja en construcción. Un oficial de corporación o miembro de LLC con al menos el 10% puede, en cambio, presentar una exención ante el estado (hasta tres oficiales por empresa en construcción). Muchos contratistas generales le pedirán una póliza o un certificado de exención antes de empezar. Llámenos y revisamos su caso.' },
        { q: '¿La responsabilidad civil general cubre mis herramientas o mi camioneta?', a: 'No. La responsabilidad civil general es para lesiones o daños que usted cause a otras personas y a sus bienes. Sus herramientas necesitan una cobertura de herramientas y equipos (inland marine) y la camioneta de trabajo, una póliza de auto comercial.' },
        { q: '¿Puedo incluir a un cliente como asegurado adicional en mi certificado?', a: 'Muchas veces, sí. Muchas pólizas de responsabilidad general incluyen o permiten agregar endosos de asegurado adicional, pero la redacción varía. Envíenos la solicitud y confirmamos lo que permite su póliza antes de que se lo prometa al cliente.' },
        { q: '¿Cotizan para empresas de construcción nuevas?', a: 'Sí. Las aseguradoras toman en cuenta su experiencia en el oficio, el tipo de trabajo que planea hacer y los ingresos que espera, así que tenga esos datos a mano cuando llame.' },
        { q: '¿Solo trabajan con contratistas cerca de Florida City?', a: 'No. Nuestra oficina está en Florida City, pero atendemos a contratistas en toda Florida por teléfono, mensaje de texto y correo, en español, inglés y ruso.' },
      ],
      sources: sources('es', ['fs440_02', 'fs440_05', 'fs440_10', 'fs489_115', 'fs489_507', 'dbprLookup', 'bps2025']),
    },
    ru: {
      metaTitle: 'Страховка для подрядчиков во Флориде | M&K Agency',
      metaDesc: 'Страхование подрядчиков во Флориде: общая ответственность, workers’ comp, рабочие машины и инструмент. Агент говорит по-русски, по-английски и по-испански.',
      breadcrumb: 'Страховка для подрядчиков',
      kicker: 'Страховка для подрядчиков · Флорида',
      h1a: 'Страховка для подрядчиков во Флориде —',
      h1b: 'под ту работу, которую вы реально делаете.',
      sub: 'Генподрядчики, кровельщики, электрики, сантехники, HVAC и узкие специалисты по всей Флориде: поможем собрать general liability, workers’ comp, страховку рабочих машин и инструмента и выдать сертификаты вашим заказчикам, когда их требует объект. По-русски, по-английски или по-испански.',
      linkLabel: 'Подрядчики',
      serviceType: 'Страхование подрядчиков',
      intro: [
        { type: 'h2', text: 'С какими рисками сталкиваются подрядчики во Флориде' },
        { type: 'p', text: 'Флорида — один из самых активных строительных рынков США. По данным Бюро переписи США о разрешениях на строительство, в 2025 году во Флориде было разрешено строительство **178 297 новых единиц жилья**. Больше объектов — больше генподрядчиков, требующих сертификаты, больше бригад на лестницах и крышах, больше пикапов и прицепов между объектами.' },
        { type: 'p', text: 'Самые болезненные претензии к подрядчикам обычно возникают в одних и тех же ситуациях:' },
        { type: 'ul', items: [
          '**Ущерб имуществу заказчика:** лестница, разбившая окно, перебитая при демонтаже водопроводная труба, краска на соседской машине.',
          '**Травмы посторонних людей:** хозяин дома споткнулся о материалы, курьер получил травму на объекте.',
          '**Травмы ваших работников:** падения, порезы, тепловой удар, травмы спины при подъёме тяжестей.',
          '**ДТП по дороге:** рабочий пикап или гружёный прицеп на пути к объекту.',
          '**Кража или поломка инструмента и оборудования** из машины, с объекта или из мастерской.',
          '**Требования договора:** генподрядчики, управляющие компании и HOA часто требуют определённые лимиты, статус additional insured или сертификат до начала работ.',
        ] },
      ],
      covTitle: 'Какие виды страховки обычно нужны подрядчику',
      cov: [
        { h: 'General liability (общая ответственность)', p: 'Покрывает претензии о том, что ваша работа или ваша бригада причинили вред здоровью или имуществу третьих лиц, в рамках условий полиса. Именно этот полис заказчики чаще всего просят в сертификате.' },
        { h: 'Workers’ compensation', p: 'Оплачивает лечение и потерянный заработок работников, пострадавших на работе. В строительной отрасли Флориды обязанность возникает с первого работника.' },
        { h: 'Коммерческое авто', p: 'Для пикапов, фургонов и box truck, оформленных на бизнес или используемых в основном для работы, а также прицепов, которые вы возите на объект.' },
        { h: 'Инструмент и оборудование', p: 'Также называется inland marine. Помогает отремонтировать или заменить инструмент и оборудование, украденные или повреждённые на объекте, в дороге или на складе.' },
        { h: 'Business owner’s policy (BOP)', p: 'Для подходящих бизнесов объединяет общую ответственность со страховкой имущества бизнеса: мастерской, офисного имущества, запасов.' },
        { h: 'Umbrella / excess liability', p: 'Добавляет лимиты ответственности поверх полисов general liability и авто, когда договор требует больше базовых лимитов.' },
      ],
      body: [
        { type: 'h2', text: 'Правила Флориды, которые должен знать подрядчик' },
        { type: 'h3', text: 'В строительстве workers’ comp нужен уже с одним работником' },
        { type: 'p', text: `Согласно [Статутам Флориды § 440.02](${U.fs440_02}), большинству частных работодателей workers’ compensation нужен с четырёх работников, но в **строительной отрасли порог — один работник**. Та же статья для целей workers’ comp считает работниками индивидуальных предпринимателей и партнёров, занятых в строительстве, а также независимых подрядчиков, работающих в строительстве.` },
        { type: 'p', text: `Должностные лица корпорации могут вместо этого оформить освобождение (exemption). В строительстве освобождение могут получить не более трёх должностных лиц корпорации (или группы аффилированных компаний); каждый должен владеть не менее 10% компании и значиться должностным лицом в Division of Corporations. Участник LLC с долей от 10% считается должностным лицом ([§ 440.02](${U.fs440_02})). Заявление подаётся электронно в Департамент финансовых услуг, сертификат действует два года ([§ 440.05](${U.fs440_05})).` },
        { type: 'h3', text: 'Субподрядчики — тоже ваша ответственность' },
        { type: 'p', text: `[Статья 440.10](${U.fs440_10}) обязывает подрядчика требовать от субподрядчика подтверждение страховки workers’ compensation или копию сертификата освобождения должностного лица. Если у субподрядчика нет покрытия, отвечать за его работников может подрядчик. Собирайте сертификаты до начала работ и храните их.` },
        { type: 'h3', text: 'Лицензированные подрядчики подтверждают наличие страховки' },
        { type: 'p', text: `Подрядчики, сертифицированные или зарегистрированные Construction Industry Licensing Board, при выдаче лицензии и при каждом продлении подтверждают, что у них есть workers’ compensation по главе 440 и страховка публичной ответственности и ущерба имуществу в размерах, установленных правилами совета ([§ 489.115](${U.fs489_115})). Электрики лицензируются отдельным советом ([§ 489.507](${U.fs489_507})). Проверить любую лицензию можно в [поиске лицензий DBPR](${U.dbprLookup}).` },
        { type: 'h2', text: 'Что подготовить для расчёта' },
        { type: 'ul', items: [
          'Ваша специализация и номер лицензии, если есть',
          'Название бизнеса, форма (LLC, корпорация, ИП) и сколько лет работаете',
          'Ожидаемая выручка и фонд оплаты труда на ближайшие 12 месяцев',
          'Количество работников и какую часть работ отдаёте на субподряд',
          'Жилые или коммерческие объекты, есть ли новое строительство',
          'Машины (год, марка, модель, VIN) и кто за рулём',
          'Инструмент и оборудование, которые нужно застраховать, с примерной стоимостью',
          'Требования договора или сертификата: лимиты, additional insured, waiver of subrogation',
          'Страховые случаи за последние три–пять лет',
        ] },
        { type: 'callout', title: 'Нужен сертификат для объекта?', text: 'Пришлите раздел договора о страховании или запрос сертификата от генподрядчика. Разберём формулировки вместе и скажем, что ваш текущий полис покрывает, а что нет, до того как вы подпишете договор.' },
        { type: 'p', text: 'См. также: [общая ответственность](/ru/insurance/general-liability), [коммерческое авто](/ru/insurance/commercial-auto), [business owner’s policy](/ru/insurance/business-owners-policy) и [umbrella-страховка](/ru/umbrella-insurance-florida-city).' },
      ],
      faqTitle: 'Страховка для подрядчиков: частые вопросы',
      faq: [
        { q: 'Нужен ли workers’ comp, если я работаю один?', a: 'Зависит от того, как оформлен бизнес. Закон Флориды для целей workers’ comp считает работником индивидуального предпринимателя или партнёра, работающего в строительстве. Должностное лицо корпорации или участник LLC с долей от 10% может вместо этого оформить освобождение в штате (в строительстве — до трёх человек на компанию). Многие генподрядчики до начала работ попросят либо полис, либо сертификат освобождения. Позвоните — разберём вашу ситуацию.' },
        { q: 'Покрывает ли general liability мой инструмент или машину?', a: 'Нет. General liability — это вред, который вы причиняете другим людям и их имуществу. Для инструмента нужна страховка инструмента и оборудования (inland marine), для рабочей машины — полис коммерческого авто.' },
        { q: 'Можно ли вписать заказчика как additional insured в мой сертификат?', a: 'Часто да. Многие полисы общей ответственности включают или позволяют добавить эндорсмент additional insured, но формулировки отличаются. Пришлите запрос — мы проверим, что допускает ваш полис, прежде чем вы пообещаете это заказчику.' },
        { q: 'Вы делаете расчёт для новых строительных компаний?', a: 'Да. Страховые компании смотрят на ваш опыт в профессии, виды работ, которые вы планируете, и ожидаемую выручку, так что подготовьте эти данные к звонку.' },
        { q: 'Вы работаете только с подрядчиками рядом с Florida City?', a: 'Нет. Наш офис во Florida City, но мы работаем с подрядчиками по всей Флориде по телефону, SMS и email — по-русски, по-английски и по-испански.' },
      ],
      sources: sources('ru', ['fs440_02', 'fs440_05', 'fs440_10', 'fs489_115', 'fs489_507', 'dbprLookup', 'bps2025']),
    },
  },
};
