import type { BusinessPage } from './types';
import { SRC_URL as U, sources } from './sources';

export const HANDYMAN: BusinessPage = {
  path: '/handyman-insurance-florida',
  icon: '🛠️',
  published: '2026-09-26',
  modified: '2026-09-26',
  team: ['mikhail-kozlov', 'craig-fernandes', 'carolina-silva'],
  copy: {
    en: {
      metaTitle: 'Handyman Insurance in Florida | M&K Agency',
      metaDesc: 'Insurance for Florida handymen and small repair businesses: general liability, tools, work vans, workers’ comp. Agents speak English, Spanish, Russian.',
      breadcrumb: 'Handyman insurance',
      kicker: 'Handyman Insurance · Florida',
      h1a: 'Handyman insurance in Florida,',
      h1b: 'for the jobs you do inside people’s homes.',
      sub: 'Repairs, installs, assembly, drywall patches, fixtures and punch lists across Florida: we help one-person and small handyman businesses cover liability, tools and the work van, and answer the certificate requests that come with property-management work. In English, Spanish or Russian.',
      linkLabel: 'Handyman',
      serviceType: 'Handyman insurance',
      intro: [
        { type: 'h2', text: 'Small jobs, real exposure' },
        { type: 'p', text: 'A handyman spends the day inside other people’s homes and rental units, which is exactly why a small mistake can turn into a large claim. The U.S. Census Bureau counts **10,287 residential remodeling establishments** with paid employees in Florida (County Business Patterns, 2023), and many more handymen work on their own.' },
        { type: 'p', text: 'Typical problems we hear about:' },
        { type: 'ul', items: [
          'A supply line or toilet you installed leaks and damages floors and cabinets.',
          'A TV mount or shelf pulls out of the wall and injures someone or breaks what’s underneath.',
          'You scratch hardwood floors, crack countertops or damage furniture while working.',
          'A tenant or homeowner trips over your tools or drop cloth.',
          'You fall from a ladder, or cut or burn yourself on the job.',
          'Your tools are stolen from the van while you’re inside a customer’s home.',
          'A property manager won’t send more work until you provide a certificate of insurance.',
        ] },
      ],
      covTitle: 'Coverage that usually fits a handyman business',
      cov: [
        { h: 'General liability', p: 'For claims that your work caused injury to someone or damage to their property, such as a leak from a fixture you installed, subject to the policy terms. Property managers usually ask for it on a certificate.' },
        { h: 'Tools & equipment', p: 'Inland marine coverage for your power tools, ladders and equipment, in the van, at the job or in storage.' },
        { h: 'Commercial auto', p: 'For the van or pickup you use for the business. A personal auto policy may not cover a vehicle used mainly for work, so tell us how you use it.' },
        { h: 'Workers’ compensation', p: 'Once you hire help, workers’ comp pays medical bills and lost wages if they’re hurt on the job. The threshold depends on the kind of work you do (see below).' },
        { h: 'Business owner’s policy', p: 'For eligible businesses, combines general liability with coverage for business property, such as a small shop or stored materials.' },
      ],
      body: [
        { type: 'h2', text: 'Florida points for handymen' },
        { type: 'h3', text: 'The $2,500 minor-work exemption has limits' },
        { type: 'p', text: `Florida’s contractor licensing law exempts work “of a casual, minor, or inconsequential nature” when the total contract price for labor, materials and everything else is less than $2,500 ([§ 489.103](${U.fs489_103})). The exemption does **not** apply if the job is part of a larger or major operation, if a job is split into smaller contracts to stay under the limit, or to a person who advertises as a contractor or otherwise says they are qualified to engage in contracting. Work outside that exemption may require a state contractor license; you can check licenses on the [DBPR license search](${U.dbprLookup}).` },
        { type: 'p', text: 'Why it matters for insurance: when we quote, we describe your operations as they actually are. If you take on work that needs a license, tell us, so the policy matches the work you do.' },
        { type: 'h3', text: 'Workers’ comp when you hire help' },
        { type: 'p', text: `[Florida Statutes § 440.02](${U.fs440_02}) requires workers’ compensation for most private employers with four or more employees, and for construction-industry employers with one or more. The statute’s definition of construction includes substantial improvement in the size or use of any structure. If your jobs are mostly repairs and installs, ask us which threshold applies before you bring on a helper.` },
        { type: 'h2', text: 'What to have ready for a quote' },
        { type: 'ul', items: [
          'The kinds of jobs you do, and any you don’t (roofing, electrical panels, gas lines, etc.)',
          'Whether you hold a contractor license, and which one',
          'Estimated revenue for the next 12 months and your largest typical job',
          'Helpers or employees, and any work you sub out',
          'Homeowners vs. landlords and property managers',
          'Your van or truck (year, make, model, VIN) and who drives it',
          'Tools and equipment you want covered, with approximate values',
          'Claims in the last three to five years',
        ] },
        { type: 'callout', title: 'Working for a property manager?', text: 'Forward us their certificate request. Many ask to be listed as additional insured; we’ll confirm what your policy supports and get the certificate issued once the policy is in place.' },
        { type: 'p', text: 'Related: [general liability](/en/insurance/general-liability), [commercial auto](/en/insurance/commercial-auto) and [contractor insurance](/en/contractor-insurance-florida).' },
      ],
      faqTitle: 'Handyman insurance: common questions',
      faq: [
        { q: 'Do I need a license to work as a handyman in Florida?', a: 'State law exempts casual, minor or inconsequential work when the total contract price is under $2,500, but not if the job is part of a larger operation, is split up to stay under the limit, or if you advertise as a contractor. Work beyond that may require a state contractor license. When in doubt, check with the state licensing board before you take the job.' },
        { q: 'Does general liability pay if a fixture I installed leaks?', a: 'Water damage to the customer’s property caused by your work is the kind of claim general liability is meant to address, subject to the policy’s terms, limits and deductible. It usually won’t pay to redo your own work, so ask us to explain what your policy excludes.' },
        { q: 'Can I use my personal car insurance for my work van?', a: 'Not always. Personal auto policies may exclude or limit a vehicle used mainly for business. Tell us how the vehicle is used and titled, and we’ll tell you whether you need a commercial auto policy.' },
        { q: 'I work alone. What do I need first?', a: 'Most solo handymen start with general liability, because that’s what customers and property managers ask for, and add tools coverage and the right auto policy. Call us and we’ll go through your situation.' },
        { q: 'Do you only work with handymen near Florida City?', a: 'No. Our office is in Florida City, but we work with handyman businesses across Florida by phone, text and email, in English, Spanish and Russian.' },
      ],
      sources: sources('en', ['fs489_103', 'fs440_02', 'dbprLookup', 'cbp2023']),
    },
    es: {
      metaTitle: 'Seguro para Handyman en Florida | M&K Agency',
      metaDesc: 'Seguros para handyman y pequeños negocios de reparaciones en Florida: responsabilidad civil, herramientas, van de trabajo y compensación laboral. En español.',
      breadcrumb: 'Seguro para handyman',
      kicker: 'Seguro para handyman · Florida',
      h1a: 'Seguro para handyman en Florida,',
      h1b: 'para los trabajos que hace dentro de casas ajenas.',
      sub: 'Reparaciones, instalaciones, armado de muebles, parches de drywall, accesorios y listas de pendientes en toda Florida: ayudamos a handymen independientes y pequeños negocios a cubrir la responsabilidad civil, las herramientas y la van de trabajo, y a responder a las solicitudes de certificado de los administradores de propiedades. En español, inglés o ruso.',
      linkLabel: 'Handyman',
      serviceType: 'Seguro para handyman',
      intro: [
        { type: 'h2', text: 'Trabajos pequeños, riesgos reales' },
        { type: 'p', text: 'Un handyman pasa el día dentro de casas y apartamentos de otras personas, y por eso un error pequeño puede convertirse en un reclamo grande. La Oficina del Censo de EE. UU. cuenta **10,287 establecimientos de remodelación residencial** con empleados en Florida (County Business Patterns, 2023), y muchos otros handymen trabajan por su cuenta.' },
        { type: 'p', text: 'Problemas que escuchamos con frecuencia:' },
        { type: 'ul', items: [
          'Una manguera de suministro o un inodoro que usted instaló gotea y daña pisos y gabinetes.',
          'Un soporte de TV o un estante se desprende de la pared y lastima a alguien o rompe lo que hay debajo.',
          'Raya un piso de madera, agrieta una encimera o daña muebles mientras trabaja.',
          'Un inquilino o el dueño de la casa tropieza con sus herramientas o con la lona.',
          'Usted se cae de una escalera, o se corta o se quema trabajando.',
          'Le roban las herramientas de la van mientras está dentro de la casa del cliente.',
          'Un administrador de propiedades no le da más trabajo hasta que presente un certificado de seguro.',
        ] },
      ],
      covTitle: 'Coberturas que suelen necesitar los handymen',
      cov: [
        { h: 'Responsabilidad civil general', p: 'Para reclamos de que su trabajo lesionó a alguien o dañó su propiedad, como una fuga de un accesorio que instaló, según los términos de la póliza. Los administradores de propiedades suelen pedirla en un certificado.' },
        { h: 'Herramientas y equipos', p: 'Cobertura inland marine para sus herramientas eléctricas, escaleras y equipos, en la van, en el trabajo o guardados.' },
        { h: 'Auto comercial', p: 'Para la van o pickup que usa en el negocio. Una póliza de auto personal puede no cubrir un vehículo usado principalmente para trabajar, así que díganos cómo lo usa.' },
        { h: 'Compensación laboral', p: 'Cuando contrata ayudantes, paga gastos médicos y salarios perdidos si se lastiman trabajando. El umbral depende del tipo de trabajo (vea abajo).' },
        { h: 'Póliza de dueño de negocio (BOP)', p: 'Para negocios elegibles, combina responsabilidad civil general con cobertura para bienes del negocio, como un pequeño taller o materiales guardados.' },
      ],
      body: [
        { type: 'h2', text: 'Lo que un handyman debe saber en Florida' },
        { type: 'h3', text: 'La exención de $2,500 para trabajos menores tiene límites' },
        { type: 'p', text: `La ley de licencias de contratistas de Florida exime los trabajos “de naturaleza casual, menor o intrascendente” cuando el precio total del contrato, incluyendo mano de obra, materiales y todo lo demás, es menor de $2,500 ([§ 489.103](${U.fs489_103})). La exención **no** aplica si el trabajo es parte de una obra mayor, si se divide en contratos más pequeños para quedar por debajo del límite, ni a quien se anuncia como contratista o dice estar calificado para hacer trabajos de contratista. Los trabajos fuera de esa exención pueden requerir una licencia estatal de contratista; puede verificar licencias en la [búsqueda de licencias del DBPR](${U.dbprLookup}).` },
        { type: 'p', text: 'Por qué importa para el seguro: al cotizar describimos sus operaciones tal como son. Si acepta trabajos que requieren licencia, díganoslo para que la póliza corresponda al trabajo que hace.' },
        { type: 'h3', text: 'Compensación laboral cuando contrata ayuda' },
        { type: 'p', text: `Los [Estatutos de Florida § 440.02](${U.fs440_02}) exigen compensación laboral a la mayoría de los empleadores privados con cuatro o más empleados, y a los de la industria de la construcción desde uno. La definición de construcción del estatuto incluye la mejora sustancial en el tamaño o el uso de cualquier estructura. Si sus trabajos son sobre todo reparaciones e instalaciones, pregúntenos qué umbral le aplica antes de contratar a un ayudante.` },
        { type: 'h2', text: 'Qué tener a mano para cotizar' },
        { type: 'ul', items: [
          'Los tipos de trabajo que hace, y los que no hace (techos, paneles eléctricos, líneas de gas, etc.)',
          'Si tiene licencia de contratista, y cuál',
          'Ingresos estimados para los próximos 12 meses y el tamaño de su trabajo típico más grande',
          'Ayudantes o empleados, y si subcontrata trabajo',
          'Si trabaja para dueños de casa o para arrendadores y administradores de propiedades',
          'Su van o camioneta (año, marca, modelo, VIN) y quién la maneja',
          'Herramientas y equipos que quiere asegurar, con su valor aproximado',
          'Reclamos de los últimos tres a cinco años',
        ] },
        { type: 'callout', title: '¿Trabaja para un administrador de propiedades?', text: 'Reenvíenos su solicitud de certificado. Muchos piden figurar como asegurado adicional; confirmamos lo que permite su póliza y emitimos el certificado cuando la póliza esté vigente.' },
        { type: 'p', text: 'Relacionado: [responsabilidad civil general](/es/insurance/general-liability), [auto comercial](/es/insurance/commercial-auto) y [seguro para contratistas](/es/contractor-insurance-florida).' },
      ],
      faqTitle: 'Seguro para handyman: preguntas frecuentes',
      faq: [
        { q: '¿Necesito licencia para trabajar como handyman en Florida?', a: 'La ley estatal exime los trabajos casuales, menores o intrascendentes cuando el precio total del contrato es menor de $2,500, pero no si el trabajo es parte de una obra mayor, si se divide para quedar por debajo del límite, o si usted se anuncia como contratista. Los trabajos más allá de eso pueden requerir una licencia estatal de contratista. Si tiene dudas, consulte con la junta estatal de licencias antes de aceptar el trabajo.' },
        { q: '¿La responsabilidad civil general paga si gotea un accesorio que instalé?', a: 'Los daños por agua a la propiedad del cliente causados por su trabajo son el tipo de reclamo que atiende la responsabilidad civil general, según los términos, límites y deducible de la póliza. Normalmente no paga por rehacer su propio trabajo, así que pídanos que le expliquemos las exclusiones de su póliza.' },
        { q: '¿Puedo usar mi seguro de auto personal para la van de trabajo?', a: 'No siempre. Las pólizas de auto personal pueden excluir o limitar un vehículo usado principalmente para el negocio. Díganos cómo usa el vehículo y a nombre de quién está, y le diremos si necesita una póliza de auto comercial.' },
        { q: 'Trabajo solo. ¿Qué necesito primero?', a: 'La mayoría de los handymen independientes empiezan con responsabilidad civil general, porque es lo que piden clientes y administradores, y agregan cobertura de herramientas y la póliza de auto adecuada. Llámenos y revisamos su caso.' },
        { q: '¿Solo trabajan con handymen cerca de Florida City?', a: 'No. Nuestra oficina está en Florida City, pero atendemos a handymen en toda Florida por teléfono, mensaje de texto y correo, en español, inglés y ruso.' },
      ],
      sources: sources('es', ['fs489_103', 'fs440_02', 'dbprLookup', 'cbp2023']),
    },
    ru: {
      metaTitle: 'Страховка для хендимена во Флориде | M&K Agency',
      metaDesc: 'Страхование хендименов и небольших ремонтных бизнесов во Флориде: ответственность, инструмент, рабочий фургон и workers’ comp. Агент говорит по-русски.',
      breadcrumb: 'Страховка для хендимена',
      kicker: 'Страховка для хендимена · Флорида',
      h1a: 'Страховка для хендимена во Флориде —',
      h1b: 'для работы в чужих домах.',
      sub: 'Мелкий ремонт, установка, сборка мебели, заделка гипсокартона, сантехника и светильники по всей Флориде: помогаем хендименам-одиночкам и небольшим командам застраховать ответственность, инструмент и рабочий фургон и отвечать на запросы сертификатов от управляющих компаний. По-русски, по-английски или по-испански.',
      linkLabel: 'Хендимен',
      serviceType: 'Страхование хендименов',
      intro: [
        { type: 'h2', text: 'Мелкие работы — реальные риски' },
        { type: 'p', text: 'Хендимен проводит день в чужих домах и съёмных квартирах, и именно поэтому небольшая ошибка может обернуться крупной претензией. Бюро переписи США насчитывает во Флориде **10 287 предприятий по ремонту жилья** с наёмными работниками (County Business Patterns, 2023), и ещё больше хендименов работают в одиночку.' },
        { type: 'p', text: 'Типичные ситуации, о которых мы слышим:' },
        { type: 'ul', items: [
          'Подводка или унитаз, который вы установили, протекает и портит полы и шкафы.',
          'Кронштейн телевизора или полка вырывается из стены, травмирует человека или разбивает то, что внизу.',
          'Вы поцарапали паркет, треснула столешница или пострадала мебель во время работы.',
          'Жилец или хозяин спотыкается о ваш инструмент или укрывную плёнку.',
          'Вы падаете с лестницы, режетесь или обжигаетесь на работе.',
          'Инструмент крадут из фургона, пока вы в доме у клиента.',
          'Управляющая компания не даёт новых заказов, пока вы не предоставите сертификат страховки.',
        ] },
      ],
      covTitle: 'Какие виды страховки обычно нужны хендимену',
      cov: [
        { h: 'General liability (общая ответственность)', p: 'Для претензий о том, что ваша работа причинила вред человеку или его имуществу — например, протечка из установленной вами сантехники, — в рамках условий полиса. Управляющие компании обычно просят его в сертификате.' },
        { h: 'Инструмент и оборудование', p: 'Страховка inland marine для электроинструмента, лестниц и оборудования — в фургоне, на объекте или на хранении.' },
        { h: 'Коммерческое авто', p: 'Для фургона или пикапа, который вы используете в бизнесе. Личный автополис может не покрывать машину, используемую в основном для работы, — расскажите нам, как вы ею пользуетесь.' },
        { h: 'Workers’ compensation', p: 'Когда вы нанимаете помощника, оплачивает лечение и потерянный заработок при травме на работе. Порог зависит от вида работ (см. ниже).' },
        { h: 'Business owner’s policy (BOP)', p: 'Для подходящих бизнесов объединяет общую ответственность со страховкой имущества бизнеса — небольшой мастерской или хранящихся материалов.' },
      ],
      body: [
        { type: 'h2', text: 'Что важно знать хендимену во Флориде' },
        { type: 'h3', text: 'Исключение для мелких работ до $2,500 имеет ограничения' },
        { type: 'p', text: `Закон Флориды о лицензировании подрядчиков освобождает работы «случайного, мелкого или незначительного характера», если общая цена договора — труд, материалы и всё остальное — меньше $2,500 ([§ 489.103](${U.fs489_103})). Исключение **не** действует, если работа — часть более крупного проекта, если её разбили на мелкие договоры, чтобы уложиться в лимит, а также для того, кто рекламирует себя как подрядчика или иначе заявляет о квалификации для подрядных работ. Работы за пределами этого исключения могут требовать лицензии подрядчика штата; проверить лицензии можно в [поиске лицензий DBPR](${U.dbprLookup}).` },
        { type: 'p', text: 'Почему это важно для страховки: при расчёте мы описываем вашу деятельность такой, какая она есть. Если вы берёте работы, требующие лицензии, скажите нам, чтобы полис соответствовал реальной работе.' },
        { type: 'h3', text: 'Workers’ comp, когда вы нанимаете помощника' },
        { type: 'p', text: `[Статуты Флориды § 440.02](${U.fs440_02}) требуют workers’ compensation у большинства частных работодателей с четырьмя и более работниками, а в строительной отрасли — уже с одним. Определение строительства в статуте включает существенное изменение размера или назначения любого сооружения. Если вы в основном занимаетесь ремонтом и установкой, спросите нас, какой порог к вам относится, до того как нанять помощника.` },
        { type: 'h2', text: 'Что подготовить для расчёта' },
        { type: 'ul', items: [
          'Какие работы вы делаете, а какие нет (кровля, электрощиты, газ и т.п.)',
          'Есть ли у вас лицензия подрядчика и какая',
          'Ожидаемая выручка на 12 месяцев и размер самого крупного типичного заказа',
          'Помощники или работники, отдаёте ли работу на субподряд',
          'Кто ваши клиенты: владельцы домов или арендодатели и управляющие компании',
          'Фургон или пикап (год, марка, модель, VIN) и кто за рулём',
          'Инструмент и оборудование, которые нужно застраховать, с примерной стоимостью',
          'Страховые случаи за последние три–пять лет',
        ] },
        { type: 'callout', title: 'Работаете с управляющей компанией?', text: 'Перешлите нам их запрос сертификата. Многие просят вписать их как additional insured; мы проверим, что допускает ваш полис, и выпустим сертификат, когда полис будет оформлен.' },
        { type: 'p', text: 'См. также: [общая ответственность](/ru/insurance/general-liability), [коммерческое авто](/ru/insurance/commercial-auto) и [страховка для подрядчиков](/ru/contractor-insurance-florida).' },
      ],
      faqTitle: 'Страховка для хендимена: частые вопросы',
      faq: [
        { q: 'Нужна ли лицензия, чтобы работать хендименом во Флориде?', a: 'Закон штата освобождает случайные, мелкие или незначительные работы, если общая цена договора меньше $2,500, но не в случае, когда работа — часть более крупного проекта, разбита на части ради лимита или если вы рекламируете себя как подрядчика. Работы сверх этого могут требовать лицензии подрядчика штата. Если сомневаетесь, уточните в лицензионном совете штата до того, как брать заказ.' },
        { q: 'Заплатит ли general liability, если протечёт установленная мной сантехника?', a: 'Ущерб от воды имуществу клиента, причинённый вашей работой, — это тот тип претензий, для которого существует general liability, в рамках условий, лимитов и франшизы полиса. Переделку вашей собственной работы он обычно не оплачивает, поэтому попросите нас объяснить исключения вашего полиса.' },
        { q: 'Можно ли использовать личную автостраховку для рабочего фургона?', a: 'Не всегда. Личные автополисы могут исключать или ограничивать покрытие машины, используемой в основном для бизнеса. Расскажите, как используется машина и на кого она оформлена, и мы скажем, нужен ли полис коммерческого авто.' },
        { q: 'Я работаю один. С чего начать?', a: 'Большинство хендименов-одиночек начинают с general liability — именно его просят клиенты и управляющие компании, — а затем добавляют страховку инструмента и подходящий автополис. Позвоните — разберём вашу ситуацию.' },
        { q: 'Вы работаете только с хендименами рядом с Florida City?', a: 'Нет. Наш офис во Florida City, но мы работаем с хендименами по всей Флориде по телефону, SMS и email — по-русски, по-английски и по-испански.' },
      ],
      sources: sources('ru', ['fs489_103', 'fs440_02', 'dbprLookup', 'cbp2023']),
    },
  },
};
