import type { BusinessPage } from './types';
import { SRC_URL as U, sources } from './sources';

export const LANDSCAPING: BusinessPage = {
  path: '/landscaping-insurance-florida',
  icon: '🌴',
  published: '2026-09-26',
  modified: '2026-09-26',
  team: ['mikhail-kozlov', 'elena-de-ona', 'shane-henry'],
  copy: {
    en: {
      metaTitle: 'Landscaping & Lawn Care Insurance in Florida | M&K Agency',
      metaDesc: 'Insurance for Florida lawn care and landscaping businesses: general liability, workers’ comp, trucks, trailers and mowers. English, Spanish or Russian.',
      breadcrumb: 'Landscaping insurance',
      kicker: 'Landscaping & Lawn Care · Florida',
      h1a: 'Landscaping insurance in Florida,',
      h1b: 'for crews that work all year.',
      sub: 'Lawn care, landscape maintenance, installation and irrigation businesses across Florida: we help you cover the liability, the crew, the truck and trailer, and the mowers and equipment that keep you working. In English, Spanish or Russian.',
      linkLabel: 'Landscaping',
      serviceType: 'Landscaping and lawn care insurance',
      intro: [
        { type: 'h2', text: 'Where landscaping businesses get hurt' },
        { type: 'p', text: 'In Florida the growing season barely stops, so crews are out almost every week of the year, in the heat, next to homes, parked cars and pool enclosures. The U.S. Census Bureau counts **10,670 landscaping services establishments** with paid employees in Florida (County Business Patterns, 2023), and that’s before counting the many owner-operators working on their own.' },
        { type: 'p', text: 'Most claims in this trade are small and sudden:' },
        { type: 'ul', items: [
          'A rock or debris thrown by a mower or string trimmer breaks a window or chips a car.',
          'A crew member cuts an irrigation line, landscape lighting or a buried cable.',
          'A customer or passer-by trips over a hose or equipment left on a walkway.',
          'Crew injuries: blade cuts, heat illness, falls from ladders during trimming, back strain.',
          'A trailer comes loose, or equipment falls off it on the road.',
          'Mowers, blowers and trimmers are stolen from an open trailer overnight.',
          'Herbicide or fertilizer drift damages a customer’s plants or a neighbor’s lawn.',
        ] },
      ],
      covTitle: 'Coverage that usually fits a landscaping business',
      cov: [
        { h: 'General liability', p: 'For claims that your crew injured someone or damaged someone else’s property while working, such as a broken window or a cut irrigation line, subject to the policy terms.' },
        { h: 'Workers’ compensation', p: 'Pays medical bills and lost wages if a crew member is hurt on the job. Whether and when it’s required depends on your headcount and the kind of work you do (see below).' },
        { h: 'Commercial auto', p: 'For the pickup or stake-bed truck that pulls your trailer. Tell us about every trailer so it’s listed correctly.' },
        { h: 'Tools & equipment', p: 'Inland marine coverage for mowers, blowers, trimmers, edgers and other equipment, on the trailer, at the job or in storage.' },
        { h: 'Business owner’s policy', p: 'For eligible businesses with a yard, shop or office, combines general liability with coverage for business property.' },
        { h: 'Umbrella / excess liability', p: 'Extra liability limits over your general liability and auto policies, useful when HOA or commercial-property contracts ask for higher limits.' },
      ],
      body: [
        { type: 'h2', text: 'Florida points for landscaping businesses' },
        { type: 'h3', text: 'Workers’ comp: four employees, or one in construction' },
        { type: 'p', text: `[Florida Statutes § 440.02](${U.fs440_02}) requires workers’ compensation for most private employers with four or more employees, and for construction-industry employers with even one. The statute’s definition of construction includes clearing, filling, excavation and substantial improvement in the appearance of any land, and the state sets the detailed classifications by rule. If your crews only mow and maintain, the four-employee threshold is the usual starting point; if you also clear land, grade, dig or install hardscape, ask us to check which rule applies to your business.` },
        { type: 'h3', text: 'Applying herbicides or pesticides?' },
        { type: 'p', text: `Florida has a limited certification for commercial landscape maintenance personnel who apply herbicides to control weeds in plant beds, driveways, sidewalks and patios, or apply certain lower-toxicity pesticides to ornamental plants with handheld or backpack equipment ([§ 482.156](${U.fs482_156})). Before the state issues that certification, the applicant must furnish proof of a certificate of insurance showing the employer meets the minimum bodily injury and property damage requirements of § 482.071(4). If anyone on your crew needs this certification, tell us so your certificate is set up correctly.` },
        { type: 'h3', text: 'HOA and commercial contracts' },
        { type: 'p', text: 'Property managers, HOAs and commercial clients usually ask for a certificate of insurance before you start, often with specific limits and additional insured wording. Send us the contract language and we’ll check it against your policy.' },
        { type: 'h2', text: 'What to have ready for a quote' },
        { type: 'ul', items: [
          'Services you offer: mowing and maintenance, installation, irrigation, hardscape, chemical application',
          'Number of crew members and estimated payroll for the next 12 months',
          'Estimated revenue, and the share from residential, HOA and commercial clients',
          'Trucks (year, make, model, VIN), trailers and drivers',
          'Equipment list with approximate values, and where it’s kept overnight',
          'Any certificate or contract requirements you’ve been given',
          'Claims in the last three to five years',
        ] },
        { type: 'p', text: 'Related: [general liability](/en/insurance/general-liability), [commercial auto](/en/insurance/commercial-auto) and [business owner’s policy](/en/insurance/business-owners-policy).' },
      ],
      faqTitle: 'Landscaping insurance: common questions',
      faq: [
        { q: 'Would general liability cover a window broken by my mower?', a: 'Accidental damage to a customer’s or neighbor’s property caused by your work is the kind of claim general liability is designed for, subject to the policy’s terms, limits and deductible. Damage to your own mower is not covered by general liability; that needs tools and equipment coverage.' },
        { q: 'Are my mowers covered while they’re on the trailer?', a: 'Usually not by general liability or your auto policy. Equipment on a trailer is typically covered under a tools and equipment (inland marine) policy. Some policies set conditions for theft from an unattended trailer, so ask us to go over them.' },
        { q: 'Do I need workers’ comp for my lawn crew?', a: 'Florida requires it for most private employers with four or more employees, and for construction-industry employers with one or more. Whether your work counts as construction depends on what you do, for example land clearing or hardscape versus routine maintenance. Call us and we’ll look at your situation.' },
        { q: 'Can you quote HOA and commercial maintenance contracts?', a: 'Yes. Those contracts often require specific limits and additional insured wording, so send us the insurance section of the contract with your request.' },
        { q: 'Do you only work with landscapers near Florida City?', a: 'No. Our office is in Florida City, but we work with landscaping businesses across Florida by phone, text and email, in English, Spanish and Russian.' },
      ],
      sources: sources('en', ['fs440_02', 'fs482_156', 'cbp2023']),
    },
    es: {
      metaTitle: 'Seguro para Jardinería y Paisajismo en Florida | M&K Agency',
      metaDesc: 'Seguros para negocios de jardinería y paisajismo en Florida: responsabilidad civil, compensación laboral, camionetas, remolques y cortadoras. En español.',
      breadcrumb: 'Seguro para jardinería',
      kicker: 'Jardinería y paisajismo · Florida',
      h1a: 'Seguro para jardinería en Florida,',
      h1b: 'para cuadrillas que trabajan todo el año.',
      sub: 'Negocios de corte de césped, mantenimiento de jardines, instalación y riego en toda Florida: le ayudamos a cubrir la responsabilidad civil, a su equipo, la camioneta y el remolque, y las cortadoras y equipos con los que trabaja. En español, inglés o ruso.',
      linkLabel: 'Jardinería',
      serviceType: 'Seguro para jardinería y paisajismo',
      intro: [
        { type: 'h2', text: 'Dónde se lastiman los negocios de jardinería' },
        { type: 'p', text: 'En Florida la temporada de crecimiento casi no se detiene, así que las cuadrillas salen casi todas las semanas del año, con calor, junto a casas, carros estacionados y jaulas de piscina. La Oficina del Censo de EE. UU. cuenta **10,670 establecimientos de servicios de paisajismo** con empleados en Florida (County Business Patterns, 2023), sin contar a los muchos que trabajan por su cuenta.' },
        { type: 'p', text: 'La mayoría de los reclamos en este oficio son pequeños y repentinos:' },
        { type: 'ul', items: [
          'Una piedra lanzada por la cortadora o la desbrozadora rompe una ventana o golpea un carro.',
          'Alguien del equipo corta una línea de riego, la iluminación del jardín o un cable enterrado.',
          'Un cliente o un peatón tropieza con una manguera o con equipo dejado en la acera.',
          'Lesiones del equipo: cortes, golpes de calor, caídas de escaleras al podar, lesiones de espalda.',
          'Un remolque se suelta, o se cae equipo en la carretera.',
          'Roban cortadoras, sopladoras y desbrozadoras de un remolque abierto durante la noche.',
          'El herbicida o el fertilizante daña las plantas del cliente o el césped del vecino.',
        ] },
      ],
      covTitle: 'Coberturas que suelen necesitar los negocios de jardinería',
      cov: [
        { h: 'Responsabilidad civil general', p: 'Para reclamos de que su equipo lesionó a alguien o dañó la propiedad de otra persona mientras trabajaba, como una ventana rota o una línea de riego cortada, según los términos de la póliza.' },
        { h: 'Compensación laboral', p: 'Paga gastos médicos y salarios perdidos si alguien de su cuadrilla se lastima trabajando. Si es obligatoria y desde cuándo depende de cuántos empleados tiene y del tipo de trabajo (vea abajo).' },
        { h: 'Auto comercial', p: 'Para la pickup o el camión de plataforma que remolca su tráiler. Infórmenos de cada remolque para que quede bien listado.' },
        { h: 'Herramientas y equipos', p: 'Cobertura inland marine para cortadoras, sopladoras, desbrozadoras, bordeadoras y otros equipos, en el remolque, en el trabajo o guardados.' },
        { h: 'Póliza de dueño de negocio (BOP)', p: 'Para negocios elegibles con patio, taller u oficina, combina responsabilidad civil general con cobertura para los bienes del negocio.' },
        { h: 'Umbrella / responsabilidad en exceso', p: 'Límites adicionales de responsabilidad sobre sus pólizas de responsabilidad general y de auto, útiles cuando contratos de HOA o comerciales piden límites más altos.' },
      ],
      body: [
        { type: 'h2', text: 'Lo que un negocio de jardinería debe saber en Florida' },
        { type: 'h3', text: 'Compensación laboral: cuatro empleados, o uno en construcción' },
        { type: 'p', text: `Los [Estatutos de Florida § 440.02](${U.fs440_02}) exigen compensación laboral a la mayoría de los empleadores privados con cuatro o más empleados, y a los de la industria de la construcción desde uno. La definición de construcción del estatuto incluye el desmonte, el relleno, la excavación y la mejora sustancial en la apariencia de cualquier terreno, y el estado fija las clasificaciones detalladas por reglamento. Si sus cuadrillas solo cortan y dan mantenimiento, el punto de partida habitual es el umbral de cuatro empleados; si además desmontan, nivelan, excavan o instalan hardscape, pídanos que revisemos qué regla aplica a su negocio.` },
        { type: 'h3', text: '¿Aplica herbicidas o pesticidas?' },
        { type: 'p', text: `Florida tiene una certificación limitada para el personal de mantenimiento de jardines comerciales que aplica herbicidas para controlar malezas en canteros, entradas, aceras y patios, o ciertos pesticidas de baja toxicidad en plantas ornamentales con equipo manual o de mochila ([§ 482.156](${U.fs482_156})). Antes de emitir esa certificación, el solicitante debe presentar un certificado de seguro que demuestre que el empleador cumple con los requisitos mínimos de lesiones corporales y daños a la propiedad del § 482.071(4). Si alguien de su equipo necesita esta certificación, avísenos para preparar bien su certificado.` },
        { type: 'h3', text: 'Contratos con HOA y clientes comerciales' },
        { type: 'p', text: 'Los administradores de propiedades, las asociaciones de propietarios y los clientes comerciales suelen pedir un certificado de seguro antes de empezar, muchas veces con límites específicos y asegurado adicional. Envíenos el texto del contrato y lo comparamos con su póliza.' },
        { type: 'h2', text: 'Qué tener a mano para cotizar' },
        { type: 'ul', items: [
          'Servicios que ofrece: corte y mantenimiento, instalación, riego, hardscape, aplicación de químicos',
          'Número de personas en su equipo y nómina estimada para los próximos 12 meses',
          'Ingresos estimados y qué parte viene de clientes residenciales, HOA y comerciales',
          'Camionetas (año, marca, modelo, VIN), remolques y choferes',
          'Lista de equipos con su valor aproximado, y dónde se guardan de noche',
          'Requisitos de certificado o de contrato que le hayan dado',
          'Reclamos de los últimos tres a cinco años',
        ] },
        { type: 'p', text: 'Relacionado: [responsabilidad civil general](/es/insurance/general-liability), [auto comercial](/es/insurance/commercial-auto) y [póliza de dueño de negocio](/es/insurance/business-owners-policy).' },
      ],
      faqTitle: 'Seguro para jardinería: preguntas frecuentes',
      faq: [
        { q: '¿La responsabilidad civil general cubre una ventana rota por mi cortadora?', a: 'Los daños accidentales a la propiedad de un cliente o de un vecino causados por su trabajo son el tipo de reclamo para el que existe la responsabilidad civil general, según los términos, límites y deducible de la póliza. Los daños a su propia cortadora no los cubre la responsabilidad general; para eso está la cobertura de herramientas y equipos.' },
        { q: '¿Mis cortadoras están cubiertas mientras van en el remolque?', a: 'Normalmente no por la responsabilidad general ni por su póliza de auto. El equipo en un remolque suele cubrirse con una póliza de herramientas y equipos (inland marine). Algunas pólizas ponen condiciones para robos de un remolque sin vigilancia, así que pídanos que se las expliquemos.' },
        { q: '¿Necesito compensación laboral para mi cuadrilla?', a: 'Florida la exige a la mayoría de los empleadores privados con cuatro o más empleados, y a los de construcción desde uno. Que su trabajo cuente como construcción depende de lo que hace, por ejemplo desmonte o hardscape frente a mantenimiento de rutina. Llámenos y revisamos su caso.' },
        { q: '¿Pueden cotizar contratos de mantenimiento para HOA y clientes comerciales?', a: 'Sí. Esos contratos suelen exigir límites específicos y asegurado adicional, así que envíenos la sección de seguros del contrato junto con su solicitud.' },
        { q: '¿Solo trabajan con jardineros cerca de Florida City?', a: 'No. Nuestra oficina está en Florida City, pero atendemos negocios de jardinería en toda Florida por teléfono, mensaje de texto y correo, en español, inglés y ruso.' },
      ],
      sources: sources('es', ['fs440_02', 'fs482_156', 'cbp2023']),
    },
    ru: {
      metaTitle: 'Страховка для ландшафтного бизнеса во Флориде | M&K Agency',
      metaDesc: 'Страхование ландшафтного бизнеса и ухода за газонами во Флориде: ответственность, workers’ comp, пикапы, прицепы и газонокосилки. Агент говорит по-русски.',
      breadcrumb: 'Страховка для ландшафтного бизнеса',
      kicker: 'Ландшафт и уход за газонами · Флорида',
      h1a: 'Страховка для ландшафтного бизнеса во Флориде —',
      h1b: 'для бригад, которые работают круглый год.',
      sub: 'Стрижка газонов, обслуживание территорий, озеленение и полив по всей Флориде: поможем застраховать ответственность, бригаду, пикап с прицепом и газонокосилки с оборудованием, на которых держится работа. По-русски, по-английски или по-испански.',
      linkLabel: 'Ландшафт и газоны',
      serviceType: 'Страхование ландшафтного бизнеса',
      intro: [
        { type: 'h2', text: 'Где ландшафтный бизнес чаще всего теряет деньги' },
        { type: 'p', text: 'Во Флориде сезон роста почти не заканчивается, поэтому бригады работают практически каждую неделю года — в жару, рядом с домами, машинами и сетками бассейнов. Бюро переписи США насчитывает во Флориде **10 670 предприятий ландшафтных услуг** с наёмными работниками (County Business Patterns, 2023) — и это без учёта тех, кто работает в одиночку.' },
        { type: 'p', text: 'Большинство претензий в этой профессии небольшие и внезапные:' },
        { type: 'ul', items: [
          'Камень из-под газонокосилки или триммера разбивает окно или бьёт машину.',
          'Работник перерезает трубу полива, садовую подсветку или подземный кабель.',
          'Клиент или прохожий спотыкается о шланг или оборудование на дорожке.',
          'Травмы бригады: порезы, тепловой удар, падение с лестницы при обрезке, травмы спины.',
          'Отцепляется прицеп или с него падает оборудование на дороге.',
          'За ночь из открытого прицепа крадут косилки, воздуходувки и триммеры.',
          'Гербицид или удобрение повреждает растения клиента или газон соседа.',
        ] },
      ],
      covTitle: 'Какие виды страховки обычно нужны ландшафтному бизнесу',
      cov: [
        { h: 'General liability (общая ответственность)', p: 'Для претензий о том, что ваша бригада во время работы травмировала человека или повредила чужое имущество — разбитое окно, перерезанный полив, — в рамках условий полиса.' },
        { h: 'Workers’ compensation', p: 'Оплачивает лечение и потерянный заработок, если работник пострадал на работе. Обязательна ли она и с какого момента, зависит от числа работников и вида работ (см. ниже).' },
        { h: 'Коммерческое авто', p: 'Для пикапа или бортового грузовика, который тянет прицеп. Сообщите нам о каждом прицепе, чтобы он был правильно вписан.' },
        { h: 'Инструмент и оборудование', p: 'Страховка inland marine для газонокосилок, воздуходувок, триммеров, кромкорезов и другого оборудования — на прицепе, на объекте или на хранении.' },
        { h: 'Business owner’s policy (BOP)', p: 'Для подходящих бизнесов с площадкой, мастерской или офисом объединяет общую ответственность со страховкой имущества бизнеса.' },
        { h: 'Umbrella / excess liability', p: 'Дополнительные лимиты ответственности поверх полисов general liability и авто — пригодятся, когда договоры с HOA или коммерческими объектами требуют больших лимитов.' },
      ],
      body: [
        { type: 'h2', text: 'Что важно знать ландшафтному бизнесу во Флориде' },
        { type: 'h3', text: 'Workers’ comp: четыре работника, а в строительстве — один' },
        { type: 'p', text: `[Статуты Флориды § 440.02](${U.fs440_02}) требуют workers’ compensation у большинства частных работодателей с четырьмя и более работниками, а в строительной отрасли — уже с одним. Определение строительства в статуте включает расчистку, засыпку, земляные работы и существенное улучшение внешнего вида любого участка земли, а подробные классификации штат устанавливает правилами. Если ваши бригады только стригут и обслуживают, обычно отправная точка — порог в четыре работника; если вы также расчищаете участки, выравниваете, копаете или укладываете hardscape, попросите нас проверить, какое правило применяется к вашему бизнесу.` },
        { type: 'h3', text: 'Работаете с гербицидами или пестицидами?' },
        { type: 'p', text: `Во Флориде есть ограниченная сертификация для персонала коммерческого ухода за ландшафтом, который применяет гербициды против сорняков на клумбах, подъездных дорожках, тротуарах и патио или некоторые пестициды низкой токсичности на декоративных растениях с ручным или ранцевым оборудованием ([§ 482.156](${U.fs482_156})). Прежде чем штат выдаст такую сертификацию, заявитель должен предоставить сертификат страховки, подтверждающий, что работодатель соответствует минимальным требованиям по вреду здоровью и ущербу имуществу из § 482.071(4). Если кому-то из вашей бригады нужна эта сертификация, скажите нам — подготовим сертификат правильно.` },
        { type: 'h3', text: 'Договоры с HOA и коммерческими клиентами' },
        { type: 'p', text: 'Управляющие компании, HOA и коммерческие клиенты обычно просят сертификат страховки до начала работ, часто с определёнными лимитами и статусом additional insured. Пришлите текст договора — сверим его с вашим полисом.' },
        { type: 'h2', text: 'Что подготовить для расчёта' },
        { type: 'ul', items: [
          'Какие услуги вы оказываете: стрижка и обслуживание, озеленение, полив, hardscape, обработка химикатами',
          'Сколько человек в бригаде и ожидаемый фонд оплаты труда на 12 месяцев',
          'Ожидаемая выручка и доля частных клиентов, HOA и коммерческих объектов',
          'Машины (год, марка, модель, VIN), прицепы и водители',
          'Список оборудования с примерной стоимостью и где оно хранится ночью',
          'Требования к сертификату или договору, если есть',
          'Страховые случаи за последние три–пять лет',
        ] },
        { type: 'p', text: 'См. также: [общая ответственность](/ru/insurance/general-liability), [коммерческое авто](/ru/insurance/commercial-auto) и [business owner’s policy](/ru/insurance/business-owners-policy).' },
      ],
      faqTitle: 'Страховка для ландшафтного бизнеса: частые вопросы',
      faq: [
        { q: 'Покроет ли general liability окно, разбитое моей газонокосилкой?', a: 'Случайный ущерб имуществу клиента или соседа, причинённый вашей работой, — именно тот тип претензий, для которого существует general liability, в рамках условий, лимитов и франшизы полиса. Поломку вашей собственной косилки general liability не покрывает — для этого нужна страховка инструмента и оборудования.' },
        { q: 'Застрахованы ли мои косилки, пока они на прицепе?', a: 'Обычно ни general liability, ни автополис этого не покрывают. Оборудование на прицепе, как правило, страхуется полисом инструмента и оборудования (inland marine). В некоторых полисах есть условия для кражи из оставленного без присмотра прицепа — попросите нас их разъяснить.' },
        { q: 'Нужен ли workers’ comp для моей бригады?', a: 'Флорида требует его у большинства частных работодателей с четырьмя и более работниками, а в строительстве — с одного. Считается ли ваша работа строительством, зависит от того, что именно вы делаете: например, расчистка участков или hardscape против регулярного обслуживания. Позвоните — разберём вашу ситуацию.' },
        { q: 'Можете сделать расчёт под договоры с HOA и коммерческими объектами?', a: 'Да. Такие договоры часто требуют определённых лимитов и статуса additional insured, поэтому пришлите вместе с запросом раздел договора о страховании.' },
        { q: 'Вы работаете только с ландшафтными компаниями рядом с Florida City?', a: 'Нет. Наш офис во Florida City, но мы работаем с ландшафтным бизнесом по всей Флориде по телефону, SMS и email — по-русски, по-английски и по-испански.' },
      ],
      sources: sources('ru', ['fs440_02', 'fs482_156', 'cbp2023']),
    },
  },
};
