import type { BusinessPage } from './types';
import { SRC_URL as U, sources } from './sources';

export const PAINTING: BusinessPage = {
  path: '/painting-contractor-insurance-florida',
  icon: '🎨',
  published: '2026-09-26',
  modified: '2026-09-26',
  team: ['mikhail-kozlov', 'jose-egues-chalela', 'carolina-silva'],
  copy: {
    en: {
      metaTitle: 'Painting Contractor Insurance in Florida | M&K Agency',
      metaDesc: 'Insurance for Florida painting contractors: general liability for overspray and spills, workers’ comp, sprayers and ladders, work vans. English, Spanish, Russian.',
      breadcrumb: 'Painting contractor insurance',
      kicker: 'Painting Contractors · Florida',
      h1a: 'Painting contractor insurance in Florida,',
      h1b: 'for interior, exterior and commercial crews.',
      sub: 'Residential repaints, new construction, commercial and HOA work across Florida: we help painting businesses cover overspray and spill claims, the crew on ladders, the sprayers and the vans, and get certificates to GCs and property managers. In English, Spanish or Russian.',
      linkLabel: 'Painting',
      serviceType: 'Painting contractor insurance',
      intro: [
        { type: 'h2', text: 'The risks behind a paint job' },
        { type: 'p', text: 'Florida sun and humidity keep painters busy on repaints as well as new construction. The U.S. Census Bureau counts **4,421 painting and wall covering contractor establishments** with paid employees in Florida (County Business Patterns, 2023). Most claims in this trade have little to do with the paint itself:' },
        { type: 'ul', items: [
          'Overspray drifts onto a neighbor’s car, a boat or a screen enclosure.',
          'A spilled bucket ruins carpet, tile grout or hardwood.',
          'Tape or prep work pulls off finishes, or pressure washing before painting forces water inside.',
          'A homeowner or tenant trips over a drop cloth or ladder.',
          'A painter falls from a ladder or scaffold, or suffers heat illness on an exterior job.',
          'Airless sprayers and ladders are stolen from the van or the job site.',
          'A GC won’t let your crew on site without a certificate, or asks for additional insured wording.',
        ] },
      ],
      covTitle: 'Coverage that usually fits a painting business',
      cov: [
        { h: 'General liability', p: 'For claims that your work caused injury to someone or damage to their property, such as overspray on a car or a spill on a floor, subject to the policy terms. Redoing your own work is usually not covered.' },
        { h: 'Workers’ compensation', p: 'Pays medical bills and lost wages for employees hurt on the job, such as a ladder fall. If your work is in the construction industry, Florida requires it from the first employee.' },
        { h: 'Commercial auto', p: 'For the vans and pickups that carry your crew, ladders and paint, including racks and any trailer.' },
        { h: 'Tools & equipment', p: 'Inland marine coverage for airless sprayers, pressure washers, ladders, scaffolding and other gear, in the van, on the job or in storage.' },
        { h: 'Business owner’s policy', p: 'For eligible businesses with a shop or storage unit, combines general liability with coverage for business property and stored materials.' },
        { h: 'Umbrella / excess liability', p: 'Extra liability limits over your general liability and auto policies when commercial or HOA contracts require higher limits.' },
      ],
      body: [
        { type: 'h2', text: 'Florida points for painting contractors' },
        { type: 'h3', text: 'Workers’ comp: know which threshold applies' },
        { type: 'p', text: `[Florida Statutes § 440.02](${U.fs440_02}) requires workers’ compensation for most private employers with four or more employees, and for construction-industry employers with one or more. The same section counts sole proprietors, partners and independent contractors working in construction as employees. If your painting work falls within the construction industry under the statute and the state’s classification rules, the one-employee threshold applies, so check before you hire or use helpers paid as independent contractors.` },
        { type: 'h3', text: 'Working as a subcontractor' },
        { type: 'p', text: `Florida law says a contractor shall require a subcontractor to provide evidence of workers’ compensation insurance, or a copy of an officer’s exemption certificate ([§ 440.10](${U.fs440_10})). If you paint for general contractors or builders, expect to be asked for one or the other before you start, along with a general liability certificate.` },
        { type: 'h2', text: 'What to have ready for a quote' },
        { type: 'ul', items: [
          'Interior, exterior or both; residential, commercial, HOA or new construction',
          'Whether you spray, and whether you pressure wash as part of prep',
          'The tallest buildings you paint and whether you use scaffolding or lifts',
          'Number of employees, helpers and subcontractors, with estimated payroll',
          'Estimated revenue for the next 12 months',
          'Vehicles (year, make, model, VIN) and drivers',
          'Equipment you want covered, with approximate values',
          'Contract or certificate requirements you’ve been given',
          'Claims in the last three to five years',
        ] },
        { type: 'p', text: 'Related: [contractor insurance](/en/contractor-insurance-florida), [pressure washing insurance](/en/pressure-washing-insurance-florida) and [general liability](/en/insurance/general-liability).' },
      ],
      faqTitle: 'Painting contractor insurance: common questions',
      faq: [
        { q: 'Would general liability pay for overspray on a neighbor’s car?', a: 'Accidental damage to someone else’s property caused by your work is the kind of claim general liability is designed for, subject to the policy’s terms, limits and deductible. It won’t pay to repaint a wall the customer didn’t like; that’s your own workmanship.' },
        { q: 'Do I need workers’ comp as a painter in Florida?', a: 'It depends on your headcount and on whether your work falls within the construction industry. Construction employers need it from the first employee, and the statute also counts sole proprietors and partners working in construction as employees. Corporate officers and LLC members who own at least 10% may be able to file an exemption. Call us and we’ll go through your setup.' },
        { q: 'A GC asked for additional insured and waiver of subrogation. Can I get that?', a: 'Many policies can add those endorsements, but the wording varies. Send us the contract or the certificate request and we’ll confirm what your policy supports before you sign.' },
        { q: 'Are my sprayers covered when they’re in the van?', a: 'Not by general liability or usually by the auto policy. Sprayers and other equipment are typically covered under a tools and equipment (inland marine) policy. Ask us about any conditions for theft from a vehicle.' },
        { q: 'Do you only work with painters near Florida City?', a: 'No. Our office is in Florida City, but we work with painting contractors across Florida by phone, text and email, in English, Spanish and Russian.' },
      ],
      sources: sources('en', ['fs440_02', 'fs440_10', 'cbp2023']),
    },
    es: {
      metaTitle: 'Seguro para Contratistas de Pintura en Florida | M&K Agency',
      metaDesc: 'Seguros para pintores en Florida: responsabilidad civil por pintura rociada y derrames, compensación laboral, equipos, escaleras y vans de trabajo. En español.',
      breadcrumb: 'Seguro para pintores',
      kicker: 'Contratistas de pintura · Florida',
      h1a: 'Seguro para contratistas de pintura en Florida,',
      h1b: 'para trabajos de interior, exterior y comerciales.',
      sub: 'Repintados residenciales, construcción nueva, trabajos comerciales y de HOA en toda Florida: ayudamos a negocios de pintura a cubrir reclamos por pintura rociada y derrames, al equipo en escaleras, las máquinas de pintar y las vans, y a enviar certificados a contratistas generales y administradores. En español, inglés o ruso.',
      linkLabel: 'Pintura',
      serviceType: 'Seguro para contratistas de pintura',
      intro: [
        { type: 'h2', text: 'Los riesgos detrás de un trabajo de pintura' },
        { type: 'p', text: 'El sol y la humedad de Florida mantienen ocupados a los pintores tanto en repintados como en construcción nueva. La Oficina del Censo de EE. UU. cuenta **4,421 establecimientos de contratistas de pintura y revestimiento de paredes** con empleados en Florida (County Business Patterns, 2023). La mayoría de los reclamos en este oficio tienen poco que ver con la pintura en sí:' },
        { type: 'ul', items: [
          'La pintura rociada cae sobre el carro de un vecino, un bote o una jaula de piscina.',
          'Un cubo derramado arruina una alfombra, la lechada de las losas o un piso de madera.',
          'La cinta o la preparación arrancan acabados, o el lavado a presión antes de pintar mete agua a la casa.',
          'Un dueño de casa o inquilino tropieza con una lona o una escalera.',
          'Un pintor se cae de una escalera o un andamio, o sufre un golpe de calor en un trabajo exterior.',
          'Roban máquinas airless y escaleras de la van o de la obra.',
          'Un contratista general no deja entrar a su equipo sin certificado, o pide asegurado adicional.',
        ] },
      ],
      covTitle: 'Coberturas que suelen necesitar los negocios de pintura',
      cov: [
        { h: 'Responsabilidad civil general', p: 'Para reclamos de que su trabajo lesionó a alguien o dañó su propiedad, como pintura rociada sobre un carro o un derrame en el piso, según los términos de la póliza. Rehacer su propio trabajo normalmente no está cubierto.' },
        { h: 'Compensación laboral', p: 'Paga gastos médicos y salarios perdidos de empleados lesionados, por ejemplo en una caída de escalera. Si su trabajo es de la industria de la construcción, Florida la exige desde el primer empleado.' },
        { h: 'Auto comercial', p: 'Para las vans y pickups que llevan a su equipo, escaleras y pintura, incluidos portaescaleras y cualquier remolque.' },
        { h: 'Herramientas y equipos', p: 'Cobertura inland marine para máquinas airless, hidrolavadoras, escaleras, andamios y demás equipo, en la van, en la obra o guardado.' },
        { h: 'Póliza de dueño de negocio (BOP)', p: 'Para negocios elegibles con taller o bodega, combina responsabilidad civil general con cobertura para bienes del negocio y materiales guardados.' },
        { h: 'Umbrella / responsabilidad en exceso', p: 'Límites adicionales de responsabilidad sobre sus pólizas de responsabilidad general y de auto cuando contratos comerciales o de HOA piden límites más altos.' },
      ],
      body: [
        { type: 'h2', text: 'Lo que un contratista de pintura debe saber en Florida' },
        { type: 'h3', text: 'Compensación laboral: sepa qué umbral le aplica' },
        { type: 'p', text: `Los [Estatutos de Florida § 440.02](${U.fs440_02}) exigen compensación laboral a la mayoría de los empleadores privados con cuatro o más empleados, y a los de la industria de la construcción desde uno. La misma sección considera empleados a los propietarios únicos, socios y contratistas independientes que trabajan en construcción. Si su trabajo de pintura entra en la industria de la construcción según el estatuto y las reglas de clasificación del estado, aplica el umbral de un empleado; verifíquelo antes de contratar o de usar ayudantes pagados como contratistas independientes.` },
        { type: 'h3', text: 'Si trabaja como subcontratista' },
        { type: 'p', text: `La ley de Florida establece que el contratista debe exigir a cada subcontratista prueba de seguro de compensación laboral, o una copia del certificado de exención del oficial ([§ 440.10](${U.fs440_10})). Si pinta para contratistas generales o constructores, espere que le pidan uno u otro antes de empezar, junto con un certificado de responsabilidad general.` },
        { type: 'h2', text: 'Qué tener a mano para cotizar' },
        { type: 'ul', items: [
          'Interior, exterior o ambos; residencial, comercial, HOA o construcción nueva',
          'Si pinta con pistola y si hace lavado a presión como preparación',
          'Los edificios más altos que pinta y si usa andamios o plataformas elevadoras',
          'Número de empleados, ayudantes y subcontratistas, con la nómina estimada',
          'Ingresos estimados para los próximos 12 meses',
          'Vehículos (año, marca, modelo, VIN) y choferes',
          'Equipos que quiere asegurar, con su valor aproximado',
          'Requisitos de contrato o de certificado que le hayan dado',
          'Reclamos de los últimos tres a cinco años',
        ] },
        { type: 'p', text: 'Relacionado: [seguro para contratistas](/es/contractor-insurance-florida), [seguro para lavado a presión](/es/pressure-washing-insurance-florida) y [responsabilidad civil general](/es/insurance/general-liability).' },
      ],
      faqTitle: 'Seguro para pintores: preguntas frecuentes',
      faq: [
        { q: '¿La responsabilidad civil general paga por pintura rociada sobre el carro de un vecino?', a: 'Los daños accidentales a la propiedad de otra persona causados por su trabajo son el tipo de reclamo que atiende la responsabilidad civil general, según los términos, límites y deducible de la póliza. No paga por repintar una pared que al cliente no le gustó; eso es la calidad de su propio trabajo.' },
        { q: '¿Necesito compensación laboral como pintor en Florida?', a: 'Depende de cuántos empleados tiene y de si su trabajo entra en la industria de la construcción. Los empleadores de construcción la necesitan desde el primer empleado, y el estatuto también considera empleados a los propietarios únicos y socios que trabajan en construcción. Los oficiales de corporación y miembros de LLC con al menos el 10% pueden presentar una exención. Llámenos y revisamos su caso.' },
        { q: 'Un contratista general me pidió asegurado adicional y renuncia de subrogación. ¿Puedo tenerlos?', a: 'Muchas pólizas pueden agregar esos endosos, pero la redacción varía. Envíenos el contrato o la solicitud de certificado y confirmamos lo que permite su póliza antes de que firme.' },
        { q: '¿Mis máquinas de pintar están cubiertas cuando están en la van?', a: 'No por la responsabilidad general ni, normalmente, por la póliza de auto. Las máquinas y demás equipo suelen cubrirse con una póliza de herramientas y equipos (inland marine). Pregúntenos por las condiciones para robos desde un vehículo.' },
        { q: '¿Solo trabajan con pintores cerca de Florida City?', a: 'No. Nuestra oficina está en Florida City, pero atendemos contratistas de pintura en toda Florida por teléfono, mensaje de texto y correo, en español, inglés y ruso.' },
      ],
      sources: sources('es', ['fs440_02', 'fs440_10', 'cbp2023']),
    },
    ru: {
      metaTitle: 'Страховка для малярных подрядчиков во Флориде | M&K Agency',
      metaDesc: 'Страхование маляров во Флориде: ответственность за брызги краски и пролитую краску, workers’ comp, краскопульты, лестницы и фургоны. Агент говорит по-русски.',
      breadcrumb: 'Страховка для маляров',
      kicker: 'Малярные работы · Флорида',
      h1a: 'Страховка для малярных подрядчиков во Флориде —',
      h1b: 'для внутренних, наружных и коммерческих работ.',
      sub: 'Перекраска домов, новостройки, коммерческие объекты и HOA по всей Флориде: помогаем малярным компаниям застраховаться от претензий за брызги и пролитую краску, защитить бригаду на лестницах, краскопульты и фургоны и выдавать сертификаты генподрядчикам и управляющим компаниям. По-русски, по-английски или по-испански.',
      linkLabel: 'Малярные работы',
      serviceType: 'Страхование малярных подрядчиков',
      intro: [
        { type: 'h2', text: 'Какие риски стоят за покраской' },
        { type: 'p', text: 'Солнце и влажность Флориды обеспечивают малярам работу и на перекраске, и на новостройках. Бюро переписи США насчитывает во Флориде **4 421 предприятие малярных и обойных подрядчиков** с наёмными работниками (County Business Patterns, 2023). Большинство претензий в этой профессии почти не связаны с самой краской:' },
        { type: 'ul', items: [
          'Краска из распылителя оседает на соседской машине, лодке или сетке бассейна.',
          'Опрокинутое ведро портит ковёр, затирку плитки или паркет.',
          'Малярный скотч или подготовка срывают отделку, или мойка под давлением перед покраской загоняет воду внутрь.',
          'Хозяин или жилец спотыкается об укрывную ткань или лестницу.',
          'Маляр падает с лестницы или лесов или получает тепловой удар на наружных работах.',
          'Из фургона или с объекта крадут безвоздушные краскопульты и лестницы.',
          'Генподрядчик не пускает бригаду на объект без сертификата или требует статус additional insured.',
        ] },
      ],
      covTitle: 'Какие виды страховки обычно нужны малярному бизнесу',
      cov: [
        { h: 'General liability (общая ответственность)', p: 'Для претензий о том, что ваша работа причинила вред человеку или его имуществу — краска на машине, пятно на полу, — в рамках условий полиса. Переделка вашей собственной работы обычно не покрывается.' },
        { h: 'Workers’ compensation', p: 'Оплачивает лечение и потерянный заработок пострадавших работников, например при падении с лестницы. Если ваша работа относится к строительной отрасли, Флорида требует её с первого работника.' },
        { h: 'Коммерческое авто', p: 'Для фургонов и пикапов, которые возят бригаду, лестницы и краску, включая багажники и прицеп.' },
        { h: 'Инструмент и оборудование', p: 'Страховка inland marine для безвоздушных краскопультов, моек высокого давления, лестниц, лесов и другого снаряжения — в фургоне, на объекте или на хранении.' },
        { h: 'Business owner’s policy (BOP)', p: 'Для подходящих бизнесов с мастерской или складом объединяет общую ответственность со страховкой имущества бизнеса и хранящихся материалов.' },
        { h: 'Umbrella / excess liability', p: 'Дополнительные лимиты ответственности поверх полисов general liability и авто, когда коммерческие договоры или договоры с HOA требуют больших лимитов.' },
      ],
      body: [
        { type: 'h2', text: 'Что важно знать малярному подрядчику во Флориде' },
        { type: 'h3', text: 'Workers’ comp: выясните, какой порог к вам относится' },
        { type: 'p', text: `[Статуты Флориды § 440.02](${U.fs440_02}) требуют workers’ compensation у большинства частных работодателей с четырьмя и более работниками, а в строительной отрасли — уже с одним. Та же статья считает работниками индивидуальных предпринимателей, партнёров и независимых подрядчиков, занятых в строительстве. Если ваши малярные работы относятся к строительной отрасли по статуту и правилам классификации штата, действует порог в одного работника, поэтому проверьте это до того, как нанимать людей или привлекать помощников как независимых подрядчиков.` },
        { type: 'h3', text: 'Если вы работаете на субподряде' },
        { type: 'p', text: `Закон Флориды обязывает подрядчика требовать от субподрядчика подтверждение страховки workers’ compensation или копию сертификата освобождения должностного лица ([§ 440.10](${U.fs440_10})). Если вы красите для генподрядчиков или застройщиков, будьте готовы, что до начала работ у вас попросят одно из двух, а также сертификат general liability.` },
        { type: 'h2', text: 'Что подготовить для расчёта' },
        { type: 'ul', items: [
          'Внутренние, наружные работы или и то и другое; жилые, коммерческие объекты, HOA или новостройки',
          'Работаете ли вы распылителем и делаете ли мойку под давлением при подготовке',
          'Самые высокие здания, которые вы красите, и используете ли леса или подъёмники',
          'Количество работников, помощников и субподрядчиков, ожидаемый фонд оплаты труда',
          'Ожидаемая выручка на 12 месяцев',
          'Машины (год, марка, модель, VIN) и водители',
          'Оборудование, которое нужно застраховать, с примерной стоимостью',
          'Требования договора или сертификата, если есть',
          'Страховые случаи за последние три–пять лет',
        ] },
        { type: 'p', text: 'См. также: [страховка для подрядчиков](/ru/contractor-insurance-florida), [страховка для мойки под давлением](/ru/pressure-washing-insurance-florida) и [общая ответственность](/ru/insurance/general-liability).' },
      ],
      faqTitle: 'Страховка для маляров: частые вопросы',
      faq: [
        { q: 'Заплатит ли general liability за краску на соседской машине?', a: 'Случайный ущерб чужому имуществу, причинённый вашей работой, — это тот тип претензий, для которого существует general liability, в рамках условий, лимитов и франшизы полиса. Перекраску стены, которая не понравилась клиенту, он не оплатит — это качество вашей собственной работы.' },
        { q: 'Нужен ли маляру во Флориде workers’ comp?', a: 'Зависит от числа работников и от того, относится ли ваша работа к строительной отрасли. Строительным работодателям он нужен с первого работника, а статут также считает работниками индивидуальных предпринимателей и партнёров, занятых в строительстве. Должностные лица корпорации и участники LLC с долей от 10% могут оформить освобождение. Позвоните — разберём вашу ситуацию.' },
        { q: 'Генподрядчик просит additional insured и waiver of subrogation. Это возможно?', a: 'Многие полисы позволяют добавить такие эндорсменты, но формулировки отличаются. Пришлите договор или запрос сертификата — мы проверим, что допускает ваш полис, до того как вы подпишете.' },
        { q: 'Застрахованы ли краскопульты, пока они в фургоне?', a: 'Ни general liability, ни обычно автополис их не покрывают. Краскопульты и другое оборудование, как правило, страхуются полисом инструмента и оборудования (inland marine). Спросите нас об условиях для кражи из машины.' },
        { q: 'Вы работаете только с малярами рядом с Florida City?', a: 'Нет. Наш офис во Florida City, но мы работаем с малярными подрядчиками по всей Флориде по телефону, SMS и email — по-русски, по-английски и по-испански.' },
      ],
      sources: sources('ru', ['fs440_02', 'fs440_10', 'cbp2023']),
    },
  },
};
