import type { BusinessPage } from './types';
import { SRC_URL as U, sources } from './sources';

export const PRESSURE_WASHING: BusinessPage = {
  path: '/pressure-washing-insurance-florida',
  icon: '💦',
  published: '2026-09-26',
  modified: '2026-09-26',
  team: ['mikhail-kozlov', 'craig-fernandes', 'elena-de-ona'],
  copy: {
    en: {
      metaTitle: 'Pressure Washing Insurance in Florida | M&K Agency',
      metaDesc: 'Insurance for Florida pressure and soft washing businesses: general liability, trailer rigs, equipment, work trucks, workers’ comp. English, Spanish, Russian.',
      breadcrumb: 'Pressure washing insurance',
      kicker: 'Pressure Washing · Florida',
      h1a: 'Pressure washing insurance in Florida,',
      h1b: 'for driveways, decks, fences and building exteriors.',
      sub: 'Pressure washing and soft washing businesses across Florida: we help you cover the property-damage and slip claims that come with high-pressure water and cleaning chemicals, plus your truck, trailer rig and equipment. In English, Spanish or Russian.',
      linkLabel: 'Pressure washing',
      serviceType: 'Pressure washing insurance',
      intro: [
        { type: 'h2', text: 'Why pressure washers need their own coverage plan' },
        { type: 'p', text: 'Mildew, algae and rust stains keep Florida pressure washers busy all year. The U.S. Census Bureau counts **3,260 establishments** with paid employees in Florida in the industry that includes pressure washing of buildings, decks and fences (NAICS 561790, County Business Patterns, 2023). High-pressure water and chemicals are powerful, and so are the claims when something goes wrong:' },
        { type: 'ul', items: [
          'Etched concrete, damaged pavers or stripped paint and stain.',
          'Water forced through a window, door or soffit, damaging the interior.',
          'Cleaning solution or runoff damages plants, lawns, a car or a neighbor’s property.',
          'Torn screens or damaged pool enclosures.',
          'A customer or pedestrian slips on a wet, slick surface.',
          'A crew member is hurt by the spray, a hot-water unit or a fall from a ladder.',
          'A trailer rig, surface cleaner or pump is stolen, or damaged on the road.',
        ] },
      ],
      covTitle: 'Coverage that usually fits a pressure washing business',
      cov: [
        { h: 'General liability', p: 'For claims that your work injured someone or damaged their property, such as water intrusion or chemical damage to landscaping, subject to the policy terms. Commercial and HOA clients usually ask for it.' },
        { h: 'Tools & equipment', p: 'Inland marine coverage for pressure washers, pumps, hot-water units, surface cleaners, hoses and tanks, on the trailer, at the job or in storage.' },
        { h: 'Commercial auto', p: 'For the truck that pulls your rig and the trailer itself. Tell us about skid units and tanks so everything is listed the right way.' },
        { h: 'Workers’ compensation', p: 'Pays medical bills and lost wages if an employee is hurt on the job. When it’s required depends on your headcount and how your work is classified (see below).' },
        { h: 'Business owner’s policy', p: 'For eligible businesses, bundles general liability with coverage for business property such as a shop, stored chemicals and supplies.' },
      ],
      body: [
        { type: 'h2', text: 'Florida points for pressure washing businesses' },
        { type: 'h3', text: 'Workers’ comp when you hire a crew' },
        { type: 'p', text: `[Florida Statutes § 440.02](${U.fs440_02}) requires workers’ compensation for most private employers with four or more employees, and for construction-industry employers with one or more. Which threshold applies depends on how your work is classified. If you mainly clean surfaces, ask us to confirm before your first employee starts, and again if you add services like painting or sealing.` },
        { type: 'h3', text: 'Tell us everything you wash' },
        { type: 'p', text: 'Driveways and pool decks, house exteriors, commercial buildings, fleet vehicles and boats can all be treated differently by insurance companies. Some also ask specifically about soft washing chemicals and roof cleaning. A complete, accurate description of your services is what keeps a claim from being disputed later.' },
        { type: 'h2', text: 'What to have ready for a quote' },
        { type: 'ul', items: [
          'Services you offer: driveways, decks, fences, house and building exteriors, soft washing, gutter brightening, sealing',
          'Residential vs. commercial and HOA work',
          'Equipment: pressure washers (PSI and hot or cold water), pumps, tanks, surface cleaners, with approximate values',
          'Truck and trailer details (year, make, model, VIN) and drivers',
          'Number of employees and estimated payroll for the next 12 months',
          'Estimated revenue for the next 12 months',
          'Any certificate or contract requirements you’ve been given',
          'Claims in the last three to five years',
        ] },
        { type: 'p', text: 'Related: [window cleaning insurance](/en/window-cleaning-insurance-florida), [painting contractor insurance](/en/painting-contractor-insurance-florida) and [general liability](/en/insurance/general-liability).' },
      ],
      faqTitle: 'Pressure washing insurance: common questions',
      faq: [
        { q: 'Would general liability cover water that gets inside a customer’s house?', a: 'Accidental damage to a customer’s property caused by your work is the kind of claim general liability is designed for, subject to the policy’s terms, limits and deductible. Some policies limit coverage for the specific surface you’re working on, so ask us to show you how yours reads.' },
        { q: 'Is my trailer rig covered by my auto policy?', a: 'The trailer should be listed on your commercial auto policy, but the pressure washer, pump and tank mounted on it are usually covered under a tools and equipment (inland marine) policy. We’ll set them up together so there’s no gap.' },
        { q: 'Do HOAs and property managers require insurance?', a: 'Most ask for a certificate of general liability before you start, often with additional insured wording. Send us their request and we’ll confirm what your policy supports.' },
        { q: 'Do I need workers’ comp?', a: 'Florida requires it for most private employers with four or more employees, and for construction-industry employers with one or more. Call us before you hire and we’ll confirm which rule applies to your business.' },
        { q: 'Do you only work with pressure washing companies near Florida City?', a: 'No. Our office is in Florida City, but we work with pressure washing businesses across Florida by phone, text and email, in English, Spanish and Russian.' },
      ],
      sources: sources('en', ['fs440_02', 'cbp2023', 'naics561790']),
    },
    es: {
      metaTitle: 'Seguro para Lavado a Presión en Florida | M&K Agency',
      metaDesc: 'Seguros para negocios de lavado a presión y soft wash en Florida: responsabilidad civil, remolques y equipos, camionetas de trabajo, compensación laboral.',
      breadcrumb: 'Seguro para lavado a presión',
      kicker: 'Lavado a presión · Florida',
      h1a: 'Seguro para lavado a presión en Florida,',
      h1b: 'para entradas, terrazas, cercas y fachadas.',
      sub: 'Negocios de lavado a presión y soft wash en toda Florida: le ayudamos a cubrir los reclamos por daños a la propiedad y resbalones que vienen con el agua a alta presión y los químicos de limpieza, además de su camioneta, su remolque y sus equipos. En español, inglés o ruso.',
      linkLabel: 'Lavado a presión',
      serviceType: 'Seguro para lavado a presión',
      intro: [
        { type: 'h2', text: 'Por qué el lavado a presión necesita su propio plan de coberturas' },
        { type: 'p', text: 'El moho, las algas y las manchas de óxido mantienen ocupados todo el año a los negocios de lavado a presión en Florida. La Oficina del Censo de EE. UU. cuenta **3,260 establecimientos** con empleados en Florida en la industria que incluye el lavado a presión de edificios, terrazas y cercas (NAICS 561790, County Business Patterns, 2023). El agua a alta presión y los químicos son potentes, y los reclamos también lo son cuando algo sale mal:' },
        { type: 'ul', items: [
          'Concreto marcado, adoquines dañados o pintura y sellador levantados.',
          'Agua que entra por una ventana, puerta o sofito y daña el interior.',
          'El químico o el agua de escorrentía daña plantas, césped, un carro o la propiedad del vecino.',
          'Mosquiteros rotos o jaulas de piscina dañadas.',
          'Un cliente o peatón resbala en una superficie mojada.',
          'Alguien del equipo se lastima con el chorro, con un equipo de agua caliente o al caer de una escalera.',
          'Roban el remolque con el equipo, la limpiadora de superficies o la bomba, o se dañan en la carretera.',
        ] },
      ],
      covTitle: 'Coberturas que suelen necesitar los negocios de lavado a presión',
      cov: [
        { h: 'Responsabilidad civil general', p: 'Para reclamos de que su trabajo lesionó a alguien o dañó su propiedad, como agua que entra a la casa o químicos que dañan el jardín, según los términos de la póliza. Los clientes comerciales y las HOA suelen pedirla.' },
        { h: 'Herramientas y equipos', p: 'Cobertura inland marine para hidrolavadoras, bombas, equipos de agua caliente, limpiadoras de superficies, mangueras y tanques, en el remolque, en el trabajo o guardados.' },
        { h: 'Auto comercial', p: 'Para la camioneta que remolca su equipo y para el remolque. Cuéntenos de las unidades skid y los tanques para que todo quede bien listado.' },
        { h: 'Compensación laboral', p: 'Paga gastos médicos y salarios perdidos si un empleado se lastima trabajando. Cuándo es obligatoria depende de cuántos empleados tiene y de cómo se clasifica su trabajo (vea abajo).' },
        { h: 'Póliza de dueño de negocio (BOP)', p: 'Para negocios elegibles, combina responsabilidad civil general con cobertura para bienes del negocio, como un taller, químicos y suministros guardados.' },
      ],
      body: [
        { type: 'h2', text: 'Lo que un negocio de lavado a presión debe saber en Florida' },
        { type: 'h3', text: 'Compensación laboral cuando contrata personal' },
        { type: 'p', text: `Los [Estatutos de Florida § 440.02](${U.fs440_02}) exigen compensación laboral a la mayoría de los empleadores privados con cuatro o más empleados, y a los de la industria de la construcción desde uno. Qué umbral le aplica depende de cómo se clasifique su trabajo. Si se dedica principalmente a limpiar superficies, pídanos que lo confirmemos antes de que empiece su primer empleado, y otra vez si agrega servicios como pintura o sellado.` },
        { type: 'h3', text: 'Cuéntenos todo lo que lava' },
        { type: 'p', text: 'Entradas y terrazas de piscina, fachadas de casas, edificios comerciales, flotas de vehículos y botes pueden ser tratados de forma distinta por las aseguradoras. Algunas también preguntan específicamente por los químicos de soft wash y la limpieza de techos. Una descripción completa y exacta de sus servicios es lo que evita que un reclamo se dispute más adelante.' },
        { type: 'h2', text: 'Qué tener a mano para cotizar' },
        { type: 'ul', items: [
          'Servicios que ofrece: entradas, terrazas, cercas, fachadas de casas y edificios, soft wash, limpieza de canaletas, sellado',
          'Trabajo residencial o comercial y de HOA',
          'Equipos: hidrolavadoras (PSI y agua caliente o fría), bombas, tanques, limpiadoras de superficies, con su valor aproximado',
          'Datos de la camioneta y el remolque (año, marca, modelo, VIN) y choferes',
          'Número de empleados y nómina estimada para los próximos 12 meses',
          'Ingresos estimados para los próximos 12 meses',
          'Requisitos de certificado o de contrato que le hayan dado',
          'Reclamos de los últimos tres a cinco años',
        ] },
        { type: 'p', text: 'Relacionado: [seguro para limpieza de ventanas](/es/window-cleaning-insurance-florida), [seguro para contratistas de pintura](/es/painting-contractor-insurance-florida) y [responsabilidad civil general](/es/insurance/general-liability).' },
      ],
      faqTitle: 'Seguro para lavado a presión: preguntas frecuentes',
      faq: [
        { q: '¿La responsabilidad civil general cubre el agua que entra a la casa del cliente?', a: 'Los daños accidentales a la propiedad del cliente causados por su trabajo son el tipo de reclamo que atiende la responsabilidad civil general, según los términos, límites y deducible de la póliza. Algunas pólizas limitan la cobertura de la superficie específica en la que trabaja, así que pídanos que le mostremos cómo está redactada la suya.' },
        { q: '¿Mi remolque con el equipo está cubierto por la póliza de auto?', a: 'El remolque debe figurar en su póliza de auto comercial, pero la hidrolavadora, la bomba y el tanque montados en él suelen cubrirse con una póliza de herramientas y equipos (inland marine). Las preparamos juntas para que no queden huecos.' },
        { q: '¿Las HOA y los administradores de propiedades exigen seguro?', a: 'La mayoría pide un certificado de responsabilidad civil general antes de empezar, muchas veces con asegurado adicional. Envíenos su solicitud y confirmamos lo que permite su póliza.' },
        { q: '¿Necesito compensación laboral?', a: 'Florida la exige a la mayoría de los empleadores privados con cuatro o más empleados, y a los de construcción desde uno. Llámenos antes de contratar y confirmamos qué regla aplica a su negocio.' },
        { q: '¿Solo trabajan con empresas de lavado a presión cerca de Florida City?', a: 'No. Nuestra oficina está en Florida City, pero atendemos negocios de lavado a presión en toda Florida por teléfono, mensaje de texto y correo, en español, inglés y ruso.' },
      ],
      sources: sources('es', ['fs440_02', 'cbp2023', 'naics561790']),
    },
    ru: {
      metaTitle: 'Страховка для мойки под давлением во Флориде | M&K Agency',
      metaDesc: 'Страхование бизнеса по мойке под давлением и soft wash во Флориде: ответственность, прицепы, оборудование, машины, workers’ comp. Агент говорит по-русски.',
      breadcrumb: 'Страховка для мойки под давлением',
      kicker: 'Мойка под давлением · Флорида',
      h1a: 'Страховка для мойки под давлением во Флориде —',
      h1b: 'для подъездов, террас, заборов и фасадов.',
      sub: 'Бизнес по мойке под давлением и soft wash по всей Флориде: поможем застраховаться от претензий за ущерб имуществу и падения, которые случаются при работе с водой под высоким давлением и химией, а также застраховать машину, прицеп с установкой и оборудование. По-русски, по-английски или по-испански.',
      linkLabel: 'Мойка под давлением',
      serviceType: 'Страхование бизнеса по мойке под давлением',
      intro: [
        { type: 'h2', text: 'Почему мойке под давлением нужен свой набор страховок' },
        { type: 'p', text: 'Плесень, водоросли и ржавые пятна обеспечивают работой мойщиков во Флориде круглый год. Бюро переписи США насчитывает во Флориде **3 260 предприятий** с наёмными работниками в отрасли, куда входит мойка под давлением зданий, террас и заборов (NAICS 561790, County Business Patterns, 2023). Вода под высоким давлением и химия — мощные инструменты, и претензии, когда что-то идёт не так, тоже бывают серьёзными:' },
        { type: 'ul', items: [
          'Разъеденный бетон, повреждённая брусчатка, сорванная краска или пропитка.',
          'Вода проникает через окно, дверь или софит и портит интерьер.',
          'Моющий раствор или сток повреждает растения, газон, машину или имущество соседа.',
          'Порванные москитные сетки или повреждённая сетка бассейна.',
          'Клиент или прохожий поскальзывается на мокрой поверхности.',
          'Работник травмируется струёй, установкой с горячей водой или при падении с лестницы.',
          'Прицеп с установкой, насадку для поверхностей или насос крадут или повреждают в дороге.',
        ] },
      ],
      covTitle: 'Какие виды страховки обычно нужны бизнесу по мойке под давлением',
      cov: [
        { h: 'General liability (общая ответственность)', p: 'Для претензий о том, что ваша работа травмировала человека или повредила его имущество — вода внутри дома, химия на газоне, — в рамках условий полиса. Коммерческие клиенты и HOA обычно его требуют.' },
        { h: 'Инструмент и оборудование', p: 'Страховка inland marine для моек высокого давления, насосов, установок с горячей водой, насадок, шлангов и баков — на прицепе, на объекте или на хранении.' },
        { h: 'Коммерческое авто', p: 'Для машины, которая тянет установку, и для самого прицепа. Расскажите нам о skid-установках и баках, чтобы всё было вписано правильно.' },
        { h: 'Workers’ compensation', p: 'Оплачивает лечение и потерянный заработок, если работник пострадал на работе. Когда она обязательна, зависит от числа работников и классификации вашей работы (см. ниже).' },
        { h: 'Business owner’s policy (BOP)', p: 'Для подходящих бизнесов объединяет общую ответственность со страховкой имущества бизнеса — мастерской, хранящейся химии и материалов.' },
      ],
      body: [
        { type: 'h2', text: 'Что важно знать бизнесу по мойке под давлением во Флориде' },
        { type: 'h3', text: 'Workers’ comp, когда вы нанимаете работников' },
        { type: 'p', text: `[Статуты Флориды § 440.02](${U.fs440_02}) требуют workers’ compensation у большинства частных работодателей с четырьмя и более работниками, а в строительной отрасли — уже с одним. Какой порог относится к вам, зависит от классификации вашей работы. Если вы в основном моете поверхности, попросите нас уточнить это до выхода первого работника — и ещё раз, если добавите покраску или нанесение пропитки.` },
        { type: 'h3', text: 'Расскажите обо всём, что вы моете' },
        { type: 'p', text: 'Подъезды и террасы у бассейнов, фасады домов, коммерческие здания, автопарки и лодки страховые компании могут оценивать по-разному. Некоторые отдельно спрашивают о химии для soft wash и мойке крыш. Полное и точное описание услуг — то, что помогает избежать споров по страховому случаю потом.' },
        { type: 'h2', text: 'Что подготовить для расчёта' },
        { type: 'ul', items: [
          'Какие услуги вы оказываете: подъезды, террасы, заборы, фасады домов и зданий, soft wash, чистка водостоков, пропитка',
          'Частные клиенты или коммерческие объекты и HOA',
          'Оборудование: мойки (PSI, горячая или холодная вода), насосы, баки, насадки для поверхностей — с примерной стоимостью',
          'Машина и прицеп (год, марка, модель, VIN) и водители',
          'Количество работников и ожидаемый фонд оплаты труда на 12 месяцев',
          'Ожидаемая выручка на 12 месяцев',
          'Требования к сертификату или договору, если есть',
          'Страховые случаи за последние три–пять лет',
        ] },
        { type: 'p', text: 'См. также: [страховка для мойки окон](/ru/window-cleaning-insurance-florida), [страховка для малярных подрядчиков](/ru/painting-contractor-insurance-florida) и [общая ответственность](/ru/insurance/general-liability).' },
      ],
      faqTitle: 'Страховка для мойки под давлением: частые вопросы',
      faq: [
        { q: 'Покроет ли general liability воду, попавшую в дом клиента?', a: 'Случайный ущерб имуществу клиента, причинённый вашей работой, — это тот тип претензий, для которого существует general liability, в рамках условий, лимитов и франшизы полиса. Некоторые полисы ограничивают покрытие той поверхности, с которой вы работаете, поэтому попросите нас показать, как это сформулировано в вашем.' },
        { q: 'Покрывает ли автополис мой прицеп с установкой?', a: 'Прицеп должен быть вписан в полис коммерческого авто, а мойка, насос и бак на нём обычно страхуются полисом инструмента и оборудования (inland marine). Мы оформим их вместе, чтобы не было пробелов.' },
        { q: 'Требуют ли HOA и управляющие компании страховку?', a: 'Большинство просят сертификат general liability до начала работ, часто со статусом additional insured. Пришлите их запрос — мы проверим, что допускает ваш полис.' },
        { q: 'Нужен ли мне workers’ comp?', a: 'Флорида требует его у большинства частных работодателей с четырьмя и более работниками, а в строительстве — с одного. Позвоните до того, как нанимать, — уточним, какое правило относится к вашему бизнесу.' },
        { q: 'Вы работаете только с компаниями рядом с Florida City?', a: 'Нет. Наш офис во Florida City, но мы работаем с бизнесом по мойке под давлением по всей Флориде по телефону, SMS и email — по-русски, по-английски и по-испански.' },
      ],
      sources: sources('ru', ['fs440_02', 'cbp2023', 'naics561790']),
    },
  },
};
