import type { BusinessPage } from './types';
import { SRC_URL as U, sources } from './sources';

export const WINDOW_CLEANING: BusinessPage = {
  path: '/window-cleaning-insurance-florida',
  icon: '🪟',
  published: '2026-09-26',
  modified: '2026-09-26',
  team: ['mikhail-kozlov', 'shane-henry', 'elena-de-ona'],
  copy: {
    en: {
      metaTitle: 'Window Cleaning Insurance in Florida | M&K Agency',
      metaDesc: 'Insurance for Florida window cleaners serving homes, storefronts and low-rise buildings: general liability, ladders and equipment, vans, workers’ comp.',
      breadcrumb: 'Window cleaning insurance',
      kicker: 'Window Cleaning · Florida',
      h1a: 'Window cleaning insurance in Florida,',
      h1b: 'for homes, storefronts and low-rise buildings.',
      sub: 'Residential and storefront window cleaners across Florida: we help you cover the liability that comes with ladders, glass and water around other people’s property, plus your van, your equipment and your crew. In English, Spanish or Russian.',
      linkLabel: 'Window cleaning',
      serviceType: 'Window cleaning insurance',
      intro: [
        { type: 'h2', text: 'What can go wrong on a window cleaning job' },
        { type: 'p', text: 'Window cleaning looks simple until something breaks. You’re working on ladders, around glass, with water and cleaning solutions, often at a storefront full of customers or a home full of furniture. The U.S. Census Bureau counts **6,675 janitorial services establishments** with paid employees in Florida, the Census category that includes window cleaning (County Business Patterns, 2023).' },
        { type: 'p', text: 'The claims window cleaners run into most:' },
        { type: 'ul', items: [
          'A cracked or broken pane, or a damaged screen or window track.',
          'A ladder slips and damages a roof edge, gutter, awning or storefront sign.',
          'Water gets inside and stains a floor, wall or merchandise.',
          'A shopper or pedestrian slips on a wet sidewalk in front of a storefront you’re cleaning.',
          'Cleaning solution drips onto a car, plants or a painted surface.',
          'A crew member falls from a ladder or is cut by broken glass.',
          'Ladders, water-fed poles or a purification unit are stolen from the van.',
        ] },
      ],
      covTitle: 'Coverage that usually fits a window cleaning business',
      cov: [
        { h: 'General liability', p: 'For claims that your work injured someone or damaged their property, such as a broken pane or a slip on a wet sidewalk, subject to the policy terms. Storefront and property-management clients usually require it.' },
        { h: 'Workers’ compensation', p: 'Pays medical bills and lost wages if an employee is hurt on the job, for example in a ladder fall. When it’s required depends on your headcount and how your work is classified (see below).' },
        { h: 'Commercial auto', p: 'For the van or pickup that carries your ladders and water-fed pole system, including any racks or built-in equipment.' },
        { h: 'Tools & equipment', p: 'Inland marine coverage for ladders, water-fed poles, pure-water units and other gear, in the van, at the job or in storage.' },
        { h: 'Business owner’s policy', p: 'For eligible businesses, bundles general liability with coverage for business property such as stored supplies and equipment.' },
      ],
      body: [
        { type: 'h2', text: 'Who this page is for' },
        { type: 'p', text: 'This page is for window cleaning businesses that work on **homes, storefronts and low-rise buildings**, using ladders and water-fed poles from the ground. Tell us about every service you offer, including add-ons such as screen repair, gutter cleaning or pressure washing, so the policy describes your business correctly.' },
        { type: 'h2', text: 'Florida points for window cleaners' },
        { type: 'h3', text: 'Workers’ comp when you hire a crew' },
        { type: 'p', text: `[Florida Statutes § 440.02](${U.fs440_02}) requires workers’ compensation for most private employers with four or more employees, and for construction-industry employers with one or more. Which threshold applies to you depends on how your work is classified, so if you’re about to hire, ask us to confirm before your first employee starts.` },
        { type: 'h3', text: 'Storefront and commercial accounts' },
        { type: 'p', text: 'Retail landlords, property managers and franchise locations often ask for a certificate of insurance before your first visit, sometimes with additional insured wording. Send us the request and we’ll check it against your policy.' },
        { type: 'h2', text: 'What to have ready for a quote' },
        { type: 'ul', items: [
          'Types of properties you clean: homes, storefronts, low-rise offices',
          'How many stories your tallest regular job is, and the equipment you use (ladders, water-fed poles)',
          'Interior, exterior or both, and any add-on services',
          'Number of employees and estimated payroll for the next 12 months',
          'Estimated revenue for the next 12 months',
          'Vehicles (year, make, model, VIN) and drivers',
          'Equipment you want covered, with approximate values',
          'Claims in the last three to five years',
        ] },
        { type: 'p', text: 'Related: [general liability](/en/insurance/general-liability), [pressure washing insurance](/en/pressure-washing-insurance-florida) and [commercial auto](/en/insurance/commercial-auto).' },
      ],
      faqTitle: 'Window cleaning insurance: common questions',
      faq: [
        { q: 'Does general liability cover a window I break while cleaning it?', a: 'Accidental damage to a customer’s property caused by your work is the kind of claim general liability is designed for, subject to the policy’s terms, limits and deductible. Some policies limit coverage for the specific item you’re working on, so ask us to show you how your policy handles it.' },
        { q: 'I’m a one-person operation. What do storefront clients usually ask for?', a: 'Most ask for a certificate showing general liability, and some want to be named as additional insured. Send us their request and we’ll confirm what your policy supports.' },
        { q: 'Are my ladders and water-fed pole system covered?', a: 'Not by general liability. Ladders, poles and pure-water units are typically covered under a tools and equipment (inland marine) policy, and built-in equipment on a van should be discussed when we set up the auto policy.' },
        { q: 'Do I need workers’ comp?', a: 'Florida requires it for most private employers with four or more employees, and for construction-industry employers with one or more. Call us before you hire and we’ll confirm which rule applies to your business.' },
        { q: 'Do you only work with window cleaners near Florida City?', a: 'No. Our office is in Florida City, but we work with window cleaning businesses across Florida by phone, text and email, in English, Spanish and Russian.' },
      ],
      sources: sources('en', ['fs440_02', 'cbp2023', 'naics561720']),
    },
    es: {
      metaTitle: 'Seguro para Limpieza de Ventanas en Florida | M&K Agency',
      metaDesc: 'Seguros para limpiadores de ventanas en Florida que trabajan en casas, locales comerciales y edificios bajos: responsabilidad civil, equipos, van y más.',
      breadcrumb: 'Seguro para limpieza de ventanas',
      kicker: 'Limpieza de ventanas · Florida',
      h1a: 'Seguro para limpieza de ventanas en Florida,',
      h1b: 'para casas, locales comerciales y edificios bajos.',
      sub: 'Limpiadores de ventanas residenciales y de locales comerciales en toda Florida: le ayudamos a cubrir la responsabilidad que implica trabajar con escaleras, vidrio y agua en propiedad ajena, además de su van, su equipo y su personal. En español, inglés o ruso.',
      linkLabel: 'Limpieza de ventanas',
      serviceType: 'Seguro para limpieza de ventanas',
      intro: [
        { type: 'h2', text: 'Qué puede salir mal en una limpieza de ventanas' },
        { type: 'p', text: 'Limpiar ventanas parece sencillo hasta que algo se rompe. Trabaja en escaleras, alrededor de vidrio, con agua y productos de limpieza, muchas veces frente a un local lleno de clientes o en una casa llena de muebles. La Oficina del Censo de EE. UU. cuenta **6,675 establecimientos de servicios de limpieza** con empleados en Florida, la categoría del Censo que incluye la limpieza de ventanas (County Business Patterns, 2023).' },
        { type: 'p', text: 'Los reclamos más comunes para limpiadores de ventanas:' },
        { type: 'ul', items: [
          'Un vidrio agrietado o roto, o un mosquitero o riel de ventana dañado.',
          'La escalera se resbala y daña el borde del techo, una canaleta, un toldo o el letrero del local.',
          'Entra agua y mancha un piso, una pared o mercancía.',
          'Un cliente o peatón resbala en la acera mojada frente al local que está limpiando.',
          'El producto de limpieza gotea sobre un carro, plantas o una superficie pintada.',
          'Alguien del equipo se cae de una escalera o se corta con vidrio roto.',
          'Roban escaleras, pértigas con agua o el equipo de purificación de la van.',
        ] },
      ],
      covTitle: 'Coberturas que suelen necesitar los negocios de limpieza de ventanas',
      cov: [
        { h: 'Responsabilidad civil general', p: 'Para reclamos de que su trabajo lesionó a alguien o dañó su propiedad, como un vidrio roto o un resbalón en la acera mojada, según los términos de la póliza. Los locales comerciales y administradores suelen exigirla.' },
        { h: 'Compensación laboral', p: 'Paga gastos médicos y salarios perdidos si un empleado se lastima trabajando, por ejemplo en una caída de escalera. Cuándo es obligatoria depende de cuántos empleados tiene y de cómo se clasifica su trabajo (vea abajo).' },
        { h: 'Auto comercial', p: 'Para la van o pickup que lleva sus escaleras y el sistema de pértiga con agua, incluidos portaescaleras o equipos instalados.' },
        { h: 'Herramientas y equipos', p: 'Cobertura inland marine para escaleras, pértigas con agua, equipos de agua pura y demás, en la van, en el trabajo o guardados.' },
        { h: 'Póliza de dueño de negocio (BOP)', p: 'Para negocios elegibles, combina responsabilidad civil general con cobertura para bienes del negocio, como suministros y equipos guardados.' },
      ],
      body: [
        { type: 'h2', text: 'Para quién es esta página' },
        { type: 'p', text: 'Esta página es para negocios de limpieza de ventanas que trabajan en **casas, locales comerciales y edificios bajos**, con escaleras y pértigas con agua desde el suelo. Cuéntenos todos los servicios que ofrece, incluidos extras como reparación de mosquiteros, limpieza de canaletas o lavado a presión, para que la póliza describa bien su negocio.' },
        { type: 'h2', text: 'Lo que un limpiador de ventanas debe saber en Florida' },
        { type: 'h3', text: 'Compensación laboral cuando contrata personal' },
        { type: 'p', text: `Los [Estatutos de Florida § 440.02](${U.fs440_02}) exigen compensación laboral a la mayoría de los empleadores privados con cuatro o más empleados, y a los de la industria de la construcción desde uno. Qué umbral le aplica depende de cómo se clasifique su trabajo, así que si va a contratar, pídanos que lo confirmemos antes de que empiece su primer empleado.` },
        { type: 'h3', text: 'Locales y cuentas comerciales' },
        { type: 'p', text: 'Los dueños de locales, administradores de propiedades y franquicias suelen pedir un certificado de seguro antes de la primera visita, a veces con asegurado adicional. Envíenos la solicitud y la comparamos con su póliza.' },
        { type: 'h2', text: 'Qué tener a mano para cotizar' },
        { type: 'ul', items: [
          'Tipos de propiedades que limpia: casas, locales comerciales, oficinas en edificios bajos',
          'Cuántos pisos tiene su trabajo regular más alto y qué equipo usa (escaleras, pértigas con agua)',
          'Interior, exterior o ambos, y servicios adicionales',
          'Número de empleados y nómina estimada para los próximos 12 meses',
          'Ingresos estimados para los próximos 12 meses',
          'Vehículos (año, marca, modelo, VIN) y choferes',
          'Equipos que quiere asegurar, con su valor aproximado',
          'Reclamos de los últimos tres a cinco años',
        ] },
        { type: 'p', text: 'Relacionado: [responsabilidad civil general](/es/insurance/general-liability), [seguro para lavado a presión](/es/pressure-washing-insurance-florida) y [auto comercial](/es/insurance/commercial-auto).' },
      ],
      faqTitle: 'Seguro para limpieza de ventanas: preguntas frecuentes',
      faq: [
        { q: '¿La responsabilidad civil general cubre una ventana que rompo al limpiarla?', a: 'Los daños accidentales a la propiedad del cliente causados por su trabajo son el tipo de reclamo que atiende la responsabilidad civil general, según los términos, límites y deducible de la póliza. Algunas pólizas limitan la cobertura del objeto específico en el que está trabajando, así que pídanos que le mostremos cómo lo maneja su póliza.' },
        { q: 'Trabajo solo. ¿Qué suelen pedir los locales comerciales?', a: 'La mayoría pide un certificado que muestre responsabilidad civil general, y algunos quieren figurar como asegurado adicional. Envíenos su solicitud y confirmamos lo que permite su póliza.' },
        { q: '¿Mis escaleras y mi sistema de pértiga con agua están cubiertos?', a: 'No por la responsabilidad civil general. Las escaleras, pértigas y equipos de agua pura suelen cubrirse con una póliza de herramientas y equipos (inland marine), y el equipo instalado en la van se revisa al preparar la póliza de auto.' },
        { q: '¿Necesito compensación laboral?', a: 'Florida la exige a la mayoría de los empleadores privados con cuatro o más empleados, y a los de construcción desde uno. Llámenos antes de contratar y confirmamos qué regla aplica a su negocio.' },
        { q: '¿Solo trabajan con limpiadores de ventanas cerca de Florida City?', a: 'No. Nuestra oficina está en Florida City, pero atendemos negocios de limpieza de ventanas en toda Florida por teléfono, mensaje de texto y correo, en español, inglés y ruso.' },
      ],
      sources: sources('es', ['fs440_02', 'cbp2023', 'naics561720']),
    },
    ru: {
      metaTitle: 'Страховка для мойки окон во Флориде | M&K Agency',
      metaDesc: 'Страхование бизнеса по мойке окон во Флориде — дома, витрины, малоэтажные здания: ответственность, лестницы и оборудование, фургон, workers’ comp.',
      breadcrumb: 'Страховка для мойки окон',
      kicker: 'Мойка окон · Флорида',
      h1a: 'Страховка для мойки окон во Флориде —',
      h1b: 'для домов, витрин и малоэтажных зданий.',
      sub: 'Мойщики окон в частных домах и магазинах по всей Флориде: поможем застраховать ответственность при работе с лестницами, стеклом и водой на чужой собственности, а также фургон, оборудование и работников. По-русски, по-английски или по-испански.',
      linkLabel: 'Мойка окон',
      serviceType: 'Страхование бизнеса по мойке окон',
      intro: [
        { type: 'h2', text: 'Что может пойти не так при мойке окон' },
        { type: 'p', text: 'Мойка окон кажется простой работой, пока что-нибудь не разобьётся. Вы работаете на лестницах, рядом со стеклом, с водой и моющими средствами — часто у витрины, полной покупателей, или в доме, полном мебели. Бюро переписи США насчитывает во Флориде **6 675 клининговых предприятий** с наёмными работниками — это категория, в которую входит и мойка окон (County Business Patterns, 2023).' },
        { type: 'p', text: 'Чаще всего мойщики окон сталкиваются с такими претензиями:' },
        { type: 'ul', items: [
          'Треснувшее или разбитое стекло, повреждённая москитная сетка или направляющая окна.',
          'Лестница соскальзывает и повреждает край крыши, водосток, навес или вывеску магазина.',
          'Вода попадает внутрь и портит пол, стену или товар.',
          'Покупатель или прохожий поскальзывается на мокром тротуаре у витрины, которую вы моете.',
          'Моющее средство капает на машину, растения или окрашенную поверхность.',
          'Работник падает с лестницы или режется о разбитое стекло.',
          'Из фургона крадут лестницы, телескопические штанги с подачей воды или систему очистки воды.',
        ] },
      ],
      covTitle: 'Какие виды страховки обычно нужны бизнесу по мойке окон',
      cov: [
        { h: 'General liability (общая ответственность)', p: 'Для претензий о том, что ваша работа травмировала человека или повредила его имущество — разбитое стекло, падение на мокром тротуаре, — в рамках условий полиса. Магазины и управляющие компании обычно требуют этот полис.' },
        { h: 'Workers’ compensation', p: 'Оплачивает лечение и потерянный заработок, если работник пострадал на работе, например упал с лестницы. Когда она обязательна, зависит от числа работников и классификации вашей работы (см. ниже).' },
        { h: 'Коммерческое авто', p: 'Для фургона или пикапа, который возит лестницы и систему штанг с подачей воды, включая багажники и встроенное оборудование.' },
        { h: 'Инструмент и оборудование', p: 'Страховка inland marine для лестниц, штанг, систем очистки воды и другого снаряжения — в фургоне, на объекте или на хранении.' },
        { h: 'Business owner’s policy (BOP)', p: 'Для подходящих бизнесов объединяет общую ответственность со страховкой имущества бизнеса, например хранящихся материалов и оборудования.' },
      ],
      body: [
        { type: 'h2', text: 'Для кого эта страница' },
        { type: 'p', text: 'Эта страница — для бизнеса по мойке окон, который работает с **частными домами, витринами и малоэтажными зданиями**, с лестниц и штанг с земли. Расскажите нам обо всех услугах, включая дополнительные — ремонт сеток, чистку водостоков или мойку под давлением, — чтобы полис правильно описывал ваш бизнес.' },
        { type: 'h2', text: 'Что важно знать мойщику окон во Флориде' },
        { type: 'h3', text: 'Workers’ comp, когда вы нанимаете работников' },
        { type: 'p', text: `[Статуты Флориды § 440.02](${U.fs440_02}) требуют workers’ compensation у большинства частных работодателей с четырьмя и более работниками, а в строительной отрасли — уже с одним. Какой порог относится к вам, зависит от классификации вашей работы, поэтому, если собираетесь нанимать, попросите нас уточнить это до выхода первого работника.` },
        { type: 'h3', text: 'Магазины и коммерческие клиенты' },
        { type: 'p', text: 'Арендодатели торговых помещений, управляющие компании и франшизы часто просят сертификат страховки до первого визита, иногда со статусом additional insured. Пришлите запрос — сверим его с вашим полисом.' },
        { type: 'h2', text: 'Что подготовить для расчёта' },
        { type: 'ul', items: [
          'Какие объекты вы моете: дома, витрины, офисы в малоэтажных зданиях',
          'Сколько этажей в самом высоком из ваших регулярных объектов и каким оборудованием вы работаете (лестницы, штанги с подачей воды)',
          'Внутри, снаружи или и то и другое, какие дополнительные услуги',
          'Количество работников и ожидаемый фонд оплаты труда на 12 месяцев',
          'Ожидаемая выручка на 12 месяцев',
          'Машины (год, марка, модель, VIN) и водители',
          'Оборудование, которое нужно застраховать, с примерной стоимостью',
          'Страховые случаи за последние три–пять лет',
        ] },
        { type: 'p', text: 'См. также: [общая ответственность](/ru/insurance/general-liability), [страховка для мойки под давлением](/ru/pressure-washing-insurance-florida) и [коммерческое авто](/ru/insurance/commercial-auto).' },
      ],
      faqTitle: 'Страховка для мойки окон: частые вопросы',
      faq: [
        { q: 'Покроет ли general liability окно, которое я разбил во время мойки?', a: 'Случайный ущерб имуществу клиента, причинённый вашей работой, — это тот тип претензий, для которого существует general liability, в рамках условий, лимитов и франшизы полиса. Некоторые полисы ограничивают покрытие именно того предмета, с которым вы работаете, поэтому попросите нас показать, как это решено в вашем полисе.' },
        { q: 'Я работаю один. Что обычно просят магазины?', a: 'Большинство просят сертификат с general liability, а некоторые хотят быть вписаны как additional insured. Пришлите их запрос — мы проверим, что допускает ваш полис.' },
        { q: 'Застрахованы ли мои лестницы и система штанг с подачей воды?', a: 'General liability их не покрывает. Лестницы, штанги и системы очистки воды обычно страхуются полисом инструмента и оборудования (inland marine), а встроенное в фургон оборудование обсуждается при оформлении автополиса.' },
        { q: 'Нужен ли мне workers’ comp?', a: 'Флорида требует его у большинства частных работодателей с четырьмя и более работниками, а в строительстве — с одного. Позвоните до того, как нанимать, — уточним, какое правило относится к вашему бизнесу.' },
        { q: 'Вы работаете только с мойщиками окон рядом с Florida City?', a: 'Нет. Наш офис во Florida City, но мы работаем с бизнесом по мойке окон по всей Флориде по телефону, SMS и email — по-русски, по-английски и по-испански.' },
      ],
      sources: sources('ru', ['fs440_02', 'cbp2023', 'naics561720']),
    },
  },
};
