import type { BusinessPage } from './types';
import { SRC_URL as U, sources } from './sources';

// Commercial auto page. Scope: vehicles operating within Florida only
// (pickups, vans, box trucks for local delivery, trailers). Do not add
// interstate, long-haul or federal registration content.
export const WORK_TRUCK: BusinessPage = {
  path: '/work-truck-insurance-florida',
  icon: '🚚',
  published: '2026-09-26',
  modified: '2026-09-26',
  team: ['mikhail-kozlov', 'shane-henry', 'jose-egues-chalela'],
  copy: {
    en: {
      metaTitle: 'Work Truck Insurance in Florida | M&K Agency',
      metaDesc: 'Commercial auto insurance for pickups, cargo vans, box trucks and trailers used by Florida businesses. Talk to an agent in English, Spanish or Russian.',
      breadcrumb: 'Work truck insurance',
      kicker: 'Commercial Auto · Within Florida',
      h1a: 'Work truck insurance in Florida,',
      h1b: 'for the vehicles your business runs on.',
      sub: 'Pickups, cargo vans, box trucks and trailers used by contractors, service companies and local delivery businesses operating within Florida: we help you set up commercial auto coverage that matches how each vehicle is actually used. In English, Spanish or Russian.',
      linkLabel: 'Work trucks',
      serviceType: 'Commercial auto insurance',
      intro: [
        { type: 'h2', text: 'Who this page is for' },
        { type: 'p', text: 'This page is for businesses whose vehicles work **within Florida**: a contractor’s pickup and trailer, a plumber’s or electrician’s van, a landscaper’s truck, or a box truck making local deliveries for a store, supplier or service company.' },
        { type: 'p', text: 'What business vehicles run into:' },
        { type: 'ul', items: [
          'An at-fault accident that injures other people or damages their vehicles or property.',
          'Damage to your own truck from a collision, theft, vandalism or a storm.',
          'An employee driving a company vehicle, or their own car on a work errand, when something happens.',
          'A trailer that comes loose, or equipment that falls off on the road.',
          'Tools and equipment stolen from the truck bed or van.',
          'Downtime while a truck is in the shop and jobs or deliveries still have to happen.',
        ] },
      ],
      covTitle: 'Coverage that usually fits a work vehicle',
      cov: [
        { h: 'Liability', p: 'Bodily injury and property damage you cause to others while driving for the business, up to the limits you choose. Heavier trucks have higher legal minimums (see below).' },
        { h: 'PIP and property damage liability', p: 'Florida requires both before a vehicle with at least four wheels can be registered.' },
        { h: 'Collision & comprehensive', p: 'Physical damage to your own vehicles from a crash, theft, vandalism, fire, falling objects or storms, subject to deductibles.' },
        { h: 'Uninsured / underinsured motorist', p: 'Helps protect you and your drivers when the other driver has no insurance or not enough.' },
        { h: 'Hired & non-owned auto', p: 'Liability for vehicles your business rents, or employees’ own cars used for business errands.' },
        { h: 'Tools & equipment', p: 'Tools and gear carried in the truck are usually covered under a separate inland marine policy, not the auto policy.' },
      ],
      body: [
        { type: 'h2', text: 'Florida requirements to know' },
        { type: 'h3', text: 'PIP and property damage liability before registration' },
        { type: 'p', text: `According to the [Florida Department of Highway Safety and Motor Vehicles](${U.flhsmv}), before you register a vehicle with at least four wheels in Florida you must show proof of Personal Injury Protection (PIP) and Property Damage Liability (PDL), with a minimum of $10,000 of each.` },
        { type: 'h3', text: 'Heavier commercial vehicles need higher liability limits' },
        { type: 'p', text: `[Florida Statutes § 627.7415](${U.fs627_7415}) sets additional minimum combined bodily injury and property damage liability for commercial motor vehicles, based on gross vehicle weight: **$50,000** per occurrence from 26,000 to under 35,000 pounds, **$100,000** from 35,000 to under 44,000 pounds, and **$300,000** at 44,000 pounds or more. Many customers and contracts ask for more than the legal minimum, so tell us what you’ve been asked to carry.` },
        { type: 'h3', text: 'Safety rules for commercial vehicles operating within Florida' },
        { type: 'p', text: `[Florida Statutes § 316.302](${U.fs316_302}) applies federal motor carrier safety regulations to owners and drivers of commercial motor vehicles engaged in intrastate commerce, with exceptions written into the statute, including some for vehicles operated solely within Florida. Whether and how they apply depends on the vehicle and its use, so check the statute or ask FLHSMV about your trucks.` },
        { type: 'h2', text: 'Personal policy or commercial policy?' },
        { type: 'p', text: 'If a vehicle is titled to your business, used mainly for work, carries signage or permanently mounted equipment, or is driven by employees, a personal auto policy may not be the right fit. Tell us exactly how each vehicle is used and we’ll tell you what kind of policy it needs.' },
        { type: 'h2', text: 'What to have ready for a quote' },
        { type: 'ul', items: [
          'Each vehicle: year, make, model, VIN, and gross vehicle weight for trucks',
          'Whether it’s owned or leased, by you or by the business, and any lienholder',
          'Drivers: names, dates of birth, license numbers and driving history',
          'How each vehicle is used: carrying tools, pulling a trailer, local deliveries within Florida',
          'Where the vehicles are parked overnight',
          'Trailers and any permanently attached equipment',
          'Current or prior insurance, and claims in the last three to five years',
        ] },
        { type: 'p', text: 'Related: [commercial auto](/en/insurance/commercial-auto), [contractor insurance](/en/contractor-insurance-florida) and [landscaping insurance](/en/landscaping-insurance-florida).' },
      ],
      faqTitle: 'Work truck insurance: common questions',
      faq: [
        { q: 'Do I need commercial auto for a pickup I use for work?', a: 'Often, yes, especially if the truck is titled to the business, used mainly for jobs, pulls a trailer or is driven by employees. A personal auto policy may exclude or limit business use. Tell us how the truck is used and we’ll point you to the right policy.' },
        { q: 'Does my commercial auto policy cover the tools in my truck?', a: 'Usually not. Commercial auto covers the vehicle and your liability for driving it. Tools and equipment carried in it are typically covered under a separate tools and equipment (inland marine) policy.' },
        { q: 'Can you quote box trucks for local delivery?', a: 'Yes, for box trucks used by local businesses for deliveries within Florida. Have the truck’s gross vehicle weight, what you carry and the area you serve ready when you call.' },
        { q: 'My employees sometimes use their own cars for work errands. Is my business covered?', a: 'Their personal auto policy usually responds first, but your business can still be pulled into a claim. Hired and non-owned auto coverage can help protect the business in that situation. Ask us whether it fits your operation.' },
        { q: 'Do you only work with businesses near Florida City?', a: 'No. Our office is in Florida City, but we work with businesses across Florida by phone, text and email, in English, Spanish and Russian.' },
      ],
      sources: sources('en', ['flhsmv', 'fs627_7415', 'fs316_302']),
    },
    es: {
      metaTitle: 'Seguro para Camionetas de Trabajo en Florida | M&K Agency',
      metaDesc: 'Seguro de auto comercial para pickups, vans de carga, camiones de caja y remolques de negocios locales que operan dentro de Florida. Atención en español.',
      breadcrumb: 'Seguro para camionetas de trabajo',
      kicker: 'Auto comercial · Dentro de Florida',
      h1a: 'Seguro para camionetas de trabajo en Florida,',
      h1b: 'para los vehículos con los que trabaja su negocio.',
      sub: 'Pickups, vans de carga, camiones de caja y remolques de contratistas, empresas de servicios y negocios de reparto local que operan dentro de Florida: le ayudamos a armar una cobertura de auto comercial que corresponda a cómo se usa realmente cada vehículo. En español, inglés o ruso.',
      linkLabel: 'Camionetas de trabajo',
      serviceType: 'Seguro de auto comercial',
      intro: [
        { type: 'h2', text: 'Para quién es esta página' },
        { type: 'p', text: 'Esta página es para negocios cuyos vehículos trabajan **dentro de Florida**: la pickup y el remolque de un contratista, la van de un plomero o electricista, la camioneta de un jardinero, o un camión de caja que hace entregas locales para una tienda, un proveedor o una empresa de servicios.' },
        { type: 'p', text: 'Lo que les pasa a los vehículos de trabajo:' },
        { type: 'ul', items: [
          'Un accidente con culpa que lesiona a otras personas o daña sus vehículos o su propiedad.',
          'Daños a su propia camioneta por choque, robo, vandalismo o tormenta.',
          'Un empleado que maneja un vehículo de la empresa, o su propio carro en un mandado de trabajo, cuando ocurre algo.',
          'Un remolque que se suelta, o equipo que se cae en la carretera.',
          'Herramientas y equipo robados de la caja de la pickup o de la van.',
          'Tiempo perdido mientras la camioneta está en el taller y los trabajos o entregas siguen pendientes.',
        ] },
      ],
      covTitle: 'Coberturas que suelen necesitar los vehículos de trabajo',
      cov: [
        { h: 'Responsabilidad civil', p: 'Lesiones y daños a la propiedad que cause a terceros mientras maneja para el negocio, hasta los límites que elija. Los camiones más pesados tienen mínimos legales más altos (vea abajo).' },
        { h: 'PIP y daños a la propiedad (PDL)', p: 'Florida exige ambas antes de poder registrar un vehículo de al menos cuatro ruedas.' },
        { h: 'Choque y cobertura amplia', p: 'Daños físicos a sus propios vehículos por choque, robo, vandalismo, incendio, objetos que caen o tormentas, sujetos a deducibles.' },
        { h: 'Conductor sin seguro o con seguro insuficiente', p: 'Ayuda a protegerle a usted y a sus choferes cuando el otro conductor no tiene seguro o no tiene suficiente.' },
        { h: 'Autos alquilados y no propios', p: 'Responsabilidad por vehículos que su negocio alquila, o por los carros propios de empleados usados en mandados de trabajo.' },
        { h: 'Herramientas y equipos', p: 'Las herramientas y el equipo que lleva en la camioneta normalmente se cubren con una póliza inland marine aparte, no con la de auto.' },
      ],
      body: [
        { type: 'h2', text: 'Requisitos de Florida que debe conocer' },
        { type: 'h3', text: 'PIP y responsabilidad por daños a la propiedad antes del registro' },
        { type: 'p', text: `Según el [Departamento de Seguridad en las Carreteras y Vehículos Motorizados de Florida](${U.flhsmv}), antes de registrar un vehículo de al menos cuatro ruedas en Florida debe mostrar prueba de Protección contra Lesiones Personales (PIP) y de Responsabilidad por Daños a la Propiedad (PDL), con un mínimo de $10,000 de cada una.` },
        { type: 'h3', text: 'Los vehículos comerciales más pesados necesitan límites más altos' },
        { type: 'p', text: `Los [Estatutos de Florida § 627.7415](${U.fs627_7415}) fijan mínimos adicionales de responsabilidad combinada por lesiones y daños a la propiedad para vehículos motorizados comerciales, según su peso bruto vehicular: **$50,000** por ocurrencia de 26,000 a menos de 35,000 libras, **$100,000** de 35,000 a menos de 44,000 libras y **$300,000** a partir de 44,000 libras. Muchos clientes y contratos piden más que el mínimo legal, así que díganos cuánto le han pedido.` },
        { type: 'h3', text: 'Normas de seguridad para vehículos comerciales que operan dentro de Florida' },
        { type: 'p', text: `Los [Estatutos de Florida § 316.302](${U.fs316_302}) aplican las normas federales de seguridad de transportistas a los dueños y conductores de vehículos motorizados comerciales en comercio intraestatal, con excepciones escritas en el propio estatuto, incluidas algunas para vehículos que operan solo dentro de Florida. Si le aplican y cómo depende del vehículo y de su uso, así que consulte el estatuto o pregunte al FLHSMV por sus camiones.` },
        { type: 'h2', text: '¿Póliza personal o póliza comercial?' },
        { type: 'p', text: 'Si un vehículo está a nombre de su negocio, se usa principalmente para trabajar, lleva rotulación o equipo instalado de forma permanente, o lo manejan empleados, una póliza de auto personal puede no ser la adecuada. Díganos exactamente cómo se usa cada vehículo y le diremos qué tipo de póliza necesita.' },
        { type: 'h2', text: 'Qué tener a mano para cotizar' },
        { type: 'ul', items: [
          'Cada vehículo: año, marca, modelo, VIN y peso bruto vehicular en el caso de camiones',
          'Si es propio o arrendado, a su nombre o del negocio, y si tiene financiamiento',
          'Choferes: nombres, fechas de nacimiento, números de licencia e historial de manejo',
          'Cómo se usa cada vehículo: llevar herramientas, arrastrar un remolque, entregas locales dentro de Florida',
          'Dónde se estacionan los vehículos de noche',
          'Remolques y cualquier equipo instalado de forma permanente',
          'Seguro actual o anterior, y reclamos de los últimos tres a cinco años',
        ] },
        { type: 'p', text: 'Relacionado: [auto comercial](/es/insurance/commercial-auto), [seguro para contratistas](/es/contractor-insurance-florida) y [seguro para jardinería](/es/landscaping-insurance-florida).' },
      ],
      faqTitle: 'Seguro para camionetas de trabajo: preguntas frecuentes',
      faq: [
        { q: '¿Necesito auto comercial para una pickup que uso para trabajar?', a: 'Muchas veces sí, sobre todo si la camioneta está a nombre del negocio, se usa principalmente para trabajos, arrastra un remolque o la manejan empleados. Una póliza de auto personal puede excluir o limitar el uso comercial. Díganos cómo usa la camioneta y le indicamos la póliza adecuada.' },
        { q: '¿Mi póliza de auto comercial cubre las herramientas que llevo en la camioneta?', a: 'Normalmente no. El auto comercial cubre el vehículo y su responsabilidad al manejarlo. Las herramientas y equipos que lleva suelen cubrirse con una póliza aparte de herramientas y equipos (inland marine).' },
        { q: '¿Cotizan camiones de caja para reparto local?', a: 'Sí, para camiones de caja que usan negocios locales para entregas dentro de Florida. Tenga a mano el peso bruto vehicular del camión, lo que transporta y la zona que atiende cuando llame.' },
        { q: 'Mis empleados a veces usan sus propios carros para mandados de trabajo. ¿Mi negocio está cubierto?', a: 'Normalmente responde primero la póliza personal del empleado, pero su negocio igual puede verse involucrado en un reclamo. La cobertura de autos alquilados y no propios puede ayudar a proteger al negocio en esa situación. Pregúntenos si le conviene.' },
        { q: '¿Solo trabajan con negocios cerca de Florida City?', a: 'No. Nuestra oficina está en Florida City, pero atendemos negocios en toda Florida por teléfono, mensaje de texto y correo, en español, inglés y ruso.' },
      ],
      sources: sources('es', ['flhsmv', 'fs627_7415', 'fs316_302']),
    },
    ru: {
      metaTitle: 'Страховка рабочих машин во Флориде | M&K Agency',
      metaDesc: 'Страхование коммерческого авто для пикапов, грузовых фургонов, box truck и прицепов местного бизнеса, работающего внутри Флориды. Агент говорит по-русски.',
      breadcrumb: 'Страховка рабочих машин',
      kicker: 'Коммерческое авто · Внутри Флориды',
      h1a: 'Страховка рабочих машин во Флориде —',
      h1b: 'для транспорта, на котором держится ваш бизнес.',
      sub: 'Пикапы, грузовые фургоны, box truck и прицепы подрядчиков, сервисных компаний и местных служб доставки, работающих внутри Флориды: поможем оформить коммерческую автостраховку, которая соответствует тому, как реально используется каждая машина. По-русски, по-английски или по-испански.',
      linkLabel: 'Рабочие машины',
      serviceType: 'Страхование коммерческого авто',
      intro: [
        { type: 'h2', text: 'Для кого эта страница' },
        { type: 'p', text: 'Эта страница — для бизнеса, чьи машины работают **внутри Флориды**: пикап с прицепом у подрядчика, фургон сантехника или электрика, грузовик ландшафтной компании или box truck, который развозит местные заказы магазина, поставщика или сервисной компании.' },
        { type: 'p', text: 'С чем сталкиваются рабочие машины:' },
        { type: 'ul', items: [
          'ДТП по вашей вине, в котором пострадали люди, их машины или имущество.',
          'Повреждение вашей машины при столкновении, угоне, вандализме или шторме.',
          'Что-то случилось, когда работник был за рулём служебной машины — или своей, по рабочему поручению.',
          'Отцепившийся прицеп или оборудование, упавшее на дорогу.',
          'Кража инструмента из кузова пикапа или фургона.',
          'Простой, пока машина в ремонте, а заказы и доставки никто не отменял.',
        ] },
      ],
      covTitle: 'Какие виды страховки обычно нужны рабочей машине',
      cov: [
        { h: 'Ответственность (liability)', p: 'Вред здоровью и имуществу третьих лиц, причинённый вами за рулём по делам бизнеса, в пределах выбранных лимитов. Для тяжёлых грузовиков законные минимумы выше (см. ниже).' },
        { h: 'PIP и PDL', p: 'Флорида требует обе страховки до регистрации любой машины минимум с четырьмя колёсами.' },
        { h: 'Collision и comprehensive', p: 'Ущерб вашим машинам при столкновении, угоне, вандализме, пожаре, падении предметов или шторме — с учётом франшизы.' },
        { h: 'Незастрахованный водитель (UM/UIM)', p: 'Помогает защитить вас и ваших водителей, если у виновника нет страховки или её не хватает.' },
        { h: 'Hired & non-owned auto', p: 'Ответственность за машины, которые бизнес арендует, и за личные машины работников, используемые для рабочих поручений.' },
        { h: 'Инструмент и оборудование', p: 'Инструмент и снаряжение в машине обычно страхуются отдельным полисом inland marine, а не автополисом.' },
      ],
      body: [
        { type: 'h2', text: 'Требования Флориды, которые нужно знать' },
        { type: 'h3', text: 'PIP и страховка ущерба имуществу до регистрации' },
        { type: 'p', text: `По данным [Департамента безопасности дорожного движения и транспорта Флориды (FLHSMV)](${U.flhsmv}), прежде чем зарегистрировать во Флориде машину минимум с четырьмя колёсами, нужно предъявить подтверждение страховки Personal Injury Protection (PIP) и Property Damage Liability (PDL) — не менее $10,000 каждая.` },
        { type: 'h3', text: 'Для более тяжёлых коммерческих машин — более высокие лимиты' },
        { type: 'p', text: `[Статуты Флориды § 627.7415](${U.fs627_7415}) устанавливают дополнительные минимальные совокупные лимиты ответственности за вред здоровью и имуществу для коммерческих транспортных средств в зависимости от полной массы: **$50,000** на случай — от 26 000 до менее 35 000 фунтов, **$100,000** — от 35 000 до менее 44 000 фунтов и **$300,000** — от 44 000 фунтов. Многие заказчики и договоры требуют больше законного минимума, поэтому скажите нам, какие лимиты у вас просят.` },
        { type: 'h3', text: 'Правила безопасности для коммерческих машин, работающих внутри Флориды' },
        { type: 'p', text: `[Статуты Флориды § 316.302](${U.fs316_302}) распространяют федеральные правила безопасности перевозчиков на владельцев и водителей коммерческих транспортных средств, занятых перевозками внутри штата, с исключениями, прописанными в самом статуте, в том числе для машин, работающих только внутри Флориды. Применяются ли они к вам и как, зависит от машины и её использования, поэтому сверьтесь со статутом или уточните в FLHSMV.` },
        { type: 'h2', text: 'Личный полис или коммерческий?' },
        { type: 'p', text: 'Если машина оформлена на бизнес, используется в основном для работы, несёт рекламу или стационарно установленное оборудование или на ней ездят работники, личный автополис может не подойти. Расскажите, как именно используется каждая машина, и мы скажем, какой полис ей нужен.' },
        { type: 'h2', text: 'Что подготовить для расчёта' },
        { type: 'ul', items: [
          'Каждая машина: год, марка, модель, VIN, а для грузовиков — полная масса (GVW)',
          'В собственности или в лизинге, на вас или на бизнес, есть ли кредит',
          'Водители: имена, даты рождения, номера прав и история вождения',
          'Как используется каждая машина: возит инструмент, тянет прицеп, местная доставка внутри Флориды',
          'Где машины стоят ночью',
          'Прицепы и стационарно установленное оборудование',
          'Текущая или предыдущая страховка и страховые случаи за последние три–пять лет',
        ] },
        { type: 'p', text: 'См. также: [коммерческое авто](/ru/insurance/commercial-auto), [страховка для подрядчиков](/ru/contractor-insurance-florida) и [страховка для ландшафтного бизнеса](/ru/landscaping-insurance-florida).' },
      ],
      faqTitle: 'Страховка рабочих машин: частые вопросы',
      faq: [
        { q: 'Нужна ли коммерческая страховка для пикапа, на котором я езжу по работе?', a: 'Часто да — особенно если машина оформлена на бизнес, используется в основном для работы, тянет прицеп или на ней ездят работники. Личный автополис может исключать или ограничивать использование в бизнесе. Расскажите, как используется машина, и мы подскажем нужный полис.' },
        { q: 'Покрывает ли коммерческий автополис инструмент в машине?', a: 'Обычно нет. Коммерческое авто покрывает саму машину и вашу ответственность за рулём. Инструмент и оборудование в ней, как правило, страхуются отдельным полисом инструмента и оборудования (inland marine).' },
        { q: 'Вы делаете расчёт для box truck под местную доставку?', a: 'Да, для box truck, которые местный бизнес использует для доставки внутри Флориды. Подготовьте к звонку полную массу грузовика, что вы возите и в каком районе работаете.' },
        { q: 'Работники иногда ездят по делам на своих машинах. Защищён ли мой бизнес?', a: 'Обычно первым отвечает личный полис работника, но ваш бизнес всё равно могут втянуть в претензию. Страховка hired & non-owned auto может помочь защитить бизнес в такой ситуации. Спросите нас, подходит ли она вам.' },
        { q: 'Вы работаете только с бизнесом рядом с Florida City?', a: 'Нет. Наш офис во Florida City, но мы работаем с бизнесом по всей Флориде по телефону, SMS и email — по-русски, по-английски и по-испански.' },
      ],
      sources: sources('ru', ['flhsmv', 'fs627_7415', 'fs316_302']),
    },
  },
};
