import type { GuidePage } from './types';
import { sources } from './sources';

const SRC = ['crashReport', 'crashReportDriver', 'pip', 'flhsmv', 'um'] as const;

export const AFTER_ACCIDENT: GuidePage = {
  path: '/auto-insurance-after-accident-miami-dade',
  leadType: 'Auto',
  heroImage: 'guide-after-accident',
  ogImage: { src: '/og/after-accident.webp', alt: { en: 'What to do after a car accident in Florida — M&K Agency', es: 'Qué hacer después de un accidente de auto en Florida — M&K Agency', ru: 'Что делать после ДТП во Флориде — M&K Agency' } },
  published: '2026-10-03',
  modified: '2026-10-03',
  areaServed: [{ '@type': 'AdministrativeArea', name: 'Miami-Dade County, FL' }],
  copy: {
    en: {
      metaTitle: 'Car Accident in Miami-Dade: What to Do Next | M&K Agency',
      metaDesc: 'After a car accident in Miami-Dade: when Florida law requires a police report, the 14-day PIP rule, what PIP pays and what to tell your insurer. Call us.',
      breadcrumb: 'After a car accident in Miami-Dade',
      kicker: 'Auto insurance guide · Miami-Dade',
      h1a: 'Car accident in Miami-Dade?',
      h1b: 'What to do in the first 14 days.',
      answer: 'After a crash in Miami-Dade, check for injuries and call 911 if anyone is hurt. Florida law requires drivers to report crashes involving injury, death or apparent damage of at least $2,000 to police. Get medical care within 14 days to use your PIP benefits, and notify your insurer as soon as you can.',
      serviceType: 'Auto insurance',
      intro: [
        { type: 'h2', text: 'Step by step' },
        { type: 'ol', items: [
          '**Get safe and check on everyone.** Call 911 if anyone is hurt.',
          '**Report the crash when the law requires it.** Florida requires drivers to notify police right away when a crash causes injury, death or apparent property damage of at least $2,000. Each driver must give the officer proof of insurance.',
          '**If no officer files a report,** a driver involved in a property-damage crash generally has to submit a written report to FLHSMV within 10 days.',
          '**Document everything.** Take photos of the vehicles, the scene and any injuries. Write down the other driver’s name, insurer and policy number, and the names of witnesses.',
          '**See a doctor within 14 days.** Florida PIP pays medical benefits only if you get initial care within 14 days of the crash.',
          '**Notify your insurer promptly.** Your policy can require written notice as soon as practicable. Keep every bill, receipt and letter.',
        ] },
        { type: 'h2', text: 'What PIP does, in plain words' },
        { type: 'p', text: 'Personal Injury Protection is required on every Florida-registered car with four or more wheels, with a minimum of $10,000. It pays 80% of reasonable medical expenses and 60% of lost income, no matter who caused the crash, plus a $5,000 death benefit. If a qualified provider finds you did **not** have an emergency medical condition, medical benefits are limited to $2,500.' },
        { type: 'h2', text: 'Who this page is for' },
        { type: 'ul', items: [
          '**Drivers who just had a crash** in Miami-Dade and want to know their next step.',
          '**Our clients**, who can call us for help opening the claim.',
          '**Anyone whose policy carries only the state minimum** and who wants to know what it will and won’t pay.',
        ] },
      ],
      checklistTitle: 'Four questions we will ask you',
      checklist: [
        '**Was anyone hurt, and when did you first see a doctor?** The 14-day PIP rule makes this date important.',
        '**Was there a police report?** We will want the agency name and the report number.',
        '**Which coverages are on your policy?** Collision, comprehensive, rental, towing, bodily injury and uninsured motorist coverage each pay for different things.',
        '**Who was driving, and for what purpose?** If the car was being used for rideshare or delivery at the time, a personal policy may not respond the way you expect.',
      ],
      body: [
        { type: 'h2', text: 'What is not covered (honest limits)' },
        { type: 'ul', items: [
          '**PIP doesn’t fix cars.** It is injury coverage. Damage to your own car is covered only if you carry collision, or comprehensive for non-collision losses.',
          '**Property damage liability pays others, not you.** It covers damage you cause to someone else’s property.',
          '**PIP excludes massage therapy and acupuncture** from medical benefits.',
          '**Rental cars and towing** are paid only if those coverages are on your policy.',
          '**Work use** such as rideshare or delivery is commonly excluded from personal policies unless you added the right coverage.',
        ] },
      ],
      officeTitle: 'Talk to a licensed agent',
      office: [
        { type: 'p', text: 'If you’re our client, call **(305) 859-3953** and we’ll help you report the claim and explain the next steps. If you’re not, we’re still glad to explain how your coverage works. Call us, or leave your number and we’ll contact you within an hour during business hours.' },
        { type: 'p', text: 'We are insurance agents, not attorneys. For questions about fault, lawsuits or deadlines, talk to a Florida attorney.' },
        { type: 'p', text: 'We speak English, Spanish and Russian. Policy documents are issued in English; we explain them in your language.' },
      ],
      faqTitle: 'After a car accident in Miami-Dade: FAQ',
      faq: [
        { q: 'Do I have to call the police after a minor fender-bender?', a: 'Florida requires it when there is injury, death or apparent damage of at least $2,000. If no officer files a report on a property-damage crash, a driver generally has to submit a written report to FLHSMV within 10 days.' },
        { q: 'How long do I have to see a doctor after a crash?', a: 'To use PIP medical benefits, you must receive initial care within 14 days of the crash.' },
        { q: 'Does PIP cover me if the crash was my fault?', a: 'Yes. PIP pays your covered injury benefits no matter who caused the crash, up to your policy limit.' },
        { q: 'What if the other driver has no insurance?', a: 'Your PIP still applies to your injuries. Beyond that, uninsured motorist coverage can help with injuries to you and your passengers, but only if it is on your policy.' },
        { q: 'Should I call my agent or the insurance company first?', a: 'Either one, as long as the insurer is notified promptly. Our clients can call us and we will help open the claim.' },
      ],
      related: [
        { path: '/car-insurance-miami-dade-county-fl', label: 'Car insurance in Miami-Dade County' },
        { path: '/car-insurance-florida-city', label: 'Auto insurance in Florida City' },
        { path: '/protect/car-insurance', label: 'Guide: hit by a driver with no insurance? (uninsured motorist coverage)' },
        { path: '/gap-insurance', label: 'Gap insurance' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Accidente de carro en Miami-Dade: qué hacer | M&K Agency',
      metaDesc: 'Después de un choque en Miami-Dade: cuándo la ley exige reportar a la policía, la regla de 14 días del PIP, qué paga el PIP y qué decirle a su aseguradora.',
      breadcrumb: 'Después de un choque en Miami-Dade',
      kicker: 'Guía de seguro de auto · Miami-Dade',
      h1a: '¿Tuvo un accidente de carro en Miami-Dade?',
      h1b: 'Qué hacer en los primeros 14 días.',
      answer: 'Después de un choque en Miami-Dade, revise si hay heridos y llame al 911 si alguien está lesionado. La ley de Florida obliga a los conductores a reportar a la policía los accidentes con lesiones, muertes o daños aparentes de $2,000 o más. Reciba atención médica dentro de los 14 días para poder usar sus beneficios de PIP, y avise a su aseguradora lo antes posible.',
      serviceType: 'Seguro de auto',
      intro: [
        { type: 'h2', text: 'Paso a paso' },
        { type: 'ol', items: [
          '**Póngase a salvo y revise cómo están todos.** Llame al 911 si alguien está herido.',
          '**Reporte el accidente cuando la ley lo exige.** Florida obliga a los conductores a avisar de inmediato a la policía cuando un accidente causa lesiones, muertes o daños aparentes a la propiedad de $2,000 o más. Cada conductor debe mostrarle al oficial su prueba de seguro.',
          '**Si ningún oficial hace un informe,** el conductor involucrado en un accidente con daños a la propiedad por lo general debe enviar un informe escrito a FLHSMV dentro de 10 días.',
          '**Documente todo.** Tome fotos de los vehículos, del lugar y de cualquier lesión. Anote el nombre del otro conductor, su aseguradora y su número de póliza, y los nombres de los testigos.',
          '**Vea a un médico dentro de los 14 días.** El PIP de Florida paga beneficios médicos solo si recibe atención inicial dentro de los 14 días posteriores al accidente.',
          '**Avise a su aseguradora cuanto antes.** Su póliza puede exigir un aviso por escrito tan pronto como sea posible. Guarde cada factura, recibo y carta.',
        ] },
        { type: 'h2', text: 'Qué hace el PIP, en palabras sencillas' },
        { type: 'p', text: 'La protección contra lesiones personales (PIP) es obligatoria en todo vehículo de cuatro ruedas o más registrado en Florida, con un mínimo de $10,000. Paga el 80% de los gastos médicos razonables y el 60% del ingreso perdido, sin importar quién causó el accidente, más un beneficio por muerte de $5,000. Si un proveedor calificado determina que usted **no** tuvo una condición médica de emergencia, los beneficios médicos se limitan a $2,500.' },
        { type: 'h2', text: 'Para quién es esta página' },
        { type: 'ul', items: [
          '**Conductores que acaban de tener un choque** en Miami-Dade y quieren saber cuál es el siguiente paso.',
          '**Nuestros clientes**, que pueden llamarnos para que les ayudemos a abrir el reclamo.',
          '**Cualquiera cuya póliza tenga solo el mínimo del estado** y quiera saber qué paga y qué no.',
        ] },
      ],
      checklistTitle: 'Cuatro preguntas que le haremos',
      checklist: [
        '**¿Hubo heridos y cuándo vio a un médico por primera vez?** La regla de 14 días del PIP hace que esta fecha sea importante.',
        '**¿Hubo informe policial?** Le pediremos el nombre de la agencia y el número del informe.',
        '**¿Qué coberturas tiene su póliza?** Choque (collision), integral (comprehensive), carro de alquiler, remolque, responsabilidad por lesiones (BI) y conductor sin seguro (UM) pagan cosas distintas.',
        '**¿Quién manejaba y para qué?** Si el carro se estaba usando en ese momento para Uber/Lyft o entregas, una póliza personal puede no responder como usted espera.',
      ],
      body: [
        { type: 'h2', text: 'Lo que no está cubierto (límites claros)' },
        { type: 'ul', items: [
          '**El PIP no arregla carros.** Es una cobertura de lesiones. Los daños a su propio carro solo están cubiertos si tiene cobertura de choque (collision), o integral (comprehensive) para pérdidas que no son por choque.',
          '**La responsabilidad por daños a la propiedad (PDL) paga a otros, no a usted.** Cubre los daños que usted cause a la propiedad de otra persona.',
          '**El PIP excluye la masoterapia y la acupuntura** de los beneficios médicos.',
          '**El carro de alquiler y el remolque** solo se pagan si esas coberturas están en su póliza.',
          '**El uso para trabajar**, como Uber/Lyft o entregas, suele estar excluido de las pólizas personales si no agregó la cobertura correcta.',
        ] },
      ],
      officeTitle: 'Hable con un agente licenciado',
      office: [
        { type: 'p', text: 'Si es nuestro cliente, llame al **(305) 859-3953** y le ayudamos a reportar el reclamo y le explicamos los próximos pasos. Si no lo es, con gusto le explicamos cómo funciona su cobertura. Llámenos, o déjenos su número y lo contactamos en menos de una hora en horario de oficina.' },
        { type: 'p', text: 'Somos agentes de seguros, no abogados. Para preguntas sobre culpa, demandas o plazos, consulte con un abogado de Florida.' },
        { type: 'p', text: 'Hablamos inglés, español y ruso. Las pólizas se emiten en inglés; se las explicamos en su idioma.' },
      ],
      faqTitle: 'Después de un choque en Miami-Dade: preguntas frecuentes',
      faq: [
        { q: '¿Tengo que llamar a la policía después de un choque menor?', a: 'Florida lo exige cuando hay lesiones, muertes o daños aparentes de $2,000 o más. Si ningún oficial hace un informe de un accidente con daños a la propiedad, el conductor por lo general debe enviar un informe escrito a FLHSMV dentro de 10 días.' },
        { q: '¿Cuánto tiempo tengo para ver a un médico después de un choque?', a: 'Para usar los beneficios médicos del PIP, debe recibir atención inicial dentro de los 14 días posteriores al accidente.' },
        { q: '¿El PIP me cubre si el choque fue mi culpa?', a: 'Sí. El PIP paga sus beneficios por lesiones cubiertos sin importar quién causó el accidente, hasta el límite de su póliza.' },
        { q: '¿Y si el otro conductor no tiene seguro?', a: 'Su PIP se sigue aplicando a sus lesiones. Más allá de eso, la cobertura de conductor sin seguro (UM) puede ayudar con las lesiones suyas y de sus pasajeros, pero solo si está en su póliza.' },
        { q: '¿Llamo primero a mi agente o a la compañía de seguros?', a: 'A cualquiera de los dos, siempre que se avise a la aseguradora cuanto antes. Nuestros clientes pueden llamarnos y les ayudamos a abrir el reclamo.' },
      ],
      related: [
        { path: '/car-insurance-miami-dade-county-fl', label: 'Seguro de auto en el Condado Miami-Dade' },
        { path: '/car-insurance-florida-city', label: 'Seguro de auto en Florida City' },
        { path: '/protect/car-insurance', label: 'Guía: ¿lo chocó alguien sin seguro? (cobertura UM)' },
        { path: '/gap-insurance', label: 'Seguro GAP' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'ДТП в Miami-Dade: что делать дальше | M&K Agency',
      metaDesc: 'После ДТП в Miami-Dade: когда закон Флориды требует сообщить в полицию, правило 14 дней для PIP, что оплачивает PIP и что сказать страховой. Звоните нам.',
      breadcrumb: 'После ДТП в Miami-Dade',
      kicker: 'Гид по автостраховке · Miami-Dade',
      h1a: 'Попали в ДТП в Miami-Dade?',
      h1b: 'Что делать в первые 14 дней.',
      answer: 'После аварии в Miami-Dade проверьте, есть ли пострадавшие, и звоните 911, если кто-то травмирован. Закон Флориды обязывает водителей сообщать в полицию о ДТП с пострадавшими или погибшими либо с видимым ущербом от $2,000. Обратитесь к врачу в течение 14 дней, чтобы воспользоваться выплатами PIP, и как можно скорее сообщите в свою страховую.',
      serviceType: 'Автострахование',
      intro: [
        { type: 'h2', text: 'Пошагово' },
        { type: 'ol', items: [
          '**Обеспечьте безопасность и проверьте, как все себя чувствуют.** Звоните 911, если кто-то пострадал.',
          '**Сообщите о ДТП, когда этого требует закон.** Во Флориде водители обязаны сразу сообщить в полицию, если в аварии есть пострадавшие или погибшие либо видимый ущерб имуществу от $2,000. Каждый водитель должен предъявить офицеру подтверждение страховки.',
          '**Если офицер не составил отчёт,** водитель, попавший в ДТП с ущербом имуществу, как правило, должен в течение 10 дней подать письменный отчёт в FLHSMV.',
          '**Документируйте всё.** Сфотографируйте машины, место аварии и травмы. Запишите имя другого водителя, его страховую и номер полиса, а также имена свидетелей.',
          '**Обратитесь к врачу в течение 14 дней.** PIP во Флориде оплачивает лечение, только если первичная помощь получена в течение 14 дней после аварии.',
          '**Сразу сообщите в свою страховую.** Полис может требовать письменного уведомления в кратчайший разумный срок. Сохраняйте все счета, чеки и письма.',
        ] },
        { type: 'h2', text: 'Что делает PIP — простыми словами' },
        { type: 'p', text: 'PIP (Personal Injury Protection, страхование от травм) обязательна для каждой машины с четырьмя и более колёсами, зарегистрированной во Флориде, с минимумом $10,000. Она оплачивает 80% разумных медицинских расходов и 60% потерянного дохода независимо от того, кто виноват в аварии, плюс $5,000 при гибели. Если квалифицированный медик установит, что у вас **не** было экстренного медицинского состояния, выплаты на лечение ограничиваются $2,500.' },
        { type: 'h2', text: 'Для кого эта страница' },
        { type: 'ul', items: [
          '**Водители, которые только что попали в ДТП** в Miami-Dade и хотят знать, что делать дальше.',
          '**Наши клиенты**, которые могут позвонить нам, чтобы мы помогли открыть клейм.',
          '**Все, у кого в полисе только минимум штата**, и кто хочет знать, что он оплатит, а что нет.',
        ] },
      ],
      checklistTitle: 'Четыре вопроса, которые мы вам зададим',
      checklist: [
        '**Были ли пострадавшие и когда вы впервые обратились к врачу?** Из-за правила 14 дней для PIP эта дата важна.',
        '**Был ли полицейский отчёт?** Нам понадобятся название ведомства и номер отчёта.',
        '**Какие покрытия есть в вашем полисе?** Collision, comprehensive, аренда машины, эвакуатор, bodily injury и покрытие от незастрахованных водителей (UM) оплачивают разные вещи.',
        '**Кто был за рулём и с какой целью?** Если машина в тот момент использовалась для такси через приложение или доставки, личный полис может сработать не так, как вы ожидаете.',
      ],
      body: [
        { type: 'h2', text: 'Что не покрывается (честно о границах)' },
        { type: 'ul', items: [
          '**PIP не ремонтирует машины.** Это покрытие травм. Ущерб вашей собственной машине покрывается, только если у вас есть collision, или comprehensive для ущерба не от столкновения.',
          '**PDL (ответственность за ущерб имуществу) платит другим, а не вам.** Она покрывает ущерб, который вы причинили чужому имуществу.',
          '**PIP не оплачивает массаж и иглоукалывание.**',
          '**Аренда машины и эвакуатор** оплачиваются, только если эти покрытия есть в полисе.',
          '**Использование для работы**, например такси через приложение или доставка, обычно исключено из личных полисов, если не добавлено нужное покрытие.',
        ] },
      ],
      officeTitle: 'Поговорите с лицензированным агентом',
      office: [
        { type: 'p', text: 'Если вы наш клиент, звоните **(305) 859-3953** — мы поможем заявить клейм и объясним следующие шаги. Если нет, мы всё равно с радостью объясним, как работает ваше покрытие. Позвоните нам или оставьте номер — мы свяжемся с вами в течение часа в рабочее время.' },
        { type: 'p', text: 'Мы страховые агенты, а не адвокаты. С вопросами о виновности, исках или сроках обращайтесь к адвокату во Флориде.' },
        { type: 'p', text: 'Мы говорим по-английски, по-испански и по-русски. Полисы выдаются на английском языке; мы объясняем их на вашем языке.' },
      ],
      faqTitle: 'После ДТП в Miami-Dade: частые вопросы',
      faq: [
        { q: 'Нужно ли вызывать полицию после мелкой аварии?', a: 'Во Флориде это обязательно, если есть пострадавшие или погибшие либо видимый ущерб от $2,000. Если офицер не составил отчёт о ДТП с ущербом имуществу, водитель, как правило, должен в течение 10 дней подать письменный отчёт в FLHSMV.' },
        { q: 'Сколько времени есть, чтобы обратиться к врачу после аварии?', a: 'Чтобы воспользоваться выплатами PIP на лечение, первичную помощь нужно получить в течение 14 дней после аварии.' },
        { q: 'Покрывает ли меня PIP, если авария произошла по моей вине?', a: 'Да. PIP оплачивает положенные вам выплаты по травмам независимо от того, кто виноват в аварии, в пределах лимита полиса.' },
        { q: 'Что, если у другого водителя нет страховки?', a: 'Ваша PIP всё равно действует для ваших травм. Сверх этого покрытие от незастрахованных водителей (UM) может помочь с травмами у вас и ваших пассажиров, но только если оно есть в вашем полисе.' },
        { q: 'Кому звонить сначала — агенту или в страховую компанию?', a: 'Любому из них, главное — быстро уведомить страховую. Наши клиенты могут позвонить нам, и мы поможем открыть клейм.' },
      ],
      related: [
        { path: '/car-insurance-miami-dade-county-fl', label: 'Автостраховка в округе Miami-Dade' },
        { path: '/car-insurance-florida-city', label: 'Автостраховка во Florida City' },
        { path: '/protect/car-insurance', label: 'Гид: в вас врезался водитель без страховки? (покрытие UM)' },
        { path: '/gap-insurance', label: 'GAP-страховка' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
