import type { GuidePage } from './types';

// Scope confirmed by Mikhail (2026-10-03): the agency writes general liability
// and small-business risks that fit its markets; other lines case by case.
// No carrier names, no workers' comp / inland marine / commercial property.
export const COMMERCIAL_FC: GuidePage = {
  path: '/commercial-insurance-florida-city',
  leadType: 'Commercial',
  heroImage: 'guide-commercial-gl',
  ogImage: { src: '/og/commercial-gl.webp', alt: { en: 'Commercial general liability insurance in Florida — M&K Agency', es: 'Seguro de responsabilidad civil comercial en Florida — M&K Agency', ru: 'Страхование коммерческой ответственности во Флориде — M&K Agency' } },
  published: '2026-10-03',
  modified: '2026-10-03',
  areaServed: [{ '@type': 'City', name: 'Florida City, FL' }, { '@type': 'City', name: 'Homestead, FL' }, { '@type': 'State', name: 'Florida' }],
  copy: {
    en: {
      metaTitle: 'Commercial Insurance in Florida City, FL | M&K Agency',
      metaDesc: 'General liability for eligible small businesses and contractors in Florida City and South Dade, subject to underwriting. Help in English, Spanish or Russian.',
      breadcrumb: 'Commercial insurance in Florida City',
      kicker: 'Commercial insurance · Florida City, FL',
      h1a: 'Commercial insurance for Florida City businesses,',
      h1b: 'from a local agency.',
      answer: 'M&K Agency helps eligible small businesses and contractors in Florida City and South Dade with general liability insurance. We write general liability and small-business risks that fit our markets; other lines can be discussed case by case. All coverage is subject to underwriting. Talk to a licensed agent at our Florida City office in English, Spanish or Russian: (305) 859-3953.',
      serviceType: 'General liability insurance',
      intro: [
        { type: 'h2', text: 'Who this page is for' },
        { type: 'ul', items: [
          '**Contractors and trades** (handyman, painting, pressure washing, landscaping, window cleaning) who work in customers’ homes and need certificates of insurance for jobs.',
          '**Shops, offices and other small businesses** along US-1 and Krome Avenue that need liability coverage.',
          '**Home-based businesses**, which often fall outside a homeowners policy.',
          '**Businesses asked by a landlord or client** to show proof of liability coverage.',
        ] },
      ],
      checklistTitle: 'Four questions we will ask you',
      checklist: [
        '**What exactly do you do, and where?** Coverage depends on your operations. Working in customers’ homes, on job sites or only at your own location are three different risks.',
        '**Have you had insurance before, and any liability claims?** Prior coverage and claims history are part of underwriting.',
        '**What do your contracts or landlord require?** Many contracts call for specific liability limits, certificates of insurance or additional insured wording. Bring the contract and we will read the insurance section with you.',
        '**Do you need coverage other than general liability?** Tell us. Other lines can be discussed case by case, and if we can’t help, we will tell you plainly.',
      ],
      body: [
        { type: 'h2', text: 'What is not covered (honest limits)' },
        { type: 'ul', items: [
          '**General liability does not cover injuries to your own employees.**',
          '**General liability does not cover your vehicles.**',
          '**General liability does not cover your own tools, equipment or building.**',
          '**Professional mistakes** are generally outside general liability.',
          '**Underwriting decides eligibility.** Some types of business may not fit our markets. If we can’t help, we will tell you plainly.',
        ] },
      ],
      officeTitle: 'Talk to a licensed agent',
      office: [
        { type: 'p', text: 'Call **(305) 859-3953**, or leave your number and we’ll contact you within an hour during business hours. Bring your current policy and any contract with insurance requirements to **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**. We are open Monday to Friday 9 to 6, with Saturdays by appointment.' },
        { type: 'p', text: 'We speak English, Spanish and Russian. Policy documents are issued in English; we explain them in your language.' },
      ],
      faqTitle: 'Commercial insurance in Florida City: FAQ',
      faq: [
        { q: 'What kind of business insurance do you write?', a: 'We write general liability and small-business risks that fit our markets, mainly for eligible small businesses and contractors. Other lines can be discussed case by case. Call us and we will tell you plainly whether we can help.' },
        { q: 'What does general liability insurance respond to?', a: 'It generally responds to claims that your business caused bodily injury or property damage to other people, subject to the policy’s terms, limits and exclusions. It does not cover your own employees, vehicles, tools or building.' },
        { q: 'Can you help me get a certificate of insurance for a job?', a: 'Yes. Tell us who needs the certificate and what wording the contract requires, and we will help you get it for policies we service.' },
        { q: 'Is my homeowners policy enough for a home-based business?', a: 'Often not. Homeowners policies often exclude business activity. Tell us what you do and we will explain the options for your business, subject to underwriting.' },
        { q: 'Do you work with businesses outside Florida City?', a: 'Yes. Our office is in Florida City, and we work with businesses across Florida by phone, email and WhatsApp.' },
      ],
      related: [
        { path: '/insurance/general-liability', label: 'General liability insurance' },
        { path: '/contractor-insurance-florida', label: 'Contractor insurance' },
        { path: '/handyman-insurance-florida', label: 'Handyman insurance' },
        { path: '/painting-contractor-insurance-florida', label: 'Painting contractor insurance' },
        { path: '/pressure-washing-insurance-florida', label: 'Pressure washing insurance' },
        { path: '/landscaping-insurance-florida', label: 'Landscaping insurance' },
        { path: '/window-cleaning-insurance-florida', label: 'Window cleaning insurance' },
        { path: '/work-truck-insurance-florida', label: 'Work truck insurance' },
        { path: '/builders-risk-insurance-florida', label: 'Builders risk insurance' },
      ],
      sources: [],
    },
    es: {
      metaTitle: 'Seguro comercial en Florida City, FL | M&K Agency',
      metaDesc: 'Responsabilidad civil general para negocios y contratistas elegibles en Florida City y South Dade, sujeto a suscripción. En inglés, español o ruso.',
      breadcrumb: 'Seguro comercial en Florida City',
      kicker: 'Seguro comercial · Florida City, FL',
      h1a: 'Seguro comercial para negocios de Florida City,',
      h1b: 'de una agencia local.',
      answer: 'M&K Agency ayuda a pequeños negocios y contratistas elegibles de Florida City y el sur de Miami-Dade con seguros de responsabilidad civil general. Emitimos responsabilidad civil general y riesgos de pequeños negocios que encajan en nuestros mercados; otras líneas se pueden conversar caso por caso. Toda cobertura está sujeta a suscripción (underwriting). Hable con un agente licenciado en nuestra oficina de Florida City, en inglés, español o ruso: (305) 859-3953.',
      serviceType: 'Seguro de responsabilidad civil general',
      intro: [
        { type: 'h2', text: 'Para quién es esta página' },
        { type: 'ul', items: [
          '**Contratistas y oficios** (handyman, pintura, lavado a presión, jardinería, limpieza de ventanas) que trabajan en casas de clientes y necesitan certificados de seguro para sus trabajos.',
          '**Tiendas, oficinas y otros pequeños negocios** a lo largo de la US-1 y la Krome Avenue que necesitan cobertura de responsabilidad.',
          '**Negocios desde casa**, que muchas veces quedan fuera de la póliza de casa.',
          '**Negocios a los que un arrendador o un cliente les pide** una prueba de cobertura de responsabilidad.',
        ] },
      ],
      checklistTitle: 'Cuatro preguntas que le haremos',
      checklist: [
        '**¿A qué se dedica exactamente y dónde?** La cobertura depende de sus operaciones. Trabajar en casas de clientes, en obras o solo en su propio local son tres riesgos distintos.',
        '**¿Ha tenido seguro antes y algún reclamo de responsabilidad?** La cobertura anterior y el historial de reclamos forman parte de la suscripción.',
        '**¿Qué exigen sus contratos o su arrendador?** Muchos contratos piden límites de responsabilidad específicos, certificados de seguro o la cláusula de asegurado adicional (additional insured). Traiga el contrato y leemos con usted la sección de seguros.',
        '**¿Necesita otra cobertura además de la responsabilidad civil general?** Díganos. Otras líneas se pueden conversar caso por caso, y si no podemos ayudarle, se lo diremos con claridad.',
      ],
      body: [
        { type: 'h2', text: 'Lo que no está cubierto (límites claros)' },
        { type: 'ul', items: [
          '**La responsabilidad civil general no cubre las lesiones de sus propios empleados.**',
          '**La responsabilidad civil general no cubre sus vehículos.**',
          '**La responsabilidad civil general no cubre sus propias herramientas, equipos ni su edificio.**',
          '**Los errores profesionales** por lo general quedan fuera de la responsabilidad civil general.',
          '**La suscripción decide la elegibilidad.** Algunos tipos de negocio pueden no encajar en nuestros mercados. Si no podemos ayudarle, se lo diremos con claridad.',
        ] },
      ],
      officeTitle: 'Hable con un agente licenciado',
      office: [
        { type: 'p', text: 'Llame al **(305) 859-3953**, o déjenos su número y lo contactamos en menos de una hora en horario de oficina. Traiga su póliza actual y cualquier contrato con requisitos de seguro a **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**. Abrimos de lunes a viernes de 9 a 6, y los sábados con cita.' },
        { type: 'p', text: 'Hablamos inglés, español y ruso. Las pólizas se emiten en inglés; se las explicamos en su idioma.' },
      ],
      faqTitle: 'Seguro comercial en Florida City: preguntas frecuentes',
      faq: [
        { q: '¿Qué tipo de seguro comercial emiten?', a: 'Emitimos responsabilidad civil general y riesgos de pequeños negocios que encajan en nuestros mercados, sobre todo para pequeños negocios y contratistas elegibles. Otras líneas se pueden conversar caso por caso. Llámenos y le diremos con claridad si podemos ayudarle.' },
        { q: '¿A qué responde el seguro de responsabilidad civil general?', a: 'Por lo general responde a reclamos de que su negocio causó lesiones corporales o daños a la propiedad de otras personas, según los términos, límites y exclusiones de la póliza. No cubre a sus propios empleados, ni sus vehículos, herramientas o edificio.' },
        { q: '¿Me pueden ayudar a conseguir un certificado de seguro para un trabajo?', a: 'Sí. Díganos quién necesita el certificado y qué texto exige el contrato, y le ayudamos a obtenerlo para las pólizas que atendemos.' },
        { q: '¿Mi póliza de casa alcanza para un negocio desde casa?', a: 'Muchas veces no. Las pólizas de casa a menudo excluyen la actividad comercial. Cuéntenos a qué se dedica y le explicamos las opciones para su negocio, sujeto a suscripción.' },
        { q: '¿Trabajan con negocios fuera de Florida City?', a: 'Sí. Nuestra oficina está en Florida City y trabajamos con negocios de toda Florida por teléfono, correo y WhatsApp.' },
      ],
      related: [
        { path: '/insurance/general-liability', label: 'Seguro de responsabilidad civil general' },
        { path: '/contractor-insurance-florida', label: 'Seguro para contratistas' },
        { path: '/handyman-insurance-florida', label: 'Seguro para handyman' },
        { path: '/painting-contractor-insurance-florida', label: 'Seguro para pintores' },
        { path: '/pressure-washing-insurance-florida', label: 'Seguro para lavado a presión' },
        { path: '/landscaping-insurance-florida', label: 'Seguro para jardinería' },
        { path: '/window-cleaning-insurance-florida', label: 'Seguro para limpieza de ventanas' },
        { path: '/work-truck-insurance-florida', label: 'Seguro para camionetas de trabajo' },
        { path: '/builders-risk-insurance-florida', label: 'Seguro builders risk (obra en construcción)' },
      ],
      sources: [],
    },
    ru: {
      metaTitle: 'Страхование бизнеса во Florida City, FL | M&K Agency',
      metaDesc: 'General liability для малого бизнеса и подрядчиков во Florida City и South Dade при условии андеррайтинга. По-английски, по-испански или по-русски.',
      breadcrumb: 'Страхование бизнеса во Florida City',
      kicker: 'Страхование бизнеса · Florida City, FL',
      h1a: 'Страхование бизнеса во Florida City —',
      h1b: 'от местного агентства.',
      answer: 'M&K Agency помогает малому бизнесу и подрядчикам во Florida City и на юге Miami-Dade со страхованием общей ответственности (general liability), если бизнес подходит под требования. Мы оформляем general liability и риски малого бизнеса, которые подходят нашим рынкам; другие виды страхования можно обсудить индивидуально. Любое покрытие — при условии андеррайтинга. Поговорите с лицензированным агентом в нашем офисе во Florida City по-английски, по-испански или по-русски: (305) 859-3953.',
      serviceType: 'Страхование общей ответственности',
      intro: [
        { type: 'h2', text: 'Для кого эта страница' },
        { type: 'ul', items: [
          '**Подрядчики и мастера** (хендимены, маляры, мойка под давлением, ландшафт и газоны, мойка окон), которые работают в домах клиентов и которым для заказов нужен сертификат страховки.',
          '**Магазины, офисы и другой малый бизнес** вдоль US-1 и Krome Avenue, которым нужно покрытие ответственности.',
          '**Бизнес на дому**, который часто не попадает под полис на дом.',
          '**Бизнес, у которого арендодатель или клиент требует** подтверждение страхования ответственности.',
        ] },
      ],
      checklistTitle: 'Четыре вопроса, которые мы вам зададим',
      checklist: [
        '**Чем именно вы занимаетесь и где?** Покрытие зависит от вашей деятельности. Работа в домах клиентов, на стройке или только у себя — это три разных риска.',
        '**Была ли у вас страховка раньше и были ли претензии по ответственности?** Предыдущее покрытие и история клеймов учитываются при андеррайтинге.',
        '**Что требуют ваши договоры или арендодатель?** Многие договоры требуют определённых лимитов ответственности, сертификатов страховки или формулировки additional insured. Принесите договор — прочитаем раздел о страховке вместе.',
        '**Нужно ли вам что-то кроме general liability?** Скажите нам. Другие виды страхования можно обсудить индивидуально, и если мы не сможем помочь, скажем прямо.',
      ],
      body: [
        { type: 'h2', text: 'Что не покрывается (честно о границах)' },
        { type: 'ul', items: [
          '**General liability не покрывает травмы ваших собственных сотрудников.**',
          '**General liability не покрывает ваши машины.**',
          '**General liability не покрывает ваш собственный инструмент, оборудование или здание.**',
          '**Профессиональные ошибки**, как правило, не входят в general liability.',
          '**Решение о страховании принимается по итогам андеррайтинга.** Некоторые виды бизнеса могут не подходить нашим рынкам. Если мы не сможем помочь, скажем прямо.',
        ] },
      ],
      officeTitle: 'Поговорите с лицензированным агентом',
      office: [
        { type: 'p', text: 'Звоните **(305) 859-3953** или оставьте номер — мы свяжемся с вами в течение часа в рабочее время. Приносите действующий полис и договоры с требованиями к страховке по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**. Мы работаем с понедельника по пятницу с 9 до 6, в субботу — по записи.' },
        { type: 'p', text: 'Мы говорим по-английски, по-испански и по-русски. Полисы выдаются на английском языке; мы объясняем их на вашем языке.' },
      ],
      faqTitle: 'Страхование бизнеса во Florida City: частые вопросы',
      faq: [
        { q: 'Какое страхование бизнеса вы оформляете?', a: 'Мы оформляем general liability и риски малого бизнеса, которые подходят нашим рынкам, в основном для малого бизнеса и подрядчиков, подходящих под требования. Другие виды страхования можно обсудить индивидуально. Позвоните — мы прямо скажем, сможем ли помочь.' },
        { q: 'На что распространяется страхование общей ответственности?', a: 'Как правило, на претензии о том, что ваш бизнес причинил телесные повреждения или ущерб имуществу других людей, — на условиях, в пределах лимитов и с исключениями полиса. Ваших сотрудников, машины, инструмент и здание оно не покрывает.' },
        { q: 'Поможете получить сертификат страховки для заказа?', a: 'Да. Скажите, кому нужен сертификат и какую формулировку требует договор, и мы поможем получить его по полисам, которые мы обслуживаем.' },
        { q: 'Хватит ли полиса на дом для бизнеса на дому?', a: 'Часто нет. Полисы на дом нередко исключают коммерческую деятельность. Расскажите, чем вы занимаетесь, и мы объясним варианты для вашего бизнеса при условии андеррайтинга.' },
        { q: 'Вы работаете с бизнесом за пределами Florida City?', a: 'Да. Наш офис во Florida City, а с бизнесом по всей Флориде мы работаем по телефону, почте и в WhatsApp.' },
      ],
      related: [
        { path: '/insurance/general-liability', label: 'Страхование ответственности (General Liability)' },
        { path: '/contractor-insurance-florida', label: 'Страховка для подрядчиков' },
        { path: '/handyman-insurance-florida', label: 'Страховка для хендимена' },
        { path: '/painting-contractor-insurance-florida', label: 'Страховка для маляров' },
        { path: '/pressure-washing-insurance-florida', label: 'Страховка для мойки под давлением' },
        { path: '/landscaping-insurance-florida', label: 'Страховка для ландшафтного бизнеса' },
        { path: '/window-cleaning-insurance-florida', label: 'Страховка для мойки окон' },
        { path: '/work-truck-insurance-florida', label: 'Страховка рабочих машин' },
        { path: '/builders-risk-insurance-florida', label: 'Страховка builders risk (строящийся объект)' },
      ],
      sources: [],
    },
  },
};
