import type { GuidePage } from './types';
import { sources } from './sources';

const SRC = ['hurricaneDef', 'deductibles', 'mitigation', 'oirTropical', 'dfsHurricane', 'claimDeadline', 'citizensFlood'] as const;

export const WIND_DEDUCTIBLE: GuidePage = {
  path: '/florida-home-insurance-wind-deductible',
  leadType: 'Home',
  heroImage: 'guide-wind-deductible',
  ogImage: { src: '/og/wind-deductible.webp', alt: { en: 'Florida hurricane wind deductible explained — M&K Agency', es: 'Deducible por huracán en Florida explicado — M&K Agency', ru: 'Франшиза при урагане во Флориде — M&K Agency' } },
  published: '2026-10-03',
  modified: '2026-10-03',
  areaServed: [{ '@type': 'State', name: 'Florida' }],
  copy: {
    en: {
      metaTitle: 'Florida Hurricane Deductible, Explained | M&K Agency',
      metaDesc: 'How Florida’s hurricane (wind) deductible works: when it applies, 2%, 5% or 10% options, once per calendar year, tropical storms and what to check before June.',
      breadcrumb: 'Florida hurricane deductible',
      kicker: 'Home insurance guide · Florida',
      h1a: 'Florida hurricane (wind) deductible:',
      h1b: 'what you pay before your policy does.',
      answer: 'In Florida, the hurricane deductible applies to windstorm damage from a storm the National Hurricane Center has declared a hurricane, from when a hurricane warning is issued for any part of Florida until 72 hours after the last watch or warning ends. It is often 2%, 5% or 10% of your dwelling limit and generally applies once per calendar year.',
      serviceType: 'Homeowners insurance',
      intro: [
        { type: 'h2', text: 'Who this page is for' },
        { type: 'ul', items: [
          '**Homeowners and condo owners** reviewing a renewal before hurricane season.',
          '**Buyers** comparing deductible options before closing.',
          '**Anyone who just found out** their “wind deductible” is a percentage, not a flat dollar amount.',
        ] },
        { type: 'h2', text: 'How the hurricane deductible works' },
        { type: 'ul', items: [
          '**It’s a percentage of the dwelling limit, not of the damage.** With a $300,000 dwelling limit, a 2% hurricane deductible is $6,000 and a 5% deductible is $15,000. Florida law requires the dollar amount to be printed on your declarations page.',
          '**Options insurers must offer.** Before issuing a personal residential policy, insurers must offer hurricane deductibles of $500, 2%, 5% and 10% of the dwelling limit. There are exceptions by dwelling limit; for example, the $500 option isn’t required at $250,000 and up.',
          '**Above 10% takes extra steps.** For a home valued under $500,000, a hurricane deductible above 10% requires a handwritten, signed statement from the policyholder. If there is a mortgage, the lender must approve it in writing.',
          '**Once per calendar year, with conditions.** If more than one hurricane damages your home in the same calendar year, and you are insured by the same insurer or insurer group, the later storm uses the greater of what is left of your hurricane deductible or your regular deductible. Your insurer may ask you to report smaller losses or keep receipts, so document every storm loss, even small ones.',
          '**Tropical storms are different.** Damage from a storm before the National Hurricane Center declares it a hurricane falls under your regular “all other perils” deductible, not the hurricane deductible.',
        ] },
      ],
      checklistTitle: 'Four questions we will ask you',
      checklist: [
        '**What is your dwelling limit and your hurricane deductible in dollars?** Both are on the declarations page.',
        '**How much cash could you realistically pay the week after a storm?** That number should guide your deductible choice.',
        '**Do you have a wind mitigation inspection report?** Florida law requires insurers to offer either a reduced hurricane deductible or a credit for qualifying mitigation features. Which one you get, and how much, depends on the insurer and the inspection.',
        '**Do you have a mortgage, and what does your lender require?** Lenders can limit how high a deductible you may choose.',
      ],
      body: [
        { type: 'h2', text: 'What is not covered (honest limits)' },
        { type: 'ul', items: [
          '**Flood is not part of hurricane coverage.** Storm-surge and rising-water damage needs a separate flood policy, which has its own deductible.',
          '**The deductible is yours to pay.** No homeowners policy pays the hurricane deductible back to you.',
          '**Separate roof deductibles exist.** Some policies include one for non-hurricane roof claims, so read your declarations page closely.',
          '**Wind may be on a separate policy.** Some homes carry wind coverage through a separate policy, such as a Citizens Property Insurance wind-only policy, with its own deductible.',
        ] },
      ],
      officeTitle: 'Talk to a licensed agent',
      office: [
        { type: 'p', text: 'Send us your declarations page and we’ll explain your hurricane deductible in dollars and the options you have at renewal. Call **(305) 859-3953**, or leave your number and we’ll contact you within an hour during business hours.' },
        { type: 'p', text: 'We speak English, Spanish and Russian. Policy documents are issued in English; we explain them in your language.' },
      ],
      faqTitle: 'Florida hurricane deductible: FAQ',
      faq: [
        { q: 'Does the hurricane deductible apply to tropical storms?', a: 'No. It applies only to a storm the National Hurricane Center has declared a hurricane, during the window set by Florida law. Damage before that declaration uses your regular deductible.' },
        { q: 'Is the hurricane deductible per storm or per year?', a: 'For personal residential policies it generally applies once per calendar year, as long as you stay with the same insurer or insurer group. A later hurricane uses the greater of your remaining hurricane deductible or your regular deductible.' },
        { q: 'Can I change my hurricane deductible in the middle of hurricane season?', a: 'Usually changes are made at renewal, and insurers can restrict changes once a storm threatens. If you want a different deductible, ask well before June 1.' },
        { q: 'Where do I find my hurricane deductible?', a: 'On your declarations page. Florida law requires insurers to show it as a dollar amount, even if it is written as a percentage.' },
        { q: 'How long do I have to report hurricane damage?', a: 'Florida law generally requires notice of a property claim within 1 year of the date of loss, and a supplemental claim within 18 months. For a hurricane, the date of loss is the date it made landfall. Report as soon as you can.' },
      ],
      related: [
        { path: '/homeowners-insurance-florida-city', label: 'Home insurance in Florida City' },
        { path: '/homeowners-insurance-homestead-fl', label: 'Homeowners insurance in Homestead' },
        { path: '/homeowners-insurance-miami-dade-county-fl', label: 'Homeowners insurance in Miami-Dade County' },
        { path: '/condo-insurance-florida-city', label: 'Condo insurance' },
        { path: '/flood-insurance-homestead-fl', label: 'Flood insurance in Florida City and Homestead' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Deducible de huracán en Florida, explicado | M&K Agency',
      metaDesc: 'Cómo funciona el deducible de huracán (viento) en Florida: cuándo aplica, opciones de 2%, 5% o 10%, una vez por año, tormentas tropicales y qué revisar.',
      breadcrumb: 'Deducible de huracán en Florida',
      kicker: 'Guía de seguro de casa · Florida',
      h1a: 'Deducible de huracán (viento) en Florida:',
      h1b: 'lo que usted paga antes que su póliza.',
      answer: 'En Florida, el deducible de huracán se aplica a los daños por viento de una tormenta que el Centro Nacional de Huracanes ha declarado huracán, desde que se emite un aviso de huracán para cualquier parte de Florida hasta 72 horas después de que termine la última vigilancia o aviso. Muchas veces es el 2%, 5% o 10% del límite de la vivienda y, por lo general, se aplica una vez por año calendario.',
      serviceType: 'Seguro de casa',
      intro: [
        { type: 'h2', text: 'Para quién es esta página' },
        { type: 'ul', items: [
          '**Dueños de casa y de condominio** que revisan su renovación antes de la temporada de huracanes.',
          '**Compradores** que comparan opciones de deducible antes del cierre.',
          '**Cualquiera que acaba de descubrir** que su “deducible de viento” es un porcentaje y no una cantidad fija en dólares.',
        ] },
        { type: 'h2', text: 'Cómo funciona el deducible de huracán' },
        { type: 'ul', items: [
          '**Es un porcentaje del límite de la vivienda, no del daño.** Con un límite de vivienda de $300,000, un deducible de huracán del 2% son $6,000 y uno del 5% son $15,000. La ley de Florida exige que la cantidad en dólares aparezca en su página de declaraciones.',
          '**Opciones que las aseguradoras deben ofrecer.** Antes de emitir una póliza residencial personal, las aseguradoras deben ofrecer deducibles de huracán de $500 y del 2%, 5% y 10% del límite de la vivienda. Hay excepciones según el límite de la vivienda; por ejemplo, la opción de $500 no es obligatoria a partir de $250,000.',
          '**Más del 10% requiere pasos adicionales.** Para una casa con un valor menor de $500,000, un deducible de huracán de más del 10% exige una declaración escrita a mano y firmada por el asegurado. Si hay hipoteca, el prestamista debe aprobarlo por escrito.',
          '**Una vez por año calendario, con condiciones.** Si más de un huracán daña su casa en el mismo año calendario y usted está asegurado con la misma aseguradora o grupo asegurador, la tormenta posterior usa la cantidad mayor entre lo que queda de su deducible de huracán y su deducible regular. Su aseguradora puede pedirle que reporte pérdidas menores o que guarde recibos, así que documente cada pérdida por tormenta, aunque sea pequeña.',
          '**Las tormentas tropicales son distintas.** Los daños de una tormenta antes de que el Centro Nacional de Huracanes la declare huracán se rigen por su deducible regular de “todos los demás riesgos” (all other perils), no por el deducible de huracán.',
        ] },
      ],
      checklistTitle: 'Cuatro preguntas que le haremos',
      checklist: [
        '**¿Cuál es el límite de su vivienda y cuánto es su deducible de huracán en dólares?** Los dos aparecen en la página de declaraciones.',
        '**¿Cuánto dinero en efectivo podría pagar de verdad la semana después de una tormenta?** Esa cifra debería guiar su elección de deducible.',
        '**¿Tiene un informe de inspección de mitigación de viento?** La ley de Florida exige que las aseguradoras ofrezcan un deducible de huracán reducido o un crédito por las características de mitigación que califiquen. Cuál recibe, y de cuánto, depende de la aseguradora y de la inspección.',
        '**¿Tiene hipoteca y qué exige su prestamista?** Los prestamistas pueden limitar qué tan alto puede ser el deducible que elija.',
      ],
      body: [
        { type: 'h2', text: 'Lo que no está cubierto (límites claros)' },
        { type: 'ul', items: [
          '**La inundación no forma parte de la cobertura de huracán.** Los daños por marejada ciclónica y por subida del agua necesitan una póliza de inundación aparte, que tiene su propio deducible.',
          '**El deducible lo paga usted.** Ninguna póliza de casa le devuelve el deducible de huracán.',
          '**Existen deducibles de techo separados.** Algunas pólizas incluyen uno para reclamos de techo que no son por huracán, así que lea su página de declaraciones con atención.',
          '**El viento puede estar en una póliza aparte.** Algunas casas tienen la cobertura de viento en una póliza separada, como una póliza solo de viento de Citizens Property Insurance, con su propio deducible.',
        ] },
      ],
      officeTitle: 'Hable con un agente licenciado',
      office: [
        { type: 'p', text: 'Envíenos su página de declaraciones y le explicamos su deducible de huracán en dólares y las opciones que tiene al renovar. Llame al **(305) 859-3953**, o déjenos su número y lo contactamos en menos de una hora en horario de oficina.' },
        { type: 'p', text: 'Hablamos inglés, español y ruso. Las pólizas se emiten en inglés; se las explicamos en su idioma.' },
      ],
      faqTitle: 'Deducible de huracán en Florida: preguntas frecuentes',
      faq: [
        { q: '¿El deducible de huracán se aplica a las tormentas tropicales?', a: 'No. Solo se aplica a una tormenta que el Centro Nacional de Huracanes ha declarado huracán, durante el período que fija la ley de Florida. Los daños antes de esa declaración usan su deducible regular.' },
        { q: '¿El deducible de huracán es por tormenta o por año?', a: 'En las pólizas residenciales personales, por lo general se aplica una vez por año calendario, siempre que siga con la misma aseguradora o grupo asegurador. Un huracán posterior usa la cantidad mayor entre lo que queda de su deducible de huracán y su deducible regular.' },
        { q: '¿Puedo cambiar mi deducible de huracán en plena temporada de huracanes?', a: 'Normalmente los cambios se hacen al renovar, y las aseguradoras pueden restringir los cambios cuando amenaza una tormenta. Si quiere otro deducible, pregunte mucho antes del 1 de junio.' },
        { q: '¿Dónde encuentro mi deducible de huracán?', a: 'En su página de declaraciones. La ley de Florida exige que las aseguradoras lo muestren como una cantidad en dólares, aunque esté expresado como porcentaje.' },
        { q: '¿Cuánto tiempo tengo para reportar daños por huracán?', a: 'La ley de Florida por lo general exige avisar un reclamo de propiedad dentro de 1 año desde la fecha de la pérdida, y un reclamo suplementario dentro de 18 meses. En un huracán, la fecha de la pérdida es el día en que tocó tierra. Repórtelo lo antes posible.' },
      ],
      related: [
        { path: '/homeowners-insurance-florida-city', label: 'Seguro de casa en Florida City' },
        { path: '/homeowners-insurance-homestead-fl', label: 'Seguro de casa en Homestead' },
        { path: '/homeowners-insurance-miami-dade-county-fl', label: 'Seguro de casa en el Condado Miami-Dade' },
        { path: '/condo-insurance-florida-city', label: 'Seguro de condominio' },
        { path: '/flood-insurance-homestead-fl', label: 'Seguro de inundación en Florida City y Homestead' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Ураганная франшиза во Флориде | M&K Agency',
      metaDesc: 'Как работает ураганная (ветровая) франшиза во Флориде: когда применяется, варианты 2%, 5% и 10%, раз в календарный год, тропические штормы и что проверить.',
      breadcrumb: 'Ураганная франшиза во Флориде',
      kicker: 'Гид по страховке дома · Флорида',
      h1a: 'Ураганная (ветровая) франшиза во Флориде:',
      h1b: 'сколько вы платите до того, как заплатит полис.',
      answer: 'Во Флориде ураганная франшиза применяется к ущербу от ветра во время шторма, который Национальный центр ураганов объявил ураганом, — с момента объявления штормового предупреждения об урагане для любой части Флориды и до истечения 72 часов после отмены последнего штормового предупреждения или оповещения. Часто она составляет 2%, 5% или 10% от покрытия дома и, как правило, применяется раз в календарный год.',
      serviceType: 'Страхование дома',
      intro: [
        { type: 'h2', text: 'Для кого эта страница' },
        { type: 'ul', items: [
          '**Владельцы домов и кондо**, которые проверяют условия продления перед сезоном ураганов.',
          '**Покупатели**, которые сравнивают варианты франшизы до закрытия сделки.',
          '**Все, кто только что узнал**, что их «ветровая франшиза» — это процент, а не фиксированная сумма в долларах.',
        ] },
        { type: 'h2', text: 'Как работает ураганная франшиза' },
        { type: 'ul', items: [
          '**Это процент от покрытия дома, а не от суммы ущерба.** При покрытии дома $300,000 ураганная франшиза 2% — это $6,000, а 5% — $15,000. Закон Флориды требует, чтобы сумма в долларах была указана на декларационной странице полиса.',
          '**Варианты, которые страховая обязана предложить.** Прежде чем выдать личный полис на жильё, страховая обязана предложить ураганную франшизу $500, 2%, 5% и 10% от покрытия дома. Есть исключения в зависимости от покрытия: например, вариант $500 не обязателен при покрытии от $250,000.',
          '**Выше 10% — дополнительные шаги.** Для дома стоимостью менее $500,000 ураганная франшиза выше 10% требует написанного от руки и подписанного заявления владельца полиса. Если есть ипотека, кредитор должен одобрить это письменно.',
          '**Раз в календарный год — с условиями.** Если за один календарный год дом повредят несколько ураганов и вы застрахованы у той же страховой или в той же группе страховых, для следующего шторма применяется бо́льшая из двух сумм: остаток ураганной франшизы или обычная франшиза. Страховая может попросить сообщать и о небольших убытках или сохранять чеки, поэтому документируйте каждый ущерб от шторма, даже небольшой.',
          '**Тропические штормы — другое дело.** Ущерб от шторма до того, как Национальный центр ураганов объявит его ураганом, идёт по обычной франшизе «на все остальные риски» (all other perils), а не по ураганной.',
        ] },
      ],
      checklistTitle: 'Четыре вопроса, которые мы вам зададим',
      checklist: [
        '**Какое у вас покрытие дома и сколько составляет ураганная франшиза в долларах?** И то, и другое указано на декларационной странице.',
        '**Сколько наличных вы реально сможете заплатить через неделю после шторма?** От этой суммы и стоит отталкиваться при выборе франшизы.',
        '**Есть ли у вас отчёт об инспекции wind mitigation?** Закон Флориды обязывает страховые предлагать либо сниженную ураганную франшизу, либо кредит за подходящие элементы защиты от ветра. Что именно вы получите и в каком размере, зависит от страховой и от инспекции.',
        '**Есть ли у вас ипотека и что требует кредитор?** Кредитор может ограничить, насколько высокую франшизу вам можно выбрать.',
      ],
      body: [
        { type: 'h2', text: 'Что не покрывается (честно о границах)' },
        { type: 'ul', items: [
          '**Наводнение не входит в ураганное покрытие.** Для ущерба от нагонной волны и поднявшейся воды нужен отдельный полис от наводнения со своей франшизой.',
          '**Франшизу платите вы.** Ни один полис на дом не возвращает вам ураганную франшизу.',
          '**Бывают отдельные франшизы на крышу.** В некоторых полисах есть отдельная франшиза для клеймов по крыше, не связанных с ураганом, поэтому внимательно читайте декларационную страницу.',
          '**Ветер может быть в отдельном полисе.** У некоторых домов покрытие от ветра оформлено отдельным полисом, например полисом только от ветра (wind-only) в Citizens Property Insurance, со своей франшизой.',
        ] },
      ],
      officeTitle: 'Поговорите с лицензированным агентом',
      office: [
        { type: 'p', text: 'Пришлите нам декларационную страницу полиса — мы переведём вашу ураганную франшизу в доллары и объясним, какие варианты есть при продлении. Звоните **(305) 859-3953** или оставьте номер — мы свяжемся с вами в течение часа в рабочее время.' },
        { type: 'p', text: 'Мы говорим по-английски, по-испански и по-русски. Полисы выдаются на английском языке; мы объясняем их на вашем языке.' },
      ],
      faqTitle: 'Ураганная франшиза во Флориде: частые вопросы',
      faq: [
        { q: 'Применяется ли ураганная франшиза к тропическим штормам?', a: 'Нет. Она применяется только к шторму, который Национальный центр ураганов объявил ураганом, и только в период, установленный законом Флориды. Ущерб до этого объявления идёт по обычной франшизе.' },
        { q: 'Ураганная франшиза — за каждый шторм или за год?', a: 'Для личных полисов на жильё она, как правило, применяется раз в календарный год, если вы остаётесь у той же страховой или в той же группе страховых. Для следующего урагана применяется бо́льшая сумма: остаток ураганной франшизы или обычная франшиза.' },
        { q: 'Можно ли поменять ураганную франшизу в разгар сезона ураганов?', a: 'Обычно изменения вносят при продлении, а когда шторм уже угрожает, страховые могут ограничивать изменения. Если хотите другую франшизу, спросите задолго до 1 июня.' },
        { q: 'Где найти мою ураганную франшизу?', a: 'На декларационной странице полиса. Закон Флориды требует, чтобы страховые указывали её суммой в долларах, даже если она записана в процентах.' },
        { q: 'Сколько времени есть, чтобы заявить ущерб от урагана?', a: 'Закон Флориды, как правило, требует заявить клейм по имуществу в течение 1 года с даты ущерба, а дополнительный клейм — в течение 18 месяцев. При урагане дата ущерба — день его выхода на сушу. Заявляйте как можно скорее.' },
      ],
      related: [
        { path: '/homeowners-insurance-florida-city', label: 'Страховка дома во Florida City' },
        { path: '/homeowners-insurance-homestead-fl', label: 'Страховка дома в Homestead' },
        { path: '/homeowners-insurance-miami-dade-county-fl', label: 'Страховка дома в округе Miami-Dade' },
        { path: '/condo-insurance-florida-city', label: 'Страховка кондо' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
