import type { GuidePage } from './types';
import { sources } from './sources';

const SRC = ['deductibles', 'citizensFlood', 'floodsmart'] as const;

export const AGENT_HOMESTEAD: GuidePage = {
  path: '/insurance-agent-homestead',
  leadType: 'Home',
  heroImage: 'legacy-family-home',
  published: '2026-10-03',
  modified: '2026-10-03',
  areaServed: [{ '@type': 'City', name: 'Homestead, FL' }],
  copy: {
    en: {
      metaTitle: 'Insurance Agent for Homestead, FL | M&K Agency',
      metaDesc: 'Homestead insurance agent for home, condo, auto, life and small-business liability, from our Florida City office 1.5 miles south. EN, ES, RU.',
      breadcrumb: 'Insurance agent for Homestead',
      kicker: 'Insurance agent · Homestead, FL',
      h1a: 'Insurance agent for Homestead, FL,',
      h1b: 'five minutes down US-1.',
      answer: 'M&K Agency serves Homestead from our Florida City office at 33550 S Dixie Hwy, Suite 102, about 1.5 miles south of Homestead City Hall. Licensed agents help with home, condo, auto and life insurance and general liability for small businesses, and answer flood questions, in English, Spanish or Russian. Call (305) 859-3953, or leave your number and we’ll contact you within an hour during business hours.',
      serviceType: 'Insurance agency',
      intro: [
        { type: 'h2', text: 'Who this page is for' },
        { type: 'ul', items: [
          '**Homestead homeowners**, including people in houses rebuilt or built after Hurricane Andrew, who want someone to explain their hurricane deductible and roof questions.',
          '**Commuters** who drive the Turnpike or US-1 to Cutler Bay, Kendall or Miami every day.',
          '**Condo and townhome owners** who need to know where the association’s policy stops.',
          '**Small businesses and contractors** in Homestead and the Redland that need general liability coverage.',
          '**Renters** who want their belongings and liability covered.',
        ] },
        { type: 'p', text: 'We don’t have an office inside Homestead. Our Florida City office is just past the city line, usually around five minutes from downtown in light traffic.' },
      ],
      checklistTitle: 'Four questions we will ask you',
      checklist: [
        '**When was the home built, and how old is the roof?** Insurers ask about both, and the answers affect eligibility and terms. A wind mitigation inspection report can help document the home’s features.',
        '**What flood zone are you in, and do you have a flood policy?** A standard homeowners policy generally does not cover flood. If your home is insured with Citizens Property Insurance, flood coverage may be a condition of renewal.',
        '**Who drives, and how far?** Long daily commutes and teen drivers change what limits make sense, especially bodily injury and uninsured motorist coverage.',
        '**Do you run a business from home or use your truck for work?** Personal policies often exclude business activity unless the right coverage is added.',
      ],
      body: [
        { type: 'h2', text: 'What is not covered (honest limits)' },
        { type: 'ul', items: [
          '**Flood** is excluded from standard homeowners and condo policies. It needs a separate policy.',
          '**Hurricane deductibles** are paid out of pocket before the policy pays. They are often a percentage of the dwelling limit, so a 2% deductible on a $300,000 dwelling limit is $6,000.',
          '**Cars damaged by flood water or a falling tree** are covered only if the auto policy includes comprehensive coverage.',
          '**Everything is subject to underwriting.** We can’t promise that a specific insurer will accept a particular home, roof or driving record.',
        ] },
      ],
      officeTitle: 'Talk to a licensed agent',
      office: [
        { type: 'p', text: 'Call **(305) 859-3953**, or leave your number and we’ll contact you within an hour during business hours. Our office is at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, open Monday to Friday 9 to 6, with Saturdays by appointment. WhatsApp: (971) 998-7313.' },
        { type: 'p', text: 'We speak English, Spanish and Russian. Jose Chalela, Carolina Silva and Elena De Oña (home insurance) help in Spanish, and Mikhail (Mike) Kozlov helps in Russian. Policy documents are issued in English; we explain them in your language.' },
      ],
      faqTitle: 'Insurance agent for Homestead: FAQ',
      faq: [
        { q: 'Do you have an office in Homestead?', a: 'No. We serve Homestead from Florida City, about 1.5 miles south of Homestead City Hall on US-1. Most questions can also be handled by phone, WhatsApp, text or email.' },
        { q: 'My insurer sent a nonrenewal notice. Can you help?', a: 'Yes. Send us the notice and your current declarations page. We will look at what options may be available before your policy ends, subject to underwriting. If you end up with Citizens Property Insurance, we will explain its flood requirement.' },
        { q: 'Does homeowners insurance in Homestead cover flooding?', a: 'Generally, no. Flood is a separate policy. Ask us early, because flood policies often have a waiting period before coverage starts.' },
        { q: 'Can you handle my car and home at the same office?', a: 'Yes. One agency can look after your home, auto, condo and life policies and your business liability, so you have one place to call when something changes.' },
        { q: 'Do you help when I have a claim?', a: 'Yes. We help you report it, explain the next steps and follow up. The insurer adjusts the claim and decides coverage under your policy.' },
      ],
      related: [
        { path: '/car-insurance-homestead-fl', label: 'Car insurance in Homestead' },
        { path: '/homeowners-insurance-homestead-fl', label: 'Homeowners insurance in Homestead' },
        { path: '/flood-insurance-homestead-fl', label: 'Flood insurance in Florida City and Homestead' },
        { path: '/florida-home-insurance-wind-deductible', label: 'Florida hurricane deductible, explained' },
        { path: '/commercial-insurance-florida-city', label: 'Commercial insurance in Florida City' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Agente de seguros para Homestead, FL | M&K Agency',
      metaDesc: 'Agente de seguros para Homestead: casa, condominio, auto, vida y responsabilidad para pequeños negocios, desde Florida City, a 1.5 millas. EN, ES, RU.',
      breadcrumb: 'Agente de seguros para Homestead',
      kicker: 'Agente de seguros · Homestead, FL',
      h1a: 'Agente de seguros para Homestead, FL,',
      h1b: 'a cinco minutos por la US-1.',
      answer: 'M&K Agency atiende a Homestead desde nuestra oficina en Florida City, en 33550 S Dixie Hwy, Suite 102, a unas 1.5 millas al sur del ayuntamiento de Homestead. Nuestros agentes licenciados le ayudan con seguros de casa, condominio, auto y vida, y con responsabilidad civil general para pequeños negocios, y responden sus preguntas sobre inundación, en inglés, español o ruso. Llámenos al (305) 859-3953, o déjenos su número y lo contactamos en menos de una hora en horario de oficina.',
      serviceType: 'Agencia de seguros',
      intro: [
        { type: 'h2', text: 'Para quién es esta página' },
        { type: 'ul', items: [
          '**Dueños de casa en Homestead**, incluidas las casas reconstruidas o construidas después del huracán Andrew, que quieren que alguien les explique su deducible de huracán y las preguntas sobre el techo.',
          '**Quienes manejan a diario** por el Turnpike o la US-1 hacia Cutler Bay, Kendall o Miami.',
          '**Dueños de condominios y townhomes** que necesitan saber hasta dónde llega la póliza de la asociación.',
          '**Pequeños negocios y contratistas** de Homestead y la Redland que necesitan responsabilidad civil general.',
          '**Inquilinos** que quieren cubrir sus pertenencias y su responsabilidad.',
        ] },
        { type: 'p', text: 'No tenemos oficina dentro de Homestead. Nuestra oficina de Florida City está justo pasando el límite de la ciudad, normalmente a unos cinco minutos del centro con poco tráfico.' },
      ],
      checklistTitle: 'Cuatro preguntas que le haremos',
      checklist: [
        '**¿Cuándo se construyó la casa y qué edad tiene el techo?** Las aseguradoras preguntan por ambas cosas, y las respuestas influyen en la elegibilidad y en las condiciones. Un informe de inspección de mitigación de viento puede ayudar a documentar las características de la casa.',
        '**¿En qué zona de inundación está y tiene póliza de inundación?** Una póliza de casa estándar por lo general no cubre inundaciones. Si su casa está asegurada con Citizens Property Insurance, el seguro de inundación puede ser una condición para renovar.',
        '**¿Quién maneja y cuánto?** Los viajes largos de cada día y los conductores adolescentes cambian qué límites tienen sentido, sobre todo en responsabilidad por lesiones (BI) y conductor sin seguro (UM).',
        '**¿Tiene un negocio en casa o usa su camioneta para trabajar?** Las pólizas personales muchas veces excluyen la actividad comercial si no se agrega la cobertura correcta.',
      ],
      body: [
        { type: 'h2', text: 'Lo que no está cubierto (límites claros)' },
        { type: 'ul', items: [
          '**La inundación** está excluida de las pólizas estándar de casa y de condominio. Necesita una póliza aparte.',
          '**El deducible de huracán** lo paga usted antes de que pague la póliza. Muchas veces es un porcentaje del límite de la vivienda: un deducible del 2% sobre un límite de vivienda de $300,000 son $6,000.',
          '**Los carros dañados por agua de inundación o por un árbol caído** solo están cubiertos si la póliza de auto incluye cobertura integral.',
          '**Todo está sujeto a suscripción (underwriting).** No podemos prometer que una aseguradora determinada acepte una casa, un techo o un historial de manejo en particular.',
        ] },
      ],
      officeTitle: 'Hable con un agente licenciado',
      office: [
        { type: 'p', text: 'Llame al **(305) 859-3953**, o déjenos su número y lo contactamos en menos de una hora en horario de oficina. Nuestra oficina está en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, abierta de lunes a viernes de 9 a 6, y los sábados con cita. WhatsApp: (971) 998-7313.' },
        { type: 'p', text: 'Hablamos inglés, español y ruso. Jose Chalela, Carolina Silva y Elena De Oña (seguros de casa) le atienden en español, y Mikhail (Mike) Kozlov en ruso. Las pólizas se emiten en inglés; se las explicamos en su idioma.' },
      ],
      faqTitle: 'Agente de seguros para Homestead: preguntas frecuentes',
      faq: [
        { q: '¿Tienen oficina en Homestead?', a: 'No. Atendemos a Homestead desde Florida City, a unas 1.5 millas al sur del ayuntamiento de Homestead por la US-1. La mayoría de las consultas también se pueden resolver por teléfono, WhatsApp, mensaje de texto o correo.' },
        { q: 'Mi aseguradora me envió un aviso de no renovación. ¿Me pueden ayudar?', a: 'Sí. Envíenos el aviso y su página de declaraciones actual. Veremos qué opciones puede haber antes de que termine su póliza, sujeto a suscripción. Si termina con Citizens Property Insurance, le explicaremos su requisito de inundación.' },
        { q: '¿El seguro de casa en Homestead cubre inundaciones?', a: 'Por lo general, no. La inundación es una póliza aparte. Pregúntenos con tiempo, porque las pólizas de inundación muchas veces tienen un período de espera antes de que empiece la cobertura.' },
        { q: '¿Pueden encargarse de mi carro y de mi casa en la misma oficina?', a: 'Sí. Una sola agencia puede atender sus pólizas de casa, auto, condominio y vida, y la responsabilidad de su negocio, para que tenga un solo lugar al que llamar cuando algo cambie.' },
        { q: '¿Me ayudan cuando tengo un reclamo?', a: 'Sí. Le ayudamos a reportarlo, le explicamos los próximos pasos y damos seguimiento. La aseguradora ajusta el reclamo y decide la cobertura según su póliza.' },
      ],
      related: [
        { path: '/car-insurance-homestead-fl', label: 'Seguro de auto en Homestead' },
        { path: '/homeowners-insurance-homestead-fl', label: 'Seguro de casa en Homestead' },
        { path: '/flood-insurance-homestead-fl', label: 'Seguro de inundación en Florida City y Homestead' },
        { path: '/florida-home-insurance-wind-deductible', label: 'El deducible de huracán en Florida, explicado' },
        { path: '/commercial-insurance-florida-city', label: 'Seguro comercial en Florida City' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Страховой агент для Homestead, FL | M&K Agency',
      metaDesc: 'Страховой агент для Homestead: дом, кондо, авто, жизнь и ответственность малого бизнеса. Офис во Florida City в 1.5 милях к югу. EN, ES, RU.',
      breadcrumb: 'Страховой агент для Homestead',
      kicker: 'Страховой агент · Homestead, FL',
      h1a: 'Страховой агент для Homestead, FL —',
      h1b: 'в пяти минутах по US-1.',
      answer: 'M&K Agency обслуживает Homestead из офиса во Florida City по адресу 33550 S Dixie Hwy, Suite 102, примерно в 1.5 милях к югу от мэрии Homestead. Лицензированные агенты помогут со страховкой дома, кондо, машины и жизни, со страхованием общей ответственности (general liability) для малого бизнеса и ответят на вопросы о наводнении — по-английски, по-испански или по-русски. Позвоните нам по номеру (305) 859-3953 или оставьте номер — мы свяжемся с вами в течение часа в рабочее время.',
      serviceType: 'Страховое агентство',
      intro: [
        { type: 'h2', text: 'Для кого эта страница' },
        { type: 'ul', items: [
          '**Владельцы домов в Homestead**, в том числе домов, отстроенных заново или построенных после урагана Andrew, которым нужен человек, способный объяснить ураганную франшизу и вопросы о крыше.',
          '**Те, кто каждый день ездит** по Turnpike или US-1 в Cutler Bay, Kendall или Miami.',
          '**Владельцы кондо и таунхаусов**, которым нужно понять, где заканчивается полис ассоциации.',
          '**Малый бизнес и подрядчики** в Homestead и Redland, которым нужно страхование общей ответственности.',
          '**Арендаторы**, которые хотят застраховать свои вещи и свою ответственность.',
        ] },
        { type: 'p', text: 'Офиса в самом Homestead у нас нет. Наш офис во Florida City — сразу за границей города, обычно примерно в пяти минутах от центра, если нет пробок.' },
      ],
      checklistTitle: 'Четыре вопроса, которые мы вам зададим',
      checklist: [
        '**Когда построен дом и сколько лет крыше?** Страховые спрашивают и о том, и о другом, и ответы влияют на то, примут ли дом и на каких условиях. Отчёт об инспекции wind mitigation помогает подтвердить характеристики дома.',
        '**В какой зоне затопления вы находитесь и есть ли у вас полис от наводнения?** Обычный полис на дом, как правило, не покрывает наводнение. Если дом застрахован в Citizens Property Insurance, страховка от наводнения может быть условием продления.',
        '**Кто водит и сколько ездит?** Долгая дорога каждый день и водители-подростки меняют то, какие лимиты разумны, особенно по bodily injury и по покрытию от незастрахованных водителей (UM).',
        '**Вы ведёте бизнес из дома или используете машину для работы?** Личные полисы часто исключают коммерческую деятельность, если не добавить нужное покрытие.',
      ],
      body: [
        { type: 'h2', text: 'Что не покрывается (честно о границах)' },
        { type: 'ul', items: [
          '**Наводнение** исключено из обычных полисов на дом и кондо. Для него нужен отдельный полис.',
          '**Ураганную франшизу** вы платите сами, прежде чем начнёт платить полис. Часто это процент от покрытия дома: франшиза 2% при покрытии дома $300,000 — это $6,000.',
          '**Машины, повреждённые водой при наводнении или упавшим деревом**, покрываются, только если в автополисе есть comprehensive.',
          '**Всё зависит от андеррайтинга.** Мы не можем обещать, что конкретная страховая примет определённый дом, крышу или водительскую историю.',
        ] },
      ],
      officeTitle: 'Поговорите с лицензированным агентом',
      office: [
        { type: 'p', text: 'Звоните **(305) 859-3953** или оставьте номер — мы свяжемся с вами в течение часа в рабочее время. Наш офис: **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, с понедельника по пятницу с 9 до 6, в субботу — по записи. WhatsApp: (971) 998-7313.' },
        { type: 'p', text: 'Мы говорим по-английски, по-испански и по-русски. По-испански вам помогут Jose Chalela, Carolina Silva и Elena De Oña (страховка дома), по-русски — Михаил (Майк) Козлов. Полисы выдаются на английском языке; мы объясняем их на вашем языке.' },
      ],
      faqTitle: 'Страховой агент для Homestead: частые вопросы',
      faq: [
        { q: 'У вас есть офис в Homestead?', a: 'Нет. Мы обслуживаем Homestead из Florida City, примерно в 1.5 милях к югу от мэрии Homestead по US-1. Большинство вопросов можно решить и по телефону, в WhatsApp, по SMS или по почте.' },
        { q: 'Страховая прислала уведомление, что не продлит полис. Вы поможете?', a: 'Да. Пришлите нам уведомление и текущую декларационную страницу полиса (declarations page). Мы посмотрим, какие варианты могут быть до окончания полиса, при условии андеррайтинга. Если в итоге вы окажетесь в Citizens Property Insurance, мы объясним её требование о страховке от наводнения.' },
        { q: 'Покрывает ли страховка дома в Homestead наводнение?', a: 'Как правило, нет. Наводнение страхуется отдельным полисом. Спросите нас заранее: у полисов от наводнения часто есть период ожидания, прежде чем начнёт действовать покрытие.' },
        { q: 'Можно оформить машину и дом в одном офисе?', a: 'Да. Одно агентство может вести ваши полисы на дом, машину, кондо и жизнь, а также ответственность вашего бизнеса — так у вас одно место, куда звонить, когда что-то меняется.' },
        { q: 'Вы помогаете, если случился страховой случай?', a: 'Да. Мы поможем заявить клейм, объясним следующие шаги и будем следить за ходом дела. Клейм урегулирует страховая, и она же решает вопрос о покрытии по вашему полису.' },
      ],
      related: [
        { path: '/car-insurance-homestead-fl', label: 'Автостраховка в Homestead' },
        { path: '/homeowners-insurance-homestead-fl', label: 'Страховка дома в Homestead' },
        { path: '/florida-home-insurance-wind-deductible', label: 'Ураганная франшиза во Флориде: как она работает' },
        { path: '/commercial-insurance-florida-city', label: 'Страхование бизнеса во Florida City' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
