import type { CityPage } from './types';
import { sources } from './sources';

// /[lang]/car-insurance-cutler-bay-fl. Local facts checked 2026-10-03 (see sources).
const SRC = ['flhsmv', 'pip', 'pip2026', 'um', 'iiiUm', 'hb837', 'turnpike', 'metroExpress', 'mdSurge', 'acsCutlerBay', 'cutlerBayTown'] as const;

export const CAR_CUTLER_BAY: CityPage = {
  path: '/car-insurance-cutler-bay-fl',
  line: 'auto',
  kind: 'city',
  area: 'cutler-bay',
  parent: '/car-insurance-miami-dade-county-fl',
  heroImage: 'auto-06',
  published: '2026-10-03',
  modified: '2026-10-03',
  areaServed: [
    { '@type': 'City', name: 'Cutler Bay, FL' },
    { '@type': 'AdministrativeArea', name: 'Miami-Dade County, FL' },
  ],
  copy: {
    en: {
      metaTitle: 'Car Insurance in Cutler Bay, FL | Local Agent | M&K Agency',
      metaDesc: 'Car insurance for Cutler Bay families: Turnpike and US-1 commutes, teen drivers, stacked uninsured motorist coverage and a free review of your current policy.',
      breadcrumb: 'Cutler Bay',
      kicker: 'Auto insurance · Cutler Bay, FL',
      h1a: 'Car insurance in Cutler Bay, FL,',
      h1b: 'for families with more than one car.',
      sub: 'Turnpike or US-1, school runs, a teenager about to get a license. We review the whole household policy, explain what is missing and stay with you if you ever have a claim. English, Spanish or Russian.',
      serviceType: 'Auto insurance',
      intro: [
        { type: 'h2', text: 'Cutler Bay is a commuter town' },
        { type: 'p', text: 'Cutler Bay, the former Cutler Ridge, became a town on November 9, 2005. It sits between US-1 and Biscayne Bay in South Miami-Dade, and it is mostly a place where families live and drive somewhere else to work. Census data for 2020–2024 shows Cutler Bay residents spend about 38 minutes getting to work, among the longest average commutes in the county, and nearly four in ten spend 45 minutes or more each way. Around 70% of homes are owner-occupied, which usually means several cars and several drivers under one roof.' },
        { type: 'p', text: 'Most of those trips start with one choice: **the Turnpike or US-1**. The Homestead Extension of Florida’s Turnpike (SR 821) runs along the town’s west side, with exits at SW 216th Street (Cutler Ridge Boulevard) and at Caribbean Boulevard/US-1, and it is the fast way north to Kendall, the Don Shula Expressway (SR 874) and Miami. **US-1 (South Dixie Highway)** is the toll-free alternative, with traffic lights every few blocks and the busy commercial strip around Southland Mall. Along US-1 you also share the corridor with the South Dade TransitWay, where Miami-Dade’s Metro Express buses have run since October 27, 2025 with gate arms and signal priority at intersections. **Old Cutler Road**, on the bay side, is the scenic route through neighborhoods and school zones.' },
        { type: 'p', text: 'Short local trips add up too: school drop-off, the mall parking lots, practice at the park. Most claims we help with are not dramatic highway crashes. They are low-speed collisions, a parked car that gets hit, or a driver who leaves without exchanging information.' },
      ],
      checklistTitle: 'Coverage gaps we check on Cutler Bay family policies',
      checklist: [
        '**A new or teen driver** added correctly before they drive alone, not after the first ticket.',
        '**Bodily injury limits that match what your family owns:** a house, savings and future wages are what is at stake if you injure someone.',
        '**Stacked uninsured motorist coverage** with two or more cars, so each car’s UM limit can apply to an injured family member.',
        '**A signed UM rejection or lower-limits form** you may have forgotten about. If you have one on file, your UM is lower than your BI or gone.',
        '**Collision coverage** on any car you could not afford to replace out of pocket.',
        '**Comprehensive** for storm surge, street flooding, fallen trees and theft.',
        '**Rental reimbursement**, so one car in the shop does not leave a two-commuter household with no ride to work.',
        '**Medical payments coverage**, which can help with the 20% of medical bills PIP does not pay.',
        '**Garaging address and annual mileage** that reflect how each car is really used.',
      ],
      body: [
        { type: 'h2', text: 'Florida’s minimums, explained plainly' },
        { type: 'p', text: 'Every registered car in Florida must carry **$10,000 of Personal Injury Protection** and **$10,000 of Property Damage Liability**, continuously. PIP is no-fault: it pays 80% of reasonable medical expenses and 60% of lost gross income for you and the relatives who live with you, whoever caused the crash. To use it, you need to see a doctor within 14 days, and without a finding of an emergency medical condition the benefit is limited to $2,500. Bills to repeal PIP were filed again in the 2026 session and did not pass, so these rules still apply.' },
        { type: 'p', text: 'Bodily injury liability is not required for most Florida drivers. That is why the uninsured motorist rules matter so much. Under Florida law, any policy with BI must offer UM at the same limits, you can only reject it or lower it in writing on an approved form, and your insurer has to remind you of the option each year. UM also applies when the at-fault driver is **underinsured**, or when their insurer becomes insolvent. If you choose non-stacked UM, the law requires it to cost at least 20% less than stacked, which tells you how much protection you give up.' },
        { type: 'p', text: 'The Insurance Research Council estimated that roughly 20.6% of Florida drivers had no insurance in 2023. Combine that with Florida’s 2023 tort changes, where a person found more than 50% at fault generally recovers nothing from the other side, and your own coverage often ends up being the coverage that pays.' },
        { type: 'h2', text: 'Storm surge and your cars' },
        { type: 'p', text: 'Land east of the old Cutler Ridge is lower and close to Biscayne Bay, and much of Cutler Bay falls inside Miami-Dade’s storm surge planning zones. When an evacuation is ordered, you cannot take every car with you. Comprehensive is the only auto coverage that pays for salt-water damage, and it has to be in place before a storm is named.' },
        { type: 'h2', text: 'A personal agent, not a call center' },
        { type: 'p', text: 'M&K Agency is family-owned, with a team of 12 and more than 5,000 clients across Florida. **Send us your policy and we’ll check your coverage**: we will lay out each driver and car, show what is missing and explain the options. When you need to file a claim, you call us and we help you through it.' },
      ],
      officeTitle: 'From Cutler Bay to our Florida City office',
      office: [
        { type: 'p', text: 'We do not have an office in Cutler Bay. We serve Cutler Bay from our office at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**. From Cutler Bay Town Hall it is about 12.5 miles, roughly 20 minutes in light traffic on the Turnpike to its last exit at US-1; staying on US-1 avoids the tolls but takes longer. Most families never need to come in: we work by phone, WhatsApp, text and email.' },
        { type: 'p', text: 'Office hours are Monday to Friday, 9 to 6, and Saturday by appointment. Call (305) 859-3953 or WhatsApp (971) 998-7313. Leave a request during business hours and an agent will call you back within an hour.' },
      ],
      faqTitle: 'Car insurance in Cutler Bay: common questions',
      faq: [
        { q: 'When should I add my teenager to my car insurance?', a: 'Tell your agent when your teen gets a learner’s permit and add them before they drive on their own. A licensed driver living in the home who is left off the policy can cause problems when a claim is filed.' },
        { q: 'What is stacked uninsured motorist coverage?', a: 'With stacked UM, the UM limits for each car on the policy can be combined for an injured household member. Non-stacked UM limits you to the limit on one car. Florida requires non-stacked UM to cost at least 20% less, so the price difference shows what you give up.' },
        { q: 'Is bodily injury liability required in Cutler Bay?', a: 'Not for most drivers. Florida requires PIP and property damage liability. BI usually becomes mandatory only after certain crashes or violations. Without BI you cannot carry uninsured motorist coverage, and your own assets are exposed if you injure someone.' },
        { q: 'Will my car insurance pay if storm surge floods my car?', a: 'Only with comprehensive coverage. Insurers usually stop changing policies once a storm threatens, so add comprehensive before hurricane season if your car is not covered.' },
        { q: 'Do I have to come to the office?', a: 'No. Most Cutler Bay clients work with us by phone, WhatsApp, text or email. You are always welcome at our Florida City office, about 20 minutes away by Turnpike in light traffic.' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Seguro de Auto en Cutler Bay, FL | Agente Local | M&K Agency',
      metaDesc: 'Seguro de auto para familias de Cutler Bay: Turnpike y US-1, conductores jóvenes, cobertura de conductor sin seguro acumulable y revisión gratis de su póliza.',
      breadcrumb: 'Cutler Bay',
      kicker: 'Seguro de auto · Cutler Bay, FL',
      h1a: 'Seguro de auto en Cutler Bay, FL,',
      h1b: 'para familias con más de un carro.',
      sub: 'Turnpike o US-1, llevar a los niños a la escuela, un hijo que está por sacar la licencia. Revisamos la póliza de toda la familia, le explicamos lo que falta y le acompañamos si un día tiene un reclamo. En español, inglés o ruso.',
      serviceType: 'Seguro de auto',
      intro: [
        { type: 'h2', text: 'En Cutler Bay se vive aquí y se trabaja lejos' },
        { type: 'p', text: 'Cutler Bay, el antiguo Cutler Ridge, se convirtió en municipio el 9 de noviembre de 2005. Queda entre la US-1 y la bahía de Biscayne, en el sur de Miami-Dade, y es sobre todo un lugar donde las familias viven y salen a trabajar a otro lado. Según el Censo de 2020 a 2024, los residentes tardan unos 38 minutos en llegar al trabajo, uno de los promedios más altos del condado, y casi cuatro de cada diez pasan 45 minutos o más en cada viaje. Cerca del 70% de las viviendas las ocupan sus dueños, lo que normalmente significa varios carros y varios conductores en la misma casa.' },
        { type: 'p', text: 'Casi todos esos viajes empiezan con la misma decisión: **¿Turnpike o US-1?** La Extensión Homestead del Turnpike (SR 821) bordea el oeste del pueblo, con salidas en la SW 216 Street (Cutler Ridge Boulevard) y en Caribbean Boulevard/US-1, y es la vía rápida hacia Kendall, la Don Shula Expressway (SR 874) y Miami. La **US-1 (South Dixie Highway)** es la opción sin peaje, con semáforos cada pocas cuadras y el tramo comercial alrededor de Southland Mall. Al lado de la US-1 corre el South Dade TransitWay, por donde pasa el Metro Express de Miami-Dade desde el 27 de octubre de 2025, con barreras y prioridad en los semáforos. Por el lado de la bahía, **Old Cutler Road** atraviesa vecindarios y zonas escolares.' },
        { type: 'p', text: 'Los viajes cortos también cuentan: la escuela, los estacionamientos del mall, la práctica en el parque. La mayoría de los reclamos con los que ayudamos no son choques espectaculares en la autopista, sino golpes a poca velocidad, un carro estacionado que alguien choca o un conductor que se va sin dar sus datos.' },
      ],
      checklistTitle: 'Lo que revisamos en las pólizas de las familias de Cutler Bay',
      checklist: [
        '**Un conductor nuevo o adolescente** agregado bien, antes de que maneje solo y no después de la primera multa.',
        '**Límites de lesiones (BI) acordes con lo que tiene su familia:** la casa, los ahorros y el sueldo futuro están en juego si usted lesiona a alguien.',
        '**Conductor sin seguro acumulable (stacked UM)** si tiene dos carros o más, para que el límite de cada carro pueda proteger a un familiar lesionado.',
        '**Un formulario firmado de rechazo o de límites más bajos de UM** del que quizá ya no se acuerda. Si existe, su UM es menor que su BI o no tiene.',
        '**Cobertura de choque (collision)** en cualquier carro que no podría reponer de su bolsillo.',
        '**Cobertura integral (comprehensive)** para marejada, calles inundadas, árboles caídos y robo.',
        '**Carro de alquiler**, para que un carro en el taller no deje sin transporte a una casa con dos personas que trabajan lejos.',
        '**Pagos médicos (MedPay)**, que pueden ayudar con el 20% de las facturas que el PIP no paga.',
        '**Dirección y millaje anual** que correspondan a cómo se usa realmente cada carro.',
      ],
      body: [
        { type: 'h2', text: 'Los mínimos de Florida, sin rodeos' },
        { type: 'p', text: 'Todo carro registrado en Florida debe tener **$10,000 de Protección contra Lesiones Personales (PIP)** y **$10,000 de Responsabilidad por Daños a la Propiedad (PDL)**, sin interrupciones. El PIP es “sin culpa”: paga el 80% de los gastos médicos razonables y el 60% del ingreso bruto perdido para usted y los familiares que viven con usted, sin importar quién causó el accidente. Para usarlo hay que ver a un médico dentro de los 14 días, y si no se determina una condición médica de emergencia, el beneficio se limita a $2,500. En la sesión legislativa de 2026 se volvió a proponer eliminar el PIP y no se aprobó, así que estas reglas siguen vigentes.' },
        { type: 'p', text: 'La responsabilidad por lesiones corporales (BI) no es obligatoria para la mayoría de los conductores en Florida, y por eso las reglas de la cobertura de conductor sin seguro (UM) importan tanto. Según la ley, toda póliza con BI debe ofrecer UM con los mismos límites; solo se puede rechazar o bajar por escrito en un formulario aprobado, y la aseguradora debe recordarle la opción cada año. La UM también responde cuando el culpable tiene **poco seguro** o cuando su aseguradora quiebra. Si elige UM no acumulable, la ley exige que cueste al menos un 20% menos que la acumulable, lo que da una idea de cuánta protección se pierde.' },
        { type: 'p', text: 'El Insurance Research Council estimó que en 2023 cerca del 20.6% de los conductores de Florida no tenía seguro. Si a eso se suma la reforma de 2023, según la cual quien tiene más del 50% de la culpa en general no cobra nada a la otra parte, muchas veces la póliza que termina pagando es la suya.' },
        { type: 'h2', text: 'Marejada ciclónica y sus carros' },
        { type: 'p', text: 'El terreno al este del antiguo Cutler Ridge es más bajo y está pegado a la bahía, y buena parte de Cutler Bay está dentro de las zonas de planificación por marejada de Miami-Dade. Cuando hay orden de evacuación no siempre se pueden llevar todos los carros. La cobertura integral es la única que paga los daños por agua salada, y hay que tenerla antes de que la tormenta tenga nombre.' },
        { type: 'h2', text: 'Un agente que usted conoce, no un call center' },
        { type: 'p', text: 'M&K Agency es una agencia familiar con un equipo de 12 personas y más de 5,000 clientes en Florida. **Envíenos su póliza y la revisamos**: repasamos cada conductor y cada carro, le mostramos lo que falta y le explicamos las opciones. Cuando necesite hacer un reclamo, nos llama a nosotros y le ayudamos en todo el proceso.' },
      ],
      officeTitle: 'De Cutler Bay a nuestra oficina en Florida City',
      office: [
        { type: 'p', text: 'No tenemos oficina en Cutler Bay. Atendemos a Cutler Bay desde nuestra oficina en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**. Desde la Alcaldía de Cutler Bay son unas 12.5 millas, alrededor de 20 minutos sin tráfico por el Turnpike hasta su última salida en la US-1; por la US-1 se evita el peaje, pero se tarda más. La mayoría de las familias nunca necesita venir: trabajamos por teléfono, WhatsApp, mensaje de texto y correo.' },
        { type: 'p', text: 'Horario: lunes a viernes de 9 a 6, sábados con cita. Llame al (305) 859-3953 o escriba por WhatsApp al (971) 998-7313. Si nos deja una solicitud en horario de oficina, un agente le llama en menos de una hora.' },
      ],
      faqTitle: 'Seguro de auto en Cutler Bay: preguntas frecuentes',
      faq: [
        { q: '¿Cuándo debo agregar a mi hijo adolescente a la póliza?', a: 'Avísele a su agente cuando su hijo saque el permiso de aprendiz y agréguelo antes de que maneje solo. Un conductor con licencia que vive en la casa y no aparece en la póliza puede complicar un reclamo.' },
        { q: '¿Qué es la cobertura de conductor sin seguro acumulable?', a: 'Con la UM acumulable (stacked), los límites de UM de cada carro de la póliza se pueden sumar para un familiar lesionado. Con la no acumulable, solo cuenta el límite de un carro. En Florida, la no acumulable debe costar al menos un 20% menos, y esa diferencia muestra lo que se deja de tener.' },
        { q: '¿Es obligatoria la responsabilidad por lesiones (BI) en Cutler Bay?', a: 'Para la mayoría, no. Florida exige PIP y daños a la propiedad. La BI normalmente solo se vuelve obligatoria después de ciertos accidentes o infracciones. Sin BI no se puede tener cobertura de conductor sin seguro, y su patrimonio queda expuesto si lesiona a alguien.' },
        { q: '¿Mi seguro paga si la marejada inunda mi carro?', a: 'Solo si tiene cobertura integral (comprehensive). Las aseguradoras suelen dejar de hacer cambios cuando una tormenta amenaza la zona, así que agréguela antes de la temporada de huracanes.' },
        { q: '¿Tengo que ir a la oficina?', a: 'No. La mayoría de nuestros clientes de Cutler Bay trabaja con nosotros por teléfono, WhatsApp, texto o correo. Siempre puede visitarnos en Florida City, a unos 20 minutos por el Turnpike sin tráfico.' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Автостраховка в Cutler Bay, FL | Местный агент | M&K Agency',
      metaDesc: 'Автостраховка для семей из Cutler Bay: поездки по Turnpike и US-1, молодые водители, stacked UM и бесплатная проверка вашего нынешнего полиса.',
      breadcrumb: 'Cutler Bay',
      kicker: 'Автостраховка · Cutler Bay, FL',
      h1a: 'Автостраховка в Cutler Bay, FL —',
      h1b: 'для семей, где машин больше одной.',
      sub: 'Turnpike или US-1, школа, подросток, который вот-вот получит права. Проверим полис всей семьи, объясним, чего не хватает, и будем рядом, если понадобится клейм. По-русски, по-английски или по-испански.',
      serviceType: 'Автострахование',
      intro: [
        { type: 'h2', text: 'Cutler Bay: живут здесь, работают в другом месте' },
        { type: 'p', text: 'Cutler Bay, бывший Cutler Ridge, получил статус города 9 ноября 2005 года. Он лежит между US-1 и заливом Biscayne на юге Miami-Dade, и для большинства семей это место, где живут, а не работают. По данным переписи за 2020–2024 годы, дорога на работу у жителей занимает в среднем около 38 минут — один из самых высоких показателей в округе, — и почти четыре из десяти тратят 45 минут и больше в одну сторону. Около 70% жилья занимают сами владельцы, а это обычно несколько машин и несколько водителей в одном доме.' },
        { type: 'p', text: 'Почти каждая поездка начинается с выбора: **Turnpike или US-1**. Homestead Extension платной магистрали Turnpike (SR 821) идёт вдоль западной стороны города, со съездами на SW 216th Street (Cutler Ridge Boulevard) и на Caribbean Boulevard/US-1, — это быстрый путь на север, к Kendall, Don Shula Expressway (SR 874) и в Майами. **US-1 (South Dixie Highway)** — бесплатная альтернатива: светофоры через каждые несколько кварталов и оживлённый торговый участок у Southland Mall. Рядом с US-1 проходит South Dade TransitWay, где с 27 октября 2025 года ходят автобусы Metro Express — со шлагбаумами и приоритетом на светофорах. Со стороны залива **Old Cutler Road** ведёт через жилые кварталы и школьные зоны.' },
        { type: 'p', text: 'Короткие поездки тоже считаются: школа, парковки у торгового центра, тренировки в парке. Большинство клеймов, с которыми мы помогаем, — это не громкие аварии на шоссе, а столкновения на малой скорости, удар по припаркованной машине или водитель, который уехал, не оставив данных.' },
      ],
      checklistTitle: 'Что мы проверяем в семейных полисах Cutler Bay',
      checklist: [
        '**Новый или молодой водитель** вписан правильно — до того, как сядет за руль один, а не после первого штрафа.',
        '**Лимиты bodily injury (BI) соответствуют тому, что есть у семьи:** если вы кого-то травмируете, под угрозой дом, сбережения и будущая зарплата.',
        '**Stacked UM** при двух машинах и больше: тогда лимит UM каждой машины может работать на пострадавшего члена семьи.',
        '**Подписанный отказ от UM или форма с пониженными лимитами**, о которой вы могли забыть. Если такая есть, UM у вас меньше BI или её нет совсем.',
        '**Collision** на любую машину, которую вы не сможете заменить за свой счёт.',
        '**Comprehensive** — на случай нагонной волны, затопленных улиц, упавших деревьев и угона.',
        '**Аренда машины на время ремонта**, чтобы семья, где оба ездят далеко на работу, не осталась без транспорта.',
        '**Medical payments (MedPay)** — помогает с теми 20% медицинских счетов, которые не оплачивает PIP.',
        '**Адрес стоянки и годовой пробег** соответствуют тому, как на самом деле используется каждая машина.',
      ],
      body: [
        { type: 'h2', text: 'Минимум по закону Флориды — простыми словами' },
        { type: 'p', text: 'Каждая зарегистрированная во Флориде машина должна иметь **$10,000 PIP** и **$10,000 PDL** без перерывов. PIP работает по принципу no-fault: оплачивает 80% разумных медицинских расходов и 60% потерянного дохода (до налогов) вам и родственникам, которые живут с вами, независимо от того, кто виноват в аварии. Чтобы им воспользоваться, к врачу нужно обратиться в течение 14 дней, а без заключения о состоянии, требующем неотложной помощи, выплата ограничена $2,500. В сессии 2026 года законопроекты об отмене PIP снова внесли, но они не прошли, так что эти правила действуют.' },
        { type: 'p', text: 'Bodily injury liability для большинства водителей Флориды не обязательна, и именно поэтому так важны правила об UM. По закону любой полис с BI должен включать предложение UM с теми же лимитами; отказаться или уменьшить лимиты можно только письменно, на утверждённой форме, а страховая обязана ежегодно напоминать вам об этой опции. UM срабатывает и тогда, когда у виновника **слишком маленькая страховка**, и когда его страховая обанкротилась. Если выбрать non-stacked UM, закон требует, чтобы она стоила минимум на 20% меньше, чем stacked, — по этой разнице видно, сколько защиты вы теряете.' },
        { type: 'p', text: 'По оценке Insurance Research Council, в 2023 году около 20.6% водителей Флориды ездили без страховки. Добавьте к этому реформу 2023 года, по которой тот, кто виноват больше чем на 50%, как правило, ничего не получает с другой стороны, — и часто оказывается, что платить будет именно ваш полис.' },
        { type: 'h2', text: 'Нагонная волна и ваши машины' },
        { type: 'p', text: 'Земля к востоку от старого хребта Cutler Ridge ниже и ближе к заливу, и большая часть Cutler Bay входит в зоны планирования на случай нагонной волны (storm surge) округа Miami-Dade. При эвакуации не всегда получается увезти все машины. За ущерб от солёной воды платит только comprehensive, и оформить её нужно до того, как у шторма появится имя.' },
        { type: 'h2', text: 'Личный агент, а не колл-центр' },
        { type: 'p', text: 'M&K Agency — семейное агентство: 12 человек в команде и более 5,000 клиентов по всей Флориде. **Пришлите нам свой полис — мы проверим покрытие**: разберём каждого водителя и каждую машину, покажем, чего не хватает, и объясним варианты. А когда нужно подать клейм, вы звоните нам, и мы ведём вас до конца.' },
      ],
      officeTitle: 'Из Cutler Bay в наш офис во Florida City',
      office: [
        { type: 'p', text: 'Офиса в Cutler Bay у нас нет: мы обслуживаем Cutler Bay из офиса по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**. От мэрии Cutler Bay это около 12.5 мили, примерно 20 минут без пробок по Turnpike до последнего съезда на US-1; по US-1 без платных участков, но дольше. Большинству семей приезжать вообще не нужно: мы работаем по телефону, в WhatsApp, по SMS и электронной почте.' },
        { type: 'p', text: 'Часы работы: понедельник–пятница с 9 до 6, суббота — по записи. Звоните (305) 859-3953 или пишите в WhatsApp: (971) 998-7313. Оставите заявку в рабочее время — агент перезвонит в течение часа.' },
      ],
      faqTitle: 'Автостраховка в Cutler Bay: частые вопросы',
      faq: [
        { q: 'Когда вписывать подростка в автостраховку?', a: 'Сообщите агенту, когда подросток получит learner’s permit, и впишите его до того, как он начнёт ездить самостоятельно. Если водитель с правами живёт в доме, но не указан в полисе, при клейме могут возникнуть проблемы.' },
        { q: 'Что такое stacked UM?', a: 'При stacked UM лимиты UM всех машин в полисе можно сложить для пострадавшего члена семьи. При non-stacked учитывается лимит только одной машины. Во Флориде non-stacked должна стоить минимум на 20% меньше, и эта разница показывает, от чего вы отказываетесь.' },
        { q: 'Обязательна ли bodily injury liability в Cutler Bay?', a: 'Для большинства — нет. Флорида требует PIP и PDL. BI обычно становится обязательной только после определённых аварий или нарушений. Без BI нельзя оформить UM, а ваше имущество остаётся под угрозой, если вы кого-то травмируете.' },
        { q: 'Заплатит ли страховка, если машину затопит нагонной волной?', a: 'Только при наличии comprehensive. Когда шторм уже угрожает району, страховые обычно перестают вносить изменения, поэтому добавьте comprehensive до начала сезона ураганов.' },
        { q: 'Нужно ли приезжать в офис?', a: 'Нет. Большинство клиентов из Cutler Bay работают с нами по телефону, в WhatsApp, по SMS или почте. Но в наш офис во Florida City вы всегда можете заехать — это около 20 минут по Turnpike без пробок.' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
