import type { CityPage } from './types';
import { sources } from './sources';

// /[lang]/car-insurance-broward-county-fl (county hub). Facts checked 2026-10-03.
// No Broward city pages exist yet, so `served` has no links.
const SRC = ['flhsmv', 'pip', 'pip2026', 'um', 'iiiUm', 'hb837', 'crashReport', 'wilma', 'acsBroward'] as const;

export const CAR_BROWARD: CityPage = {
  path: '/car-insurance-broward-county-fl',
  line: 'auto',
  kind: 'county',
  area: 'broward',
  heroImage: 'auto-08',
  published: '2026-10-03',
  modified: '2026-10-03',
  served: [
    { name: 'Fort Lauderdale' }, { name: 'Hollywood' }, { name: 'Hallandale Beach' }, { name: 'Pembroke Pines' },
    { name: 'Miramar' }, { name: 'Davie' }, { name: 'Plantation' }, { name: 'Sunrise' }, { name: 'Weston' },
    { name: 'Coral Springs' }, { name: 'Pompano Beach' }, { name: 'Deerfield Beach' }, { name: 'Dania Beach' },
    { name: 'Cooper City' }, { name: 'Lauderhill' }, { name: 'Tamarac' }, { name: 'Margate' }, { name: 'Coconut Creek' },
  ],
  areaServed: [
    { '@type': 'AdministrativeArea', name: 'Broward County, FL' },
  ],
  copy: {
    en: {
      metaTitle: 'Car Insurance in Broward County, FL | M&K Agency',
      metaDesc: 'Car insurance for Broward drivers: I-95, I-595, the Turnpike and the Sawgrass, rail crossings, Florida PIP and uninsured motorist rules, and a free review of your policy by WhatsApp.',
      breadcrumb: 'Broward County',
      kicker: 'Auto insurance · Broward County',
      h1a: 'Car insurance in Broward County,',
      h1b: 'reviewed by a personal agent.',
      sub: 'From Hallandale Beach to Deerfield Beach and out to Weston. Send us your policy by WhatsApp or email and a licensed agent will show you the gaps, explain the options and help you when you have a claim. English, Spanish or Russian.',
      serviceType: 'Auto insurance',
      intro: [
        { type: 'h2', text: 'Broward drivers are on the road between two big counties' },
        { type: 'p', text: 'Broward had about 1.94 million residents at the 2020 Census, the second-largest county in Florida, and it sits between Miami-Dade and Palm Beach. Many residents commute across one of those county lines every day. The average one-way commute is about 29 minutes, a little shorter than in Miami-Dade, but the main corridors are some of the busiest in the state.' },
        { type: 'p', text: '**I-95** runs the length of the county near the coast, with tolled 95 Express lanes whose prices rise and fall with traffic. **I-595** crosses east to west from the Port Everglades and airport area toward the western suburbs and has its own reversible express lanes. **Florida’s Turnpike** runs north–south through the middle of the county, and the tolled **Sawgrass Expressway (SR 869)** curves along the western edge past Sunrise, Coral Springs and the Deerfield area. To the west, **I-75** heads toward Weston and Alligator Alley. On the surface streets, **US-1 (Federal Highway)** and **US-441/SR 7** carry heavy local traffic, and **A1A** runs along the beaches.' },
        { type: 'p', text: 'Broward also has busy rail corridors. Brightline intercity trains and freight trains use the coastal tracks through downtown Fort Lauderdale, Hollywood and other cities, with many street-level crossings, and Tri-Rail runs along the I-95 corridor. Never stop on the tracks or go around lowered gates.' },
      ],
      checklistTitle: 'Coverage gaps we check for Broward drivers',
      checklist: [
        '**Bodily injury liability.** Not required for most Florida drivers, and often missing on policies we review.',
        '**Uninsured motorist coverage** at the same limits as BI, and no forgotten rejection form.',
        '**Stacked UM** if there are two or more cars in the household.',
        '**Comprehensive** for flooding, theft, falling trees and hail, especially on cars parked outdoors or in coastal garages.',
        '**Medical payments coverage** to help with what PIP does not pay.',
        '**Every resident driver listed**, including adult children and relatives living with you.',
        '**Correct garaging ZIP code** and mileage, especially if you recently moved within or into Broward.',
        '**Work use**: delivery or rideshare driving usually needs an endorsement.',
        '**Umbrella liability** for homeowners and anyone with savings to protect.',
      ],
      body: [
        { type: 'h2', text: 'Florida law applies county by county the same way' },
        { type: 'p', text: 'Every registered car in Florida must carry **$10,000 of Personal Injury Protection** and **$10,000 of Property Damage Liability** continuously. PIP pays 80% of reasonable medical expenses and 60% of lost income for you and your household regardless of fault, provided you get initial treatment within 14 days, with a $2,500 limit unless a doctor finds an emergency medical condition. Bills to repeal PIP died in committee in the 2026 session.' },
        { type: 'p', text: 'What the law does **not** require of most drivers is bodily injury liability. The Insurance Research Council estimated that about 20.6% of Florida drivers were uninsured in 2023, the seventh-highest rate in the country. Uninsured motorist coverage protects you and your passengers when the other driver has no insurance or too little. Florida insurers must offer it at your BI limits and can only remove or lower it with your written rejection. With two or more cars, stacking lets the limits combine for an injured family member, and non-stacked UM must cost at least 20% less, a sign of how much protection it gives up.' },
        { type: 'p', text: 'Florida’s 2023 tort reform also changed the math after a crash. If you are found more than 50% at fault for your own injuries, you generally recover nothing from the other driver, and most negligence lawsuits must now be filed within two years. Your own policy often ends up paying.' },
        { type: 'h2', text: 'After a crash in Broward' },
        { type: 'ul', items: [
          'Call 911 if anyone is hurt. Florida requires drivers to report crashes with injuries, deaths or apparent damage of at least $2,000 to the local police, the sheriff or the Florida Highway Patrol.',
          'Photograph the vehicles, the scene and the other driver’s license, registration and insurance card.',
          'See a doctor within 14 days so you keep your PIP benefits.',
          'Report the claim to your insurer and send us the claim number. We will help you follow it.',
        ] },
        { type: 'h2', text: 'Storms and high-rise garages' },
        { type: 'p', text: 'Hurricane Wilma in 2005 brought Category 2 conditions to parts of Broward, with gusts near 100 knots and extensive damage to roofs and windows. Cars parked in low garages near the Intracoastal or on open lots are exposed to wind debris and flooding. Only comprehensive coverage pays for that damage, and it must be in place before a storm approaches.' },
        { type: 'p', text: 'M&K Agency is family-owned, with a team of 12 and more than 5,000 clients across Florida. **Send us your policy and we’ll check your coverage.** We will explain it in plain language, in English, Spanish or Russian, and you will have a personal agent when you need to file a claim.' },
      ],
      officeTitle: 'How we work with Broward clients',
      office: [
        { type: 'p', text: 'We do not have an office in Broward County. Our only office is in Florida City, at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, at the southern end of the Turnpike: roughly an hour from Pembroke Pines and about 70 to 80 minutes from Hollywood or downtown Fort Lauderdale in light traffic. So we serve Broward clients mainly by phone, WhatsApp, text and email. You send photos of your documents, we call you to review them, and you can visit by appointment whenever you like.' },
        { type: 'p', text: 'Hours are Monday to Friday, 9 to 6, and Saturday by appointment. Call (305) 859-3953 or WhatsApp (971) 998-7313. During business hours, an agent calls back within an hour.' },
      ],
      faqTitle: 'Car insurance in Broward County: common questions',
      faq: [
        { q: 'Can you insure my car if I live in Broward and your office is in Miami-Dade?', a: 'Yes. We are licensed to work with clients throughout Florida. Most Broward clients never visit the office; we handle everything by phone, WhatsApp, text and email.' },
        { q: 'What car insurance does Florida require in Broward?', a: 'Personal injury protection of $10,000 and property damage liability of $10,000, kept active as long as the car is registered. Bodily injury liability is not required for most drivers but is needed to buy uninsured motorist coverage.' },
        { q: 'What is the difference between stacked and non-stacked UM?', a: 'Stacked UM lets the UM limits of each car on your policy add up for an injured household member. Non-stacked uses only one limit. Florida requires non-stacked to cost at least 20% less than stacked.' },
        { q: 'Does my policy cover me in the 95 Express or 595 Express lanes?', a: 'Yes, your coverage is the same on any public road. The express lanes only change the tolls, which are billed through SunPass or by mail and are not paid by insurance.' },
        { q: 'How do I send you my policy?', a: 'Take a photo or screenshot of your declarations page and send it by WhatsApp to (971) 998-7313 or by text. A licensed agent will review it and call you back.' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Seguro de Auto en el Condado Broward, FL | M&K Agency',
      metaDesc: 'Seguro de auto en Broward: I-95, I-595, el Turnpike y la Sawgrass, cruces de tren, las reglas de PIP y conductor sin seguro en Florida, y revisión gratis de su póliza por WhatsApp.',
      breadcrumb: 'Condado Broward',
      kicker: 'Seguro de auto · Condado Broward',
      h1a: 'Seguro de auto en el Condado Broward,',
      h1b: 'revisado por un agente personal.',
      sub: 'De Hallandale Beach a Deerfield Beach y hasta Weston. Envíenos su póliza por WhatsApp o correo y un agente licenciado le muestra lo que falta, le explica las opciones y le ayuda cuando tiene un reclamo. En español, inglés o ruso.',
      serviceType: 'Seguro de auto',
      intro: [
        { type: 'h2', text: 'En Broward se maneja entre dos condados grandes' },
        { type: 'p', text: 'Broward tenía unos 1.94 millones de habitantes en el Censo de 2020, el segundo condado más poblado de Florida, y queda entre Miami-Dade y Palm Beach. Mucha gente cruza una de esas líneas de condado todos los días para ir a trabajar. El viaje promedio es de unos 29 minutos, un poco menos que en Miami-Dade, pero las vías principales están entre las más cargadas del estado.' },
        { type: 'p', text: 'La **I-95** recorre todo el condado cerca de la costa, con los carriles de peaje 95 Express, cuyo precio sube y baja con el tráfico. La **I-595** cruza de este a oeste, desde la zona de Port Everglades y el aeropuerto hacia los suburbios del oeste, y tiene sus propios carriles exprés reversibles. El **Turnpike** atraviesa el centro del condado de norte a sur, y la **Sawgrass Expressway (SR 869)**, también de peaje, bordea el oeste por Sunrise, Coral Springs y la zona de Deerfield. Más al oeste, la **I-75** va hacia Weston y el Alligator Alley. En las calles, la **US-1 (Federal Highway)** y la **US-441/SR 7** llevan mucho tráfico local, y la **A1A** corre junto a las playas.' },
        { type: 'p', text: 'Broward también tiene corredores de tren muy activos. Los trenes de Brightline y los de carga usan las vías de la costa por el centro de Fort Lauderdale, Hollywood y otras ciudades, con muchos cruces a nivel, y el Tri-Rail corre a lo largo de la I-95. Nunca se detenga sobre las vías ni pase por el lado de las barreras bajadas.' },
      ],
      checklistTitle: 'Lo que revisamos a los conductores de Broward',
      checklist: [
        '**Responsabilidad por lesiones (BI).** No es obligatoria para la mayoría en Florida, y falta en muchas de las pólizas que revisamos.',
        '**Conductor sin seguro (UM)** con los mismos límites que la BI, y sin un formulario de rechazo olvidado.',
        '**UM acumulable** si hay dos carros o más en la casa.',
        '**Cobertura integral** para inundación, robo, árboles caídos y granizo, sobre todo si el carro duerme afuera o en garajes cerca de la costa.',
        '**Pagos médicos (MedPay)** para lo que el PIP no paga.',
        '**Todos los conductores que viven en la casa**, incluidos hijos adultos y familiares.',
        '**Código postal y millaje correctos**, sobre todo si se mudó hace poco dentro de Broward o desde otro condado.',
        '**Uso para trabajar**: las entregas o Uber/Lyft normalmente necesitan un endoso.',
        '**Póliza paraguas** si tiene casa propia o ahorros que proteger.',
      ],
      body: [
        { type: 'h2', text: 'La ley de Florida es la misma en todos los condados' },
        { type: 'p', text: 'Todo carro registrado en Florida debe tener **$10,000 de Protección contra Lesiones Personales (PIP)** y **$10,000 de Responsabilidad por Daños a la Propiedad (PDL)** sin interrupciones. El PIP paga el 80% de los gastos médicos razonables y el 60% del ingreso perdido para usted y su familia, sin importar la culpa, siempre que reciba atención inicial dentro de 14 días, con un tope de $2,500 si un médico no determina una condición de emergencia. Los proyectos para eliminar el PIP murieron en comité en la sesión de 2026.' },
        { type: 'p', text: 'Lo que la ley **no** le exige a la mayoría es la responsabilidad por lesiones corporales. El Insurance Research Council estimó que en 2023 cerca del 20.6% de los conductores de Florida no tenía seguro, la séptima tasa más alta del país. La cobertura de conductor sin seguro le protege a usted y a sus pasajeros cuando el otro conductor no tiene seguro o tiene muy poco. La aseguradora debe ofrecerla con los límites de su BI y solo puede quitarla o bajarla con su rechazo por escrito. Con dos carros o más, la opción acumulable permite sumar los límites para un familiar lesionado, y la no acumulable debe costar al menos un 20% menos, señal de cuánta protección se pierde.' },
        { type: 'p', text: 'La reforma de 2023 también cambió las cuentas después de un choque. Si se determina que usted tuvo más del 50% de la culpa de sus propias lesiones, en general no cobra nada del otro conductor, y la mayoría de las demandas por negligencia deben presentarse en dos años. Muchas veces termina pagando su propia póliza.' },
        { type: 'h2', text: 'Después de un choque en Broward' },
        { type: 'ul', items: [
          'Llame al 911 si hay heridos. En Florida hay que reportar a la policía local, al sheriff o a la Patrulla de Carreteras los accidentes con heridos, muertos o daños aparentes de $2,000 o más.',
          'Tome fotos de los carros, del lugar y de la licencia, el registro y la tarjeta de seguro del otro conductor.',
          'Vea a un médico dentro de los 14 días para no perder los beneficios del PIP.',
          'Reporte el reclamo a su aseguradora y mándenos el número de reclamo. Le ayudamos a darle seguimiento.',
        ] },
        { type: 'h2', text: 'Tormentas y garajes de edificios altos' },
        { type: 'p', text: 'El huracán Wilma, en 2005, trajo condiciones de categoría 2 a partes de Broward, con ráfagas cercanas a los 100 nudos y daños extensos en techos y ventanas. Los carros en garajes bajos cerca del Intracostal o en estacionamientos abiertos quedan expuestos a escombros y a inundación. Solo la cobertura integral paga ese daño, y hay que tenerla antes de que se acerque una tormenta.' },
        { type: 'p', text: 'M&K Agency es una agencia familiar con un equipo de 12 personas y más de 5,000 clientes en Florida. **Envíenos su póliza y la revisamos.** Se la explicamos en palabras sencillas, en español, inglés o ruso, y tendrá un agente personal cuando necesite hacer un reclamo.' },
      ],
      officeTitle: 'Cómo trabajamos con clientes de Broward',
      office: [
        { type: 'p', text: 'No tenemos oficina en el Condado Broward. Nuestra única oficina está en Florida City, en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, al final del Turnpike: más o menos una hora desde Pembroke Pines y de 70 a 80 minutos desde Hollywood o el centro de Fort Lauderdale sin tráfico. Por eso atendemos a los clientes de Broward sobre todo por teléfono, WhatsApp, texto y correo. Usted nos manda fotos de sus documentos, le llamamos para revisarlos y, si quiere, nos visita con cita.' },
        { type: 'p', text: 'Horario: lunes a viernes de 9 a 6, sábados con cita. Llame al (305) 859-3953 o escriba por WhatsApp al (971) 998-7313. En horario de oficina, un agente le devuelve la llamada en menos de una hora.' },
      ],
      faqTitle: 'Seguro de auto en el Condado Broward: preguntas frecuentes',
      faq: [
        { q: '¿Pueden asegurar mi carro si vivo en Broward y su oficina está en Miami-Dade?', a: 'Sí. Trabajamos con clientes en toda Florida. La mayoría de nuestros clientes de Broward nunca viene a la oficina; todo se hace por teléfono, WhatsApp, texto y correo.' },
        { q: '¿Qué seguro de auto exige Florida en Broward?', a: 'Protección contra lesiones personales de $10,000 y daños a la propiedad de $10,000, activos mientras el carro esté registrado. La responsabilidad por lesiones no es obligatoria para la mayoría, pero hace falta para poder comprar cobertura de conductor sin seguro.' },
        { q: '¿Qué diferencia hay entre UM acumulable y no acumulable?', a: 'Con la acumulable, los límites de UM de cada carro de la póliza se suman para un familiar lesionado. La no acumulable usa un solo límite. En Florida, la no acumulable debe costar al menos un 20% menos que la acumulable.' },
        { q: '¿Mi póliza me cubre en los carriles 95 Express o 595 Express?', a: 'Sí, su cobertura es la misma en cualquier vía pública. Los carriles exprés solo cambian el peaje, que se cobra por SunPass o por correo y no lo paga el seguro.' },
        { q: '¿Cómo les envío mi póliza?', a: 'Tome una foto o captura de su página de declaraciones y mándela por WhatsApp al (971) 998-7313 o por mensaje de texto. Un agente licenciado la revisa y le llama.' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Автостраховка в округе Broward, FL | M&K Agency',
      metaDesc: 'Автостраховка для водителей Broward: I-95, I-595, Turnpike и Sawgrass, железнодорожные переезды, правила PIP и UM во Флориде и бесплатная проверка полиса через WhatsApp.',
      breadcrumb: 'Округ Broward',
      kicker: 'Автостраховка · округ Broward',
      h1a: 'Автостраховка в округе Broward —',
      h1b: 'с проверкой от личного агента.',
      sub: 'От Hallandale Beach до Deerfield Beach и до Weston. Пришлите нам полис в WhatsApp или по почте — лицензированный агент покажет пробелы, объяснит варианты и поможет, когда понадобится клейм. По-русски, по-английски или по-испански.',
      serviceType: 'Автострахование',
      intro: [
        { type: 'h2', text: 'Водители Broward живут между двумя большими округами' },
        { type: 'p', text: 'По переписи 2020 года в Broward жило около 1.94 миллиона человек — это второй по населению округ Флориды, и он зажат между Miami-Dade и Palm Beach. Многие каждый день пересекают одну из этих границ по дороге на работу. Средняя поездка в одну сторону — около 29 минут, чуть меньше, чем в Miami-Dade, но главные магистрали здесь одни из самых загруженных в штате.' },
        { type: 'p', text: '**I-95** проходит через весь округ вдоль побережья; на ней платные полосы 95 Express, цена которых зависит от трафика. **I-595** пересекает округ с востока на запад — от района Port Everglades и аэропорта к западным пригородам — и имеет свои реверсивные экспресс-полосы. **Turnpike** идёт с севера на юг через центр округа, а платная **Sawgrass Expressway (SR 869)** огибает западную окраину мимо Sunrise, Coral Springs и района Deerfield. Дальше на запад **I-75** ведёт к Weston и Alligator Alley. На обычных улицах основной местный поток несут **US-1 (Federal Highway)** и **US-441/SR 7**, а вдоль пляжей идёт **A1A**.' },
        { type: 'p', text: 'В Broward ещё и оживлённые железные дороги. Поезда Brightline и грузовые составы идут по прибрежной линии через центр Fort Lauderdale, Hollywood и другие города, с множеством переездов в одном уровне, а вдоль I-95 ходит Tri-Rail. Никогда не останавливайтесь на путях и не объезжайте опущенный шлагбаум.' },
      ],
      checklistTitle: 'Что мы проверяем у водителей Broward',
      checklist: [
        '**Bodily injury liability.** Для большинства во Флориде она не обязательна и часто отсутствует в полисах, которые мы смотрим.',
        '**UM с теми же лимитами, что и BI**, — и без забытого подписанного отказа.',
        '**Stacked UM**, если в семье две машины и больше.',
        '**Comprehensive** от затопления, угона, упавших деревьев и града — особенно если машина стоит на улице или в гараже у побережья.',
        '**Medical payments (MedPay)** — на то, что не оплачивает PIP.',
        '**Все водители, живущие в доме, вписаны в полис**, включая взрослых детей и родственников.',
        '**Правильный ZIP-код стоянки и пробег** — особенно если вы недавно переехали внутри Broward или из другого округа.',
        '**Работа за рулём**: для доставки или такси через приложение обычно нужно отдельное дополнение.',
        '**Umbrella liability** для владельцев домов и всех, кому есть что защищать.',
      ],
      body: [
        { type: 'h2', text: 'Закон Флориды одинаков для всех округов' },
        { type: 'p', text: 'Каждая зарегистрированная во Флориде машина должна иметь **$10,000 PIP** и **$10,000 PDL** без перерывов. PIP оплачивает 80% разумных медицинских расходов и 60% потерянного дохода вам и семье независимо от вины — при условии, что вы обратились к врачу в течение 14 дней; без заключения о состоянии, требующем неотложной помощи, лимит — $2,500. Законопроекты об отмене PIP не прошли комитеты в сессии 2026 года.' },
        { type: 'p', text: 'Чего закон от большинства водителей **не** требует — так это bodily injury liability. По оценке Insurance Research Council, в 2023 году около 20.6% водителей Флориды ездили без страховки — седьмое место в стране. UM защищает вас и пассажиров, когда у другого водителя нет страховки или её слишком мало. Страховая обязана предложить UM с лимитами вашей BI и может убрать или уменьшить её только по вашему письменному отказу. Если машин две и больше, stacked UM позволяет сложить лимиты для пострадавшего члена семьи, а non-stacked по закону должна стоить минимум на 20% меньше — по этой разнице видно, сколько защиты теряется.' },
        { type: 'p', text: 'Реформа 2023 года изменила и расклад после аварии. Если суд решит, что вы виноваты в своих травмах больше чем на 50%, вы, как правило, ничего не получите с другого водителя, а большинство исков о небрежности теперь нужно подать в течение двух лет. Часто в итоге платит ваш собственный полис.' },
        { type: 'h2', text: 'После ДТП в Broward' },
        { type: 'ul', items: [
          'Если есть пострадавшие, звоните 911. Во Флориде о ДТП с пострадавшими, погибшими или видимым ущербом от $2,000 нужно сообщить в местную полицию, офис шерифа или Florida Highway Patrol.',
          'Сфотографируйте машины, место аварии, права, регистрацию и страховую карточку другого водителя.',
          'Обратитесь к врачу в течение 14 дней, чтобы сохранить право на PIP.',
          'Сообщите о клейме в страховую и пришлите нам номер клейма. Мы поможем его вести.',
        ] },
        { type: 'h2', text: 'Штормы и гаражи высотных домов' },
        { type: 'p', text: 'Ураган Wilma в 2005 году принёс в часть Broward условия 2-й категории с порывами около 100 узлов и серьёзными повреждениями крыш и окон. Машины в низких гаражах у Intracoastal или на открытых парковках страдают от летящих обломков и воды. Платит за это только comprehensive, и оформить её нужно до того, как шторм приблизится.' },
        { type: 'p', text: 'M&K Agency — семейное агентство: 12 человек в команде и более 5,000 клиентов по всей Флориде. **Пришлите нам свой полис — мы проверим покрытие.** Объясним всё простыми словами — по-русски, по-английски или по-испански, — и когда нужно будет подать клейм, у вас будет личный агент.' },
      ],
      officeTitle: 'Как мы работаем с клиентами из Broward',
      office: [
        { type: 'p', text: 'Офиса в округе Broward у нас нет. Наш единственный офис — во Florida City, по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, в самом конце Turnpike: без пробок это примерно час от Pembroke Pines и 70–80 минут от Hollywood или центра Fort Lauderdale. Поэтому клиентов из Broward мы обслуживаем в основном по телефону, в WhatsApp, по SMS и почте: вы присылаете фото документов, мы звоним и разбираем их с вами, а приехать можно по записи в любое время.' },
        { type: 'p', text: 'Часы работы: понедельник–пятница с 9 до 6, суббота — по записи. Звоните (305) 859-3953 или пишите в WhatsApp: (971) 998-7313. В рабочее время агент перезванивает в течение часа.' },
      ],
      faqTitle: 'Автостраховка в округе Broward: частые вопросы',
      faq: [
        { q: 'Вы можете застраховать мою машину, если я живу в Broward, а офис у вас в Miami-Dade?', a: 'Да. Мы работаем с клиентами по всей Флориде. Большинство клиентов из Broward в офис не приезжают — всё делается по телефону, в WhatsApp, по SMS и почте.' },
        { q: 'Какую автостраховку требует Флорида в Broward?', a: 'PIP на $10,000 и PDL на $10,000 — действующие всё время, пока машина зарегистрирована. Bodily injury liability для большинства не обязательна, но без неё нельзя купить UM.' },
        { q: 'Чем stacked UM отличается от non-stacked?', a: 'При stacked лимиты UM всех машин в полисе складываются для пострадавшего члена семьи. При non-stacked действует один лимит. Во Флориде non-stacked должна стоить минимум на 20% меньше, чем stacked.' },
        { q: 'Действует ли полис на полосах 95 Express или 595 Express?', a: 'Да, покрытие одинаковое на любой дороге общего пользования. На экспресс-полосах меняется только плата за проезд — её списывает SunPass или присылают счёт по почте, и страховка её не оплачивает.' },
        { q: 'Как прислать вам полис?', a: 'Сфотографируйте или сделайте скриншот declarations page и отправьте в WhatsApp на (971) 998-7313 или по SMS. Лицензированный агент проверит его и перезвонит.' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
