import type { CityPage } from './types';
import { sources } from './sources';

// /[lang]/car-insurance-homestead-fl. Local facts checked 2026-10-03 (see sources).
const SRC = ['flhsmv', 'pip', 'um', 'iiiUm', 'hb837', 'turnpike', 'krome', 'metroExpress', 'acsHomestead', 'homesteadCity'] as const;

export const CAR_HOMESTEAD: CityPage = {
  path: '/car-insurance-homestead-fl',
  line: 'auto',
  kind: 'city',
  area: 'homestead',
  parent: '/car-insurance-miami-dade-county-fl',
  heroImage: 'auto-05',
  published: '2026-10-03',
  modified: '2026-10-03',
  areaServed: [
    { '@type': 'City', name: 'Homestead, FL' },
    { '@type': 'AdministrativeArea', name: 'Miami-Dade County, FL' },
  ],
  copy: {
    en: {
      metaTitle: 'Car Insurance in Homestead, FL | Local Agent | M&K Agency',
      metaDesc: 'Car insurance for Homestead drivers: Florida PIP/PDL rules, why uninsured motorist coverage matters on US-1 and the Turnpike, and a free coverage check.',
      breadcrumb: 'Homestead',
      kicker: 'Auto insurance · Homestead, FL',
      h1a: 'Car insurance in Homestead, FL,',
      h1b: 'built around how you actually drive.',
      sub: 'Long commutes up the Turnpike, US-1 traffic, farm trucks on Krome Avenue. We look at your policy line by line, show you the gaps and help your family at claim time. English, Spanish or Russian.',
      serviceType: 'Auto insurance',
      intro: [
        { type: 'h2', text: 'Driving in Homestead is mostly about distance' },
        { type: 'p', text: 'Homestead sits at the southern end of Miami-Dade, between Everglades and Biscayne National Parks, and most jobs are north of it. Census commuting data for 2020–2024 puts the average one-way trip to work for Homestead residents at about 36 minutes, and close to a third of commuters spend 45 minutes or more each way. Nearly nine in ten get there by car, truck or van. That is a lot of miles at highway speed, and mileage is one of the first things an insurer asks about.' },
        { type: 'p', text: 'The main routes are familiar to anyone who lives here. **US-1** runs through the middle of the city as Homestead Boulevard and continues south through Florida City as the only road to the Keys. **Florida’s Turnpike (Homestead Extension, SR 821)** has exits at SW 137th Avenue, Biscayne Drive (SW 288th Street) and Campbell Drive (SW 312th Street) before it ends at US-1 in Florida City, and northbound drivers pass the all-electronic Homestead toll gantry on the way to Cutler Bay and Kendall. **Krome Avenue (SR 997)** runs north–south along the west side of town and through the historic downtown; FDOT finished its multi-year upgrade of the roughly 36-mile Krome corridor in 2021, but it is still a freight and farm route through the Redland, so expect trucks and slow equipment.' },
        { type: 'p', text: 'One newer thing to watch: since October 27, 2025, Miami-Dade’s Metro Express bus rapid transit runs 20 miles along the South Dade TransitWay from Florida City to Dadeland South, with gate arms and signal priority at intersections. Treat those busway crossings like rail crossings. And on race weekends at Homestead-Miami Speedway, traffic around SW 137th Avenue and Palm Drive changes completely.' },
      ],
      checklistTitle: 'Coverage gaps we check on Homestead auto policies',
      checklist: [
        '**Bodily injury liability:** Florida does not require it for most drivers. If you cause a crash on the Turnpike with no BI, your savings and wages are what is left to pay the other family.',
        '**Uninsured/underinsured motorist (UM):** it can only be added alongside BI, and it protects your own family when the other driver has little or no coverage.',
        '**Stacked vs. non-stacked UM:** with two or more cars, stacking can multiply the protection. Many people signed a non-stacked form without knowing it.',
        '**Comprehensive:** the only part of an auto policy that pays for flood or falling-tree damage to your car in a storm. A flood policy for the house does not cover cars.',
        '**Deductibles you can actually pay** the week after a hurricane or a crash.',
        '**Rental reimbursement and towing:** a long commute with no car is a lost paycheck.',
        '**Every licensed driver in the household listed**, including teens, and the correct garaging address.',
        '**Gap coverage added to your auto policy** if you finance or lease and owe more than the car is worth.',
        '**Work use:** delivery and rideshare driving are usually excluded from a personal policy unless you add the right coverage.',
      ],
      body: [
        { type: 'h2', text: 'What Florida law requires, and what it leaves out' },
        { type: 'p', text: 'To register a car in Florida you need **$10,000 of Personal Injury Protection (PIP)** and **$10,000 of Property Damage Liability (PDL)**, and the coverage has to stay continuous even if the car sits in the driveway. PIP pays 80% of reasonable medical bills and 60% of lost income for you and your household, no matter who caused the crash, plus a $5,000 death benefit. Two details catch people out: you must get initial medical care **within 14 days** of the crash, and benefits are capped at $2,500 unless a doctor determines there was an emergency medical condition.' },
        { type: 'p', text: 'What Florida does **not** require of most drivers is bodily injury liability, the coverage that pays for injuries you cause to other people. BI generally becomes mandatory only after certain crashes or violations (SR-22 or FR-44 filings). The flip side is that many cars on US-1 carry only the state minimum. The Insurance Research Council estimated that about 20.6% of Florida drivers were uninsured in 2023, roughly one in five, which is why we spend real time on **uninsured motorist coverage**. Florida law ties UM to BI: insurers must offer UM at your BI limits, and you can only reject it or choose lower limits in writing.' },
        { type: 'p', text: 'Since March 24, 2023, Florida uses modified comparative negligence: if you are found more than 50% at fault for your own injuries, you generally cannot recover from the other driver, and the deadline to file most negligence lawsuits dropped from four years to two. Your own coverage matters more than it used to.' },
        { type: 'h2', text: 'Hurricane season and your car' },
        { type: 'p', text: 'Homestead remembers August 24, 1992. A storm surge or a stalled tropical system can put water in low streets anywhere in South Dade. Only comprehensive coverage pays for a flooded or crushed car, and insurers can stop adding or changing coverage once a storm is approaching. Check it in May, not when the cone is on TV.' },
        { type: 'h2', text: 'How we help Homestead families' },
        { type: 'p', text: 'M&K Agency is a family-owned agency with a team of 12 and more than 5,000 clients across Florida. We do not just quote a number. **Send us your current policy and we’ll check your coverage**: we will tell you, in English, Spanish or Russian, where you are exposed and what it would take to fix it. When something happens, you call a person you know, and we help you through the claim.' },
      ],
      officeTitle: 'Our office is a few minutes from downtown Homestead',
      office: [
        { type: 'p', text: 'We do not have an office inside Homestead; we serve Homestead drivers from our Florida City office at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, just past the Homestead city line. From Homestead City Hall it is about 1.5 miles south on US-1, usually around five minutes in light traffic. From the Turnpike, take the last exit at US-1 in Florida City.' },
        { type: 'p', text: 'We are open Monday to Friday from 9 to 6, and on Saturdays by appointment. Call (305) 859-3953 or message us on WhatsApp at (971) 998-7313. If you leave a request during business hours, an agent calls you back within an hour.' },
      ],
      faqTitle: 'Car insurance in Homestead: common questions',
      faq: [
        { q: 'What car insurance is required in Homestead, FL?', a: 'The same as anywhere in Florida: $10,000 of PIP and $10,000 of property damage liability, kept continuously while the car is registered. Bodily injury liability is not required for most drivers, but without it you cannot add uninsured motorist coverage and your own assets are exposed if you injure someone.' },
        { q: 'Why does uninsured motorist coverage matter so much here?', a: 'The Insurance Research Council estimated that about one in five Florida drivers was uninsured in 2023, and many insured drivers carry only PIP and PDL. UM pays for injuries to you and your passengers when the at-fault driver cannot. Florida requires insurers to offer it with BI, and it can only be rejected in writing.' },
        { q: 'I commute to Kendall or Miami on the Turnpike every day. Does that change my policy?', a: 'It can. Insurers rate on how far and how often you drive, so tell us your real commute. A long daily commute is also a reason to look closely at BI and UM limits, rental reimbursement and towing.' },
        { q: 'Does my car insurance cover hurricane or flood damage?', a: 'Only if you carry comprehensive coverage. Liability, PIP and collision do not pay for a car damaged by flood water or a falling tree. A home flood policy does not cover vehicles either.' },
        { q: 'Can you review the policy I already have?', a: 'Yes. Send us a photo of your declarations page by WhatsApp or text, or bring it to our Florida City office. A licensed agent will go through it with you and show you any gaps. There is no charge for the review.' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Seguro de Auto en Homestead, FL | Agente Local | M&K Agency',
      metaDesc: 'Seguro de auto para Homestead: lo que exige Florida (PIP y PDL), por qué importa la cobertura de conductor sin seguro y revisión gratis de su póliza.',
      breadcrumb: 'Homestead',
      kicker: 'Seguro de auto · Homestead, FL',
      h1a: 'Seguro de auto en Homestead, FL,',
      h1b: 'pensado para cómo usted maneja.',
      sub: 'Muchas millas por el Turnpike, el tráfico de la US-1 y los camiones de la Krome. Revisamos su póliza punto por punto, le mostramos lo que le falta y le acompañamos si tiene un reclamo. En español, inglés o ruso.',
      serviceType: 'Seguro de auto',
      intro: [
        { type: 'h2', text: 'En Homestead, todo queda lejos' },
        { type: 'p', text: 'Homestead está en el extremo sur de Miami-Dade, entre los parques nacionales Everglades y Biscayne, y la mayoría de los trabajos quedan al norte. Según los datos del Censo de 2020 a 2024, el residente promedio tarda unos 36 minutos en llegar al trabajo, y casi uno de cada tres pasa 45 minutos o más en cada viaje. Casi nueve de cada diez van en carro, camioneta o van. Son muchas millas a velocidad de autopista, y las millas son de lo primero que pregunta una aseguradora.' },
        { type: 'p', text: 'Las rutas las conoce cualquiera que viva aquí. La **US-1** atraviesa la ciudad con el nombre de Homestead Boulevard y sigue hacia Florida City como la única vía a los Cayos. El **Turnpike (Extensión Homestead, SR 821)** tiene salidas en la SW 137 Avenue, Biscayne Drive (SW 288 Street) y Campbell Drive (SW 312 Street) y termina en la US-1, en Florida City; quien sube hacia Cutler Bay o Kendall pasa por el peaje electrónico de Homestead. La **Krome Avenue (SR 997)** corre de norte a sur por el oeste de la ciudad y por el centro histórico. El FDOT terminó en 2021 la renovación de los casi 36 millas del corredor, pero sigue siendo ruta de carga y de fincas en la zona de Redland: cuente con camiones y equipos agrícolas lentos.' },
        { type: 'p', text: 'Algo nuevo: desde el 27 de octubre de 2025, el Metro Express de Miami-Dade recorre 20 millas por el South Dade TransitWay, de Florida City a Dadeland South, con barreras y prioridad en los semáforos. Cruce esas intersecciones como si fueran vías de tren. Y en fin de semana de carreras en el Homestead-Miami Speedway, el tráfico por la SW 137 Avenue y Palm Drive cambia por completo.' },
      ],
      checklistTitle: 'Lo que revisamos en las pólizas de auto de Homestead',
      checklist: [
        '**Responsabilidad por lesiones (BI):** Florida no la exige a la mayoría. Si usted causa un accidente en el Turnpike sin BI, lo que queda para pagarle a la otra familia son sus ahorros y su sueldo.',
        '**Conductor sin seguro (UM):** solo se puede tener junto con BI, y protege a su propia familia cuando el otro conductor no tiene con qué pagar.',
        '**UM acumulable o no acumulable (stacked):** con dos carros o más, la versión acumulable multiplica la protección. Mucha gente firmó la no acumulable sin saberlo.',
        '**Cobertura integral (comprehensive):** es la única parte de la póliza de auto que paga si el carro se inunda o le cae un árbol en una tormenta. El seguro de inundación de la casa no cubre carros.',
        '**Deducibles que usted pueda pagar** la semana después de un huracán o un choque.',
        '**Carro de alquiler y grúa:** con un viaje largo al trabajo, quedarse sin carro es perder días de sueldo.',
        '**Todos los conductores de la casa en la póliza**, incluidos los jóvenes, y la dirección correcta donde duerme el carro.',
        '**Cobertura GAP agregada a su póliza de auto** si financia o arrienda y debe más de lo que vale el carro.',
        '**Uso para trabajar:** las entregas y Uber o Lyft casi nunca están cubiertas por una póliza personal si no se agrega la cobertura adecuada.',
      ],
      body: [
        { type: 'h2', text: 'Lo que exige la ley de Florida y lo que deja por fuera' },
        { type: 'p', text: 'Para registrar un carro en Florida necesita **$10,000 de Protección contra Lesiones Personales (PIP)** y **$10,000 de Responsabilidad por Daños a la Propiedad (PDL)**, sin interrupciones, aunque el carro no se use. El PIP paga el 80% de los gastos médicos razonables y el 60% del ingreso perdido para usted y su familia, sin importar quién tuvo la culpa, además de un beneficio por muerte de $5,000. Dos detalles que sorprenden: hay que recibir la primera atención médica **dentro de los 14 días** del accidente, y el beneficio se limita a $2,500 si un médico no determina que hubo una condición médica de emergencia.' },
        { type: 'p', text: 'Lo que Florida **no** le exige a la mayoría es la responsabilidad por lesiones corporales (BI), que paga las lesiones que usted le cause a otros. Normalmente solo se vuelve obligatoria después de ciertos accidentes o infracciones (trámites SR-22 o FR-44). El resultado es que muchos carros en la US-1 andan con el mínimo. El Insurance Research Council estimó que en 2023 alrededor del 20.6% de los conductores de Florida no tenía seguro, uno de cada cinco más o menos. Por eso le dedicamos tiempo a la **cobertura de conductor sin seguro (UM)**. La ley la amarra a la BI: la aseguradora tiene que ofrecérsela con los mismos límites y solo se puede rechazar o bajar por escrito.' },
        { type: 'p', text: 'Desde el 24 de marzo de 2023, Florida aplica la negligencia comparativa modificada: si se determina que usted tuvo más del 50% de la culpa de sus propias lesiones, en general no puede cobrarle al otro conductor. Además, el plazo para demandar en la mayoría de los casos de negligencia bajó de cuatro a dos años. Su propia póliza pesa más que antes.' },
        { type: 'h2', text: 'Temporada de huracanes y su carro' },
        { type: 'p', text: 'En Homestead nadie olvida el 24 de agosto de 1992. Una marejada o una tormenta que se queda estacionada puede inundar calles bajas en cualquier parte del sur de Miami-Dade. Solo la cobertura integral paga un carro inundado o aplastado, y las aseguradoras pueden dejar de hacer cambios cuando ya viene una tormenta. Revíselo en mayo, no cuando el cono ya está en el noticiero.' },
        { type: 'h2', text: 'Cómo ayudamos a las familias de Homestead' },
        { type: 'p', text: 'M&K Agency es una agencia familiar con un equipo de 12 personas y más de 5,000 clientes en toda Florida. No nos limitamos a darle un precio. **Envíenos su póliza y la revisamos**: le diremos con claridad dónde está desprotegido y qué haría falta para corregirlo. Y si un día tiene un accidente, llama a alguien que ya conoce, y le ayudamos con el reclamo de principio a fin.' },
      ],
      officeTitle: 'Nuestra oficina queda a pocos minutos del centro de Homestead',
      office: [
        { type: 'p', text: 'No tenemos oficina dentro de Homestead: atendemos a los conductores de Homestead desde nuestra oficina en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, justo después del límite de la ciudad. Desde la Alcaldía de Homestead son aproximadamente 1.5 millas hacia el sur por la US-1, unos cinco minutos sin tráfico. Si viene por el Turnpike, tome la última salida, en la US-1 de Florida City.' },
        { type: 'p', text: 'Abrimos de lunes a viernes de 9 a 6, y los sábados con cita. Llame al (305) 859-3953 o escríbanos por WhatsApp al (971) 998-7313. Si nos deja un mensaje en horario de oficina, un agente le devuelve la llamada en menos de una hora.' },
      ],
      faqTitle: 'Seguro de auto en Homestead: preguntas frecuentes',
      faq: [
        { q: '¿Qué seguro de auto es obligatorio en Homestead, FL?', a: 'El mismo que en toda Florida: $10,000 de PIP y $10,000 de daños a la propiedad (PDL), sin interrupciones mientras el carro esté registrado. La responsabilidad por lesiones (BI) no es obligatoria para la mayoría, pero sin ella no puede tener cobertura de conductor sin seguro y su patrimonio queda expuesto si lesiona a alguien.' },
        { q: '¿Por qué importa tanto la cobertura de conductor sin seguro aquí?', a: 'El Insurance Research Council calculó que en 2023 cerca de uno de cada cinco conductores en Florida no tenía seguro, y muchos de los asegurados solo llevan PIP y PDL. La UM paga las lesiones suyas y de sus pasajeros cuando el culpable no puede. En Florida la aseguradora tiene que ofrecerla junto con la BI y solo se puede rechazar por escrito.' },
        { q: 'Voy todos los días a Kendall o a Miami por el Turnpike. ¿Eso cambia mi póliza?', a: 'Puede cambiarla. Las aseguradoras calculan según cuánto y cuán seguido maneja, así que díganos su recorrido real. Un viaje largo cada día también es razón para revisar bien los límites de BI y UM, el carro de alquiler y la grúa.' },
        { q: '¿Mi seguro de auto cubre daños por huracán o inundación?', a: 'Solo si tiene cobertura integral (comprehensive). La responsabilidad civil, el PIP y la cobertura de choque no pagan un carro dañado por agua o por un árbol. La póliza de inundación de la casa tampoco cubre vehículos.' },
        { q: '¿Pueden revisar la póliza que ya tengo?', a: 'Sí. Mándenos una foto de la página de declaraciones por WhatsApp o mensaje de texto, o tráigala a nuestra oficina en Florida City. Un agente licenciado la revisa con usted y le muestra lo que le falta. La revisión no cuesta nada.' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Автостраховка в Homestead, FL | Местный агент | M&K Agency',
      metaDesc: 'Автостраховка для Homestead: что требует закон Флориды (PIP и PDL), зачем нужна защита от незастрахованных водителей и бесплатная проверка полиса.',
      breadcrumb: 'Homestead',
      kicker: 'Автостраховка · Homestead, FL',
      h1a: 'Автостраховка в Homestead, FL —',
      h1b: 'под ваши реальные поездки.',
      sub: 'Ежедневные поездки по Turnpike, пробки на US-1, фуры на Krome Avenue. Разберём ваш полис построчно, покажем пробелы и поможем семье, если случится авария. По-русски, по-английски или по-испански.',
      serviceType: 'Автострахование',
      intro: [
        { type: 'h2', text: 'В Homestead главное — расстояния' },
        { type: 'p', text: 'Homestead — самый юг Miami-Dade, между национальными парками Everglades и Biscayne, а основная работа находится севернее. По данным переписи за 2020–2024 годы, дорога на работу у жителей Homestead занимает в среднем около 36 минут в одну сторону, и почти треть тратит 45 минут и больше. Почти девять из десяти ездят на машине. Это много миль на скорости шоссе, а пробег — один из первых вопросов, которые задаёт страховая.' },
        { type: 'p', text: 'Маршруты знакомы всем, кто здесь живёт. **US-1** проходит через центр города под названием Homestead Boulevard и дальше, через Florida City, остаётся единственной дорогой на Keys. На **Turnpike (Homestead Extension, SR 821)** есть съезды на SW 137th Avenue, Biscayne Drive (SW 288th Street) и Campbell Drive (SW 312th Street), а заканчивается он на US-1 во Florida City. По пути на север, к Cutler Bay и Kendall, вы проезжаете электронный пункт оплаты Homestead, так что без SunPass не обойтись. **Krome Avenue (SR 997)** идёт с севера на юг по западной части города и через исторический центр. FDOT закончил многолетнюю реконструкцию этого коридора длиной около 36 миль в 2021 году, но это по-прежнему грузовой и фермерский маршрут через Redland: фуры и медленная сельхозтехника — обычное дело.' },
        { type: 'p', text: 'Новое, к чему стоит привыкнуть: с 27 октября 2025 года по South Dade TransitWay ходит скоростной автобус Metro Express — 20 миль от Florida City до Dadeland South, со шлагбаумами и приоритетом на светофорах. Пересекайте эти перекрёстки так же внимательно, как железнодорожный переезд. А в гоночные выходные на Homestead-Miami Speedway движение по SW 137th Avenue и Palm Drive становится совсем другим.' },
      ],
      checklistTitle: 'Какие пробелы мы ищем в автополисах жителей Homestead',
      checklist: [
        '**Bodily injury liability (BI):** для большинства водителей во Флориде она не обязательна. Если вы без BI станете виновником аварии на Turnpike, платить пострадавшей семье придётся из сбережений и зарплаты.',
        '**Uninsured/underinsured motorist (UM):** добавляется только вместе с BI и защищает вашу семью, когда у виновника нет страховки или её мало.',
        '**Stacked или non-stacked UM:** если машин две и больше, «стекинг» умножает защиту. Многие подписали отказ от него, даже не заметив.',
        '**Comprehensive:** единственная часть автополиса, которая платит, если машину затопило или на неё упало дерево во время шторма. Страховка дома от наводнения машины не покрывает.',
        '**Франшиза (deductible), которую реально заплатить** через неделю после урагана или аварии.',
        '**Аренда машины и эвакуатор:** при длинной дороге на работу остаться без машины — значит терять зарплату.',
        '**Все водители в семье вписаны в полис**, включая подростков, и указан правильный адрес, где ночует машина.',
        '**GAP-покрытие в составе автополиса**, если машина в кредите или лизинге и долг больше её стоимости.',
        '**Работа за рулём:** доставка, Uber и Lyft обычно исключены из личного полиса, если не добавить нужное покрытие.',
      ],
      body: [
        { type: 'h2', text: 'Что требует закон Флориды и чего в нём нет' },
        { type: 'p', text: 'Чтобы зарегистрировать машину во Флориде, нужны **$10,000 PIP (Personal Injury Protection)** и **$10,000 PDL (Property Damage Liability)**, причём без перерывов, даже если машина стоит во дворе. PIP оплачивает 80% разумных медицинских расходов и 60% потерянного дохода — вам и членам семьи, независимо от того, кто виноват, плюс $5,000 при гибели. Два момента, о которых узнают слишком поздно: к врачу нужно обратиться **в течение 14 дней** после аварии, а без заключения врача о состоянии, требующем неотложной помощи (emergency medical condition), выплата ограничена $2,500.' },
        { type: 'p', text: 'Чего Флорида от большинства водителей **не** требует — так это bodily injury liability, то есть страховки, которая платит за травмы, причинённые другим людям. Обычно BI становится обязательной только после определённых аварий или нарушений (SR-22 или FR-44). Поэтому многие машины на US-1 застрахованы по минимуму. По оценке Insurance Research Council, в 2023 году около 20.6% водителей Флориды ездили без страховки — примерно каждый пятый. Вот почему мы так подробно говорим о **UM**. Закон привязывает её к BI: страховая обязана предложить UM с теми же лимитами, а отказаться от неё или уменьшить лимиты можно только письменно.' },
        { type: 'p', text: 'С 24 марта 2023 года во Флориде действует модифицированная сравнительная вина: если суд решит, что вы виноваты в собственных травмах больше чем на 50%, получить компенсацию с другого водителя, как правило, нельзя. А срок подачи большинства исков о небрежности сократился с четырёх лет до двух. Собственный полис теперь значит больше, чем раньше.' },
        { type: 'h2', text: 'Сезон ураганов и ваша машина' },
        { type: 'p', text: 'В Homestead хорошо помнят 24 августа 1992 года — ураган Andrew. Нагонная волна или затяжной тропический шторм могут затопить низкие улицы в любой части South Dade. За затопленную или раздавленную машину платит только comprehensive, а когда шторм уже приближается, страховые могут перестать оформлять изменения. Проверьте полис в мае, а не тогда, когда «конус» прогноза уже показывают в новостях.' },
        { type: 'h2', text: 'Как мы помогаем семьям из Homestead' },
        { type: 'p', text: 'M&K Agency — семейное агентство: команда из 12 человек и более 5,000 клиентов по всей Флориде. Мы не просто называем цену. **Пришлите нам свой полис — мы проверим покрытие** и простыми словами объясним, где вы не защищены и что нужно изменить. А если что-то случится, вы звоните человеку, которого уже знаете, и мы помогаем пройти клейм до конца.' },
      ],
      officeTitle: 'Наш офис — в нескольких минутах от центра Homestead',
      office: [
        { type: 'p', text: 'Офиса в самом Homestead у нас нет: водителей из Homestead мы обслуживаем из офиса во Florida City по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, сразу за границей города. От мэрии Homestead это примерно 1.5 мили на юг по US-1, около пяти минут без пробок. С Turnpike — последний съезд, на US-1 во Florida City.' },
        { type: 'p', text: 'Мы работаем с понедельника по пятницу с 9 до 6, в субботу — по записи. Звоните (305) 859-3953 или пишите в WhatsApp: (971) 998-7313. Если оставите заявку в рабочее время, агент перезвонит в течение часа.' },
      ],
      faqTitle: 'Автостраховка в Homestead: частые вопросы',
      faq: [
        { q: 'Какая автостраховка обязательна в Homestead, FL?', a: 'Та же, что и во всей Флориде: $10,000 PIP и $10,000 PDL, без перерывов, пока машина зарегистрирована. Bodily injury liability для большинства не обязательна, но без неё нельзя оформить UM, и если вы кого-то травмируете, под ударом окажется ваше имущество.' },
        { q: 'Почему здесь так важна защита от незастрахованных водителей?', a: 'По оценке Insurance Research Council, в 2023 году примерно каждый пятый водитель Флориды был без страховки, а многие застрахованные имеют только PIP и PDL. UM оплачивает травмы вам и вашим пассажирам, когда виновник заплатить не может. Страховая обязана предложить UM вместе с BI, а отказ оформляется только письменно.' },
        { q: 'Я каждый день езжу в Kendall или Miami по Turnpike. Это влияет на полис?', a: 'Может повлиять. Страховые учитывают, сколько и как часто вы ездите, поэтому называйте реальный маршрут. Длинная ежедневная дорога — ещё и повод внимательно посмотреть на лимиты BI и UM, аренду машины и эвакуатор.' },
        { q: 'Покрывает ли автостраховка ущерб от урагана или наводнения?', a: 'Только если у вас есть comprehensive. Liability, PIP и collision не платят за машину, повреждённую водой или упавшим деревом. Страховка дома от наводнения автомобили тоже не покрывает.' },
        { q: 'Можете проверить мой нынешний полис?', a: 'Да. Пришлите фото первой страницы полиса (declarations page) в WhatsApp или SMS либо принесите его в наш офис во Florida City. Лицензированный агент разберёт его вместе с вами и покажет пробелы. Проверка бесплатная.' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
