import type { CityPage } from './types';
import { sources } from './sources';

// /[lang]/car-insurance-kendall-fl. Local facts checked 2026-10-03 (see sources).
const SRC = ['flhsmv', 'pip', 'pip2026', 'um', 'iiiUm', 'hb837', 'turnpike', 'metroExpress', 'acsKendall'] as const;

export const CAR_KENDALL: CityPage = {
  path: '/car-insurance-kendall-fl',
  line: 'auto',
  kind: 'city',
  area: 'kendall',
  parent: '/car-insurance-miami-dade-county-fl',
  heroImage: 'auto-12',
  published: '2026-10-03',
  modified: '2026-10-03',
  areaServed: [
    { '@type': 'Place', name: 'Kendall, FL' },
    { '@type': 'AdministrativeArea', name: 'Miami-Dade County, FL' },
  ],
  copy: {
    en: {
      metaTitle: 'Car Insurance in Kendall, FL | Local Agent | M&K Agency',
      metaDesc: 'Car insurance for Kendall: Kendall Drive, the Don Shula and Snapper Creek expressways, Florida PIP rules, uninsured motorist coverage and a free policy review.',
      breadcrumb: 'Kendall',
      kicker: 'Auto insurance · Kendall, FL',
      h1a: 'Car insurance in Kendall, FL,',
      h1b: 'for busy roads and busier schedules.',
      sub: 'Kendall Drive at rush hour, Dadeland parking garages, expressway tolls. We read your policy with you, point out the gaps and help you when you have a claim. English, Spanish or Russian.',
      serviceType: 'Auto insurance',
      intro: [
        { type: 'h2', text: 'Kendall traffic is dense, not just long' },
        { type: 'p', text: 'Kendall is one of the largest unincorporated communities in Miami-Dade, with about 80,000 residents at the 2020 Census. It is not a city with its own police department or city hall; Miami-Dade County provides local government. What defines driving here is density: shopping centers, schools, hospitals and apartment complexes along wide arterial roads, with traffic moving all day, not only at rush hour. The average commute for Kendall residents is about 30 minutes, close to the county average, but much of it is stop-and-go.' },
        { type: 'p', text: 'The main corridors are well known. **Kendall Drive (SW 88th Street, SR 94)** is the east–west spine, from US-1 at Dadeland out past the Turnpike. **US-1 (South Dixie Highway)** forms the eastern edge, with Dadeland Mall and the Dadeland North and Dadeland South Metrorail stations. Since October 2025, Dadeland South is also the northern end of the Metro Express buses that run the South Dade TransitWay to Florida City. Two tolled expressways cross the area: the **Don Shula Expressway (SR 874)** and the **Snapper Creek Expressway (SR 878)**. On the west side, **Florida’s Turnpike (SR 821)** has exits at SR 874, SW 120th Street and Kendall Drive.' },
        { type: 'p', text: 'More than four in ten Kendall homes are in buildings with two or more units, and about a third are in buildings with ten or more. That means a lot of cars parked in shared lots and garages, a lot of pedestrians near stations and shopping centers, and a lot of renters, who often carry only the legal minimum on their cars.' },
      ],
      checklistTitle: 'Coverage gaps we check on Kendall auto policies',
      checklist: [
        '**Bodily injury liability:** in heavy traffic, one rear-end chain collision can injure several people. Florida does not require BI for most drivers, so many people simply do not have it.',
        '**Uninsured motorist coverage at the same limits as BI**, and a check for any old rejection form you signed.',
        '**Comprehensive for parked cars:** hail, a falling tree, vandalism or a flooded garage are not collision claims.',
        '**Collision with a deductible you can cover**, because parking-garage scrapes and low-speed crashes are the most common claims in dense areas.',
        '**Medical payments coverage** on top of PIP, which pays only 80% of medical bills.',
        '**Rental reimbursement**, especially if you have one car and no easy transit to work.',
        '**Toll and work use:** if you drive for a delivery app or rideshare, your personal policy may not cover you while you are working.',
        '**Everyone in the household with a license listed**, including adult children and relatives who moved in.',
        '**Umbrella liability** if you own a home or have savings to protect.',
      ],
      body: [
        { type: 'h2', text: 'Florida’s rules, from a Kendall point of view' },
        { type: 'p', text: 'Florida requires **$10,000 of Personal Injury Protection (PIP)** and **$10,000 of Property Damage Liability (PDL)** on every registered car, without lapses. PIP is no-fault and pays 80% of reasonable medical expenses and 60% of lost income. Something many Kendall residents do not know: PIP generally also protects you and the relatives in your household **as pedestrians or cyclists** if a car hits you, which matters in a neighborhood with busy crosswalks near Metrorail and shopping centers. The rules are strict, though: initial treatment within 14 days, and a $2,500 cap unless a doctor finds an emergency medical condition. Bills to repeal PIP died in committee in March 2026, so the system stays in place for now.' },
        { type: 'p', text: 'Florida does not require most drivers to carry bodily injury liability. The Insurance Research Council estimated that about 20.6% of Florida drivers were uninsured in 2023, roughly one in five. When an uninsured or underinsured driver hurts you, **uninsured motorist coverage (UM)** is what pays for your injuries beyond PIP. Florida insurers must offer UM at your BI limits, and it can only be lowered or rejected in writing. If you have two or more cars, ask about stacking.' },
        { type: 'p', text: 'Fault matters more since March 24, 2023. Under Florida’s modified comparative negligence rule, a driver found more than 50% responsible for their own injuries generally recovers nothing from the other side, and most negligence claims now have a two-year deadline instead of four. In stop-and-go traffic, fault is often disputed, so good documentation and your own coverage both matter.' },
        { type: 'h2', text: 'Storms, garages and flooded streets' },
        { type: 'p', text: 'Hurricane Andrew’s worst damage in 1992 reached from the Kendall area south through Homestead and Florida City. Today the more common problem is heavy rain that floods low parking lots and underground garages. Only comprehensive coverage pays for water-damaged cars, and insurers can stop accepting changes once a storm is threatening.' },
        { type: 'h2', text: 'Why Kendall clients work with us' },
        { type: 'p', text: 'M&K Agency is a family-owned agency with a team of 12 and more than 5,000 clients across Florida. **Send us your policy and we’ll check your coverage.** A licensed agent will explain the gaps in plain language, in English, Spanish or Russian, and when you have a claim you will have a person to call who knows your file.' },
      ],
      officeTitle: 'Serving Kendall from Florida City',
      office: [
        { type: 'p', text: 'We do not have an office in Kendall. We serve Kendall from our office at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, about 20 miles away. In light traffic the drive is roughly 26 to 30 minutes via the Don Shula Expressway and the Turnpike, longer at rush hour. That is why most Kendall clients never visit: we handle quotes, reviews, changes and claims by phone, WhatsApp, text and email.' },
        { type: 'p', text: 'Office hours are Monday to Friday, 9 to 6, and Saturday by appointment. Call (305) 859-3953 or WhatsApp (971) 998-7313. Requests received during business hours get a call back from an agent within an hour.' },
      ],
      faqTitle: 'Car insurance in Kendall: common questions',
      faq: [
        { q: 'Does PIP cover me if I am hit by a car while walking in Kendall?', a: 'In general, yes. Florida PIP covers the named insured and resident relatives who are struck by a motor vehicle as pedestrians or cyclists, subject to the same 80% medical, 60% lost income and 14-day rules. Your agent can confirm the details of your policy.' },
        { q: 'I rent an apartment in Kendall. Do I need more than the minimum car insurance?', a: 'The law only requires PIP and property damage liability. But if you injure someone, the minimum does not include bodily injury liability, and if someone uninsured injures you, PIP pays only part of your costs. Adding BI and UM is how you protect yourself and your income.' },
        { q: 'My car was damaged in a parking garage. Which coverage pays?', a: 'If another car hit it and the driver is known, their property damage liability should pay. If the driver left, or the damage came from a falling object, flooding or vandalism, you need your own collision or comprehensive coverage.' },
        { q: 'Is uninsured motorist coverage required in Florida?', a: 'It is not required, but insurers must offer it with bodily injury liability, at the same limits, and you can only reject it in writing. Without BI you generally cannot buy UM.' },
        { q: 'Kendall is far from your office. Can you still help me?', a: 'Yes. Most of our Kendall clients never come in. We review policies sent by WhatsApp or email, call you back within an hour during business hours, and help with claims by phone.' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Seguro de Auto en Kendall, FL | Agente Local | M&K Agency',
      metaDesc: 'Seguro de auto en Kendall: Kendall Drive, las autopistas Don Shula y Snapper Creek, el PIP en Florida, conductor sin seguro y revisión gratis de su póliza.',
      breadcrumb: 'Kendall',
      kicker: 'Seguro de auto · Kendall, FL',
      h1a: 'Seguro de auto en Kendall, FL,',
      h1b: 'para calles llenas y días ocupados.',
      sub: 'La Kendall Drive en hora pico, los garajes de Dadeland, los peajes de las autopistas. Leemos su póliza con usted, le señalamos lo que falta y le ayudamos cuando tiene un reclamo. En español, inglés o ruso.',
      serviceType: 'Seguro de auto',
      intro: [
        { type: 'h2', text: 'En Kendall el tráfico no es solo largo: es denso' },
        { type: 'p', text: 'Kendall es una de las comunidades no incorporadas más grandes de Miami-Dade, con unos 80,000 habitantes en el Censo de 2020. No es una ciudad con su propia alcaldía ni su propia policía; el gobierno local lo ejerce el Condado de Miami-Dade. Lo que marca la manera de manejar aquí es la densidad: centros comerciales, escuelas, hospitales y complejos de apartamentos a lo largo de avenidas anchas, con tráfico a toda hora y no solo en hora pico. El viaje promedio al trabajo ronda los 30 minutos, parecido al del condado, pero gran parte es de arranca y para.' },
        { type: 'p', text: 'Las vías principales las conoce todo el mundo. La **Kendall Drive (SW 88 Street, SR 94)** es el eje este–oeste, desde la US-1 en Dadeland hasta más allá del Turnpike. La **US-1 (South Dixie Highway)** marca el borde este, con Dadeland Mall y las estaciones de Metrorail Dadeland North y Dadeland South. Desde octubre de 2025, Dadeland South es además la terminal norte del Metro Express que recorre el South Dade TransitWay hasta Florida City. Dos autopistas de peaje atraviesan la zona: la **Don Shula Expressway (SR 874)** y la **Snapper Creek Expressway (SR 878)**. Al oeste, el **Turnpike (SR 821)** tiene salidas en la SR 874, la SW 120 Street y la Kendall Drive.' },
        { type: 'p', text: 'Más de cuatro de cada diez viviendas en Kendall están en edificios de dos o más unidades, y cerca de un tercio en edificios de diez o más. Eso significa muchos carros en estacionamientos y garajes compartidos, mucha gente caminando cerca de las estaciones y los centros comerciales, y muchos inquilinos, que con frecuencia solo llevan el mínimo que pide la ley.' },
      ],
      checklistTitle: 'Lo que revisamos en las pólizas de auto de Kendall',
      checklist: [
        '**Responsabilidad por lesiones (BI):** en tráfico pesado, un choque en cadena puede lesionar a varias personas. Florida no la exige a la mayoría, así que mucha gente sencillamente no la tiene.',
        '**Conductor sin seguro (UM) con los mismos límites que la BI**, y revisar si alguna vez firmó un rechazo.',
        '**Cobertura integral para el carro estacionado:** granizo, un árbol, vandalismo o un garaje inundado no son reclamos de choque.',
        '**Choque (collision) con un deducible que pueda pagar**, porque los raspones en garajes y los golpes a baja velocidad son los reclamos más comunes en zonas densas.',
        '**Pagos médicos (MedPay)** además del PIP, que solo paga el 80% de las facturas médicas.',
        '**Carro de alquiler**, sobre todo si tiene un solo carro y no le queda fácil el transporte público.',
        '**Uso para trabajar:** si maneja para una app de entregas o de viajes, su póliza personal puede no cubrirle mientras trabaja.',
        '**Todas las personas con licencia que viven en la casa**, incluidos hijos adultos y familiares que se mudaron con usted.',
        '**Póliza paraguas (umbrella)** si tiene casa propia o ahorros que proteger.',
      ],
      body: [
        { type: 'h2', text: 'Las reglas de Florida, vistas desde Kendall' },
        { type: 'p', text: 'Florida exige **$10,000 de Protección contra Lesiones Personales (PIP)** y **$10,000 de Responsabilidad por Daños a la Propiedad (PDL)** en todo carro registrado, sin interrupciones. El PIP es “sin culpa” y paga el 80% de los gastos médicos razonables y el 60% del ingreso perdido. Algo que muchos en Kendall no saben: por lo general el PIP también le protege a usted y a sus familiares que viven en la casa **como peatones o ciclistas** si un carro los atropella, algo importante en una zona con cruces peatonales concurridos cerca del Metrorail y los centros comerciales. Las condiciones son estrictas: primera atención dentro de 14 días y un tope de $2,500 si un médico no determina una condición de emergencia. Los proyectos para eliminar el PIP murieron en comité en marzo de 2026, así que el sistema sigue igual por ahora.' },
        { type: 'p', text: 'Florida no exige a la mayoría de los conductores la responsabilidad por lesiones corporales. El Insurance Research Council estimó que en 2023 cerca del 20.6% de los conductores de Florida no tenía seguro, más o menos uno de cada cinco. Cuando un conductor sin seguro o con poco seguro le lesiona, lo que paga sus lesiones más allá del PIP es la **cobertura de conductor sin seguro (UM)**. La aseguradora debe ofrecérsela con los límites de su BI, y solo se puede bajar o rechazar por escrito. Si tiene dos carros o más, pregunte por la opción acumulable.' },
        { type: 'p', text: 'La culpa pesa más desde el 24 de marzo de 2023. Con la regla de negligencia comparativa modificada, el conductor que resulta responsable en más del 50% de sus propias lesiones en general no le cobra nada a la otra parte, y la mayoría de los reclamos por negligencia tienen ahora un plazo de dos años en vez de cuatro. En el tráfico de arranca y para, la culpa se discute a menudo, así que documentar bien y tener buena cobertura propia son igual de importantes.' },
        { type: 'h2', text: 'Tormentas, garajes y calles inundadas' },
        { type: 'p', text: 'En 1992, los peores daños del huracán Andrew se extendieron desde la zona de Kendall hacia el sur, hasta Homestead y Florida City. Hoy el problema más frecuente son los aguaceros que inundan estacionamientos bajos y garajes subterráneos. Solo la cobertura integral paga un carro dañado por agua, y las aseguradoras pueden dejar de aceptar cambios cuando ya amenaza una tormenta.' },
        { type: 'h2', text: 'Por qué nuestros clientes de Kendall trabajan con nosotros' },
        { type: 'p', text: 'M&K Agency es una agencia familiar con un equipo de 12 personas y más de 5,000 clientes en toda Florida. **Envíenos su póliza y la revisamos.** Un agente licenciado le explica lo que le falta en palabras sencillas, en español, inglés o ruso, y cuando tenga un reclamo tendrá a alguien a quien llamar que ya conoce su caso.' },
      ],
      officeTitle: 'Atendemos Kendall desde Florida City',
      office: [
        { type: 'p', text: 'No tenemos oficina en Kendall. Atendemos a Kendall desde nuestra oficina en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, a unas 20 millas. Sin tráfico son de 26 a 30 minutos por la Don Shula Expressway y el Turnpike; en hora pico, más. Por eso la mayoría de nuestros clientes de Kendall nunca viene: hacemos cotizaciones, revisiones, cambios y reclamos por teléfono, WhatsApp, texto y correo.' },
        { type: 'p', text: 'Horario: lunes a viernes de 9 a 6, sábados con cita. Llame al (305) 859-3953 o escriba por WhatsApp al (971) 998-7313. Las solicitudes que llegan en horario de oficina reciben la llamada de un agente en menos de una hora.' },
      ],
      faqTitle: 'Seguro de auto en Kendall: preguntas frecuentes',
      faq: [
        { q: '¿El PIP me cubre si me atropella un carro caminando en Kendall?', a: 'Por lo general, sí. El PIP de Florida cubre al asegurado y a los familiares que viven con él si un vehículo los atropella como peatones o ciclistas, con las mismas reglas del 80% médico, 60% de ingresos y 14 días. Su agente puede confirmarle los detalles de su póliza.' },
        { q: 'Alquilo un apartamento en Kendall. ¿Necesito más que el seguro mínimo?', a: 'La ley solo exige PIP y daños a la propiedad. Pero el mínimo no incluye responsabilidad por lesiones si usted lesiona a alguien, y si alguien sin seguro le lesiona a usted, el PIP paga solo una parte. Agregar BI y UM es la forma de protegerse usted y proteger su ingreso.' },
        { q: 'Me dañaron el carro en un garaje. ¿Qué cobertura paga?', a: 'Si lo chocó otro carro y se sabe quién fue, debería pagar la cobertura de daños a la propiedad de ese conductor. Si el conductor se fue, o el daño fue por un objeto que cayó, inundación o vandalismo, necesita su propia cobertura de choque o integral.' },
        { q: '¿Es obligatoria la cobertura de conductor sin seguro en Florida?', a: 'No es obligatoria, pero la aseguradora tiene que ofrecerla junto con la responsabilidad por lesiones, con los mismos límites, y solo se puede rechazar por escrito. Sin BI, normalmente no se puede comprar UM.' },
        { q: 'Kendall queda lejos de su oficina. ¿Igual me pueden ayudar?', a: 'Sí. La mayoría de nuestros clientes de Kendall nunca viene a la oficina. Revisamos las pólizas que nos envían por WhatsApp o correo, le devolvemos la llamada en menos de una hora en horario de oficina y le ayudamos con los reclamos por teléfono.' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Автостраховка в Kendall, FL | Местный агент | M&K Agency',
      metaDesc: 'Автостраховка в Kendall: Kendall Drive, платные Don Shula и Snapper Creek, PIP во Флориде, защита от незастрахованных водителей и бесплатная проверка полиса.',
      breadcrumb: 'Kendall',
      kicker: 'Автостраховка · Kendall, FL',
      h1a: 'Автостраховка в Kendall, FL —',
      h1b: 'для плотного трафика и насыщенных дней.',
      sub: 'Kendall Drive в час пик, гаражи у Dadeland, платные экспрессвеи. Прочитаем ваш полис вместе с вами, покажем пробелы и поможем, когда понадобится клейм. По-русски, по-английски или по-испански.',
      serviceType: 'Автострахование',
      intro: [
        { type: 'h2', text: 'В Kendall трафик не столько длинный, сколько плотный' },
        { type: 'p', text: 'Kendall — одно из крупнейших неинкорпорированных сообществ Miami-Dade: по переписи 2020 года здесь жило около 80,000 человек. Это не город со своей мэрией и полицией — местной властью здесь выступает сам округ Miami-Dade. Езду здесь определяет плотность: торговые центры, школы, больницы и жилые комплексы вдоль широких магистралей, и движение не стихает весь день, а не только в часы пик. Дорога на работу в среднем занимает около 30 минут — примерно как по округу, — но большая часть этого времени уходит на «стоп-старт».' },
        { type: 'p', text: 'Главные дороги известны всем. **Kendall Drive (SW 88th Street, SR 94)** — основная ось с востока на запад, от US-1 у Dadeland и дальше за Turnpike. **US-1 (South Dixie Highway)** проходит по восточному краю, где находятся Dadeland Mall и станции Metrorail Dadeland North и Dadeland South. С октября 2025 года Dadeland South — ещё и северная конечная автобусов Metro Express, которые идут по South Dade TransitWay до Florida City. Район пересекают два платных экспрессвея — **Don Shula Expressway (SR 874)** и **Snapper Creek Expressway (SR 878)**. На западе у **Turnpike (SR 821)** есть съезды на SR 874, SW 120th Street и Kendall Drive.' },
        { type: 'p', text: 'Больше 40% жилья в Kendall — в зданиях на две квартиры и больше, а около трети — в домах на десять и более квартир. Значит, много машин на общих парковках и в гаражах, много пешеходов у станций и торговых центров и много арендаторов, которые часто страхуют машину только по закону, на минимум.' },
      ],
      checklistTitle: 'Какие пробелы мы ищем в автополисах Kendall',
      checklist: [
        '**Bodily injury liability (BI):** в плотном потоке одна цепная авария может травмировать сразу нескольких человек. Для большинства BI во Флориде не обязательна, и у многих её просто нет.',
        '**UM с теми же лимитами, что и BI**, плюс проверка, не подписывали ли вы когда-то отказ.',
        '**Comprehensive для припаркованной машины:** град, упавшее дерево, вандализм или затопленный гараж — это не collision.',
        '**Collision с франшизой, которую вы потянете**: царапины в гаражах и столкновения на малой скорости — самые частые клеймы в плотных районах.',
        '**Medical payments (MedPay)** в дополнение к PIP, который оплачивает только 80% медицинских счетов.',
        '**Аренда машины на время ремонта**, особенно если машина одна, а общественным транспортом до работы неудобно.',
        '**Работа за рулём:** если вы ездите на доставку или в такси через приложение, личный полис может не действовать, пока вы работаете.',
        '**Все члены семьи с правами вписаны**, включая взрослых детей и родственников, которые переехали к вам.',
        '**Umbrella liability**, если у вас есть дом или сбережения, которые нужно защитить.',
      ],
      body: [
        { type: 'h2', text: 'Правила Флориды — применительно к Kendall' },
        { type: 'p', text: 'Флорида требует на каждой зарегистрированной машине **$10,000 PIP** и **$10,000 PDL** без перерывов. PIP работает по принципу no-fault: 80% разумных медицинских расходов и 60% потерянного дохода. Многие в Kendall не знают, что PIP, как правило, защищает вас и живущих с вами родственников и **когда вы пешеход или велосипедист**, если вас сбила машина. В районе с оживлёнными переходами у Metrorail и торговых центров это важно. Но условия строгие: к врачу — в течение 14 дней, а без заключения о состоянии, требующем неотложной помощи, лимит — $2,500. Законопроекты об отмене PIP не прошли комитеты в марте 2026 года, так что пока система остаётся прежней.' },
        { type: 'p', text: 'Большинство водителей во Флориде не обязаны иметь bodily injury liability. По оценке Insurance Research Council, в 2023 году около 20.6% водителей штата ездили без страховки — примерно каждый пятый. Если вас травмировал водитель без страховки или с маленькими лимитами, сверх PIP ваши расходы покрывает **UM (uninsured motorist)**. Страховая обязана предложить UM с лимитами вашей BI, а уменьшить её или отказаться можно только письменно. Если машин две и больше, спросите про stacked UM.' },
        { type: 'p', text: 'С 24 марта 2023 года вина значит больше. По правилу модифицированной сравнительной вины водитель, который сам виноват в своих травмах больше чем на 50%, как правило, ничего не получает с другой стороны, а срок для большинства исков о небрежности теперь два года вместо четырёх. В пробках вину часто оспаривают, поэтому важны и хорошие доказательства, и собственная страховка.' },
        { type: 'h2', text: 'Штормы, гаражи и затопленные улицы' },
        { type: 'p', text: 'В 1992 году самые тяжёлые разрушения от урагана Andrew протянулись от района Kendall на юг, до Homestead и Florida City. Сегодня чаще другая беда — ливни, которые заливают низкие парковки и подземные гаражи. За машину, повреждённую водой, платит только comprehensive, а когда шторм уже угрожает, страховые могут перестать принимать изменения.' },
        { type: 'h2', text: 'Почему клиенты из Kendall работают с нами' },
        { type: 'p', text: 'M&K Agency — семейное агентство: 12 человек в команде и более 5,000 клиентов по всей Флориде. **Пришлите нам свой полис — мы проверим покрытие.** Лицензированный агент простыми словами объяснит, где пробелы, — по-русски, по-английски или по-испански, — а когда случится клейм, вам будет кому позвонить: человеку, который знает ваш полис.' },
      ],
      officeTitle: 'Обслуживаем Kendall из Florida City',
      office: [
        { type: 'p', text: 'Офиса в Kendall у нас нет: мы обслуживаем Kendall из офиса по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, примерно в 20 милях. Без пробок дорога занимает 26–30 минут по Don Shula Expressway и Turnpike, в час пик — дольше. Поэтому большинство клиентов из Kendall к нам вообще не приезжают: расчёты, проверки, изменения и клеймы мы ведём по телефону, в WhatsApp, по SMS и почте.' },
        { type: 'p', text: 'Часы работы: понедельник–пятница с 9 до 6, суббота — по записи. Звоните (305) 859-3953 или пишите в WhatsApp: (971) 998-7313. На заявки в рабочее время агент перезванивает в течение часа.' },
      ],
      faqTitle: 'Автостраховка в Kendall: частые вопросы',
      faq: [
        { q: 'Покрывает ли PIP, если меня сбила машина, когда я шёл пешком?', a: 'Как правило, да. PIP во Флориде покрывает владельца полиса и живущих с ним родственников, если их сбил автомобиль, когда они были пешеходами или велосипедистами, — на тех же условиях: 80% лечения, 60% дохода, правило 14 дней. Детали вашего полиса подтвердит агент.' },
        { q: 'Я снимаю квартиру в Kendall. Нужно ли мне больше минимальной страховки?', a: 'Закон требует только PIP и PDL. Но в минимум не входит bodily injury liability на случай, если вы кого-то травмируете, а если вас травмирует водитель без страховки, PIP покроет только часть расходов. Добавив BI и UM, вы защищаете себя и свой доход.' },
        { q: 'Машину повредили в гараже. Какое покрытие платит?', a: 'Если в неё въехала другая машина и водитель известен, платить должна его property damage liability. Если водитель уехал или ущерб нанесли упавший предмет, вода или вандалы, нужна ваша собственная collision или comprehensive.' },
        { q: 'Обязательна ли UM во Флориде?', a: 'Не обязательна, но страховая должна предложить её вместе с bodily injury liability и с теми же лимитами, а отказаться можно только письменно. Без BI купить UM, как правило, нельзя.' },
        { q: 'Kendall далеко от вашего офиса. Вы всё равно сможете помочь?', a: 'Да. Большинство наших клиентов из Kendall в офис не приезжают. Мы проверяем полисы, присланные в WhatsApp или по почте, перезваниваем в течение часа в рабочее время и помогаем с клеймами по телефону.' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
