import type { CityPage } from './types';
import { sources } from './sources';

// /[lang]/car-insurance-miami-dade-county-fl (county hub). Facts checked 2026-10-03.
const SRC = ['flhsmv', 'pip', 'pip2026', 'um', 'iiiUm', 'hb837', 'crashReport', 'turnpike', 'metroExpress', 'acsMiamiDade'] as const;

export const CAR_MIAMI_DADE: CityPage = {
  path: '/car-insurance-miami-dade-county-fl',
  line: 'auto',
  kind: 'county',
  area: 'miami-dade',
  heroImage: 'legacy-sunset-highway',
  published: '2026-10-03',
  modified: '2026-10-03',
  served: [
    { name: 'Florida City', path: '/car-insurance-florida-city' },
    { name: 'Homestead', path: '/car-insurance-homestead-fl' },
    { name: 'Cutler Bay', path: '/car-insurance-cutler-bay-fl' },
    { name: 'Kendall', path: '/car-insurance-kendall-fl' },
    { name: 'Palmetto Bay' }, { name: 'Pinecrest' }, { name: 'South Miami' }, { name: 'Coral Gables' },
    { name: 'Miami' }, { name: 'Doral' }, { name: 'Hialeah' }, { name: 'Miami Beach' },
    { name: 'North Miami' }, { name: 'Aventura' }, { name: 'Sunny Isles Beach' },
    { name: 'Redland, Leisure City, Naranja and Princeton' },
  ],
  areaServed: [
    { '@type': 'AdministrativeArea', name: 'Miami-Dade County, FL' },
  ],
  copy: {
    en: {
      metaTitle: 'Car Insurance in Miami-Dade County, FL | M&K Agency',
      metaDesc: 'Car insurance in Miami-Dade: I-95, the Palmetto, the Turnpike and US-1, Florida PIP and uninsured motorist rules, steps after a crash and a free policy review.',
      breadcrumb: 'Miami-Dade County',
      kicker: 'Auto insurance · Miami-Dade County',
      h1a: 'Car insurance in Miami-Dade County,',
      h1b: 'from the Keys road to the Broward line.',
      sub: 'A local, family-owned agency in South Dade that works with drivers across the county. We check your policy for gaps, explain Florida’s rules in plain words and help you when you have a claim. English, Spanish or Russian.',
      serviceType: 'Auto insurance',
      intro: [
        { type: 'h2', text: 'Driving in a county of 2.7 million people' },
        { type: 'p', text: 'Miami-Dade had about 2.7 million residents at the 2020 Census, more than any other county in Florida, and most of them depend on a car. The average commute is about 31 minutes each way, but averages hide how different the county is from end to end: a resident of Homestead or Cutler Bay usually drives farther than someone in Kendall, while drivers in Miami, Hialeah and Doral deal with shorter but denser trips.' },
        { type: 'p', text: 'A handful of corridors carry most of that traffic. **I-95** runs north from its southern end at US-1 near Brickell, through downtown and into Broward, with tolled 95 Express lanes whose prices change with traffic. **The Palmetto Expressway (SR 826)** loops through the western suburbs, and **the Dolphin Expressway (SR 836)** links the airport area and downtown. **Florida’s Turnpike** has two arms here: the mainline toward Broward and the **Homestead Extension (SR 821)**, which runs south through Kendall and Cutler Bay to its end at US-1 in Florida City. **US-1** itself crosses the whole county, from the Keys road in Florida City up through South Dixie Highway, Brickell and Biscayne Boulevard to Aventura. Most tolls in the county are electronic, so a SunPass or toll-by-plate bill is part of everyday driving.' },
        { type: 'p', text: 'Public transit is changing the south end of the county as well. Since October 27, 2025, Metro Express bus rapid transit has run 20 miles on the South Dade TransitWay, from Florida City to the Dadeland South Metrorail station, with gate arms and signal priority at intersections. Drivers who cross the busway need to treat it with the same care as a rail line.' },
      ],
      checklistTitle: 'Coverage gaps we see most often in Miami-Dade',
      checklist: [
        '**No bodily injury liability.** It is optional for most Florida drivers, so many policies in the county have none.',
        '**Uninsured motorist coverage rejected or set below BI limits**, often on a form signed years ago.',
        '**Non-stacked UM** on a household with several cars, without anyone explaining the difference.',
        '**No comprehensive** on an older car, leaving no coverage for flooding, theft or a falling tree.',
        '**Drivers missing from the policy**, such as adult children or relatives who live in the home.',
        '**The wrong garaging address** after a move within the county.',
        '**Personal policies used for delivery or rideshare work** without the right endorsement.',
        '**No rental reimbursement** for families who depend on one car.',
        '**Low liability limits for someone who owns a home**, with no umbrella policy.',
      ],
      body: [
        { type: 'h2', text: 'Florida’s rules, in short' },
        { type: 'p', text: 'Every car registered in Florida needs **$10,000 of PIP** and **$10,000 of property damage liability**, without lapses. PIP pays 80% of reasonable medical bills and 60% of lost income for you and your household after a crash, regardless of fault, if you get initial care within 14 days; without a finding of an emergency medical condition, it is capped at $2,500. Lawmakers again filed bills in 2026 to repeal PIP, and they died in committee in March, so these rules still apply.' },
        { type: 'p', text: '**Bodily injury liability is not required for most drivers.** The Insurance Research Council estimated that about 20.6% of Florida drivers were uninsured in 2023, the seventh-highest rate in the country, against a national rate of about 15.4%. That is why uninsured motorist coverage matters. Insurers must offer UM at your BI limits, it can only be rejected or reduced in writing, and it also applies when the other driver has too little insurance. Since March 24, 2023, a person found more than 50% at fault for their own injuries generally cannot recover from the other driver, and most negligence lawsuits must be filed within two years.' },
        { type: 'h2', text: 'After a crash anywhere in the county' },
        { type: 'ul', items: [
          'Check for injuries and call 911 if anyone is hurt. Florida law requires drivers to report crashes involving injury or death, or apparent damage of at least $2,000, to the police, the sheriff or the Florida Highway Patrol.',
          'Exchange names, license numbers, plates and insurance information, and photograph the cars, the scene and the other driver’s documents.',
          'See a doctor within 14 days, even if you feel fine, so you do not lose PIP benefits.',
          'Report the claim to your insurer promptly, and call your agent. We can help you understand what your policy covers and what to expect.',
        ] },
        { type: 'h2', text: 'Hurricane season' },
        { type: 'p', text: 'Storm surge, street flooding and falling trees damage thousands of cars in a bad season. Only comprehensive coverage pays for them, and insurers commonly stop accepting new coverage or changes once a storm threatens. Review your policy before June 1.' },
        { type: 'p', text: 'M&K Agency is a family-owned agency with a team of 12 and more than 5,000 clients across Florida. **Send us your policy and we’ll check your coverage.** A licensed agent will go through it with you, in English, Spanish or Russian, and you will have a person to call when you need to use it.' },
      ],
      officeTitle: 'One office in South Dade, clients across the county',
      office: [
        { type: 'p', text: 'Our office is at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, at the southern end of the Turnpike. In light traffic it is about five minutes from downtown Homestead, about 20 minutes from Cutler Bay, roughly half an hour from Kendall and around 50 minutes from downtown Miami, longer at rush hour. We do not have other offices in the county, so most clients north of Kendall work with us by phone, WhatsApp, text and email, and visit by appointment when they want to.' },
        { type: 'p', text: 'Hours are Monday to Friday, 9 to 6, and Saturday by appointment. Call (305) 859-3953 or WhatsApp (971) 998-7313. An agent calls back within an hour on requests received during business hours.' },
      ],
      faqTitle: 'Car insurance in Miami-Dade County: common questions',
      faq: [
        { q: 'What is the minimum car insurance in Miami-Dade County?', a: 'The same as everywhere in Florida: $10,000 of personal injury protection and $10,000 of property damage liability. Bodily injury liability is not required for most drivers, but without it you cannot carry uninsured motorist coverage.' },
        { q: 'Do I have to call the police after a minor crash?', a: 'Florida law requires drivers to report crashes that cause injury or death or apparent damage of at least $2,000. Even when a report is not required, photos and the other driver’s information make the claim much easier.' },
        { q: 'Why is uninsured motorist coverage so important here?', a: 'The Insurance Research Council estimated that about one in five Florida drivers was uninsured in 2023. UM pays for your injuries and your passengers’ injuries when the at-fault driver has no insurance or too little.' },
        { q: 'Do you only work with drivers in South Dade?', a: 'No. Our office is in Florida City, but we work with drivers throughout Miami-Dade, and across Florida, by phone, WhatsApp, text and email.' },
        { q: 'Can you check my current policy before I renew?', a: 'Yes. Send a photo of your declarations page by WhatsApp or text. A licensed agent will review it and explain any gaps, at no cost.' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Seguro de Auto en el Condado Miami-Dade, FL | M&K Agency',
      metaDesc: 'Seguro de auto en Miami-Dade: I-95, el Palmetto, el Turnpike y la US-1, reglas de PIP y conductor sin seguro, qué hacer tras un choque y revisión gratis.',
      breadcrumb: 'Condado Miami-Dade',
      kicker: 'Seguro de auto · Condado Miami-Dade',
      h1a: 'Seguro de auto en el Condado Miami-Dade,',
      h1b: 'desde la ruta a los Cayos hasta Broward.',
      sub: 'Una agencia local y familiar en el sur de Miami-Dade que trabaja con conductores de todo el condado. Revisamos su póliza, le explicamos las reglas de Florida sin complicaciones y le ayudamos cuando tiene un reclamo. En español, inglés o ruso.',
      serviceType: 'Seguro de auto',
      intro: [
        { type: 'h2', text: 'Manejar en un condado de 2.7 millones de personas' },
        { type: 'p', text: 'Miami-Dade tenía unos 2.7 millones de habitantes en el Censo de 2020, más que cualquier otro condado de Florida, y casi todos dependen del carro. El viaje promedio al trabajo es de unos 31 minutos, pero el promedio esconde lo distinto que es el condado de punta a punta: quien vive en Homestead o Cutler Bay suele manejar más que quien vive en Kendall, mientras que en Miami, Hialeah y Doral los viajes son más cortos pero más congestionados.' },
        { type: 'p', text: 'Unas pocas vías llevan casi todo el tráfico. La **I-95** sube desde su extremo sur en la US-1, cerca de Brickell, pasa por el downtown y entra en Broward, con los carriles 95 Express de peaje, cuyo precio cambia según el tráfico. El **Palmetto Expressway (SR 826)** rodea los suburbios del oeste, y el **Dolphin Expressway (SR 836)** une la zona del aeropuerto con el downtown. El **Turnpike** tiene dos brazos aquí: la línea principal hacia Broward y la **Extensión Homestead (SR 821)**, que baja por Kendall y Cutler Bay hasta terminar en la US-1 en Florida City. Y la **US-1** atraviesa todo el condado, desde la salida a los Cayos en Florida City, por la South Dixie Highway, Brickell y Biscayne Boulevard, hasta Aventura. Casi todos los peajes del condado son electrónicos, así que el SunPass o la factura de toll-by-plate son parte del día a día.' },
        { type: 'p', text: 'El transporte público también está cambiando el sur del condado. Desde el 27 de octubre de 2025, el Metro Express recorre 20 millas por el South Dade TransitWay, de Florida City a la estación de Metrorail Dadeland South, con barreras y prioridad en los semáforos. Al cruzar el corredor del bus hay que tener el mismo cuidado que en una vía de tren.' },
      ],
      checklistTitle: 'Los vacíos de cobertura que más vemos en Miami-Dade',
      checklist: [
        '**Sin responsabilidad por lesiones (BI).** Es opcional para la mayoría en Florida, así que muchas pólizas del condado no la tienen.',
        '**Conductor sin seguro (UM) rechazado o por debajo de la BI**, muchas veces en un formulario firmado hace años.',
        '**UM no acumulable** en una casa con varios carros, sin que nadie explicara la diferencia.',
        '**Sin cobertura integral** en un carro viejo, y por lo tanto sin protección contra inundación, robo o un árbol caído.',
        '**Conductores que no aparecen en la póliza**, como hijos adultos o familiares que viven en la casa.',
        '**Dirección equivocada** después de mudarse dentro del condado.',
        '**Pólizas personales usadas para entregas o Uber/Lyft** sin el endoso correcto.',
        '**Sin carro de alquiler** en familias que dependen de un solo carro.',
        '**Límites bajos de responsabilidad para alguien que tiene casa propia**, y sin póliza paraguas.',
      ],
      body: [
        { type: 'h2', text: 'Las reglas de Florida, en resumen' },
        { type: 'p', text: 'Todo carro registrado en Florida necesita **$10,000 de PIP** y **$10,000 de daños a la propiedad (PDL)**, sin interrupciones. Después de un accidente, el PIP paga el 80% de los gastos médicos razonables y el 60% del ingreso perdido para usted y su familia, sin importar la culpa, si recibe la primera atención dentro de 14 días; si no se determina una condición médica de emergencia, el tope es de $2,500. En 2026 se volvió a proponer eliminar el PIP y los proyectos murieron en comité en marzo, así que estas reglas siguen vigentes.' },
        { type: 'p', text: '**La responsabilidad por lesiones no es obligatoria para la mayoría.** El Insurance Research Council estimó que en 2023 cerca del 20.6% de los conductores de Florida no tenía seguro, la séptima tasa más alta del país, frente a un 15.4% a nivel nacional. Por eso importa la cobertura de conductor sin seguro. La aseguradora debe ofrecerla con los límites de su BI, solo se puede rechazar o bajar por escrito y también aplica cuando el otro conductor tiene muy poco seguro. Desde el 24 de marzo de 2023, quien tiene más del 50% de la culpa de sus propias lesiones en general no puede cobrarle al otro conductor, y la mayoría de las demandas por negligencia deben presentarse en dos años.' },
        { type: 'h2', text: 'Después de un choque en cualquier parte del condado' },
        { type: 'ul', items: [
          'Revise si hay heridos y llame al 911 si alguien está lesionado. La ley de Florida obliga a reportar a la policía, al sheriff o a la Patrulla de Carreteras los accidentes con heridos o muertos, o con daños aparentes de $2,000 o más.',
          'Intercambie nombres, números de licencia, placas y datos del seguro, y tome fotos de los carros, del lugar y de los documentos del otro conductor.',
          'Vea a un médico dentro de los 14 días, aunque se sienta bien, para no perder los beneficios del PIP.',
          'Reporte el reclamo a su aseguradora cuanto antes y llame a su agente. Le ayudamos a entender qué cubre su póliza y qué esperar.',
        ] },
        { type: 'h2', text: 'Temporada de huracanes' },
        { type: 'p', text: 'La marejada, las calles inundadas y los árboles caídos dañan miles de carros en una mala temporada. Solo la cobertura integral los paga, y las aseguradoras suelen dejar de aceptar coberturas nuevas o cambios cuando amenaza una tormenta. Revise su póliza antes del 1 de junio.' },
        { type: 'p', text: 'M&K Agency es una agencia familiar con un equipo de 12 personas y más de 5,000 clientes en Florida. **Envíenos su póliza y la revisamos.** Un agente licenciado la repasa con usted, en español, inglés o ruso, y tendrá a una persona a quien llamar cuando la necesite.' },
      ],
      officeTitle: 'Una oficina en el sur de Miami-Dade, clientes en todo el condado',
      office: [
        { type: 'p', text: 'Nuestra oficina está en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, al final del Turnpike. Sin tráfico queda a unos cinco minutos del centro de Homestead, unos 20 de Cutler Bay, cerca de media hora de Kendall y unos 50 minutos del downtown de Miami; en hora pico, más. No tenemos otras oficinas en el condado, así que la mayoría de los clientes al norte de Kendall trabaja con nosotros por teléfono, WhatsApp, texto y correo, y viene con cita cuando lo desea.' },
        { type: 'p', text: 'Horario: lunes a viernes de 9 a 6, sábados con cita. Llame al (305) 859-3953 o escriba por WhatsApp al (971) 998-7313. Un agente le devuelve la llamada en menos de una hora si nos escribe en horario de oficina.' },
      ],
      faqTitle: 'Seguro de auto en el Condado Miami-Dade: preguntas frecuentes',
      faq: [
        { q: '¿Cuál es el seguro mínimo de auto en Miami-Dade?', a: 'El mismo que en toda Florida: $10,000 de protección contra lesiones personales y $10,000 de daños a la propiedad. La responsabilidad por lesiones no es obligatoria para la mayoría, pero sin ella no puede tener cobertura de conductor sin seguro.' },
        { q: '¿Tengo que llamar a la policía después de un choque pequeño?', a: 'La ley de Florida obliga a reportar los accidentes con heridos o muertos o con daños aparentes de al menos $2,000. Aunque no haga falta el reporte, las fotos y los datos del otro conductor facilitan mucho el reclamo.' },
        { q: '¿Por qué es tan importante la cobertura de conductor sin seguro aquí?', a: 'El Insurance Research Council estimó que en 2023 casi uno de cada cinco conductores en Florida no tenía seguro. La UM paga sus lesiones y las de sus pasajeros cuando el culpable no tiene seguro o tiene muy poco.' },
        { q: '¿Solo trabajan con conductores del sur de Miami-Dade?', a: 'No. Nuestra oficina está en Florida City, pero trabajamos con conductores de todo Miami-Dade y de toda Florida por teléfono, WhatsApp, texto y correo.' },
        { q: '¿Pueden revisar mi póliza antes de renovar?', a: 'Sí. Mándenos una foto de la página de declaraciones por WhatsApp o mensaje de texto. Un agente licenciado la revisa y le explica cualquier vacío, sin costo.' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Автостраховка в округе Miami-Dade, FL | M&K Agency',
      metaDesc: 'Автостраховка по всему Miami-Dade: I-95, Palmetto, Turnpike и US-1, правила PIP и UM во Флориде, что делать после ДТП и бесплатная проверка вашего полиса.',
      breadcrumb: 'Округ Miami-Dade',
      kicker: 'Автостраховка · округ Miami-Dade',
      h1a: 'Автостраховка в округе Miami-Dade —',
      h1b: 'от дороги на Keys до границы с Broward.',
      sub: 'Местное семейное агентство на юге Miami-Dade, которое работает с водителями по всему округу. Проверим полис на пробелы, понятно объясним правила Флориды и поможем, когда понадобится клейм. По-русски, по-английски или по-испански.',
      serviceType: 'Автострахование',
      intro: [
        { type: 'h2', text: 'За рулём в округе с населением 2.7 миллиона' },
        { type: 'p', text: 'По переписи 2020 года в Miami-Dade жило около 2.7 миллиона человек — больше, чем в любом другом округе Флориды, и почти все зависят от машины. Средняя дорога на работу — около 31 минуты в одну сторону, но среднее скрывает, насколько разный округ из конца в конец: жители Homestead и Cutler Bay обычно ездят дальше, чем в Kendall, а в Miami, Hialeah и Doral поездки короче, но плотнее.' },
        { type: 'p', text: 'Основной поток идёт по нескольким магистралям. **I-95** начинается на юге у US-1 рядом с Brickell, проходит через даунтаун и уходит в Broward; на ней есть платные полосы 95 Express, цена которых меняется в зависимости от трафика. **Palmetto Expressway (SR 826)** огибает западные пригороды, а **Dolphin Expressway (SR 836)** соединяет район аэропорта с даунтауном. У **Turnpike** здесь две ветки: основная — в сторону Broward — и **Homestead Extension (SR 821)**, которая идёт на юг через Kendall и Cutler Bay и заканчивается на US-1 во Florida City. А **US-1** пересекает весь округ — от выезда на Keys во Florida City через South Dixie Highway, Brickell и Biscayne Boulevard до Aventura. Почти все платные дороги в округе электронные, так что SunPass или счёт toll-by-plate — часть обычной жизни.' },
        { type: 'p', text: 'Меняется и общественный транспорт на юге округа. С 27 октября 2025 года по South Dade TransitWay ходит скоростной автобус Metro Express — 20 миль от Florida City до станции Metrorail Dadeland South, со шлагбаумами и приоритетом на светофорах. Пересекая автобусный коридор, будьте так же внимательны, как на железнодорожном переезде.' },
      ],
      checklistTitle: 'Пробелы в покрытии, которые мы чаще всего видим в Miami-Dade',
      checklist: [
        '**Нет bodily injury liability.** Для большинства водителей Флориды она добровольная, и во многих полисах округа её нет.',
        '**UM отклонена или ниже лимитов BI** — часто по форме, подписанной много лет назад.',
        '**Non-stacked UM** в семье с несколькими машинами, и никто не объяснил разницу.',
        '**Нет comprehensive** на старой машине — а значит, нет защиты от затопления, угона или упавшего дерева.',
        '**В полисе не указаны все водители** — например, взрослые дети или родственники, живущие в доме.',
        '**Неверный адрес стоянки** после переезда внутри округа.',
        '**Личный полис используется для доставки или работы в такси через приложение** без нужного дополнения.',
        '**Нет аренды машины на время ремонта** у семьи с одной машиной.',
        '**Низкие лимиты ответственности у владельца дома** и нет umbrella-полиса.',
      ],
      body: [
        { type: 'h2', text: 'Правила Флориды коротко' },
        { type: 'p', text: 'Каждая машина, зарегистрированная во Флориде, должна иметь **$10,000 PIP** и **$10,000 PDL** без перерывов. После аварии PIP оплачивает 80% разумных медицинских расходов и 60% потерянного дохода вам и семье независимо от вины — если к врачу вы обратились в течение 14 дней; без заключения о состоянии, требующем неотложной помощи, лимит — $2,500. В 2026 году законопроекты об отмене PIP снова внесли, и в марте они не прошли комитеты, так что эти правила действуют.' },
        { type: 'p', text: '**Bodily injury liability для большинства не обязательна.** По оценке Insurance Research Council, в 2023 году около 20.6% водителей Флориды ездили без страховки — седьмой по величине показатель в стране при среднем по США около 15.4%. Поэтому так важна UM. Страховая обязана предложить её с лимитами вашей BI, отказаться или уменьшить лимиты можно только письменно, и она работает также, когда у другого водителя слишком маленькая страховка. С 24 марта 2023 года тот, кто виноват в собственных травмах больше чем на 50%, как правило, не может получить компенсацию с другого водителя, а большинство исков о небрежности нужно подать в течение двух лет.' },
        { type: 'h2', text: 'После ДТП в любой точке округа' },
        { type: 'ul', items: [
          'Проверьте, есть ли пострадавшие, и звоните 911, если кто-то травмирован. По закону Флориды о ДТП с пострадавшими или погибшими либо с видимым ущербом от $2,000 водитель обязан сообщить в полицию, офис шерифа или Florida Highway Patrol.',
          'Обменяйтесь именами, номерами прав, номерными знаками и данными страховки; сфотографируйте машины, место аварии и документы другого водителя.',
          'Обратитесь к врачу в течение 14 дней, даже если чувствуете себя нормально, чтобы не потерять право на PIP.',
          'Сразу сообщите о клейме в страховую и позвоните своему агенту. Мы поможем понять, что покрывает ваш полис и чего ожидать.',
        ] },
        { type: 'h2', text: 'Сезон ураганов' },
        { type: 'p', text: 'В тяжёлый сезон нагонная волна, затопленные улицы и упавшие деревья повреждают тысячи машин. Платит за них только comprehensive, а когда шторм уже угрожает, страховые обычно перестают оформлять новые покрытия и изменения. Проверьте полис до 1 июня.' },
        { type: 'p', text: 'M&K Agency — семейное агентство: 12 человек в команде и более 5,000 клиентов по всей Флориде. **Пришлите нам свой полис — мы проверим покрытие.** Лицензированный агент разберёт его с вами по-русски, по-английски или по-испански, и вам будет кому позвонить, когда страховка понадобится.' },
      ],
      officeTitle: 'Один офис на юге округа, клиенты — по всему Miami-Dade',
      office: [
        { type: 'p', text: 'Наш офис находится по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, в самом конце Turnpike. Без пробок это около пяти минут от центра Homestead, около 20 минут от Cutler Bay, примерно полчаса от Kendall и около 50 минут от даунтауна Майами; в час пик дольше. Других офисов в округе у нас нет, поэтому большинство клиентов севернее Kendall работают с нами по телефону, в WhatsApp, по SMS и почте, а приезжают по записи, когда хотят.' },
        { type: 'p', text: 'Часы работы: понедельник–пятница с 9 до 6, суббота — по записи. Звоните (305) 859-3953 или пишите в WhatsApp: (971) 998-7313. На заявки в рабочее время агент перезванивает в течение часа.' },
      ],
      faqTitle: 'Автостраховка в округе Miami-Dade: частые вопросы',
      faq: [
        { q: 'Какая минимальная автостраховка в Miami-Dade?', a: 'Такая же, как во всей Флориде: $10,000 PIP и $10,000 PDL. Bodily injury liability для большинства водителей не обязательна, но без неё нельзя оформить UM.' },
        { q: 'Нужно ли вызывать полицию после небольшой аварии?', a: 'По закону Флориды водитель обязан сообщать о ДТП с пострадавшими или погибшими либо с видимым ущербом не менее $2,000. Даже если протокол не обязателен, фото и данные другого водителя сильно упрощают клейм.' },
        { q: 'Почему здесь так важна UM?', a: 'По оценке Insurance Research Council, в 2023 году почти каждый пятый водитель Флориды был без страховки. UM оплачивает травмы вам и вашим пассажирам, когда у виновника нет страховки или её слишком мало.' },
        { q: 'Вы работаете только с водителями на юге округа?', a: 'Нет. Офис у нас во Florida City, но мы работаем с водителями по всему Miami-Dade и по всей Флориде — по телефону, в WhatsApp, по SMS и почте.' },
        { q: 'Можете проверить мой полис перед продлением?', a: 'Да. Пришлите фото declarations page в WhatsApp или SMS. Лицензированный агент проверит полис и объяснит пробелы — бесплатно.' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
