import type { CityPage } from './types';
import { sources } from './sources';

// /[lang]/homeowners-insurance-miami-dade-county-fl (county hub). Facts checked 2026-10-03.
const SRC = ['andrew', 'andrewCat5', 'wilma', 'fbcHvhz', 'mdProductControl', 'acsMiamiDade', 'windForm', 'mitigation', 'roofAge', 'deductibles', 'claimDeadline', 'condoMaster', 'lossAssessment', 'condoInspections', 'floodsmart', 'mdFloodMaps', 'mdSurge', 'msfh'] as const;

export const HOME_MIAMI_DADE: CityPage = {
  path: '/homeowners-insurance-miami-dade-county-fl',
  line: 'home',
  kind: 'county',
  area: 'miami-dade',
  heroImage: 'home-02',
  published: '2026-10-03',
  modified: '2026-10-03',
  served: [
    { name: 'Florida City', path: '/homeowners-insurance-florida-city' },
    { name: 'Homestead', path: '/homeowners-insurance-homestead-fl' },
    { name: 'Cutler Bay', path: '/homeowners-insurance-cutler-bay-fl' },
    { name: 'Kendall', path: '/homeowners-insurance-kendall-fl' },
    { name: 'Palmetto Bay' }, { name: 'Pinecrest' }, { name: 'South Miami' }, { name: 'Coral Gables' },
    { name: 'Miami' }, { name: 'Doral' }, { name: 'Hialeah' }, { name: 'Miami Beach' },
    { name: 'North Miami' }, { name: 'Aventura' }, { name: 'Sunny Isles Beach' },
    { name: 'Redland, Leisure City, Naranja and Princeton' },
  ],
  areaServed: [
    { '@type': 'AdministrativeArea', name: 'Miami-Dade County, FL' },
  ],
  copy: {
    en: {
      metaTitle: 'Homeowners & Condo Insurance in Miami-Dade County | M&K Agency',
      metaDesc: 'Home and condo insurance in Miami-Dade: the HVHZ code, wind mitigation credits, condo master policies and HO-6, flood and surge zones and a free policy review.',
      breadcrumb: 'Miami-Dade County',
      kicker: 'Home & condo insurance · Miami-Dade County',
      h1a: 'Home and condo insurance in Miami-Dade,',
      h1b: 'where the building code was written for hurricanes.',
      sub: 'Houses in the Redland, townhomes in Kendall, high-rise condos on the bay. We read your policy against the way your home was built and the risks of your street, show you the gaps and help you through a claim. English, Spanish or Russian.',
      serviceType: 'Homeowners and condo insurance',
      intro: [
        { type: 'h2', text: 'The High-Velocity Hurricane Zone starts here' },
        { type: 'p', text: 'After Hurricane Andrew struck South Dade on August 24, 1992, destroying about 25,500 homes and damaging more than 101,000 in the county, Miami-Dade rebuilt its building rules around wind. The Florida Building Code now defines Miami-Dade and Broward as the state’s **High-Velocity Hurricane Zone (HVHZ)**. It has the strictest design requirements in Florida: design wind speeds in Miami-Dade run from 165 to 186 mph depending on the building’s risk category. Windows, doors, shutters and roofing used in the HVHZ need a specific product approval, such as a Miami-Dade Notice of Acceptance (NOA).' },
        { type: 'p', text: 'For insurance, the code matters in two ways. It makes newer homes more resistant to wind, and insurers must reflect documented wind-resistant features in your premium. But most of the county’s housing was built before the modern code: Census estimates for 2020–2024 put the median year built at **1980**, and only about a quarter of homes date from 2000 or later.' },
        { type: 'p', text: 'Miami-Dade is also a county of condos and apartments. About half of all homes are in buildings with two or more units, and about 40% are in buildings with ten or more. Only about 52% of homes are owner-occupied. A house owner in the Redland, a townhome owner in an HOA and a condo owner in a 30-story tower all need different coverage.' },
      ],
      checklistTitle: 'What we check, by type of home',
      checklist: [
        '**Single-family houses:** dwelling limit at current rebuilding cost, roof age and permit date, wind mitigation report, law and ordinance coverage, and hurricane deductible in dollars.',
        '**Townhomes and HOA homes:** what the association documents say you must insure (often the whole structure), and whether the HOA policy covers the roof.',
        '**Condo units (HO-6):** interior finishes, cabinets, appliances and water heater, which the master policy excludes by law, plus loss assessment coverage above the $2,000 minimum.',
        '**Older condo buildings:** milestone inspection and reserve study status, which can lead to special assessments that insurance does not pay.',
        '**Renters:** belongings, liability and temporary housing. About half of Miami-Dade households rent.',
        '**Everyone:** flood insurance, because no homeowners, condo or renters policy covers flood or storm surge.',
        '**Everyone:** liability limits that match what your family owns.',
      ],
      body: [
        { type: 'h2', text: 'Florida rules that shape every Miami-Dade policy' },
        { type: 'p', text: '**Wind mitigation credits.** Insurers must include actuarially reasonable credits for features that reduce wind losses and describe them on their websites. On the state inspection form (OIR-B1-1802), all of Miami-Dade is HVHZ. Homes permitted after September 1, 1994 under the South Florida Building Code, or after March 1, 2002 under the Florida Building Code, can qualify for code-based credits, and older homes can earn credits for later upgrades such as opening protection or a new roof deck. A report is valid for up to five years if nothing material changes. Eligible single-family homes and townhomes may get a free inspection through **My Safe Florida Home**.' },
        { type: 'p', text: '**Roofs.** For policies issued or renewed since July 1, 2022, insurers cannot refuse a home only because the roof is under 15 years old, and an older roof with an inspection showing at least five years of life left cannot be refused on age alone.' },
        { type: 'p', text: '**Deductibles and claims.** Hurricane deductibles are offered at $500 or 2%, 5% or 10% of the dwelling limit and apply once per calendar year. New claims must be reported within one year of the date of loss, which for a hurricane is landfall; supplemental claims within 18 months. Condo loss-assessment claims have a separate deadline tied to the association’s assessment.' },
        { type: 'h2', text: 'Condos: the master policy and your HO-6' },
        { type: 'p', text: 'Florida law requires a condo association to insure the building but to exclude what is inside each unit: floor, wall and ceiling coverings, electrical fixtures, appliances, water heaters, built-in cabinets and countertops, window treatments and personal property. Your HO-6 covers those, your liability and loss of use, and must include at least $2,000 of loss assessment coverage. Buildings with three or more habitable stories need milestone inspections at 30 years and every 10 years after, plus a structural integrity reserve study. The results can mean repairs and special assessments, so ask your association where it stands. High-rise owners should also remember Wilma in 2005, when the strongest winds were felt on upper floors and many windows broke.' },
        { type: 'h2', text: 'Flood and storm surge' },
        { type: 'p', text: 'Every homeowners and condo policy excludes flood, including storm surge. Miami-Dade’s effective flood maps date from September 11, 2009; preliminary maps released in 2021 are not yet in force. The county’s storm surge planning zones, A through E, show where evacuations may be ordered. NFIP policies usually take 30 days to start and cover up to $250,000 for the building and $100,000 for contents. Andrew’s storm tide reached 16.9 feet on the western shore of Biscayne Bay, so coastal homes need to take surge seriously.' },
        { type: 'p', text: 'M&K Agency is family-owned, with a team of 12 and more than 5,000 clients across Florida. **Send us your policy and we’ll check your coverage.** We will match it to your home and your association documents, find the gaps and stay with you through any claim.' },
      ],
      officeTitle: 'One South Dade office, clients across Miami-Dade',
      office: [
        { type: 'p', text: 'Our office is at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, at the southern end of the Turnpike. In light traffic it is a few minutes from Homestead, about 20 minutes from Cutler Bay, about half an hour from Kendall and roughly 50 minutes from downtown Miami. We do not have offices elsewhere in the county, so clients farther north usually send us their documents by WhatsApp or email and we review them by phone.' },
        { type: 'p', text: 'Hours are Monday to Friday, 9 to 6, and Saturday by appointment. Call (305) 859-3953 or WhatsApp (971) 998-7313. An agent calls back within an hour on requests received during business hours.' },
      ],
      faqTitle: 'Home and condo insurance in Miami-Dade: common questions',
      faq: [
        { q: 'What is the High-Velocity Hurricane Zone?', a: 'It is the part of the Florida Building Code that applies to Miami-Dade and Broward counties. It sets the state’s strictest wind design requirements and requires approved products for windows, doors, shutters and roofs. Insurers treat the whole county as HVHZ on the wind mitigation inspection form.' },
        { q: 'Can a wind mitigation inspection lower my premium in Miami-Dade?', a: 'It can, if your home has features the insurer gives credit for, such as hurricane-rated openings, a hip roof, strong roof deck attachment or roof-to-wall connections. The credits are only applied when a valid inspection report documents them.' },
        { q: 'Does my condo association’s policy cover my unit?', a: 'Only partly. Florida law requires the master policy to exclude interior finishes, cabinets, countertops, appliances, water heaters, fixtures and your belongings. You need an HO-6 policy for those and for your liability.' },
        { q: 'How do I find my flood zone in Miami-Dade?', a: 'Use the county’s flood zone map tool or call the county flood zone hotline listed on its website. The maps in effect today date from 2009; preliminary maps are not yet in force. Remember that flooding also happens outside high-risk zones.' },
        { q: 'Do you insure homes outside South Dade?', a: 'Yes. We work with homeowners and condo owners throughout Miami-Dade and Florida, mostly by phone, WhatsApp, text and email.' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Seguro de Casa y Condominio en Miami-Dade | M&K Agency',
      metaDesc: 'Seguro de casa y condominio en Miami-Dade: código HVHZ para huracanes, créditos por mitigación, póliza maestra y HO-6, inundación y marejada, y revisión gratis.',
      breadcrumb: 'Condado Miami-Dade',
      kicker: 'Seguro de casa y condominio · Condado Miami-Dade',
      h1a: 'Seguro de casa y condominio en Miami-Dade,',
      h1b: 'donde el código se escribió pensando en huracanes.',
      sub: 'Casas en el Redland, townhouses en Kendall, condominios frente a la bahía. Leemos su póliza según cómo está construida su casa y los riesgos de su calle, le mostramos lo que falta y le ayudamos con el reclamo. En español, inglés o ruso.',
      serviceType: 'Seguro de casa y de condominio',
      intro: [
        { type: 'h2', text: 'La Zona de Huracanes de Alta Velocidad empieza aquí' },
        { type: 'p', text: 'Después de que el huracán Andrew golpeó el sur de Miami-Dade el 24 de agosto de 1992, destruyendo unas 25,500 viviendas y dañando más de 101,000 en el condado, Miami-Dade rehízo sus reglas de construcción pensando en el viento. Hoy el Código de Construcción de Florida define a Miami-Dade y Broward como la **Zona de Huracanes de Alta Velocidad (HVHZ)** del estado. Es la zona con las exigencias más estrictas de Florida: las velocidades de viento de diseño en Miami-Dade van de 165 a 186 mph según la categoría de riesgo del edificio. Las ventanas, puertas, shutters y techos que se usan en la HVHZ necesitan una aprobación específica, como una Notice of Acceptance (NOA) de Miami-Dade.' },
        { type: 'p', text: 'Para el seguro, el código importa de dos maneras. Hace que las casas nuevas resistan mejor el viento, y las aseguradoras deben reflejar en la prima las características resistentes que estén documentadas. Pero la mayoría de las viviendas del condado se construyó antes del código moderno: según el Censo para 2020–2024, la vivienda típica es de **1980**, y solo una cuarta parte es del año 2000 en adelante.' },
        { type: 'p', text: 'Miami-Dade es además un condado de condominios y apartamentos. Cerca de la mitad de las viviendas está en edificios de dos o más unidades, y alrededor del 40% en edificios de diez o más. Solo un 52% de las viviendas las ocupan sus dueños. Quien tiene una casa en el Redland, un townhouse en una HOA o un condominio en una torre de 30 pisos necesita coberturas distintas.' },
      ],
      checklistTitle: 'Lo que revisamos, según el tipo de vivienda',
      checklist: [
        '**Casas unifamiliares:** cobertura al costo actual de reconstrucción, edad y permiso del techo, informe de mitigación de viento, leyes y ordenanzas, y deducible de huracán en dólares.',
        '**Townhouses y casas en HOA:** lo que los documentos de la asociación le obligan a asegurar (muchas veces toda la estructura) y si la póliza de la HOA cubre el techo.',
        '**Condominios (HO-6):** acabados interiores, gabinetes, electrodomésticos y calentador, que la ley excluye de la póliza maestra, además de loss assessment por encima del mínimo de $2,000.',
        '**Edificios de condominio con años:** estado de la inspección de hito y del estudio de reservas, que pueden traer cuotas especiales que el seguro no paga.',
        '**Inquilinos:** pertenencias, responsabilidad y vivienda temporal. Casi la mitad de los hogares de Miami-Dade alquila.',
        '**Todos:** seguro de inundación, porque ninguna póliza de casa, condominio o inquilino cubre inundación ni marejada.',
        '**Todos:** límites de responsabilidad acordes con lo que tiene su familia.',
      ],
      body: [
        { type: 'h2', text: 'Reglas de Florida que definen toda póliza en Miami-Dade' },
        { type: 'p', text: '**Créditos por mitigación de viento.** Las aseguradoras deben incluir créditos razonables por las características que reducen las pérdidas por viento y explicarlos en sus sitios web. En el formulario estatal de inspección (OIR-B1-1802), todo Miami-Dade es HVHZ. Las casas con permiso posterior al 1 de septiembre de 1994 bajo el South Florida Building Code, o posterior al 1 de marzo de 2002 bajo el Código de Construcción de Florida, pueden calificar para créditos por código, y las más viejas pueden ganarlos por mejoras posteriores, como protección de aberturas o un techo nuevo bien clavado. El informe vale hasta cinco años si no hay cambios importantes. Las casas unifamiliares y townhouses que califiquen pueden conseguir una inspección gratis con **My Safe Florida Home**.' },
        { type: 'p', text: '**Techos.** En las pólizas emitidas o renovadas desde el 1 de julio de 2022, la aseguradora no puede rechazar una casa solo porque el techo tiene menos de 15 años, y un techo más viejo con una inspección que muestre al menos cinco años de vida útil no puede rechazarse solo por la edad.' },
        { type: 'p', text: '**Deducibles y reclamos.** Los deducibles de huracán se ofrecen de $500 o del 2%, 5% o 10% de la cobertura de la vivienda y se aplican una vez por año calendario. Los reclamos nuevos deben avisarse dentro de un año desde la fecha de la pérdida, que en un huracán es la entrada a tierra; los suplementarios, dentro de 18 meses. Los reclamos de loss assessment de condominio tienen un plazo propio, ligado a la cuota que apruebe la asociación.' },
        { type: 'h2', text: 'Condominios: la póliza maestra y su HO-6' },
        { type: 'p', text: 'La ley de Florida exige que la asociación asegure el edificio, pero que excluya lo que hay dentro de cada unidad: revestimientos de pisos, paredes y techos, instalaciones eléctricas, electrodomésticos, calentadores, gabinetes y topes empotrados, cortinas y persianas, y los bienes personales. Su HO-6 cubre todo eso, su responsabilidad y los gastos de vivienda, y debe incluir al menos $2,000 de loss assessment. Los edificios de tres o más pisos habitables necesitan inspecciones de hito a los 30 años y cada 10 años después, además de un estudio de reservas de integridad estructural. Los resultados pueden significar reparaciones y cuotas especiales, así que pregunte a su asociación en qué punto está. Quien vive en una torre también debe recordar a Wilma en 2005, cuando los vientos más fuertes se sintieron en los pisos altos y se rompieron muchas ventanas.' },
        { type: 'h2', text: 'Inundación y marejada' },
        { type: 'p', text: 'Toda póliza de casa y de condominio excluye la inundación, incluida la marejada. Los mapas de inundación vigentes en Miami-Dade son del 11 de septiembre de 2009; los preliminares publicados en 2021 todavía no están en vigor. Las zonas de planificación por marejada del condado, de la A a la E, indican dónde pueden ordenarse evacuaciones. Las pólizas del NFIP suelen tardar 30 días en empezar y cubren hasta $250,000 para el edificio y $100,000 para el contenido. La marea de tormenta de Andrew llegó a 16.9 pies en la orilla oeste de la bahía de Biscayne, así que en la costa la marejada hay que tomarla en serio.' },
        { type: 'p', text: 'M&K Agency es una agencia familiar con un equipo de 12 personas y más de 5,000 clientes en Florida. **Envíenos su póliza y la revisamos.** La comparamos con su casa y con los documentos de su asociación, encontramos los vacíos y le acompañamos en cualquier reclamo.' },
      ],
      officeTitle: 'Una oficina en el sur, clientes en todo Miami-Dade',
      office: [
        { type: 'p', text: 'Nuestra oficina está en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, al final del Turnpike. Sin tráfico queda a pocos minutos de Homestead, a unos 20 de Cutler Bay, a media hora de Kendall y a unos 50 minutos del downtown de Miami. No tenemos oficinas en otras partes del condado, así que los clientes que viven más al norte suelen mandarnos sus documentos por WhatsApp o correo y los revisamos por teléfono.' },
        { type: 'p', text: 'Horario: lunes a viernes de 9 a 6, sábados con cita. Llame al (305) 859-3953 o escriba por WhatsApp al (971) 998-7313. Un agente le devuelve la llamada en menos de una hora si nos escribe en horario de oficina.' },
      ],
      faqTitle: 'Seguro de casa y condominio en Miami-Dade: preguntas frecuentes',
      faq: [
        { q: '¿Qué es la Zona de Huracanes de Alta Velocidad?', a: 'Es la parte del Código de Construcción de Florida que aplica a los condados Miami-Dade y Broward. Fija las exigencias de diseño contra viento más estrictas del estado y pide productos aprobados para ventanas, puertas, shutters y techos. En el formulario de mitigación de viento, todo el condado se considera HVHZ.' },
        { q: '¿Una inspección de mitigación de viento puede bajar mi prima en Miami-Dade?', a: 'Puede, si su casa tiene características que la aseguradora acredita, como aberturas protegidas contra huracanes, techo a cuatro aguas, buen clavado del techo o conexiones techo-pared. Los créditos solo se aplican si un informe de inspección vigente los documenta.' },
        { q: '¿La póliza de mi asociación de condominio cubre mi unidad?', a: 'Solo en parte. La ley de Florida obliga a que la póliza maestra excluya acabados interiores, gabinetes, topes, electrodomésticos, calentadores, lámparas y sus pertenencias. Para eso y para su responsabilidad necesita una póliza HO-6.' },
        { q: '¿Cómo encuentro mi zona de inundación en Miami-Dade?', a: 'Use la herramienta de mapas de zonas de inundación del condado o llame a la línea de zonas de inundación que aparece en su sitio web. Los mapas vigentes son de 2009; los preliminares aún no están en vigor. Recuerde que también hay inundaciones fuera de las zonas de alto riesgo.' },
        { q: '¿Aseguran casas fuera del sur de Miami-Dade?', a: 'Sí. Trabajamos con propietarios de casas y condominios en todo Miami-Dade y en Florida, sobre todo por teléfono, WhatsApp, texto y correo.' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Страховка дома и кондо в округе Miami-Dade | M&K Agency',
      metaDesc: 'Страховка дома и кондо в Miami-Dade: строительный код HVHZ, кредиты за wind mitigation, мастер-полис и HO-6, зоны наводнения и нагона, бесплатная проверка.',
      breadcrumb: 'Округ Miami-Dade',
      kicker: 'Страховка дома и кондо · округ Miami-Dade',
      h1a: 'Страховка дома и кондо в Miami-Dade —',
      h1b: 'там, где строительный код писали под ураганы.',
      sub: 'Дома в Redland, таунхаусы в Kendall, кондо в высотках у залива. Мы сверяем полис с тем, как построен ваш дом и какие риски у вашей улицы, показываем пробелы и помогаем с клеймом. По-русски, по-английски или по-испански.',
      serviceType: 'Страхование дома и кондо',
      intro: [
        { type: 'h2', text: 'High-Velocity Hurricane Zone начинается здесь' },
        { type: 'p', text: 'После того как 24 августа 1992 года ураган Andrew ударил по югу округа, разрушив около 25,500 домов и повредив более 101,000, Miami-Dade перестроил свои строительные правила с прицелом на ветер. Сегодня Florida Building Code относит Miami-Dade и Broward к **High-Velocity Hurricane Zone (HVHZ)** — зоне с самыми строгими требованиями в штате: расчётная скорость ветра в Miami-Dade — от 165 до 186 миль в час в зависимости от категории риска здания. Окна, двери, ставни и кровельные материалы для HVHZ должны иметь специальное одобрение — например, Miami-Dade Notice of Acceptance (NOA).' },
        { type: 'p', text: 'Для страховки код важен в двух смыслах. Новые дома лучше держат ветер, и страховые обязаны учитывать в премии подтверждённые ветроустойчивые элементы. Но большая часть жилья в округе построена до современного кода: по оценкам переписи за 2020–2024 годы, медианный год постройки — **1980**, и лишь около четверти домов построены в 2000 году или позже.' },
        { type: 'p', text: 'Кроме того, Miami-Dade — округ кондо и квартир. Около половины всего жилья — в зданиях на две квартиры и больше, около 40% — в домах на десять и более квартир. Владельцы живут лишь примерно в 52% жилья. Хозяину дома в Redland, владельцу таунхауса в HOA и владельцу квартиры в 30-этажной башне нужны совершенно разные полисы.' },
      ],
      checklistTitle: 'Что мы проверяем — в зависимости от типа жилья',
      checklist: [
        '**Частный дом:** покрытие по текущей стоимости восстановления, возраст крыши и дата разрешения, отчёт wind mitigation, law and ordinance и ураганная франшиза в долларах.',
        '**Таунхаусы и дома в HOA:** что по документам ассоциации обязаны страховать вы (часто — всё строение) и покрывает ли полис HOA крышу.',
        '**Квартира в кондо (HO-6):** отделка, шкафы, техника и водонагреватель, которые по закону исключены из мастер-полиса, плюс loss assessment сверх минимума $2,000.',
        '**Старые здания кондо:** статус milestone inspection и SIRS — они могут обернуться спецвзносами, которые страховка не оплачивает.',
        '**Арендаторы:** вещи, ответственность и временное жильё. Почти половина домохозяйств в Miami-Dade снимает жильё.',
        '**Для всех:** страховка от наводнения — ни один полис на дом, кондо или аренду не покрывает наводнение и нагонную волну.',
        '**Для всех:** лимиты ответственности, соответствующие тому, что есть у семьи.',
      ],
      body: [
        { type: 'h2', text: 'Правила Флориды, которые определяют любой полис в Miami-Dade' },
        { type: 'p', text: '**Кредиты за wind mitigation.** Страховые обязаны включать обоснованные кредиты за элементы, снижающие ущерб от ветра, и описывать их на своих сайтах. В государственной форме инспекции (OIR-B1-1802) весь Miami-Dade — это HVHZ. Дома, получившие разрешение на строительство после 1 сентября 1994 года по South Florida Building Code или после 1 марта 2002 года по Florida Building Code, могут получить кредиты за соответствие коду, а более старые — за последующие улучшения, например защиту окон и дверей или новую крышу с правильным креплением настила. Отчёт действует до пяти лет, если ничего существенно не менялось. Подходящие частные дома и таунхаусы могут получить бесплатную инспекцию по программе **My Safe Florida Home**.' },
        { type: 'p', text: '**Крыши.** Для полисов, выданных или продлённых с 1 июля 2022 года, страховая не может отказать только из-за того, что крыше меньше 15 лет, а более старой крыше с инспекцией, подтверждающей не менее пяти лет службы, нельзя отказать только по возрасту.' },
        { type: 'p', text: '**Франшизы и клеймы.** Ураганную франшизу предлагают в размере $500 или 2%, 5% либо 10% от покрытия дома, и она применяется раз в календарный год. О новом клейме нужно заявить в течение года с даты ущерба (для урагана — с даты выхода на сушу), о дополнительном — в течение 18 месяцев. У клеймов по loss assessment в кондо отдельный срок, привязанный к решению ассоциации о взносе.' },
        { type: 'h2', text: 'Кондо: мастер-полис и ваш HO-6' },
        { type: 'p', text: 'Закон Флориды требует, чтобы ассоциация страховала здание, но исключала всё, что внутри квартир: покрытия полов, стен и потолков, светильники, бытовую технику, водонагреватели, встроенные шкафы и столешницы, шторы и жалюзи, личные вещи. Ваш HO-6 покрывает это, вашу ответственность и временное проживание и должен включать не менее $2,000 loss assessment. Здания от трёх жилых этажей обязаны проходить milestone inspection в 30 лет и затем каждые 10 лет, а также делать SIRS. Результаты могут означать ремонт и спецвзносы, так что узнайте у ассоциации, на каком она этапе. Владельцам квартир в высотках стоит помнить и про Wilma в 2005 году: самые сильные порывы пришлись на верхние этажи, и было выбито много окон.' },
        { type: 'h2', text: 'Наводнение и нагонная волна' },
        { type: 'p', text: 'Любой полис на дом или кондо исключает наводнение, включая нагонную волну. Действующие карты затопления Miami-Dade вступили в силу 11 сентября 2009 года; предварительные карты 2021 года пока не действуют. Зоны планирования округа на случай нагонной волны (от A до E) показывают, где может быть объявлена эвакуация. Полисы NFIP обычно начинают действовать через 30 дней и покрывают до $250,000 за здание и до $100,000 за имущество. Штормовой прилив Andrew достиг 16.9 фута на западном берегу залива Biscayne, так что прибрежным домам к нагонной волне нужно относиться серьёзно.' },
        { type: 'p', text: 'M&K Agency — семейное агентство: 12 человек в команде и более 5,000 клиентов по всей Флориде. **Пришлите нам свой полис — мы проверим покрытие.** Сверим его с вашим домом и документами ассоциации, найдём пробелы и будем рядом при любом клейме.' },
      ],
      officeTitle: 'Один офис на юге — клиенты по всему Miami-Dade',
      office: [
        { type: 'p', text: 'Наш офис находится по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, в самом конце Turnpike. Без пробок это несколько минут от Homestead, около 20 минут от Cutler Bay, полчаса от Kendall и примерно 50 минут от даунтауна Майами. Других офисов в округе у нас нет, поэтому клиенты, которые живут севернее, обычно присылают документы в WhatsApp или по почте, а мы разбираем их по телефону.' },
        { type: 'p', text: 'Часы работы: понедельник–пятница с 9 до 6, суббота — по записи. Звоните (305) 859-3953 или пишите в WhatsApp: (971) 998-7313. На заявки в рабочее время агент перезванивает в течение часа.' },
      ],
      faqTitle: 'Страховка дома и кондо в Miami-Dade: частые вопросы',
      faq: [
        { q: 'Что такое High-Velocity Hurricane Zone?', a: 'Это часть Florida Building Code, которая действует в округах Miami-Dade и Broward. Она задаёт самые строгие в штате требования к ветроустойчивости и требует одобренных продуктов для окон, дверей, ставней и кровли. В форме wind mitigation весь округ считается HVHZ.' },
        { q: 'Может ли инспекция wind mitigation снизить премию в Miami-Dade?', a: 'Может, если у дома есть элементы, за которые страховая даёт кредиты: ураганная защита окон и дверей, четырёхскатная крыша, надёжное крепление настила, связь крыши со стенами. Кредиты применяются только при действующем отчёте инспекции.' },
        { q: 'Покрывает ли полис ассоциации мою квартиру в кондо?', a: 'Лишь частично. Закон Флориды требует исключать из мастер-полиса отделку, шкафы, столешницы, технику, водонагреватели, светильники и ваши вещи. Для них и для вашей ответственности нужен полис HO-6.' },
        { q: 'Как узнать свою зону затопления в Miami-Dade?', a: 'Воспользуйтесь картой зон затопления на сайте округа или позвоните по горячей линии, указанной там же. Действующие карты — 2009 года, предварительные пока не вступили в силу. И помните: наводнения случаются и вне зон высокого риска.' },
        { q: 'Вы страхуете дома не только на юге округа?', a: 'Да. Мы работаем с владельцами домов и кондо по всему Miami-Dade и по всей Флориде — в основном по телефону, в WhatsApp, по SMS и почте.' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
