import type { CityPage } from './types';
import { sources } from './sources';

// /[lang]/homeowners-insurance-cutler-bay-fl. Local facts checked 2026-10-03 (see sources).
const SRC = ['andrew', 'andrewCat5', 'acsCutlerBay', 'mdSurge', 'mdFloodMaps', 'floodsmart', 'roofAge', 'deductibles', 'windForm', 'mitigation', 'claimDeadline', 'msfh', 'cutlerBayTown'] as const;

export const HOME_CUTLER_BAY: CityPage = {
  path: '/homeowners-insurance-cutler-bay-fl',
  line: 'home',
  kind: 'city',
  area: 'cutler-bay',
  parent: '/homeowners-insurance-miami-dade-county-fl',
  heroImage: 'home-04',
  published: '2026-10-03',
  modified: '2026-10-03',
  areaServed: [
    { '@type': 'City', name: 'Cutler Bay, FL' },
    { '@type': 'AdministrativeArea', name: 'Miami-Dade County, FL' },
  ],
  copy: {
    en: {
      metaTitle: 'Homeowners Insurance in Cutler Bay, FL | M&K Agency',
      metaDesc: 'Homeowners insurance for Cutler Bay: 1980s homes, roof age rules, storm surge zones near Biscayne Bay, hurricane deductibles and a free review of your current policy.',
      breadcrumb: 'Cutler Bay',
      kicker: 'Homeowners insurance · Cutler Bay, FL',
      h1a: 'Homeowners insurance in Cutler Bay, FL,',
      h1b: 'for older homes close to the bay.',
      sub: 'Many Cutler Bay houses date from before Andrew, and part of town sits below the old ridge, close to Biscayne Bay. We check your roof, your deductibles and your flood exposure, and we help you through a claim. English, Spanish or Russian.',
      serviceType: 'Homeowners insurance',
      intro: [
        { type: 'h2', text: 'A town of single-family homes, many of them built before 1990' },
        { type: 'p', text: 'Cutler Bay is a neighborhood of houses more than anything else. Census estimates for 2020–2024 show about two-thirds of homes are detached single-family houses, and roughly 70% are lived in by their owners, one of the higher rates in South Miami-Dade. The housing is also older than in neighboring Homestead: the median home was built around **1984**, and about 57% were built before 1990. Only about a third date from 2000 or later.' },
        { type: 'p', text: 'That timing matters. Most of those homes were standing when Hurricane Andrew, later classified as a Category 5, came ashore just to the south on August 24, 1992. Many were repaired or rebuilt afterward, at different times and under different codes, so two houses on the same street can have very different roofs, windows and roof-to-wall connections. Insurers price that difference, which is why we start every Cutler Bay review with the house itself.' },
        { type: 'p', text: 'Geography is the other half of the story. The town takes its old name from the **Cutler Ridge**, a limestone ridge that rises to about 14 feet. Land east of the ridge, toward Biscayne Bay, is lower and exposed to storm surge, and much of Cutler Bay is inside Miami-Dade’s storm surge planning zones. During Andrew, the highest storm tide in the county, 16.9 feet, was measured on the bay shore just north of today’s town limits.' },
      ],
      checklistTitle: 'What we check on Cutler Bay home policies',
      checklist: [
        '**Roof age and permit date.** Roofs over 15 years old can cause problems at renewal unless an inspection shows remaining life.',
        '**A wind mitigation inspection** documenting any upgrades: impact windows or shutters, a re-nailed roof deck, hurricane straps.',
        '**Law and ordinance coverage** at 50% rather than 25% for an older home, because rebuilding to the current code can cost much more than the original repair.',
        '**Dwelling coverage at current rebuilding cost.** Building costs in South Florida have risen faster than many policies were updated.',
        '**Flood insurance**, especially east of the ridge. Homeowners policies do not cover flood or storm surge.',
        '**The hurricane deductible in dollars**, and whether you could pay it after a storm.',
        '**Water damage limits and exclusions** for older plumbing and slow leaks.',
        '**Pool, screen enclosure and fence coverage**, which may have separate limits.',
        '**Personal liability** for a pool, a dog or guests.',
      ],
      body: [
        { type: 'h2', text: 'Older roofs and Florida’s roof-age law' },
        { type: 'p', text: 'For policies issued or renewed since July 1, 2022, a Florida insurer cannot refuse to write or renew a home only because the roof is under 15 years old. If your roof is older, you can have it inspected, and if the inspection shows at least five years of remaining useful life, the insurer cannot refuse based on roof age alone. Florida also allows a separate roof deductible in some policies, limited to the lesser of 2% of the dwelling limit or 50% of the roof replacement cost. It does not apply to hurricane losses, to a tree falling through the roof, or to repairs of less than half the roof. Read your declarations page to see whether you have one.' },
        { type: 'h2', text: 'Credits for wind-resistant features' },
        { type: 'p', text: 'Insurers must include actuarially reasonable credits for features that reduce wind losses, and in Miami-Dade the state inspection form treats the whole county as a High-Velocity Hurricane Zone. For older homes the credits usually come from upgrades rather than the original construction: opening protection, roof deck attachment on a new roof, secondary water resistance and roof-to-wall connections. A report is valid for up to five years if nothing material changes. Through **My Safe Florida Home**, eligible homeowners may get a free inspection and, if they qualify, a grant toward certain improvements.' },
        { type: 'h2', text: 'Storm surge and flood' },
        { type: 'p', text: 'Every homeowners policy excludes flood, and storm surge is flood. Miami-Dade’s storm surge planning zones, A through E, show which neighborhoods may be told to evacuate, and the county’s flood maps show your official flood zone; the current maps took effect in 2009 and preliminary updates are not yet in force. A flood policy through the NFIP usually has a 30-day waiting period, so it has to be bought well before a storm.' },
        { type: 'h2', text: 'Hurricane deductibles and claims' },
        { type: 'p', text: 'Florida hurricane deductibles are offered at $500 or 2%, 5% or 10% of the dwelling limit, and they apply once per calendar year. New claims must be reported within one year of the date of loss (landfall, for a hurricane), and supplemental claims within 18 months.' },
        { type: 'p', text: 'M&K Agency is a family-owned agency with a team of 12 and more than 5,000 clients across Florida. **Send us your policy and we’ll check your coverage.** We will tell you where an older home is exposed, what an inspection could change, and how your deductibles work in dollars. When a storm passes, you call us and we help you file and follow the claim.' },
      ],
      officeTitle: 'Serving Cutler Bay from Florida City',
      office: [
        { type: 'p', text: 'We do not have an office in Cutler Bay. We serve Cutler Bay homeowners from our office at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, about 12.5 miles from Cutler Bay Town Hall. That is roughly 20 minutes on the Turnpike in light traffic, or a longer drive down US-1. Most reviews happen by WhatsApp or email: send photos of your declarations page and any inspection reports.' },
        { type: 'p', text: 'Office hours are Monday to Friday, 9 to 6, and Saturday by appointment. Call (305) 859-3953 or WhatsApp (971) 998-7313. An agent calls back within an hour on requests received during business hours.' },
      ],
      faqTitle: 'Homeowners insurance in Cutler Bay: common questions',
      faq: [
        { q: 'Is my Cutler Bay home in a storm surge zone?', a: 'Many are, especially east of the old Cutler Ridge toward Biscayne Bay. Look up your address on Miami-Dade County’s storm surge planning zone map and flood zone map. Remember that a homeowners policy does not cover storm surge damage; you need flood insurance.' },
        { q: 'My house was built in the 1980s. What should I check first?', a: 'Start with the roof age and permit date, a wind mitigation inspection, your law and ordinance limit, and whether the dwelling limit still matches today’s rebuilding cost. Older homes often benefit most from documenting later upgrades.' },
        { q: 'What is law and ordinance coverage?', a: 'When part of a home is damaged, current building codes can require upgrades to the rest of it. Law and ordinance coverage pays for those code-required costs. Florida insurers must offer limits of 25% or 50% of the dwelling limit.' },
        { q: 'Do I need flood insurance if I am not in a high-risk zone?', a: 'Lenders only require it in high-risk zones, but flooding happens outside them too, and homeowners policies exclude flood. Policies for lower-risk zones are often more affordable, and NFIP coverage usually starts 30 days after purchase.' },
        { q: 'How long do I have to report hurricane damage?', a: 'Under Florida law, notice of a new claim must be given within one year of the date of loss, which for a hurricane is the date of landfall. Reopened or supplemental claims have 18 months. Report as soon as you safely can.' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Seguro de Casa en Cutler Bay, FL | M&K Agency',
      metaDesc: 'Seguro de casa en Cutler Bay: casas de los años 80, la ley sobre la edad del techo, zonas de marejada cerca de la bahía, deducibles de huracán y revisión gratis de su póliza.',
      breadcrumb: 'Cutler Bay',
      kicker: 'Seguro de casa · Cutler Bay, FL',
      h1a: 'Seguro de casa en Cutler Bay, FL,',
      h1b: 'para casas con años y cerca de la bahía.',
      sub: 'Muchas casas de Cutler Bay son de antes de Andrew, y parte del pueblo queda por debajo de la antigua loma, cerca de la bahía de Biscayne. Revisamos su techo, sus deducibles y su riesgo de inundación, y le ayudamos con el reclamo. En español, inglés o ruso.',
      serviceType: 'Seguro de casa',
      intro: [
        { type: 'h2', text: 'Un pueblo de casas, muchas de ellas anteriores a 1990' },
        { type: 'p', text: 'Cutler Bay es, ante todo, un lugar de casas. Según las estimaciones del Censo para 2020–2024, cerca de dos tercios de las viviendas son casas independientes y alrededor del 70% las habitan sus propios dueños, una de las proporciones más altas del sur de Miami-Dade. Además, las casas son más viejas que en Homestead: la vivienda típica se construyó alrededor de **1984**, y cerca del 57% es anterior a 1990. Solo un tercio es del año 2000 en adelante.' },
        { type: 'p', text: 'Ese dato importa. La mayoría de esas casas ya estaba en pie cuando el huracán Andrew, luego reclasificado como categoría 5, tocó tierra justo al sur el 24 de agosto de 1992. Muchas se repararon o reconstruyeron después, en distintos momentos y con distintos códigos, así que dos casas en la misma calle pueden tener techos, ventanas y amarres muy diferentes. Las aseguradoras cobran según esa diferencia, y por eso cada revisión en Cutler Bay empieza por la casa.' },
        { type: 'p', text: 'La otra mitad de la historia es el terreno. El nombre antiguo del pueblo viene de **Cutler Ridge**, una loma de piedra caliza que llega a unos 14 pies. Hacia el este, rumbo a la bahía de Biscayne, el terreno es más bajo y está expuesto a la marejada ciclónica, y buena parte de Cutler Bay está dentro de las zonas de planificación por marejada de Miami-Dade. Durante Andrew, la marea de tormenta más alta del condado, 16.9 pies, se midió en la orilla de la bahía, justo al norte de los límites actuales del pueblo.' },
      ],
      checklistTitle: 'Lo que revisamos en las pólizas de casa de Cutler Bay',
      checklist: [
        '**Edad del techo y fecha del permiso.** Un techo de más de 15 años puede dar problemas en la renovación si una inspección no demuestra que le queda vida útil.',
        '**Una inspección de mitigación de viento** que documente las mejoras: ventanas de impacto o shutters, techo con clavado reforzado, amarres contra huracanes.',
        '**Leyes y ordenanzas al 50%** en vez del 25% en una casa vieja, porque reconstruir con el código actual puede costar mucho más que la reparación original.',
        '**Cobertura de la vivienda al costo actual de reconstrucción.** Construir en el sur de Florida ha subido más rápido de lo que se actualizaron muchas pólizas.',
        '**Seguro de inundación**, sobre todo al este de la loma. La póliza de casa no cubre inundación ni marejada.',
        '**El deducible de huracán en dólares**, y si podría pagarlo después de una tormenta.',
        '**Límites y exclusiones por daños de agua** en tuberías viejas y filtraciones lentas.',
        '**Piscina, screen enclosure y cercas**, que pueden tener límites aparte.',
        '**Responsabilidad civil** por la piscina, el perro o las visitas.',
      ],
      body: [
        { type: 'h2', text: 'Techos viejos y la ley de Florida sobre la edad del techo' },
        { type: 'p', text: 'En las pólizas emitidas o renovadas desde el 1 de julio de 2022, una aseguradora de Florida no puede negarse a asegurar o renovar una casa solo porque el techo tiene menos de 15 años. Si el suyo es más viejo, puede hacerlo inspeccionar, y si la inspección muestra al menos cinco años de vida útil, no la pueden rechazar solo por la edad del techo. Florida también permite que algunas pólizas tengan un deducible aparte para el techo, limitado al menor entre el 2% de la cobertura de la vivienda y el 50% del costo de cambiar el techo. No se aplica a pérdidas por huracán, a un árbol que atraviesa el techo ni a reparaciones de menos de la mitad del techo. Revise su página de declaraciones para ver si lo tiene.' },
        { type: 'h2', text: 'Créditos por resistencia al viento' },
        { type: 'p', text: 'Las aseguradoras deben incluir créditos razonables por las características que reducen las pérdidas por viento, y en Miami-Dade el formulario estatal de inspección trata a todo el condado como Zona de Huracanes de Alta Velocidad. En las casas viejas, los créditos suelen venir de las mejoras y no de la construcción original: protección de aberturas, el clavado del techo nuevo, la barrera secundaria contra el agua y las conexiones techo-pared. El informe vale hasta cinco años si no hay cambios importantes. Con **My Safe Florida Home**, los propietarios que califican pueden conseguir una inspección gratis y, si cumplen los requisitos, un subsidio para ciertas mejoras.' },
        { type: 'h2', text: 'Marejada e inundación' },
        { type: 'p', text: 'Toda póliza de propietario excluye la inundación, y la marejada es inundación. Las zonas de planificación por marejada de Miami-Dade, de la A a la E, indican qué vecindarios pueden recibir orden de evacuar, y los mapas de inundación del condado muestran su zona oficial; los mapas vigentes son de 2009 y las actualizaciones preliminares todavía no están en vigor. Una póliza del NFIP suele tener 30 días de espera, así que hay que comprarla mucho antes de una tormenta.' },
        { type: 'h2', text: 'Deducibles de huracán y reclamos' },
        { type: 'p', text: 'En Florida, los deducibles de huracán se ofrecen de $500 o del 2%, 5% o 10% de la cobertura de la vivienda, y se aplican una vez por año calendario. Los reclamos nuevos deben avisarse dentro de un año desde la fecha de la pérdida (la entrada a tierra, en un huracán), y los suplementarios dentro de 18 meses.' },
        { type: 'p', text: 'M&K Agency es una agencia familiar con un equipo de 12 personas y más de 5,000 clientes en Florida. **Envíenos su póliza y la revisamos.** Le diremos dónde está expuesta una casa con años, qué podría cambiar una inspección y cuánto son sus deducibles en dólares. Cuando pase la tormenta, nos llama y le ayudamos a presentar el reclamo y darle seguimiento.' },
      ],
      officeTitle: 'Atendemos Cutler Bay desde Florida City',
      office: [
        { type: 'p', text: 'No tenemos oficina en Cutler Bay. Atendemos a los propietarios de Cutler Bay desde nuestra oficina en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, a unas 12.5 millas de la Alcaldía de Cutler Bay. Son unos 20 minutos por el Turnpike sin tráfico, o algo más bajando por la US-1. La mayoría de las revisiones se hacen por WhatsApp o correo: mándenos fotos de su página de declaraciones y de cualquier informe de inspección.' },
        { type: 'p', text: 'Horario: lunes a viernes de 9 a 6, sábados con cita. Llame al (305) 859-3953 o escriba por WhatsApp al (971) 998-7313. Un agente le devuelve la llamada en menos de una hora si nos escribe en horario de oficina.' },
      ],
      faqTitle: 'Seguro de casa en Cutler Bay: preguntas frecuentes',
      faq: [
        { q: '¿Mi casa en Cutler Bay está en zona de marejada?', a: 'Muchas lo están, sobre todo al este de la antigua Cutler Ridge, hacia la bahía de Biscayne. Busque su dirección en el mapa de zonas de marejada y en el mapa de zonas de inundación del Condado de Miami-Dade. Recuerde que la póliza de casa no cubre los daños por marejada: para eso necesita seguro de inundación.' },
        { q: 'Mi casa es de los años 80. ¿Qué reviso primero?', a: 'Empiece por la edad y el permiso del techo, una inspección de mitigación de viento, su límite de leyes y ordenanzas y si la cobertura de la vivienda todavía alcanza para reconstruir hoy. Las casas viejas suelen ganar más documentando las mejoras que se hicieron después.' },
        { q: '¿Qué es la cobertura de leyes y ordenanzas?', a: 'Cuando se daña parte de una casa, el código actual puede exigir mejoras en el resto. La cobertura de leyes y ordenanzas paga esos costos obligatorios. En Florida, la aseguradora debe ofrecer límites del 25% o del 50% de la cobertura de la vivienda.' },
        { q: '¿Necesito seguro de inundación si no estoy en zona de alto riesgo?', a: 'El banco solo lo exige en zonas de alto riesgo, pero también hay inundaciones fuera de ellas, y la póliza de casa no las cubre. En zonas de menor riesgo las pólizas suelen ser más accesibles, y la del NFIP normalmente empieza 30 días después de comprarla.' },
        { q: '¿Cuánto tiempo tengo para reportar daños por huracán?', a: 'Según la ley de Florida, el aviso de un reclamo nuevo debe darse dentro de un año desde la fecha de la pérdida, que en un huracán es el día de la entrada a tierra. Los reclamos reabiertos o suplementarios tienen 18 meses. Repórtelo en cuanto pueda hacerlo con seguridad.' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Страховка дома в Cutler Bay, FL | M&K Agency',
      metaDesc: 'Страховка дома в Cutler Bay: дома 1980-х, закон о возрасте крыши, зоны нагонной волны у залива Biscayne, ураганная франшиза и бесплатная проверка полиса.',
      breadcrumb: 'Cutler Bay',
      kicker: 'Страховка дома · Cutler Bay, FL',
      h1a: 'Страховка дома в Cutler Bay, FL —',
      h1b: 'для домов постарше и поближе к заливу.',
      sub: 'Многие дома в Cutler Bay построены ещё до Andrew, а часть города лежит ниже старого хребта, у самого залива Biscayne. Проверим крышу, франшизы и риск наводнения и поможем с клеймом. По-русски, по-английски или по-испански.',
      serviceType: 'Страхование дома',
      intro: [
        { type: 'h2', text: 'Город частных домов, во многом построенных до 1990 года' },
        { type: 'p', text: 'Cutler Bay — прежде всего город частных домов. По оценкам переписи за 2020–2024 годы, около двух третей жилья — отдельные дома на одну семью, и примерно в 70% живут сами владельцы — это один из самых высоких показателей на юге Miami-Dade. И дома здесь старше, чем в соседнем Homestead: медианный год постройки — около **1984**, около 57% построено до 1990 года и лишь около трети — в 2000-м или позже.' },
        { type: 'p', text: 'Это важно. Большинство этих домов уже стояли, когда ураган Andrew, позже отнесённый к 5-й категории, вышел на сушу чуть южнее, 24 августа 1992 года. Многие потом ремонтировали или отстраивали заново — в разное время и по разным нормам, поэтому у двух домов на одной улице могут быть совершенно разные крыши, окна и крепления крыши к стенам. Страховые учитывают эту разницу в цене, и поэтому каждую проверку в Cutler Bay мы начинаем с самого дома.' },
        { type: 'p', text: 'Вторая половина истории — рельеф. Старое название города происходит от **Cutler Ridge** — известнякового хребта высотой около 14 футов. Восточнее, ближе к заливу Biscayne, земля ниже и открыта нагонной волне (storm surge), и значительная часть Cutler Bay входит в зоны планирования на случай нагонной волны округа Miami-Dade. Во время Andrew самый высокий штормовой прилив в округе — 16.9 фута — был зафиксирован на берегу залива, чуть севернее нынешних границ города.' },
      ],
      checklistTitle: 'Что мы проверяем в полисах на дома в Cutler Bay',
      checklist: [
        '**Возраст крыши и дата разрешения (permit).** С крышей старше 15 лет могут быть проблемы при продлении, если инспекция не подтвердит оставшийся срок службы.',
        '**Инспекция wind mitigation**, которая фиксирует все улучшения: ударопрочные окна или ставни, перебитый настил крыши, ураганные крепления.',
        '**Law and ordinance на 50%, а не на 25%** для старого дома: восстановление по действующему коду может стоить намного дороже обычного ремонта.',
        '**Покрытие дома по нынешней стоимости восстановления.** Стройка в Южной Флориде дорожала быстрее, чем обновлялись многие полисы.',
        '**Страховка от наводнения**, особенно к востоку от хребта. Полис на дом не покрывает ни наводнение, ни нагонную волну.',
        '**Ураганная франшиза в долларах** — и сможете ли вы её заплатить после шторма.',
        '**Лимиты и исключения по ущербу от воды** при старых трубах и медленных протечках.',
        '**Бассейн, screen enclosure и заборы** — у них могут быть отдельные лимиты.',
        '**Personal liability** на случай травмы гостя, у бассейна или из-за собаки.',
      ],
      body: [
        { type: 'h2', text: 'Старые крыши и закон Флориды о возрасте крыши' },
        { type: 'p', text: 'Для полисов, выданных или продлённых с 1 июля 2022 года, страховая во Флориде не может отказать в страховке или продлении только из-за возраста крыши, если ей меньше 15 лет. Если ваша крыша старше, её можно проинспектировать, и если инспекция покажет не менее пяти лет оставшегося срока службы, отказать только по возрасту крыши нельзя. Кроме того, закон допускает в некоторых полисах отдельную франшизу на крышу — не больше меньшей из двух сумм: 2% от покрытия дома или 50% стоимости замены крыши. Она не применяется к ущербу от урагана, к дереву, пробившему крышу, и к ремонту менее половины крыши. Посмотрите declarations page, есть ли она у вас.' },
        { type: 'h2', text: 'Кредиты за ветроустойчивость' },
        { type: 'p', text: 'Страховые обязаны включать обоснованные кредиты за элементы, снижающие ущерб от ветра, а в государственной форме инспекции весь Miami-Dade считается зоной High-Velocity Hurricane Zone. У старых домов кредиты обычно дают не исходная постройка, а последующие улучшения: защита окон и дверей, крепление настила новой крыши, дополнительный гидробарьер (secondary water resistance) и связь крыши со стенами. Отчёт действует до пяти лет, если ничего существенно не менялось. По программе **My Safe Florida Home** подходящие владельцы могут получить бесплатную инспекцию, а при соответствии условиям — грант на часть улучшений.' },
        { type: 'h2', text: 'Нагонная волна и наводнение' },
        { type: 'p', text: 'Любой полис на дом исключает наводнение, а нагонная волна — это наводнение. Зоны планирования Miami-Dade на случай нагонной волны (от A до E) показывают, каким районам могут объявить эвакуацию, а карты затопления округа — вашу официальную flood zone; действующие карты вступили в силу в 2009 году, а предварительные обновления пока не действуют. У полиса NFIP обычно 30 дней ожидания, так что покупать его нужно задолго до шторма.' },
        { type: 'h2', text: 'Ураганная франшиза и клеймы' },
        { type: 'p', text: 'Во Флориде ураганную франшизу предлагают в размере $500 или 2%, 5% либо 10% от покрытия дома, и она применяется раз в календарный год. О новом клейме нужно заявить в течение года с даты ущерба (для урагана — с даты выхода на сушу), о дополнительном — в течение 18 месяцев.' },
        { type: 'p', text: 'M&K Agency — семейное агентство: 12 человек в команде и более 5,000 клиентов по всей Флориде. **Пришлите нам свой полис — мы проверим покрытие.** Расскажем, где старый дом уязвим, что может изменить инспекция и сколько составляют ваши франшизы в долларах. Когда шторм пройдёт, вы звоните нам, и мы помогаем подать клейм и проследить за ним.' },
      ],
      officeTitle: 'Обслуживаем Cutler Bay из Florida City',
      office: [
        { type: 'p', text: 'Офиса в Cutler Bay у нас нет: мы обслуживаем владельцев домов в Cutler Bay из офиса по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, примерно в 12.5 мили от мэрии Cutler Bay. Это около 20 минут по Turnpike без пробок или подольше по US-1. Чаще всего проверка идёт через WhatsApp или почту: пришлите фото declarations page и отчётов об инспекциях.' },
        { type: 'p', text: 'Часы работы: понедельник–пятница с 9 до 6, суббота — по записи. Звоните (305) 859-3953 или пишите в WhatsApp: (971) 998-7313. На заявки в рабочее время агент перезванивает в течение часа.' },
      ],
      faqTitle: 'Страховка дома в Cutler Bay: частые вопросы',
      faq: [
        { q: 'Находится ли мой дом в Cutler Bay в зоне нагонной волны?', a: 'Многие дома — да, особенно к востоку от старого хребта Cutler Ridge, в сторону залива Biscayne. Найдите свой адрес на карте зон нагонной волны и на карте зон затопления округа Miami-Dade. И помните: полис на дом ущерб от нагонной волны не покрывает, для этого нужна страховка от наводнения.' },
        { q: 'Мой дом построен в 1980-х. Что проверить в первую очередь?', a: 'Возраст крыши и дату разрешения, инспекцию wind mitigation, лимит law and ordinance и то, хватает ли покрытия дома на восстановление по сегодняшним ценам. Старым домам обычно больше всего помогает документальное подтверждение сделанных позже улучшений.' },
        { q: 'Что такое law and ordinance?', a: 'Когда повреждена часть дома, действующий строительный код может потребовать модернизировать и остальное. Покрытие law and ordinance оплачивает эти обязательные расходы. Во Флориде страховая должна предложить лимит 25% или 50% от покрытия дома.' },
        { q: 'Нужна ли страховка от наводнения, если я не в зоне высокого риска?', a: 'Банк требует её только в зонах высокого риска, но наводнения бывают и за их пределами, а полис на дом их не покрывает. В зонах пониженного риска полисы обычно доступнее, а покрытие NFIP, как правило, начинает действовать через 30 дней после покупки.' },
        { q: 'Сколько времени есть, чтобы заявить об ущербе от урагана?', a: 'По закону Флориды о новом клейме нужно заявить в течение года с даты ущерба — для урагана это дата выхода на сушу. Для повторно открытых и дополнительных клеймов — 18 месяцев. Сообщайте, как только это станет безопасно.' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
