import type { CityPage } from './types';
import { sources } from './sources';

// /[lang]/homeowners-insurance-kendall-fl. Local facts checked 2026-10-03 (see sources).
const SRC = ['andrew', 'acsKendall', 'condoMaster', 'lossAssessment', 'condoInspections', 'roofAge', 'deductibles', 'windForm', 'mitigation', 'claimDeadline', 'floodsmart', 'mdFloodMaps'] as const;

export const HOME_KENDALL: CityPage = {
  path: '/homeowners-insurance-kendall-fl',
  line: 'home',
  kind: 'city',
  area: 'kendall',
  parent: '/homeowners-insurance-miami-dade-county-fl',
  heroImage: 'condo-11',
  published: '2026-10-03',
  modified: '2026-10-03',
  areaServed: [
    { '@type': 'Place', name: 'Kendall, FL' },
    { '@type': 'AdministrativeArea', name: 'Miami-Dade County, FL' },
  ],
  copy: {
    en: {
      metaTitle: 'Home & Condo Insurance in Kendall, FL | M&K Agency',
      metaDesc: 'Home and condo (HO-6) insurance in Kendall: master policy gaps, loss assessment, 1970s–80s homes and roofs, hurricane deductibles and a free policy review.',
      breadcrumb: 'Kendall',
      kicker: 'Home & condo insurance · Kendall, FL',
      h1a: 'Home and condo insurance in Kendall, FL,',
      h1b: 'whether you own a house or a unit.',
      sub: 'Kendall has older single-family homes and a lot of condos and townhomes. We read your policy next to your association documents, find what is missing and help you if you ever file a claim. English, Spanish or Russian.',
      serviceType: 'Homeowners and condo insurance',
      intro: [
        { type: 'h2', text: 'Kendall’s housing is older and more mixed than most of South Dade' },
        { type: 'p', text: 'Kendall grew mostly in the 1970s and 1980s. Census estimates for 2020–2024 put the median year built at **1978**: roughly 81% of homes were built before 1990 and fewer than one in ten in 2000 or later. Only about 40% are detached houses. Around 16% are townhomes and other attached homes, about 44% are in buildings with two or more units, and roughly a third are in buildings with ten or more units. About 62% of homes are owner-occupied.' },
        { type: 'p', text: 'In practice that means two very different insurance situations on the same street. A house owner in Kendall insures the whole structure and deals with roof age, older plumbing and code upgrades. A condo owner shares a building with dozens of neighbors, depends on the association’s master policy, and needs a unit-owner policy (HO-6) that fills in what the master policy leaves out. Townhome owners can fall on either side, depending on the association documents.' },
        { type: 'p', text: 'The hurricane history is the same for both. The National Hurricane Center describes Andrew’s 1992 impact as extreme from the Kendall area south through Homestead and Florida City. Most of Kendall’s homes and buildings were already standing then, and many were repaired or re-roofed afterward.' },
      ],
      checklistTitle: 'What we check for Kendall homeowners and condo owners',
      checklist: [
        '**Condo owners: what the master policy excludes.** Florida law says the association’s policy does not cover your flooring, cabinets, countertops, appliances, water heater, fixtures or belongings inside the unit.',
        '**Loss assessment coverage** above the $2,000 legal minimum, in case the association passes part of a covered loss or its deductible to owners.',
        '**The association’s deductible**, especially the hurricane deductible, which can be large on a building policy.',
        '**Water damage from a neighboring unit** and liability if water from your unit damages someone else’s.',
        '**House owners: roof age and permit date**, and a roof inspection if the roof is over 15 years old.',
        '**Law and ordinance coverage** for older houses that would need code upgrades after damage.',
        '**A wind mitigation inspection** for any house or townhome with opening protection or a newer roof.',
        '**Dwelling or unit coverage at current rebuilding cost**, not market value.',
        '**Flood insurance**: excluded from every homeowners and condo policy.',
      ],
      body: [
        { type: 'h2', text: 'Condo owners: your policy starts where the association’s ends' },
        { type: 'p', text: 'Under Florida’s condominium law, the association must insure the building and common elements, but its policy must exclude personal property inside units and items such as floor, wall and ceiling coverings, electrical fixtures, appliances, water heaters, built-in cabinets and countertops, and window treatments. Those are the owner’s responsibility. Your HO-6 policy should cover them at replacement cost, along with your belongings, your liability and loss of use if the unit becomes uninhabitable.' },
        { type: 'p', text: 'Florida requires unit-owner policies to include at least **$2,000 of loss assessment coverage**, which pays your share when the association assesses owners for a covered loss. It does not cover routine special assessments for maintenance or repairs. Many Kendall buildings are well past 25 or 30 years old, so they fall under the state’s **milestone inspection** rules for buildings of three or more habitable stories, and they must complete a **structural integrity reserve study (SIRS)**. Those reports can lead to repairs, special assessments or loans. Insurance does not pay for them, but knowing they are coming helps you plan.' },
        { type: 'h2', text: 'House owners: roofs, codes and wind credits' },
        { type: 'p', text: 'Since July 1, 2022, an insurer cannot refuse to write or renew a Florida home only because its roof is under 15 years old, and an older roof that passes an inspection showing five or more years of remaining life cannot be refused on age alone. Insurers must offer law and ordinance coverage of 25% or 50% of the dwelling limit; for a 1970s house, 50% is usually worth a look. Miami-Dade is a High-Velocity Hurricane Zone, and insurers must give actuarially reasonable credits for documented wind-resistant features, so a wind mitigation report (valid up to five years) is worth having after any roof replacement or window upgrade.' },
        { type: 'h2', text: 'Deductibles, flood and claims' },
        { type: 'p', text: 'Hurricane deductibles in Florida are offered at $500 or 2%, 5% or 10% of the dwelling limit and apply once per calendar year. Flood is excluded from homeowners and condo policies; Kendall is inland, but heavy rain floods low streets, ground floors and parking areas, and the association’s flood policy, if it has one, protects the building, not your unit’s contents. NFIP policies usually take 30 days to start. New claims must be reported within one year of the date of loss, and condo loss-assessment claims have their own deadline tied to the association’s assessment.' },
        { type: 'p', text: 'M&K Agency is family-owned, with a team of 12 and more than 5,000 clients across Florida. **Send us your policy and we’ll check your coverage**, and send the association’s insurance summary too if you own a condo. We will show you exactly where the gaps are, and when there is a claim we help you deal with both your insurer and the association.' },
      ],
      officeTitle: 'Serving Kendall from Florida City',
      office: [
        { type: 'p', text: 'We do not have an office in Kendall. We serve Kendall from our office at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, about 20 miles south. In light traffic it is around 26 to 30 minutes via the Don Shula Expressway and the Turnpike, longer at rush hour, so most Kendall clients work with us by phone, WhatsApp, text and email.' },
        { type: 'p', text: 'Office hours are Monday to Friday, 9 to 6, and Saturday by appointment. Call (305) 859-3953 or WhatsApp (971) 998-7313. If you write during business hours, an agent calls you back within an hour.' },
      ],
      faqTitle: 'Home and condo insurance in Kendall: common questions',
      faq: [
        { q: 'My condo association has insurance. Why do I need my own policy?', a: 'Florida law requires the association’s policy to exclude what is inside your unit: flooring, wall and ceiling coverings, cabinets, countertops, appliances, water heaters, fixtures and your belongings. An HO-6 policy covers those, your liability and your living costs if you have to move out during repairs.' },
        { q: 'What is loss assessment coverage?', a: 'It pays your share when the association charges owners for a covered loss, for example part of a large hurricane deductible. Florida unit-owner policies must include at least $2,000, and higher limits are available. It does not pay for routine maintenance or reserve-related assessments.' },
        { q: 'Does insurance pay for special assessments after a milestone inspection?', a: 'Generally no. Assessments for repairs found in a milestone inspection or a structural integrity reserve study are maintenance costs, not insured losses. Loss assessment coverage applies to assessments for covered losses.' },
        { q: 'My Kendall house is from the 1970s. What matters most for insurance?', a: 'The roof age and condition, the age of plumbing and electrical systems, law and ordinance coverage for code upgrades, any documented wind-resistant features, and a dwelling limit that matches today’s rebuilding cost.' },
        { q: 'Do I need flood insurance for a condo on an upper floor?', a: 'Your unit is unlikely to take on water directly, but the building may, and the association could assess owners for uninsured flood damage. A flood policy for your unit can also cover your contents. Check the association’s flood coverage first.' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Seguro de Casa y Condominio en Kendall, FL | M&K Agency',
      metaDesc: 'Seguro de casa y condominio (HO-6) en Kendall: lo que la póliza maestra le deja, loss assessment, casas de los 70 y 80, deducible de huracán y revisión gratis.',
      breadcrumb: 'Kendall',
      kicker: 'Seguro de casa y condominio · Kendall, FL',
      h1a: 'Seguro de casa y condominio en Kendall, FL,',
      h1b: 'tenga casa o apartamento.',
      sub: 'En Kendall hay casas con años y muchísimos condominios y townhouses. Leemos su póliza al lado de los documentos de la asociación, encontramos lo que falta y le ayudamos si un día tiene un reclamo. En español, inglés o ruso.',
      serviceType: 'Seguro de casa y de condominio',
      intro: [
        { type: 'h2', text: 'Las viviendas de Kendall son más viejas y más variadas que en el resto del sur' },
        { type: 'p', text: 'Kendall creció sobre todo en los años 70 y 80. Según las estimaciones del Censo para 2020–2024, la vivienda típica se construyó en **1978**: cerca del 81% es anterior a 1990 y menos de una de cada diez es del 2000 en adelante. Solo un 40% son casas independientes. Alrededor del 16% son townhouses y otras casas adosadas, cerca del 44% está en edificios de dos o más unidades y aproximadamente un tercio en edificios de diez o más. Los dueños viven en cerca del 62% de las viviendas.' },
        { type: 'p', text: 'En la práctica, eso significa dos situaciones de seguro muy distintas en la misma calle. Quien tiene una casa asegura toda la estructura y tiene que pensar en la edad del techo, las tuberías viejas y las mejoras que exige el código. Quien tiene un condominio comparte el edificio con decenas de vecinos, depende de la póliza maestra de la asociación y necesita una póliza de propietario de unidad (HO-6) que cubra lo que la maestra deja por fuera. Los townhouses pueden caer en un lado o en el otro, según los documentos de la asociación.' },
        { type: 'p', text: 'La historia de huracanes es la misma para todos. Según el Centro Nacional de Huracanes, el impacto de Andrew en 1992 fue extremo desde la zona de Kendall hacia el sur, hasta Homestead y Florida City. La mayoría de las casas y edificios de Kendall ya existía entonces, y muchos se repararon o les cambiaron el techo después.' },
      ],
      checklistTitle: 'Lo que revisamos a propietarios de casas y condominios en Kendall',
      checklist: [
        '**Condominios: lo que excluye la póliza maestra.** La ley de Florida dice que la póliza de la asociación no cubre sus pisos, gabinetes, topes de cocina, electrodomésticos, calentador de agua, lámparas ni sus pertenencias dentro de la unidad.',
        '**Cobertura de loss assessment** por encima del mínimo legal de $2,000, por si la asociación les pasa a los dueños parte de una pérdida cubierta o de su deducible.',
        '**El deducible de la asociación**, sobre todo el de huracán, que en una póliza de edificio puede ser muy alto.',
        '**Daños por agua que vienen de otra unidad**, y su responsabilidad si el agua de su apartamento daña el de un vecino.',
        '**Casas: edad y permiso del techo**, y una inspección si el techo tiene más de 15 años.',
        '**Leyes y ordenanzas** para casas viejas que necesitarían mejoras de código después de un daño.',
        '**Inspección de mitigación de viento** para casas o townhouses con protección de ventanas o techo más nuevo.',
        '**Cobertura de la vivienda o de la unidad al costo actual de reconstrucción**, no al valor de mercado.',
        '**Seguro de inundación**: ninguna póliza de casa ni de condominio lo incluye.',
      ],
      body: [
        { type: 'h2', text: 'Condominios: su póliza empieza donde termina la de la asociación' },
        { type: 'p', text: 'Según la ley de condominios de Florida, la asociación debe asegurar el edificio y las áreas comunes, pero su póliza tiene que excluir los bienes personales dentro de las unidades y elementos como los revestimientos de pisos, paredes y techos, las instalaciones eléctricas, los electrodomésticos, los calentadores de agua, los gabinetes y topes empotrados y las cortinas o persianas. Todo eso le corresponde al dueño. Su póliza HO-6 debería cubrirlo al costo de reposición, junto con sus pertenencias, su responsabilidad civil y los gastos de vivienda si la unidad queda inhabitable.' },
        { type: 'p', text: 'Florida exige que las pólizas de propietario de unidad incluyan al menos **$2,000 de cobertura de loss assessment**, que paga su parte cuando la asociación les cobra a los dueños por una pérdida cubierta. No cubre las cuotas especiales normales de mantenimiento o reparación. Muchos edificios de Kendall tienen bastante más de 25 o 30 años, así que están sujetos a las **inspecciones de hito (milestone)** que el estado exige para edificios de tres o más pisos habitables, y deben completar un **estudio de reservas de integridad estructural (SIRS)**. Esos informes pueden terminar en reparaciones, cuotas especiales o préstamos. El seguro no los paga, pero saber que vienen le ayuda a planificar.' },
        { type: 'h2', text: 'Casas: techos, códigos y créditos por viento' },
        { type: 'p', text: 'Desde el 1 de julio de 2022, una aseguradora no puede negarse a asegurar o renovar una casa en Florida solo porque el techo tiene menos de 15 años, y un techo más viejo que pase una inspección con cinco o más años de vida útil no puede rechazarse solo por la edad. Las aseguradoras deben ofrecer leyes y ordenanzas al 25% o al 50% de la cobertura de la vivienda; en una casa de los 70, conviene mirar el 50%. Miami-Dade es Zona de Huracanes de Alta Velocidad, y las aseguradoras deben dar créditos razonables por las características resistentes al viento que estén documentadas, así que vale la pena tener un informe de mitigación (vigente hasta cinco años) después de cambiar el techo o las ventanas.' },
        { type: 'h2', text: 'Deducibles, inundación y reclamos' },
        { type: 'p', text: 'En Florida, los deducibles de huracán se ofrecen de $500 o del 2%, 5% o 10% de la cobertura y se aplican una vez por año calendario. La inundación está excluida de las pólizas de casa y de condominio; Kendall no está en la costa, pero los aguaceros inundan calles bajas, primeros pisos y estacionamientos, y la póliza de inundación de la asociación, si existe, protege el edificio, no el contenido de su unidad. Las pólizas del NFIP suelen tardar 30 días en empezar. Los reclamos nuevos deben avisarse dentro de un año desde la pérdida, y los de loss assessment de condominio tienen su propio plazo, ligado a la cuota que apruebe la asociación.' },
        { type: 'p', text: 'M&K Agency es una agencia familiar con un equipo de 12 personas y más de 5,000 clientes en Florida. **Envíenos su póliza y la revisamos**, y si tiene condominio, mándenos también el resumen del seguro de la asociación. Le mostramos con exactitud dónde están los vacíos, y cuando hay un reclamo le ayudamos a tratar tanto con su aseguradora como con la asociación.' },
      ],
      officeTitle: 'Atendemos Kendall desde Florida City',
      office: [
        { type: 'p', text: 'No tenemos oficina en Kendall. Atendemos a Kendall desde nuestra oficina en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, unas 20 millas al sur. Sin tráfico son de 26 a 30 minutos por la Don Shula Expressway y el Turnpike, más en hora pico, así que la mayoría de nuestros clientes de Kendall trabaja con nosotros por teléfono, WhatsApp, texto y correo.' },
        { type: 'p', text: 'Horario: lunes a viernes de 9 a 6, sábados con cita. Llame al (305) 859-3953 o escriba por WhatsApp al (971) 998-7313. Si nos escribe en horario de oficina, un agente le llama en menos de una hora.' },
      ],
      faqTitle: 'Seguro de casa y condominio en Kendall: preguntas frecuentes',
      faq: [
        { q: 'Mi asociación de condominio tiene seguro. ¿Para qué necesito el mío?', a: 'La ley de Florida obliga a que la póliza de la asociación excluya lo que está dentro de su unidad: pisos, revestimientos de paredes y techos, gabinetes, topes, electrodomésticos, calentador de agua, lámparas y sus pertenencias. Una póliza HO-6 cubre todo eso, su responsabilidad civil y sus gastos si tiene que mudarse durante las reparaciones.' },
        { q: '¿Qué es la cobertura de loss assessment?', a: 'Paga su parte cuando la asociación les cobra a los dueños por una pérdida cubierta, por ejemplo una parte de un deducible de huracán grande. En Florida, las pólizas de unidad deben incluir al menos $2,000, y se pueden contratar límites más altos. No paga mantenimiento normal ni cuotas para reservas.' },
        { q: '¿El seguro paga las cuotas especiales después de una inspección de hito?', a: 'En general, no. Las cuotas para reparaciones que aparecen en una inspección de hito o en un estudio de reservas estructurales son costos de mantenimiento, no pérdidas aseguradas. La cobertura de loss assessment aplica a cuotas por pérdidas cubiertas.' },
        { q: 'Mi casa en Kendall es de los años 70. ¿Qué es lo más importante para el seguro?', a: 'La edad y el estado del techo, la edad de la plomería y la electricidad, la cobertura de leyes y ordenanzas para las mejoras de código, las características resistentes al viento que estén documentadas y una cobertura de la vivienda que alcance para reconstruir a precios de hoy.' },
        { q: '¿Necesito seguro de inundación para un condominio en un piso alto?', a: 'Es poco probable que el agua entre directo a su unidad, pero sí al edificio, y la asociación podría cobrarles a los dueños los daños por inundación no asegurados. Una póliza de inundación para su unidad también puede cubrir sus pertenencias. Primero revise qué cobertura de inundación tiene la asociación.' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Страховка дома и кондо в Kendall, FL | M&K Agency',
      metaDesc: 'Страховка дома и кондо (HO-6) в Kendall: что мастер-полис оставляет вам, loss assessment, дома 1970–80-х, ураганная франшиза и бесплатная проверка полиса.',
      breadcrumb: 'Kendall',
      kicker: 'Страховка дома и кондо · Kendall, FL',
      h1a: 'Страховка дома и кондо в Kendall, FL —',
      h1b: 'будь у вас дом или квартира.',
      sub: 'В Kendall много старых частных домов, кондо и таунхаусов. Мы читаем ваш полис рядом с документами ассоциации, находим, чего не хватает, и помогаем, если понадобится клейм. По-русски, по-английски или по-испански.',
      serviceType: 'Страхование дома и кондо',
      intro: [
        { type: 'h2', text: 'Жильё в Kendall старше и разнообразнее, чем на остальном юге округа' },
        { type: 'p', text: 'Kendall в основном застраивался в 1970–80-х. По оценкам переписи за 2020–2024 годы, медианный год постройки — **1978**: около 81% жилья построено до 1990 года и меньше одного из десяти — в 2000-м или позже. Отдельных домов только около 40%. Примерно 16% — таунхаусы и другие сблокированные дома, около 44% жилья — в зданиях на две квартиры и больше, и примерно треть — в домах на десять и более квартир. Около 62% жилья занимают сами владельцы.' },
        { type: 'p', text: 'На практике это две совершенно разные страховые ситуации на одной улице. Владелец дома страхует всё строение и думает о возрасте крыши, старых трубах и модернизации по коду. Владелец кондо делит здание с десятками соседей, зависит от мастер-полиса ассоциации и нуждается в полисе владельца квартиры (HO-6), который закрывает то, что мастер-полис не покрывает. Таунхаусы могут оказаться и там, и там — всё зависит от документов ассоциации.' },
        { type: 'p', text: 'История ураганов у всех одна. По описанию Национального центра ураганов, удар Andrew в 1992 году был катастрофическим от района Kendall на юг, до Homestead и Florida City. Большинство домов и зданий Kendall тогда уже стояли, и многие потом ремонтировали или перекрывали.' },
      ],
      checklistTitle: 'Что мы проверяем у владельцев домов и кондо в Kendall',
      checklist: [
        '**Кондо: что исключено из мастер-полиса.** По закону Флориды полис ассоциации не покрывает ваши полы, шкафы, столешницы, бытовую технику, водонагреватель, светильники и вещи внутри квартиры.',
        '**Loss assessment** сверх законного минимума $2,000 — на случай, если ассоциация разложит на владельцев часть застрахованного ущерба или свою франшизу.',
        '**Франшиза ассоциации**, особенно ураганная: в полисе на здание она может быть очень большой.',
        '**Залив от соседей** и ваша ответственность, если вода из вашей квартиры повредит чужую.',
        '**Дома: возраст крыши и дата разрешения (permit)**, а для крыши старше 15 лет — инспекция.',
        '**Law and ordinance** для старых домов, которым после ущерба потребуется модернизация по коду.',
        '**Инспекция wind mitigation** для дома или таунхауса с защитой окон или более новой крышей.',
        '**Покрытие дома или квартиры по стоимости восстановления**, а не по рыночной цене.',
        '**Страховка от наводнения**: её нет ни в одном полисе на дом или кондо.',
      ],
      body: [
        { type: 'h2', text: 'Кондо: ваш полис начинается там, где заканчивается полис ассоциации' },
        { type: 'p', text: 'По закону Флориды о кондоминиумах ассоциация обязана страховать здание и общие элементы, но её полис должен исключать личное имущество в квартирах и такие вещи, как покрытия полов, стен и потолков, электрические светильники, бытовую технику, водонагреватели, встроенные шкафы и столешницы, шторы и жалюзи. Всё это — ответственность владельца. Ваш полис HO-6 должен покрывать это по replacement cost, а вместе с этим — ваши вещи, вашу ответственность и проживание, если в квартире нельзя жить.' },
        { type: 'p', text: 'Флорида требует, чтобы полис владельца квартиры включал не менее **$2,000 покрытия loss assessment**: оно оплачивает вашу долю, когда ассоциация собирает с владельцев деньги на застрахованный ущерб. Обычные спецвзносы (special assessments) на обслуживание и ремонт оно не покрывает. Многим зданиям в Kendall давно больше 25–30 лет, поэтому на них распространяются государственные **milestone inspections** для зданий от трёх жилых этажей, и они обязаны провести **SIRS** — исследование резервов на конструктивную целостность. По итогам могут потребоваться ремонт, спецвзносы или кредиты. Страховка за это не платит, но, зная заранее, проще спланировать бюджет.' },
        { type: 'h2', text: 'Дома: крыши, код и кредиты за ветроустойчивость' },
        { type: 'p', text: 'С 1 июля 2022 года страховая во Флориде не может отказать в страховке или продлении только из-за возраста крыши, если ей меньше 15 лет, а более старой крыше, прошедшей инспекцию с запасом службы от пяти лет, нельзя отказать только по возрасту. Страховые обязаны предлагать law and ordinance на 25% или 50% от покрытия дома; для дома 1970-х стоит присмотреться к 50%. Miami-Dade — зона High-Velocity Hurricane Zone, и страховые должны давать обоснованные кредиты за подтверждённые ветроустойчивые элементы, поэтому после замены крыши или окон полезно сделать отчёт wind mitigation (действует до пяти лет).' },
        { type: 'h2', text: 'Франшизы, наводнение и клеймы' },
        { type: 'p', text: 'Ураганную франшизу во Флориде предлагают в размере $500 или 2%, 5% либо 10% от покрытия, и применяется она раз в календарный год. Наводнение исключено из полисов на дом и кондо. Kendall не на побережье, но ливни заливают низкие улицы, первые этажи и парковки, а полис ассоциации от наводнения, если он вообще есть, защищает здание, но не содержимое вашей квартиры. Полисы NFIP обычно начинают действовать через 30 дней. О новом клейме нужно заявить в течение года с даты ущерба, а у клеймов по loss assessment в кондо свой срок, привязанный к решению ассоциации о взносе.' },
        { type: 'p', text: 'M&K Agency — семейное агентство: 12 человек в команде и более 5,000 клиентов по всей Флориде. **Пришлите нам свой полис — мы проверим покрытие**, а если у вас кондо, пришлите и сводку страховки ассоциации. Мы точно покажем, где пробелы, а при клейме поможем общаться и со страховой, и с ассоциацией.' },
      ],
      officeTitle: 'Обслуживаем Kendall из Florida City',
      office: [
        { type: 'p', text: 'Офиса в Kendall у нас нет: мы обслуживаем Kendall из офиса по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, примерно в 20 милях к югу. Без пробок это 26–30 минут по Don Shula Expressway и Turnpike, в час пик дольше, поэтому большинство клиентов из Kendall работают с нами по телефону, в WhatsApp, по SMS и почте.' },
        { type: 'p', text: 'Часы работы: понедельник–пятница с 9 до 6, суббота — по записи. Звоните (305) 859-3953 или пишите в WhatsApp: (971) 998-7313. Если напишете в рабочее время, агент перезвонит в течение часа.' },
      ],
      faqTitle: 'Страховка дома и кондо в Kendall: частые вопросы',
      faq: [
        { q: 'У ассоциации кондо есть страховка. Зачем мне своя?', a: 'Закон Флориды требует, чтобы полис ассоциации исключал всё, что внутри вашей квартиры: полы, покрытия стен и потолков, шкафы, столешницы, технику, водонагреватель, светильники и ваши вещи. Полис HO-6 покрывает это, вашу ответственность и расходы на жильё, если на время ремонта придётся съехать.' },
        { q: 'Что такое loss assessment?', a: 'Это покрытие вашей доли, когда ассоциация собирает с владельцев деньги на застрахованный ущерб — например, часть большой ураганной франшизы. Во Флориде полис владельца квартиры должен включать не менее $2,000, можно взять и больше. Обычное обслуживание и взносы в резервы оно не оплачивает.' },
        { q: 'Платит ли страховка спецвзносы после milestone inspection?', a: 'Как правило, нет. Взносы на ремонт, выявленный milestone inspection или SIRS, — это расходы на содержание, а не страховой случай. Loss assessment применяется к взносам на застрахованный ущерб.' },
        { q: 'Мой дом в Kendall построен в 1970-х. Что важнее всего для страховки?', a: 'Возраст и состояние крыши, возраст сантехники и электрики, покрытие law and ordinance на модернизацию по коду, подтверждённые ветроустойчивые элементы и лимит по дому, которого хватит на восстановление по сегодняшним ценам.' },
        { q: 'Нужна ли страховка от наводнения для кондо на высоком этаже?', a: 'Вашу квартиру вода вряд ли зальёт напрямую, а вот здание — может, и ассоциация может разложить на владельцев незастрахованный ущерб от наводнения. Полис от наводнения на квартиру может покрыть и ваши вещи. Сначала узнайте, какая страховка от наводнения есть у ассоциации.' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
