import type { CityPage } from './types';
import { sources } from './sources';

// /[lang]/homeowners-insurance-homestead-fl. Local facts checked 2026-10-03 (see sources).
const SRC = ['andrew', 'andrewCat5', 'acsHomestead', 'windForm', 'mitigation', 'roofAge', 'deductibles', 'claimDeadline', 'floodsmart', 'mdFloodMaps', 'msfh', 'homesteadCity'] as const;

export const HOME_HOMESTEAD: CityPage = {
  path: '/homeowners-insurance-homestead-fl',
  line: 'home',
  kind: 'city',
  area: 'homestead',
  parent: '/homeowners-insurance-miami-dade-county-fl',
  heroImage: 'home-12',
  published: '2026-10-03',
  modified: '2026-10-03',
  areaServed: [
    { '@type': 'City', name: 'Homestead, FL' },
    { '@type': 'AdministrativeArea', name: 'Miami-Dade County, FL' },
  ],
  copy: {
    en: {
      metaTitle: 'Homeowners Insurance in Homestead, FL | M&K Agency',
      metaDesc: 'Homeowners insurance for Homestead: what Andrew changed, wind mitigation credits for newer homes, hurricane deductibles, flood gaps and a free review of your policy.',
      breadcrumb: 'Homestead',
      kicker: 'Homeowners insurance · Homestead, FL',
      h1a: 'Homeowners insurance in Homestead, FL,',
      h1b: 'from people who know what a hurricane does.',
      sub: 'Most Homestead homes were built or rebuilt after Andrew. We make sure your policy gets credit for that, explain your hurricane deductible in dollars and help you when you have a claim. English, Spanish or Russian.',
      serviceType: 'Homeowners insurance',
      intro: [
        { type: 'h2', text: 'Homestead was rebuilt after 1992' },
        { type: 'p', text: 'Hurricane Andrew made landfall just east of Homestead on August 24, 1992. NOAA later upgraded it to Category 5, with estimated sustained winds of 165 mph. The National Hurricane Center describes the impact as extreme from Kendall south through Homestead and Florida City: across Miami-Dade, about 25,500 homes were destroyed and more than 101,000 damaged, and 1,167 of Homestead’s 1,176 mobile homes were destroyed. Homestead was incorporated in 1913 and is the second-oldest city in Miami-Dade, but most of its housing is much younger than that.' },
        { type: 'p', text: 'Census estimates for 2020–2024 put the median year a Homestead home was built at **2001**. About 55% of homes date from 2000 or later and only about a third from before 1990. Around 39% are detached single-family houses, about 21% are townhomes and similar attached homes, and the rest are mostly apartments and condos. Roughly half of homes are owner-occupied, so many Homestead families rent and need renters insurance rather than a homeowners policy.' },
        { type: 'p', text: 'For insurance, that history matters in a very practical way. Newer homes in Miami-Dade were built to the High-Velocity Hurricane Zone (HVHZ) requirements of the building code. Insurers must offer premium credits for features that reduce wind damage, but they only apply them when the features are documented.' },
      ],
      checklistTitle: 'What we check on Homestead home policies',
      checklist: [
        '**A current wind mitigation inspection** (form OIR-B1-1802). It is valid for up to five years if nothing material changes, and newer homes often qualify for several credits.',
        '**Dwelling coverage at today’s rebuilding cost**, not the price you paid or the county’s assessed value.',
        '**Your hurricane deductible in dollars.** A 2% deductible on a $350,000 dwelling limit is $7,000 out of pocket.',
        '**Replacement cost for your belongings**, not actual cash value.',
        '**Law and ordinance coverage**, which pays for code upgrades when part of a home is rebuilt. Florida insurers must offer 25% or 50%.',
        '**Flood insurance.** Homeowners policies exclude flood, including storm surge, and a new NFIP policy usually has a 30-day waiting period.',
        '**Other structures and screen enclosures**: fences, sheds, pool cages and their limits.',
        '**Loss of use** for hotel or rent while your home is repaired.',
        '**Personal liability** high enough to protect your family if someone is hurt on your property.',
      ],
      body: [
        { type: 'h2', text: 'Florida rules that affect your Homestead policy' },
        { type: 'p', text: '**Wind mitigation credits.** Florida law requires insurers to include actuarially reasonable credits for construction features that reduce wind losses, such as roof deck attachment, roof-to-wall connections, a hip roof and opening protection, and since October 2023 they must explain these credits on their websites. In Miami-Dade, the inspection form treats the whole county as HVHZ. Homes permitted after September 1, 1994 under the South Florida Building Code, or under the Florida Building Code from 2002 on, can get credit for meeting the code. Free inspections may also be available through the state’s **My Safe Florida Home** program for eligible single-family homes and townhomes.' },
        { type: 'p', text: '**Roof age.** For policies issued or renewed since July 1, 2022, insurers cannot refuse to write or renew a home only because its roof is less than 15 years old. With an older roof, an inspection showing at least five years of remaining useful life prevents a refusal based on age alone. Many roofs replaced in the early 2000s are now past that line, so it is worth knowing your roof’s permit date.' },
        { type: 'p', text: '**Hurricane deductibles.** Florida insurers offer hurricane deductibles of $500 or 2%, 5% or 10% of the dwelling limit, and the policy must show the amount in dollars. The deductible applies once per calendar year: if a second hurricane hits in the same year, the part you already paid counts toward it.' },
        { type: 'p', text: '**Claim deadlines.** You must give notice of a new property claim within one year of the date of loss, and for a hurricane that date is landfall. Reopened or supplemental claims have 18 months. Report damage early, take photos and keep receipts for emergency repairs.' },
        { type: 'h2', text: 'Flood is a separate policy' },
        { type: 'p', text: 'Homestead is inland, but rain from slow tropical systems and canals that back up can flood streets and low lots. A homeowners policy does not pay for flood. Miami-Dade’s current flood maps took effect in 2009, and new preliminary maps are not yet in force, so check your zone with the county. Ask us for a flood quote along with your home quote, and see our page on [flood insurance in Homestead](/en/flood-insurance-homestead-fl).' },
        { type: 'h2', text: 'An agent who stays with you after the storm' },
        { type: 'p', text: 'M&K Agency is family-owned, with a team of 12 and more than 5,000 clients across Florida. **Send us your policy and we’ll check your coverage**: we compare your dwelling limit with rebuilding costs, look for missing mitigation credits and translate your deductibles into dollars. After a storm, you call us, and we help you report the claim and follow it through.' },
      ],
      officeTitle: 'Five minutes from Homestead City Hall',
      office: [
        { type: 'p', text: 'We do not have an office inside Homestead; we serve Homestead homeowners from our Florida City office at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**. From Homestead City Hall it is about 1.5 miles south on US-1, around five minutes without traffic. Bring your declarations page and your wind mitigation report if you have one, or send photos by WhatsApp.' },
        { type: 'p', text: 'We are open Monday to Friday from 9 to 6, and Saturday by appointment. Call (305) 859-3953 or WhatsApp (971) 998-7313. Requests received during business hours get a call back from an agent within an hour.' },
      ],
      faqTitle: 'Homeowners insurance in Homestead: common questions',
      faq: [
        { q: 'My Homestead house was built after Andrew. Can that lower my premium?', a: 'It can. Insurers must offer credits for wind-resistant features, and homes built to the 1994 South Florida Building Code or the Florida Building Code can qualify. The credits are applied only when a wind mitigation inspection (form OIR-B1-1802) documents them, so send us your report or ask about getting one.' },
        { q: 'How does a 2% hurricane deductible work?', a: 'It is 2% of your dwelling coverage, not of the claim. With $300,000 of dwelling coverage, you pay the first $6,000 of hurricane damage. The deductible applies once per calendar year, so a second hurricane in the same year uses up whatever remains of it.' },
        { q: 'Does homeowners insurance in Homestead cover flooding?', a: 'No. Flood, including storm surge, is excluded from homeowners policies. You need a separate flood policy, and NFIP policies usually take 30 days to start, so buy it before hurricane season.' },
        { q: 'My roof is 16 years old. Will insurers refuse my home?', a: 'Florida law lets you have the roof inspected. If the inspection shows at least five years of remaining useful life, an insurer cannot refuse to write or renew the policy based on roof age alone. Other factors can still affect eligibility and price.' },
        { q: 'I rent in Homestead. Do I need insurance?', a: 'Your landlord’s policy covers the building, not your belongings or your liability. A renters policy covers both, and it is one of the simplest ways to protect your family after a fire, theft or storm.' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Seguro de Casa en Homestead, FL | M&K Agency',
      metaDesc: 'Seguro de casa en Homestead: lo que cambió después de Andrew, créditos por mitigación de viento, deducible de huracán, inundación y revisión gratis de su póliza.',
      breadcrumb: 'Homestead',
      kicker: 'Seguro de casa · Homestead, FL',
      h1a: 'Seguro de casa en Homestead, FL,',
      h1b: 'con gente que sabe lo que hace un huracán.',
      sub: 'La mayoría de las casas de Homestead se construyeron o reconstruyeron después de Andrew. Nos aseguramos de que su póliza lo tome en cuenta, le explicamos el deducible de huracán en dólares y le ayudamos si tiene un reclamo. En español, inglés o ruso.',
      serviceType: 'Seguro de casa',
      intro: [
        { type: 'h2', text: 'Homestead se reconstruyó después de 1992' },
        { type: 'p', text: 'El huracán Andrew tocó tierra justo al este de Homestead el 24 de agosto de 1992. Años después, NOAA lo reclasificó como categoría 5, con vientos sostenidos estimados de 165 mph. Según el Centro Nacional de Huracanes, el impacto fue extremo desde Kendall hacia el sur, pasando por Homestead y Florida City: en Miami-Dade quedaron destruidas unas 25,500 viviendas y más de 101,000 dañadas, y de las 1,176 casas móviles de Homestead, 1,167 desaparecieron. Homestead se fundó como ciudad en 1913 y es la segunda más antigua de Miami-Dade, pero la mayoría de sus casas son mucho más recientes.' },
        { type: 'p', text: 'Según las estimaciones del Censo para 2020–2024, la mitad de las viviendas de Homestead se construyó en **2001** o después. Cerca del 55% es del año 2000 en adelante y solo un tercio es anterior a 1990. Alrededor del 39% son casas independientes, un 21% son townhouses y otras casas adosadas, y el resto son sobre todo apartamentos y condominios. Más o menos la mitad de las viviendas las ocupan sus dueños, así que muchas familias de Homestead alquilan y lo que necesitan es un seguro de inquilino, no uno de propietario.' },
        { type: 'p', text: 'Para el seguro, esa historia importa mucho. Las casas nuevas en Miami-Dade se construyeron con las exigencias de la Zona de Huracanes de Alta Velocidad (HVHZ) del código. Las aseguradoras deben ofrecer créditos por las características que reducen el daño por viento, pero solo los aplican si están documentadas.' },
      ],
      checklistTitle: 'Lo que revisamos en las pólizas de casa de Homestead',
      checklist: [
        '**Una inspección de mitigación de viento vigente** (formulario OIR-B1-1802). Vale hasta cinco años si no hay cambios importantes, y las casas nuevas suelen calificar para varios créditos.',
        '**Cobertura de la vivienda al costo actual de reconstrucción**, no lo que pagó por la casa ni el valor del tasador del condado.',
        '**Su deducible de huracán en dólares.** Un 2% sobre $350,000 de cobertura son $7,000 de su bolsillo.',
        '**Costo de reposición para sus pertenencias**, no valor real en efectivo (ACV).',
        '**Cobertura de leyes y ordenanzas**, que paga las mejoras que exige el código al reconstruir. En Florida deben ofrecerle 25% o 50%.',
        '**Seguro de inundación.** La póliza de casa excluye la inundación, incluida la marejada, y una póliza nueva del NFIP suele tener 30 días de espera.',
        '**Otras estructuras y screen enclosures**: cercas, cobertizos, la jaula de la piscina y sus límites.',
        '**Gastos de vivienda temporal** (hotel o alquiler) mientras reparan su casa.',
        '**Responsabilidad civil** suficiente para proteger a su familia si alguien se lesiona en su propiedad.',
      ],
      body: [
        { type: 'h2', text: 'Reglas de Florida que afectan su póliza en Homestead' },
        { type: 'p', text: '**Créditos por mitigación de viento.** La ley obliga a las aseguradoras a incluir créditos razonables por características que reducen las pérdidas por viento, como la fijación del techo, las conexiones techo-pared, el techo a cuatro aguas y la protección de puertas y ventanas, y desde octubre de 2023 tienen que explicarlos en sus sitios web. En Miami-Dade, el formulario de inspección trata a todo el condado como HVHZ. Las casas con permiso posterior al 1 de septiembre de 1994 bajo el South Florida Building Code, o bajo el Código de Construcción de Florida desde 2002, pueden recibir crédito por cumplir el código. Además, el programa estatal **My Safe Florida Home** puede ofrecer inspecciones gratuitas a casas unifamiliares y townhouses que califiquen.' },
        { type: 'p', text: '**Edad del techo.** En las pólizas emitidas o renovadas desde el 1 de julio de 2022, la aseguradora no puede negarse a asegurar o renovar una casa solo porque el techo tiene menos de 15 años. Si el techo es más viejo, una inspección que muestre al menos cinco años de vida útil impide que la rechacen solo por la edad. Muchos techos cambiados a principios de los 2000 ya pasaron esa línea, así que conviene saber la fecha del permiso del suyo.' },
        { type: 'p', text: '**Deducibles de huracán.** En Florida se ofrecen deducibles de huracán de $500 o del 2%, 5% o 10% de la cobertura de la vivienda, y la póliza debe mostrar la cantidad en dólares. Se aplica una vez por año calendario: si llega un segundo huracán el mismo año, lo que ya pagó cuenta para ese deducible.' },
        { type: 'p', text: '**Plazos para reclamar.** Debe avisar un reclamo nuevo dentro de un año desde la fecha de la pérdida, y en un huracán esa fecha es la de entrada a tierra. Los reclamos reabiertos o suplementarios tienen 18 meses. Reporte el daño pronto, tome fotos y guarde los recibos de las reparaciones de emergencia.' },
        { type: 'h2', text: 'La inundación va en una póliza aparte' },
        { type: 'p', text: 'Homestead no está en la costa, pero la lluvia de los sistemas tropicales lentos y los canales que se desbordan pueden inundar calles y terrenos bajos. La póliza de casa no paga inundaciones. Los mapas de inundación vigentes en Miami-Dade son de 2009 y los nuevos mapas preliminares todavía no están en vigor, así que confirme su zona con el condado. Pídanos una cotización de inundación junto con la de su casa y vea nuestra página de [seguro de inundación en Homestead](/es/flood-insurance-homestead-fl).' },
        { type: 'h2', text: 'Un agente que sigue con usted después de la tormenta' },
        { type: 'p', text: 'M&K Agency es una agencia familiar con un equipo de 12 personas y más de 5,000 clientes en Florida. **Envíenos su póliza y la revisamos**: comparamos su cobertura con el costo de reconstrucción, buscamos créditos de mitigación que le falten y le traducimos los deducibles a dólares. Después de una tormenta, nos llama y le ayudamos a reportar el reclamo y darle seguimiento.' },
      ],
      officeTitle: 'A cinco minutos de la Alcaldía de Homestead',
      office: [
        { type: 'p', text: 'No tenemos oficina dentro de Homestead: atendemos a los propietarios de Homestead desde nuestra oficina en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**. Desde la Alcaldía de Homestead son unas 1.5 millas hacia el sur por la US-1, cerca de cinco minutos sin tráfico. Traiga su página de declaraciones y su informe de mitigación de viento si lo tiene, o mándenos fotos por WhatsApp.' },
        { type: 'p', text: 'Abrimos de lunes a viernes de 9 a 6, y los sábados con cita. Llame al (305) 859-3953 o escriba por WhatsApp al (971) 998-7313. Si nos escribe en horario de oficina, un agente le llama en menos de una hora.' },
      ],
      faqTitle: 'Seguro de casa en Homestead: preguntas frecuentes',
      faq: [
        { q: 'Mi casa en Homestead se construyó después de Andrew. ¿Eso puede bajar la prima?', a: 'Puede. Las aseguradoras deben ofrecer créditos por características resistentes al viento, y las casas construidas con el South Florida Building Code de 1994 o con el Código de Construcción de Florida pueden calificar. Los créditos solo se aplican si una inspección de mitigación de viento (formulario OIR-B1-1802) los documenta, así que envíenos su informe o pregúntenos cómo conseguir uno.' },
        { q: '¿Cómo funciona un deducible de huracán del 2%?', a: 'Es el 2% de la cobertura de la vivienda, no del reclamo. Con $300,000 de cobertura, usted paga los primeros $6,000 de daño por huracán. Se aplica una vez por año calendario, así que un segundo huracán el mismo año usa lo que quede de ese deducible.' },
        { q: '¿El seguro de casa en Homestead cubre inundaciones?', a: 'No. La inundación, incluida la marejada, está excluida de las pólizas de propietario. Necesita una póliza de inundación aparte, y las del NFIP normalmente tardan 30 días en entrar en vigor, así que cómprela antes de la temporada de huracanes.' },
        { q: 'Mi techo tiene 16 años. ¿Me van a rechazar la casa?', a: 'La ley de Florida le permite hacer inspeccionar el techo. Si la inspección muestra al menos cinco años de vida útil, la aseguradora no puede negarse a asegurar o renovar solo por la edad del techo. Otros factores pueden seguir influyendo en la aceptación y el precio.' },
        { q: 'Alquilo en Homestead. ¿Necesito seguro?', a: 'La póliza del dueño cubre el edificio, no sus pertenencias ni su responsabilidad. Un seguro de inquilino cubre las dos cosas, y es una de las maneras más sencillas de proteger a su familia ante un incendio, un robo o una tormenta.' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Страховка дома в Homestead, FL | M&K Agency',
      metaDesc: 'Страховка дома в Homestead: что изменил ураган Andrew, кредиты за wind mitigation, ураганная франшиза, наводнение и бесплатная проверка вашего полиса.',
      breadcrumb: 'Homestead',
      kicker: 'Страховка дома · Homestead, FL',
      h1a: 'Страховка дома в Homestead, FL —',
      h1b: 'от тех, кто знает, что такое ураган.',
      sub: 'Большинство домов в Homestead построены или отстроены заново после Andrew. Мы проследим, чтобы полис это учитывал, переведём ураганную франшизу в доллары и поможем, если понадобится клейм. По-русски, по-английски или по-испански.',
      serviceType: 'Страхование дома',
      intro: [
        { type: 'h2', text: 'Homestead отстроили заново после 1992 года' },
        { type: 'p', text: 'Ураган Andrew вышел на сушу чуть восточнее Homestead 24 августа 1992 года. Позже NOAA повысила его до 5-й категории с расчётным устойчивым ветром 165 миль в час. По оценке Национального центра ураганов, удар был катастрофическим от Kendall на юг, через Homestead и Florida City: в Miami-Dade было разрушено около 25,500 домов и повреждено более 101,000, а из 1,176 передвижных домов Homestead полностью разрушены 1,167. Homestead получил статус города ещё в 1913 году и считается вторым по возрасту городом округа, но жильё здесь в основном гораздо моложе.' },
        { type: 'p', text: 'По оценкам переписи за 2020–2024 годы, медианный год постройки дома в Homestead — **2001**. Около 55% жилья построено в 2000 году или позже и лишь около трети — до 1990-го. Примерно 39% — отдельные дома на одну семью, около 21% — таунхаусы и другие сблокированные дома, остальное — в основном квартиры и кондо. Владельцы живут примерно в половине жилья, так что многим семьям в Homestead нужна не страховка дома, а страховка арендатора (renters insurance).' },
        { type: 'p', text: 'Для страховки эта история очень практична. Новые дома в Miami-Dade строились по требованиям зоны High-Velocity Hurricane Zone (HVHZ) строительного кода. Страховые обязаны давать кредиты (снижение премии) за конструктивные элементы, уменьшающие ущерб от ветра, но применяют их только тогда, когда эти элементы подтверждены документально.' },
      ],
      checklistTitle: 'Что мы проверяем в полисах на дома в Homestead',
      checklist: [
        '**Действующая инспекция wind mitigation** (форма OIR-B1-1802). Она действует до пяти лет, если в доме ничего существенно не менялось, а новые дома часто получают сразу несколько кредитов.',
        '**Покрытие дома (Coverage A) по сегодняшней стоимости восстановления**, а не по цене покупки или оценке округа.',
        '**Ураганная франшиза в долларах.** 2% от покрытия $350,000 — это $7,000 из вашего кармана.',
        '**Replacement cost для вещей**, а не actual cash value с учётом износа.',
        '**Law and ordinance** — оплата работ, которых требует действующий код при восстановлении. Во Флориде страховая обязана предложить 25% или 50%.',
        '**Страховка от наводнения.** Полис на дом не покрывает наводнение, в том числе нагонную волну, а у нового полиса NFIP обычно 30 дней ожидания.',
        '**Другие постройки и screen enclosure**: заборы, сараи, сетчатый «купол» над бассейном и их лимиты.',
        '**Loss of use** — гостиница или аренда, пока дом ремонтируют.',
        '**Personal liability** с лимитом, достаточным, чтобы защитить семью, если кто-то пострадает у вас на участке.',
      ],
      body: [
        { type: 'h2', text: 'Правила Флориды, которые влияют на ваш полис в Homestead' },
        { type: 'p', text: '**Кредиты за wind mitigation.** Закон обязывает страховые включать в тарифы обоснованные кредиты за элементы, снижающие ущерб от ветра: крепление настила крыши, связь крыши со стенами, четырёхскатную крышу, защиту окон и дверей. С октября 2023 года страховые должны объяснять эти кредиты на своих сайтах. В форме инспекции весь Miami-Dade считается зоной HVHZ. Дома, разрешение на строительство которых выдано после 1 сентября 1994 года по South Florida Building Code или с 2002 года по Florida Building Code, могут получить кредит за соответствие коду. Кроме того, по государственной программе **My Safe Florida Home** подходящим отдельным домам и таунхаусам может быть доступна бесплатная инспекция.' },
        { type: 'p', text: '**Возраст крыши.** Для полисов, выданных или продлённых с 1 июля 2022 года, страховая не может отказать в страховке или продлении только из-за возраста крыши, если ей меньше 15 лет. Если крыша старше, инспекция, подтверждающая не менее пяти лет оставшегося срока службы, не позволяет отказать только по возрасту. Многие крыши, перекрытые в начале 2000-х, уже перешли этот рубеж, так что полезно знать дату разрешения (permit) на свою.' },
        { type: 'p', text: '**Ураганная франшиза.** Во Флориде предлагают ураганную франшизу $500 или 2%, 5% либо 10% от покрытия дома, и в полисе сумма должна быть указана в долларах. Она применяется один раз за календарный год: если в том же году придёт второй ураган, уже уплаченная часть засчитывается.' },
        { type: 'p', text: '**Сроки клейма.** О новом клейме по имуществу нужно заявить в течение года с даты ущерба, а при урагане эта дата — день выхода урагана на сушу. Для повторно открытых и дополнительных клеймов срок — 18 месяцев. Сообщайте об ущербе сразу, фотографируйте и сохраняйте чеки за срочный ремонт.' },
        { type: 'h2', text: 'Наводнение — это отдельный полис' },
        { type: 'p', text: 'Homestead не на побережье, но дожди от медленных тропических систем и переполненные каналы могут затопить улицы и низкие участки. Полис на дом за наводнение не платит. Действующие карты затопления Miami-Dade вступили в силу в 2009 году, а новые предварительные карты пока не действуют, поэтому проверьте свою зону на сайте округа. Попросите у нас расчёт страховки от наводнения вместе с расчётом по дому.' },
        { type: 'h2', text: 'Агент, который остаётся с вами и после шторма' },
        { type: 'p', text: 'M&K Agency — семейное агентство: 12 человек в команде и более 5,000 клиентов по всей Флориде. **Пришлите нам свой полис — мы проверим покрытие**: сравним лимит по дому со стоимостью восстановления, найдём недостающие кредиты за wind mitigation и переведём франшизы в доллары. После шторма вы звоните нам, и мы помогаем подать клейм и довести его до конца.' },
      ],
      officeTitle: 'В пяти минутах от мэрии Homestead',
      office: [
        { type: 'p', text: 'Офиса в самом Homestead у нас нет: мы обслуживаем владельцев домов в Homestead из офиса во Florida City по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**. От мэрии Homestead это около 1.5 мили на юг по US-1, примерно пять минут без пробок. Возьмите с собой declarations page и отчёт wind mitigation, если он есть, или пришлите фото в WhatsApp.' },
        { type: 'p', text: 'Мы работаем с понедельника по пятницу с 9 до 6, в субботу — по записи. Звоните (305) 859-3953 или пишите в WhatsApp: (971) 998-7313. На заявки в рабочее время агент перезванивает в течение часа.' },
      ],
      faqTitle: 'Страховка дома в Homestead: частые вопросы',
      faq: [
        { q: 'Мой дом в Homestead построен после Andrew. Это может снизить премию?', a: 'Может. Страховые обязаны давать кредиты за ветроустойчивые элементы, и дома, построенные по South Florida Building Code 1994 года или по Florida Building Code, могут на них претендовать. Но кредиты применяются, только если их подтверждает инспекция wind mitigation (форма OIR-B1-1802). Пришлите нам отчёт или спросите, как его получить.' },
        { q: 'Как работает ураганная франшиза 2%?', a: 'Это 2% от покрытия дома, а не от суммы ущерба. При покрытии $300,000 первые $6,000 ущерба от урагана платите вы. Франшиза применяется раз в календарный год, так что при втором урагане в том же году учитывается её оставшаяся часть.' },
        { q: 'Покрывает ли страховка дома в Homestead наводнение?', a: 'Нет. Наводнение, включая нагонную волну, исключено из полисов на дом. Нужен отдельный полис от наводнения, а полисы NFIP обычно начинают действовать через 30 дней, поэтому оформляйте его до сезона ураганов.' },
        { q: 'Моей крыше 16 лет. Мне откажут в страховке?', a: 'Закон Флориды позволяет провести инспекцию крыши. Если она покажет не менее пяти лет оставшегося срока службы, страховая не может отказать в оформлении или продлении только из-за возраста крыши. Другие факторы всё равно могут влиять на решение и цену.' },
        { q: 'Я снимаю жильё в Homestead. Мне нужна страховка?', a: 'Полис хозяина покрывает здание, но не ваши вещи и не вашу ответственность. Страховка арендатора (renters insurance) покрывает и то, и другое — это один из самых простых способов защитить семью от пожара, кражи или шторма.' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
