import type { CityPage } from './types';
import { sources } from './sources';

// /[lang]/homeowners-insurance-broward-county-fl (county hub). Facts checked 2026-10-03.
// No Broward city pages exist yet, so `served` has no links.
const SRC = ['wilma', 'fbcHvhz', 'browardBora', 'acsBroward', 'browardFlood', 'floodsmart', 'windForm', 'mitigation', 'roofAge', 'deductibles', 'claimDeadline', 'condoMaster', 'lossAssessment', 'condoInspections', 'msfh'] as const;

export const HOME_BROWARD: CityPage = {
  path: '/homeowners-insurance-broward-county-fl',
  line: 'home',
  kind: 'county',
  area: 'broward',
  heroImage: 'home-06',
  published: '2026-10-03',
  modified: '2026-10-03',
  served: [
    { name: 'Fort Lauderdale' }, { name: 'Hollywood' }, { name: 'Hallandale Beach' }, { name: 'Pembroke Pines' },
    { name: 'Miramar' }, { name: 'Davie' }, { name: 'Plantation' }, { name: 'Sunrise' }, { name: 'Weston' },
    { name: 'Coral Springs' }, { name: 'Pompano Beach' }, { name: 'Deerfield Beach' }, { name: 'Dania Beach' },
    { name: 'Lauderdale-by-the-Sea' }, { name: 'Cooper City' }, { name: 'Tamarac' }, { name: 'Margate' }, { name: 'Coconut Creek' },
  ],
  areaServed: [
    { '@type': 'AdministrativeArea', name: 'Broward County, FL' },
  ],
  copy: {
    en: {
      metaTitle: 'Homeowners & Condo Insurance in Broward County | M&K Agency',
      metaDesc: 'Home and condo insurance in Broward: HVHZ building code, new FEMA flood maps from July 2024, condo milestone inspections and HO-6 gaps, wind mitigation credits and a free policy review.',
      breadcrumb: 'Broward County',
      kicker: 'Home & condo insurance · Broward County',
      h1a: 'Home and condo insurance in Broward County,',
      h1b: 'checked against your building and your flood zone.',
      sub: 'Beachfront condos, canal-front houses, HOA communities out west. Send us your policy by WhatsApp or email, and a licensed agent will show you the gaps and stay with you through a claim. English, Spanish or Russian.',
      serviceType: 'Homeowners and condo insurance',
      intro: [
        { type: 'h2', text: 'Broward is part of the High-Velocity Hurricane Zone' },
        { type: 'p', text: 'Under the Florida Building Code, Broward and Miami-Dade are the only two counties in the **High-Velocity Hurricane Zone (HVHZ)**, with the state’s strictest wind requirements. Broward’s design wind speeds are slightly lower than Miami-Dade’s, from 156 to 180 mph depending on the building’s risk category, but the same rules apply: windows, doors, shutters and roofing must carry an HVHZ product approval, and local amendments and code interpretations go through the county’s Board of Rules and Appeals.' },
        { type: 'p', text: 'Most Broward homes, however, are older than today’s code. Census estimates for 2020–2024 put the median year built at **1980**, and about 68% of homes were built before 1990. Nearly half of all homes, about 49%, are in buildings with two or more units, and about 36% are in buildings with ten or more, from beachfront towers in Hallandale Beach and Fort Lauderdale to garden-style condos inland. About 64% of homes are owner-occupied.' },
        { type: 'p', text: 'Broward’s most recent big hurricane lesson came from Wilma in October 2005. The National Hurricane Center found that parts of Broward likely had Category 2 conditions, with gusts near 100 knots and even stronger winds on the upper floors of high-rises. Broken windows and roof damage were widespread.' },
      ],
      checklistTitle: 'What we check for Broward homeowners and condo owners',
      checklist: [
        '**Your flood zone on the July 2024 maps.** If your zone changed, your flood requirements and options may have changed too.',
        '**Flood insurance**, whatever the zone. Homeowners and condo policies exclude flood and storm surge.',
        '**Condo owners:** HO-6 coverage for interior finishes, cabinets, appliances and water heater, which the association’s master policy must exclude by law.',
        '**Loss assessment coverage** above the $2,000 minimum, and the size of the association’s hurricane deductible.',
        '**Milestone inspection and reserve study status** for buildings three stories and up, since they can lead to special assessments.',
        '**House owners:** roof age and permit date, a current wind mitigation report and law and ordinance coverage.',
        '**HOA homes and townhomes:** what the association documents require you to insure.',
        '**Hurricane deductible in dollars**, and how it compares with your emergency savings.',
        '**Liability limits** for pools, docks, dogs and guests.',
      ],
      body: [
        { type: 'h2', text: 'New flood maps since July 31, 2024' },
        { type: 'p', text: 'FEMA’s updated Flood Insurance Rate Maps for Broward took effect on July 31, 2024. Some properties moved into or out of high-risk zones, which can change whether a lender requires flood insurance. Check your address on the county’s flood zone map, and remember that the map only describes the chance of flooding, not your protection. Every homeowners and condo policy excludes flood, including storm surge, and NFIP policies usually start 30 days after purchase, with limits of up to $250,000 for the building and $100,000 for contents. Condo associations may carry flood coverage for the building, but that does not cover your unit’s contents.' },
        { type: 'h2', text: 'Condos: what is yours to insure' },
        { type: 'p', text: 'Florida condominium law requires the association’s property policy to exclude what lies within the unit and serves only it: floor, wall and ceiling coverings, electrical fixtures, appliances, water heaters, built-in cabinets and countertops, window treatments and personal property. Your HO-6 should cover those, plus liability and loss of use, and Florida requires at least $2,000 of loss assessment coverage, which pays your share of an assessment for a covered loss. Buildings with three or more habitable stories must have a milestone inspection at 30 years and every 10 years after, and a structural integrity reserve study. The repairs those reports find are paid by owners, not by insurance.' },
        { type: 'h2', text: 'Houses: roofs and wind credits' },
        { type: 'p', text: 'Since July 1, 2022, an insurer cannot refuse to write or renew a Florida home only because its roof is under 15 years old, and an older roof that passes an inspection showing at least five years of life left cannot be refused on age alone. Insurers must include actuarially reasonable credits for documented wind-resistant features, and on the inspection form Broward is HVHZ. Homes permitted after September 1, 1994 under the South Florida Building Code, or under the Florida Building Code from 2002, can get credit for meeting the code; older homes earn credits through upgrades. Eligible homeowners may get a free inspection through **My Safe Florida Home**.' },
        { type: 'h2', text: 'Deductibles and claim deadlines' },
        { type: 'p', text: 'Florida hurricane deductibles are $500 or 2%, 5% or 10% of the dwelling limit and apply once per calendar year. Notice of a new claim is due within one year of the date of loss, landfall for a hurricane, and supplemental claims within 18 months.' },
        { type: 'p', text: 'M&K Agency is a family-owned agency with a team of 12 and more than 5,000 clients across Florida. **Send us your policy and we’ll check your coverage**, along with your association’s insurance summary if you own a condo. We will show you the gaps in plain language and help you through a claim when you need it.' },
      ],
      officeTitle: 'How we work with Broward homeowners',
      office: [
        { type: 'p', text: 'We do not have an office in Broward County. Our office is in Florida City, at **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, roughly an hour from Pembroke Pines and 70 to 80 minutes from Hollywood or downtown Fort Lauderdale in light traffic. So we serve Broward clients mainly by phone, WhatsApp, text and email: you send photos of your declarations page and any inspection or association documents, and we go through them with you by phone. Visits are welcome by appointment.' },
        { type: 'p', text: 'Hours are Monday to Friday, 9 to 6, and Saturday by appointment. Call (305) 859-3953 or WhatsApp (971) 998-7313. During business hours, an agent calls back within an hour.' },
      ],
      faqTitle: 'Home and condo insurance in Broward: common questions',
      faq: [
        { q: 'Did the new Broward flood maps change my flood zone?', a: 'They may have. FEMA’s updated maps for Broward took effect on July 31, 2024. Look up your address on the county’s flood zone map, and send us the result if you are not sure what it means for your coverage.' },
        { q: 'Is Broward in the High-Velocity Hurricane Zone?', a: 'Yes. The Florida Building Code places Broward and Miami-Dade in the HVHZ. Building products there need HVHZ approval, and the wind mitigation inspection form treats all of Broward as HVHZ.' },
        { q: 'What does an HO-6 condo policy cover?', a: 'The parts of the unit the association’s policy must exclude, such as flooring, wall and ceiling coverings, cabinets, countertops, appliances and water heaters, plus your belongings, liability, loss of use and at least $2,000 of loss assessment coverage.' },
        { q: 'Will insurance pay a special assessment after my building’s milestone inspection?', a: 'Generally not. Repairs found in a milestone inspection or a reserve study are maintenance costs. Loss assessment coverage applies when the association assesses owners for a covered loss.' },
        { q: 'Can you insure my Broward home if your office is in Miami-Dade?', a: 'Yes. We work with clients throughout Florida. Most Broward clients never come to the office; we handle reviews, quotes and claims by phone, WhatsApp, text and email.' },
      ],
      sources: sources('en', [...SRC]),
    },
    es: {
      metaTitle: 'Seguro de Casa y Condominio en Broward | M&K Agency',
      metaDesc: 'Seguro de casa y condominio en Broward: código HVHZ, nuevos mapas de inundación de FEMA desde julio de 2024, inspecciones de hito y HO-6, créditos por mitigación y revisión gratis.',
      breadcrumb: 'Condado Broward',
      kicker: 'Seguro de casa y condominio · Condado Broward',
      h1a: 'Seguro de casa y condominio en Broward,',
      h1b: 'revisado según su edificio y su zona de inundación.',
      sub: 'Condominios frente al mar, casas en canales, comunidades con HOA en el oeste. Envíenos su póliza por WhatsApp o correo y un agente licenciado le muestra lo que falta y le acompaña en el reclamo. En español, inglés o ruso.',
      serviceType: 'Seguro de casa y de condominio',
      intro: [
        { type: 'h2', text: 'Broward es parte de la Zona de Huracanes de Alta Velocidad' },
        { type: 'p', text: 'Según el Código de Construcción de Florida, Broward y Miami-Dade son los dos únicos condados de la **Zona de Huracanes de Alta Velocidad (HVHZ)**, con las exigencias contra viento más estrictas del estado. Las velocidades de diseño en Broward son un poco menores que en Miami-Dade, de 156 a 180 mph según la categoría de riesgo del edificio, pero las reglas son las mismas: ventanas, puertas, shutters y techos necesitan aprobación para la HVHZ, y las enmiendas e interpretaciones locales del código pasan por la Junta de Reglas y Apelaciones del condado (Board of Rules and Appeals).' },
        { type: 'p', text: 'Sin embargo, la mayoría de las viviendas de Broward es anterior al código actual. Según el Censo para 2020–2024, la vivienda típica es de **1980**, y cerca del 68% se construyó antes de 1990. Casi la mitad, un 49%, está en edificios de dos o más unidades, y alrededor del 36% en edificios de diez o más, desde las torres frente al mar en Hallandale Beach y Fort Lauderdale hasta los condominios de pocos pisos tierra adentro. Cerca del 64% de las viviendas las ocupan sus dueños.' },
        { type: 'p', text: 'La lección más reciente de un gran huracán en Broward fue Wilma, en octubre de 2005. Según el Centro Nacional de Huracanes, partes de Broward probablemente tuvieron condiciones de categoría 2, con ráfagas cercanas a los 100 nudos y vientos todavía más fuertes en los pisos altos de las torres. Hubo ventanas rotas y daños en techos por todas partes.' },
      ],
      checklistTitle: 'Lo que revisamos a propietarios de casas y condominios en Broward',
      checklist: [
        '**Su zona de inundación en los mapas de julio de 2024.** Si su zona cambió, pueden haber cambiado también sus requisitos y opciones de seguro de inundación.',
        '**Seguro de inundación**, sea cual sea la zona. Las pólizas de casa y de condominio excluyen inundación y marejada.',
        '**Dueños de condominio:** HO-6 para acabados interiores, gabinetes, electrodomésticos y calentador, que por ley la póliza maestra debe excluir.',
        '**Loss assessment** por encima del mínimo de $2,000, y el tamaño del deducible de huracán de la asociación.',
        '**Estado de la inspección de hito y del estudio de reservas** en edificios de tres pisos o más, porque pueden traer cuotas especiales.',
        '**Dueños de casa:** edad y permiso del techo, informe de mitigación de viento vigente y leyes y ordenanzas.',
        '**Casas en HOA y townhouses:** lo que los documentos de la asociación le exigen asegurar.',
        '**Deducible de huracán en dólares**, comparado con sus ahorros para emergencias.',
        '**Límites de responsabilidad** por piscina, muelle, perro y visitas.',
      ],
      body: [
        { type: 'h2', text: 'Nuevos mapas de inundación desde el 31 de julio de 2024' },
        { type: 'p', text: 'Los mapas de tarifas de seguro de inundación (FIRM) actualizados de FEMA para Broward entraron en vigor el 31 de julio de 2024. Algunas propiedades entraron o salieron de zonas de alto riesgo, lo que puede cambiar si el banco le exige seguro de inundación. Busque su dirección en el mapa de zonas de inundación del condado, y recuerde que el mapa solo describe la probabilidad de inundarse, no su protección. Toda póliza de casa y de condominio excluye la inundación, incluida la marejada, y las pólizas del NFIP suelen empezar 30 días después de comprarlas, con límites de hasta $250,000 para el edificio y $100,000 para el contenido. La asociación puede tener seguro de inundación para el edificio, pero ese seguro no cubre el contenido de su unidad.' },
        { type: 'h2', text: 'Condominios: lo que le toca asegurar a usted' },
        { type: 'p', text: 'La ley de condominios de Florida exige que la póliza de la asociación excluya lo que está dentro de la unidad y sirve solo a ella: revestimientos de pisos, paredes y techos, instalaciones eléctricas, electrodomésticos, calentadores, gabinetes y topes empotrados, cortinas y persianas, y los bienes personales. Su HO-6 debería cubrir todo eso, además de responsabilidad y gastos de vivienda, y Florida exige al menos $2,000 de loss assessment, que paga su parte de una cuota por una pérdida cubierta. Los edificios de tres o más pisos habitables deben tener una inspección de hito a los 30 años y cada 10 años después, y un estudio de reservas de integridad estructural. Las reparaciones que salen de esos informes las pagan los dueños, no el seguro.' },
        { type: 'h2', text: 'Casas: techos y créditos por viento' },
        { type: 'p', text: 'Desde el 1 de julio de 2022, la aseguradora no puede negarse a asegurar o renovar una casa en Florida solo porque el techo tiene menos de 15 años, y un techo más viejo que pase una inspección con al menos cinco años de vida útil no puede rechazarse solo por la edad. Las aseguradoras deben incluir créditos razonables por las características resistentes al viento que estén documentadas, y en el formulario de inspección Broward es HVHZ. Las casas con permiso posterior al 1 de septiembre de 1994 bajo el South Florida Building Code, o bajo el Código de Construcción de Florida desde 2002, pueden recibir crédito por cumplir el código; las más viejas lo ganan con mejoras. Los propietarios que califiquen pueden conseguir una inspección gratis con **My Safe Florida Home**.' },
        { type: 'h2', text: 'Deducibles y plazos para reclamar' },
        { type: 'p', text: 'En Florida, los deducibles de huracán son de $500 o del 2%, 5% o 10% de la cobertura de la vivienda y se aplican una vez por año calendario. El aviso de un reclamo nuevo vence un año después de la fecha de la pérdida, que en un huracán es la entrada a tierra, y los suplementarios a los 18 meses.' },
        { type: 'p', text: 'M&K Agency es una agencia familiar con un equipo de 12 personas y más de 5,000 clientes en Florida. **Envíenos su póliza y la revisamos**, junto con el resumen del seguro de su asociación si tiene condominio. Le mostramos los vacíos en palabras sencillas y le ayudamos con el reclamo cuando lo necesite.' },
      ],
      officeTitle: 'Cómo trabajamos con propietarios de Broward',
      office: [
        { type: 'p', text: 'No tenemos oficina en el Condado Broward. Nuestra oficina está en Florida City, en **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**, más o menos a una hora de Pembroke Pines y a 70 u 80 minutos de Hollywood o del centro de Fort Lauderdale sin tráfico. Por eso atendemos a los clientes de Broward sobre todo por teléfono, WhatsApp, texto y correo: usted nos manda fotos de su página de declaraciones y de cualquier informe de inspección o documento de la asociación, y los repasamos juntos por teléfono. Si quiere visitarnos, con gusto le damos cita.' },
        { type: 'p', text: 'Horario: lunes a viernes de 9 a 6, sábados con cita. Llame al (305) 859-3953 o escriba por WhatsApp al (971) 998-7313. En horario de oficina, un agente le devuelve la llamada en menos de una hora.' },
      ],
      faqTitle: 'Seguro de casa y condominio en Broward: preguntas frecuentes',
      faq: [
        { q: '¿Los nuevos mapas de inundación de Broward cambiaron mi zona?', a: 'Puede ser. Los mapas actualizados de FEMA para Broward entraron en vigor el 31 de julio de 2024. Busque su dirección en el mapa de zonas de inundación del condado y, si no está seguro de lo que significa para su cobertura, mándenos el resultado.' },
        { q: '¿Broward está en la Zona de Huracanes de Alta Velocidad?', a: 'Sí. El Código de Construcción de Florida ubica a Broward y Miami-Dade en la HVHZ. Los productos de construcción allí necesitan aprobación para la HVHZ, y el formulario de mitigación de viento considera todo Broward como HVHZ.' },
        { q: '¿Qué cubre una póliza de condominio HO-6?', a: 'Las partes de la unidad que la póliza de la asociación debe excluir, como pisos, revestimientos de paredes y techos, gabinetes, topes, electrodomésticos y calentadores, además de sus pertenencias, su responsabilidad, los gastos de vivienda y al menos $2,000 de loss assessment.' },
        { q: '¿El seguro paga una cuota especial después de la inspección de hito de mi edificio?', a: 'En general, no. Las reparaciones que aparecen en una inspección de hito o un estudio de reservas son costos de mantenimiento. El loss assessment aplica cuando la asociación les cobra a los dueños por una pérdida cubierta.' },
        { q: '¿Pueden asegurar mi casa en Broward si su oficina está en Miami-Dade?', a: 'Sí. Trabajamos con clientes en toda Florida. La mayoría de nuestros clientes de Broward nunca viene a la oficina; hacemos revisiones, cotizaciones y reclamos por teléfono, WhatsApp, texto y correo.' },
      ],
      sources: sources('es', [...SRC]),
    },
    ru: {
      metaTitle: 'Страховка дома и кондо в округе Broward | M&K Agency',
      metaDesc: 'Страховка дома и кондо в Broward: код HVHZ, новые карты затопления FEMA с июля 2024 года, milestone inspections и пробелы HO-6, кредиты за wind mitigation и бесплатная проверка полиса.',
      breadcrumb: 'Округ Broward',
      kicker: 'Страховка дома и кондо · округ Broward',
      h1a: 'Страховка дома и кондо в округе Broward —',
      h1b: 'с учётом вашего здания и зоны затопления.',
      sub: 'Кондо на первой линии, дома на каналах, комьюнити с HOA на западе округа. Пришлите нам полис в WhatsApp или по почте — лицензированный агент покажет пробелы и будет рядом при клейме. По-русски, по-английски или по-испански.',
      serviceType: 'Страхование дома и кондо',
      intro: [
        { type: 'h2', text: 'Broward входит в High-Velocity Hurricane Zone' },
        { type: 'p', text: 'По Florida Building Code только два округа — Broward и Miami-Dade — относятся к **High-Velocity Hurricane Zone (HVHZ)** с самыми строгими в штате требованиями к ветроустойчивости. Расчётная скорость ветра в Broward чуть ниже, чем в Miami-Dade, — от 156 до 180 миль в час в зависимости от категории риска здания, — но правила те же: окна, двери, ставни и кровля должны иметь одобрение для HVHZ, а местные поправки и толкования кода проходят через окружной Board of Rules and Appeals.' },
        { type: 'p', text: 'При этом большая часть жилья в Broward старше нынешнего кода. По оценкам переписи за 2020–2024 годы, медианный год постройки — **1980**, а около 68% жилья построено до 1990 года. Почти половина — около 49% — находится в зданиях на две квартиры и больше, а около 36% — в домах на десять и более квартир: от высоток на первой линии в Hallandale Beach и Fort Lauderdale до малоэтажных кондо в глубине округа. Около 64% жилья занимают сами владельцы.' },
        { type: 'p', text: 'Последний большой урок урагана для Broward — Wilma в октябре 2005 года. По данным Национального центра ураганов, в части округа, вероятно, были условия 2-й категории с порывами около 100 узлов, а на верхних этажах высоток ветер был ещё сильнее. Выбитые окна и повреждённые крыши были повсюду.' },
      ],
      checklistTitle: 'Что мы проверяем у владельцев домов и кондо в Broward',
      checklist: [
        '**Ваша зона на картах затопления июля 2024 года.** Если зона изменилась, могли измениться и требования, и варианты страховки от наводнения.',
        '**Страховка от наводнения** — в любой зоне. Полисы на дом и кондо не покрывают наводнение и нагонную волну.',
        '**Владельцам кондо:** HO-6 на отделку, шкафы, технику и водонагреватель — по закону они исключены из мастер-полиса ассоциации.',
        '**Loss assessment** сверх минимума $2,000 и размер ураганной франшизы ассоциации.',
        '**Статус milestone inspection и SIRS** в зданиях от трёх этажей — они могут обернуться спецвзносами.',
        '**Владельцам домов:** возраст крыши и дата разрешения, действующий отчёт wind mitigation, law and ordinance.',
        '**Дома в HOA и таунхаусы:** что по документам ассоциации обязаны страховать вы.',
        '**Ураганная франшиза в долларах** — по сравнению с вашим запасом на чёрный день.',
        '**Лимиты ответственности** за бассейн, причал, собаку и гостей.',
      ],
      body: [
        { type: 'h2', text: 'Новые карты затопления с 31 июля 2024 года' },
        { type: 'p', text: 'Обновлённые карты FEMA (Flood Insurance Rate Maps) для Broward вступили в силу 31 июля 2024 года. Часть домов перешла в зоны высокого риска или вышла из них, а от этого зависит, потребует ли банк страховку от наводнения. Проверьте свой адрес на карте зон затопления на сайте округа и помните: карта показывает лишь вероятность затопления, а не вашу защиту. Любой полис на дом или кондо исключает наводнение, включая нагонную волну, а полисы NFIP обычно начинают действовать через 30 дней после покупки, с лимитами до $250,000 за здание и до $100,000 за имущество. У ассоциации может быть страховка здания от наводнения, но содержимое вашей квартиры она не покрывает.' },
        { type: 'h2', text: 'Кондо: что страхуете вы' },
        { type: 'p', text: 'Закон Флориды о кондоминиумах требует, чтобы полис ассоциации исключал всё, что находится внутри квартиры и обслуживает только её: покрытия полов, стен и потолков, светильники, технику, водонагреватели, встроенные шкафы и столешницы, шторы и жалюзи, личные вещи. Всё это должен покрывать ваш HO-6 — вместе с ответственностью и временным жильём, — а Флорида требует в нём не менее $2,000 loss assessment: это ваша доля взноса на застрахованный ущерб. Здания от трёх жилых этажей обязаны пройти milestone inspection в 30 лет и затем каждые 10 лет, а также сделать SIRS. Ремонт по итогам этих отчётов оплачивают владельцы, а не страховка.' },
        { type: 'h2', text: 'Дома: крыши и кредиты за ветроустойчивость' },
        { type: 'p', text: 'С 1 июля 2022 года страховая не может отказать в страховке или продлении дома во Флориде только из-за возраста крыши, если ей меньше 15 лет, а более старой крыше, прошедшей инспекцию с запасом службы не менее пяти лет, нельзя отказать только по возрасту. Страховые обязаны давать обоснованные кредиты за подтверждённые ветроустойчивые элементы, и в форме инспекции Broward — это HVHZ. Дома с разрешением на строительство после 1 сентября 1994 года по South Florida Building Code или с 2002 года по Florida Building Code могут получить кредит за соответствие коду; старые дома получают кредиты за улучшения. Подходящие владельцы могут сделать бесплатную инспекцию по программе **My Safe Florida Home**.' },
        { type: 'h2', text: 'Франшизы и сроки клеймов' },
        { type: 'p', text: 'Ураганная франшиза во Флориде — $500 или 2%, 5% либо 10% от покрытия дома, и применяется она раз в календарный год. О новом клейме нужно заявить в течение года с даты ущерба (для урагана — с даты выхода на сушу), о дополнительном — в течение 18 месяцев.' },
        { type: 'p', text: 'M&K Agency — семейное агентство: 12 человек в команде и более 5,000 клиентов по всей Флориде. **Пришлите нам свой полис — мы проверим покрытие**, а если у вас кондо — ещё и сводку страховки ассоциации. Простыми словами покажем пробелы и поможем с клеймом, когда понадобится.' },
      ],
      officeTitle: 'Как мы работаем с владельцами жилья в Broward',
      office: [
        { type: 'p', text: 'Офиса в округе Broward у нас нет. Наш офис — во Florida City, по адресу **33550 S Dixie Hwy, Suite 102, Florida City, FL 33034**: без пробок примерно час от Pembroke Pines и 70–80 минут от Hollywood или центра Fort Lauderdale. Поэтому клиентов из Broward мы обслуживаем в основном по телефону, в WhatsApp, по SMS и почте: вы присылаете фото declarations page, отчётов об инспекциях и документов ассоциации, и мы разбираем их вместе по телефону. Приехать к нам можно по записи.' },
        { type: 'p', text: 'Часы работы: понедельник–пятница с 9 до 6, суббота — по записи. Звоните (305) 859-3953 или пишите в WhatsApp: (971) 998-7313. В рабочее время агент перезванивает в течение часа.' },
      ],
      faqTitle: 'Страховка дома и кондо в Broward: частые вопросы',
      faq: [
        { q: 'Изменили ли новые карты затопления мою зону в Broward?', a: 'Возможно. Обновлённые карты FEMA для Broward действуют с 31 июля 2024 года. Найдите свой адрес на карте зон затопления на сайте округа и, если не уверены, что это значит для вашей страховки, пришлите нам результат.' },
        { q: 'Входит ли Broward в High-Velocity Hurricane Zone?', a: 'Да. Florida Building Code относит Broward и Miami-Dade к HVHZ. Строительные материалы там должны иметь одобрение для HVHZ, а в форме wind mitigation весь Broward считается HVHZ.' },
        { q: 'Что покрывает полис HO-6 для кондо?', a: 'То, что должен исключать полис ассоциации: полы, покрытия стен и потолков, шкафы, столешницы, технику и водонагреватели, а также ваши вещи, ответственность, временное жильё и не менее $2,000 loss assessment.' },
        { q: 'Оплатит ли страховка спецвзнос после milestone inspection моего здания?', a: 'Как правило, нет. Ремонт, выявленный milestone inspection или SIRS, — это расходы на содержание. Loss assessment работает, когда ассоциация собирает с владельцев деньги на застрахованный ущерб.' },
        { q: 'Вы можете застраховать мой дом в Broward, если офис у вас в Miami-Dade?', a: 'Да. Мы работаем с клиентами по всей Флориде. Большинство клиентов из Broward в офис не приезжают: проверки, расчёты и клеймы мы ведём по телефону, в WhatsApp, по SMS и почте.' },
      ],
      sources: sources('ru', [...SRC]),
    },
  },
};
