import type { RecPage } from './types';
import { srcList, u } from './sources';

// Facts: s. 316.003(2) autocycle definition and (47) motorcycle includes autocycle;
// s. 322.03(5) + FLHSMV: autocycle without motorcycle endorsement; FLHSMV endorsement page
// (3-Wheel BRC for three-wheel motorcycles); s. 316.211(3)(a) helmet rule does not apply
// to persons riding within an enclosed cab; s. 627.732 + FLHSMV insurance page (PIP/PDL
// for vehicles with at least four wheels); ss. 324.021, 324.051; III/IRC 20.6% uninsured.
const KEYS = ['s316_003', 's322_03', 'flhsmvMotoTypes', 'flhsmvEndorse', 's316_211', 's627_732', 'flhsmvInsurance', 's324_021', 's324_051', 'iiiUninsured', 's627_727'] as const;

export const AUTOCYCLE: RecPage = {
  line: 'autocycle',
  path: '/slingshot-autocycle-insurance-florida',
  leadValue: 'Slingshot / autocycle',
  leadSource: 'rec-autocycle',
  articleSlug: 'autocycle-motorcycle-endorsement-florida',
  productSlug: 'motorcycle-insurance',
  published: '2026-10-03',
  modified: '2026-10-03',
  copy: {
    en: {
      metaTitle: 'Slingshot & Autocycle Insurance in Florida | M&K Agency',
      metaDesc: 'Do you need a motorcycle endorsement for an autocycle in Florida? Why PIP does not apply on three wheels, and the coverage gaps to check with a local agent.',
      breadcrumb: 'Slingshot and autocycle insurance',
      kicker: 'Autocycle and three-wheeler insurance · All of Florida',
      h1a: 'Slingshot and autocycle insurance in Florida:',
      h1b: 'three wheels, open air, and no PIP to fall back on.',
      answer: 'Florida law calls a three-wheeler with two wheels in front, a steering wheel and real seats an **autocycle**, and you may drive one **without a motorcycle endorsement**. But it is still a **motorcycle** under the law, so the PIP that covers you in a car **does not apply**. We check your coverage and explain it in your language.',
      serviceType: 'Autocycle and three-wheel motorcycle insurance',
      leadLabel: 'Slingshot / autocycle',
      intro: [
        { type: 'p', text: 'Open-cockpit three-wheelers, such as the Polaris Slingshot, are a common sight on A1A and the Overseas Highway. They drive like a car and feel like a motorcycle, and Florida law treats them as something in between.' },
        { type: 'p', text: 'That in-between status is where the surprises are: a license question, a helmet question and an insurance question. Here are the answers in plain words, with links to the law, and the coverage gaps to close before your next ride.' },
      ],
      factsTitle: 'Autocycles in Florida: the key points',
      facts: [
        { value: '2 + 1', text: 'An autocycle has two wheels in front and one in back, a steering mechanism, roll cage or hoops and a seat belt for each occupant.', source: u('s316_003') },
        { value: 'No', text: 'motorcycle endorsement is needed to drive an autocycle in Florida. You still need a valid driver license.', source: u('s322_03') },
        { value: '4+', text: 'wheels: that is what Florida PIP and property damage requirements are written for. A three-wheeler is outside them.', source: u('flhsmvInsurance') },
        { value: '20.6%', text: 'of Florida drivers were uninsured in 2023, about 1 in 5 (Insurance Research Council estimate).', source: u('iiiUninsured') },
      ],
      figureAlt: 'Infographic. Florida autocycle at a glance: two wheels in front and one in back, steering wheel, seats you do not straddle, roll hoops and seat belts. A driver license is required but no motorcycle endorsement. It is a motorcycle under Florida law, so car PIP does not apply. Medical payments, uninsured motorist and liability coverage can help, depending on the policy.',
      figureCaption: 'Rules from ss. 316.003, 322.03 and 627.732, Florida Statutes, and FLHSMV.',
      gapsTitle: 'Where autocycle owners get caught short',
      gaps: [
        { h: 'Your own injuries', p: 'Because PIP applies to vehicles with four or more wheels, there is no PIP for you on three. An open cockpit offers less protection than a car. Medical payments and health insurance carry the load.' },
        { h: 'The driver who hits you has no insurance', p: 'About 1 in 5 Florida drivers is uninsured. Uninsured motorist coverage on your autocycle policy may be the only source that pays for your injuries.' },
        { h: 'Insured like the wrong vehicle', p: 'A three-wheeler is not a car and not a typical bike. Make sure the policy lists the vehicle correctly, with its passenger and its add-ons.' },
      ],
      coverageTitle: 'Coverage to ask about on an autocycle policy',
      coverage: [
        { h: 'Bodily injury and property damage liability', p: 'Injuries and damage you cause to others, up to your limits, plus legal defense.' },
        { h: 'Uninsured / underinsured motorist', p: 'Your injuries and lost income when the at-fault driver has no insurance or not enough.' },
        { h: 'Medical payments', p: 'Medical bills for you and your passenger after a crash, regardless of fault.' },
        { h: 'Collision and comprehensive', p: 'Damage from a crash, theft, flood, fire or a falling tree.' },
        { h: 'Custom parts and accessories', p: 'Wheels, audio, wraps, tops and lighting, if listed or included.' },
        { h: 'Roadside help and towing', p: 'A tow that can handle a three-wheeler, where offered.' },
      ],
      coverageNote: 'These are general descriptions. Availability, limits and exclusions depend on the policy.',
      body: [
        { type: 'h2', text: 'What counts as an autocycle in Florida' },
        { type: 'p', text: 'Florida defines an autocycle as a **three-wheeled motorcycle with two wheels in front and one in back**, a roll cage or roll hoops, a **seat belt for each occupant**, brakes that meet federal standard 122, a steering mechanism and **seating you do not straddle**, built to federal motorcycle safety standards ([s. 316.003](https://www.flsenate.gov/Laws/Statutes/2026/316.003)). The same statute says the word **motorcycle includes an autocycle**.' },
        { type: 'p', text: 'A three-wheeler with handlebars and a seat you sit astride does not fit that definition. Whether a specific model meets it depends on its equipment, so check the paperwork and the statute.' },
        { type: 'h2', text: 'Do you need a motorcycle endorsement for an autocycle?' },
        { type: 'p', text: 'No. Florida law says a person may operate an autocycle **without a motorcycle endorsement** ([s. 322.03](https://www.flsenate.gov/Laws/Statutes/2026/322.03)); you still need a valid driver license ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/motorcycle-motor-scooter-moped-and-motorized-scooter/)). Other two- and three-wheel motorcycles over 50 cc do need an endorsement, and FLHSMV lists a **3-Wheel Basic RiderCourse** among the courses that lead to one ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/)).' },
        { type: 'h2', text: 'Helmets and eye protection' },
        { type: 'p', text: 'Florida’s helmet and eye-protection law applies to motorcycle riders, and an autocycle is a motorcycle under Florida law. The law does not apply to people **riding within an enclosed cab** ([s. 316.211](https://www.flsenate.gov/Laws/Statutes/2026/316.211)). If your autocycle has an open cockpit, read the statute before you ride without a helmet or eye protection.' },
        { type: 'h2', text: 'Insurance: no PIP, but the Financial Responsibility Law applies' },
        { type: 'p', text: 'Florida requires PIP and property damage liability before you register a vehicle with **at least four wheels** ([FLHSMV](https://www.flhsmv.gov/insurance/), [s. 627.732](https://www.flsenate.gov/Laws/Statutes/2026/627.732)). An autocycle has three. The Financial Responsibility Law still applies: after certain crashes, the state can suspend the license and registration of a driver who cannot show the ability to pay for damages ([s. 324.051](https://www.flsenate.gov/Laws/Statutes/2026/324.051)); the proof amounts are $10,000, $20,000 and $10,000 ([s. 324.021](https://www.flsenate.gov/Laws/Statutes/2026/324.021)). Uninsured motorist coverage is offered under [s. 627.727](https://www.flsenate.gov/Laws/Statutes/2026/627.727) and can be rejected only in writing.' },
        { type: 'callout', title: 'Renting one for the weekend?', text: 'Before you rent a three-wheeler on vacation, ask whether your own policy follows you onto it, and what the rental agreement says about damage and injuries.' },
      ],
      checklistTitle: 'A quick check for your autocycle policy',
      checklist: [
        'Is the vehicle listed as what it is, a **three-wheeled autocycle**?',
        'Do you carry **uninsured motorist** coverage on it?',
        'How much **medical payments** coverage do you have for you and your passenger?',
        'Are your **liability limits** right for what you own and earn?',
        'Are **wheels, audio, wraps and tops** listed?',
        'Does the policy include **towing** that can handle a three-wheeler?',
      ],
      agentTitle: 'A personal agent when it counts: at claim time',
      agent: [
        { type: 'p', text: 'M&K Agency is a family-owned agency in Florida City with more than 5,000 clients across Florida and a team of 12 who speak English, Spanish and Russian.' },
        { type: 'p', text: 'After a crash or a theft, call or message us. We help you report the claim, explain what the policy pays and stay with you until it is settled. **Send us your policy and we’ll check your coverage.**' },
      ],
      faqTitle: 'Slingshot and autocycle insurance in Florida: common questions',
      faq: [
        { q: 'Do I need a motorcycle endorsement to drive a Slingshot in Florida?', a: 'Not if the vehicle meets Florida’s definition of an autocycle: s. 322.03 lets you operate an autocycle without a motorcycle endorsement. You still need a valid driver license. Three-wheelers with handlebars and a straddle seat are not autocycles and need an endorsement.' },
        { q: 'Is an autocycle a car or a motorcycle in Florida?', a: 'A motorcycle. Florida’s definition of motorcycle includes autocycles, which is why car rules like PIP do not apply to it.' },
        { q: 'Does my car’s PIP cover me in an autocycle?', a: 'Florida’s PIP law is written for vehicles with four or more wheels. Medical payments, health insurance and uninsured motorist coverage are the usual ways autocycle drivers protect themselves. Ask us how your policies fit together.' },
        { q: 'Do I need a helmet in an autocycle in Florida?', a: 'Florida’s helmet and eye-protection law applies to motorcycle riders and exempts people riding within an enclosed cab. An autocycle is a motorcycle under Florida law, so if yours is open, read s. 316.211 before you ride without a helmet.' },
        { q: 'Is insurance required for an autocycle in Florida?', a: 'The PIP and property damage requirement for registration applies to vehicles with four or more wheels. But the Financial Responsibility Law applies after a crash, and a serious injury claim can be far larger than any minimum. Liability and uninsured motorist coverage are what protect you.' },
        { q: 'Do you help with autocycle claims?', a: 'Yes. Call us or message us on WhatsApp. A licensed agent helps you report the claim and explains each step in English, Spanish or Russian.' },
      ],
      related: [
        { path: '/motorcycle-insurance-florida-city', label: 'Motorcycle insurance in Florida' },
        { path: '/blog/uninsured-motorist-coverage-florida', label: 'Uninsured motorist coverage in Florida, explained' },
      ],
      sources: srcList('en', [...KEYS]),
    },
    es: {
      metaTitle: 'Seguro de Slingshot y Autociclo en Florida | M&K Agency',
      metaDesc: '¿Necesita endoso de motocicleta para un autociclo en Florida? Por qué el PIP no aplica en tres ruedas y qué huecos de cobertura revisar con un agente local.',
      breadcrumb: 'Seguro de Slingshot y autociclo',
      kicker: 'Seguro de autociclos y vehículos de tres ruedas · Toda la Florida',
      h1a: 'Seguro de Slingshot y autociclo en Florida:',
      h1b: 'tres ruedas, aire libre y sin PIP que lo respalde.',
      answer: 'La ley de Florida llama **autociclo** a un vehículo de tres ruedas con dos ruedas adelante, volante y asientos de verdad, y usted puede manejarlo **sin endoso de motocicleta**. Pero para la ley sigue siendo una **motocicleta**, así que el PIP que lo cubre en un carro **no aplica**. Revisamos su cobertura y se la explicamos en español.',
      serviceType: 'Seguro de autociclos y motocicletas de tres ruedas',
      leadLabel: 'Slingshot / autociclo',
      intro: [
        { type: 'p', text: 'Los vehículos de tres ruedas descapotados, como el Polaris Slingshot, se ven mucho por la A1A y la Overseas Highway. Se manejan como un carro y se sienten como una moto, y la ley de Florida los pone en un punto intermedio.' },
        { type: 'p', text: 'En ese punto intermedio están las sorpresas: una pregunta de licencia, una de casco y una de seguro. Aquí tiene las respuestas con palabras claras y enlaces a la ley, y los huecos de cobertura que conviene cerrar antes de salir a pasear.' },
      ],
      factsTitle: 'Autociclos en Florida: lo esencial',
      facts: [
        { value: '2 + 1', text: 'Un autociclo tiene dos ruedas adelante y una atrás, sistema de dirección, jaula o arcos antivuelco y cinturón para cada ocupante.', source: u('s316_003') },
        { value: 'No', text: 'se necesita endoso de motocicleta para manejar un autociclo en Florida. Sí necesita licencia de conducir vigente.', source: u('s322_03') },
        { value: '4+', text: 'ruedas: para eso están escritos los requisitos de PIP y daños a la propiedad de Florida. Un vehículo de tres ruedas queda fuera.', source: u('flhsmvInsurance') },
        { value: '20.6%', text: 'de los conductores de Florida no tenían seguro en 2023, alrededor de 1 de cada 5 (estimación del Insurance Research Council).', source: u('iiiUninsured') },
      ],
      figureAlt: 'Infografía. El autociclo en Florida de un vistazo: dos ruedas adelante y una atrás, volante, asientos en los que no se va a horcajadas, arcos antivuelco y cinturones. Se necesita licencia de conducir pero no endoso de motocicleta. Para la ley de Florida es una motocicleta, así que el PIP del carro no aplica. Los pagos médicos, la cobertura de conductor sin seguro y la responsabilidad civil pueden ayudar, según la póliza.',
      figureCaption: 'Reglas de las ss. 316.003, 322.03 y 627.732 de los Estatutos de Florida y del FLHSMV.',
      gapsTitle: 'Dónde se quedan cortos los dueños de autociclos',
      gaps: [
        { h: 'Sus propias lesiones', p: 'Como el PIP aplica a vehículos de cuatro ruedas o más, en tres ruedas no tiene PIP. Una cabina abierta protege menos que un carro. Los pagos médicos y el seguro de salud cargan con el peso.' },
        { h: 'El que lo choca no tiene seguro', p: 'Alrededor de 1 de cada 5 conductores en Florida no tiene seguro. La cobertura de conductor sin seguro en la póliza de su autociclo puede ser lo único que pague sus lesiones.' },
        { h: 'Asegurado como otro vehículo', p: 'Un vehículo de tres ruedas no es un carro ni una moto típica. Asegúrese de que la póliza lo describa bien, con su pasajero y sus accesorios.' },
      ],
      coverageTitle: 'Coberturas que conviene preguntar para un autociclo',
      coverage: [
        { h: 'Responsabilidad civil por lesiones y daños', p: 'Lesiones y daños que usted cause a otros, hasta sus límites, y la defensa legal.' },
        { h: 'Conductor sin seguro o con seguro insuficiente', p: 'Sus lesiones y sus ingresos perdidos cuando el culpable no tiene seguro o no le alcanza.' },
        { h: 'Pagos médicos', p: 'Gastos médicos suyos y de su pasajero después de un choque, sin importar la culpa.' },
        { h: 'Choque y cobertura amplia', p: 'Daños por choque, robo, inundación, incendio o un árbol que cae.' },
        { h: 'Piezas personalizadas y accesorios', p: 'Rines, sonido, vinilos, techos e iluminación, si se declaran o están incluidos.' },
        { h: 'Asistencia en el camino y grúa', p: 'Una grúa que pueda con un vehículo de tres ruedas, cuando se ofrece.' },
      ],
      coverageNote: 'Son descripciones generales. La disponibilidad, los límites y las exclusiones dependen de la póliza.',
      body: [
        { type: 'h2', text: 'Qué es un autociclo en Florida' },
        { type: 'p', text: 'Florida define el autociclo como una **motocicleta de tres ruedas, con dos adelante y una atrás**, jaula o arcos antivuelco, **cinturón para cada ocupante**, frenos que cumplen la norma federal 122, sistema de dirección y **asientos en los que no se va a horcajadas**, fabricada según las normas federales de seguridad para motocicletas ([s. 316.003](https://www.flsenate.gov/Laws/Statutes/2026/316.003)). La misma ley dice que la palabra **motocicleta incluye el autociclo**.' },
        { type: 'p', text: 'Un vehículo de tres ruedas con manubrio y asiento a horcajadas no cumple esa definición. Que un modelo específico la cumpla depende de su equipo; revise los papeles y la ley.' },
        { type: 'h2', text: '¿Hace falta endoso de motocicleta para un autociclo?' },
        { type: 'p', text: 'No. La ley de Florida dice que se puede manejar un autociclo **sin endoso de motocicleta** ([s. 322.03](https://www.flsenate.gov/Laws/Statutes/2026/322.03)); sí necesita licencia de conducir vigente ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/motorcycle-motor-scooter-moped-and-motorized-scooter/)). Las demás motocicletas de dos o tres ruedas de más de 50 cc sí necesitan endoso, y el FLHSMV incluye un **curso básico para tres ruedas (3-Wheel Basic RiderCourse)** entre los que llevan a obtenerlo ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/)).' },
        { type: 'h2', text: 'Casco y protección para los ojos' },
        { type: 'p', text: 'La ley de casco y protección para los ojos de Florida aplica a los motociclistas, y para la ley de Florida un autociclo es una motocicleta. La ley no aplica a quienes **van dentro de una cabina cerrada** ([s. 316.211](https://www.flsenate.gov/Laws/Statutes/2026/316.211)). Si su autociclo es descapotado, lea la ley antes de salir sin casco o sin protección para los ojos.' },
        { type: 'h2', text: 'Seguro: sin PIP, pero aplica la Ley de Responsabilidad Financiera' },
        { type: 'p', text: 'Florida exige PIP y responsabilidad por daños a la propiedad antes de registrar un vehículo de **al menos cuatro ruedas** ([FLHSMV](https://www.flhsmv.gov/insurance/), [s. 627.732](https://www.flsenate.gov/Laws/Statutes/2026/627.732)). Un autociclo tiene tres. Aun así, aplica la Ley de Responsabilidad Financiera: después de ciertos choques, el estado puede suspender la licencia y el registro de quien no demuestre que podía pagar los daños ([s. 324.051](https://www.flsenate.gov/Laws/Statutes/2026/324.051)); los montos son $10,000, $20,000 y $10,000 ([s. 324.021](https://www.flsenate.gov/Laws/Statutes/2026/324.021)). La cobertura de conductor sin seguro se ofrece según la [s. 627.727](https://www.flsenate.gov/Laws/Statutes/2026/627.727) y solo se puede rechazar por escrito.' },
        { type: 'callout', title: '¿Lo va a alquilar el fin de semana?', text: 'Antes de alquilar un vehículo de tres ruedas en vacaciones, pregunte si su propia póliza lo cubre en él y qué dice el contrato de alquiler sobre daños y lesiones.' },
      ],
      checklistTitle: 'Revise la póliza de su autociclo',
      checklist: [
        '¿El vehículo aparece como lo que es, un **autociclo de tres ruedas**?',
        '¿Tiene cobertura de **conductor sin seguro** en él?',
        '¿Cuánto tiene en **pagos médicos** para usted y su pasajero?',
        '¿Sus **límites de responsabilidad civil** van de acuerdo con lo que tiene y lo que gana?',
        '¿Están declarados los **rines, el sonido, los vinilos y los techos**?',
        '¿La póliza incluye una **grúa** que pueda con tres ruedas?',
      ],
      agentTitle: 'Un agente personal cuando más importa: en el reclamo',
      agent: [
        { type: 'p', text: 'M&K Agency es una agencia familiar de Florida City con más de 5,000 clientes en toda la Florida y un equipo de 12 personas que hablan español, inglés y ruso.' },
        { type: 'p', text: 'Después de un choque o un robo, llámenos o escríbanos. Le ayudamos a reportar el reclamo, le explicamos qué paga la póliza y lo acompañamos hasta el final. **Envíenos su póliza y revisamos su cobertura.**' },
      ],
      faqTitle: 'Seguro de Slingshot y autociclo en Florida: preguntas frecuentes',
      faq: [
        { q: '¿Necesito endoso de motocicleta para manejar un Slingshot en Florida?', a: 'No, si el vehículo cumple la definición de autociclo de Florida: la s. 322.03 permite manejar un autociclo sin endoso de motocicleta. Sí necesita licencia de conducir vigente. Los vehículos de tres ruedas con manubrio y asiento a horcajadas no son autociclos y necesitan endoso.' },
        { q: '¿Un autociclo es un carro o una motocicleta en Florida?', a: 'Una motocicleta. La definición de motocicleta de Florida incluye los autociclos; por eso las reglas del carro, como el PIP, no le aplican.' },
        { q: '¿El PIP de mi carro me cubre en un autociclo?', a: 'La ley de PIP de Florida está escrita para vehículos de cuatro ruedas o más. Los pagos médicos, el seguro de salud y la cobertura de conductor sin seguro son la forma habitual de protegerse. Pregúntenos cómo encajan sus pólizas.' },
        { q: '¿Necesito casco en un autociclo en Florida?', a: 'La ley de casco y protección para los ojos aplica a los motociclistas y exime a quienes van dentro de una cabina cerrada. Para la ley de Florida un autociclo es una motocicleta, así que si el suyo es descapotado, lea la s. 316.211 antes de salir sin casco.' },
        { q: '¿El seguro es obligatorio para un autociclo en Florida?', a: 'El requisito de PIP y daños a la propiedad para el registro aplica a vehículos de cuatro ruedas o más. Pero la Ley de Responsabilidad Financiera aplica después de un choque, y un reclamo por lesiones graves puede ser mucho mayor que cualquier mínimo. La responsabilidad civil y la cobertura de conductor sin seguro son las que lo protegen.' },
        { q: '¿Me ayudan con un reclamo de autociclo?', a: 'Sí. Llámenos o escríbanos por WhatsApp. Un agente licenciado le ayuda a reportar el reclamo y le explica cada paso en español, inglés o ruso.' },
      ],
      related: [
        { path: '/motorcycle-insurance-florida-city', label: 'Seguro de motocicleta en Florida' },
        { path: '/blog/uninsured-motorist-coverage-florida', label: 'La cobertura de conductor sin seguro en Florida, explicada' },
      ],
      sources: srcList('es', [...KEYS]),
    },
    ru: {
      metaTitle: 'Страховка Slingshot и автоцикла во Флориде | M&K Agency',
      metaDesc: 'Нужна ли мотоциклетная отметка в правах для автоцикла во Флориде? Почему на трёх колёсах нет PIP и какие дыры в покрытии проверить с местным агентом.',
      breadcrumb: 'Страховка Slingshot и автоцикла',
      kicker: 'Страхование автоциклов и трёхколёсной техники · Вся Флорида',
      h1a: 'Страховка Slingshot и автоцикла во Флориде:',
      h1b: 'три колеса, открытый кокпит и никакого PIP за спиной.',
      answer: 'Закон Флориды называет **автоциклом** трёхколёсную машину с двумя колёсами спереди, рулём и нормальными сиденьями, и водить её можно **без мотоциклетной отметки в правах**. Но по закону это всё равно **мотоцикл**, поэтому PIP, который защищает вас в машине, **не действует**. Проверим ваше покрытие и объясним по-русски.',
      serviceType: 'Страхование автоциклов и трёхколёсных мотоциклов',
      leadLabel: 'Slingshot / автоцикл',
      intro: [
        { type: 'p', text: 'Открытые трёхколёсники вроде Polaris Slingshot — привычная картина на A1A и Overseas Highway. Управляются как машина, ощущаются как мотоцикл, и закон Флориды ставит их где-то посередине.' },
        { type: 'p', text: 'Именно в этой «середине» и прячутся сюрпризы: вопрос о правах, вопрос о шлеме и вопрос о страховке. Ниже — ответы простыми словами со ссылками на закон и дыры в покрытии, которые стоит закрыть до следующей поездки.' },
      ],
      factsTitle: 'Автоциклы во Флориде: главное',
      facts: [
        { value: '2 + 1', text: 'У автоцикла два колеса спереди и одно сзади, рулевое управление, каркас или дуги безопасности и ремень для каждого человека.', source: u('s316_003') },
        { value: 'Нет', text: '— мотоциклетная отметка для автоцикла во Флориде не нужна. Но действующие водительские права нужны.', source: u('s322_03') },
        { value: '4+', text: 'колеса — для таких машин написаны требования Флориды о PIP и ущербе имуществу. Трёхколёсник под них не попадает.', source: u('flhsmvInsurance') },
        { value: '20,6%', text: 'водителей во Флориде в 2023 году ездили без страховки — примерно каждый пятый (оценка Insurance Research Council).', source: u('iiiUninsured') },
      ],
      figureAlt: 'Инфографика. Автоцикл во Флориде коротко: два колеса спереди и одно сзади, руль, сиденья без посадки верхом, дуги безопасности и ремни. Нужны водительские права, но не мотоциклетная отметка. По закону Флориды это мотоцикл, поэтому автомобильный PIP не действует. Помочь могут медицинские расходы, покрытие UM и ответственность — в зависимости от полиса.',
      figureCaption: 'Правила — ст. 316.003, 322.03 и 627.732 Законов Флориды и FLHSMV.',
      gapsTitle: 'Где владельцы автоциклов остаются без защиты',
      gaps: [
        { h: 'Ваши собственные травмы', p: 'PIP распространяется на машины с четырьмя и более колёсами, поэтому на трёх колёсах его у вас нет. Открытый кокпит защищает хуже машины. Основная нагрузка ложится на медицинские расходы и медстраховку.' },
        { h: 'У виновника нет страховки', p: 'Примерно каждый пятый водитель во Флориде без страховки. Покрытие UM в полисе на автоцикл может оказаться единственным, что оплатит ваши травмы.' },
        { h: 'Застрахован не как то, что есть', p: 'Трёхколёсник — не машина и не обычный мотоцикл. Убедитесь, что в полисе он описан правильно, вместе с пассажиром и доп. оборудованием.' },
      ],
      coverageTitle: 'О каких покрытиях спросить в полисе на автоцикл',
      coverage: [
        { h: 'Ответственность за травмы и ущерб', p: 'Травмы и ущерб, причинённые вами другим, в пределах лимитов, плюс юридическая защита.' },
        { h: 'Водитель без страховки или с недостаточной (UM/UIM)', p: 'Ваши травмы и потерянный доход, когда у виновника нет страховки или её не хватает.' },
        { h: 'Медицинские расходы', p: 'Лечение вас и пассажира после аварии, независимо от вины.' },
        { h: 'Collision и comprehensive', p: 'Ущерб от аварии, угона, наводнения, пожара или упавшего дерева.' },
        { h: 'Тюнинг и аксессуары', p: 'Диски, аудио, плёнка, крыша и подсветка — если указаны или включены.' },
        { h: 'Помощь на дороге и эвакуатор', p: 'Эвакуатор, который справится с трёхколёсником, — там, где это предлагается.' },
      ],
      coverageNote: 'Это общие описания. Наличие покрытий, лимиты и исключения зависят от конкретного полиса.',
      body: [
        { type: 'h2', text: 'Что во Флориде считается автоциклом' },
        { type: 'p', text: 'Флорида определяет автоцикл как **трёхколёсный мотоцикл с двумя колёсами спереди и одним сзади**, с каркасом или дугами безопасности, **ремнём для каждого человека**, тормозами по федеральному стандарту 122, рулевым управлением и **сиденьями, на которых не сидят верхом**, построенный по федеральным стандартам безопасности мотоциклов ([ст. 316.003](https://www.flsenate.gov/Laws/Statutes/2026/316.003)). Та же статья говорит, что понятие **«мотоцикл» включает автоцикл**.' },
        { type: 'p', text: 'Трёхколёсник с мотоциклетным рулём и седлом, на котором сидят верхом, под это определение не подходит. Подходит ли конкретная модель, зависит от её оснащения — сверьтесь с документами и законом.' },
        { type: 'h2', text: 'Нужна ли мотоциклетная отметка для автоцикла?' },
        { type: 'p', text: 'Нет. Закон Флориды разрешает управлять автоциклом **без мотоциклетной отметки** ([ст. 322.03](https://www.flsenate.gov/Laws/Statutes/2026/322.03)); действующие водительские права при этом нужны ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/motorcycle-motor-scooter-moped-and-motorized-scooter/)). Для других двух- и трёхколёсных мотоциклов больше 50 куб. см отметка нужна, и среди курсов, которые к ней ведут, FLHSMV называет **базовый курс для трёхколёсных мотоциклов (3-Wheel Basic RiderCourse)** ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/)).' },
        { type: 'h2', text: 'Шлем и защита для глаз' },
        { type: 'p', text: 'Закон Флориды о шлемах и защите глаз распространяется на мотоциклистов, а автоцикл по закону Флориды — мотоцикл. Закон не применяется к тем, кто **едет в закрытой кабине** ([ст. 316.211](https://www.flsenate.gov/Laws/Statutes/2026/316.211)). Если у вашего автоцикла открытый кокпит, прочитайте статью, прежде чем ехать без шлема или очков.' },
        { type: 'h2', text: 'Страховка: PIP нет, но закон о финансовой ответственности действует' },
        { type: 'p', text: 'Флорида требует PIP и ответственность за ущерб имуществу при регистрации машины **минимум с четырьмя колёсами** ([FLHSMV](https://www.flhsmv.gov/insurance/), [ст. 627.732](https://www.flsenate.gov/Laws/Statutes/2026/627.732)). У автоцикла их три. Но закон о финансовой ответственности действует: после некоторых аварий штат может приостановить права и регистрацию водителя, который не докажет, что способен возместить ущерб ([ст. 324.051](https://www.flsenate.gov/Laws/Statutes/2026/324.051)); суммы — $10 000, $20 000 и $10 000 ([ст. 324.021](https://www.flsenate.gov/Laws/Statutes/2026/324.021)). Покрытие UM предлагается по [ст. 627.727](https://www.flsenate.gov/Laws/Statutes/2026/627.727), и отказаться от него можно только письменно.' },
        { type: 'callout', title: 'Берёте напрокат на выходные?', text: 'Прежде чем арендовать трёхколёсник в отпуске, уточните, распространяется ли на него ваш собственный полис и что договор аренды говорит об ущербе и травмах.' },
      ],
      checklistTitle: 'Короткая проверка полиса на автоцикл',
      checklist: [
        'Записан ли автомобиль в полисе как то, чем он является, — **трёхколёсный автоцикл**?',
        'Есть ли на нём покрытие **UM** (водитель без страховки)?',
        'Сколько покрытия **медицинских расходов** у вас и пассажира?',
        'Соответствуют ли **лимиты ответственности** тому, что у вас есть и сколько вы зарабатываете?',
        'Указаны ли **диски, аудио, плёнка и крыша**?',
        'Есть ли в полисе **эвакуатор**, который справится с тремя колёсами?',
      ],
      agentTitle: 'Личный агент, когда это важнее всего: при страховом случае',
      agent: [
        { type: 'p', text: 'M&K Agency — семейное агентство во Флорида-Сити: больше 5 000 клиентов по всей Флориде и команда из 12 человек, которые говорят по-русски, по-английски и по-испански.' },
        { type: 'p', text: 'После аварии или угона позвоните или напишите нам. Поможем заявить убыток, объясним, что платит полис, и будем рядом до конца урегулирования. **Пришлите полис — мы проверим ваше покрытие.**' },
      ],
      faqTitle: 'Страховка Slingshot и автоцикла во Флориде: частые вопросы',
      faq: [
        { q: 'Нужна ли мотоциклетная отметка, чтобы водить Slingshot во Флориде?', a: 'Нет, если машина подходит под определение автоцикла во Флориде: ст. 322.03 разрешает управлять автоциклом без мотоциклетной отметки. Действующие права нужны. Трёхколёсники с мотоциклетным рулём и седлом верхом — не автоциклы, для них отметка нужна.' },
        { q: 'Автоцикл во Флориде — это машина или мотоцикл?', a: 'Мотоцикл. Определение мотоцикла во Флориде включает автоциклы, поэтому автомобильные правила, например PIP, к нему не применяются.' },
        { q: 'Покрывает ли меня PIP от машины, когда я в автоцикле?', a: 'Закон Флориды о PIP написан для машин с четырьмя и более колёсами. Обычно водители автоциклов защищают себя покрытием медицинских расходов, медстраховкой и покрытием UM. Спросите нас, как ваши полисы дополняют друг друга.' },
        { q: 'Нужен ли шлем в автоцикле во Флориде?', a: 'Закон о шлемах и защите глаз распространяется на мотоциклистов и не применяется к тем, кто едет в закрытой кабине. По закону Флориды автоцикл — мотоцикл, поэтому, если ваш открытый, прочитайте ст. 316.211, прежде чем ехать без шлема.' },
        { q: 'Обязательна ли страховка на автоцикл во Флориде?', a: 'Требование PIP и ответственности за ущерб имуществу при регистрации относится к машинам с четырьмя и более колёсами. Но после аварии действует закон о финансовой ответственности, а иск за серьёзную травму может намного превысить любой минимум. Защищают вас ответственность и покрытие UM.' },
        { q: 'Помогаете ли вы со страховыми случаями по автоциклу?', a: 'Да. Позвоните или напишите в WhatsApp. Лицензированный агент поможет заявить убыток и объяснит каждый шаг по-русски, по-английски или по-испански.' },
      ],
      related: [
        { path: '/motorcycle-insurance-florida-city', label: 'Страховка мотоцикла во Флориде' },
        { path: '/blog/uninsured-motorist-coverage-florida', label: 'Покрытие UM во Флориде: подробный разбор' },
      ],
      sources: srcList('ru', [...KEYS]),
    },
  },
};
