import type { RecPage } from './types';
import { srcList, u } from './sources';

// Facts: FWC 2025 BASR summary (1,027,742 registered vessels; 694 accidents; 35% collision
// with fixed object; Monroe 72 accidents; 51 deaths, 53% drowning; 67% of operators in fatal
// accidents had no formal boater education); USCG 2024 (87% of drowning victims not wearing PFD);
// NHC climatology (June 1 - Nov 30); s. 327.59 (marina evacuation, fees, marina not liable);
// s. 823.11 (derelict vessels, 24 h, hurricane 45-day window); FWC storm prep page.
const KEYS = ['fwc2025', 'uscg2024', 'nhcClimo', 's327_59', 's823_11', 'fwcStorm', 's327_301', 's327_395', 's327_35'] as const;

export const BOAT: RecPage = {
  line: 'boat',
  path: '/boat-insurance-florida',
  leadValue: 'Boat',
  leadSource: 'rec-boat',
  articleSlug: 'hurricane-plan-for-your-boat-florida',
  productSlug: 'boat-insurance',
  published: '2026-10-03',
  modified: '2026-10-03',
  copy: {
    en: {
      metaTitle: 'Boat Insurance in Florida: Liability & Storms | M&K',
      metaDesc: 'Florida boating: liability on a crowded sandbar, hurricane haul-out, marina rules and towing. The coverage gaps to check, with a local agent.',
      breadcrumb: 'Boat insurance in Florida',
      kicker: 'Boat insurance · All of Florida',
      h1a: 'Boat insurance in Florida:',
      h1b: 'liability on the water, a plan for hurricane season.',
      answer: 'In Florida, the two biggest money risks for a boat owner are **hurting someone on the water** and **a named storm**. A good policy is built around both, plus towing and the people who ride with you. We check yours and explain it in your language.',
      serviceType: 'Boat insurance',
      leadLabel: 'Boat',
      intro: [
        { type: 'p', text: 'Florida has more registered boats than any other state, and South Florida waters are some of the busiest in the country. That means more chances of a collision, a guest hurt on board or damage to someone else’s boat or dock. Then, from June through November, every owner needs a storm plan: haul out, move or tie down.' },
        { type: 'p', text: 'This page explains the Florida rules that matter for boat owners, the coverage gaps we see most often and the questions to ask your agent, in plain words and with links to the law.' },
      ],
      factsTitle: 'Boating in Florida: what the numbers say',
      facts: [
        { value: '1,027,742', text: 'registered vessels in Florida in 2025, the most in the nation.', source: u('fwc2025') },
        { value: '694', text: 'reportable boating accidents in Florida in 2025. Collision with a fixed object was the leading type (35%).', source: u('fwc2025') },
        { value: '72', text: 'accidents in Monroe County (the Keys) in 2025, more than any other county.', source: u('fwc2025') },
        { value: '67%', text: 'of operators in Florida’s fatal boating accidents in 2025 had no formal boater education.', source: u('fwc2025') },
      ],
      figureAlt: 'Infographic. A Florida boat owner’s year: on the water, liability for injuries and damage to others; June 1 to November 30, hurricane season with a haul-out or tie-down plan; after a storm, the duty to remove a wrecked boat from the water. Liability, physical damage, towing and wreck removal coverage can help, depending on the policy.',
      figureCaption: 'Illustration. Hurricane season dates from the National Hurricane Center; rules from chapters 327 and 823, Florida Statutes.',
      gapsTitle: 'Where Florida boat owners get caught short',
      gaps: [
        { h: 'Someone gets hurt', p: 'A guest falls on deck, a swimmer is struck, another boat is hit. Liability and medical payments are what usually respond, and the limits matter.' },
        { h: 'The storm and the days after', p: 'Hauling out, moving the boat, wreck removal and cleanup can add up even before repairs. Some policies help with part of these costs; many have special storm deductibles.' },
        { h: 'Far from the dock', p: 'An engine that won’t start offshore or a soft grounding on a flat means a tow. Check what your policy says about towing and assistance.' },
      ],
      coverageTitle: 'Coverage to ask about on a Florida boat policy',
      coverage: [
        { h: 'Liability', p: 'Injuries and damage you cause to others, including other boats, docks and swimmers, up to your limits, plus legal defense.' },
        { h: 'Physical damage', p: 'Hull, engine and equipment after a collision, sinking, fire, theft or storm, based on how the policy values the boat.' },
        { h: 'Medical payments and uninsured boater', p: 'Medical bills for you and your guests, and help when another boater who injures you has no insurance.' },
        { h: 'Towing and on-water assistance', p: 'A tow back to the ramp or marina, fuel delivery or a jump start, if included.' },
        { h: 'Wreck removal and hurricane haul-out', p: 'Some policies help pay to remove a sunken boat or to haul it out before a named storm.' },
        { h: 'Trailer, gear and personal items', p: 'Your trailer, electronics, fishing gear and other equipment, if listed or included.' },
      ],
      coverageNote: 'These are general descriptions. Availability, limits, deductibles and exclusions depend on the policy.',
      body: [
        { type: 'h2', text: 'Hurricane season: what Florida law says about marinas' },
        { type: 'p', text: 'The Atlantic hurricane season runs from **June 1 to November 30** ([National Hurricane Center](https://www.nhc.noaa.gov/climo/)). Florida law does not let marinas require owners to take their boats out when a hurricane watch or warning is issued, so that people’s safety comes first. But after a tropical storm or hurricane watch, the marina may take reasonable steps to secure your boat and **charge a reasonable fee**. If your contract includes the notice the law describes, the marina may even **move your boat** if you don’t remove it promptly, and it is generally not liable for storm damage to your vessel ([s. 327.59](https://www.flsenate.gov/Laws/Statutes/2026/327.59)).' },
        { type: 'p', text: 'FWC’s advice is to trailer the boat and move it as far from tidal waters as you can. If it must stay in the water, double the lines, add spring lines, attach them high on the pilings for surge, protect against chafe and keep the batteries charged for the bilge pumps. Never stay aboard during the storm ([FWC](https://myfwc.com/boating/safety-education/hurricane/)).' },
        { type: 'h2', text: 'After the storm: a wrecked boat is still your responsibility' },
        { type: 'p', text: 'In Florida, an owner may not leave a derelict vessel on state waters for more than 24 hours. If the boat became derelict because of a hurricane, the owner is not charged if he or she documents what happened and removes or repairs it **within 45 days after the hurricane has passed** ([s. 823.11](https://www.flsenate.gov/Laws/Statutes/2026/823.11)). Raising and removing a sunken boat can be expensive, which is why wreck removal coverage is worth asking about.' },
        { type: 'h2', text: 'Accidents, reports and life jackets' },
        { type: 'p', text: 'If an accident causes an injury needing more than first aid, a death or disappearance, or at least **$2,000** in damage, the operator must send a written report to FWC ([s. 327.301](https://www.flsenate.gov/Laws/Statutes/2026/327.301)). Nationally, where life jacket use was known, **87% of people who drowned in boating incidents in 2024 were not wearing one** ([USCG](https://uscgboating.org/library/accident-statistics/Recreational-Boating-Statistics-2024.pdf)).' },
        { type: 'callout', title: 'Boater ID', text: 'Anyone born on or after January 1, 1988, needs a Boating Safety Education ID card or another accepted document to operate a boat with a motor of 10 horsepower or more ([s. 327.395](https://www.flsenate.gov/Laws/Statutes/2026/327.395)). Tell your agent who drives your boat.' },
      ],
      checklistTitle: 'A quick check of your boat policy before the next storm',
      checklist: [
        'Read the **named storm or hurricane deductible** on your declarations page.',
        'Ask whether your policy helps with **hurricane haul-out or moving the boat**.',
        'Check for **wreck removal** and how much it pays.',
        'Read your **marina or storage contract** for the hurricane clause and fees.',
        'Check your **liability limits** and whether **guests and other operators** are covered.',
        'Make sure your **cruising area** in the policy matches where you really go, including the Keys and the Bahamas.',
      ],
      agentTitle: 'A personal agent when it counts: at claim time',
      agent: [
        { type: 'p', text: 'M&K Agency is a family-owned agency in Florida City, the gateway to the Keys, with more than 5,000 clients across Florida and a team of 12 who speak English, Spanish and Russian.' },
        { type: 'p', text: 'After an accident or a storm, call or message us. We help you report the claim, explain what the policy pays and stay with you until it is settled. **Send us your policy and we’ll check your coverage.**' },
      ],
      faqTitle: 'Boat insurance in Florida: common questions',
      faq: [
        { q: 'Is boat insurance required in Florida?', a: 'Florida’s boating laws set insurance rules for rental businesses, not a general insurance requirement for private boat owners. A marina, storage or HOA contract may require proof of liability coverage, so read yours. Either way, an owner can be sued for injuries or damage the boat causes.' },
        { q: 'Can my marina make me take my boat out before a hurricane?', a: 'Florida law doesn’t let a marina require you to remove your boat when a hurricane watch or warning is issued. After a watch, the marina may take reasonable steps to secure your boat and charge a reasonable fee, and with the right notice in your contract it may move the boat if you don’t remove it promptly.' },
        { q: 'Does boat insurance pay to haul out my boat before a storm?', a: 'Some policies help pay part of the cost of hauling out or moving a boat ahead of a named storm. It depends on the policy, so ask before the season starts.' },
        { q: 'What if my boat sinks in a hurricane?', a: 'You are responsible for getting it out of the water. Florida gives owners 45 days after a hurricane to remove or repair a boat that became derelict because of the storm, if they document what happened. Wreck removal coverage, if your policy has it, can help with the cost.' },
        { q: 'Does my homeowners policy cover my boat?', a: 'Often only in a limited way for small boats, and many home policies exclude larger or faster boats and liability on the water. Send us your home policy and we will tell you what it says.' },
        { q: 'Do you help with boat claims?', a: 'Yes. Call us or message us on WhatsApp after an accident or storm. A licensed agent helps you report the claim and explains each step in English, Spanish or Russian.' },
      ],
      related: [
        { path: '/jet-ski-insurance-florida', label: 'Jet ski (PWC) insurance in Florida' },
        { path: '/umbrella-insurance-florida-city', label: 'Umbrella insurance: extra liability protection' },
      ],
      sources: srcList('en', [...KEYS]),
    },
    es: {
      metaTitle: 'Seguro de Bote en Florida: Responsabilidad y Huracanes',
      metaDesc: 'Navegar en Florida: responsabilidad civil en el agua, sacar el bote antes de un huracán, reglas de marinas y remolque. Revise su cobertura con nosotros.',
      breadcrumb: 'Seguro de bote en Florida',
      kicker: 'Seguro de bote · Toda la Florida',
      h1a: 'Seguro de bote en Florida:',
      h1b: 'responsabilidad en el agua y un plan para los huracanes.',
      answer: 'En Florida, los dos riesgos de dinero más grandes para el dueño de un bote son **lesionar a alguien en el agua** y **una tormenta con nombre**. Una buena póliza se arma pensando en los dos, más el remolque y las personas que van con usted. Revisamos la suya y se la explicamos en español.',
      serviceType: 'Seguro de embarcaciones',
      leadLabel: 'Bote',
      intro: [
        { type: 'p', text: 'Florida tiene más botes registrados que cualquier otro estado, y las aguas del sur de la Florida están entre las más transitadas del país. Eso significa más posibilidades de un choque, de un invitado lesionado a bordo o de daños al bote o al muelle de otra persona. Y de junio a noviembre, todo dueño necesita un plan para las tormentas: sacarlo del agua, moverlo o amarrarlo bien.' },
        { type: 'p', text: 'Aquí explicamos las reglas de Florida que importan para los dueños de botes, los huecos de cobertura que más vemos y las preguntas que conviene hacerle a su agente, con palabras claras y enlaces a la ley.' },
      ],
      factsTitle: 'Navegar en Florida: lo que dicen las cifras',
      facts: [
        { value: '1,027,742', text: 'embarcaciones registradas en Florida en 2025, más que en cualquier otro estado.', source: u('fwc2025') },
        { value: '694', text: 'accidentes náuticos reportables en Florida en 2025. El tipo más común fue el choque contra un objeto fijo (35%).', source: u('fwc2025') },
        { value: '72', text: 'accidentes en el condado de Monroe (los Cayos) en 2025, más que en cualquier otro condado.', source: u('fwc2025') },
        { value: '67%', text: 'de quienes manejaban en los accidentes náuticos mortales de Florida en 2025 no tenía educación náutica formal.', source: u('fwc2025') },
      ],
      figureAlt: 'Infografía. El año del dueño de un bote en Florida: en el agua, la responsabilidad por lesiones y daños a otros; del 1 de junio al 30 de noviembre, la temporada de huracanes con un plan para sacar o amarrar el bote; después de la tormenta, la obligación de retirar del agua un bote hundido. La responsabilidad civil, el daño físico, el remolque y el retiro de restos pueden ayudar, según la póliza.',
      figureCaption: 'Ilustración. Fechas de la temporada del Centro Nacional de Huracanes; reglas de los capítulos 327 y 823 de los Estatutos de Florida.',
      gapsTitle: 'Dónde se quedan cortos los dueños de botes en Florida',
      gaps: [
        { h: 'Alguien sale lesionado', p: 'Un invitado se cae en cubierta, golpean a un bañista, chocan con otro bote. Normalmente responden la responsabilidad civil y los pagos médicos, y los límites importan.' },
        { h: 'La tormenta y los días después', p: 'Sacar el bote, moverlo, retirar los restos y limpiar puede costar mucho, aun antes de las reparaciones. Algunas pólizas ayudan con parte de estos gastos; muchas tienen deducibles especiales para tormentas.' },
        { h: 'Lejos del muelle', p: 'Un motor que no arranca mar afuera o una varada suave en un bajo significan un remolque. Revise qué dice su póliza sobre remolque y asistencia.' },
      ],
      coverageTitle: 'Coberturas que conviene preguntar en una póliza de bote en Florida',
      coverage: [
        { h: 'Responsabilidad civil', p: 'Lesiones y daños que usted cause a otros, incluidos otros botes, muelles y bañistas, hasta sus límites, y la defensa legal.' },
        { h: 'Daño físico', p: 'Casco, motor y equipo después de un choque, hundimiento, incendio, robo o tormenta, según cómo la póliza valore el bote.' },
        { h: 'Pagos médicos y navegante sin seguro', p: 'Gastos médicos suyos y de sus invitados, y ayuda cuando el navegante que lo lesiona no tiene seguro.' },
        { h: 'Remolque y asistencia en el agua', p: 'Remolque hasta la rampa o la marina, entrega de combustible o arranque de batería, si está incluido.' },
        { h: 'Retiro de restos y salida del agua por huracán', p: 'Algunas pólizas ayudan a pagar el retiro de un bote hundido o sacarlo del agua antes de una tormenta con nombre.' },
        { h: 'Tráiler, equipo y objetos personales', p: 'Su tráiler, la electrónica, el equipo de pesca y otros equipos, si se declaran o están incluidos.' },
      ],
      coverageNote: 'Son descripciones generales. La disponibilidad, los límites, los deducibles y las exclusiones dependen de la póliza.',
      body: [
        { type: 'h2', text: 'Temporada de huracanes: lo que dice la ley de Florida sobre las marinas' },
        { type: 'p', text: 'La temporada de huracanes del Atlántico va del **1 de junio al 30 de noviembre** ([Centro Nacional de Huracanes](https://www.nhc.noaa.gov/climo/)). La ley de Florida no permite que una marina obligue a los dueños a sacar sus botes cuando se emite una vigilancia o un aviso de huracán, para que la seguridad de las personas vaya primero. Pero después de una vigilancia de tormenta tropical o de huracán, la marina puede tomar medidas razonables para asegurar su bote y **cobrarle un cargo razonable**. Si su contrato incluye el aviso que describe la ley, la marina incluso puede **mover su bote** si usted no lo saca a tiempo, y en general no responde por los daños de la tormenta a su embarcación ([s. 327.59](https://www.flsenate.gov/Laws/Statutes/2026/327.59)).' },
        { type: 'p', text: 'La FWC recomienda subir el bote al tráiler y llevarlo lo más lejos posible de las aguas con marea. Si tiene que quedarse en el agua, duplique los cabos, agregue cabos de resorte, amárrelos alto en los pilotes por la marejada, protéjalos del roce y mantenga cargadas las baterías de las bombas de achique. Nunca se quede a bordo durante la tormenta ([FWC](https://myfwc.com/boating/safety-education/hurricane/)).' },
        { type: 'h2', text: 'Después de la tormenta: el bote hundido sigue siendo su responsabilidad' },
        { type: 'p', text: 'En Florida, el dueño no puede dejar una embarcación abandonada o naufragada en aguas del estado por más de 24 horas. Si el bote quedó así por un huracán, no lo multan si documenta lo que pasó y lo retira o lo repara **dentro de los 45 días después de que pasó el huracán** ([s. 823.11](https://www.flsenate.gov/Laws/Statutes/2026/823.11)). Reflotar y retirar un bote hundido puede salir caro; por eso vale la pena preguntar por la cobertura de retiro de restos.' },
        { type: 'h2', text: 'Accidentes, reportes y chalecos salvavidas' },
        { type: 'p', text: 'Si un accidente causa una lesión que necesita más que primeros auxilios, una muerte o desaparición, o al menos **$2,000** en daños, quien maneja debe enviar un reporte escrito a la FWC ([s. 327.301](https://www.flsenate.gov/Laws/Statutes/2026/327.301)). En todo el país, cuando se supo si llevaban chaleco, **el 87% de quienes se ahogaron en accidentes náuticos en 2024 no lo llevaba puesto** ([USCG](https://uscgboating.org/library/accident-statistics/Recreational-Boating-Statistics-2024.pdf)).' },
        { type: 'callout', title: 'Tarjeta de navegante', text: 'Quien haya nacido el 1 de enero de 1988 o después necesita la tarjeta de educación en seguridad náutica u otro documento aceptado para manejar un bote con motor de 10 caballos de fuerza o más ([s. 327.395](https://www.flsenate.gov/Laws/Statutes/2026/327.395)). Dígale a su agente quién maneja su bote.' },
      ],
      checklistTitle: 'Revise su póliza de bote antes de la próxima tormenta',
      checklist: [
        'Lea el **deducible por tormenta con nombre o huracán** en su página de declaraciones.',
        'Pregunte si su póliza ayuda a **sacar o mover el bote antes de un huracán**.',
        'Revise si tiene **retiro de restos** y cuánto paga.',
        'Lea la **cláusula de huracanes y los cargos** en el contrato de su marina o depósito.',
        'Revise sus **límites de responsabilidad civil** y si están cubiertos **los invitados y otros conductores**.',
        'Confirme que la **zona de navegación** de la póliza coincide con donde de verdad navega, incluidos los Cayos y las Bahamas.',
      ],
      agentTitle: 'Un agente personal cuando más importa: en el reclamo',
      agent: [
        { type: 'p', text: 'M&K Agency es una agencia familiar de Florida City, la puerta de entrada a los Cayos, con más de 5,000 clientes en toda la Florida y un equipo de 12 personas que hablan español, inglés y ruso.' },
        { type: 'p', text: 'Después de un accidente o de una tormenta, llámenos o escríbanos. Le ayudamos a reportar el reclamo, le explicamos qué paga la póliza y lo acompañamos hasta el final. **Envíenos su póliza y revisamos su cobertura.**' },
      ],
      faqTitle: 'Seguro de bote en Florida: preguntas frecuentes',
      faq: [
        { q: '¿Es obligatorio el seguro de bote en Florida?', a: 'Las leyes náuticas de Florida fijan reglas de seguro para los negocios de alquiler, no un requisito general para los dueños particulares. El contrato de una marina, un depósito o su HOA puede exigir prueba de responsabilidad civil, así que lea el suyo. De todos modos, al dueño lo pueden demandar por lesiones o daños causados con el bote.' },
        { q: '¿La marina me puede obligar a sacar el bote antes de un huracán?', a: 'La ley de Florida no permite que una marina lo obligue a sacar su bote cuando se emite una vigilancia o un aviso de huracán. Después de una vigilancia, la marina puede tomar medidas razonables para asegurarlo y cobrar un cargo razonable, y con el aviso correcto en su contrato puede mover el bote si usted no lo saca a tiempo.' },
        { q: '¿El seguro paga por sacar el bote del agua antes de una tormenta?', a: 'Algunas pólizas ayudan con parte del costo de sacar o mover el bote antes de una tormenta con nombre. Depende de la póliza, así que pregunte antes de que empiece la temporada.' },
        { q: '¿Qué pasa si mi bote se hunde en un huracán?', a: 'Usted es responsable de sacarlo del agua. Florida da 45 días después del huracán para retirar o reparar un bote que quedó naufragado por la tormenta, si se documenta lo que pasó. La cobertura de retiro de restos, si su póliza la tiene, puede ayudar con el costo.' },
        { q: '¿Mi seguro de casa cubre mi bote?', a: 'Muchas veces solo de forma limitada para botes pequeños, y muchas pólizas de casa excluyen botes más grandes o rápidos y la responsabilidad en el agua. Envíenos su póliza de casa y le decimos qué dice.' },
        { q: '¿Me ayudan con un reclamo de bote?', a: 'Sí. Llámenos o escríbanos por WhatsApp después de un accidente o de una tormenta. Un agente licenciado le ayuda a reportar el reclamo y le explica cada paso en español, inglés o ruso.' },
      ],
      related: [
        { path: '/jet-ski-insurance-florida', label: 'Seguro de jet ski (moto acuática) en Florida' },
        { path: '/umbrella-insurance-florida-city', label: 'Seguro umbrella: más protección de responsabilidad civil' },
      ],
      sources: srcList('es', [...KEYS]),
    },
    ru: {
      metaTitle: 'Страховка лодки во Флориде: ответственность и ураганы',
      metaDesc: 'Лодка во Флориде: ответственность на воде, подъём из воды перед ураганом, правила марин и буксировка. Проверим, где дыры в вашем покрытии.',
      breadcrumb: 'Страховка лодки во Флориде',
      kicker: 'Страховка лодки · Вся Флорида',
      h1a: 'Страховка лодки во Флориде:',
      h1b: 'ответственность на воде и план на сезон ураганов.',
      answer: 'Во Флориде два главных финансовых риска для владельца лодки — **травмировать кого-то на воде** и **именной шторм**. Хороший полис строится вокруг обоих, плюс буксировка и люди, которые выходят с вами. Проверим ваш полис и объясним по-русски.',
      serviceType: 'Страхование лодок',
      leadLabel: 'Лодка',
      intro: [
        { type: 'p', text: 'Во Флориде зарегистрировано больше лодок, чем в любом другом штате, а воды Южной Флориды — одни из самых загруженных в стране. Значит, больше шансов на столкновение, травму гостя на борту или ущерб чужой лодке либо причалу. А с июня по ноябрь каждому владельцу нужен план на шторм: поднять лодку из воды, перегнать или как следует закрепить.' },
        { type: 'p', text: 'Здесь — правила Флориды, важные для владельцев лодок, самые частые дыры в покрытии и вопросы, которые стоит задать агенту. Простыми словами и со ссылками на закон.' },
      ],
      factsTitle: 'Лодки во Флориде: что говорят цифры',
      facts: [
        { value: '1 027 742', text: 'зарегистрированных судна во Флориде в 2025 году — больше, чем в любом другом штате.', source: u('fwc2025') },
        { value: '694', text: 'зарегистрированных происшествия на воде во Флориде в 2025 году. Чаще всего — столкновение с неподвижным объектом (35%).', source: u('fwc2025') },
        { value: '72', text: 'происшествия в округе Монро (Кис) в 2025 году — больше, чем в любом другом округе.', source: u('fwc2025') },
        { value: '67%', text: 'судоводителей в смертельных происшествиях во Флориде в 2025 году не проходили никакого обучения.', source: u('fwc2025') },
      ],
      figureAlt: 'Инфографика. Год владельца лодки во Флориде: на воде — ответственность за травмы и ущерб другим; с 1 июня по 30 ноября — сезон ураганов и план подъёма или закрепления лодки; после шторма — обязанность убрать затонувшую лодку из воды. Помочь могут ответственность, ущерб самой лодке, буксировка и удаление обломков — в зависимости от полиса.',
      figureCaption: 'Иллюстрация. Сроки сезона — по данным Национального центра по ураганам; правила — главы 327 и 823 Законов Флориды.',
      gapsTitle: 'Где владельцы лодок во Флориде остаются без защиты',
      gaps: [
        { h: 'Кто-то пострадал', p: 'Гость упал на палубе, задели пловца, столкнулись с другой лодкой. Обычно тут работают ответственность и медицинские расходы — и важны лимиты.' },
        { h: 'Шторм и дни после него', p: 'Подъём, перегон, удаление обломков и уборка стоят денег ещё до ремонта. Некоторые полисы помогают с частью этих расходов; у многих есть отдельная франшиза на шторм.' },
        { h: 'Далеко от причала', p: 'Двигатель не заводится в море или лодка мягко села на мель — нужна буксировка. Проверьте, что ваш полис говорит о буксировке и помощи на воде.' },
      ],
      coverageTitle: 'О каких покрытиях спросить в полисе на лодку',
      coverage: [
        { h: 'Ответственность (liability)', p: 'Травмы и ущерб, причинённые другим — лодкам, причалам, пловцам, — в пределах лимитов, плюс юридическая защита.' },
        { h: 'Ущерб самой лодке', p: 'Корпус, двигатель и оборудование после столкновения, затопления, пожара, угона или шторма — в зависимости от того, как полис оценивает лодку.' },
        { h: 'Медицинские расходы и судоводитель без страховки', p: 'Лечение вас и ваших гостей и помощь, если у того, кто вас травмировал, нет страховки.' },
        { h: 'Буксировка и помощь на воде', p: 'Буксировка до слипа или марины, доставка топлива, запуск двигателя — если включено.' },
        { h: 'Удаление обломков и подъём перед ураганом', p: 'Некоторые полисы помогают оплатить подъём затонувшей лодки или её вывоз из воды перед именным штормом.' },
        { h: 'Прицеп, снаряжение и личные вещи', p: 'Прицеп, электроника, рыболовное снаряжение и другое оборудование — если указано или включено.' },
      ],
      coverageNote: 'Это общие описания. Наличие покрытий, лимиты, франшизы и исключения зависят от конкретного полиса.',
      body: [
        { type: 'h2', text: 'Сезон ураганов: что закон Флориды говорит о маринах' },
        { type: 'p', text: 'Сезон ураганов в Атлантике длится **с 1 июня по 30 ноября** ([Национальный центр по ураганам](https://www.nhc.noaa.gov/climo/)). Закон Флориды не разрешает маринам требовать, чтобы владельцы уводили лодки после объявления штормового предупреждения (hurricane watch или warning): безопасность людей важнее. Но после объявления watch марина может принять разумные меры, чтобы закрепить вашу лодку, и **взять за это разумную плату**. Если в вашем договоре есть уведомление, описанное в законе, марина может даже **переставить лодку**, если вы не увели её вовремя, и, как правило, не отвечает за ущерб, который шторм причинит вашему судну ([ст. 327.59](https://www.flsenate.gov/Laws/Statutes/2026/327.59)).' },
        { type: 'p', text: 'FWC советует поставить лодку на прицеп и увезти как можно дальше от приливных вод. Если она остаётся на воде, удвойте швартовы, заведите шпринги, крепите их высоко на сваях с запасом на нагон воды, защитите от перетирания и держите заряженными аккумуляторы трюмных помп. И никогда не оставайтесь на борту во время шторма ([FWC](https://myfwc.com/boating/safety-education/hurricane/)).' },
        { type: 'h2', text: 'После шторма: затонувшая лодка — всё ещё ваша ответственность' },
        { type: 'p', text: 'Во Флориде владелец не вправе оставлять брошенное или разбитое судно в водах штата дольше 24 часов. Если лодка оказалась в таком состоянии из-за урагана, владельца не накажут, если он задокументирует, что произошло, и уберёт или отремонтирует её **в течение 45 дней после прохождения урагана** ([ст. 823.11](https://www.flsenate.gov/Laws/Statutes/2026/823.11)). Подъём и вывоз затонувшей лодки обходятся дорого — поэтому стоит спросить о покрытии удаления обломков.' },
        { type: 'h2', text: 'Происшествия, отчёты и спасжилеты' },
        { type: 'p', text: 'Если в происшествии кто-то получил травму, требующую больше чем первой помощи, погиб или пропал, либо ущерб составил не меньше **$2 000**, судоводитель обязан подать письменный отчёт в FWC ([ст. 327.301](https://www.flsenate.gov/Laws/Statutes/2026/327.301)). По всей стране в 2024 году **87% утонувших в происшествиях на воде были без спасжилета** — среди тех случаев, где это известно ([USCG](https://uscgboating.org/library/accident-statistics/Recreational-Boating-Statistics-2024.pdf)).' },
        { type: 'callout', title: 'Удостоверение FWC', text: 'Тем, кто родился 1 января 1988 года или позже, для управления лодкой с мотором от 10 л. с. нужно удостоверение FWC об обучении безопасности на воде или другой принятый документ ([ст. 327.395](https://www.flsenate.gov/Laws/Statutes/2026/327.395)). Скажите агенту, кто управляет вашей лодкой.' },
      ],
      checklistTitle: 'Проверьте полис на лодку до следующего шторма',
      checklist: [
        'Найдите на странице деклараций **франшизу на именной шторм или ураган**.',
        'Спросите, помогает ли полис **поднять или перегнать лодку перед ураганом**.',
        'Проверьте, есть ли **удаление обломков** и на какую сумму.',
        'Прочитайте **ураганный пункт и сборы** в договоре с мариной или стоянкой.',
        'Проверьте **лимиты ответственности** и покрыты ли **гости и другие судоводители**.',
        'Убедитесь, что **район плавания** в полисе совпадает с тем, куда вы реально ходите, включая Кис и Багамы.',
      ],
      agentTitle: 'Личный агент, когда это важнее всего: при страховом случае',
      agent: [
        { type: 'p', text: 'M&K Agency — семейное агентство во Флорида-Сити, у самых ворот в Кис: больше 5 000 клиентов по всей Флориде и команда из 12 человек, которые говорят по-русски, по-английски и по-испански.' },
        { type: 'p', text: 'После происшествия или шторма позвоните или напишите нам. Поможем заявить убыток, объясним, что платит полис, и будем рядом до конца урегулирования. **Пришлите полис — мы проверим ваше покрытие.**' },
      ],
      faqTitle: 'Страховка лодки во Флориде: частые вопросы',
      faq: [
        { q: 'Обязательна ли страховка лодки во Флориде?', a: 'Законы Флориды о судоходстве устанавливают требования к страховке для пунктов проката, а не общее требование для частных владельцев. Но договор с мариной, стоянкой или HOA может требовать подтверждение страховки ответственности — прочитайте свой. И в любом случае владельца могут засудить за травмы или ущерб, причинённые лодкой.' },
        { q: 'Может ли марина заставить меня увести лодку перед ураганом?', a: 'Закон Флориды не разрешает марине требовать, чтобы вы увели лодку после объявления hurricane watch или warning. После объявления watch марина может разумно закрепить лодку и взять разумную плату, а при нужном уведомлении в договоре — переставить лодку, если вы не увели её вовремя.' },
        { q: 'Оплачивает ли страховка подъём лодки из воды перед штормом?', a: 'Некоторые полисы помогают оплатить часть расходов на подъём или перегон лодки перед именным штормом. Это зависит от полиса — спросите до начала сезона.' },
        { q: 'Что если моя лодка затонет во время урагана?', a: 'Убрать её из воды обязаны вы. После урагана Флорида даёт владельцу 45 дней, чтобы убрать или отремонтировать лодку, пострадавшую от шторма, если он задокументировал, что произошло. Помочь с расходами может покрытие удаления обломков, если оно есть в полисе.' },
        { q: 'Покрывает ли лодку моя страховка дома?', a: 'Часто лишь ограниченно и только для маленьких лодок, а многие полисы на дом исключают более крупные или быстрые лодки и ответственность на воде. Пришлите нам полис на дом — скажем, что там написано.' },
        { q: 'Помогаете ли вы со страховыми случаями по лодке?', a: 'Да. После происшествия или шторма позвоните или напишите в WhatsApp. Лицензированный агент поможет заявить убыток и объяснит каждый шаг по-русски, по-английски или по-испански.' },
      ],
      related: [
        { path: '/jet-ski-insurance-florida', label: 'Страховка гидроцикла во Флориде' },
        { path: '/umbrella-insurance-florida-city', label: 'Umbrella: дополнительная защита ответственности' },
      ],
      sources: srcList('ru', [...KEYS]),
    },
  },
};
