import type { RecPage } from './types';
import { srcList, u } from './sources';

// Facts: s. 316.212 (designated roads + signs; sunrise-sunset unless authorized with
// headlights, brake lights, turn signals, windshield; equipment; under 18 needs learner's
// or driver license, 18+ needs government photo ID; stricter local ordinances);
// s. 320.01 (golf cart <= 20 mph; LSV > 20 and <= 25 mph); s. 316.2122 (LSV roads <= 35 mph,
// equipment, registered and insured, driver license); s. 316.2125 (retirement communities);
// FLHSMV LSV page (PIP + PDL, golf cart conversion inspection); FLHSMV TL-63 (golf carts are
// not titled or registered).
const KEYS = ['s316_212', 's320_01', 's316_2122', 's316_2125', 'flhsmvLsv', 'flhsmvTl63'] as const;

export const GOLF_CART: RecPage = {
  line: 'golf-cart',
  path: '/golf-cart-insurance-florida',
  leadValue: 'Golf cart / LSV',
  leadSource: 'rec-golf-cart',
  articleSlug: 'golf-cart-rules-florida-public-roads',
  productSlug: 'golf-cart-insurance',
  published: '2026-10-03',
  modified: '2026-10-03',
  copy: {
    en: {
      metaTitle: 'Golf Cart & LSV Insurance in Florida | M&K Agency',
      metaDesc: 'Florida golf cart rules on public roads, who may drive, and how a low-speed vehicle differs. Plus the liability and injury gaps to check with a local agent.',
      breadcrumb: 'Golf cart and LSV insurance',
      kicker: 'Golf cart and low-speed vehicle insurance · All of Florida',
      h1a: 'Golf cart insurance in Florida:',
      h1b: 'for the neighborhood, the community and the grandkids in the back seat.',
      answer: 'In Florida a golf cart can only use **roads a city or county has designated**, and drivers **under 18 need a learner’s or driver license**. A street-legal **low-speed vehicle (LSV)** follows different rules. Either way, an injured passenger or pedestrian can mean a serious claim. We check your coverage and explain it in your language.',
      serviceType: 'Golf cart and low-speed vehicle insurance',
      leadLabel: 'Golf cart / LSV',
      intro: [
        { type: 'p', text: 'Golf carts are everywhere in Florida: retirement communities, beach towns, gated neighborhoods, RV parks and farms in South Dade. Many families treat them like toys. Florida law and an injury claim treat them more seriously.' },
        { type: 'p', text: 'This page explains, in plain words and with links to the law, where you may drive a golf cart, who may drive it, how an LSV is different, and which coverage gaps to close.' },
      ],
      factsTitle: 'Golf carts and LSVs: the numbers in Florida law',
      facts: [
        { value: '20 mph', text: 'A golf cart, under Florida law, is a vehicle built for golf courses that cannot go faster than 20 mph.', source: u('s320_01') },
        { value: '18', text: 'Under 18, a golf cart driver on public roads must have a learner’s or driver license; 18 and over, a government photo ID.', source: u('s316_212') },
        { value: '25 mph', text: 'A low-speed vehicle has a top speed over 20 mph and up to 25 mph, and it must be registered and insured.', source: u('s320_01') },
        { value: '35 mph', text: 'LSVs may only be driven on streets with a posted speed limit of 35 mph or less (they may cross faster roads at intersections).', source: u('s316_2122') },
      ],
      figureAlt: 'Infographic comparing a golf cart and a low-speed vehicle in Florida. Golf cart: top speed 20 mph, only on roads designated by the city or county, sunrise to sunset unless allowed, not titled or registered. LSV: top speed 25 mph, roads posted 35 mph or less, needs a VIN, title, registration, PIP and property damage liability, and a driver license. Liability and medical payments coverage can help, depending on the policy.',
      figureCaption: 'Rules from ss. 316.212, 316.2122 and 320.01, Florida Statutes, and FLHSMV. Local ordinances can be stricter.',
      gapsTitle: 'Where golf cart owners get caught short',
      gaps: [
        { h: 'A passenger falls out', p: 'Many golf carts have no doors or seat belts. A sharp turn with a child or grandparent on the back bench can mean a hospital visit. Medical payments and liability are what usually respond.' },
        { h: 'Home policy limits', p: 'Some homeowners policies give limited golf cart coverage, often only in certain places, such as on a golf course or inside your community. Check before you drive to the store.' },
        { h: 'The cart was converted into an LSV', p: 'An LSV is a registered motor vehicle with its own insurance requirements. A converted cart that is still insured like a golf cart can leave a gap.' },
      ],
      coverageTitle: 'Coverage to ask about for a golf cart or LSV',
      coverage: [
        { h: 'Liability', p: 'Injuries and damage you or a permitted driver cause to others, up to your limits, plus legal defense.' },
        { h: 'Medical payments', p: 'Helps with medical bills for you and your passengers, regardless of fault.' },
        { h: 'Collision and comprehensive', p: 'Damage to the cart from a crash, theft, fire, flood or a falling tree.' },
        { h: 'Uninsured motorist', p: 'Helps if a driver with no insurance injures you or your passengers, where the policy offers it.' },
        { h: 'Accessories and custom parts', p: 'Lift kits, custom seats, enclosures, lights and sound systems, if listed or included.' },
        { h: 'PIP and property damage for LSVs', p: 'A registered LSV needs the Florida motor vehicle minimums, PIP and property damage liability.' },
      ],
      coverageNote: 'These are general descriptions. Availability, limits and exclusions depend on the policy.',
      body: [
        { type: 'h2', text: 'Where you may drive a golf cart in Florida' },
        { type: 'p', text: 'Driving a golf cart on public roads is **prohibited except as the law allows** ([s. 316.212](https://www.flsenate.gov/Laws/Statutes/2026/316.212)). Mainly, that means a county road or city street that the county or city has **designated for golf carts and posted with signs**. Golf carts may cross a state highway only at crossings the state has approved.' },
        { type: 'ul', items: [
          'Only **from sunrise to sunset**, unless the local government allows night driving and the cart has **headlights, brake lights, turn signals and a windshield**.',
          'Every golf cart needs **efficient brakes, reliable steering, safe tires, a rearview mirror and red reflectors** front and rear.',
          'A driver **under 18** must have a **learner’s or driver license**; a driver **18 or older** must carry a **government photo ID**.',
          'Cities and counties can pass **stricter rules** and can allow carts on certain sidewalks.',
          'Retirement communities have their own section of the law ([s. 316.2125](https://www.flsenate.gov/Laws/Statutes/2026/316.2125)).',
        ] },
        { type: 'h2', text: 'Golf cart or low-speed vehicle?' },
        { type: 'p', text: 'A **golf cart** cannot go faster than 20 mph; a **low-speed vehicle** goes over 20 and up to 25 mph ([s. 320.01](https://www.flsenate.gov/Laws/Statutes/2026/320.01)). An LSV may use streets posted at **35 mph or less**, must have headlamps, stop lamps, turn signals, tail lamps, reflectors, a parking brake, mirrors, a windshield, **seat belts** and a **VIN**, must be **registered and insured**, and the driver needs a **valid driver license** ([s. 316.2122](https://www.flsenate.gov/Laws/Statutes/2026/316.2122)).' },
        { type: 'p', text: 'Golf carts are **not titled or registered** in Florida ([FLHSMV TL-63](https://www.flhsmv.gov/pdf/proc/tl/tl-63.pdf)). To turn one into an LSV, the owner needs an inspection, a Florida-assigned VIN, a title and registration, and proof of **PIP and property damage liability** ([FLHSMV](https://www.flhsmv.gov/safety-center/consumer-education/low-speed-vehicles/)).' },
        { type: 'callout', title: 'Kids and golf carts', text: 'A young teen without a learner’s license may not drive a golf cart on public roads in Florida. If teens drive yours inside the community, ask your agent how the policy treats them.' },
      ],
      checklistTitle: 'A quick check for your golf cart or LSV',
      checklist: [
        'Is your cart a **golf cart** or a registered **LSV**? The coverage you need is different.',
        'Does your policy cover the cart **on public roads**, not only on your property or the golf course?',
        'Are **family members and guests** who drive it covered?',
        'Do you have **medical payments** for passengers?',
        'Are **lift kits, enclosures and other upgrades** listed?',
        'Where is it parked during a **hurricane**?',
      ],
      agentTitle: 'A personal agent when it counts: at claim time',
      agent: [
        { type: 'p', text: 'M&K Agency is a family-owned agency in Florida City with more than 5,000 clients across Florida and a team of 12 who speak English, Spanish and Russian.' },
        { type: 'p', text: 'If someone is hurt or the cart is stolen or damaged, call or message us. We help you report the claim, explain what the policy pays and stay with you until it is settled. **Send us your policy and we’ll check your coverage.**' },
      ],
      faqTitle: 'Golf cart insurance in Florida: common questions',
      faq: [
        { q: 'Can I drive a golf cart on the street in Florida?', a: 'Only where the law allows: mainly county roads and city streets that the local government has designated for golf carts and posted with signs, from sunrise to sunset unless night driving is authorized. Check your city and county rules too.' },
        { q: 'How old do you have to be to drive a golf cart in Florida?', a: 'On public roads, a driver under 18 must have a valid learner’s or driver license, and a driver 18 or older must have a valid government-issued photo ID (s. 316.212, Florida Statutes).' },
        { q: 'Does a golf cart need insurance in Florida?', a: 'Golf carts are not titled or registered in Florida, so there is no registration insurance requirement. But an injury claim does not care: liability and medical payments coverage protect you and your passengers. An LSV is different and must be insured.' },
        { q: 'What is the difference between a golf cart and an LSV?', a: 'A golf cart cannot exceed 20 mph. A low-speed vehicle goes over 20 and up to 25 mph, has safety equipment like seat belts and a VIN, is titled and registered, needs PIP and property damage liability, and can use streets posted at 35 mph or less.' },
        { q: 'Does my homeowners policy cover my golf cart?', a: 'Sometimes, but often only in a limited way or in certain places. Send us your home policy and we will tell you what it says about golf carts.' },
        { q: 'Do you help with golf cart claims?', a: 'Yes. Call us or message us on WhatsApp. A licensed agent helps you report the claim and explains each step in English, Spanish or Russian.' },
      ],
      related: [
        { path: '/atv-utv-insurance-florida', label: 'ATV, UTV and dirt bike insurance in Florida' },
        { path: '/umbrella-insurance-florida-city', label: 'Umbrella insurance: extra liability protection' },
      ],
      sources: srcList('en', [...KEYS]),
    },
    es: {
      metaTitle: 'Seguro de Carrito de Golf y LSV en Florida | M&K Agency',
      metaDesc: 'Reglas de Florida para carritos de golf en la vía pública, quién puede manejarlos y en qué se diferencia un LSV. Y los huecos de cobertura que conviene revisar.',
      breadcrumb: 'Seguro de carrito de golf y LSV',
      kicker: 'Seguro de carrito de golf y vehículo de baja velocidad · Toda la Florida',
      h1a: 'Seguro de carrito de golf en Florida:',
      h1b: 'para el barrio, la comunidad y los nietos en el asiento de atrás.',
      answer: 'En Florida, un carrito de golf solo puede usar **las vías que la ciudad o el condado hayan designado**, y quien maneja **siendo menor de 18 años necesita permiso de aprendiz o licencia**. Un **vehículo de baja velocidad (LSV)** sigue otras reglas. En los dos casos, un pasajero o peatón lesionado puede terminar en un reclamo serio. Revisamos su cobertura y se la explicamos en español.',
      serviceType: 'Seguro de carritos de golf y vehículos de baja velocidad',
      leadLabel: 'Carrito de golf / LSV',
      intro: [
        { type: 'p', text: 'En Florida hay carritos de golf por todas partes: comunidades de jubilados, pueblos de playa, urbanizaciones cerradas, parques de RV y fincas del sur de Miami-Dade. Muchas familias los ven como un juguete. La ley de Florida y un reclamo por lesiones los ven con más seriedad.' },
        { type: 'p', text: 'Aquí le explicamos, con palabras claras y enlaces a la ley, por dónde puede ir un carrito de golf, quién puede manejarlo, en qué se diferencia un LSV y qué huecos de cobertura conviene cerrar.' },
      ],
      factsTitle: 'Carritos de golf y LSV: las cifras de la ley de Florida',
      facts: [
        { value: '20 mph', text: 'Según la ley de Florida, un carrito de golf es un vehículo hecho para campos de golf que no puede pasar de 20 mph.', source: u('s320_01') },
        { value: '18', text: 'Si es menor de 18 años, quien maneje un carrito de golf en la vía pública necesita permiso de aprendiz o licencia; desde los 18, una identificación oficial con foto.', source: u('s316_212') },
        { value: '25 mph', text: 'Un vehículo de baja velocidad tiene velocidad máxima de más de 20 y hasta 25 mph, y debe estar registrado y asegurado.', source: u('s320_01') },
        { value: '35 mph', text: 'Los LSV solo pueden circular por calles con límite señalizado de 35 mph o menos (pueden cruzar vías más rápidas en las intersecciones).', source: u('s316_2122') },
      ],
      figureAlt: 'Infografía que compara un carrito de golf y un vehículo de baja velocidad en Florida. Carrito de golf: hasta 20 mph, solo por vías designadas por la ciudad o el condado, de la salida a la puesta del sol salvo autorización, sin título ni registro. LSV: hasta 25 mph, calles con límite de 35 mph o menos, necesita VIN, título, registro, PIP y responsabilidad por daños a la propiedad, y licencia de conducir. La responsabilidad civil y los pagos médicos pueden ayudar, según la póliza.',
      figureCaption: 'Reglas de las ss. 316.212, 316.2122 y 320.01 de los Estatutos de Florida y del FLHSMV. Las ordenanzas locales pueden ser más estrictas.',
      gapsTitle: 'Dónde se quedan cortos los dueños de carritos de golf',
      gaps: [
        { h: 'Un pasajero se cae', p: 'Muchos carritos no tienen puertas ni cinturones. Una curva cerrada con un niño o un abuelo en el banco de atrás puede terminar en el hospital. Normalmente responden los pagos médicos y la responsabilidad civil.' },
        { h: 'Los límites del seguro de casa', p: 'Algunas pólizas de casa dan una cobertura limitada para carritos de golf, muchas veces solo en ciertos lugares, como el campo de golf o dentro de su comunidad. Revíselo antes de ir a la tienda en el carrito.' },
        { h: 'El carrito se convirtió en LSV', p: 'Un LSV es un vehículo motorizado registrado, con sus propios requisitos de seguro. Si un carrito convertido sigue asegurado como carrito de golf, puede quedar un hueco.' },
      ],
      coverageTitle: 'Coberturas que conviene preguntar para un carrito de golf o LSV',
      coverage: [
        { h: 'Responsabilidad civil', p: 'Lesiones y daños que usted o alguien con su permiso cause a otros, hasta sus límites, y la defensa legal.' },
        { h: 'Pagos médicos', p: 'Ayuda con los gastos médicos suyos y de sus pasajeros, sin importar la culpa.' },
        { h: 'Choque y cobertura amplia', p: 'Daños al carrito por choque, robo, incendio, inundación o un árbol que cae.' },
        { h: 'Conductor sin seguro', p: 'Ayuda si un conductor sin seguro lo lesiona a usted o a sus pasajeros, cuando la póliza la ofrece.' },
        { h: 'Accesorios y piezas personalizadas', p: 'Kits de elevación, asientos especiales, cerramientos, luces y equipos de sonido, si se declaran o están incluidos.' },
        { h: 'PIP y daños a la propiedad para LSV', p: 'Un LSV registrado necesita los mínimos de Florida para vehículos: PIP y responsabilidad por daños a la propiedad.' },
      ],
      coverageNote: 'Son descripciones generales. La disponibilidad, los límites y las exclusiones dependen de la póliza.',
      body: [
        { type: 'h2', text: 'Por dónde puede manejar un carrito de golf en Florida' },
        { type: 'p', text: 'Manejar un carrito de golf por la vía pública está **prohibido salvo en los casos que la ley permite** ([s. 316.212](https://www.flsenate.gov/Laws/Statutes/2026/316.212)). Sobre todo, eso significa una vía del condado o una calle de la ciudad que el condado o la ciudad hayan **designado para carritos de golf y señalizado**. Solo pueden cruzar una carretera estatal por cruces aprobados por el estado.' },
        { type: 'ul', items: [
          'Solo **de la salida a la puesta del sol**, salvo que el gobierno local permita manejar de noche y el carrito tenga **faros, luces de freno, direccionales y parabrisas**.',
          'Todo carrito de golf necesita **frenos eficientes, dirección confiable, llantas seguras, espejo retrovisor y reflectores rojos** adelante y atrás.',
          'Quien maneje **siendo menor de 18 años** debe tener **permiso de aprendiz o licencia de conducir**; desde los **18 años**, una **identificación oficial con foto**.',
          'Las ciudades y los condados pueden aprobar **reglas más estrictas** y permitir carritos en ciertas aceras.',
          'Las comunidades de jubilados tienen su propia sección en la ley ([s. 316.2125](https://www.flsenate.gov/Laws/Statutes/2026/316.2125)).',
        ] },
        { type: 'h2', text: '¿Carrito de golf o vehículo de baja velocidad?' },
        { type: 'p', text: 'Un **carrito de golf** no puede pasar de 20 mph; un **vehículo de baja velocidad** va a más de 20 y hasta 25 mph ([s. 320.01](https://www.flsenate.gov/Laws/Statutes/2026/320.01)). Un LSV puede circular por calles con límite de **35 mph o menos**; debe tener faros, luces de freno, direccionales, luces traseras, reflectores, freno de estacionamiento, espejos, parabrisas, **cinturones de seguridad** y **VIN**; debe estar **registrado y asegurado**, y quien lo maneja necesita **licencia de conducir vigente** ([s. 316.2122](https://www.flsenate.gov/Laws/Statutes/2026/316.2122)).' },
        { type: 'p', text: 'En Florida, los carritos de golf **no se titulan ni se registran** ([FLHSMV TL-63](https://www.flhsmv.gov/pdf/proc/tl/tl-63.pdf)). Para convertir uno en LSV, el dueño necesita una inspección, un VIN asignado por Florida, título y registro, y prueba de **PIP y responsabilidad por daños a la propiedad** ([FLHSMV](https://www.flhsmv.gov/safety-center/consumer-education/low-speed-vehicles/)).' },
        { type: 'callout', title: 'Los niños y el carrito', text: 'Un adolescente sin permiso de aprendiz no puede manejar un carrito de golf por la vía pública en Florida. Si los adolescentes de la casa lo manejan dentro de la comunidad, pregúntele a su agente cómo los trata la póliza.' },
      ],
      checklistTitle: 'Revise su carrito de golf o LSV',
      checklist: [
        '¿Su vehículo es un **carrito de golf** o un **LSV** registrado? La cobertura que necesita es distinta.',
        '¿La póliza lo cubre **en la vía pública**, y no solo en su propiedad o en el campo de golf?',
        '¿Están cubiertos los **familiares e invitados** que lo manejan?',
        '¿Tiene **pagos médicos** para los pasajeros?',
        '¿Están declarados los **kits de elevación, cerramientos y otras mejoras**?',
        '¿Dónde lo guarda durante un **huracán**?',
      ],
      agentTitle: 'Un agente personal cuando más importa: en el reclamo',
      agent: [
        { type: 'p', text: 'M&K Agency es una agencia familiar de Florida City con más de 5,000 clientes en toda la Florida y un equipo de 12 personas que hablan español, inglés y ruso.' },
        { type: 'p', text: 'Si alguien se lesiona o el carrito se lo roban o se daña, llámenos o escríbanos. Le ayudamos a reportar el reclamo, le explicamos qué paga la póliza y lo acompañamos hasta el final. **Envíenos su póliza y revisamos su cobertura.**' },
      ],
      faqTitle: 'Seguro de carrito de golf en Florida: preguntas frecuentes',
      faq: [
        { q: '¿Puedo manejar un carrito de golf por la calle en Florida?', a: 'Solo donde la ley lo permite: principalmente vías del condado y calles de la ciudad que el gobierno local haya designado para carritos de golf y señalizado, de la salida a la puesta del sol, salvo que se autorice de noche. Revise también las reglas de su ciudad y su condado.' },
        { q: '¿Qué edad hay que tener para manejar un carrito de golf en Florida?', a: 'En la vía pública, quien tenga menos de 18 años necesita permiso de aprendiz o licencia de conducir vigente, y desde los 18 años, una identificación oficial con foto vigente (s. 316.212 de los Estatutos de Florida).' },
        { q: '¿Un carrito de golf necesita seguro en Florida?', a: 'Los carritos de golf no se titulan ni se registran en Florida, así que no hay un requisito de seguro para el registro. Pero un reclamo por lesiones no hace esa distinción: la responsabilidad civil y los pagos médicos lo protegen a usted y a sus pasajeros. Un LSV es distinto y debe estar asegurado.' },
        { q: '¿Qué diferencia hay entre un carrito de golf y un LSV?', a: 'Un carrito de golf no pasa de 20 mph. Un vehículo de baja velocidad va a más de 20 y hasta 25 mph, tiene equipo de seguridad como cinturones y VIN, se titula y se registra, necesita PIP y responsabilidad por daños a la propiedad, y puede ir por calles con límite de 35 mph o menos.' },
        { q: '¿Mi seguro de casa cubre mi carrito de golf?', a: 'A veces, pero muchas veces de forma limitada o solo en ciertos lugares. Envíenos su póliza de casa y le decimos qué dice sobre los carritos de golf.' },
        { q: '¿Me ayudan con un reclamo de carrito de golf?', a: 'Sí. Llámenos o escríbanos por WhatsApp. Un agente licenciado le ayuda a reportar el reclamo y le explica cada paso en español, inglés o ruso.' },
      ],
      related: [
        { path: '/atv-utv-insurance-florida', label: 'Seguro de ATV, UTV y motos de tierra en Florida' },
        { path: '/umbrella-insurance-florida-city', label: 'Seguro umbrella: más protección de responsabilidad civil' },
      ],
      sources: srcList('es', [...KEYS]),
    },
    ru: {
      metaTitle: 'Страховка гольф-кара и LSV во Флориде | M&K Agency',
      metaDesc: 'Правила Флориды для гольф-каров на дорогах общего пользования, кто может водить и чем отличается LSV. И дыры в покрытии, которые стоит проверить с агентом.',
      breadcrumb: 'Страховка гольф-кара и LSV',
      kicker: 'Страхование гольф-каров и тихоходных автомобилей · Вся Флорида',
      h1a: 'Страховка гольф-кара во Флориде:',
      h1b: 'для района, комьюнити и внуков на заднем сиденье.',
      answer: 'Во Флориде гольф-кар может ездить только по **дорогам, которые назначил город или округ**, а водителю **младше 18 лет нужны ученические или обычные права**. У **тихоходного автомобиля (LSV)** другие правила. В обоих случаях травмированный пассажир или пешеход — это серьёзный иск. Проверим ваше покрытие и объясним по-русски.',
      serviceType: 'Страхование гольф-каров и тихоходных автомобилей',
      leadLabel: 'Гольф-кар / LSV',
      intro: [
        { type: 'p', text: 'Гольф-кары во Флориде повсюду: пенсионные комьюнити, пляжные городки, закрытые посёлки, парки для автодомов и фермы на юге Майами-Дейд. Многие семьи относятся к ним как к игрушке. Закон Флориды и иск за травму — гораздо серьёзнее.' },
        { type: 'p', text: 'На этой странице простыми словами и со ссылками на закон: где можно ездить на гольф-каре, кто может им управлять, чем отличается LSV и какие дыры в покрытии стоит закрыть.' },
      ],
      factsTitle: 'Гольф-кары и LSV: цифры из закона Флориды',
      facts: [
        { value: '20 миль/ч', text: 'По закону Флориды гольф-кар — машина для поля для гольфа, которая не может ехать быстрее 20 миль в час.', source: u('s320_01') },
        { value: '18', text: 'Водителю гольф-кара младше 18 лет на дорогах общего пользования нужны ученические или обычные права; с 18 лет — государственное удостоверение с фото.', source: u('s316_212') },
        { value: '25 миль/ч', text: 'Тихоходный автомобиль (LSV) едет быстрее 20 и до 25 миль в час; его обязательно регистрируют и страхуют.', source: u('s320_01') },
        { value: '35 миль/ч', text: 'LSV можно ездить только по улицам с ограничением скорости 35 миль в час или ниже (более быстрые дороги можно пересекать на перекрёстках).', source: u('s316_2122') },
      ],
      figureAlt: 'Инфографика: гольф-кар и тихоходный автомобиль во Флориде. Гольф-кар: до 20 миль в час, только по дорогам, назначенным городом или округом, от восхода до заката, если не разрешено иное, без титула и регистрации. LSV: до 25 миль в час, улицы с ограничением 35 миль в час или ниже, нужны VIN, титул, регистрация, PIP и ответственность за ущерб имуществу, водительские права. Помочь могут ответственность и медицинские расходы — в зависимости от полиса.',
      figureCaption: 'Правила — ст. 316.212, 316.2122 и 320.01 Законов Флориды и FLHSMV. Местные постановления могут быть строже.',
      gapsTitle: 'Где владельцы гольф-каров остаются без защиты',
      gaps: [
        { h: 'Пассажир выпал', p: 'У многих гольф-каров нет ни дверей, ни ремней. Резкий поворот с ребёнком или бабушкой на заднем сиденье — и вы в больнице. Обычно тут работают медицинские расходы и ответственность.' },
        { h: 'Ограничения страховки дома', p: 'Некоторые полисы на дом дают ограниченное покрытие гольф-кара, часто только в определённых местах — на поле для гольфа или внутри вашего комьюнити. Проверьте до того, как поехать на нём в магазин.' },
        { h: 'Гольф-кар переделали в LSV', p: 'LSV — это зарегистрированное транспортное средство со своими требованиями к страховке. Если переделанный кар застрахован как гольф-кар, может остаться дыра.' },
      ],
      coverageTitle: 'О каких покрытиях спросить для гольф-кара или LSV',
      coverage: [
        { h: 'Ответственность (liability)', p: 'Травмы и ущерб, причинённые другим вами или тем, кого вы пустили за руль, в пределах лимитов, плюс юридическая защита.' },
        { h: 'Медицинские расходы', p: 'Помогает с лечением вас и ваших пассажиров, независимо от вины.' },
        { h: 'Collision и comprehensive', p: 'Ущерб кару при аварии, угоне, пожаре, наводнении или от упавшего дерева.' },
        { h: 'Водитель без страховки (UM)', p: 'Помогает, если водитель без страховки травмировал вас или ваших пассажиров, — там, где полис это предлагает.' },
        { h: 'Аксессуары и тюнинг', p: 'Лифт-киты, особые сиденья, тенты и шторки, фары и аудиосистемы — если указаны или включены.' },
        { h: 'PIP и ущерб имуществу для LSV', p: 'Для зарегистрированного LSV нужны минимумы Флориды для автомобилей: PIP и ответственность за ущерб имуществу.' },
      ],
      coverageNote: 'Это общие описания. Наличие покрытий, лимиты и исключения зависят от конкретного полиса.',
      body: [
        { type: 'h2', text: 'Где можно ездить на гольф-каре во Флориде' },
        { type: 'p', text: 'Ездить на гольф-каре по дорогам общего пользования **запрещено, кроме случаев, прямо разрешённых законом** ([ст. 316.212](https://www.flsenate.gov/Laws/Statutes/2026/316.212)). В основном это дорога округа или городская улица, которую округ или город **назначил для гольф-каров и обозначил знаками**. Пересекать дорогу штата можно только на переездах, одобренных штатом.' },
        { type: 'ul', items: [
          'Только **от восхода до заката**, если только местная власть не разрешила ночную езду и у кара есть **фары, стоп-сигналы, поворотники и лобовое стекло**.',
          'У каждого гольф-кара должны быть **исправные тормоза, надёжное рулевое управление, безопасные шины, зеркало заднего вида и красные отражатели** спереди и сзади.',
          'Водителю **младше 18 лет** нужны **ученические или обычные права**; с **18 лет** — **государственное удостоверение с фото**.',
          'Города и округа могут вводить **более строгие правила** и разрешать гольф-кары на некоторых тротуарах.',
          'Для пенсионных комьюнити в законе есть отдельная статья ([ст. 316.2125](https://www.flsenate.gov/Laws/Statutes/2026/316.2125)).',
        ] },
        { type: 'h2', text: 'Гольф-кар или тихоходный автомобиль?' },
        { type: 'p', text: '**Гольф-кар** не может ехать быстрее 20 миль в час; **тихоходный автомобиль (LSV)** — быстрее 20 и до 25 миль в час ([ст. 320.01](https://www.flsenate.gov/Laws/Statutes/2026/320.01)). LSV можно ездить по улицам с ограничением **35 миль в час или ниже**; у него должны быть фары, стоп-сигналы, поворотники, задние фонари, отражатели, стояночный тормоз, зеркала, лобовое стекло, **ремни безопасности** и **VIN**; его нужно **зарегистрировать и застраховать**, а водителю нужны **действующие права** ([ст. 316.2122](https://www.flsenate.gov/Laws/Statutes/2026/316.2122)).' },
        { type: 'p', text: 'Гольф-кары во Флориде **не получают титул и не регистрируются** ([FLHSMV TL-63](https://www.flhsmv.gov/pdf/proc/tl/tl-63.pdf)). Чтобы переделать кар в LSV, владельцу нужны осмотр, VIN, присвоенный Флоридой, титул и регистрация, а также подтверждение **PIP и ответственности за ущерб имуществу** ([FLHSMV](https://www.flhsmv.gov/safety-center/consumer-education/low-speed-vehicles/)).' },
        { type: 'callout', title: 'Дети и гольф-кар', text: 'Подростку без ученических прав нельзя водить гольф-кар по дорогам общего пользования во Флориде. Если подростки ездят на вашем каре внутри комьюнити, спросите агента, как к этому относится полис.' },
      ],
      checklistTitle: 'Короткая проверка для гольф-кара или LSV',
      checklist: [
        'У вас **гольф-кар** или зарегистрированный **LSV**? Нужное покрытие разное.',
        'Покрывает ли полис кар **на дорогах общего пользования**, а не только на участке или поле для гольфа?',
        'Покрыты ли **родственники и гости**, которые на нём ездят?',
        'Есть ли покрытие **медицинских расходов** для пассажиров?',
        'Указаны ли **лифт-киты, тенты и другие доработки**?',
        'Где кар стоит во время **урагана**?',
      ],
      agentTitle: 'Личный агент, когда это важнее всего: при страховом случае',
      agent: [
        { type: 'p', text: 'M&K Agency — семейное агентство во Флорида-Сити: больше 5 000 клиентов по всей Флориде и команда из 12 человек, которые говорят по-русски, по-английски и по-испански.' },
        { type: 'p', text: 'Если кто-то пострадал, кар угнали или повредили, позвоните или напишите нам. Поможем заявить убыток, объясним, что платит полис, и будем рядом до конца урегулирования. **Пришлите полис — мы проверим ваше покрытие.**' },
      ],
      faqTitle: 'Страховка гольф-кара во Флориде: частые вопросы',
      faq: [
        { q: 'Можно ли ездить на гольф-каре по улице во Флориде?', a: 'Только там, где это разрешает закон: в основном по дорогам округа и городским улицам, которые местная власть назначила для гольф-каров и обозначила знаками, от восхода до заката, если ночная езда не разрешена. Проверьте и правила вашего города и округа.' },
        { q: 'С какого возраста можно водить гольф-кар во Флориде?', a: 'На дорогах общего пользования водителю младше 18 лет нужны действующие ученические или обычные права, а с 18 лет — действующее государственное удостоверение с фото (ст. 316.212 Законов Флориды).' },
        { q: 'Нужна ли страховка на гольф-кар во Флориде?', a: 'Гольф-кары во Флориде не получают титул и не регистрируются, поэтому требования к страховке при регистрации нет. Но иску за травму это неважно: ответственность и медицинские расходы защищают вас и ваших пассажиров. LSV — другое дело, его страховать обязательно.' },
        { q: 'Чем гольф-кар отличается от LSV?', a: 'Гольф-кар не едет быстрее 20 миль в час. Тихоходный автомобиль едет быстрее 20 и до 25 миль в час, имеет ремни, VIN и другое оборудование, получает титул и регистрацию, требует PIP и ответственности за ущерб имуществу и может ездить по улицам с ограничением 35 миль в час или ниже.' },
        { q: 'Покрывает ли гольф-кар моя страховка дома?', a: 'Иногда, но часто ограниченно или только в определённых местах. Пришлите нам полис на дом — скажем, что там написано о гольф-карах.' },
        { q: 'Помогаете ли вы со страховыми случаями по гольф-кару?', a: 'Да. Позвоните или напишите в WhatsApp. Лицензированный агент поможет заявить убыток и объяснит каждый шаг по-русски, по-английски или по-испански.' },
      ],
      related: [
        { path: '/atv-utv-insurance-florida', label: 'Страховка квадроцикла, UTV и эндуро во Флориде' },
        { path: '/umbrella-insurance-florida-city', label: 'Umbrella: дополнительная защита ответственности' },
      ],
      sources: srcList('ru', [...KEYS]),
    },
  },
};
