import type { RecPage } from './types';
import { srcList, u } from './sources';

// Facts: FWC 2025 BASR summary (PWC 17% of registrations, 23%/161 of accidents,
// 45% collisions with another vessel, Miami-Dade 20 + Monroe 20, 12 deaths, 131 injured);
// s. 327.39 (PFD, lanyard, no night riding, under-14 ban, owner duty, rental instruction);
// s. 327.54 (liveries: no rentals under 18, pre-ride instruction, $500k/$1M insurance, renter coverage offer);
// s. 327.395 (boater ID for people born on/after Jan 1, 1988, 10 hp+); s. 327.301 (reports, $2,000).
const KEYS = ['fwc2025', 's327_39', 's327_54', 's327_395', 'fwcId', 's327_301', 's327_35', 'uscg2024'] as const;

export const JET_SKI: RecPage = {
  line: 'jet-ski',
  path: '/jet-ski-insurance-florida',
  leadValue: 'Jet Ski / PWC',
  leadSource: 'rec-jet-ski',
  articleSlug: 'jet-ski-rental-guest-drivers-florida',
  productSlug: 'jet-ski-insurance',
  published: '2026-10-03',
  modified: '2026-10-03',
  copy: {
    en: {
      metaTitle: 'Jet Ski Insurance in Florida (PWC) | M&K Agency',
      metaDesc: 'Jet skis are 17% of Florida’s registered vessels but 23% of boating accidents. Florida PWC rules, guest riders and the coverage gaps to check.',
      breadcrumb: 'Jet ski insurance in Florida',
      kicker: 'Jet ski / PWC insurance · All of Florida',
      h1a: 'Jet ski insurance in Florida:',
      h1b: 'cover the rider, the guests and the people around you.',
      answer: 'A jet ski is small, fast and often driven by friends and family. In Florida, personal watercraft are involved in far more than their share of accidents, so **liability and guest-rider coverage** matter as much as the machine. We check your policy and explain it in your language.',
      serviceType: 'Personal watercraft (jet ski) insurance',
      leadLabel: 'Jet ski / PWC',
      intro: [
        { type: 'p', text: 'Most jet ski owners think first about the machine: a scrape on the hull, a damaged pump, a stolen trailer. Those matter. But the bigger risk on a crowded sandbar or channel is **what happens to other people**: a collision with another boat, a swimmer, a dock, or a guest who loses control on your PWC.' },
        { type: 'p', text: 'Florida has specific rules for personal watercraft, from life jackets to age limits to rentals. Below are the rules that affect your coverage, the gaps we see most often and the questions to ask before the next ride.' },
      ],
      factsTitle: 'Personal watercraft in Florida: what the numbers say',
      facts: [
        { value: '23%', text: 'of Florida’s 694 reportable boating accidents in 2025 involved a PWC, while PWC were only 17% of registered vessels.', source: u('fwc2025') },
        { value: '45%', text: 'of PWC accidents in 2025 were collisions with another vessel.', source: u('fwc2025') },
        { value: '40', text: 'PWC accidents in Miami-Dade (20) and Monroe (20) counties in 2025, more than any other area of the state.', source: u('fwc2025') },
        { value: '14', text: 'is the minimum age to operate a personal watercraft in Florida. Owners may not let anyone younger drive.', source: u('s327_39') },
      ],
      figureAlt: 'Infographic. Florida jet ski rules and risks: everyone aboard wears a non-inflatable Coast Guard-approved life jacket, the kill-switch lanyard is attached, no riding from half an hour after sunset to half an hour before sunrise, operators must be at least 14. In 2025, PWC were 17% of registered vessels but 23% of accidents.',
      figureCaption: 'Rules from s. 327.39, Florida Statutes; numbers from the FWC 2025 Boating Accident Statistical Report.',
      gapsTitle: 'Where jet ski owners get caught short',
      gaps: [
        { h: 'A guest is driving', p: 'Friends and family take turns. If a guest injures someone or damages another boat, the claim can come back to you as the owner. Check who your policy covers as an operator.' },
        { h: 'Injuries to your passengers', p: 'Falls and collisions on a PWC can injure the people riding with you. Medical payments and liability coverage are what usually respond, depending on the policy.' },
        { h: 'Off the water', p: 'Trailers, storage, theft from a driveway and storm damage are separate questions. A trailer is not always covered the same way as the craft.' },
      ],
      coverageTitle: 'Coverage to ask about on a Florida PWC policy',
      coverage: [
        { h: 'Liability', p: 'Pays for injuries and damage you or a permitted operator cause to others, up to your limits, plus legal defense.' },
        { h: 'Medical payments', p: 'Helps with medical bills for you and your passengers after an accident, regardless of fault.' },
        { h: 'Uninsured boater', p: 'Helps when another boater who injures you has no insurance or not enough.' },
        { h: 'Physical damage', p: 'Damage to the hull, engine and pump from a collision, theft, fire or storm.' },
        { h: 'Trailer and accessories', p: 'Your trailer, covers, tow ropes and other gear, if listed or included.' },
        { h: 'Towing and on-water assistance', p: 'Help getting back to the ramp if the engine dies far from shore.' },
      ],
      coverageNote: 'These are general descriptions. Availability, limits and exclusions depend on the policy.',
      body: [
        { type: 'h2', text: 'Florida’s personal watercraft rules in plain words' },
        { type: 'ul', items: [
          'Everyone riding, and anyone being towed, must wear a **Coast Guard-approved life jacket that is not inflatable** ([s. 327.39](https://www.flsenate.gov/Laws/Statutes/2026/327.39)).',
          'If the PWC has a **lanyard engine cutoff switch**, the operator must attach it to his or her body, clothing or life jacket.',
          'No riding from **half an hour after sunset to half an hour before sunrise**.',
          'Weaving through traffic, jumping another boat’s wake too close or swerving at the last moment can count as **reckless operation**.',
          'Nobody under **14** may operate a PWC, and an owner may not knowingly let them.',
          'Anyone born on or after **January 1, 1988**, needs a **Boating Safety Education ID card** (or another accepted document) with photo ID to operate a vessel with a motor of 10 horsepower or more ([s. 327.395](https://www.flsenate.gov/Laws/Statutes/2026/327.395); [FWC](https://myfwc.com/boating/safety-education/id/)).',
        ] },
        { type: 'h2', text: 'Renting a jet ski, or renting yours out' },
        { type: 'p', text: 'Florida rental businesses (the law calls them liveries) may not rent a PWC to anyone **under 18**, must give **pre-ride instruction** and must carry their own liability insurance of at least $500,000 per person and $1 million per event. They must either insure the renter in the same amounts or **offer the renter coverage**; a renter who says no signs a statement that he or she may not have other insurance for the damage ([s. 327.54](https://www.flsenate.gov/Laws/Statutes/2026/327.54)).' },
        { type: 'p', text: 'If you rent out your own PWC for money, you may be acting as a livery, with permit and insurance rules of your own. A personal policy is usually not written for that. Ask us before you list it.' },
        { type: 'h2', text: 'After an accident' },
        { type: 'p', text: 'The operator must file a written report with FWC when an accident causes an injury that needs more than first aid, a death or disappearance, or at least **$2,000** in property damage ([s. 327.301](https://www.flsenate.gov/Laws/Statutes/2026/327.301)). Take photos, get names and boat registration numbers, and call your agent the same day.' },
        { type: 'callout', title: 'Alcohol and the water', text: 'Florida’s boating-under-the-influence law uses the same 0.08 limit as on the road ([s. 327.35](https://www.flsenate.gov/Laws/Statutes/2026/327.35)). Nationally, alcohol is the leading known contributing factor in fatal boating incidents ([USCG](https://uscgboating.org/library/accident-statistics/Recreational-Boating-Statistics-2024.pdf)).' },
      ],
      checklistTitle: 'Before the next ride: a quick PWC coverage check',
      checklist: [
        'Does your policy cover **other people you allow to drive**? Are there age or experience limits?',
        'Do you have **liability limits** that match what you own and earn?',
        'Is there **medical payments** coverage for your passengers?',
        'Is your **trailer** listed, and is storage at home or at a marina covered?',
        'Do you plan to **rent it out**? Tell your agent first.',
        'Keep the **boater ID** cards of everyone who drives, plus non-inflatable life jackets for every seat.',
      ],
      agentTitle: 'A personal agent when it counts: at claim time',
      agent: [
        { type: 'p', text: 'M&K Agency is a family-owned agency in Florida City, a short drive from Biscayne Bay and the Keys, with more than 5,000 clients across Florida and a team of 12 who speak English, Spanish and Russian.' },
        { type: 'p', text: 'If something goes wrong on the water, call or message us. We help you report the claim, explain what your policy pays and stay with you until it is settled. **Send us your policy and we’ll check your coverage.**' },
      ],
      faqTitle: 'Jet ski insurance in Florida: common questions',
      faq: [
        { q: 'Is jet ski insurance required in Florida?', a: 'Florida’s boating laws spell out insurance rules for rental businesses, which must carry liability insurance and offer coverage to renters (s. 327.54). They don’t set a general insurance requirement for private owners, but a marina, storage or HOA contract may have its own. Even without a legal requirement, an owner can be sued for injuries or damage caused by the PWC, so liability coverage is the core of most PWC policies.' },
        { q: 'Can my friend drive my jet ski?', a: 'Florida law lets an adult friend drive it if he or she follows the PWC rules and, if born on or after January 1, 1988, carries a boater ID card. Nobody under 14 may operate a PWC. Whether your policy covers a guest operator depends on the policy, so check before you hand over the key.' },
        { q: 'Does my homeowners policy cover my jet ski?', a: 'Often only in a limited way, or not at all, for a motorized watercraft. Read the watercraft section of your home policy or send it to us and we will tell you what it says.' },
        { q: 'I am renting a jet ski on vacation. Should I buy the rental company’s coverage?', a: 'Florida rental companies must either insure renters or offer them coverage. Before you decline it, ask whether your own policy covers you on a rented PWC. If it doesn’t, you could be personally responsible for injuries or damage you cause.' },
        { q: 'Do I need to report a jet ski accident?', a: 'Yes, if it causes an injury needing more than first aid, a death or disappearance, or at least $2,000 in property damage. The operator files a written report with FWC unless an officer has already written one.' },
        { q: 'Do you help with PWC claims?', a: 'Yes. Call us or message us on WhatsApp. A licensed agent helps you report the claim and explains each step in English, Spanish or Russian.' },
      ],
      related: [
        { path: '/boat-insurance-florida', label: 'Boat insurance in Florida' },
        { path: '/umbrella-insurance-florida-city', label: 'Umbrella insurance: extra liability protection' },
      ],
      sources: srcList('en', [...KEYS]),
    },
    es: {
      metaTitle: 'Seguro de Moto Acuática (Jet Ski) en Florida | M&K',
      metaDesc: 'Las motos acuáticas son el 17% de las embarcaciones de Florida pero el 23% de los accidentes. Reglas, invitados al timón y huecos de cobertura.',
      breadcrumb: 'Seguro de jet ski en Florida',
      kicker: 'Seguro de jet ski / moto acuática · Toda la Florida',
      h1a: 'Seguro de jet ski en Florida:',
      h1b: 'proteja al que maneja, a sus invitados y a los demás.',
      answer: 'Un jet ski es pequeño, rápido y muchas veces lo manejan amigos y familiares. En Florida, las motos acuáticas tienen muchos más accidentes de lo que les tocaría por su número, así que la **responsabilidad civil y la cobertura para quien maneja con su permiso** importan tanto como la máquina. Revisamos su póliza y se la explicamos en español.',
      serviceType: 'Seguro de motos acuáticas (jet ski)',
      leadLabel: 'Jet ski / moto acuática',
      intro: [
        { type: 'p', text: 'Casi todos los dueños de jet ski piensan primero en la máquina: un golpe en el casco, la turbina dañada, el tráiler robado. Eso importa. Pero en un banco de arena lleno de gente o en un canal, el riesgo más grande es **lo que les pase a otras personas**: un choque con otro bote, un bañista, un muelle o un invitado que pierde el control de su moto acuática.' },
        { type: 'p', text: 'Florida tiene reglas propias para las motos acuáticas: chalecos, edad mínima, alquileres. Aquí están las que afectan su cobertura, los huecos que vemos más a menudo y lo que conviene preguntar antes de la próxima salida.' },
      ],
      factsTitle: 'Motos acuáticas en Florida: lo que dicen las cifras',
      facts: [
        { value: '23%', text: 'de los 694 accidentes náuticos reportables de Florida en 2025 involucró una moto acuática, aunque solo son el 17% de las embarcaciones registradas.', source: u('fwc2025') },
        { value: '45%', text: 'de los accidentes de motos acuáticas en 2025 fueron choques con otra embarcación.', source: u('fwc2025') },
        { value: '40', text: 'accidentes de motos acuáticas en los condados de Miami-Dade (20) y Monroe (20) en 2025, más que en cualquier otra zona del estado.', source: u('fwc2025') },
        { value: '14', text: 'años es la edad mínima para manejar una moto acuática en Florida. El dueño no puede dejar que la maneje alguien menor.', source: u('s327_39') },
      ],
      figureAlt: 'Infografía. Reglas y riesgos del jet ski en Florida: todos a bordo llevan chaleco aprobado por la Guardia Costera que no sea inflable, el cordón de apagado va sujeto al conductor, no se navega desde media hora después de la puesta del sol hasta media hora antes del amanecer, y quien maneja debe tener al menos 14 años. En 2025 las motos acuáticas fueron el 17% de las embarcaciones registradas y el 23% de los accidentes.',
      figureCaption: 'Reglas de la s. 327.39 de los Estatutos de Florida; cifras del informe de accidentes náuticos 2025 de la FWC.',
      gapsTitle: 'Dónde se quedan cortos los dueños de jet ski',
      gaps: [
        { h: 'Maneja un invitado', p: 'Amigos y familiares se turnan. Si un invitado lesiona a alguien o daña otro bote, el reclamo puede volver a usted como dueño. Revise a quién cubre su póliza como conductor.' },
        { h: 'Lesiones de sus pasajeros', p: 'Las caídas y choques en moto acuática pueden lesionar a quienes van con usted. Normalmente responden los pagos médicos y la responsabilidad civil, según la póliza.' },
        { h: 'Fuera del agua', p: 'El tráiler, el lugar donde la guarda, el robo en la entrada de su casa y los daños por tormenta son otra historia. El tráiler no siempre se cubre igual que la moto acuática.' },
      ],
      coverageTitle: 'Coberturas que conviene preguntar en una póliza de jet ski en Florida',
      coverage: [
        { h: 'Responsabilidad civil', p: 'Paga las lesiones y los daños que usted o alguien con su permiso cause a otros, hasta sus límites, y la defensa legal.' },
        { h: 'Pagos médicos', p: 'Ayuda con los gastos médicos suyos y de sus pasajeros después de un accidente, sin importar la culpa.' },
        { h: 'Navegante sin seguro', p: 'Ayuda cuando el que lo lesiona en el agua no tiene seguro o tiene muy poco.' },
        { h: 'Daño físico', p: 'Daños al casco, el motor y la turbina por choque, robo, incendio o tormenta.' },
        { h: 'Tráiler y accesorios', p: 'Su tráiler, fundas, cuerdas de remolque y otros equipos, si se declaran o están incluidos.' },
        { h: 'Remolque y asistencia en el agua', p: 'Ayuda para volver a la rampa si el motor se apaga lejos de la orilla.' },
      ],
      coverageNote: 'Son descripciones generales. La disponibilidad, los límites y las exclusiones dependen de la póliza.',
      body: [
        { type: 'h2', text: 'Las reglas de Florida para motos acuáticas, en palabras sencillas' },
        { type: 'ul', items: [
          'Todos a bordo, y quien vaya remolcado, deben llevar un **chaleco salvavidas aprobado por la Guardia Costera que no sea inflable** ([s. 327.39](https://www.flsenate.gov/Laws/Statutes/2026/327.39)).',
          'Si la moto acuática tiene **cordón de apagado del motor**, el conductor debe llevarlo sujeto al cuerpo, la ropa o el chaleco.',
          'No se puede navegar desde **media hora después de la puesta del sol hasta media hora antes del amanecer**.',
          'Zigzaguear entre botes, saltar la estela de otro bote demasiado cerca o esquivar a último momento puede considerarse **navegación temeraria**.',
          'Nadie **menor de 14 años** puede manejar una moto acuática, y el dueño no puede permitirlo a sabiendas.',
          'Quien haya nacido el **1 de enero de 1988 o después** necesita la **tarjeta de educación en seguridad náutica** (u otro documento aceptado) y una identificación con foto para manejar una embarcación con motor de 10 caballos de fuerza o más ([s. 327.395](https://www.flsenate.gov/Laws/Statutes/2026/327.395); [FWC](https://myfwc.com/boating/safety-education/id/)).',
        ] },
        { type: 'h2', text: 'Si alquila un jet ski, o si alquila el suyo' },
        { type: 'p', text: 'Los negocios de alquiler en Florida no pueden alquilar una moto acuática a **menores de 18 años**, deben dar **instrucciones antes de salir** y deben tener su propio seguro de responsabilidad civil de al menos $500,000 por persona y $1 millón por evento. Además, deben asegurar al cliente por los mismos montos u **ofrecerle una cobertura**; si el cliente la rechaza, firma una declaración de que quizás no tenga otro seguro para los daños ([s. 327.54](https://www.flsenate.gov/Laws/Statutes/2026/327.54)).' },
        { type: 'p', text: 'Si usted alquila su propia moto acuática por dinero, puede que la ley lo trate como un negocio de alquiler, con sus propios permisos y requisitos de seguro. Una póliza personal normalmente no está hecha para eso. Pregúntenos antes de publicarla.' },
        { type: 'h2', text: 'Después de un accidente' },
        { type: 'p', text: 'Quien maneja debe enviar un reporte escrito a la FWC cuando el accidente causa una lesión que necesita más que primeros auxilios, una muerte o desaparición, o al menos **$2,000** en daños ([s. 327.301](https://www.flsenate.gov/Laws/Statutes/2026/327.301)). Tome fotos, anote nombres y números de registro de las embarcaciones y llame a su agente ese mismo día.' },
        { type: 'callout', title: 'Alcohol en el agua', text: 'La ley de Florida sobre navegar bajo los efectos usa el mismo límite de 0.08 que en la carretera ([s. 327.35](https://www.flsenate.gov/Laws/Statutes/2026/327.35)). A nivel nacional, el alcohol es el principal factor conocido en los accidentes náuticos mortales ([USCG](https://uscgboating.org/library/accident-statistics/Recreational-Boating-Statistics-2024.pdf)).' },
      ],
      checklistTitle: 'Antes de la próxima salida: revise su cobertura de jet ski',
      checklist: [
        '¿Su póliza cubre a **otras personas que usted deja manejar**? ¿Hay límites de edad o experiencia?',
        '¿Sus **límites de responsabilidad civil** van de acuerdo con lo que tiene y lo que gana?',
        '¿Tiene **pagos médicos** para sus pasajeros?',
        '¿Su **tráiler** está en la póliza? ¿Está cubierta la moto guardada en casa o en la marina?',
        '¿Piensa **alquilarla**? Avísele primero a su agente.',
        'Tenga a mano las **tarjetas de navegante** de todos los que manejan y un chaleco no inflable para cada asiento.',
      ],
      agentTitle: 'Un agente personal cuando más importa: en el reclamo',
      agent: [
        { type: 'p', text: 'M&K Agency es una agencia familiar de Florida City, cerca de la Bahía de Biscayne y de los Cayos, con más de 5,000 clientes en toda la Florida y un equipo de 12 personas que hablan español, inglés y ruso.' },
        { type: 'p', text: 'Si algo sale mal en el agua, llámenos o escríbanos. Le ayudamos a reportar el reclamo, le explicamos qué paga su póliza y lo acompañamos hasta el final. **Envíenos su póliza y revisamos su cobertura.**' },
      ],
      faqTitle: 'Seguro de jet ski en Florida: preguntas frecuentes',
      faq: [
        { q: '¿Es obligatorio el seguro de jet ski en Florida?', a: 'Las leyes náuticas de Florida fijan reglas de seguro para los negocios de alquiler, que deben tener responsabilidad civil y ofrecer cobertura a sus clientes (s. 327.54). No fijan un requisito general para los dueños particulares, pero el contrato de la marina, del lugar donde la guarda o de su HOA puede exigirlo. Aunque no sea obligatorio, al dueño lo pueden demandar por lesiones o daños causados con la moto acuática, por eso la responsabilidad civil es el centro de casi todas las pólizas.' },
        { q: '¿Mi amigo puede manejar mi jet ski?', a: 'La ley de Florida lo permite a un amigo adulto si cumple las reglas para motos acuáticas y, si nació el 1 de enero de 1988 o después, lleva su tarjeta de navegante. Nadie menor de 14 años puede manejarla. Si su póliza cubre a un invitado al timón depende de la póliza, así que revíselo antes de entregarle la llave.' },
        { q: '¿Mi seguro de casa cubre mi jet ski?', a: 'Muchas veces solo de forma limitada, o nada, cuando se trata de una embarcación con motor. Lea la sección de embarcaciones de su póliza de casa o envíenosla y le decimos qué dice.' },
        { q: 'Voy a alquilar un jet ski en vacaciones. ¿Compro la cobertura del negocio?', a: 'En Florida, los negocios de alquiler deben asegurar al cliente u ofrecerle una cobertura. Antes de rechazarla, pregunte si su propia póliza lo cubre en una moto acuática alquilada. Si no, usted podría responder personalmente por las lesiones o daños que cause.' },
        { q: '¿Tengo que reportar un accidente de jet ski?', a: 'Sí, si causa una lesión que necesita más que primeros auxilios, una muerte o desaparición, o al menos $2,000 en daños. Quien maneja envía un reporte escrito a la FWC, salvo que un oficial ya haya hecho uno.' },
        { q: '¿Me ayudan con un reclamo de moto acuática?', a: 'Sí. Llámenos o escríbanos por WhatsApp. Un agente licenciado le ayuda a reportar el reclamo y le explica cada paso en español, inglés o ruso.' },
      ],
      related: [
        { path: '/boat-insurance-florida', label: 'Seguro de bote en Florida' },
        { path: '/umbrella-insurance-florida-city', label: 'Seguro umbrella: más protección de responsabilidad civil' },
      ],
      sources: srcList('es', [...KEYS]),
    },
    ru: {
      metaTitle: 'Страховка гидроцикла (jet ski) во Флориде | M&K',
      metaDesc: 'Гидроциклы — 17% судов Флориды, но 23% происшествий на воде. Правила штата, гости за рулём и дыры в покрытии — объясняем по-русски.',
      breadcrumb: 'Страховка гидроцикла во Флориде',
      kicker: 'Страховка гидроцикла (PWC) · Вся Флорида',
      h1a: 'Страховка гидроцикла во Флориде:',
      h1b: 'защитите себя, гостей и тех, кто рядом.',
      answer: 'Гидроцикл маленький, быстрый, и за руль часто садятся друзья и родные. Во Флориде гидроциклы попадают в происшествия намного чаще, чем можно ожидать по их числу, поэтому **ответственность и покрытие для гостей за рулём** важны не меньше, чем сама техника. Проверим ваш полис и объясним по-русски.',
      serviceType: 'Страхование гидроциклов',
      leadLabel: 'Гидроцикл (jet ski)',
      intro: [
        { type: 'p', text: 'Владельцы гидроциклов обычно думают о технике: царапина на корпусе, повреждённый водомёт, украденный прицеп. Это важно. Но на людной отмели или в канале главный риск — **то, что случится с другими людьми**: столкновение с лодкой, пловец, причал или гость, который не справился с управлением вашего гидроцикла.' },
        { type: 'p', text: 'Во Флориде для гидроциклов есть отдельные правила: спасжилеты, минимальный возраст, прокат. Ниже — те правила, которые влияют на страховку, самые частые дыры в покрытии и вопросы, которые стоит задать до следующего выезда.' },
      ],
      factsTitle: 'Гидроциклы во Флориде: что говорят цифры',
      facts: [
        { value: '23%', text: 'из 694 зарегистрированных происшествий на воде во Флориде в 2025 году — с участием гидроциклов, хотя среди всех судов их только 17%.', source: u('fwc2025') },
        { value: '45%', text: 'происшествий с гидроциклами в 2025 году — столкновения с другим судном.', source: u('fwc2025') },
        { value: '40', text: 'происшествий с гидроциклами в округах Майами-Дейд (20) и Монро (20) в 2025 году — больше, чем где-либо ещё в штате.', source: u('fwc2025') },
        { value: '14', text: 'лет — минимальный возраст, с которого во Флориде можно управлять гидроциклом. Владелец не вправе пускать за руль младших.', source: u('s327_39') },
      ],
      figureAlt: 'Инфографика. Правила и риски для гидроциклов во Флориде: все на борту в ненадувных спасжилетах, одобренных Береговой охраной, шнур аварийной остановки пристёгнут к водителю, нельзя кататься с получаса после заката до получаса до рассвета, водителю не меньше 14 лет. В 2025 году гидроциклы — 17% зарегистрированных судов и 23% происшествий.',
      figureCaption: 'Правила — ст. 327.39 Законов Флориды; цифры — отчёт FWC о происшествиях на воде за 2025 год.',
      gapsTitle: 'Где владельцы гидроциклов остаются без защиты',
      gaps: [
        { h: 'За рулём гость', p: 'Друзья и родные катаются по очереди. Если гость кого-то травмирует или повредит чужую лодку, претензия может прийти к вам как к владельцу. Проверьте, кого полис покрывает как водителя.' },
        { h: 'Травмы ваших пассажиров', p: 'Падения и столкновения на гидроцикле травмируют и тех, кто едет с вами. Обычно тут работают покрытие медицинских расходов и ответственность — в зависимости от полиса.' },
        { h: 'На суше', p: 'Прицеп, хранение, кража с подъездной дорожки и ущерб от шторма — отдельные вопросы. Прицеп не всегда покрыт так же, как сам гидроцикл.' },
      ],
      coverageTitle: 'О каких покрытиях спросить в полисе на гидроцикл',
      coverage: [
        { h: 'Ответственность (liability)', p: 'Оплачивает травмы и ущерб, причинённые другим вами или тем, кого вы пустили за руль, в пределах лимитов, плюс юридическую защиту.' },
        { h: 'Медицинские расходы', p: 'Помогает с лечением вас и ваших пассажиров после происшествия, независимо от вины.' },
        { h: 'Судоводитель без страховки', p: 'Помогает, если у того, кто вас травмировал на воде, нет страховки или её мало.' },
        { h: 'Ущерб самому гидроциклу', p: 'Корпус, двигатель и водомёт: столкновение, угон, пожар или шторм.' },
        { h: 'Прицеп и аксессуары', p: 'Прицеп, чехлы, буксировочные фалы и другое снаряжение — если оно указано или включено.' },
        { h: 'Буксировка и помощь на воде', p: 'Помощь, чтобы вернуться к слипу, если двигатель заглох далеко от берега.' },
      ],
      coverageNote: 'Это общие описания. Наличие покрытий, лимиты и исключения зависят от конкретного полиса.',
      body: [
        { type: 'h2', text: 'Правила Флориды для гидроциклов — простыми словами' },
        { type: 'ul', items: [
          'Все на борту и все, кого буксируют, должны быть в **спасжилете, одобренном Береговой охраной США, и не надувном** ([ст. 327.39](https://www.flsenate.gov/Laws/Statutes/2026/327.39)).',
          'Если у гидроцикла есть **шнур аварийной остановки двигателя**, водитель обязан пристегнуть его к себе, к одежде или к жилету.',
          'Нельзя кататься **с получаса после заката до получаса до рассвета**.',
          'Лавирование между судами, прыжки по волне другой лодки слишком близко к ней, резкие отвороты в последний момент могут считаться **опасным управлением**.',
          'Управлять гидроциклом **до 14 лет** нельзя, и владелец не вправе сознательно это допускать.',
          'Тем, кто родился **1 января 1988 года или позже**, для управления судном с мотором от 10 л. с. нужны **удостоверение FWC об обучении безопасности на воде** (или другой принятый документ) и документ с фото ([ст. 327.395](https://www.flsenate.gov/Laws/Statutes/2026/327.395); [FWC](https://myfwc.com/boating/safety-education/id/)).',
        ] },
        { type: 'h2', text: 'Если вы берёте гидроцикл напрокат — или сдаёте свой' },
        { type: 'p', text: 'Пункты проката во Флориде не вправе сдавать гидроцикл **лицам до 18 лет**, обязаны провести **инструктаж перед выездом** и иметь собственную страховку ответственности не меньше $500 000 на человека и $1 млн на случай. Кроме того, они должны либо застраховать арендатора на те же суммы, либо **предложить ему страховку**; если арендатор отказывается, он подписывает заявление, что другой страховки на такой ущерб у него может не быть ([ст. 327.54](https://www.flsenate.gov/Laws/Statutes/2026/327.54)).' },
        { type: 'p', text: 'Если вы сдаёте свой гидроцикл за деньги, закон может считать вас прокатом — со своими разрешениями и требованиями к страховке. Личный полис обычно не рассчитан на такое. Спросите нас, прежде чем размещать объявление.' },
        { type: 'h2', text: 'После происшествия' },
        { type: 'p', text: 'Водитель обязан подать письменный отчёт в FWC, если в происшествии кто-то получил травму, требующую больше чем первой помощи, погиб или пропал, либо ущерб имуществу составил не меньше **$2 000** ([ст. 327.301](https://www.flsenate.gov/Laws/Statutes/2026/327.301)). Сделайте фото, запишите имена и регистрационные номера судов и позвоните агенту в тот же день.' },
        { type: 'callout', title: 'Алкоголь на воде', text: 'Закон Флориды об управлении судном в нетрезвом виде использует тот же порог 0,08, что и на дороге ([ст. 327.35](https://www.flsenate.gov/Laws/Statutes/2026/327.35)). По всей стране алкоголь — главный известный фактор в смертельных происшествиях на воде ([USCG](https://uscgboating.org/library/accident-statistics/Recreational-Boating-Statistics-2024.pdf)).' },
      ],
      checklistTitle: 'Перед следующим выездом: короткая проверка полиса',
      checklist: [
        'Покрывает ли полис **других людей, которых вы пускаете за руль**? Есть ли ограничения по возрасту или опыту?',
        'Соответствуют ли **лимиты ответственности** тому, что у вас есть и сколько вы зарабатываете?',
        'Есть ли покрытие **медицинских расходов** для пассажиров?',
        'Вписан ли **прицеп** и покрыто ли хранение дома или в марине?',
        'Собираетесь **сдавать в прокат**? Сначала скажите агенту.',
        'Держите под рукой **удостоверения FWC** всех, кто водит, и ненадувной жилет на каждое место.',
      ],
      agentTitle: 'Личный агент, когда это важнее всего: при страховом случае',
      agent: [
        { type: 'p', text: 'M&K Agency — семейное агентство во Флорида-Сити, недалеко от залива Бискейн и Кис: больше 5 000 клиентов по всей Флориде и команда из 12 человек, которые говорят по-русски, по-английски и по-испански.' },
        { type: 'p', text: 'Если на воде что-то случилось, позвоните или напишите нам. Поможем заявить убыток, объясним, что платит полис, и будем рядом до конца урегулирования. **Пришлите полис — мы проверим ваше покрытие.**' },
      ],
      faqTitle: 'Страховка гидроцикла во Флориде: частые вопросы',
      faq: [
        { q: 'Обязательна ли страховка гидроцикла во Флориде?', a: 'Законы Флориды о судоходстве прописывают требования к страховке для пунктов проката: у них должна быть страховка ответственности, и они обязаны предлагать страховку арендаторам (ст. 327.54). Общего требования для частных владельцев там нет, но его может поставить договор с мариной, местом хранения или HOA. Даже без обязательного требования владельца могут засудить за травмы или ущерб, причинённые гидроциклом, поэтому ответственность — основа почти любого полиса.' },
        { q: 'Может ли мой друг кататься на моём гидроцикле?', a: 'Закон Флориды это допускает для взрослого друга, если он соблюдает правила для гидроциклов и, если родился 1 января 1988 года или позже, имеет удостоверение FWC. До 14 лет управлять гидроциклом нельзя. Покрывает ли полис гостя за рулём — зависит от полиса, проверьте это до того, как отдадите ключ.' },
        { q: 'Покрывает ли гидроцикл моя страховка дома?', a: 'Часто лишь ограниченно или вовсе нет, если речь о моторном судне. Прочитайте раздел о плавсредствах в полисе на дом или пришлите его нам — скажем, что там написано.' },
        { q: 'Беру гидроцикл напрокат в отпуске. Покупать страховку проката?', a: 'Во Флориде прокат обязан либо застраховать арендатора, либо предложить ему страховку. Прежде чем отказаться, узнайте, покрывает ли вас ваш собственный полис на арендованном гидроцикле. Если нет, за травмы или ущерб можете отвечать вы лично.' },
        { q: 'Нужно ли сообщать о происшествии на гидроцикле?', a: 'Да, если есть травма, требующая больше чем первой помощи, погибший или пропавший человек, либо ущерб от $2 000. Водитель подаёт письменный отчёт в FWC, если его уже не составил офицер.' },
        { q: 'Помогаете ли вы со страховыми случаями по гидроциклу?', a: 'Да. Позвоните или напишите в WhatsApp. Лицензированный агент поможет заявить убыток и объяснит каждый шаг по-русски, по-английски или по-испански.' },
      ],
      related: [
        { path: '/boat-insurance-florida', label: 'Страховка лодки во Флориде' },
        { path: '/umbrella-insurance-florida-city', label: 'Umbrella: дополнительная защита ответственности' },
      ],
      sources: srcList('ru', [...KEYS]),
    },
  },
};
