import type { RecPage } from './types';
import { srcList, u } from './sources';

// Facts: LIMRA/Life Happens 2026 Insurance Barometer (52% own; 47% of owners through work;
// 38% / ~92M need or need more; 47% trouble within 6 months; 29% secure > 2 years;
// nearly a quarter don't know how much or what type); s. 222.13 (proceeds to a named
// beneficiary exempt from the insured's creditors; payable to estate -> estate);
// s. 222.14 (cash surrender value exempt); s. 627.455 (incontestable after 2 years);
// s. 627.4555 (64+, secondary addressee, 21 days' notice before lapse).
const KEYS = ['limra2026', 's222_13', 's222_14', 's627_455', 's627_4555'] as const;

export const LIFE: RecPage = {
  line: 'life',
  path: '/life-insurance-florida',
  leadValue: 'Life',
  leadSource: 'rec-life',
  articleSlug: 'life-insurance-income-replacement-florida',
  productSlug: 'life-insurance',
  published: '2026-10-03',
  modified: '2026-10-03',
  copy: {
    en: {
      metaTitle: 'Life Insurance in Florida: Replace Your Income | M&K Agency',
      metaDesc: 'How much life insurance does a Florida family need? Income replacement, coverage through work, beneficiaries and Florida law, with a local agent. EN/ES/RU.',
      breadcrumb: 'Life insurance in Florida',
      kicker: 'Life insurance · All of Florida',
      h1a: 'Life insurance in Florida:',
      h1b: 'so your family keeps the home and the plan if your paycheck stops.',
      answer: 'Life insurance replaces the income your family would lose if you died. Nearly half of Americans say their household would struggle to pay the bills **within six months** of losing the main earner. A personal agent helps you work out how much coverage fits your family, name the right **beneficiaries**, and helps them with the claim.',
      serviceType: 'Life insurance',
      leadLabel: 'Life insurance',
      intro: [
        { type: 'p', text: 'Most families think about life insurance at a funeral. The better time is now, while you can still choose. The real question is not “Do I need a policy?” but “If my paycheck stopped tomorrow, how long would my family be OK?”' },
        { type: 'p', text: 'This page walks through that question in plain words: how much income to replace, why coverage through work may not be enough, how beneficiaries work under Florida law, and what we do when your family needs us.' },
      ],
      factsTitle: 'Life insurance in the U.S.: what the numbers say',
      facts: [
        { value: '47%', text: 'of American adults say they would have trouble paying living expenses within 6 months of their primary wage earner’s death.', source: u('limra2026') },
        { value: '29%', text: 'say they would stay financially secure for more than 2 years if a primary wage earner died.', source: u('limra2026') },
        { value: '38%', text: 'of adults, about 92 million people, say they need life insurance or need more of it.', source: u('limra2026') },
        { value: '47%', text: 'of people who have life insurance get it through work. That coverage is tied to the job.', source: u('limra2026') },
      ],
      figureAlt: 'Infographic. Income replacement: add up the years your family would need your income, the mortgage or rent, debts, childcare and college, and final expenses; subtract the coverage and assets you already have. The difference is the gap life insurance can fill. Amounts and policy types depend on the family and the policy.',
      figureCaption: 'A simple way to think about how much coverage a family needs. It is an estimate, not a recommendation.',
      gapsTitle: 'Where Florida families get caught short',
      gaps: [
        { h: 'Only the coverage from work', p: 'Group life through an employer is often a set amount, and it may end or change when you leave the job. Check whether it can be continued or converted.' },
        { h: 'The stay-at-home parent has none', p: 'If the parent at home died, the family would have to pay for childcare, driving and the work of running a house.' },
        { h: 'Outdated beneficiaries', p: 'A marriage, a divorce or a new baby can leave the wrong person named, or nobody. If the policy pays your estate, the money can go through probate.' },
      ],
      coverageTitle: 'Life insurance options to ask about',
      coverage: [
        { h: 'Term life', p: 'Coverage for a set number of years, for example while the children are growing up or until the mortgage is paid.' },
        { h: 'Permanent life (whole or universal)', p: 'Coverage meant to last for life while it is kept in force. Many permanent policies build cash value.' },
        { h: 'Riders', p: 'Add-ons such as coverage for a child, a waiver of payments after a disability, or access to part of the benefit if terminally ill, where offered.' },
        { h: 'Final expense coverage', p: 'A smaller policy meant for funeral and end-of-life costs, so the family does not have to pay them.' },
        { h: 'Coverage outside of work', p: 'An individual policy you own, that stays with you when you change jobs.' },
        { h: 'Beneficiary planning', p: 'Primary and backup beneficiaries, and how to handle minor children, reviewed with your agent.' },
      ],
      coverageNote: 'These are general descriptions. Availability, terms and exclusions depend on the policy and on underwriting.',
      body: [
        { type: 'h2', text: 'Start with income replacement' },
        { type: 'p', text: 'Among the top reasons Americans give for owning life insurance are burial and final expenses, leaving an inheritance and replacing the income of a wage earner ([LIMRA and Life Happens, 2026](https://www.limra.com/siteassets/newsroom/liam/2026/facts-about-life-insurance.pdf)). For a working family, income replacement is usually the biggest number. A simple way to think about it:' },
        { type: 'ol', items: [
          'How many **years** would your family need your income? Until the youngest finishes school, or until your spouse retires?',
          'What would they need to pay off or keep paying: **the mortgage or rent, other debts, credit cards**?',
          'What else is coming: **childcare, college, caring for a parent**?',
          'Add **final expenses**.',
          'Subtract what you already have: **coverage through work, other policies, assets**.',
        ] },
        { type: 'p', text: 'The calculator below gives you a starting point. An agent can then help you decide how much coverage and which type fit your family. Nearly a quarter of Americans say they haven’t bought life insurance because they don’t know how much they need or what type to buy; that is exactly what the conversation is for.' },
        { type: 'h2', text: 'What Florida law says about beneficiaries and your policy' },
        { type: 'ul', items: [
          'When a Florida resident dies, life insurance **paid to a named beneficiary** goes to that person and is generally **protected from the claims of the insured’s creditors**. If it is payable to the insured’s **estate**, it becomes part of the estate ([s. 222.13](https://www.flsenate.gov/Laws/Statutes/2026/222.13)).',
          'The **cash surrender value** of a policy on a Florida resident is also generally protected from creditors ([s. 222.14](https://www.flsenate.gov/Laws/Statutes/2026/222.14)).',
          'A life policy becomes **incontestable after it has been in force for 2 years** during the insured’s lifetime, except for nonpayment and certain disability and accident benefits ([s. 627.455](https://www.flsenate.gov/Laws/Statutes/2026/627.455)). Answer the application honestly and completely.',
          'For an insured **64 or older** whose policy has been in force at least a year, you can name a **secondary person** to be notified, and the insurer must mail notice to the owner and that person **at least 21 days before the policy lapses** for nonpayment ([s. 627.4555](https://www.flsenate.gov/Laws/Statutes/2026/627.4555)). It is a simple way to keep a parent’s policy from lapsing by accident.',
        ] },
        { type: 'callout', title: 'Already have a policy?', text: 'Pull it out and read the beneficiary page. If it names an ex-spouse, a minor child directly or nobody at all, talk to your agent this week. **Send us your policy and we’ll check your coverage.**' },
      ],
      checklistTitle: 'A ten-minute life insurance check',
      checklist: [
        'Do you know **how much** coverage you have, including through work?',
        'Would it cover **several years of your income**, plus the mortgage or rent?',
        'Does your spouse or partner, including a **stay-at-home parent**, have coverage?',
        'Are your **primary and backup beneficiaries** current?',
        'Would your coverage **end if you left your job**?',
        'If a parent is 64 or older, have they named a **secondary person** for lapse notices?',
      ],
      agentTitle: 'A personal agent when your family needs it most',
      agent: [
        { type: 'p', text: 'M&K Agency is a family-owned agency in Florida City with more than 5,000 clients across Florida and a team of 12 who speak English, Spanish and Russian. We sit down with you, in person or by phone, to work out what your family would need.' },
        { type: 'p', text: 'And if the worst happens, your family calls us. We help them find the policy, gather the documents and file the claim, and we explain each step in their language.' },
      ],
      faqTitle: 'Life insurance in Florida: common questions',
      faq: [
        { q: 'How much life insurance do I need?', a: 'Start with the years of income your family would need, add the mortgage or rent, debts, childcare, college and final expenses, then subtract the coverage and assets you already have. The calculator on this page gives a starting estimate; an agent can help you refine it.' },
        { q: 'Is life insurance through work enough?', a: 'Often not. Group coverage is usually a set amount, and it may end or change when you leave the job. Many families add an individual policy they own.' },
        { q: 'Is life insurance protected from creditors in Florida?', a: 'Generally, yes. Under s. 222.13, Florida Statutes, proceeds paid to a named beneficiary are exempt from the claims of the insured’s creditors unless the policy or an assignment says otherwise; if the policy pays the estate, the money becomes part of the estate. Cash surrender value is also generally exempt under s. 222.14. For your situation, ask an attorney.' },
        { q: 'What is the difference between term and permanent life insurance?', a: 'Term life covers a set number of years. Permanent life, such as whole or universal life, is meant to last for life while it is kept in force, and many permanent policies build cash value. Which one fits depends on your goals.' },
        { q: 'Can an insurer deny a claim because of something on my application?', a: 'Under Florida law, a life policy becomes incontestable after it has been in force for 2 years during the insured’s lifetime, with some exceptions such as nonpayment. Before then, misstatements on the application can matter, so answer every question honestly.' },
        { q: 'Will you help my family with a claim?', a: 'Yes. Your family can call us or message us on WhatsApp. A licensed agent helps them file the claim and explains each step in English, Spanish or Russian.' },
      ],
      related: [
        { path: '/protect', label: 'Protection guides for your family: car, home and life' },
        { path: '/umbrella-insurance-florida-city', label: 'Umbrella insurance: extra liability protection' },
      ],
      sources: srcList('en', [...KEYS]),
    },
    es: {
      metaTitle: 'Seguro de Vida en Florida: Proteja su Ingreso | M&K Agency',
      metaDesc: '¿Cuánto seguro de vida necesita una familia en Florida? Reemplazo de ingresos, cobertura del trabajo, beneficiarios y la ley de Florida, con un agente local.',
      breadcrumb: 'Seguro de vida en Florida',
      kicker: 'Seguro de vida · Toda la Florida',
      h1a: 'Seguro de vida en Florida:',
      h1b: 'para que su familia conserve la casa y sus planes si falta su sueldo.',
      answer: 'El seguro de vida reemplaza el ingreso que su familia perdería si usted falta. Casi la mitad de los estadounidenses dice que en su casa tendrían problemas para pagar las cuentas **antes de seis meses** si muere quien más aporta. Un agente personal le ayuda a calcular cuánta cobertura necesita su familia, a nombrar bien a sus **beneficiarios** y acompaña a los suyos en el reclamo.',
      serviceType: 'Seguro de vida',
      leadLabel: 'Seguro de vida',
      intro: [
        { type: 'p', text: 'Muchas familias piensan en el seguro de vida en un velorio. El mejor momento es ahora, mientras todavía se puede elegir. La pregunta de verdad no es “¿necesito una póliza?”, sino “si mañana dejara de entrar mi sueldo, ¿cuánto tiempo estaría bien mi familia?”.' },
        { type: 'p', text: 'Aquí vemos esa pregunta con palabras claras: cuánto ingreso reemplazar, por qué la cobertura del trabajo puede no alcanzar, cómo funcionan los beneficiarios según la ley de Florida y qué hacemos cuando su familia nos necesita.' },
      ],
      factsTitle: 'El seguro de vida en EE. UU.: lo que dicen las cifras',
      facts: [
        { value: '47%', text: 'de los adultos en EE. UU. dice que tendría problemas para pagar sus gastos antes de 6 meses si muere quien más aporta en la casa.', source: u('limra2026') },
        { value: '29%', text: 'dice que seguiría estable económicamente más de 2 años si muriera quien más aporta.', source: u('limra2026') },
        { value: '38%', text: 'de los adultos, unos 92 millones de personas, dice que necesita seguro de vida o necesita más.', source: u('limra2026') },
        { value: '47%', text: 'de quienes tienen seguro de vida lo tienen por el trabajo. Esa cobertura depende del empleo.', source: u('limra2026') },
      ],
      figureAlt: 'Infografía. Reemplazo de ingresos: sume los años que su familia necesitaría su ingreso, la hipoteca o la renta, las deudas, el cuidado de los niños y la universidad, y los gastos finales; reste la cobertura y los bienes que ya tiene. La diferencia es el hueco que puede llenar un seguro de vida. Los montos y el tipo de póliza dependen de la familia y de la póliza.',
      figureCaption: 'Una forma sencilla de pensar cuánta cobertura necesita una familia. Es un cálculo aproximado, no una recomendación.',
      gapsTitle: 'Dónde se quedan cortas las familias en Florida',
      gaps: [
        { h: 'Solo la cobertura del trabajo', p: 'El seguro de vida de grupo del empleador suele ser un monto fijo y puede terminar o cambiar si deja el trabajo. Pregunte si se puede continuar o convertir.' },
        { h: 'Quien cuida la casa no tiene seguro', p: 'Si falta el padre o la madre que está en casa, la familia tendría que pagar por el cuidado de los niños, los traslados y todo el trabajo del hogar.' },
        { h: 'Beneficiarios sin actualizar', p: 'Un matrimonio, un divorcio o un bebé pueden dejar nombrada a la persona equivocada, o a nadie. Si la póliza le paga a su sucesión, el dinero puede pasar por el proceso de sucesión (probate).' },
      ],
      coverageTitle: 'Opciones de seguro de vida que conviene preguntar',
      coverage: [
        { h: 'Seguro de vida a término', p: 'Cobertura por un número fijo de años, por ejemplo mientras los hijos crecen o hasta terminar de pagar la casa.' },
        { h: 'Seguro de vida permanente (entera o universal)', p: 'Cobertura pensada para toda la vida mientras se mantenga vigente. Muchas pólizas permanentes acumulan valor en efectivo.' },
        { h: 'Cláusulas adicionales (riders)', p: 'Agregados como cobertura para un hijo, exención de pagos por incapacidad o acceso a parte del beneficio ante una enfermedad terminal, cuando se ofrecen.' },
        { h: 'Cobertura de gastos finales', p: 'Una póliza más pequeña pensada para el funeral y los gastos del final de la vida, para que la familia no tenga que pagarlos.' },
        { h: 'Cobertura fuera del trabajo', p: 'Una póliza individual a su nombre, que se queda con usted aunque cambie de empleo.' },
        { h: 'Planificación de beneficiarios', p: 'Beneficiarios principales y de respaldo, y qué hacer con los hijos menores, revisado con su agente.' },
      ],
      coverageNote: 'Son descripciones generales. La disponibilidad, las condiciones y las exclusiones dependen de la póliza y de la evaluación de la aseguradora.',
      body: [
        { type: 'h2', text: 'Empiece por el reemplazo de ingresos' },
        { type: 'p', text: 'Entre las razones principales que dan los estadounidenses para tener seguro de vida están el entierro y los gastos finales, dejar una herencia y reemplazar el ingreso de quien trabaja ([LIMRA y Life Happens, 2026](https://www.limra.com/siteassets/newsroom/liam/2026/facts-about-life-insurance.pdf)). Para una familia trabajadora, el reemplazo de ingresos suele ser la cifra más grande. Una forma sencilla de pensarlo:' },
        { type: 'ol', items: [
          '¿Cuántos **años** necesitaría su familia su ingreso? ¿Hasta que el menor termine la escuela, o hasta que su pareja se retire?',
          '¿Qué tendrían que liquidar o seguir pagando: **la hipoteca o la renta, otras deudas, las tarjetas**?',
          '¿Qué viene después: **el cuidado de los niños, la universidad, cuidar a un padre**?',
          'Sume los **gastos finales**.',
          'Reste lo que ya tiene: **cobertura del trabajo, otras pólizas, bienes**.',
        ] },
        { type: 'p', text: 'La calculadora de abajo le da un punto de partida. Después, un agente le ayuda a decidir cuánta cobertura y qué tipo le convienen a su familia. Casi una cuarta parte de los estadounidenses dice que no ha comprado seguro de vida porque no sabe cuánto necesita ni qué tipo comprar; para eso es esta conversación.' },
        { type: 'h2', text: 'Lo que dice la ley de Florida sobre beneficiarios y su póliza' },
        { type: 'ul', items: [
          'Cuando muere un residente de Florida, el seguro de vida **pagadero a un beneficiario nombrado** es para esa persona y, en general, **queda protegido de los reclamos de los acreedores del asegurado**. Si se paga a la **sucesión** del asegurado, pasa a formar parte de ella ([s. 222.13](https://www.flsenate.gov/Laws/Statutes/2026/222.13)).',
          'El **valor de rescate** de una póliza de un residente de Florida también está, en general, protegido de los acreedores ([s. 222.14](https://www.flsenate.gov/Laws/Statutes/2026/222.14)).',
          'Una póliza de vida se vuelve **incontestable después de 2 años vigente** en vida del asegurado, salvo por falta de pago y ciertos beneficios de incapacidad y accidente ([s. 627.455](https://www.flsenate.gov/Laws/Statutes/2026/627.455)). Conteste la solicitud con honestidad y por completo.',
          'Si el asegurado tiene **64 años o más** y la póliza lleva al menos un año vigente, puede nombrar a una **segunda persona** para recibir avisos, y la aseguradora debe enviar aviso por correo al dueño y a esa persona **al menos 21 días antes de que la póliza caduque** por falta de pago ([s. 627.4555](https://www.flsenate.gov/Laws/Statutes/2026/627.4555)). Es una forma sencilla de evitar que la póliza de un padre se caiga por descuido.',
        ] },
        { type: 'callout', title: '¿Ya tiene una póliza?', text: 'Sáquela y lea la página de beneficiarios. Si nombra a un ex, a un hijo menor directamente o a nadie, hable con su agente esta semana. **Envíenos su póliza y revisamos su cobertura.**' },
      ],
      checklistTitle: 'Revise su seguro de vida en diez minutos',
      checklist: [
        '¿Sabe **cuánta** cobertura tiene, incluida la del trabajo?',
        '¿Alcanzaría para **varios años de su ingreso**, más la hipoteca o la renta?',
        '¿Su pareja, incluido **quien cuida la casa**, tiene cobertura?',
        '¿Sus **beneficiarios principales y de respaldo** están al día?',
        '¿Su cobertura **terminaría si deja el trabajo**?',
        'Si su padre o su madre tiene 64 años o más, ¿nombró a una **segunda persona** para los avisos de caducidad?',
      ],
      agentTitle: 'Un agente personal cuando su familia más lo necesita',
      agent: [
        { type: 'p', text: 'M&K Agency es una agencia familiar de Florida City con más de 5,000 clientes en toda la Florida y un equipo de 12 personas que hablan español, inglés y ruso. Nos sentamos con usted, en persona o por teléfono, a calcular lo que su familia necesitaría.' },
        { type: 'p', text: 'Y si pasa lo peor, su familia nos llama. Le ayudamos a encontrar la póliza, reunir los documentos y presentar el reclamo, y le explicamos cada paso en su idioma.' },
      ],
      faqTitle: 'Seguro de vida en Florida: preguntas frecuentes',
      faq: [
        { q: '¿Cuánto seguro de vida necesito?', a: 'Empiece por los años de ingreso que su familia necesitaría, sume la hipoteca o la renta, las deudas, el cuidado de los niños, la universidad y los gastos finales, y reste la cobertura y los bienes que ya tiene. La calculadora de esta página le da un estimado inicial; un agente le ayuda a afinarlo.' },
        { q: '¿Basta con el seguro de vida del trabajo?', a: 'Muchas veces no. La cobertura de grupo suele ser un monto fijo y puede terminar o cambiar si deja el empleo. Muchas familias agregan una póliza individual a su nombre.' },
        { q: '¿El seguro de vida está protegido de los acreedores en Florida?', a: 'En general, sí. Según la s. 222.13 de los Estatutos de Florida, lo que se paga a un beneficiario nombrado está protegido de los reclamos de los acreedores del asegurado, salvo que la póliza o una cesión digan otra cosa; si la póliza le paga a la sucesión, el dinero pasa a ser parte de ella. El valor de rescate también suele estar protegido según la s. 222.14. Para su caso, consulte a un abogado.' },
        { q: '¿Qué diferencia hay entre el seguro a término y el permanente?', a: 'El seguro a término cubre un número fijo de años. El permanente, como el de vida entera o el universal, está pensado para toda la vida mientras se mantenga vigente, y muchas pólizas permanentes acumulan valor en efectivo. Cuál le conviene depende de sus metas.' },
        { q: '¿Me pueden negar un reclamo por algo de la solicitud?', a: 'Según la ley de Florida, una póliza de vida se vuelve incontestable después de 2 años vigente en vida del asegurado, con algunas excepciones como la falta de pago. Antes de eso, los errores en la solicitud pueden importar, así que conteste todo con honestidad.' },
        { q: '¿Ayudarán a mi familia con el reclamo?', a: 'Sí. Su familia puede llamarnos o escribirnos por WhatsApp. Un agente licenciado le ayuda a presentar el reclamo y le explica cada paso en español, inglés o ruso.' },
      ],
      related: [
        { path: '/protect', label: 'Guías de protección para su familia: carro, casa y vida' },
        { path: '/umbrella-insurance-florida-city', label: 'Seguro umbrella: más protección de responsabilidad civil' },
      ],
      sources: srcList('es', [...KEYS]),
    },
    ru: {
      metaTitle: 'Страхование жизни во Флориде: защита дохода семьи',
      metaDesc: 'Сколько страховки жизни нужно семье во Флориде? Замена дохода, полис от работы, выгодоприобретатели и закон Флориды — с местным агентом, на русском.',
      breadcrumb: 'Страхование жизни во Флориде',
      kicker: 'Страхование жизни · Вся Флорида',
      h1a: 'Страхование жизни во Флориде:',
      h1b: 'чтобы семья сохранила дом и планы, если ваша зарплата перестанет приходить.',
      answer: 'Страхование жизни заменяет доход, который семья потеряет, если вас не станет. Почти половина американцев говорит, что их семья не смогла бы оплачивать счета **уже через полгода** после смерти главного кормильца. Личный агент поможет понять, какая сумма нужна вашей семье, правильно указать **выгодоприобретателей** и поддержит близких при выплате.',
      serviceType: 'Страхование жизни',
      leadLabel: 'Страхование жизни',
      intro: [
        { type: 'p', text: 'О страховании жизни многие задумываются на похоронах. Правильное время — сейчас, пока выбор ещё за вами. Настоящий вопрос не «нужен ли мне полис», а «если завтра моя зарплата перестанет приходить, сколько продержится моя семья?»' },
        { type: 'p', text: 'На этой странице — простыми словами об этом вопросе: какой доход нужно заменить, почему страховки от работы может не хватить, как по закону Флориды работают выгодоприобретатели и что мы делаем, когда семье нужна помощь.' },
      ],
      factsTitle: 'Страхование жизни в США: что говорят цифры',
      facts: [
        { value: '47%', text: 'взрослых американцев говорят, что им было бы трудно оплачивать расходы уже в течение 6 месяцев после смерти главного кормильца.', source: u('limra2026') },
        { value: '29%', text: 'говорят, что их семья оставалась бы финансово устойчивой дольше 2 лет, если бы не стало главного кормильца.', source: u('limra2026') },
        { value: '38%', text: 'взрослых — около 92 миллионов человек — говорят, что им нужна страховка жизни или нужно больше.', source: u('limra2026') },
        { value: '47%', text: 'тех, у кого есть страховка жизни, получают её через работу. Такое покрытие привязано к месту работы.', source: u('limra2026') },
      ],
      figureAlt: 'Инфографика. Замена дохода: сложите годы, на которые семье понадобится ваш доход, ипотеку или аренду, долги, детский сад и колледж, расходы на похороны; вычтите покрытие и активы, которые уже есть. Разница — это дыра, которую может закрыть страхование жизни. Суммы и тип полиса зависят от семьи и от полиса.',
      figureCaption: 'Простой способ прикинуть, сколько покрытия нужно семье. Это оценка, а не рекомендация.',
      gapsTitle: 'Где семьи во Флориде остаются без защиты',
      gaps: [
        { h: 'Только страховка от работы', p: 'Групповой полис работодателя — обычно фиксированная сумма, и при увольнении он может закончиться или измениться. Узнайте, можно ли его продлить или перевести на себя.' },
        { h: 'У того, кто дома с детьми, страховки нет', p: 'Если не станет родителя, который ведёт дом, семье придётся платить за присмотр за детьми, поездки и всю домашнюю работу.' },
        { h: 'Устаревшие выгодоприобретатели', p: 'Брак, развод или рождение ребёнка — и в полисе указан не тот человек или никто. Если полис выплачивается в наследственную массу, деньги могут пройти через суд по наследству (probate).' },
      ],
      coverageTitle: 'О каких вариантах страхования жизни спросить',
      coverage: [
        { h: 'Срочное страхование (term)', p: 'Покрытие на определённое число лет — например, пока растут дети или пока не выплачена ипотека.' },
        { h: 'Пожизненное страхование (whole или universal)', p: 'Покрытие на всю жизнь, пока полис действует. Многие пожизненные полисы накапливают выкупную стоимость.' },
        { h: 'Дополнительные опции (riders)', p: 'Например, покрытие ребёнка, освобождение от взносов при инвалидности или доступ к части выплаты при неизлечимой болезни — там, где это предлагается.' },
        { h: 'Покрытие расходов на похороны', p: 'Небольшой полис на похороны и последние расходы, чтобы семье не пришлось платить самой.' },
        { h: 'Полис вне работы', p: 'Индивидуальный полис на ваше имя, который остаётся с вами при смене работы.' },
        { h: 'Планирование выгодоприобретателей', p: 'Основные и запасные выгодоприобретатели и как быть с несовершеннолетними детьми — вместе с агентом.' },
      ],
      coverageNote: 'Это общие описания. Наличие, условия и исключения зависят от полиса и андеррайтинга.',
      body: [
        { type: 'h2', text: 'Начните с замены дохода' },
        { type: 'p', text: 'Среди главных причин, по которым американцы покупают страхование жизни, — похороны и последние расходы, наследство и замена дохода того, кто работает ([LIMRA и Life Happens, 2026](https://www.limra.com/siteassets/newsroom/liam/2026/facts-about-life-insurance.pdf)). Для работающей семьи замена дохода обычно и есть самая большая сумма. Простой способ прикинуть:' },
        { type: 'ol', items: [
          'На сколько **лет** семье понадобится ваш доход? Пока младший не окончит школу или пока супруг(а) не выйдет на пенсию?',
          'Что придётся закрыть или продолжать платить: **ипотеку или аренду, другие долги, кредитные карты**?',
          'Что впереди: **детский сад, колледж, уход за родителями**?',
          'Добавьте **расходы на похороны**.',
          'Вычтите то, что уже есть: **страховку от работы, другие полисы, активы**.',
        ] },
        { type: 'p', text: 'Калькулятор ниже даст отправную точку. Дальше агент поможет решить, какая сумма и какой тип полиса подходят вашей семье. Почти четверть американцев говорят, что не купили страховку жизни, потому что не знают, сколько им нужно и какой тип выбрать, — именно для этого и нужен разговор с агентом.' },
        { type: 'h2', text: 'Что закон Флориды говорит о выгодоприобретателях и полисе' },
        { type: 'ul', items: [
          'Когда умирает житель Флориды, страховка жизни, **выплачиваемая указанному выгодоприобретателю**, достаётся этому человеку и, как правило, **защищена от требований по долгам застрахованного**. Если выплата идёт в **наследственную массу**, деньги становятся её частью ([ст. 222.13](https://www.flsenate.gov/Laws/Statutes/2026/222.13)).',
          '**Выкупная стоимость** полиса жителя Флориды тоже, как правило, защищена от взыскания по долгам ([ст. 222.14](https://www.flsenate.gov/Laws/Statutes/2026/222.14)).',
          'Полис страхования жизни становится **неоспоримым после 2 лет действия** при жизни застрахованного, кроме случаев неуплаты и некоторых выплат по инвалидности и несчастному случаю ([ст. 627.455](https://www.flsenate.gov/Laws/Statutes/2026/627.455)). Отвечайте на вопросы заявления честно и полностью.',
          'Если застрахованному **64 года или больше** и полис действует не меньше года, можно указать **второго человека** для уведомлений, и страховая обязана отправить письмо владельцу и этому человеку **не позднее чем за 21 день до прекращения полиса** за неуплату ([ст. 627.4555](https://www.flsenate.gov/Laws/Statutes/2026/627.4555)). Простой способ не дать полису родителей прекратиться по случайности.',
        ] },
        { type: 'callout', title: 'Полис уже есть?', text: 'Достаньте его и прочитайте страницу о выгодоприобретателях. Если там бывший супруг, несовершеннолетний ребёнок напрямую или никто — поговорите с агентом на этой неделе. **Пришлите полис — мы проверим ваше покрытие.**' },
      ],
      checklistTitle: 'Проверка страхования жизни за десять минут',
      checklist: [
        'Знаете ли вы, **на какую сумму** вы застрахованы, включая страховку от работы?',
        'Хватит ли её на **несколько лет вашего дохода** плюс ипотеку или аренду?',
        'Застрахован(а) ли супруг(а), в том числе **тот, кто ведёт дом**?',
        'Актуальны ли **основные и запасные выгодоприобретатели**?',
        'Закончится ли покрытие, **если вы уйдёте с работы**?',
        'Если родителям 64 года или больше, указали ли они **второго человека** для уведомлений о прекращении полиса?',
      ],
      agentTitle: 'Личный агент, когда семье это нужнее всего',
      agent: [
        { type: 'p', text: 'M&K Agency — семейное агентство во Флорида-Сити: больше 5 000 клиентов по всей Флориде и команда из 12 человек, которые говорят по-русски, по-английски и по-испански. Мы сядем с вами — в офисе или по телефону — и посчитаем, что понадобится вашей семье.' },
        { type: 'p', text: 'А если случится худшее, ваша семья звонит нам. Поможем найти полис, собрать документы и подать заявление на выплату и объясним каждый шаг на родном языке.' },
      ],
      faqTitle: 'Страхование жизни во Флориде: частые вопросы',
      faq: [
        { q: 'Сколько страховки жизни мне нужно?', a: 'Начните с того, на сколько лет семье понадобится ваш доход, добавьте ипотеку или аренду, долги, детский сад, колледж и расходы на похороны и вычтите покрытие и активы, которые уже есть. Калькулятор на этой странице даст первую оценку, а агент поможет её уточнить.' },
        { q: 'Хватит ли страховки жизни от работы?', a: 'Часто нет. Групповое покрытие обычно — фиксированная сумма, и при увольнении оно может закончиться или измениться. Многие семьи добавляют индивидуальный полис на своё имя.' },
        { q: 'Защищена ли страховка жизни от долгов во Флориде?', a: 'Как правило, да. По ст. 222.13 Законов Флориды выплата указанному выгодоприобретателю защищена от требований по долгам застрахованного, если полис или уступка прав не предусматривают иное; если полис выплачивается в наследственную массу, деньги становятся её частью. Выкупная стоимость тоже, как правило, защищена по ст. 222.14. По своей ситуации посоветуйтесь с юристом.' },
        { q: 'Чем срочное страхование отличается от пожизненного?', a: 'Срочное покрывает определённое число лет. Пожизненное — например, whole или universal life — рассчитано на всю жизнь, пока полис действует, и многие такие полисы накапливают выкупную стоимость. Что подойдёт, зависит от ваших целей.' },
        { q: 'Может ли страховая отказать в выплате из-за заявления?', a: 'По закону Флориды полис страхования жизни становится неоспоримым после 2 лет действия при жизни застрахованного, с некоторыми исключениями, например при неуплате. До этого неточности в заявлении могут иметь значение, поэтому отвечайте на все вопросы честно.' },
        { q: 'Поможете ли вы моей семье с выплатой?', a: 'Да. Семья может позвонить нам или написать в WhatsApp. Лицензированный агент поможет подать заявление на выплату и объяснит каждый шаг по-русски, по-английски или по-испански.' },
      ],
      related: [
        { path: '/protect', label: 'Гиды по защите семьи: машина, дом и жизнь' },
        { path: '/umbrella-insurance-florida-city', label: 'Umbrella: дополнительная защита ответственности' },
      ],
      sources: srcList('ru', [...KEYS]),
    },
  },
};
