import type { RecPage } from './types';
import { srcList, u } from './sources';

// Upgrades the existing /motorcycle-insurance-florida-city page (same URL).
// Facts: s. 316.211 and FLHSMV helmet exemption page; s. 627.732 + FLHSMV
// insurance page (PIP/PDL = 4+ wheels); NHTSA DOT HS 813 732 (2023 data: 28x per
// mile, Florida 668 motorcyclist deaths); III/IRC 2023 (20.6% uninsured in FL);
// s. 324.021(7) and 324.051 (financial responsibility after a crash).
const KEYS = ['s316_211', 'flhsmvHelmet', 's627_732', 'flhsmvInsurance', 'nhtsaMoto', 'iiiUninsured', 's324_021', 's324_051', 's627_727', 'flhsmvEndorse'] as const;

export const MOTORCYCLE: RecPage = {
  line: 'motorcycle',
  path: '/motorcycle-insurance-florida-city',
  leadValue: 'Motorcycle',
  leadSource: 'rec-motorcycle',
  articleSlug: 'florida-motorcycle-helmet-law-medical-coverage',
  productSlug: 'motorcycle-insurance',
  published: '2026-10-03',
  modified: '2026-10-03',
  copy: {
    en: {
      metaTitle: 'Motorcycle Insurance in Florida | M&K Agency',
      metaDesc: 'Florida riders have no PIP on a bike. Learn the helmet rule, uninsured-driver risk and the coverage gaps to close, with a local agent. EN/ES/RU.',
      breadcrumb: 'Motorcycle insurance in Florida',
      kicker: 'Motorcycle insurance · All of Florida',
      h1a: 'Motorcycle insurance in Florida:',
      h1b: 'protect your body, your bike and your paycheck.',
      answer: 'On a motorcycle in Florida you have **no PIP** for your own injuries, and about 1 in 5 drivers on the road has no insurance. The right policy is built around those two gaps. We check yours and explain it in your language.',
      serviceType: 'Motorcycle insurance',
      leadLabel: 'Motorcycle',
      intro: [
        { type: 'p', text: 'A car crash and a motorcycle crash are not the same event. In a car, Florida’s Personal Injury Protection (PIP) pays part of your medical bills no matter who caused the crash. On a motorcycle, it doesn’t: Florida’s PIP law is written for vehicles with **four or more wheels**. The state agency that handles licenses even warns that PIP on your car policy is not enough for the rider or the passenger on a bike.' },
        { type: 'p', text: 'So the questions that matter for a Florida rider are simple. If you get hurt, what pays your medical bills and your lost income? If the driver who hits you has no insurance, what then? If you hurt someone else, what protects what you own? This page walks through each one in plain words, with links to the Florida law behind it.' },
      ],
      factsTitle: 'Florida riders: the numbers behind the gaps',
      facts: [
        { value: '0', text: 'PIP for you on a motorcycle. Florida PIP and PDL rules apply to vehicles with four or more wheels.', source: u('s627_732') },
        { value: '$10,000', text: 'in medical benefits is the minimum insurance a rider 21 or older needs to legally ride without a helmet.', source: u('s316_211') },
        { value: '20.6%', text: 'of Florida drivers were uninsured in 2023, about 1 in 5 (Insurance Research Council estimate).', source: u('iiiUninsured') },
        { value: '668', text: 'motorcyclists died in Florida traffic crashes in 2023. Per mile, riders were almost 28 times as likely to die as car occupants.', source: u('nhtsaMoto') },
      ],
      figureAlt: 'Infographic. A rider in a crash with an uninsured driver: PIP pays nothing for the rider, the other driver has no insurance, and the medical bills and lost paychecks are left. Medical payments and uninsured motorist coverage on the rider’s own policy can help, up to the limits.',
      figureCaption: 'Illustration with example situations. What pays depends on the coverages and limits on your policy.',
      gapsTitle: 'Where Florida riders get caught short',
      gaps: [
        { h: 'Your own injuries', p: 'With no PIP on the bike, health insurance deductibles, copays and lost work can land on you. A long recovery can mean months without a paycheck.' },
        { h: 'The other driver has no insurance', p: 'Florida doesn’t require most drivers to carry bodily injury liability. If one of them hits you, your own uninsured motorist coverage may be the only source that pays for your injuries.' },
        { h: 'You hurt someone else', p: 'If you cause a crash, the other person can come after what you own and your future income. Florida can also suspend your license and registration after a crash if you can’t show you were able to pay for damages.' },
      ],
      coverageTitle: 'Coverage to ask about on a Florida motorcycle policy',
      coverage: [
        { h: 'Bodily injury and property damage liability', p: 'Pays for injuries and damage you cause to others, up to your limits, and for a legal defense if you are sued.' },
        { h: 'Uninsured / underinsured motorist', p: 'Helps pay for your injuries, lost income and pain when the at-fault driver has no insurance or not enough.' },
        { h: 'Medical payments', p: 'Helps with medical bills for you and, on many policies, your passenger after a crash, regardless of fault.' },
        { h: 'Collision and comprehensive', p: 'Physical damage to your bike from a crash, theft, a fallen tree, fire or a flood.' },
        { h: 'Accessories, custom parts and riding gear', p: 'Saddlebags, custom paint, exhausts, helmets and jackets are often limited unless they are listed or added.' },
        { h: 'Roadside help and towing', p: 'A flat or a dead battery on a two-lane road needs a tow built for two wheels.' },
      ],
      coverageNote: 'These are general descriptions. Availability, limits and exclusions depend on the policy.',
      body: [
        { type: 'h2', text: 'Florida’s helmet rule and the $10,000 medical benefits requirement' },
        { type: 'p', text: 'Florida law requires every motorcycle rider to wear eye protection and a helmet that meets the federal safety standard. There is one exception: a rider **21 or older** may ride without a helmet **only if covered by an insurance policy with at least $10,000 in medical benefits** for motorcycle crash injuries ([s. 316.211](https://www.flsenate.gov/Laws/Statutes/2026/316.211)).' },
        { type: 'p', text: 'FLHSMV tells police to accept a current health insurance card or limited motorcycle medical coverage as proof, and it says plainly that **PIP on a car policy is not enough** for the rider or the passenger ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/helmet-exemption/)). Keep in mind that $10,000 is a legal minimum, not a measure of what a serious crash really costs.' },
        { type: 'h2', text: 'Why uninsured motorist coverage matters so much for riders' },
        { type: 'p', text: 'To register a car in Florida, an owner has to show only PIP and property damage liability ([FLHSMV](https://www.flhsmv.gov/insurance/)). Bodily injury liability, the coverage that pays for injuries a driver causes, is not required for most drivers. When a car turns left in front of a bike, the driver may have nothing to pay your hospital bill.' },
        { type: 'p', text: '**Uninsured/underinsured motorist (UM)** coverage on your own policy is designed for that moment. It can help pay medical bills, lost wages and pain and suffering, up to your limit. Florida’s UM law sets out how this coverage is offered and how it can be rejected in writing ([s. 627.727](https://www.flsenate.gov/Laws/Statutes/2026/627.727)), so check your declarations page to see whether you have it on the bike.' },
        { type: 'h2', text: 'If you cause the crash: Florida’s Financial Responsibility Law' },
        { type: 'p', text: 'Even though PIP doesn’t apply to motorcycles, Florida’s Financial Responsibility Law does. After certain crashes, the state can suspend the license and registrations of a driver who can’t show he or she was able to pay for damages, for example with a liability policy ([s. 324.051](https://www.flsenate.gov/Laws/Statutes/2026/324.051)). The proof amounts are $10,000 for one person’s injuries, $20,000 per crash and $10,000 for property damage ([s. 324.021](https://www.flsenate.gov/Laws/Statutes/2026/324.021)). Those are minimums; a serious injury claim can be far larger, which is why many riders look at higher limits and an umbrella policy.' },
        { type: 'callout', title: 'Get the endorsement first', text: 'To ride a motorcycle over 50 cc on Florida roads you need a motorcycle endorsement or a motorcycle-only license, which starts with the Basic RiderCourse ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/)). Tell your agent about any rider courses you take.' },
      ],
      checklistTitle: 'Five-minute check of your motorcycle policy',
      checklist: [
        'Find your declarations page and look for **uninsured motorist** on the bike, not just on your car.',
        'See whether you have **medical payments** coverage, and how much.',
        'If you ride without a helmet, keep proof of **at least $10,000 in medical benefits** with you.',
        'Check your **liability limits** against what you own and what you earn.',
        'List your **custom parts, accessories and gear** so they are counted.',
        'Make sure every person who rides your bike is a **listed rider** if the policy requires it.',
      ],
      agentTitle: 'A personal agent when it counts: at claim time',
      agent: [
        { type: 'p', text: 'M&K Agency is a family-owned agency in Florida City with more than 5,000 clients across Florida and a team of 12 who speak English, Spanish and Russian. You talk to the same people before and after a crash.' },
        { type: 'p', text: 'If you go down, call us. We help you report the claim, explain what your policy pays for your bike, your medical bills and your lost income, and stay with you until it is settled. **Send us your policy and we’ll check your coverage.**' },
      ],
      faqTitle: 'Florida motorcycle insurance: common questions',
      faq: [
        { q: 'Is motorcycle insurance required in Florida?', a: 'Florida’s PIP and property damage requirements for registration apply to vehicles with four or more wheels, so they don’t cover motorcycles. But Florida’s Financial Responsibility Law still applies: after certain crashes, you can lose your license and registration if you can’t show you were able to pay for damages. A rider 21 or older who rides without a helmet must also have at least $10,000 in medical benefits coverage.' },
        { q: 'Does my car’s PIP cover me on my motorcycle?', a: 'No. FLHSMV says PIP under a personal car policy is not enough for either the operator or the passenger on a motorcycle. Medical payments coverage, health insurance and uninsured motorist coverage are the usual ways riders protect themselves.' },
        { q: 'Can I ride without a helmet in Florida?', a: 'Only if you are 21 or older and covered by an insurance policy with at least $10,000 in medical benefits for motorcycle crash injuries. Eye protection is still required. Riders under 21 must always wear one.' },
        { q: 'What happens if an uninsured driver hits me on my bike?', a: 'If the driver has no bodily injury coverage, your own uninsured motorist coverage, if you carry it, can help pay your medical bills, lost wages and pain and suffering, up to your limit. Without it, you may be left with your health insurance and a lawsuit against someone who may not be able to pay.' },
        { q: 'Are my helmet, jacket and custom parts covered?', a: 'It depends on the policy. Many policies limit coverage for accessories, custom parts and gear unless they are listed or added. Tell us what you have added to the bike and we will check how it is covered.' },
        { q: 'Do you help with motorcycle claims?', a: 'Yes. Call us or message us on WhatsApp after a crash. A licensed agent helps you report the claim and explains each step in English, Spanish or Russian.' },
      ],
      related: [
        { path: '/slingshot-autocycle-insurance-florida', label: 'Slingshot and autocycle insurance in Florida' },
        { path: '/umbrella-insurance-florida-city', label: 'Umbrella insurance: extra liability protection' },
        { path: '/blog/uninsured-motorist-coverage-florida', label: 'Uninsured motorist coverage in Florida, explained' },
      ],
      sources: srcList('en', [...KEYS]),
    },
    es: {
      metaTitle: 'Seguro de Motocicleta en Florida | M&K Agency',
      metaDesc: 'En moto no tiene PIP en Florida. Conozca la regla del casco, el riesgo de conductores sin seguro y los huecos de cobertura, con un agente local.',
      breadcrumb: 'Seguro de motocicleta en Florida',
      kicker: 'Seguro de motocicleta · Toda la Florida',
      h1a: 'Seguro de motocicleta en Florida:',
      h1b: 'proteja su cuerpo, su moto y su sueldo.',
      answer: 'En moto, en Florida usted **no tiene PIP** para sus propias lesiones, y más o menos 1 de cada 5 conductores no tiene seguro. Una buena póliza se arma pensando en esos dos huecos. Revisamos la suya y se la explicamos en español.',
      serviceType: 'Seguro de motocicleta',
      leadLabel: 'Motocicleta',
      intro: [
        { type: 'p', text: 'Un choque en carro y una caída en moto no son lo mismo. En el carro, el PIP (Protección contra Lesiones Personales) paga parte de sus gastos médicos, sin importar quién tuvo la culpa. En la moto, no: la ley de PIP de Florida está escrita para vehículos de **cuatro ruedas o más**. La misma agencia estatal que emite las licencias advierte que el PIP de la póliza del carro no alcanza ni para el conductor ni para el pasajero de una moto.' },
        { type: 'p', text: 'Por eso, las preguntas que importan son sencillas. Si usted se lesiona, ¿quién paga los médicos y el sueldo que deja de ganar? Si el que lo choca no tiene seguro, ¿qué pasa? Si usted lesiona a otra persona, ¿qué protege su patrimonio? Aquí respondemos cada una en palabras claras, con enlaces a la ley de Florida.' },
      ],
      factsTitle: 'Motociclistas en Florida: las cifras detrás de los huecos',
      facts: [
        { value: '0', text: 'PIP para usted en la moto. Las reglas de PIP y PDL de Florida aplican a vehículos de cuatro ruedas o más.', source: u('s627_732') },
        { value: '$10,000', text: 'en beneficios médicos es el seguro mínimo que necesita un motociclista de 21 años o más para andar sin casco legalmente.', source: u('s316_211') },
        { value: '20.6%', text: 'de los conductores de Florida no tenía seguro en 2023, casi 1 de cada 5 (estimación del Insurance Research Council).', source: u('iiiUninsured') },
        { value: '668', text: 'motociclistas murieron en las vías de Florida en 2023. Por milla recorrida, el riesgo de morir fue casi 28 veces el de quien va en carro.', source: u('nhtsaMoto') },
      ],
      figureAlt: 'Infografía. Un motociclista choca con un conductor sin seguro: el PIP no le paga nada al motociclista, el otro conductor no tiene seguro y quedan las facturas médicas y el sueldo perdido. Los pagos médicos y la cobertura de conductor sin seguro de su propia póliza pueden ayudar, hasta sus límites.',
      figureCaption: 'Ilustración con situaciones de ejemplo. Lo que se paga depende de las coberturas y límites de su póliza.',
      gapsTitle: 'Dónde se quedan cortos los motociclistas en Florida',
      gaps: [
        { h: 'Sus propias lesiones', p: 'Sin PIP en la moto, los deducibles y copagos del seguro médico y los días sin trabajar pueden caer sobre usted. Una recuperación larga puede significar meses sin cobrar.' },
        { h: 'El otro conductor no tiene seguro', p: 'En Florida la mayoría de los conductores no está obligada a tener responsabilidad civil por lesiones. Si uno de ellos lo choca, su propia cobertura de conductor sin seguro puede ser lo único que pague sus lesiones.' },
        { h: 'Usted lesiona a otra persona', p: 'Si usted causa el choque, la otra persona puede reclamar su patrimonio y sus ingresos futuros. Además, Florida puede suspenderle la licencia y el registro si no demuestra que podía pagar los daños.' },
      ],
      coverageTitle: 'Coberturas que conviene preguntar en una póliza de moto en Florida',
      coverage: [
        { h: 'Responsabilidad civil por lesiones y daños', p: 'Paga las lesiones y los daños que usted cause a otros, hasta sus límites, y su defensa legal si lo demandan.' },
        { h: 'Conductor sin seguro o con seguro insuficiente (UM)', p: 'Ayuda a pagar sus lesiones, el sueldo perdido y el dolor cuando el culpable no tiene seguro o tiene muy poco.' },
        { h: 'Pagos médicos', p: 'Ayuda con los gastos médicos suyos y, en muchas pólizas, de su pasajero después de un choque, sin importar la culpa.' },
        { h: 'Choque y cobertura amplia', p: 'Daños a su moto por un choque, robo, un árbol caído, incendio o inundación.' },
        { h: 'Accesorios, piezas personalizadas y equipo', p: 'Alforjas, pintura personalizada, escapes, cascos y chaquetas suelen tener límites si no se declaran o se agregan.' },
        { h: 'Asistencia en la vía y grúa', p: 'Una llanta ponchada o una batería muerta en una carretera de dos carriles necesita una grúa preparada para motos.' },
      ],
      coverageNote: 'Son descripciones generales. La disponibilidad, los límites y las exclusiones dependen de la póliza.',
      body: [
        { type: 'h2', text: 'La regla del casco en Florida y el requisito de $10,000 en beneficios médicos' },
        { type: 'p', text: 'La ley de Florida exige que todo motociclista use protección para los ojos y un casco que cumpla la norma federal. Hay una sola excepción: quien tenga **21 años o más** puede andar sin casco **solo si tiene un seguro con al menos $10,000 en beneficios médicos** por lesiones en accidentes de moto ([s. 316.211](https://www.flsenate.gov/Laws/Statutes/2026/316.211)).' },
        { type: 'p', text: 'El FLHSMV indica a la policía que acepte como prueba una tarjeta vigente de seguro médico o una cobertura médica limitada para motos, y aclara que **el PIP de la póliza del carro no es suficiente** ni para el conductor ni para el pasajero ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/helmet-exemption/)). Recuerde: $10,000 es un mínimo legal, no lo que de verdad cuesta un accidente grave.' },
        { type: 'h2', text: 'Por qué la cobertura de conductor sin seguro es tan importante en moto' },
        { type: 'p', text: 'Para registrar un carro en Florida, el dueño solo tiene que demostrar PIP y responsabilidad por daños a la propiedad ([FLHSMV](https://www.flhsmv.gov/insurance/)). La responsabilidad civil por lesiones, la que paga las lesiones que un conductor causa, no es obligatoria para la mayoría. Cuando un carro dobla a la izquierda frente a una moto, puede que ese conductor no tenga con qué pagar su cuenta del hospital.' },
        { type: 'p', text: 'La **cobertura de conductor sin seguro o con seguro insuficiente (UM)** de su propia póliza está pensada para ese momento. Puede ayudar a pagar gastos médicos, sueldo perdido y dolor y sufrimiento, hasta su límite. La ley de UM de Florida explica cómo se ofrece y cómo se puede rechazar por escrito ([s. 627.727](https://www.flsenate.gov/Laws/Statutes/2026/627.727)); revise su página de declaraciones para ver si la tiene en la moto.' },
        { type: 'h2', text: 'Si usted causa el choque: la Ley de Responsabilidad Financiera' },
        { type: 'p', text: 'Aunque el PIP no aplica a las motos, la Ley de Responsabilidad Financiera de Florida sí. Después de ciertos choques, el estado puede suspender la licencia y los registros de quien no demuestre que podía pagar los daños, por ejemplo con una póliza de responsabilidad civil ([s. 324.051](https://www.flsenate.gov/Laws/Statutes/2026/324.051)). Los montos de prueba son $10,000 por las lesiones de una persona, $20,000 por choque y $10,000 por daños a la propiedad ([s. 324.021](https://www.flsenate.gov/Laws/Statutes/2026/324.021)). Son mínimos; un reclamo por lesiones graves puede ser mucho mayor, y por eso muchos motociclistas consideran límites más altos y una póliza umbrella.' },
        { type: 'callout', title: 'Primero, el endoso', text: 'Para manejar una moto de más de 50 cc en Florida necesita el endoso de motocicleta o una licencia solo para moto, y el primer paso es el curso Basic RiderCourse ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/)). Avísele a su agente de los cursos que haga.' },
      ],
      checklistTitle: 'Revise su póliza de moto en cinco minutos',
      checklist: [
        'Busque su página de declaraciones y confirme que tiene **conductor sin seguro (UM)** en la moto, no solo en el carro.',
        'Vea si tiene **pagos médicos** y por cuánto.',
        'Si anda sin casco, lleve prueba de **al menos $10,000 en beneficios médicos**.',
        'Compare sus **límites de responsabilidad civil** con lo que tiene y lo que gana.',
        'Haga una lista de sus **accesorios, piezas personalizadas y equipo** para que queden incluidos.',
        'Asegúrese de que toda persona que maneje su moto esté **en la póliza**, si la póliza lo exige.',
      ],
      agentTitle: 'Un agente personal cuando más importa: en el reclamo',
      agent: [
        { type: 'p', text: 'M&K Agency es una agencia familiar de Florida City con más de 5,000 clientes en toda la Florida y un equipo de 12 personas que hablan español, inglés y ruso. Antes y después de un accidente, usted habla con las mismas personas.' },
        { type: 'p', text: 'Si se cae, llámenos. Le ayudamos a reportar el reclamo, le explicamos qué paga su póliza por la moto, los médicos y el sueldo perdido, y lo acompañamos hasta el final. **Envíenos su póliza y revisamos su cobertura.**' },
      ],
      faqTitle: 'Seguro de moto en Florida: preguntas frecuentes',
      faq: [
        { q: '¿Es obligatorio el seguro de motocicleta en Florida?', a: 'Los requisitos de PIP y daños a la propiedad para registrar un vehículo en Florida aplican a vehículos de cuatro ruedas o más, así que no cubren las motos. Pero la Ley de Responsabilidad Financiera sí aplica: después de ciertos choques, puede perder la licencia y el registro si no demuestra que podía pagar los daños. Además, quien tenga 21 años o más y ande sin casco debe tener al menos $10,000 en beneficios médicos.' },
        { q: '¿El PIP de mi carro me cubre en la moto?', a: 'No. El FLHSMV dice que el PIP de una póliza de carro personal no es suficiente ni para el conductor ni para el pasajero de una moto. Los pagos médicos, el seguro de salud y la cobertura de conductor sin seguro son las formas habituales de protegerse.' },
        { q: '¿Puedo andar sin casco en Florida?', a: 'Solo si tiene 21 años o más y está cubierto por un seguro con al menos $10,000 en beneficios médicos por lesiones en moto. La protección para los ojos sigue siendo obligatoria. Los menores de 21 deben usar casco.' },
        { q: '¿Qué pasa si me choca un conductor sin seguro cuando voy en moto?', a: 'Si ese conductor no tiene cobertura por lesiones, su propia cobertura de conductor sin seguro, si la tiene, puede ayudar a pagar sus gastos médicos, el sueldo perdido y el dolor y sufrimiento, hasta su límite. Sin ella, puede quedarse solo con su seguro médico y una demanda contra alguien que quizás no pueda pagar.' },
        { q: '¿Están cubiertos mi casco, mi chaqueta y las piezas personalizadas?', a: 'Depende de la póliza. Muchas pólizas limitan la cobertura de accesorios, piezas personalizadas y equipo si no se declaran o se agregan. Cuéntenos qué le ha puesto a la moto y revisamos cómo queda cubierto.' },
        { q: '¿Me ayudan con un reclamo de moto?', a: 'Sí. Llámenos o escríbanos por WhatsApp después del accidente. Un agente licenciado le ayuda a reportar el reclamo y le explica cada paso en español, inglés o ruso.' },
      ],
      related: [
        { path: '/slingshot-autocycle-insurance-florida', label: 'Seguro para Slingshot y autociclos en Florida' },
        { path: '/umbrella-insurance-florida-city', label: 'Seguro umbrella: más protección de responsabilidad civil' },
        { path: '/blog/uninsured-motorist-coverage-florida', label: 'La cobertura de conductor sin seguro en Florida, explicada' },
      ],
      sources: srcList('es', [...KEYS]),
    },
    ru: {
      metaTitle: 'Страховка мотоцикла во Флориде | M&K Agency',
      metaDesc: 'На мотоцикле во Флориде у вас нет PIP. Правило о шлеме, риск водителей без страховки и дыры в покрытии — разбираем с местным агентом по-русски.',
      breadcrumb: 'Страховка мотоцикла во Флориде',
      kicker: 'Страховка мотоцикла · Вся Флорида',
      h1a: 'Страховка мотоцикла во Флориде:',
      h1b: 'защитите себя, байк и свой доход.',
      answer: 'На мотоцикле во Флориде у вас **нет PIP** на собственные травмы, а примерно каждый пятый водитель ездит без страховки. Правильный полис строится вокруг этих двух дыр. Мы проверим ваш и объясним всё по-русски.',
      serviceType: 'Страхование мотоциклов',
      leadLabel: 'Мотоцикл',
      intro: [
        { type: 'p', text: 'Авария на машине и падение с мотоцикла — разные истории. В машине PIP (Personal Injury Protection) оплачивает часть лечения, кто бы ни был виноват. На мотоцикле — нет: закон Флориды о PIP написан для машин с **четырьмя и более колёсами**. Даже FLHSMV, ведомство, которое выдаёт права, прямо предупреждает: PIP из автомобильного полиса не покрывает ни водителя мотоцикла, ни пассажира.' },
        { type: 'p', text: 'Поэтому важных вопросов немного. Если вы травмированы, кто оплатит врачей и потерянную зарплату? Если у того, кто в вас врезался, нет страховки, что тогда? Если пострадал другой человек, что защитит ваши сбережения? Ниже — простые ответы со ссылками на законы Флориды.' },
      ],
      factsTitle: 'Мотоциклисты во Флориде: цифры, из-за которых появляются дыры',
      facts: [
        { value: '0', text: 'PIP для вас на мотоцикле. Требования PIP и PDL во Флориде касаются машин с четырьмя и более колёсами.', source: u('s627_732') },
        { value: '$10 000', text: 'медицинского покрытия — минимум, при котором мотоциклист от 21 года может законно ездить без шлема.', source: u('s316_211') },
        { value: '20,6%', text: 'водителей во Флориде в 2023 году ездили без страховки — почти каждый пятый (оценка Insurance Research Council).', source: u('iiiUninsured') },
        { value: '668', text: 'мотоциклистов погибли на дорогах Флориды в 2023 году. В пересчёте на милю риск погибнуть у них почти в 28 раз выше, чем у тех, кто едет в машине.', source: u('nhtsaMoto') },
      ],
      figureAlt: 'Инфографика. Мотоциклист попадает в аварию с водителем без страховки: PIP ничего не платит мотоциклисту, у виновника страховки нет, остаются счета за лечение и потерянная зарплата. Помочь могут покрытие медицинских расходов и UM в собственном полисе мотоциклиста — в пределах лимитов.',
      figureCaption: 'Иллюстрация с условными ситуациями. Что будет оплачено, зависит от покрытий и лимитов вашего полиса.',
      gapsTitle: 'Где мотоциклисты во Флориде остаются без защиты',
      gaps: [
        { h: 'Ваши собственные травмы', p: 'Без PIP на мотоцикле франшизы и доплаты по медицинской страховке, а также дни без работы ложатся на вас. Долгое восстановление — это месяцы без зарплаты.' },
        { h: 'У виновника нет страховки', p: 'Во Флориде большинство водителей не обязаны иметь страхование ответственности за травмы. Если такой водитель собьёт вас, единственным источником выплаты может оказаться ваше собственное покрытие UM.' },
        { h: 'Пострадал другой человек', p: 'Если аварию устроили вы, пострадавший может претендовать на ваши сбережения и будущие доходы. А штат может приостановить ваши права и регистрацию, если вы не докажете, что могли возместить ущерб.' },
      ],
      coverageTitle: 'О каких покрытиях спросить в полисе на мотоцикл',
      coverage: [
        { h: 'Ответственность за травмы и ущерб имуществу', p: 'Оплачивает травмы и ущерб, которые вы причинили другим, в пределах лимитов, и юридическую защиту, если на вас подали в суд.' },
        { h: 'UM — водитель без страховки или с недостаточной страховкой', p: 'Помогает оплатить ваши травмы, потерянный доход и моральный вред, если у виновника нет страховки или её мало.' },
        { h: 'Медицинские расходы (MedPay)', p: 'Помогает с лечением вас, а во многих полисах и пассажира, после аварии, независимо от вины.' },
        { h: 'Collision и comprehensive', p: 'Ущерб самому мотоциклу: авария, угон, упавшее дерево, пожар или наводнение.' },
        { h: 'Аксессуары, тюнинг и экипировка', p: 'Кофры, аэрография, выхлоп, шлем и куртка часто покрываются ограниченно, если их не указать или не добавить.' },
        { h: 'Помощь на дороге и эвакуатор', p: 'Пробитое колесо или севший аккумулятор на загородной трассе — нужен эвакуатор, который умеет возить мотоциклы.' },
      ],
      coverageNote: 'Это общие описания. Наличие покрытий, лимиты и исключения зависят от конкретного полиса.',
      body: [
        { type: 'h2', text: 'Правило о шлеме и требование $10 000 медицинского покрытия' },
        { type: 'p', text: 'Закон Флориды требует, чтобы каждый мотоциклист носил защиту для глаз и шлем, соответствующий федеральному стандарту. Исключение одно: водитель **от 21 года** может ездить без шлема, **только если у него есть страховка с медицинским покрытием не меньше $10 000** на травмы при аварии на мотоцикле ([ст. 316.211](https://www.flsenate.gov/Laws/Statutes/2026/316.211)).' },
        { type: 'p', text: 'FLHSMV разъясняет полиции, что подтверждением служит действующая карточка медицинской страховки или ограниченное медицинское покрытие для мотоциклистов, и прямо пишет: **PIP из автомобильного полиса для этого не подходит** — ни водителю, ни пассажиру ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/helmet-exemption/)). Помните: $10 000 — это юридический минимум, а не реальная стоимость лечения после серьёзной аварии.' },
        { type: 'h2', text: 'Почему мотоциклисту так важно покрытие UM' },
        { type: 'p', text: 'Чтобы зарегистрировать машину во Флориде, владельцу достаточно показать PIP и страховку ответственности за ущерб имуществу ([FLHSMV](https://www.flhsmv.gov/insurance/)). Страхование ответственности за травмы, которое оплачивает вред здоровью других людей, большинству водителей не обязательно. Когда машина поворачивает налево прямо перед мотоциклом, у её водителя может просто не оказаться, чем оплатить ваш счёт из больницы.' },
        { type: 'p', text: 'Для такого случая и существует **UM (uninsured/underinsured motorist)** в вашем собственном полисе. Оно может оплатить лечение, потерянную зарплату, боль и страдания — в пределах лимита. Закон Флориды об UM описывает, как это покрытие предлагают и как от него письменно отказываются ([ст. 627.727](https://www.flsenate.gov/Laws/Statutes/2026/627.727)). Проверьте страницу деклараций: есть ли UM именно на мотоцикле.' },
        { type: 'h2', text: 'Если виноваты вы: закон о финансовой ответственности' },
        { type: 'p', text: 'PIP к мотоциклам не относится, а вот закон Флориды о финансовой ответственности — относится. После некоторых аварий штат может приостановить права и регистрацию водителя, который не докажет, что был способен возместить ущерб, например полисом ответственности ([ст. 324.051](https://www.flsenate.gov/Laws/Statutes/2026/324.051)). Подтверждаемые суммы — $10 000 за травмы одного человека, $20 000 за аварию и $10 000 за ущерб имуществу ([ст. 324.021](https://www.flsenate.gov/Laws/Statutes/2026/324.021)). Это минимумы: иск за серьёзную травму может быть намного больше, поэтому многие мотоциклисты выбирают лимиты повыше и полис umbrella.' },
        { type: 'callout', title: 'Сначала — мотоциклетная отметка в правах', text: 'Чтобы ездить по дорогам Флориды на мотоцикле больше 50 куб. см, нужна отметка «Motorcycle» в правах или права только на мотоцикл; начинается всё с курса Basic RiderCourse ([FLHSMV](https://www.flhsmv.gov/driver-licenses-id-cards/motorcycle-rider-education-endorsements/)). Скажите агенту, какие курсы вы прошли.' },
      ],
      checklistTitle: 'Проверьте свой полис на мотоцикл за пять минут',
      checklist: [
        'Откройте страницу деклараций и найдите **UM** именно на мотоцикле, а не только на машине.',
        'Посмотрите, есть ли покрытие **медицинских расходов** и на какую сумму.',
        'Если ездите без шлема, держите при себе подтверждение **медицинского покрытия от $10 000**.',
        'Сравните **лимиты ответственности** с тем, что у вас есть и сколько вы зарабатываете.',
        'Составьте список **тюнинга, аксессуаров и экипировки**, чтобы их учли.',
        'Проверьте, что все, кто ездит на вашем мотоцикле, **вписаны в полис**, если полис этого требует.',
      ],
      agentTitle: 'Личный агент, когда это важнее всего: при страховом случае',
      agent: [
        { type: 'p', text: 'M&K Agency — семейное агентство во Флорида-Сити: больше 5 000 клиентов по всей Флориде и команда из 12 человек, которые говорят по-русски, по-английски и по-испански. До аварии и после вы общаетесь с одними и теми же людьми.' },
        { type: 'p', text: 'Если вы упали — звоните. Поможем заявить убыток, объясним, что полис платит за мотоцикл, лечение и потерянный доход, и будем рядом до конца урегулирования. **Пришлите полис — мы проверим ваше покрытие.**' },
      ],
      faqTitle: 'Страховка мотоцикла во Флориде: частые вопросы',
      faq: [
        { q: 'Обязательна ли страховка мотоцикла во Флориде?', a: 'Требования PIP и страховки ущерба имуществу для регистрации касаются машин с четырьмя и более колёсами, поэтому на мотоциклы они не распространяются. Но закон о финансовой ответственности действует: после некоторых аварий можно лишиться прав и регистрации, если не доказать, что вы могли возместить ущерб. Кроме того, мотоциклист от 21 года без шлема обязан иметь медицинское покрытие не меньше $10 000.' },
        { q: 'Покрывает ли меня на мотоцикле PIP от машины?', a: 'Нет. FLHSMV пишет, что PIP из личного автомобильного полиса недостаточен ни для водителя мотоцикла, ни для пассажира. Обычно мотоциклисты защищают себя покрытием медицинских расходов, медицинской страховкой и UM.' },
        { q: 'Можно ли во Флориде ездить без шлема?', a: 'Только если вам 21 год или больше и у вас есть страховка с медицинским покрытием не меньше $10 000 на травмы при аварии на мотоцикле. Защита для глаз всё равно обязательна. Водители до 21 года обязаны ездить в шлеме.' },
        { q: 'Что будет, если в меня на мотоцикле врежется водитель без страховки?', a: 'Если у него нет страховки ответственности за травмы, помочь может ваше собственное покрытие UM, если оно есть: лечение, потерянная зарплата, боль и страдания — в пределах лимита. Без него остаются медицинская страховка и иск к человеку, который, возможно, не сможет заплатить.' },
        { q: 'Покрываются ли шлем, куртка и тюнинг?', a: 'Зависит от полиса. Многие полисы ограничивают покрытие аксессуаров, тюнинга и экипировки, если их не указать или не добавить. Расскажите, что вы поставили на мотоцикл, и мы проверим, как это покрыто.' },
        { q: 'Помогаете ли вы со страховыми случаями по мотоциклу?', a: 'Да. После аварии позвоните или напишите в WhatsApp. Лицензированный агент поможет заявить убыток и объяснит каждый шаг по-русски, по-английски или по-испански.' },
      ],
      related: [
        { path: '/slingshot-autocycle-insurance-florida', label: 'Страховка Slingshot и автоциклов во Флориде' },
        { path: '/umbrella-insurance-florida-city', label: 'Umbrella: дополнительная защита ответственности' },
        { path: '/blog/uninsured-motorist-coverage-florida', label: 'Покрытие UM во Флориде: подробный разбор' },
      ],
      sources: srcList('ru', [...KEYS]),
    },
  },
};
