import type { RecPage } from './types';
import { srcList, u } from './sources';

// Facts: CPSC 2024 OHV report (est. 509,900 ED-treated injuries 2019-2023, ~102,000/yr;
// Florida 107 reported OHV deaths 2019-2021; fractures 29%, head and neck 34% in 2023);
// s. 316.2074 (ATV definition, under-16 helmet + eye protection, crash notice);
// s. 316.2123 (public roads: daytime, unpaved, posted < 35 mph; county options; licensed
// driver or supervised minor; proof of ownership); ss. 317.0003, 317.0006 (OHV titles).
const KEYS = ['cpscOhv', 's316_2074', 's316_2123', 's317_0003', 's317_0006'] as const;

export const OFF_ROAD: RecPage = {
  line: 'off-road',
  path: '/atv-utv-insurance-florida',
  leadValue: 'ATV / UTV / Dirt bike',
  leadSource: 'rec-off-road',
  articleSlug: 'atv-utv-public-roads-florida',
  productSlug: 'off-road-insurance',
  published: '2026-10-03',
  modified: '2026-10-03',
  copy: {
    en: {
      metaTitle: 'ATV, UTV & Dirt Bike Insurance in Florida | M&K Agency',
      metaDesc: 'Florida rules for ATVs, UTVs and dirt bikes: titles, kids and helmets, public roads. Plus the injury and liability gaps to close, with a local agent.',
      breadcrumb: 'ATV, UTV and dirt bike insurance',
      kicker: 'Off-road vehicle insurance · All of Florida',
      h1a: 'ATV, UTV and dirt bike insurance in Florida:',
      h1b: 'for the trail, the ranch and the kids who ride.',
      answer: 'Off-road vehicles flip, collide and throw riders, and the injured person can be a family member or a friend. In Florida these machines need a **title**, follow **special road rules**, and are often **left out of home policies**. We check your coverage and explain it in your language.',
      serviceType: 'Off-road vehicle insurance (ATV, UTV, ROV, dirt bike)',
      leadLabel: 'ATV / UTV / dirt bike',
      intro: [
        { type: 'p', text: 'In South Florida, ATVs and side-by-sides do real work on groves, nurseries and large lots, and they are a weekend ride for families from Homestead to the Panhandle. They are also involved in serious injuries: the most common are fractures and head and neck injuries.' },
        { type: 'p', text: 'Below are the Florida rules every owner should know, the gaps that catch families off guard and the coverage questions to ask, in plain words with links to the law.' },
      ],
      factsTitle: 'Off-road vehicles: what the numbers say',
      facts: [
        { value: '~102,000', text: 'emergency-room injuries a year in the U.S. involved off-highway vehicles (estimated yearly average, 2019 to 2023).', source: u('cpscOhv') },
        { value: '107', text: 'reported off-highway vehicle deaths in Florida from 2019 to 2021, the sixth-highest total of any state.', source: u('cpscOhv') },
        { value: '34%', text: 'of off-highway vehicle injuries treated in emergency rooms in 2023 were to the head and neck; 29% were fractures.', source: u('cpscOhv') },
        { value: '16', text: 'Under this age, every ATV rider in Florida must wear a DOT helmet and eye protection.', source: u('s316_2074') },
      ],
      figureAlt: 'Infographic. Florida off-road basics: off-highway vehicles bought by a Florida resident or used on public lands need a title; riders under 16 wear a helmet and eye protection; ATVs stay off public roads except daytime on unpaved roads with a posted limit under 35 mph, unless the county says otherwise. Liability, medical payments and physical damage coverage can help, depending on the policy.',
      figureCaption: 'Rules from ss. 316.2074, 316.2123 and chapter 317, Florida Statutes. Counties may set different road rules.',
      gapsTitle: 'Where off-road owners get caught short',
      gaps: [
        { h: 'A friend or relative gets hurt', p: 'The injured person may be someone the owner knows: a passenger, a neighbor’s kid, a cousin on a borrowed machine. Liability and medical payments are what usually respond.' },
        { h: 'The home policy stops at the property line', p: 'Many homeowners policies limit or exclude motorized vehicles, especially off your land. Read the section on motor vehicles before you count on it.' },
        { h: 'Theft and storm damage', p: 'ATVs and UTVs are easy to load and steal, and a shed is not a garage in a hurricane. Physical damage coverage is a separate decision.' },
      ],
      coverageTitle: 'Coverage to ask about for an ATV, UTV or dirt bike',
      coverage: [
        { h: 'Liability', p: 'Injuries and damage you or a permitted rider cause to others, up to your limits, plus legal defense.' },
        { h: 'Medical payments', p: 'Helps with medical bills for you and your passengers, regardless of fault.' },
        { h: 'Collision and comprehensive', p: 'Damage to the machine from a rollover or crash, theft, fire, flood or a falling tree.' },
        { h: 'Accessories and added equipment', p: 'Winches, plows, lights, racks and custom parts, if listed or included.' },
        { h: 'Uninsured motorist', p: 'Helps if a driver with no insurance injures you, where the policy offers it.' },
        { h: 'Trailer', p: 'The trailer you haul it on, if included.' },
      ],
      coverageNote: 'These are general descriptions. Availability, limits and exclusions depend on the policy.',
      body: [
        { type: 'h2', text: 'What counts as an off-highway vehicle in Florida' },
        { type: 'p', text: 'Florida groups **ATVs, two-rider ATVs, ROVs (side-by-sides) and off-highway motorcycles (dirt bikes)** as off-highway vehicles when they are used off the roads and are not registered for highway use ([s. 317.0003](https://www.flsenate.gov/Laws/Statutes/2026/317.0003)). For the safety law, an ATV is an off-highway vehicle 55 inches wide or less, weighing 1,500 pounds or less dry, built for recreation on three or more off-road tires ([s. 316.2074](https://www.flsenate.gov/Laws/Statutes/2026/316.2074)).' },
        { type: 'h2', text: 'Titles: yes, your ATV needs one' },
        { type: 'p', text: 'An off-highway vehicle bought by a Florida resident, or owned by a resident and used on Florida’s public lands, must be **titled** under chapter 317. When you sell one, you must hand over the title with the transfer filled in ([s. 317.0006](https://www.flsenate.gov/Laws/Statutes/2026/317.0006)). A title also makes a theft claim much easier to prove.' },
        { type: 'h2', text: 'Kids, helmets and public roads' },
        { type: 'ul', items: [
          'Anyone **under 16** riding or driving an ATV must wear a helmet that meets DOT standards and eye protection ([s. 316.2074](https://www.flsenate.gov/Laws/Statutes/2026/316.2074)).',
          'If a crash kills someone or injures someone who is then treated by a doctor, each ATV operator must give notice of the crash.',
          'ATVs are **not allowed on public roads**, except in the **daytime on an unpaved road with a posted limit under 35 mph** ([s. 316.2123](https://www.flsenate.gov/Laws/Statutes/2026/316.2123)).',
          'A county can vote to opt out of that exception, or to designate specific unpaved roads for daytime ATV use.',
          'Where road use is allowed, the operator must be a **licensed driver**, or a minor under the direct supervision of one, and must show **proof of ownership** if an officer asks.',
        ] },
        { type: 'callout', title: 'Before you lend it', text: 'A borrowed ATV with a passenger is a common setup for a serious injury. Before you hand over the key, check whether your policy covers other riders and passengers.' },
      ],
      checklistTitle: 'A quick check for every off-road vehicle you own',
      checklist: [
        'Is each machine **titled** and listed on a policy, not just on your homeowners?',
        'Does the policy cover **other riders** you allow and **passengers**?',
        'Do you have **medical payments** coverage, and how much?',
        'Are your **liability limits** high enough for an injury claim?',
        'Are **winches, plows, lights and other add-ons** listed?',
        'Is the machine used for **work on a farm or business**? Tell your agent; it can change the coverage you need.',
      ],
      agentTitle: 'A personal agent when it counts: at claim time',
      agent: [
        { type: 'p', text: 'M&K Agency is a family-owned agency in Florida City, in the middle of South Dade’s farm country, with more than 5,000 clients across Florida and a team of 12 who speak English, Spanish and Russian.' },
        { type: 'p', text: 'After a rollover, a theft or a storm, call or message us. We help you report the claim, explain what the policy pays and stay with you until it is settled. **Send us your policy and we’ll check your coverage.**' },
      ],
      faqTitle: 'ATV, UTV and dirt bike insurance in Florida: common questions',
      faq: [
        { q: 'Does my ATV need a title in Florida?', a: 'Yes, in most cases. An off-highway vehicle bought by a Florida resident, or owned by a resident and used on public lands, must be titled under chapter 317, Florida Statutes.' },
        { q: 'Can I ride my ATV on the road in Florida?', a: 'Generally no. The exception is daytime riding on an unpaved road with a posted speed limit under 35 mph, and a county can opt out of it or designate specific unpaved roads. The rider must be a licensed driver or a supervised minor and carry proof of ownership.' },
        { q: 'Does my homeowners policy cover my ATV or UTV?', a: 'Often only in a limited way, and many home policies exclude motorized vehicles away from the residence. Send us your home policy and we will tell you what it says.' },
        { q: 'Do kids need helmets on an ATV in Florida?', a: 'Yes. Anyone under 16 who operates or rides an ATV must wear a helmet that meets DOT standards and eye protection.' },
        { q: 'Is a side-by-side (UTV/ROV) covered the same as an ATV?', a: 'Florida law treats ROVs as off-highway vehicles too, but policies can treat them differently because of size, seating and use. Tell us exactly what you ride and how you use it.' },
        { q: 'Do you help with off-road claims?', a: 'Yes. Call us or message us on WhatsApp. A licensed agent helps you report the claim and explains each step in English, Spanish or Russian.' },
      ],
      related: [
        { path: '/golf-cart-insurance-florida', label: 'Golf cart and LSV insurance in Florida' },
        { path: '/homeowners-insurance-florida-city', label: 'Homeowners insurance in Florida City' },
      ],
      sources: srcList('en', [...KEYS]),
    },
    es: {
      metaTitle: 'Seguro de ATV, UTV y Motos de Tierra en Florida | M&K',
      metaDesc: 'Reglas de Florida para ATV, UTV y motos de tierra: título, niños y casco, vías públicas. Y los huecos de cobertura por lesiones y responsabilidad civil.',
      breadcrumb: 'Seguro de ATV, UTV y motos de tierra',
      kicker: 'Seguro de vehículos todoterreno · Toda la Florida',
      h1a: 'Seguro de ATV, UTV y motos de tierra en Florida:',
      h1b: 'para el trillo, la finca y los niños que montan.',
      answer: 'Los vehículos todoterreno se vuelcan, chocan y tiran al que va encima, y el lesionado puede ser un familiar o un amigo. En Florida necesitan **título**, tienen **reglas especiales para la vía pública** y muchas veces **quedan fuera del seguro de casa**. Revisamos su cobertura y se la explicamos en español.',
      serviceType: 'Seguro de vehículos todoterreno (ATV, UTV, ROV, motos de tierra)',
      leadLabel: 'ATV / UTV / moto de tierra',
      intro: [
        { type: 'p', text: 'En el sur de la Florida, los ATV y los side-by-side trabajan de verdad en fincas, viveros y terrenos grandes, y son el paseo de fin de semana de muchas familias, de Homestead al Panhandle. También están detrás de lesiones serias: las más comunes son fracturas y lesiones de cabeza y cuello.' },
        { type: 'p', text: 'Aquí están las reglas de Florida que todo dueño debe conocer, los huecos que toman por sorpresa a las familias y las preguntas de cobertura que conviene hacer, con palabras claras y enlaces a la ley.' },
      ],
      factsTitle: 'Vehículos todoterreno: lo que dicen las cifras',
      facts: [
        { value: '~102,000', text: 'lesiones al año atendidas en salas de emergencia en EE. UU. involucraron vehículos todoterreno (promedio anual estimado, 2019 a 2023).', source: u('cpscOhv') },
        { value: '107', text: 'muertes reportadas con vehículos todoterreno en Florida de 2019 a 2021, la sexta cifra más alta del país.', source: u('cpscOhv') },
        { value: '34%', text: 'de las lesiones con vehículos todoterreno atendidas en emergencias en 2023 fueron en la cabeza y el cuello; el 29% fueron fracturas.', source: u('cpscOhv') },
        { value: '16', text: 'Antes de esta edad, todo el que monte un ATV en Florida debe usar casco aprobado por el DOT y protección para los ojos.', source: u('s316_2074') },
      ],
      figureAlt: 'Infografía. Lo básico del todoterreno en Florida: los vehículos todoterreno comprados por un residente de Florida o usados en terrenos públicos necesitan título; los menores de 16 años usan casco y protección para los ojos; los ATV no van por la vía pública, salvo de día en caminos sin pavimentar con límite señalizado menor de 35 mph, a menos que el condado decida otra cosa. La responsabilidad civil, los pagos médicos y el daño físico pueden ayudar, según la póliza.',
      figureCaption: 'Reglas de las ss. 316.2074 y 316.2123 y del capítulo 317 de los Estatutos de Florida. Los condados pueden fijar otras reglas para las vías.',
      gapsTitle: 'Dónde se quedan cortos los dueños de todoterrenos',
      gaps: [
        { h: 'Se lesiona un amigo o un familiar', p: 'El lesionado puede ser alguien que el dueño conoce: un pasajero, el hijo del vecino, un primo en una máquina prestada. Normalmente responden la responsabilidad civil y los pagos médicos.' },
        { h: 'El seguro de casa se queda en la cerca', p: 'Muchas pólizas de casa limitan o excluyen los vehículos motorizados, sobre todo fuera de su terreno. Lea la sección de vehículos motorizados antes de contar con ella.' },
        { h: 'Robo y daños por tormenta', p: 'Los ATV y UTV se cargan y se roban con facilidad, y un cobertizo no es un garaje en un huracán. El daño físico es una decisión aparte.' },
      ],
      coverageTitle: 'Coberturas que conviene preguntar para un ATV, UTV o moto de tierra',
      coverage: [
        { h: 'Responsabilidad civil', p: 'Lesiones y daños que usted o alguien con su permiso cause a otros, hasta sus límites, y la defensa legal.' },
        { h: 'Pagos médicos', p: 'Ayuda con los gastos médicos suyos y de sus pasajeros, sin importar la culpa.' },
        { h: 'Choque y cobertura amplia', p: 'Daños a la máquina por vuelco o choque, robo, incendio, inundación o un árbol que cae.' },
        { h: 'Accesorios y equipo agregado', p: 'Winches, palas, luces, parrillas y piezas personalizadas, si se declaran o están incluidos.' },
        { h: 'Conductor sin seguro', p: 'Ayuda si lo lesiona un conductor sin seguro, cuando la póliza la ofrece.' },
        { h: 'Tráiler', p: 'El tráiler en que la transporta, si está incluido.' },
      ],
      coverageNote: 'Son descripciones generales. La disponibilidad, los límites y las exclusiones dependen de la póliza.',
      body: [
        { type: 'h2', text: 'Qué es un vehículo todoterreno según la ley de Florida' },
        { type: 'p', text: 'Florida agrupa los **ATV, los ATV de dos plazas, los ROV (side-by-side) y las motos de tierra (OHM)** como vehículos todoterreno cuando se usan fuera de las vías y no están registrados para la carretera ([s. 317.0003](https://www.flsenate.gov/Laws/Statutes/2026/317.0003)). Para la ley de seguridad, un ATV es un vehículo todoterreno de 55 pulgadas de ancho o menos, de 1,500 libras o menos en seco, hecho para recreación sobre tres o más llantas todoterreno ([s. 316.2074](https://www.flsenate.gov/Laws/Statutes/2026/316.2074)).' },
        { type: 'h2', text: 'Título: sí, su ATV lo necesita' },
        { type: 'p', text: 'Un vehículo todoterreno comprado por un residente de Florida, o que un residente usa en terrenos públicos de Florida, debe tener **título** según el capítulo 317. Al venderlo, hay que entregar el título con la transferencia llena ([s. 317.0006](https://www.flsenate.gov/Laws/Statutes/2026/317.0006)). Además, el título facilita mucho probar un reclamo por robo.' },
        { type: 'h2', text: 'Niños, casco y vías públicas' },
        { type: 'ul', items: [
          'Todo **menor de 16 años** que maneje o vaya en un ATV debe usar casco que cumpla la norma del DOT y protección para los ojos ([s. 316.2074](https://www.flsenate.gov/Laws/Statutes/2026/316.2074)).',
          'Si en un accidente muere alguien o alguien se lesiona y lo atiende un médico, cada conductor de ATV involucrado debe dar aviso del accidente.',
          'Los ATV **no pueden ir por la vía pública**, salvo **de día por un camino sin pavimentar con límite señalizado menor de 35 mph** ([s. 316.2123](https://www.flsenate.gov/Laws/Statutes/2026/316.2123)).',
          'Un condado puede votar para no aplicar esa excepción, o para señalar caminos sin pavimentar específicos para uso de ATV de día.',
          'Donde se permite, quien maneja debe tener **licencia de conducir**, o ser menor bajo supervisión directa de alguien con licencia, y mostrar **prueba de propiedad** si un oficial la pide.',
        ] },
        { type: 'callout', title: 'Antes de prestarlo', text: 'Un ATV prestado con un pasajero es una combinación frecuente en las lesiones graves. Antes de entregar la llave, revise si su póliza cubre a otros conductores y a los pasajeros.' },
      ],
      checklistTitle: 'Revise cada vehículo todoterreno que tenga',
      checklist: [
        '¿Cada máquina tiene **título** y está en una póliza, y no solo en el seguro de casa?',
        '¿La póliza cubre a **otros conductores** que usted autoriza y a los **pasajeros**?',
        '¿Tiene **pagos médicos** y por cuánto?',
        '¿Sus **límites de responsabilidad civil** alcanzan para un reclamo por lesiones?',
        '¿Están declarados los **winches, palas, luces y otros agregados**?',
        '¿La usa para **trabajar en una finca o un negocio**? Dígaselo a su agente; puede cambiar la cobertura que necesita.',
      ],
      agentTitle: 'Un agente personal cuando más importa: en el reclamo',
      agent: [
        { type: 'p', text: 'M&K Agency es una agencia familiar de Florida City, en plena zona agrícola del sur de Miami-Dade, con más de 5,000 clientes en toda la Florida y un equipo de 12 personas que hablan español, inglés y ruso.' },
        { type: 'p', text: 'Después de un vuelco, un robo o una tormenta, llámenos o escríbanos. Le ayudamos a reportar el reclamo, le explicamos qué paga la póliza y lo acompañamos hasta el final. **Envíenos su póliza y revisamos su cobertura.**' },
      ],
      faqTitle: 'Seguro de ATV, UTV y motos de tierra en Florida: preguntas frecuentes',
      faq: [
        { q: '¿Mi ATV necesita título en Florida?', a: 'Sí, en la mayoría de los casos. Un vehículo todoterreno comprado por un residente de Florida, o que un residente usa en terrenos públicos, debe tener título según el capítulo 317 de los Estatutos de Florida.' },
        { q: '¿Puedo andar en ATV por la calle en Florida?', a: 'Por lo general, no. La excepción es de día por un camino sin pavimentar con límite señalizado menor de 35 mph, y el condado puede no aplicarla o señalar caminos específicos. Quien maneja debe tener licencia o ser un menor supervisado, y llevar prueba de propiedad.' },
        { q: '¿Mi seguro de casa cubre mi ATV o UTV?', a: 'Muchas veces solo de forma limitada, y muchas pólizas de casa excluyen los vehículos motorizados fuera de la residencia. Envíenos su póliza de casa y le decimos qué dice.' },
        { q: '¿Los niños tienen que usar casco en un ATV en Florida?', a: 'Sí. Todo menor de 16 años que maneje o vaya en un ATV debe usar casco aprobado por el DOT y protección para los ojos.' },
        { q: '¿Un side-by-side (UTV/ROV) se cubre igual que un ATV?', a: 'La ley de Florida también trata los ROV como vehículos todoterreno, pero las pólizas pueden tratarlos distinto por el tamaño, los asientos y el uso. Díganos exactamente qué maneja y para qué lo usa.' },
        { q: '¿Me ayudan con un reclamo de todoterreno?', a: 'Sí. Llámenos o escríbanos por WhatsApp. Un agente licenciado le ayuda a reportar el reclamo y le explica cada paso en español, inglés o ruso.' },
      ],
      related: [
        { path: '/golf-cart-insurance-florida', label: 'Seguro de carrito de golf y LSV en Florida' },
        { path: '/homeowners-insurance-florida-city', label: 'Seguro de casa en Florida City' },
      ],
      sources: srcList('es', [...KEYS]),
    },
    ru: {
      metaTitle: 'Страховка квадроцикла, UTV и питбайка во Флориде',
      metaDesc: 'Правила Флориды для квадроциклов, багги и эндуро: титул, дети и шлемы, дороги общего пользования. И дыры в покрытии травм и ответственности.',
      breadcrumb: 'Страховка квадроцикла, UTV и эндуро',
      kicker: 'Страхование внедорожной техники · Вся Флорида',
      h1a: 'Страховка квадроцикла, UTV и эндуро во Флориде:',
      h1b: 'для тропы, фермы и детей, которые катаются.',
      answer: 'Внедорожная техника переворачивается, сталкивается и выбрасывает седоков, и пострадавшим может оказаться родственник или друг. Во Флориде на неё нужен **титул**, для неё действуют **особые правила на дорогах**, и её часто **не покрывает страховка дома**. Проверим ваше покрытие и объясним по-русски.',
      serviceType: 'Страхование внедорожной техники (ATV, UTV, ROV, эндуро)',
      leadLabel: 'Квадроцикл / UTV / эндуро',
      intro: [
        { type: 'p', text: 'В Южной Флориде квадроциклы и багги (side-by-side) по-настоящему работают в садах, питомниках и на больших участках, а для многих семей — от Хомстеда до Панхэндла — это ещё и выходные на природе. Но с ними связаны и серьёзные травмы: чаще всего переломы и травмы головы и шеи.' },
        { type: 'p', text: 'Ниже — правила Флориды, которые нужно знать каждому владельцу, дыры, о которых семьи узнают слишком поздно, и вопросы о покрытии. Простыми словами и со ссылками на закон.' },
      ],
      factsTitle: 'Внедорожная техника: что говорят цифры',
      facts: [
        { value: '~102 000', text: 'обращений в отделения неотложной помощи в год в США — травмы на внедорожной технике (средняя оценка за 2019–2023 годы).', source: u('cpscOhv') },
        { value: '107', text: 'зарегистрированных смертей на внедорожной технике во Флориде за 2019–2021 годы — шестой показатель среди штатов.', source: u('cpscOhv') },
        { value: '34%', text: 'травм на внедорожной технике, с которыми обращались в неотложку в 2023 году, — голова и шея; 29% — переломы.', source: u('cpscOhv') },
        { value: '16', text: 'До этого возраста каждый, кто едет на квадроцикле во Флориде, обязан быть в шлеме по стандарту DOT и в защите для глаз.', source: u('s316_2074') },
      ],
      figureAlt: 'Инфографика. Основы для внедорожной техники во Флориде: на технику, купленную жителем Флориды или используемую на государственных землях, нужен титул; до 16 лет — шлем и защита для глаз; квадроциклам нельзя на дороги общего пользования, кроме дневной езды по грунтовым дорогам с ограничением скорости ниже 35 миль в час, если округ не решил иначе. Помочь могут ответственность, медицинские расходы и ущерб технике — в зависимости от полиса.',
      figureCaption: 'Правила — ст. 316.2074, 316.2123 и глава 317 Законов Флориды. Округа могут устанавливать другие правила для дорог.',
      gapsTitle: 'Где владельцы внедорожной техники остаются без защиты',
      gaps: [
        { h: 'Травмирован друг или родственник', p: 'Пострадать может кто-то из знакомых владельца: пассажир, соседский ребёнок, двоюродный брат на одолженной машине. Обычно тут работают ответственность и медицинские расходы.' },
        { h: 'Страховка дома заканчивается у забора', p: 'Многие полисы на дом ограничивают или исключают моторную технику, особенно за пределами участка. Прочитайте раздел о моторных транспортных средствах, прежде чем на него рассчитывать.' },
        { h: 'Угон и ущерб от шторма', p: 'Квадроцикл и UTV легко погрузить и украсть, а сарай в ураган — не гараж. Покрытие ущерба технике — отдельное решение.' },
      ],
      coverageTitle: 'О каких покрытиях спросить для квадроцикла, UTV или эндуро',
      coverage: [
        { h: 'Ответственность (liability)', p: 'Травмы и ущерб, причинённые другим вами или тем, кого вы пустили за руль, в пределах лимитов, плюс юридическая защита.' },
        { h: 'Медицинские расходы', p: 'Помогает с лечением вас и ваших пассажиров, независимо от вины.' },
        { h: 'Collision и comprehensive', p: 'Ущерб технике при опрокидывании или столкновении, угоне, пожаре, наводнении или от упавшего дерева.' },
        { h: 'Аксессуары и доп. оборудование', p: 'Лебёдки, отвалы, фары, багажники и тюнинг — если указаны или включены.' },
        { h: 'Водитель без страховки (UM)', p: 'Помогает, если вас травмировал водитель без страховки, — там, где полис это предлагает.' },
        { h: 'Прицеп', p: 'Прицеп, на котором вы возите технику, — если включён.' },
      ],
      coverageNote: 'Это общие описания. Наличие покрытий, лимиты и исключения зависят от конкретного полиса.',
      body: [
        { type: 'h2', text: 'Что во Флориде считается внедорожной техникой' },
        { type: 'p', text: 'Флорида относит к внедорожной технике (off-highway vehicles) **квадроциклы (ATV), двухместные ATV, ROV (багги side-by-side) и внедорожные мотоциклы (эндуро, питбайки)**, если они используются вне дорог и не зарегистрированы для езды по шоссе ([ст. 317.0003](https://www.flsenate.gov/Laws/Statutes/2026/317.0003)). Для закона о безопасности ATV — это внедорожная машина шириной не больше 55 дюймов и сухим весом не больше 1 500 фунтов, сделанная для отдыха, на трёх или более внедорожных шинах ([ст. 316.2074](https://www.flsenate.gov/Laws/Statutes/2026/316.2074)).' },
        { type: 'h2', text: 'Титул: да, он нужен и на квадроцикл' },
        { type: 'p', text: 'Внедорожная техника, купленная жителем Флориды или принадлежащая жителю и используемая на государственных землях Флориды, должна иметь **титул** по главе 317. При продаже нужно передать титул с заполненной передачей права собственности ([ст. 317.0006](https://www.flsenate.gov/Laws/Statutes/2026/317.0006)). Кроме того, с титулом гораздо проще доказать угон.' },
        { type: 'h2', text: 'Дети, шлемы и дороги общего пользования' },
        { type: 'ul', items: [
          'Каждый **младше 16 лет**, кто управляет квадроциклом или едет на нём, обязан быть в шлеме по стандарту DOT и в защите для глаз ([ст. 316.2074](https://www.flsenate.gov/Laws/Statutes/2026/316.2074)).',
          'Если в аварии кто-то погиб или получил травму, по которой его лечил врач, каждый водитель квадроцикла обязан сообщить об аварии.',
          'Квадроциклам **нельзя на дороги общего пользования**, кроме **дневной езды по грунтовой дороге с ограничением скорости ниже 35 миль в час** ([ст. 316.2123](https://www.flsenate.gov/Laws/Statutes/2026/316.2123)).',
          'Округ может голосованием отменить это исключение или, наоборот, назначить конкретные грунтовые дороги для дневной езды на ATV.',
          'Там, где это разрешено, водитель должен иметь **права** либо быть несовершеннолетним под прямым присмотром водителя с правами и по требованию полиции показать **документ о праве собственности**.',
        ] },
        { type: 'callout', title: 'Прежде чем дать покататься', text: 'Одолженный квадроцикл с пассажиром — частый сценарий серьёзной травмы. Прежде чем отдать ключ, проверьте, покрывает ли полис других водителей и пассажиров.' },
      ],
      checklistTitle: 'Короткая проверка для каждой единицы техники',
      checklist: [
        'Есть ли на каждую машину **титул**, и вписана ли она в полис, а не только «в расчёте» на страховку дома?',
        'Покрывает ли полис **других водителей**, которых вы пускаете, и **пассажиров**?',
        'Есть ли покрытие **медицинских расходов** и на какую сумму?',
        'Достаточны ли **лимиты ответственности** для иска за травму?',
        'Указаны ли **лебёдки, отвалы, фары и другое доп. оборудование**?',
        'Используете технику **для работы на ферме или в бизнесе**? Скажите агенту: от этого может зависеть нужное покрытие.',
      ],
      agentTitle: 'Личный агент, когда это важнее всего: при страховом случае',
      agent: [
        { type: 'p', text: 'M&K Agency — семейное агентство во Флорида-Сити, посреди фермерского юга округа Майами-Дейд: больше 5 000 клиентов по всей Флориде и команда из 12 человек, которые говорят по-русски, по-английски и по-испански.' },
        { type: 'p', text: 'После опрокидывания, угона или шторма позвоните или напишите нам. Поможем заявить убыток, объясним, что платит полис, и будем рядом до конца урегулирования. **Пришлите полис — мы проверим ваше покрытие.**' },
      ],
      faqTitle: 'Страховка квадроцикла, UTV и эндуро во Флориде: частые вопросы',
      faq: [
        { q: 'Нужен ли титул на квадроцикл во Флориде?', a: 'Да, в большинстве случаев. Внедорожная техника, купленная жителем Флориды или используемая жителем на государственных землях, должна иметь титул по главе 317 Законов Флориды.' },
        { q: 'Можно ли ездить на квадроцикле по дороге во Флориде?', a: 'Как правило, нет. Исключение — дневная езда по грунтовой дороге с ограничением скорости ниже 35 миль в час, а округ может это исключение отменить или назначить конкретные дороги. Водитель должен иметь права или быть несовершеннолетним под присмотром и иметь при себе документ о праве собственности.' },
        { q: 'Покрывает ли квадроцикл или UTV моя страховка дома?', a: 'Часто лишь ограниченно, а многие полисы на дом исключают моторную технику за пределами участка. Пришлите нам полис на дом — скажем, что там написано.' },
        { q: 'Нужен ли детям шлем на квадроцикле во Флориде?', a: 'Да. Каждый младше 16 лет, кто управляет квадроциклом или едет на нём, обязан быть в шлеме по стандарту DOT и в защите для глаз.' },
        { q: 'Багги (UTV/ROV) страхуется так же, как квадроцикл?', a: 'Закон Флориды тоже относит ROV к внедорожной технике, но полисы могут рассматривать их иначе из-за размера, числа мест и способа использования. Расскажите, на чём именно и как вы ездите.' },
        { q: 'Помогаете ли вы со страховыми случаями по внедорожной технике?', a: 'Да. Позвоните или напишите в WhatsApp. Лицензированный агент поможет заявить убыток и объяснит каждый шаг по-русски, по-английски или по-испански.' },
      ],
      related: [
        { path: '/golf-cart-insurance-florida', label: 'Страховка гольф-кара и LSV во Флориде' },
        { path: '/homeowners-insurance-florida-city', label: 'Страховка дома во Флорида-Сити' },
      ],
      sources: srcList('ru', [...KEYS]),
    },
  },
};
